### DISCUSSION TITLE
Settings page - We need help with translations

### DISCUSSION THREAD

**Discussion by edwardtfn** [Blackymas/NSPanel_HA_Blueprint#1002] [General]
Now I need your help to translate the Settings page:

```yaml
    en: #English
      settings:
        reboot: Reboot
        sleep: Sleep
        brightness: Brightness
        bright: Bright
        dimming: Dimming #Not in use at the moment
        dim: Dim
```
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/82c30f37-83bf-49d6-bb75-8b4bd3c8eebb)
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/146490d9-fae6-4a06-9fe0-0a1b1b9442cd)

Edit: Updated pic with new page format

**Comment by pbranly** [comment]
Hi 
What difference do you make between brightness and bright ? 
I can’t find the difference in the menu nor in English 
Phil

**Reply by edwardtfn** [reply]
That is not in the current implementation, but I'm looking for a way to make that page more clear and I ended up ith this need for the new string.

Basically, the panel support two distinct "Brightness" levels, one is the "Bright" mode, when you are playing with the panel, and after sometime without a touch it will go to the "Dim" mode, where the "Brightness" is lower than the "Bright" mode, indicating the panel is about to sleep (or simply saving some energy).
"Dimming" is used nowk but I'm not sure if I will use this string in the new implementation. But just in case, I'm asking for help with all the possibilities (and maybe the screen will end up just like it is today).

**Reply by pbranly** [reply]
Well understood…
This is not easy to translate in French without long names 
Equivalent in English could be 
Full  brightness ——> Luminosité 
Idle brightness ——> Veille 
The screen would be self understandable
Any other French users ?

**Reply by scoudibou** [reply]
I understand the dim mode like backlight intentisity and the brightness like ...brightness. But i am perhaps wrong ? If not backlight in french => Rétroéclairage

**Reply by pbranly** [reply]
Hi it could be rétroéclairage but this would be too technical I think
I would prefer luminosité that is more user friendly 
But there are surely other French user points of view
Good debate !
Phil

**Reply by edwardtfn** [reply]
In the end I don't have the strings for French. 😞 
Any suggestion based on the updated screenshots?

**Reply by scoudibou** [reply]
fr: #French
      settings:
        reboot: Redémarrage
        sleep: Veille
        brightness: Luminosité
        bright: Clair
        dimming: Atténuation #Not in use at the moment
        dim: Sombre

**Reply by edwardtfn** [reply]
Merci!

**Reply by edwardtfn** [reply]
It would be nice if you also help with #940 for the strings on the Alarm page.

**Reply by scoudibou** [reply]
@edwardtfn I have installed V4 version and switch it to french, it's missing a "é" at "Luminosité" (brightness)

**Reply by edwardtfn** [reply]
mmmm
The "é" is there in the code:
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/470d00e2-afe0-498d-9206-58dac6f5f94f)
Either the font isn't including this char (unlikely) or the string exceeds the space available. For this second case, do you have any alternative that is shorter?
I will take a look tomorrow.

**Reply by edwardtfn** [reply]
Ok, I found the issue and have a fix already on `dev`.

**Comment by quenthal** [comment]
Good discussion. If we are to think bright as preset what to use when we want preconfigured/default max brightness and dim similarly, as edwardtfn explained, my Finnish translations would be as follows:

fi: #Finnish
      settings:
        reboot: Uudelleenkäynnistys
        sleep: Lepotila
        brightness: Kirkkaus
        bright: Kirkas
        dimming: Himmennys
        dim: Himmeä

**Reply by edwardtfn** [reply]
Do you have a shorter version for "Reboot"?
Otherwise I can try to make a bit more space, but not sure it will fit that long word.

And should I use "Himmeä" as that last line? On that place is almost impossible to find additional space.

![IMG_5191](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/ab9d4912-04bf-402f-b151-e62bc14a28f4)

**Reply by quenthal** [reply]
Finnish is sometimes difficult language to get short words out of... :)

Uudelleenkäynnistys could be shortened as "Uudelleenkäynn." (if there is room for that dot), 2nd best would be "Uud.käynnistys", lastly "Uud.käynn.". Then there is this non-official translation "Boottaus" (but I'd prefer not). 

If in current version there is this title (Brightness, Kirkkaus in Finnish) before those two sliders, you can use "Kirkas" and "Himmeä" for them.

**Reply by edwardtfn** [reply]
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/7b18aeb9-8250-4e03-9ab4-62532de79687)
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/d7dcd512-8638-4966-94ae-cafe20211cd8)

Please let me know how you liked this or if I should change something.

**Comment by MaiPiu** [comment]
Hello @edwardtfn 
If you want I can translate it into Italian. Let me know if you have more strings to translate.

    en: #Italian
      settings:
        reboot: Riavvio
        Sleep: Sleep <-This can stay like this, otherwise it would be "Modaità Risparmio" (that means "low energy mode")
        brightness: Brightness <- Luminosità
        bright: Bright <- Luminosità ( If the meaning is "Bright Mode" you can also say "Modalità Luminosa)
        dimming: Dimming <- Regolazione 
        dim: Dim <- Reg. :)
        
       Btw if the goal is to be able to define two different brightness levels for the two different profiles, I suggest using a single "Brightness" (it: Luminosità) header (be it the page name or the function that is pressed to get to the page). The two sliders will then be called "In use"(In uso) " Sleep Mode"(Risparmio Energetico)

**Reply by edwardtfn** [reply]
Grazie mille!!

> Btw if the goal is to be able to define two different brightness levels for the two different profiles, I suggest using a single "Brightness" (it: Luminosità) header (be it the page name or the function that is pressed to get to the page). The two sliders will then be called "In use"(In uso) " Sleep Mode"(Risparmio Energetico)

This is my idea in the end, but that will require a redesign of that page and I don't wanna do this before the release of v4.0, so I'm trying to translate the strings for how it is now and anticipate the future a bit, but maybe it was a bit confusing the way I've asked for.

This is how it is looking with the current implementation (using your strings):
![IMG_5215](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/3684d85a-d0ab-4887-b42b-3e35ceec95fd)


> If you want I can translate it into Italian. Let me know if you have more strings to translate.

These are all the strings we have at this moment:
```yaml
    it: #Italian
      weekdays:
        mon: Lunedì
        tue: Martedì
        wed: Mercoledì
        thu: Giovedì
        fri: Venerdì
        sat: Sabato
        sun: Domenica
      weekdays_short:
        mon: Lun
        tue: Mar
        wed: Mer
        thu: Gio
        fri: Ven
        sat: Sab
        sun: Dom
      months:
        jan: Gennaio
        feb: Febbraio
        mar: Marzo
        apr: Aprile
        may: Maggio
        jun: Giugno
        jul: Luglio
        aug: Agosto
        sep: Settembre
        oct: Ottobre
        nov: Novembre
        dec: Dicembre
      months_short:
        jan: Gen
        feb: Feb
        mar: Mar
        apr: Apr
        may: Mag
        jun: Giu
        jul: Lug
        aug: Ago
        sep: Set
        oct: Ott
        nov: Nov
        dec: Dic
      relative_day:
        today: Oggi
        tomorrow: Domani
        in_2_days: in 2 giorni
        in_3_days: in 3 giorni
        in_4_days: in 4 giorni
      climate:
        states:
          "on": on
          "off": off
        heat: caldo
      please_confirm: Confermare
      unavailable: Unavailable
      no_name: No name
      alarm:
        home: Casa
        away: Fuori
        night: Notte
        vacation: Vacanza
        bypass: Bypass
        disarm: Disarmato
      settings:
        reboot: Riavvio
        sleep: Modaità Risparmio
        brightness: Luminosità
        bright: Luminosità #( If the meaning is "Bright Mode" you can also say "Modalità Luminosa)
        dimming: Regolazione
        dim: Reg.
```
Please feel free to propose any change/fix.

**Reply by edwardtfn** [reply]
The way this screen was designed for the US model works better with those long words, although the string still limited (an easy fix in this case):
![IMG_5216](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/6dac6f82-76ca-4b92-a3c1-632786e4863e)

I will take a look for a way to change the EU version towards this format.

**Comment by MaiPiu** [comment]
Ok now i get the point:

My 2 cent:

Change: 
from: "Modalità Risparmio" to: "Modalità ECO"
from: "Luminosità" to: "In Uso"
From: "Regolazione" to: "Eco Mode"

in this way the word "Brightness" is never mentioned but is clearly explained by the icon, and we use the words to better describe the related usage scenarios.

Regarding the other strings, a little more context would be needed, in the meantime I'll add a few notes:

 in_2_days: in 2 giorni (Maybe you can also say Dopodomani, literally means "The day after tomorrow)
 
 On and Off are widely used in Italian, but if we wanted to be precise: On = Acceso Off = Spento.
 
 Heat is caldo, but if the meaning is heating the translation is "Riscaldamento"; the same for Cool = Freddo, Cooling = "Raffrescamento"
 
Another doubt about the alarm for the "away" if the meaning is away from home, the correct translation would be "Fuori di Casa"
 
As soon as you release the new version, I install it so I can give you some more feedback as a user.
For now, I have a US model and I'm waiting for the landscape version :).
Don't hesitate to ask if you need more information!
Thanks a lot!
Beppe

**Reply by edwardtfn** [reply]
> Change:
from: "Modalità Risparmio" to: "Modalità ECO"
from: "Luminosità" to: "In Uso"
From: "Regolazione" to: "Eco Mode"

Note that "Sleep mode" is deferent than "Dimming". During sleep, the panel isn't showing anything on it's screen, while dimming you can see the elements in the screen, but dimmed indicating the panel is about to sleep after some time of inactivity.

> On and Off are widely used in Italian, but if we wanted to be precise: On = Acceso Off = Spento.
>
> Heat is caldo, but if the meaning is heating the translation is "Riscaldamento"; the same for Cool = Freddo, Cooling = "Raffrescamento"

I believe o v3.4 we replaced all those strings related to climate to icons, so I'm not sure those are used anywhere. I will take a look later, otherwise will clean-up those entries.

> As soon as you release the new version, I install it so I can give you some more feedback as a user.
For now, I have a US model and I'm waiting for the landscape version :).

It's already available in the `dev` branch. Hopefully we will be able to release in less than a week.

**Reply by edwardtfn** [reply]
![IMG_5218](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/53db196a-7232-4474-9e58-3d3a292f13a4)
![IMG_5219](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/65e20b62-ba75-4fd4-a755-6070b5249e23)
![IMG_5220](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/c0ae7914-da95-44bd-954e-b61114138c2a)

**Comment by prigorus** [comment]
si: #Slovenian
      settings:
        reboot: Ponovni zagon
        sleep: Spanje
        brightness: Osvetlitev
        bright: Svetlo
        dimming: Zatemnitev
        dim: Temno

**Reply by edwardtfn** [reply]
Thanks!!
Could you please help also with translations for page Alarm on #940?

**Reply by edwardtfn** [reply]
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/e048e2b7-c997-4421-a7e7-681540832154)
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/1c2bf346-efbd-4c46-9618-042e520cf74d)

**Reply by prigorus** [reply]
Looks great! I would just change the dim translation:

si: #Slovenian
  settings:
    reboot: Ponovni zagon
    sleep: Spanje
    brightness: Osvetlitev
    bright: Svetlo
    dimming: Zatemnitev
    dim: Zatemnjeno

**Reply by edwardtfn** [reply]
It worked fine for US model, but not in the EU model:

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/8876f3bd-b405-4937-8625-9e3b4c27fa12)

Do you have anything shorter for that? It's fine if it takes multiple words, so we can split in two lines.

**Reply by prigorus** [reply]
I tried to find a better word but there is nothing shorter or a multiple word substitute. Please just use the first translation I posted, It is also okay.

**Comment by ktostam** [comment]
```
   pl: #Polish
      settings:
        reboot: Restartuj
        sleep: Usypianie
        brightness: Jasność
        bright: Jasny
        dimming: Ściemnianie
        dim: Przyciemniony
```

**Reply by edwardtfn** [reply]
Don't you have a shorter word for dim?

![IMG_5225](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/47580371-bbfe-4641-aedc-0392c76479ec)

**Reply by ktostam** [reply]
this translation will be better:

```
  pl: #Polish
      settings:
        reboot: Restartuj
        sleep: Usypianie
        brightness: Jasność
        bright: Jasny
        dimming: Ściemnianie
        dim: Ciemny
```

**Reply by edwardtfn** [reply]
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/5d0e5c15-876a-499e-818e-87ddc194b91f)
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/3948c219-ac5d-4dd9-9791-942b881b9b9b)

**Reply by ktostam** [reply]
looks great

**Comment by edwardtfn** [comment]
It's out for `beta` now: #1046

**Comment by joztoz** [comment]
sk: #Slovak
      settings: Nastavenia
        reboot: Reštartovať
        sleep: Spánok
        brightness: Jas
        bright: Zosvetlenie
        dimming: Stmavenie #Not in use at the moment
        dim: Stmavenie

**Reply by edwardtfn** [reply]
Thanks!!

Could you please help also with translations to Alarm page on #940?

**Comment by Lama131** [comment]
nl: #Nederlands
      settings: Instellingen
        reboot: Herstarten
        sleep: Slaap mode
        brightness: Helderheid
        bright: Helder
        dimming: Dimmen #Not in use at the moment
        dim: Gedimd

**Reply by edwardtfn** [reply]
Thanks!!
Do you mind taking a look on #940 also for translations to Alarm page, please?

**Reply by edwardtfn** [reply]
Forget it! That is already translated. ;)

**Comment by Dragonfir3** [comment]
I think that Spanish is not available:
```yaml
    es: #Spanish
      settings:
        reboot: Reiniciar
        sleep: Modo ECO
        brightness: Iluminación
        bright: Brillo
        dimming: Atenuación #Not in use at the moment
        dim: Atenuado
```
