### DISCUSSION TITLE
how to get value target_temp in HA?

### DISCUSSION THREAD

**Discussion by joztoz** [Blackymas/NSPanel_HA_Blueprint#1038] [Q&A]
Hello everyone,

I've recently made some modifications to my project and have condensed it into a single page on my Nextion display. In this updated setup, I have a component named target_temp which is now of type xFloat.

My primary objective is to monitor any changes to the value of target_temp and have these changes reflected in real-time (or near real-time) in Home Assistant. Essentially, every time the value of target_temp changes on the Nextion display, I want to see the updated value in Home Assistant.

I've tried a few methods, but I'm currently facing some challenges in achieving this seamless integration. I would greatly appreciate any guidance or suggestions on how to effectively send the xFloat value from my Nextion display to Home Assistant, preferably using ESPHome.

Thank you in advance for your assistance!

**Comment by edwardtfn** [comment]
Take a look at the page climate in any of the HMI files in this project, you will find a timer which is converting the value from a slider to a text where target temp is displayed as float.
In fact we are working with integers all the time in the panel, then we divide by 10 to display, but when we send to ESPHome we are using a json-like string, then parsing that into ESPHome and then calling the service in HA with the value converted to a float.
Well, in fact we call an event and then use a blueprint to call a service, just because ESPhome requires explicit permission to call services which will be cumbersome to some users.

Component relevant for you:
- nspanel_xx.HMI: Page climate, the slider, the target temp and the timer have all the logic
- ESPHome: text_sensor.localevent have all the logic

Take a look and let me know your questions. I will be happy to help.

**Reply by joztoz** [reply]
Hello, sorry I am newbie with this, however I need make one page termostat which will be just have same slider, time, date, weather and this all on one single home page. However Display Target Temperature is always as unknow.
what can be wrong? 
which variable is sent as Display Target Temperature?

thank you very much in advance, even for this amazing work

here is my hmi file:
[nspanel_eu.zip](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/12623466/nspanel_eu.zip)

**Comment by joztoz** [comment]
here is my new hmi file with new beta v4. However I struggeling with page timeout because when I use variables and timers and events from climate page it try to going back to home page and it takes cycle refresh. Please what I need delete to act like I am always on home page?
and still doesnt have any change on thermostat even after I set thermostat in blueprint:/ and also if I try to change value on home page it will show only 0.0 also in json log is 0.0
I let there clima page and it will not show slider or buttons, all bellow buttons are grey.
what I missing?
[nspanel_eu.zip](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/12641306/nspanel_eu.zip)

PS: now i can change value, problem was in ignoring temp_step, now i set it to default value 5 and it is as half degree.

**Reply by edwardtfn** [reply]
Hi @joztoz, my apologies, but the weekend is quite busy and I couldn't find a time to look at this. I will try to find some time tomorrow.
Are you using your HMI with the Blueprint and ESPHome from this project or are you customising everything?
What are you trying to achieve?
And could you please share some photo or video showing the screen and where you are stuck?

**Reply by joztoz** [reply]
Hello thank you very much for response. 
I am very sorry for interupting weekend:) 
however I want one page termostat to be simple just have slider at bottom and weather icon and time. Maybe one button for QR code and secret button for setting (these two I already have :)
My progress is that I getting message with set_temperature in HA but when i change thermostat in HA it will not reflect in nspanel and also other way I dont see any change in HA, it ignoring this message.


something like this image, just need control thermostat by this slider:
![IMG_8475](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/52895941/47eff6a6-6b0c-41a6-b15e-9f4353eda56e)

EDIT: Now I am able to reflect changes in HA using automation and event listener:

```
alias: slider_change
description: reflect temp in HA from NsPanel
trigger:
  - platform: event
    event_type: esphome.nspanel_ha_blueprint
    event_data:
      type: service_call
      service: climate.set_temperature
condition: []
action:
  - service: climate.set_temperature
    data:
      entity_id: climate.newtermostat_thermostat
      temperature: "{{ trigger.event.data.value }}"
``` 


but still I cannot reflect from HA in NsPanel and when it sleep it will start again on default value on slider, how can I update slider to last value?

**Reply by joztoz** [reply]
I triedn now fresh copy of dev and everything works great, but when I put slider and buttons and other logic from climate page to home page it stoped working.
thats where should I change from sending all info regarding climate to be sent to home page?

I think I have to modify the service: page_home and the associated scripts to include the climate control elements.
such as:
```
- service: page_home
  ...
  then:
    ...
    - lambda: |-
        ...
        // Add the climate control elements for the home page
        id(disp1).send_command_printf("climateslider.maxval=%i", total_steps);
        id(disp1).set_component_value("temp_offset", temp_offset);
        id(disp1).set_component_value("temp_step", temp_step);
        id(disp1).set_component_text_printf("current_temp", "%.1f°", current_temp);
        if (target_temp > -999)
        {
            float slider_val = round(((10*target_temp) - temp_offset) / temp_step);
            id(disp1).set_component_value("climateslider", slider_val);
            id(disp1).set_component_text_printf("target_temp", "%.1f°", target_temp);
        }
        ...

``` 

but how to use local yaml instead git?

**Reply by edwardtfn** [reply]
> something like this image, just need control thermostat by this slider:
![IMG_8475](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/52895941/47eff6a6-6b0c-41a6-b15e-9f4353eda56e)

This looks nice!

**Comment by edwardtfn** [comment]
>  but how to use local yaml instead git?

Create a subfolder under your local `\config\esphome` folder. Let's say you call this new folder `packages`, so it will be `\config\esphome\packages`.
Save a copy of `nspanel_esphome.yaml` on that new folder.
On the ESPHome yaml of your panel, replace the reference to the remote repository to a reference to this new file.
Something like this:
```yaml
substitutions:
  device_name: panel-name
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  nextion_update_url: "http://homeassistant.local:8123/local/nspanel/dev/nspanel_eu.tft"

packages:
  local_package: !include packages/nspanel_esphome.yaml
  #remote_package:
  #  url: https://github.com/Blackymas/NSPanel_HA_Blueprint
  #  ref: dev
  #  files:
  #    - nspanel_esphome.yaml # Core package
  #    #- nspanel_esphome_addon_climate_cool.yaml # activate for local climate (cooling) control
  #    #- nspanel_esphome_addon_climate_heat.yaml # activate for local climate (heater) control
  #  refresh: 30s
```
