### DISCUSSION TITLE
`DEV` How to update nspanel_esphome.yaml manually to version 4

### DISCUSSION THREAD

**Discussion by staxza** [Blackymas/NSPanel_HA_Blueprint#1041] [General]
Please help. How to update nspanel_esphome.yaml manually to version 4

I was able to update the blueprint and the tft 

...but I have not idea where the esphome file is to replace

**Comment by edwardtfn** [comment]
Be aware that v4.0 isn't released yet, so it still a bit buggy.

In order to use that, just edit your regular ESPHome file changing `remote_package` from `ref: main` to `ref: dev`.

Something like this:
```
substitutions:
  device_name: panel-name
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  nextion_update_url: "http://homeassistant.local:8123/local/nspanel/dev/nspanel_us_land.tft"

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: dev
    files:
      - nspanel_esphome.yaml # Core package
      #- nspanel_esphome_addon_climate_cool.yaml # activate for local climate (cooling) control
      #- nspanel_esphome_addon_climate_heat.yaml # activate for local climate (heater) control
    refresh: 30s
```
