### DISCUSSION TITLE
It is not possible to upload TFT 4.0

### DISCUSSION THREAD

**Discussion by mirosmartop** [Blackymas/NSPanel_HA_Blueprint#1076] [Q&A]
I need help, I can't control entities via the NSPanel display.
I cannot update TFT from 3.4 to 4.0

![2023-09-22 o 19 49 01](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/144331081/3f2b57d5-f53d-4066-8746-b6a01cb86fa6)

I also cannot control the buttons on the display. The icons also look different, just like in the photo

![2023-09-22 o 19 49 02](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/144331081/e463b21f-1a13-4c54-85db-fe53e95b6868)

I uploaded the file nspanel_eu.tft - v4.0 several times and nothing helped

An error also appears during automation

There's a version mismatch between NSPanel_HA_Blueprint components. Please update all the components to the same version.

    Panel: esppanel
    TFT:
    ESPHome: 4.0
    Blueprint: 4.0 (expected 4.0)

Please help
It is very important to me

I'm sorry for my english

**Comment by edwardtfn** [comment]
> I'm sorry for my english

We are all on the same boat... 😉

What happens when you try to upload the TFT? And are you sure you have the latest TFT in your http server?

**Reply by mirosmartop** [reply]
Yes, I am sure I have the latest TFT file

![obraz](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/144331081/072c8a62-f496-4a92-a002-4f820273e513)

When I upload TFT, the panel resets and shows what is shown in the photo I sent

I re-uploaded the entire SWPanel several times

Always the same effect.

I have no idea for this.....

**Reply by edwardtfn** [reply]
Its not connect to the error you described, but I can see your `nspanel_blank.tft` have an incorrect size. You probably have a corrupt file there.

But `nspanel_eu.tft` and `nspanel_us.tft` both looks right on size, so you probably those are OK.

Back to the problem on updating the TFT, could you please share here the ESPHome logs from right before you press the "Upload TFT" button to the moment the panel restarts?

**Reply by edwardtfn** [reply]
Go to Developer Tools > Services and look for service `esphome.xxxxx_upload_tft_url`, add the following as url and then press the button to call the service:

`http://192.168.60.113:8123/local/nspanel_us.tft`

**Reply by edwardtfn** [reply]
I have to go now, but looks like the problem is with the url I'm your ESPHome yaml settings. It's probably missing the `/local/` part.
You can try using that exactly same url in your computer (in a browser). If your browser cannot download it, your panel will fail downloading it. Once you finde the right url, use that to flash your panel and then try the upload again.

You already have the Blueprint and ESPHome with the latest version, so no need to reinstall those trying to resolve the problem. As soon you upload the TFT everything will work fine.

**Reply by mirosmartop** [reply]
Well, I think I found a mistake
It's hard to admit that such a small mistake can cause so many problems
/local/ 
I don't know why I didn't notice this before.
But two heads are better than one....

**Reply by mirosmartop** [reply]
Works !!!
Thank you for your help


And I have another question: how to get such a nice temperature controller?


![obraz](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/144331081/217d0605-6c63-49c7-af8e-1bb16d9709bd)

**Reply by edwardtfn** [reply]
This "climate" page was changed for a new format. We have to update the docs. :(
Where did you found that one?

**Reply by mirosmartop** [reply]
at this address

https://github.com/Blackymas/NSPanel_HA_Blueprint

**Reply by edwardtfn** [reply]
I've removed it and will be reflected in the coming release.

The new page look like this:

![2023-06-18 21 37 13](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/41958506/d558b552-e31d-4272-bce9-e65eacde6c36)

**Reply by mirosmartop** [reply]
How to get what you showed?
Where to enter and change what?
Because I posted your proposal

##### addon-configuration #####
  ## addon_climate ##
  cooler_relay: "1" #Use relay 1
  temp_units: "°F" #Temperatures in Fahrenheit
  temp_min: "40" #Min supported temperature is 40°F
  temp_max: "80" #Max supported temperature is 80°F
  temp_step: "1" #Temperature granularity is 1°F
    
  ##### CHANGE ME END #####


packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      - nspanel_esphome_addon_climate_cool.yaml # activate for local climate (cooling) control
      # - nspanel_esphome_addon_climate_heat.yaml # activate for local climate (heater) control
    refresh: 300s


but the time it takes to turn off the relay after reaching the required temperature is very long?

**Reply by edwardtfn** [reply]
> How to get what you showed?
Where to enter and change what?

On the Blueprint setting, you have an area specific for "Climate". That will be shown in the Home page (it's temperature) and clicking the value will open that page.
You can also assign a climate entity to any of the button pages or custom button at home page, and a long click will also open that page.

> but the time it takes to turn off the relay after reaching the required temperature is very long?

Try to adjust `min_off_time`, `min_run_time` and `min_idle_time`:
https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/docs/en/addon_climate.md#configuration

**Reply by mirosmartop** [reply]
Hi
I have a new problem
When I tried to charge the TFT, I waited for a very long time. 
Now I have the same problem as in the file. 
I cannot load a new TFT. 
The display shows Error

[logs_esppanel_logs(2).txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/12709666/logs_esppanel_logs.2.txt)

Any ideas

**Reply by edwardtfn** [reply]
> When I tried to charge the TFT, I waited for a very long time.

Those life-long transfers always fails at the end. It shouldn't take more than 15 to 20min, so if after half an hour it still Farr from the end, just interrupt that and try again. 😉

**Reply by edwardtfn** [reply]
The Nextion display is not connected to ESPHome:

```txt
[23:01:02][C][nextion:117]: Nextion:
[23:01:02][C][nextion:118]:   Device Model:     
[23:01:02][C][nextion:119]:   Firmware Version: 
[23:01:02][C][nextion:120]:   Serial Number:    
[23:01:02][C][nextion:121]:   Flash Size:       
[23:01:02][C][nextion:122]:   Wake On Touch:    True
...
[23:01:03][W][nextion:072]: Nextion is not connected! 
```

Power cycling your device should help with this.

**Reply by mirosmartop** [reply]
I've done it several times before, it's always the same problem. 
I also turned off the power several times. 
After a long flashing, information appears as in the picture. 

![Zdjęcie WhatsApp 2023-09-25 o 07 46 52](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/144331081/b3225b93-15ce-4b95-947c-9c240ec23907)


Any ideas

**Reply by edwardtfn** [reply]
I'm out of home now, but can take a look at this around lunch time and come back with some suggestions.

**Reply by edwardtfn** [reply]
@mirosmartop, let's go!

I'm starting this with the understanding that you already have installed a TFT from this project in this same panel before. If this is not the case, please let me know as I will probably take another direction.

So, the first problem to solve is about this "Nextion is not connected" issue. While this happens, no TFT will be transferred, so let's work on this.

I would suggest you to flash your device with this for our troubleshooting (when we get the TFT installed then you work on customizations, etc.):

```yaml
substitutions:
  ###### CHANGE ME START ######
  device_name: "YOUR_NSPANEL_NAME" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: "http://homeassistant.local:8123/local/nspanel_us.tft"
  nextion_update_blank_url: "http://homeassistant.local:8123/local/nspanel_blank.tft"

  ##### CHANGE ME END #####

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
    refresh: 300s

##### My customization - Start #####

button:
  ##### UPDATE TFT BLANK DISPLAY #####
  - name: ${device_name} DEBUG Update TFT display (blank)
    platform: template
    icon: mdi:file-sync
    id: tft_update_blank
    entity_category: config
    on_press:
      - logger.log: "Button pressed: Update TFT display (blank)"
      - binary_sensor.template.publish:
          id: nextion_init
          state: false
      - delay: 16ms
      - lambda: |-
          id(disp1)->set_tft_url("${nextion_update_blank_url}");
          id(disp1).upload_tft();

  ##### Turn the display off for 5sec before restarting ESPHome #####
  - name: ${device_name} DEBUG Restart screen
    id: debug_restart_screen
    platform: template
    entity_category: config
    internal: false
    on_press:
      - switch.turn_off: screen_power
      - delay: 5s
      - switch.turn_on: screen_power
      - button.press: restart_nspanel

##### My customization - End #####
```

As you may see, this is adding 2 custom buttons to help us during the debug phase. You should remove these customizations when you have successfully transferred the final TFT.
Please adjust the substitutions to reflect your environment. Note I've added one url for the final file (used by "Upload TFT" button) and another one for the Blank tft, as we will focus on transferring this one first during this troubleshoot and you might have to use that many times so you don't have to flash your device again every time.
The other DEBUG button is for cutting off the power of the screen for 5s, then restarting your panel, so hopefully you don't have to play with power supply.

So, I wanna you to flash this and then turn on your device and keep your eyes on the logs. If you have the message "Nextion is not connected", press the "DEBUG Restart screen" button and try again.
Once you have the Nextion display connected, press the button "DEBUG Update TFT display (blank)". It would be very useful if you can capture your logs from right before pressing this button to when the device restarts. Please share that log here.

I will wait for you now.
