### DISCUSSION TITLE
TFT transfer improvement - Calling for testers

### DISCUSSION THREAD

**Discussion by edwardtfn** [Blackymas/NSPanel_HA_Blueprint#1117] [General]
Hi, I wanna invest some time trying to improve the TFT transfer, but as this problem is not easy to replicate and I don't have it normally, I'd like some support from the you to test code from development branches (not as stable as main branch) and provide feedback.
Please let me know if you wanna join.
Thanks a lot!

*EDIT: This is obsolete. Please go to https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/1117#discussioncomment-7157615*

~I've started working on branch [tft-transfer](https://github.com/Blackymas/NSPanel_HA_Blueprint/tree/tft-transfer). If you wanna start playing my only instruction is to update the TFT before you update ESPHome, as I'm changing the transfer rate.~

**Comment by trinitrion** [comment]
I'm in. Just got another unit meant to revive de bricked device from #1000, but we can use the new one for improving the TFT upgrade first.

**Reply by edwardtfn** [reply]
If you have a bricked device I would love to hear if this new code works in that case. If you wanna try, just change `ref: main` to `ref: tft-transfer` in your ESPHome yaml.

**Comment by Mithrox** [comment]
I would absolutely like to try this unless its very complex. One of my panels is free for testing anything, and since none of them work right now (referring to the other post) I don't mind testing anything that can get them back up.

I'll give it a go and let you know.

**Comment by Mithrox** [comment]
I changed the file in ESPhome, and then used validate and install, but it did not turn out too well. I attached the logfile so you see.

[logs_nsp02_logs (2).txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/12743498/logs_nsp02_logs.2.txt)

**Reply by edwardtfn** [reply]
Your ESPHome is set to 921600bps while Nextion is set to 115200bps.

You will have to do the first transfer of the new TFT using the older baud_rate (115200bps), and then the new TFT will set Nextion to talk 921600bps, and after that you can set ESPHome to communicate at 921600bps.

You can add this to your ESPHome yaml now:

```yaml
# Set Nextion comm's baud rate to 115200 bps
uart:
  - id: !extend tf_uart
    baud_rate: 115200 # Use 115200 if you have a TFT v4.0.2 or less installed, or use 921600 if your installed TFT is v4.1 or greater
```

Then transfer the this blank tft: https://github.com/Blackymas/NSPanel_HA_Blueprint/raw/tft-transfer/custom_configuration/nspanel_blank_921600bps.tft

And then set ESPHome back to 921600bps:

```yaml
# Set Nextion comm's baud rate to 921600 bps
uart:
  - id: !extend tf_uart
    baud_rate: 921600 # Use 115200 if you have a TFT v4.0.2 or less installed, or use 921600 if your installed TFT is v4.1 or greater
```

And then you can try to transfer the new big TFT all with the higher baud rate:
- EU: https://github.com/Blackymas/NSPanel_HA_Blueprint/raw/tft-transfer/nspanel_eu.tft
- US: https://github.com/Blackymas/NSPanel_HA_Blueprint/raw/tft-transfer/nspanel_us.tft
- US Landscape: https://github.com/Blackymas/NSPanel_HA_Blueprint/raw/tft-transfer/nspanel_us_land.tft

Thanks for testing this. :)

**Reply by Mithrox** [reply]
It's tough to stop once you started, so I did test this process. Unfortunately, it just stopped on 4% this time, very quickly actually. I did not have the log window up, but I opened it after and it did give the same errors. I will do it properly again tomorrow and collect log from start.

**Reply by semakka1975** [reply]
[logs_nspanelusblueprint_logs.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/12752171/logs_nspanelusblueprint_logs.txt)
here's my logs, install from scratch of a panel flashed with tasmota. I've tried the tft-transfer files with 4.0.2 blueprint. tft upload stops and hangs at 83%
I've tried pretty much everything from [here](https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-Common-Issues-TFT-Upload) including 9 and 10

**Reply by edwardtfn** [reply]
Ok. Thanks a lot!
I will investigate it more.

**Reply by edwardtfn** [reply]
I've reverted back the `baud_rate` to `115200`. It was nice to have the transfer much faster, but in the end I think it wasn't helping, if not making it worse, and it would be cumbersome to migrate all users to the new baud rate.

**Comment by edwardtfn** [comment]
*EDIT: This is obsolete. Please go to https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/1117#discussioncomment-7157615*

So, I wanna volunteers to try another approach from @deejaybeam.
Basically, we are using another Nextion library just for TFT transfer. So you will flash your panel with this library, try to transfer TFT, then flash it back with the original code.

Please take a look at this example code:
```yaml

substitutions:
  ###### CHANGE ME START ######
  device_name: nspanel
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: "http://homeassistant.local:8123/local/nspanel_us_land.tft"
  nextion_update_blank_url: "http://homeassistant.local:8123/local/nspanel_blank.tft"

  ##### CHANGE ME END #####

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: tft-transfer
    files:
      # - nspanel_esphome.yaml # Core package
      - nspanel_esphome_upload_tft.yaml # Use only if you have issues with TFT transfer
    refresh: 300s
```

Please note that I've commented out the core package and added the upload TFT package. After TFT is transferred we have to revert it back.
Every time this changes you need to reflash your panel.

Once you have installed this, there's no integration to Home Assistant, so you will have to press the hardware buttons to transfer the TFT files or long press to call "Exit reparse" (which shouldn't be necessary unless you have Sonoff page in your screen).

I know the user experience is not the best at this moment, but we want to validate the solution before invest time in the user interface.

Please send your feedback.

And thanks again for your support.

**Reply by Azimuth0r** [reply]
First I want to thank you for all the work you do on this project!
I've always had the hardest time uploading the TFT files on my NSPanels. Today I attempted around 7 retries with failures anywhere between 0% and 85% uploaded
I tested your upload_tft above. Upon completion, the beeping stopped and my Wife, the cats and I crawled back out of our hiding spots to see a nice functioning TFT.
I pushed the original sketch and then made a change on the blueprint to get it to save and refresh. all looks great!
Edit: I used the device web interface to kick off the upload, I'm not sure which combinations of hardware buttons were supposed to work. the web interface was nice as it showed a progress percentage.

**Reply by semakka1975** [reply]
I'm not that lucky!
Since the previous exercise I think the baud rate of 921600bps messed up the screen as I can't flash anything on it. Just starts blank with message "System Data ERROR!".
I'll try some more stuff and post some logs later on.

**Reply by edwardtfn** [reply]
"System Data ERROR!" means you have transferred a corrupt file or the transfer failed.
Usually a power cycle is the best, sometimes it even come back directly with the previous TFT.
If you are having trouble installing a new TFT, try to alternate the baud rate between 115200 and 921600bps as this number have to match the one set in your last successfully transferred TFT (which I don't know).

You can do this by setting the following code in your ESPHome yaml:

```yaml
uart:
  - id: !extend tf_uart
    baud_rate: 115200 # or 921600
```

**Reply by semakka1975** [reply]
Following up on my previous message, procedure:
1-delete the device in HA and ESPHome (Save the yaml of the automation of this device to avoid re-configuring the automation with the blueprint, later!)
2-create new device in ESPHome with config:
```
substitutions:
  ###### CHANGE ME START ######
  device_name: nspanelusblueprint
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: "http://192.168.3.254:8123/local/dev/nspanel_us.tft" # URL to local tft File
  nextion_update_blank_url: "http://192.168.3.254:8123/local/dev/nspanel_blank.tft" # URL to local tft File

  ##### CHANGE ME END #####

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: tft-transfer
    files:
      # - nspanel_esphome.yaml # Core package
      - nspanel_esphome_upload_tft.yaml # Use only if you have issues with TFT transfer
    refresh: 300s
```
3-validate, create, download and flash `nspanelusblueprint-factory.bin` over serial with https://web.esphome.io/
4-start panel and access the http://panel_IP_address and "Update TFT display" from the web interface
5-logs:
```
Time	level	Tag	Message
11:56:52	[D]	[button:010]	'nspanelusblueprint Restart' Pressed.
11:56:52	[I]	[restart.button:012]	Restarting device...
11:56:52	[I]	[app:134]	Rebooting safely...
11:56:52	[D]	[esp32.preferences:114]	Saving 1 preferences to flash...
11:56:52	[D]	[esp32.preferences:143]	Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
11:56:52	[D]	[esp32.preferences:143]	Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
11:59:52	[I]	[ota:117]	Boot seems successful, resetting boot loop counter.
11:59:52	[D]	[esp32.preferences:114]	Saving 1 preferences to flash...
11:59:52	[D]	[esp32.preferences:143]	Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
12:03:20	[D]	[button:010]	'nspanelusblueprint Update TFT display' Pressed.
12:03:20	[D]	[main:592]	Button pressed: Update TFT display
12:03:20	[D]	[rtttl:038]	Playing song click1
12:03:20	[D]	[rtttl:038]	Playing song click1
12:03:20	[D]	[ledc.output:055]	Calculating resolution bit-depth for frequency 523.000000
12:03:20	[D]	[ledc.output:060]	Resolution calculated as 17
12:03:20	[D]	[nspanel_lovelace:119]	Sending: DRAKJHSUYDGBNCJHGJKSHBDN
12:03:20	[D]	[nspanel_lovelace:119]	Sending: recmod=0
12:03:20	[D]	[nspanel_lovelace:119]	Sending: recmod=0
12:03:20	[D]	[nspanel_lovelace:119]	Sending: connect
12:03:20	[D]	[nspanel_lovelace_upload:150]	Connected
12:03:20	[D]	[nspanel_lovelace_upload:156]	Requesting URL: http://192.168.3.254:8123/local/dev/nspanel_us.tft
12:03:21	[D]	[nspanel_lovelace_upload:188]	Updating Nextion
12:03:21	[D]	[nspanel_lovelace:119]	Sending: whmi-wris 7517548,921600,1
12:03:21	[C]	[uart.arduino_esp32:077]	Setting up UART...
12:03:21	[D]	[nspanel_lovelace_upload:213]	Waiting for upgrade response
12:03:23	[D]	[nspanel_lovelace_upload:218]	Upgrade response is []
12:03:23	[D]	[nspanel_lovelace_upload:223]	preparation for tft update failed 0 ""
12:03:23	[D]	[nspanel_lovelace_upload:276]	Restarting Nextion
12:03:23	[D]	[nspanel_lovelace:119]	Sending: rest
12:03:24	[D]	[nspanel_lovelace_upload:279]	Restarting esphome
12:06:25	[I]	[ota:117]	Boot seems successful, resetting boot loop counter.
12:06:25	[D]	[esp32.preferences:114]	Saving 1 preferences to flash...
12:06:25	[D]	[esp32.preferences:143]	Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
12:06:25	[D]	[esp32.preferences:143]	Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
12:18:32	[I]	[app:127]	Forcing a reboot...
12:22:00	[I]	[ota:117]	Boot seems successful, resetting boot loop counter.
12:22:00	[D]	[esp32.preferences:114]	Saving 1 preferences to flash...
12:22:00	[D]	[esp32.preferences:143]	Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
```
result: flashing tft doesn't even start
