### DISCUSSION TITLE
How to get target_temp as sensor to main screen

### DISCUSSION THREAD

**Discussion by vajkooo** [Blackymas/NSPanel_HA_Blueprint#1120] [Q&A]
I would like to ask for help. I would like to display target temp on the display as sensor. I have room_temperature which is 25.0C on the picture and I would like to show target temp 29,5C on the picture but I cannot extract target temp from the generic thermostat. Could anybody help me please? 
This is my generic thermostat code:

  - platform: generic_thermostat
    name: Detská izba
    heater: switch.switch_kurenie_reversed_detska
    target_sensor: sensor.teplota_detska_izba_temperature_sensor
    min_temp: 15
    max_temp: 27
    ac_mode: false
    target_temp: 20
    cold_tolerance: 0.3
    hot_tolerance: 0
    initial_hvac_mode: "off"
    away_temp: 16
    precision: 0.1
    target_temp_step: 0.5

Thank you and have a nice day. 

Regards Martin
![IMG_1667](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/48223856/8b16d387-acd1-4d4a-a202-dc34a857d26c)

**Comment by kroessig** [comment]
Hey, 
is the field "target_temp" with the value 20.0 your request.
If yes, create a seperate sensor, witch depends on the thermostat, like:

```
  - sensor:
      - name: "target_temp"
        unique_id: "target_temp"
        unit_of_measurement: "°C"
        state_class: "measurement"
        state: >
            {{ state_attr( 'climate.Detská izba', 'target_temp' )}}`
```
