### DISCUSSION TITLE
Change ICON based on SENSOR state.

### DISCUSSION THREAD

**Discussion by AubreyKloppers** [Blackymas/NSPanel_HA_Blueprint#1183] [Ideas]
Please could we have an option to change an ICON/ICON-COLOR based on a SENSOR state?

ICON EXAMPLE:
`icon: |-
  [[[
    if(states['sensor.<BLAH-alarm_entity-BLAH>'].state == 'Disarmed')
      return "mdi:alarm-light-off";
    else if(states['<BLAH-alarm_entity-BLAH>'].state == 'Away Armed')
      return "mdi:alarm-light";
  ]]] `

**Comment by kroessig** [comment]
in case anyone is looking for it

in HomeAssistant, create a template-Entity like

```
  - sensor:
      - name: "Symbol Batterie"
        unique_id: Symbol_Batterie
        unit_of_measurement: "%"
        state: >-
          {{ float(states('sensor.byd_battery_box_premium_hv_ladezustand')) }}
        icon: >-
          {% if float(states('sensor.solarnet_leistung_von_der_batterie')) | int(0) < -100 %}
          mdi:battery-arrow-up
          {% elif float(states('sensor.solarnet_leistung_von_der_batterie')) | int(0) > 100 %}
          mdi:battery-arrow-down
          {% else %}
          mdi:battery-60
          {% endif %} 
```
link that to your Panel and create a script, witch calls a service like:
```
alias: Farbe Batteriesymbol sinkt
sequence:
  - condition: state
    entity_id: sensor.symbol_batterie
    attribute: icon
    state: mdi:battery-arrow-down
  - service: esphome.panelwozi_set_component_color
    data:
      component: icon_top_06
      foreground:
        - 255
        - 0
        - 0
      background: []
mode: single
icon: mdi:battery-arrow-down
[...]
```

**Reply by pics195** [reply]
can you confirm that's work ? for me it doesn't.
![ESPhome](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/87615681/7b495e42-eed5-48c5-b734-f65252d02622)

**Reply by edwardtfn** [reply]
The component for value01 icon is `value01_icon`, so you should call like this:

```yaml
service: esphome.panelwozi_set_component_color
data:
  component: home.value01_icon
  foreground: [255, 0, 0]
```

And for the value itself:

```yaml
service: esphome.panelwozi_set_component_color
data:
  component: home.value01_state
  foreground: [255, 0, 0]
```

**Reply by pics195** [reply]
Thanks, that's nice.

**Reply by pics195** [reply]
Can we change the color of several icons at the same time? like this.
![Capture](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/87615681/c1112507-8b7a-4bd2-a43f-e4458d0545c5)

**Reply by edwardtfn** [reply]
Unfortunately no. But you can try to create a custom service by adding something like this in your panel's ESPHome yaml:

```yaml
api:
  services:
    - service: set_component_list_color
      variables:
        component_list: string[]
        foreground: int[]
      then:
        - lambda: |-
            for (const auto& component : component_list) {
              set_component_color->execute(component, foreground);
            }
```
Then you would call like:
```yaml
service: esphome.panelwozi_set_component_color
data:
  component_list: [ "home.value01_state", "home.value01_icon", "home.value02_state", "home.value02_icon" ]
  foreground: [255, 0, 0]
```
You might reach a limit of components you can transfer in a single call, as the package might have a size limit, so then one like this may be more efficient if you are always working with a single page:
```yaml
api:
  services:
    - service: set_component_list_color
      variables:
        page: string
        component_list: string[]
        foreground: int[]
      then:
        - lambda: |-
            for (const auto& component : component_list) {
              set_component_color->execute(page + "." + component, foreground);
            }
```
In this case your call will be like this (saving a few bits moving in your network and unloading the API a bit):
```yaml
service: esphome.panelwozi_set_component_color
data:
  page: "home"
  component_list: [ "value01_state", "value01_icon", "value02_state", "value02_icon" ]
  foreground: [255, 0, 0]
```
