### DISCUSSION TITLE
Rename NSPanel. Right procedure?

### DISCUSSION THREAD

**Discussion by xnisayx** [Blackymas/NSPanel_HA_Blueprint#1218] [Q&A] [answered]
Unfortunately, I have entered the wrong device name for 2 of my 4 panels.

What is the correct procedure if I want to rename the panels?

Is it sufficient to change the "Device_name" in the .yaml file and then reflash the file?

**Comment by edwardtfn** [comment]
> Is it sufficient to change the "Device_name" in the .yaml file and then reflash the file?

No, I believe that will fail.
You have to use the "Rename" hostname from the ESPHome dashboard (on the 3-dot menu related to your device).
Hopefully it won't complains about eh complexity of the project, but if that happens, please let me know.

**Reply by xnisayx** [reply]
I tried that already but it doesn't work. :-/![Screenshot_20231102-221829.png](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/50765521/b859fed7-65b6-44b3-a95a-da7d0f61c470)

**Comment by edwardtfn** [comment]
So, my suggestions are:

1st: Make a copy of your ESPHome yaml related to this device and store it somewhere. You will need that later.
2nd: Clean all the area related to `packages`, so you will have only `substitutions`. Please keep the older name.
3rd: Paste the following at the end of your cleaned yaml:
```yaml
esphome:
  name: ${device_name}

esp32:
  board: esp32dev

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  id: ota_std
  password: ${wifi_password}
  safe_mode: true
  reboot_timeout: 3min
  num_attempts: 3

wifi:
  networks:
    - id: wifi_default
      ssid: ${wifi_ssid}
      password: ${wifi_password}
  ap:
    ssid: "${device_name}"
    password: ${wifi_password}

captive_portal:
```
4th: Try to rename it again using the 3-dot menu
5th: After renamed, copy back your original yaml to your device.
6th: Change `device_name` in `substitutions` to the new name
7th: Flash it again

Please let us know if you had any issue with those steps.

**Reply by xnisayx** [reply]
I have worked through all the points and flashed the NS panel.

The flashing itself was successful. The name of the panel was changed. Unfortunately, the panel is now in a loop at the "Blueprint" point. I can see the following message in the ESPHome logs: "Blueprint version mismatch".

The new name is already stored in the automation for the NS panel. I have already restarted HA. Unfortunately, the error still occurs.![PXL_20231104_203835173.jpg](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/50765521/c9dd3926-994d-4e3a-b5c2-4bc10969f801)

**Reply by edwardtfn** [reply, marked as answer]
Ok. The hard part is done... 😉

The problem now is probably due to entities and services using the older names. You can either rename it one by one or try to reinstall the panel on Home Assistant with the following:
1. Go to Settings > Devices and Services > ESPHome and remove the panel for there
2. Restart Home Assistant
3. If the panel isn't automatically detected, go to Settings > Devices and Services and click to add a new integration
4. Select ESPHome as integration type
5. Type the panel's host name or its IP address (192.168.178.6)
6. Select it again in the automation

**Reply by xnisayx** [reply]
Yup, that helped. Now the name finally fits. 

You should add the steps to the wiki. I'm sure others will find it helpful too. 

Thanks for your help. :) I'll buy you some ice cream to thank you ;)

**Comment by HaiQ31** [comment]
for everyone coming here after esphome changes some stuff in the config:
change some of the lines in the code mentioned in https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/1218#discussioncomment-7466765 to
```
esphome:
  name: ${device_name}

esp32:
  board: esp32dev

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  plattform: esphome
  id: ota_std
  password: ${wifi_password}

safe_mode: 
  reboot_timeout: 3min
  num_attempts: 3

wifi:
  networks:
    - id: wifi_default
      ssid: ${wifi_ssid}
      password: ${wifi_password}
  ap:
    ssid: "${device_name}"
    password: ${wifi_password}

captive_portal:
```
that worked for me
