### DISCUSSION TITLE
Set display as a light

### DISCUSSION THREAD

**Discussion by CH-Tefi** [Blackymas/NSPanel_HA_Blueprint#1239] [Q&A]
There is a discription for "Set display as a light" [https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-Customization#set-display-as-a-light ], but `id: !extend page_changed` and `id: !extend set_brightness` doesn't exists anymore. Has anyone a solution?

many thanks

**Comment by edwardtfn** [comment]
That requires v4.1 which still in `dev`.

If you want to try dev, change `remote_package` from `ref: main` to `ref: dev` in your settings and then flash it again (wirelessly is OK).

**Reply by CH-Tefi** [reply]
thank you

**Reply by edwardtfn** [reply]
Have you tried that?

**Reply by CH-Tefi** [reply]
yes, I have. 
When I turn it as light on, the standard screen turns on. is that correct?

if (current_page->state == "screensaver") disp1->goto_page(wakeup_page_name->state.c_str());

**Reply by edwardtfn** [reply]
Yes, turning on will go to the wake-up page if the panel was sleeping.

**Reply by CH-Tefi** [reply]
ok. I understand that.
My idea was a night light for children.

**Reply by xnisayx** [reply]
@edwardtfn 
Today I tried to configure my NSPanels as "night light". (I am using v4.1.4)

Is there anything else that needs to be changed in the template besides the name?  I see the following error when I try to save the .yaml file:

`unknown tag !<!extend> (68:29)

 65 |     
 66 | script:
 67 |   # Updates the existing `page_changed` script to update th ...
 68 |   - id: !extend page_changed
----------------------------------^
 69 |     then:
 70 |       - lambda: |-`

and

`IDs must only consist of upper/lowercase characters, the underscorecharacter and numbers. The character ' ' cannot be used.`

**Reply by edwardtfn** [reply]
Could you please share the full yaml used for this? Please remove any sensitive information before sharing.

**Reply by edwardtfn** [reply]
```IDs must only consist of upper/lowercase characters, the underscorecharacter and numbers. The character ' ' cannot be used.```

Try removing blank spaces from the end of line 68.

**Reply by xnisayx** [reply]
```yaml
substitutions:

###### CHANGE ME START ######

  device_name: "nspanelwohn" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: "http://192.168.178.3:8123/local/nspanel_eu.tft" # URL to local tft File
#  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft" # URL to Github

  ##### addon-configuration #####
  ## addon_climate ##
  heater_relay: "1"
  temp_max: "28"

##### CHANGE ME END #####

##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # - nspanel_esphome_addon_climate_cool.yaml # activate for local climate (cooling) control
      - nspanel_esphome_addon_climate_heat.yaml # activate for local climate (heater) control 
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####

light:
  # Add the display as a light in Home Assistant
  - name: ${device_name} Display
    id: display_light
    icon: mdi:tablet-dashboard
    platform: monochromatic
    output: display_output
    default_transition_length: 0s
    on_turn_on:
      then:
        - lambda: |-
            ESP_LOGD("light.display_light", "Turn-on");
            if (current_page->state == "screensaver") disp1->goto_page(wakeup_page_name->state.c_str());
            timer_reset_all->execute(wakeup_page_name->state.c_str());
    on_turn_off:
      then:
        - lambda: |-
            ESP_LOGD("light.display_light", "Turn-off");
            disp1->goto_page("screensaver");

output:
  # Output required by `display_light` to send the commands to Nextion
  - id: display_output
    platform: template
    type: float
    write_action:
      - lambda: |-
          ESP_LOGV("output.display_output", "state: %f", state);
          uint8_t current_brightness = int(round(display_light->current_values.is_on() ? (display_light->current_values.get_brightness() * 100.0f) : 0.0));
          ESP_LOGV("output.display_output", "current_brightness: %i%%", current_brightness);
          set_brightness->execute(current_brightness);
    
script:
  # Updates the existing `page_changed` script to update the `display_light` status when a page changes
  - id: !extend page_changed
    then:
      - lambda: |-
          ESP_LOGD("script.page_changed(custom)", "page: %s", page.c_str());
          ESP_LOGV("script.page_changed(custom)", "is_on(): %s", display_light->current_values.is_on() ? "True" : "False");
          if (page == "screensaver" and display_light->current_values.is_on()) {
            auto call = display_light->turn_off();
            call.perform();
          } else if (page != "screensaver" and (not display_light->current_values.is_on())) {
            auto call = display_light->turn_on();
            call.perform();
          }

  # Updates the existing `set_brightness` script to update the `display_light` status when a new brightness level is set
  - id: !extend set_brightness
    then:
      - lambda: |-
          ESP_LOGD("script.set_brightness(custom)", "brightness: %i%%", brightness);
          uint8_t current_brightness = int(round(display_light->current_values.is_on() ? (display_light->current_values.get_brightness() * 100.0f) : 0.0));
          ESP_LOGV("script.set_brightness(custom)", "current_brightness: %i%%", current_brightness);
          if (brightness != current_brightness) {
            if (current_page->state != "screensaver" and brightness > 0) {
              auto call = display_light->turn_on();
              call.set_brightness(static_cast<float>(id(display_last_brightness)) / 100.0f);
              call.perform();
            } else if (display_light->current_values.is_on()) {
              auto call = display_light->turn_off();
              call.set_brightness(0);
              call.perform();
            }
          }
```

**Reply by xnisayx** [reply]
There are no spaces at the end of the line 68. :)

**Reply by edwardtfn** [reply]
I've copy/paste your code and I could compile with no issues with ESPHome 2023.12.5: [logs_virtual01_run.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/13779901/logs_virtual01_run.txt)
Which version of ESPHome are you using?

Try to clean your build files and compile it again.

**Reply by braini86** [reply]
Hi is this the (only) way to be able to have an action to turn on (wake up) the nspanel from sleep? I want to do that using a motion sensor that is just beside the nspanel.
Any help or hints very much appreciated! Thanks

**Reply by edwardtfn** [reply]
You can call the service `esphome.xxxxx_wake_up`

Something like this:
```yaml
service: esphome.office_workstation_panel_wake_up
data:
  reset_timer: true
```
