### DISCUSSION TITLE
Can I pass parameters to Scripts?

### DISCUSSION THREAD

**Discussion by LorenzKahl** [Blackymas/NSPanel_HA_Blueprint#1252] [General]
Hi, 

I had the idea to use the one of the button pages for triggering playback of some of my playlists on a Sonos player (group). I created a script which takes in a couple of parameters: 
- the playlist name 
- the media-players to be joined together as a group

Is there a way to specify the parameter values using YAML when the buttons are triggered? 
Otherwise I would have to create a dedicated script for each playlist and area.

**Comment by edwardtfn** [comment]
I'm not sure if I fully understand what you are trying to achieve.

In worse case, you can assign a script to each button and then use those scripts to pass your parameters to the other script you already have.

But try to give a bit more info. I'm probability missing something, sorry.

**Comment by LorenzKahl** [comment]
Hi, 

> In worse case, you can assign a script to each button and then use those scripts to pass your parameters to the other script you already have.

Yes, that's the same direction I was thinking ;-)

```yaml
...
    button_page04_label: SONOS
    entity25: script.1699732132436
    entity25_name: Release Radar
    entity25_icon: mdi:music-circle-outline
...
```
`script.1699732132436` will then forward to my other script `script.8263432112345` and add the mentioned params.

It would have been just awesome (and much more DRY) if the Blueprint-YAML supported something like this:
```yaml
...
    button_page04_label: SONOS
    entity25: script.8263432112345
    entity25_data:
        player: "livingroom"
        playlist: "Release Radar"
    entity25_name: Release Radar
    entity25_icon: mdi:music-circle-outline
...
```

Anyway, I'm very excited of having an easy way of starting the playback of my Sonos boxes without touching my phone.
Thanks for this great project ♥️
