### DISCUSSION TITLE
Removing unused stuff, what will I break?

### DISCUSSION THREAD

**Discussion by Linwood-F** [Blackymas/NSPanel_HA_Blueprint#1288] [Q&A]
This is partly a question and partly a discussion of philosophy.

I'm getting more and more esphome devices, more of which include shared project code. I think they quite rightly expose a LOT of sensors and information to HA, partly for ease of use and understanding especially for someone starting up, partly in case someone comes up with a creative use for them in HA, and partly for debugging.

This creates over time a massive number of HA entities, even if not frequently updated, which can add for confusion months later when you look for something.  Or not... the philosophy question perhaps is whether people prefer them.

I have been going through my own stuff and projects and trying to make them consistent for a few things I use a lot -- how it connects to the network, the API, returning wifi signal information, AP connected-to, etc.  It has some added "features" like if it picks a low signal AP even if it stays connected, after a while it reboots.  All in includes I just put in each device.  And each device enables the web server as well. 

I also have been going through and marking things I do not use as internal. If I ever need them they are on the web server.

This is by far one of the most complicated esphome projects I use, and it in turn has a long list marked internal (thank you for using ID's by the way).  Below is the list.  If anyone sees one that jumps out as "oh, the X will fail if you do that", please let me know.

On a somewhat related note, I notice this project uses device_name as opposed to friendly_name.  The (insert expletives here) esphome team that keeps screwing around with device names and how they work, MQTT, etc. has made something of a mess of naming, but it appears the future is to use friendly_name in esphome, and NOT name individual items with that prefix, and then HA adds it somewhere in the link you can't get to.  This is painful, and makes a mess (and why I frequently end up with a Water Heater Water Heater).  But it appears to be the future, so my own includes depend on it.  In this panel yaml I then set device_name to a space, and set the friendly name to the name and put it in esphome.  This appears to work, but am curious at the lack of use of friendly_name. 

Again, philosophy question.

In the below note I'm not using the relays at all, only the buttons to trigger through the blueprint.  I also have a 'standard' reboot button that is included hence restart was removed.  And again, I am NOT suggesting that the project should remove these -- quite the opposite, nice to see lots of data.  

I am perhaps asking if device_name should be friendly_name instead for consistency. 

    switch: 
      - id: !extend relay_1
        internal: true
      - id: !extend relay_2
        internal: true
      - id: !extend notification_unread
        internal: true
      - id: !extend notification_sound
        internal: true
    
    button: 
      - id: !extend restart_nspanel
        internal: true 
    
    number: 
      - id: !extend display_dim_brightness
        internal: true
      - id: !extend display_brightness
        internal: true
      - id: !extend timeout_dim
        internal: true
      - id: !extend timeout_sleep
        internal: true
      - id: !extend timeout_page
        internal: true
      - id: !extend temperature_correction
        internal: true
    
    text_sensor: 
      - id: !extend detailed_entity
        internal: true
      - id: !extend notification_label
        internal: true
      - id: !extend notification_text
        internal: true
    
    binary_sensor: 
    #   Note: cannot remove - id: !extend nextion_init as this causes issues with blueprint
      - id: !extend api_status
        internal: true
      - id: !extend right_button
        internal: true 
      - id: !extend left_button
        internal: true

**Comment by edwardtfn** [comment]
Sorry for the late reply here... it's an interesting topic...

In fact, those are the entities used by the blueprint:
```yaml
  left_button: 'binary_sensor.{{ nspanel_name }}_left_button'
  right_button: 'binary_sensor.{{ nspanel_name }}_right_button'
  nextion_inited: 'binary_sensor.{{ nspanel_name }}_nextion_display'
  currentpage: 'sensor.{{ nspanel_name }}_current_page'
  relay01_entity: 'switch.{{ nspanel_name }}_relay_1'
  relay02_entity: 'switch.{{ nspanel_name }}_relay_2'
  nspaneltemp: 'sensor.{{ nspanel_name }}_temperature'
  thermostat_embedded: 'climate.{{ nspanel_name }}_thermostat'
  detailed_entity: 'sensor.{{ nspanel_name }}_detailed_entity'
  notification_unread: 'switch.{{ nspanel_name }}_notification_unread'
```

So, making any of those internal, could affect the functionality, while all other entities can safely be made internal.
About those in use, it will depend of which functionality you are using. I would anticipate `binary_sensor.{{ nspanel_name }}_nextion_display` and `sensor.{{ nspanel_name }}_current_page` are core for the functionality of the system and probably (almost?) nothing will work without those.

I also more in favor of a clean device's page, but it's quite common to see people asking for additional sensors/controls or complaining when we remove something.
