### DISCUSSION TITLE
Can I call the home or a button page as an automation.

### DISCUSSION THREAD

**Discussion by iFrancisMe** [Blackymas/NSPanel_HA_Blueprint#1299] [General]
I would like to assign a physical button to take me to a specific page (either home or a button page). Is there a service I can call for this?

**Comment by edwardtfn** [comment]
Create a script and assign the script to your button.
On your script, you can call the page you want.

For opening a generic page, you can use service `esphome.xxxxx_send_command_printf`.
For more details: https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-HowTo---All-important-thing-you-should-know#11-call-certain-pages-directly

If you wanna open one of the detailed entity pages, use `esphome.xxxxx_open_entity_settings_page` like this:
```yaml
service: esphome.office_workstation_panel_open_entity_settings_page
data:
  page: light
  page_label: My light name
  page_icon_color: 246, 34, 27
  page_icon: \uF8DC
  entity: light.my_light
  back_page: home
```
You can find the icon's codes on this page: https://htmlpreview.github.io/?https://github.com/jobr99/Generate-HASP-Fonts/blob/master/cheatsheet.html
