### DISCUSSION TITLE
Refresh icons on home page

### DISCUSSION THREAD

**Discussion by Neohells** [Blackymas/NSPanel_HA_Blueprint#1338] [Q&A] [answered]
Hello,

I have a button to control the ventilation of my house that switches from the differents possible speeds (0,1,2,3).
It's icon is update depending on it's state.

On the nspanel, the icon is also updated but randomly after few minutes.
Can you help me and tell me if there's a way to force the refresh of the icons on the page please ?

Thank you

**Comment by edwardtfn** [comment]
There are ways to update it in an automation independently of the Blueprint. Just let me know in which screen (and if it is a button, which button) and I can help you with this.
However, I'd like to capture more details about this case so we can solve the problem in a way the Blueprint update it automatically without the need of a separated automation, so we can make more people happy. 😀
We can do both. 😉

**Comment by Neohells** [comment]
Thank you.
The button is actually set as "Custom button 03" on the home page.
The button is defined as follow :
```yaml
template:
  - button:
    - unique_id: 'Ventilation: incrémentation de la vitesse'
      name: 'Ventilation: incrémentation de la vitesse'
      icon: >-
        {% if is_state("number.technique_ventilation", "0") %}
            mdi:fan-off
        {% elif is_state("number.technique_ventilation", "1") %}
          mdi:fan-speed-1
        {% elif is_state("number.technique_ventilation", "2") %}
          mdi:fan-speed-2
        {% elif is_state("number.technique_ventilation", "3") %}
          mdi:fan-speed-3
        {% endif %}
      press:
        service: automation.trigger
        target:
          entity_id: automation.ventilation_basculement_de_la_vitesse
```
It's calling an automation that increase the value step by step on the entity number.technique_ventilation. (To be honest i don't know if it's the best either to do it in HA but it's working ;) ) 
If there are any other information I can give you to help I'll be glad to 'help', just tell me which one you need :).

**Reply by edwardtfn** [reply, marked as answer]
If you wanna use your automation to change that icon, you can call service `esphome.xxxxx_send_command_text_printf` (replace "xxxxx"  by your panel name). Something like this (you can try by going to the Service tab under Developer tools):
```yaml
service: esphome.xxxxx_send_command_text_printf
data:
  component: home.button03
  message: "\uE81C"
```
Note that the message is a coded (utf-8) char. It must be with `""` and must start with `\u` to indicate it is a utf-8 char coming (unless you want a normal char), then followed by the icon code.
You will find all the icon codes on this table: https://htmlpreview.github.io/?https://github.com/jobr99/Generate-HASP-Fonts/blob/master/cheatsheet.html

| icon | code |
| :--: | :--: |
| mdi:fan-off | E81C |
| mdi:fan-speed-1 | F471 |
| mdi:fan-speed-2 | F472 |
| mdi:fan-speed-3 | F473 |
