### DISCUSSION TITLE
addon_climate, how to use an external sensor

### DISCUSSION THREAD

**Discussion by alocin73** [Blackymas/NSPanel_HA_Blueprint#1345] [Q&A] [answered]
Hi all,
I'd like to use an external sensor instead of the embedded one.

I thought about doing it with a customization, something like:

<code> 
climate:
  - id: !extend thermostat_embedded
    sensor: "MY external sensor"
<end>

If it is the correct way, which is the correct sensor to put? 

Thank,

Nicola

**Comment by edwardtfn** [comment]
Is your external sensor phisically connected to your panel or is it integrated via Home Assistant?

**Reply by alocin73** [reply]
Hi,
it's integrated via home assistant.
The one i use as indoor sensor on the panel.

**Reply by edwardtfn** [reply]
In that case, I woukd recommend to not use the embedded thermostat (add-on climate), as that is designed to work all local and adds a lot of complexity (and memory consumption) o your ESPHome.
Instead use the [Generic Thermostat from Home Assistant](https://www.home-assistant.io/integrations/generic_thermostat/). It's quite powerful and will give all you need. Just add the related panel's relay as `heater` and your external temperature sensor as `target_sensor`. That will create a climate entity which can be assigned to your panel for control on it's screen just like if it was using the add-on.

**Reply by alocin73** [reply]
Yes, but i'd likes to use the addon because It work locally.
If it's not possibile, there is a way to pass the offset to the blueprint with an automation?
This way i don't loose the local capability, without adding complexity to the esphome.

**Reply by edwardtfn** [reply, marked as answer]
> Yes, but i'd likes to use the addon because It work locally

It isn't local if you're getting a value from Home Assistant, so in the end it makes no difference running this on Home Assistant side.

> If it's not possibile, there is a way to pass the offset to the blueprint with an automation?

You mean the temperature offset? That is possible.
The offset is defined into `number.YOUR_PANEL_NAME_temperature_correction`.
You can change it in an automation by calling the service `number.set_value`. Something like this:
```yaml
service: number.set_value
data:
  value: "-1.2"
target:
  entity_id: number.YOUR_PANEL_NAME_temperature_correction
```

> This way i don't loose the local capability, without adding complexity to the esphome.

Yeah, for this case you can have it running locally.

**Reply by alocin73** [reply]
Thanks for your help,

I ended up using this setup in configuration.yaml:

```
template:
  - sensor:
      .....
      .....
      - name: "Temperatura Media"
        unique_id: temperatura_media
        unit_of_measurement: "°C"
        state: >
          {% set camera = states('sensor.aqara_temperatura_camera') | float %}
          {% set soggiorno = states('sensor.aqara_temperatura_soggiorno') | float %}
          {{ ((camera + soggiorno) / 2) | round(1, default=0) }}
  - number:
      .....
      .....
      - name: offset_temp_nspanel
        state: >
          {% set nspanelTemp = states('sensor.nspanel_temperature') | float %}
          {% set tempMedia = states('sensor.temperatura_media') | float %}
          {% set offsetAttuale = states('number.nspanel_temperature_correction') | float %}
          {{ (tempMedia - (nspanelTemp - offsetAttuale)) | round(1, default=0) }}
        set_value:
        step: 0.1
```

And this automation:

```
alias: Imposta offset temperatura nspanel
trigger:
  - platform: state
    entity_id:
      - sensor.temperatura_media
      - sensor.nspanel_temperature
action:
  - service: number.set_value
    data_template:
      entity_id: number.nspanel_temperature_correction
      value: "{{ states('number.offset_temp_nspanel') | float }}"
mode: single
```

Nicola
