### DISCUSSION TITLE
NSPanel tft not updating

### DISCUSSION THREAD

**Discussion by pyriel800** [Blackymas/NSPanel_HA_Blueprint#1360] [Q&A] [answered]
Hi all,

I've updated the ESP in homeassistant to the latest version (11.6) but my NSpanel is now stuck at TFT 4.1 and won't update to 4.1.2.

I have:
Downloaded the tft to the config/www folder (checked this is accessible via web browser via http)
updated the blueprint
tried the upload TFT control in HA

The display will reboot and looks like it's trying to do something but just gets back to the initialising screen

Normally uploading the new TFT has worked, although in the interim I have changed the underlying HA hardware which has a new IP address. I have updated the yaml under the ESPHOME folder with the new IP for the TFT location (and restarted many things, many times!).

I'm not sure where to go from here... any help greatly appreciated!

**Comment by edwardtfn** [comment]
You can stay with TFT v4.1 with no issues. In fact the only difference is the version number reported.
This is not the case for ESPHome and Blueprint. For those I recommend you going to v4.1.2, as there are fixes on those.

Hopefully v4.2 ( not yet released) will be better with this TFT transfer.

**Reply by pyriel800** [reply]
okay, thank you for that but I'm stuck on the initialisation screen and it will not do any transfer at all for any version

**Reply by edwardtfn** [reply]
But then it is another issue.

What do you see on that screen for TFT, ESPHome and Blueprint?

**Reply by pyriel800** [reply]
It says TFT: 4.1
ESPhome and blueprint are blank

**Reply by edwardtfn** [reply]
Could you please share your ESPHome yaml here? Please make sure to hide any sensitive info.

**Reply by pyriel800** [reply]
sure. This is is the yaml for the device under esphome

```yaml
substitutions:
  ###### CHANGE ME START ######
  device_name: "nspoffice" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: "http://homeassistant.local:8123/local/nspanel_eu.tft"

  ##### addon-configuration #####
  ## addon_climate ##
  # addon_climate_heater_relay: "1" # possible values: 1/2

  ##### CHANGE ME END #####

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # - nspanel_esphome_advanced.yaml # activate advanced (legacy) elements - can be useful for troubleshooting
      # - nspanel_esphome_addon_climate_cool.yaml # activate for local climate (cooling) control
      # - nspanel_esphome_addon_climate_heat.yaml # activate for local climate (heater) control
    refresh: 300s
esp32:
  framework:
    type: esp-idf

##### My customization - Start #####
##### My customization - End #####
```

**Reply by edwardtfn** [reply, marked as answer]
Please try changing the framework pike this:

```yaml
esp32:
  framework:
    type: arduino
```

But before installing, in your ESPHome dashboard, click the 3-dot menu related to your panel and click "Clean build files".
