### DISCUSSION TITLE
Incorrect time

### DISCUSSION THREAD

**Discussion by Churator** [Blackymas/NSPanel_HA_Blueprint#1389] [General]
Hi

My panel show incorrect time, actually 2 hours earlier, so proably timezone thing, but everywhere I look at HA its fine.
I do see that v4 changed the time to be local, but not sure where/how to configure that to be correct.

**Comment by edwardtfn** [comment]
Please take a look at this: https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-Customization#enforce-time-zone

**Comment by DonGuaja** [comment]
Hi Team. I agree with @Churator. ESP Home detected my timezone correctly.

INFO Detected timezone 'America/Santiago'
[10:06:23][C][homeassistant.time:011]:   Timezone: '<-04>4<-03>,M9.1.6/24,M4.1.6/24'

However, the display time is still 7 hours ahead of my timezone in Santiago.

I also tried to enforce the timezone on ESPHome like this, but it didn't work.

```yaml
time:
- id: !extend time_provider
timezone: "America/Santiago"
```

What am I missing?

**Reply by Churator** [reply]
the solution suggested by @edwardtfn  worked for me.

**Reply by edwardtfn** [reply]
Please try this and let me know the results (as it probably can be improved):

```yaml
time:
  - id: !extend time_provider
    timezone: "<-04>4<-03>,M9.1.6/24,M4.1.6/24"
```

**Reply by DonGuaja** [reply]
still shown the wrong time.

the longs show
[13:09:12][C][homeassistant.time:010]: Home Assistant Time:
[13:09:12][C][homeassistant.time:011]:   Timezone: '<-04>4<-03>,M9.1.6/24,M4.1.6/24'

**Reply by edwardtfn** [reply]
How much is the offset? I mean which time is showing and which time it should be showing?

**Reply by edwardtfn** [reply]
And what about this?

```yaml
time:
  - id: !extend time_provider
    timezone: "GMT-03"
```

**Reply by DonGuaja** [reply]
time:
  - id: !extend time_provider
    timezone: "GMT+03"

This fix to my time zone, but is weird as i'm on GTM-3

**Reply by edwardtfn** [reply]
Looks like this is an issue with ESPHome: https://github.com/esphome/issues/issues/3769

**Reply by erikklavora** [reply]
I had to put in GMT-1 even though I'm in Europe/Ljubljana or GMT+1... my HA is set up as Europe/Rome, but if I don't enforce the time in detects as CET-1... strange

**Comment by tomh482** [comment]
Hi.
  I used this instead. Now it is corrent.

```yaml
time:
  - id: time_provider
    platform: sntp
    timezone: Europe/Bratislava
    servers:
     - 0.pool.ntp.org
     - 1.pool.ntp.org
     - 2.pool.ntp.org
 ```

**Reply by edwardtfn** [reply]
Have you edited the main file where all the components are?

I'm asking as if you wanna add this as a customization in your device's yaml you should use `!extend`, no? Like this:

```yaml
time:
  - id: !extend time_provider
    platform: sntp
    timezone: Europe/Bratislava
    servers:
     - 0.pool.ntp.org
     - 1.pool.ntp.org
     - 2.pool.ntp.org
 ```

**Reply by tomh482** [reply]
Actually I'am noob, and I downloaded whole code to esphome and build it locally.
I was searched a lot, and nothing helped to me.
I will try it with !extend. Thanks for advise

**Reply by edwardtfn** [reply]
You don't need the full code. Just replace all of that by this (adjusting the substitutions in the top and add that in customization area):

```yaml

substitutions:
  ###### CHANGE ME START ######
  device_name: "YOUR_NSPANEL_NAME" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: "http://homeassistant.local:8123/local/nspanel_eu.tft"
  nextion_blank_url: "http://homeassistant.local:8123/local/nspanel_blank.tft"

  ##### addon-configuration #####
  ## addon_climate ##
  # addon_climate_heater_relay: "1" # possible values: 1/2

  ##### CHANGE ME END #####

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # - advanced/esphome/nspanel_esphome_advanced.yaml # activate advanced (legacy) elements - can be useful for troubleshooting
      # - nspanel_esphome_addon_climate_cool.yaml # activate for local climate (cooling) control
      # - nspanel_esphome_addon_climate_heat.yaml # activate for local climate (heater) control
    refresh: 300s

esp32:
  framework:
    type: esp-idf

##### My customization - Start #####

# Use sntp as time source
time:
  - id: !extend time_provider
    platform: sntp
    timezone: Europe/Bratislava
    servers:
     - 0.pool.ntp.org
     - 1.pool.ntp.org
     - 2.pool.ntp.org

##### My customization - End #####
```
