### DISCUSSION TITLE
Show Media Player

### DISCUSSION THREAD

**Discussion by jonkorn4** [Blackymas/NSPanel_HA_Blueprint#1433] [Q&A]
I have a script that plays a Spotify Playlist on a specific device.   I cannot for the life of me figure out how to show the media player on the NSpanel when the script is executed.    Any help would be greatly appreciated.   

Script: 
alias: Post
sequence:
  - service: spotcast.start
    data:
      uri: spotify:playlist:5WsVmOJqkDvdYdtwzS4FBc
      force_playback: true
      start_volume: 30
      device_name: Basement
mode: single
icon: mdi:spotify

**Comment by edwardtfn** [comment]
Try this (replace the values accordingly):

```yaml
service: esphome.xxxxx_open_entity_settings_page
data:
  page: media_player
  page_label: My Spotify player
  page_icon: '\uE4C6'
  page_icon_color:
    - 255
    - 0
    - 0
  entity: media_player.office_alexa
  back_page: home
```

You will find a list of icons here: https://htmlpreview.github.io/?https://github.com/jobr99/Generate-HASP-Fonts/blob/master/cheatsheet.html
Color is RGB.

**Comment by jonkorn4** [comment]
Thanks,    I cannot get past the "page_icon_color)   
I keep getting "expected a list for dictionary value @ data['page_icon_color']"

I have tried using:
 Hex 
RBG(255,0,0) 
255 0 0
(255,0,0) 

The script I am using: 
```yaml
alias: Post
sequence:
  - service: spotcast.start
    data:
      uri: spotify:playlist:5WsVmOJqkDvdYdtwzS4FBc
      force_playback: true
      device_name: Basement
  - service: esphome.kornsnspan_open_entity_settings_page
    data:
      page: media_player
      page_label: My Spotify Player
      entity: media_player.office_alexa
      back_page: home
      page_icon: \uF590
      page_icon_color: 255,0,0
mode: single
icon: mdi:spotify
```
