### DISCUSSION TITLE
Chinese, Japanese and Korean (CJK) languages - We need help with translations

### DISCUSSION THREAD

**Discussion by edwardtfn** [Blackymas/NSPanel_HA_Blueprint#1447] [General]
Hello,

We're excited to announce that version 4.2 will include support for CJK languages. However, we need assistance in reviewing and refining the translations.

Shortly, I will share the strings that have already been integrated into the blueprint. We welcome your feedback on these, as well as your help in completing any strings that are currently missing translations.

For those interested in experiencing the new version firsthand, please switch to the `dev` branch. There, you'll find the CJK TFT files in the `/advanced/hmi` folder.

For a more in-depth understanding and to join the ongoing conversation, feel free to visit the discussion thread at #1359.

We greatly appreciate any support and contributions from the community. Thank you!

**Comment by edwardtfn** [comment]
```yaml
    ja:     # Japanese
      weekdays:
        mon: 月曜日
        tue: 火曜日
        wed: 水曜日
        thu: 木曜日
        fri: 金曜日
        sat: 土曜日
        sun: 日曜日
      weekdays_short:
        mon: 月
        tue: 火
        wed: 水
        thu: 木
        fri: 金
        sat: 土
        sun: 日
      months:
        jan: 1月
        feb: 2月
        mar: 3月
        apr: 4月
        may: 5月
        jun: 6月
        jul: 7月
        aug: 8月
        sep: 9月
        oct: 10月
        nov: 11月
        dec: 12月
      months_short:
        jan: 1月
        feb: 2月
        mar: 3月
        apr: 4月
        may: 5月
        jun: 6月
        jul: 7月
        aug: 8月
        sep: 9月
        oct: 10月
        nov: 11月
        dec: 12月
      relative_day:
        today: 今日
        tomorrow: 明日
        in_2_days: 明後日
        in_3_days: 3日間
        in_4_days:  4日間
      climate:
        states:
          "on": 入
          "off": 切
        heat: 温水器
      please_confirm: ご確認下さい
      unavailable: 無効
      no_name: 名称未設定 
      alarm:
        home: Home
        away: Away
        night: Night
        vacation: Holiday
        bypass: Custom bypass
        disarm: Disarm
      settings:
        reboot: Reboot
        sleep: Sleep mode
        brightness: Brightness
        bright: Bright
        dimming: Dimming
        dim: Dim
      meridiem:
        am: AM
        pm: PM
```

**Comment by edwardtfn** [comment]
```yaml
    ko:     # Korean
      weekdays:
        mon: Monday
        tue: Tuesday
        wed: Wednesday
        thu: Thursday
        fri: Friday
        sat: Saturday
        sun: Sunday
      weekdays_short:
        mon: 월
        tue: 화
        wed: 수
        thu: 목
        fri: 금
        sat: 토
        sun: 일
      months:
        jan: 1월
        feb: 2월
        mar: 3월
        apr: 4월
        may: 5월
        jun: 6월
        jul: 7월
        aug: 8월
        sep: 9월
        oct: 10월
        nov: 11월
        dec: 12월
      months_short:
        jan: 1월
        feb: 2월
        mar: 3월
        apr: 4월
        may: 5월
        jun: 6월
        jul: 7월
        aug: 8월
        sep: 9월
        oct: 10월
        nov: 11월
        dec: 12월
      relative_day:
        today: 오늘
        tomorrow: 내일
        in_2_days: 2일
        in_3_days: 3일
        in_4_days: 4일
      climate:
        states:
          "on": "on"
          "off": "off"
        heat: 열
      please_confirm: 확인 부탁드립니다
      unavailable: 불가능
      no_name: 공백
      alarm:
        home: Home
        away: Away
        night: Night
        vacation: Holiday
        bypass: Custom bypass
        disarm: Disarm
      settings:
        reboot: Reboot
        sleep: Sleep mode
        brightness: Brightness
        bright: Bright
        dimming: Dimming
        dim: Dim
      meridiem:
        am: AM
        pm: PM
```

**Reply by lavi02** [reply]
```yaml
    ko:     # Korean
      weekdays:
        mon: 월요일
        tue: 화요일
        wed: 수요일
        thu: 목요일
        fri: 금요일
        sat: 토요일
        sun: 일요일
      weekdays_short:
        mon: 월
        tue: 화
        wed: 수
        thu: 목
        fri: 금
        sat: 토
        sun: 일
      months:
        jan: 1월
        feb: 2월
        mar: 3월
        apr: 4월
        may: 5월
        jun: 6월
        jul: 7월
        aug: 8월
        sep: 9월
        oct: 10월
        nov: 11월
        dec: 12월
      months_short:
        jan: 1월
        feb: 2월
        mar: 3월
        apr: 4월
        may: 5월
        jun: 6월
        jul: 7월
        aug: 8월
        sep: 9월
        oct: 10월
        nov: 11월
        dec: 12월
      relative_day:
        today: 오늘
        tomorrow: 내일
        in_2_days: 2일
        in_3_days: 3일
        in_4_days: 4일
      climate:
        states:
          "on": "on"
          "off": "off"
        heat: 온도
      please_confirm: 확인 부탁드립니다
      unavailable: 불가능
      no_name: 공백
      alarm:
        home: 재가
        away: 외출
        night: 야간
        vacation: 휴가
        bypass: 커스텀
        disarm: 해제
      settings:
        reboot: 재부팅
        sleep: 절전
        brightness: 밝기
        bright: 밝게
        dimming: 조절
        dim: 어둡게
      meridiem:
        am: AM
        pm: PM
```

I don't know where the word "please_confirm" is used, but if you're talking about the notification confirmation button, you can replace it with "confirm".

**Reply by edwardtfn** [reply]
> I don't know where the word "please_confirm" is used, but if you're talking about the notification confirmation button, you can replace it with "confirm".

That is exactly the case. 😃

**Reply by lavi02** [reply]
I got it thank you :p
```yaml
please_confirm: 확인
```

**Comment by edwardtfn** [comment]
```yaml
    zh-tw:  # T.Chinese
      weekdays:
        mon: 星期一
        tue: 星期二
        wed: 星期三
        thu: 星期四
        fri: 星期五
        sat: 星期六
        sun: 星期日
      weekdays_short:
        mon: 一
        tue: 二
        wed: 三
        thu: 四
        fri: 五
        sat: 六
        sun: 日
      months:
        jan: 1月
        feb: 2月
        mar: 3月
        apr: 4月
        may: 5月
        jun: 6月
        jul: 7月
        aug: 8月
        sep: 9月
        oct: 10月
        nov: 11月
        dec: 12月
      months_short:
        jan: 1月
        feb: 2月
        mar: 3月
        apr: 4月
        may: 5月
        jun: 6月
        jul: 7月
        aug: 8月
        sep: 9月
        oct: 10月
        nov: 11月
        dec: 12月
      relative_day:
        today: 今天
        tomorrow: 明天
        in_2_days: 後天
        in_3_days: 大後天
        in_4_days: 4天後
      climate:
        states:
          'on': 開啟
          'off': 關閉
        heat: 暖氣
      please_confirm: 請確認
      unavailable: 無法使用
      no_name: 未命名
      alarm:
        home: 在家
        away: 離家
        night: 夜間
        vacation: 假期
        bypass: 忽略
        disarm: 解除
      settings:
        reboot: 重啟
        sleep: 睡眠
        brightness: 亮度
        bright: 亮度
        dimming: 調光
        dim: 調光
      meridiem:
        am: 上午
        pm: 下午
```

**Comment by shing6326** [comment]
Hi @edwardtfn and @bluefoxlee , do you have some screenshot for the page that using the following text? I think the translation could adjust a bit as follow in my opionion. 

      settings:
        reboot: 重啟
        sleep: 睡眠
        brightness: 亮度
        bright: 光
        dimming: 調光
        dim: 暗

**Reply by edwardtfn** [reply]
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/24a2283e-8459-454b-a430-fdf85482107e)

Not all those strings are in use right now, but this might give you a good idea.

**Reply by edwardtfn** [reply]
### Original translation:
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/375f73d1-21c4-4700-aad7-b784b07c687d)

### Proposed translation:
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/38cc56d1-13f1-407b-8367-4da6ee931bf9)

Please let me know which one to use.

**Reply by shing6326** [reply]
what is the effect if we adjust the "Dim" slider?

**Reply by edwardtfn** [reply]
> what is the effect if we adjust the "Dim" slider?

The panel have 2 brightness modes. When you touch the screen, it will go to the bright mode, defined by the first slider. After a few seconds without touching the screen, it will dim to the second slider brightness, and then after a bit more time, it will turn off.

**Reply by shing6326** [reply]
so I think we could translate it like this. 
正常模式 means the screen is in active mode and
待機模式 means standby mode

  settings:
    reboot: 重啟
    sleep: 睡眠
    brightness: 亮度
    bright: 正常模式
    dimming: 調光
    dim: 待機模式

**Reply by bluefoxlee** [reply]
> Please let me know which one to use.

One quick question. What is the tip to get nice and clean shot of the screen. ^^

**Reply by bluefoxlee** [reply]
> settings: reboot: 重啟 sleep: 睡眠 brightness: 亮度 bright: 正常模式 dimming: 調光 dim: 待機模式

4 characters will be too long. Or edwardtfn will have to modify HMI/TFT again. 😛 
Perhaps 正常 and 待機?

![IMG_0511](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/894044/1d4665ff-3afd-4c88-87ab-c3038aacdd5c)

**Reply by edwardtfn** [reply]
> 4 characters will be too long. Or edwardtfn will have to modify HMI/TFT again. 😛

That is not a problem at all.

**Reply by shing6326** [reply]
正常 and 待機 are good :)

  settings:
    reboot: 重啟
    sleep: 睡眠
    brightness: 亮度
    bright: 正常
    dimming: 調光
    dim: 待機

**Reply by bluefoxlee** [reply]
Have raised PR. Tks @shing6326

**Comment by edwardtfn** [comment]
I've just pushed a bunch of changes to `dev`. I would be nice if you can give me some feedback. I wanna go to `beta` tomorrow and if everything goes right I wanna release on the 3rd of January.

**Comment by shing6326** [comment]
The latest dev is not working. The screen shows System Data  ERROR!.

```INFO Successful handshake with shing_panel @ 10.186.9.107 in 0.236s
[02:11:37][C][template.number:050]: Template Number 'shing_panel Timeout Dimming'
[02:11:37][C][template.number:050]:   Icon: 'mdi:timer'
[02:11:37][C][template.number:050]:   Unit of Measurement: 's'
[02:11:37][C][template.number:051]:   Optimistic: YES
[02:11:37][C][template.number:052]:   Update Interval: 60.0s
[02:11:37][C][template.number:050]: Template Number 'shing_panel Timeout Sleep'
[02:11:37][C][template.number:050]:   Icon: 'mdi:timer'
[02:11:37][C][template.number:050]:   Unit of Measurement: 's'
[02:11:37][C][template.number:051]:   Optimistic: YES
[02:11:37][C][template.number:052]:   Update Interval: 60.0s
[02:11:37][C][template.select:065]: Template Select 'shing_panel Baud rate'
[02:11:37][C][template.select:065]:   Icon: 'mdi:swap-horizontal'
[02:11:37][C][template.select:066]:   Update Interval: 60.0s
[02:11:37][C][template.select:069]:   Optimistic: YES
[02:11:37][C][template.select:070]:   Initial Option: 115200
[02:11:37][C][template.select:071]:   Restore Value: YES
[02:11:37][C][template.select:065]: Template Select 'shing_panel Wake-up page'
[02:11:37][C][template.select:065]:   Icon: 'mdi:page-next-outline'
[02:11:37][C][template.select:066]:   Update Interval: 60.0s
[02:11:37][C][template.select:069]:   Optimistic: YES
[02:11:37][C][template.select:070]:   Initial Option: home
[02:11:37][C][template.select:071]:   Restore Value: YES
[02:11:37][C][template.text_sensor:020]: Template Sensor 'shing_panel Detailed Entity'
[02:11:37][C][template.text_sensor:020]:   Icon: 'mdi:tablet-dashboard'
[02:11:37][C][template.text_sensor:020]: Template Sensor 'shing_panel Current page'
[02:11:37][C][template.text_sensor:020]:   Icon: 'mdi:tablet-dashboard'
[02:11:37][C][template.text_sensor:020]: Template Sensor 'shing_panel Notification Label'
[02:11:37][C][template.text_sensor:020]: Template Sensor 'shing_panel Notification Text'
[02:11:37][C][switch.gpio:068]: GPIO Switch 'shing_panel Relay 1'
[02:11:37][C][switch.gpio:091]:   Restore Mode: restore defaults to OFF
[02:11:37][C][switch.gpio:031]:   Pin: GPIO22
[02:11:37][C][switch.gpio:068]: GPIO Switch 'shing_panel Relay 2'
[02:11:37][C][switch.gpio:091]:   Restore Mode: restore defaults to OFF
[02:11:37][C][switch.gpio:031]:   Pin: GPIO19
[02:11:38][C][gpio.binary_sensor:015]: GPIO Binary Sensor 'shing_panel Left Button'
[02:11:38][C][gpio.binary_sensor:016]:   Pin: GPIO14
[02:11:38][C][gpio.binary_sensor:015]: GPIO Binary Sensor 'shing_panel Right Button'
[02:11:38][C][gpio.binary_sensor:016]:   Pin: GPIO27
[02:11:38][C][switch.gpio:068]: GPIO Switch 'shing_panel Nextion display - Power'
[02:11:38][C][switch.gpio:091]:   Restore Mode: always ON
[02:11:38][C][switch.gpio:031]:   Pin: GPIO4
[02:11:38][D][nextion:276]: Manually set nextion report ready
[02:11:38][D][nextion:354]: Nextion is setup
[02:11:38][D][script.setup_sequence:2583]: Starting Nextion setup sequence
[02:11:38][D][script.setup_sequence:2584]: Fetching page id
[02:11:38][E][nextion:525]: ERROR: Received numeric return but the queue is empty
[02:11:38][C][template.switch:068]: Template Switch 'shing_panel Notification sound'
[02:11:38][C][template.switch:091]:   Restore Mode: restore defaults to OFF
[02:11:38][C][template.switch:057]:   Optimistic: YES
[02:11:38][C][template.switch:068]: Template Switch 'shing_panel Relay 1 Local'
[02:11:38][C][template.switch:091]:   Restore Mode: restore defaults to OFF
[02:11:38][C][template.switch:057]:   Optimistic: YES
[02:11:38][C][template.switch:068]: Template Switch 'shing_panel Relay 2 Local'
[02:11:38][C][template.switch:091]:   Restore Mode: restore defaults to OFF
[02:11:38][C][template.switch:057]:   Optimistic: YES
[02:11:38][C][template.switch:068]: Template Switch 'shing_panel Notification unread'
[02:11:38][C][template.switch:091]:   Restore Mode: always OFF
[02:11:38][C][template.switch:057]:   Optimistic: YES
[02:11:38][C][rtttl:029]: Rtttl
[02:11:39][C][nextion:128]: Nextion:
[02:11:39][C][nextion:129]:   Device Model:     NX4832F035_011C
[02:11:39][C][nextion:130]:   Firmware Version: 72
[02:11:39][C][nextion:131]:   Serial Number:    6CB33401CEB26738
[02:11:39][C][nextion:132]:   Flash Size:       16777216
[02:11:39][C][nextion:133]:   Wake On Touch:    YES
[02:11:39][C][nextion:134]:   Exit reparse:     YES
[02:11:39][C][restart.button:017]: Restart Button 'shing_panel Restart'
[02:11:39][C][adc:097]: ADC Sensor 'ntc_source'
[02:11:39][C][adc:097]:   Device Class: 'voltage'
[02:11:39][C][adc:097]:   State Class: 'measurement'
[02:11:39][C][adc:097]:   Unit of Measurement: 'V'
[02:11:39][C][adc:097]:   Accuracy Decimals: 2
[02:11:39][C][adc:107]:   Pin: GPIO38
[02:11:39][C][adc:122]:  Attenuation: 11db
[02:11:39][C][adc:142]:   Update Interval: 60.0s
[02:11:39][C][resistance:010]: Resistance Sensor 'resistance_sensor'
[02:11:39][C][resistance:010]:   State Class: 'measurement'
[02:11:39][C][resistance:010]:   Unit of Measurement: 'Ω'
[02:11:39][C][resistance:010]:   Accuracy Decimals: 1
[02:11:39][C][resistance:010]:   Icon: 'mdi:flash'
[02:11:39][C][resistance:011]:   Configuration: DOWNSTREAM
[02:11:39][C][resistance:012]:   Resistor: 11200.00Ω
[02:11:39][C][resistance:013]:   Reference Voltage: 3.3V
[02:11:39][C][ntc:014]: NTC Sensor 'shing_panel Temperature'
[02:11:39][C][ntc:014]:   Device Class: 'temperature'
[02:11:39][C][ntc:014]:   State Class: 'measurement'
[02:11:39][C][ntc:014]:   Unit of Measurement: '°C'
[02:11:39][C][ntc:014]:   Accuracy Decimals: 1
[02:11:39][C][homeassistant.time:010]: Home Assistant Time:
[02:11:39][C][homeassistant.time:011]:   Timezone: 'HKT-8'
[02:11:39][C][status:034]: Status Binary Sensor 'shing_panel Status'
[02:11:39][C][status:034]:   Device Class: 'connectivity'
[02:11:41][C][mdns:115]: mDNS:
[02:11:41][C][mdns:116]:   Hostname: shing_panel
[02:11:41][C][ota:097]: Over-The-Air Updates:
[02:11:41][C][ota:098]:   Address: 10.186.9.107:3232
[02:11:41][C][ota:101]:   Using Password.
[02:11:41][C][api:139]: API Server:
[02:11:41][C][api:140]:   Address: 10.186.9.107:6053
[02:11:41][C][api:142]:   Using noise encryption: YES
[02:11:41][C][wifi_signal.sensor:009]: WiFi Signal 'shing_panel RSSI'
[02:11:41][C][wifi_signal.sensor:009]:   Device Class: 'signal_strength'
[02:11:41][C][wifi_signal.sensor:009]:   State Class: 'measurement'
[02:11:41][C][wifi_signal.sensor:009]:   Unit of Measurement: 'dBm'
[02:11:41][C][wifi_signal.sensor:009]:   Accuracy Decimals: 0
[02:11:43][D][script.setup_sequence:2592]: Fetching charset
[02:11:43][W][nextion:405]: Nextion reported variable name invalid!
[02:11:48][D][script.setup_sequence:2600]: Fetching display mode
[02:11:48][W][nextion:405]: Nextion reported variable name invalid!
[02:11:53][E][script.setup_sequence:2727]: A non-compatible TFT is installed
[02:11:53][D][script.setup_sequence:2730]: Nextion setup sequence finished!
[02:12:00][W][nextion:405]: Nextion reported variable name invalid!
[02:12:00][W][nextion:405]: Nextion reported variable name invalid!```

**Reply by edwardtfn** [reply]
What if you try upload TFT again? Could you please share the logs?

**Reply by shing6326** [reply]
I tried 3 times without success, and then I tried to download nspanel_eu.tft from dev branch and replace the fonts by myself and it works, so I suspect there may have some issues on the nspanel_CJK_eu.tft file.

**Reply by edwardtfn** [reply]
From where did you got the fonts which worked?

**Reply by shing6326** [reply]
https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/1359#issuecomment-1837246987
The 4808 Set

**Reply by edwardtfn** [reply]
And have you tried downloading the CJK again? Maybe it got corrupted in your download from GitHub or upload to your local server.

**Reply by shing6326** [reply]
there are some mirror issues on my test.
1. the entity which doesn't have an icon would automatically assigned. I cannot find a way to not show the icon
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/42719827/430d2b58-f7ec-4637-ab23-dd12a56facfc)
2. the temperature mark seems not in a right place
3. the ac controll seems disabled?
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/42719827/10dd4518-71cd-4332-be44-b18a196f15f6)

**Reply by shing6326** [reply]
Yes I have, I checked the file size / md5sum and it is the same

**Reply by edwardtfn** [reply]
Let's work one by one:
- #1512 
- #1513 
- #1514 
- #1515

**Comment by leotantantan** [comment]
```
zh-cn:  # S.Chinese
      weekdays:
        mon: 星期一
        tue: 星期二
        wed: 星期三
        thu: 星期四
        fri: 星期五
        sat: 星期六
        sun: 星期日
      weekdays_short:
        mon: 一
        tue: 二
        wed: 三
        thu: 四
        fri: 五
        sat: 六
        sun: 日
      months:
        jan: 1月
        feb: 2月
        mar: 3月
        apr: 4月
        may: 5月
        jun: 6月
        jul: 7月
        aug: 8月
        sep: 9月
        oct: 10月
        nov: 11月
        dec: 12月
      months_short:
        jan: 1月
        feb: 2月
        mar: 3月
        apr: 4月
        may: 5月
        jun: 6月
        jul: 7月
        aug: 8月
        sep: 9月
        oct: 10月
        nov: 11月
        dec: 12月
      relative_day:
        today: 今天
        tomorrow: 明天
        in_2_days: 后天
        in_3_days: 大后天
        in_4_days: 4天后
      climate:
        states:
          'on': 开启
          'off': 关闭
        heat: 暖气
      please_confirm: 请确认
      unavailable: 无法使用
      no_name: 未命名
      alarm:
        home: 在家
        away: 离家
        night: 夜间
        vacation: 假期
        bypass: 忽略
        disarm: 解除
      settings:
        reboot: 重启
        sleep: 睡眠
        brightness: 亮度
        bright: 亮度
        dimming: 调光
        dim: 调光
      meridiem:
        am: 上午
        pm: 下午
```
