### DISCUSSION TITLE
Can't upload TFT display

### DISCUSSION THREAD

**Discussion by Helge137** [Blackymas/NSPanel_HA_Blueprint#1497] [Q&A]
Hello all,

thanks to the amazing work and detailed wiki I was able to flash the NSPanel and am now able to see it via ESPHome. I can also use the software buttons here to switch a relay e.g. When uploading the TFT display I do have a problem as it seems. The panel just restarts but no matter how long I wait there's no new display shown. What does surprise me is that it is not a slider, it's just a push button. But as it seems it does do something, but not the hoped upate tho...
<img width="234" alt="2023-12-31_12h59_49" src="https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/134098839/8d2dfff8-311d-436b-9f52-cd43d3c8dbd6">

I did work my way through the FAQ but none of these helped with this issue. I also re-flashed it, am using the local version but again no luck. The code I used for ESPHome is following:

```yaml
substitutions:
 
###### CHANGE ME START ######
 
  device_name: "nspanel" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
 
  nextion_update_url: "http://192.168.178.10:8123/local/nspanel_eu.tft" # URL to local tft File
 
##### CHANGE ME END #####



 ##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 1s

esp32:
  framework:
    type: esp-idf

##### DO NOT CHANGE ANYTHING! #####`
```

Any ideas what I'm doing wrong here?
Thanks and have a happy new year!
