### DISCUSSION TITLE
Use as Alarmclock

### DISCUSSION THREAD

**Discussion by itsieber** [Blackymas/NSPanel_HA_Blueprint#1538] [Ideas]
Any ideas to use nspanel on the bed as smart alarmclock?

**Comment by andythomas** [comment]
I am doing it and quite happy with the result. First, I added a toggle switch `wecker` via the helpers section as explained [here](https://www.home-assistant.io/integrations/input_boolean/). Then, I added the toggle switch to a button page of the NSPanel to be able to switch it on and off. It basically only switches between work days and vacation. I also added it as a chip in the NSPanel to see, whether it is `on` or `off` on the home screen. Finally, I created an [automation](https://www.home-assistant.io/docs/automation/basics/). 

In my case, it slowly dims the light to full brightness via the [hue integration](https://www.home-assistant.io/integrations/hue/) and plays a playlist via the [Sonos](https://www.home-assistant.io/integrations/sonos/) and [Plex](https://www.home-assistant.io/integrations/plex/) integration. If you want it 'panel only', you could play an RTTTL song via the NSPanel. 

It has no snooze, but I do not need that. 

```
alias: Aufwachen
description: ""
trigger:
  - platform: time
    at: "06:04:00"
condition:
  - condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
    before: "00:00:00"
    after: "00:00:00"
  - condition: state
    entity_id: input_boolean.wecker
    state: "on"
action:
  - service: script.aufwachlicht
    data: {}
  - delay:
      hours: 0
      minutes: 6
      seconds: 0
      milliseconds: 0
  - service: script.play_aufstehsongs_schlafzimmer
    data: {}
mode: single 
```
