### DISCUSSION TITLE
Brightness Control by Time

### DISCUSSION THREAD

**Discussion by vitalikkh** [Blackymas/NSPanel_HA_Blueprint#1553] [General]
I am sure, this is possible but (unfortunately) I cannot figure out how to set Display Brightness by time of the day.
What I am looking for - is to set a display (dim) brightness to X say, from 8am to 10pm and to Y from 10pm to 8am.
The idea is to basically turn off the display at night time.
Please advice how to set this up?

PS.
For some reason I have very hard time to figure out how to search this forum.
Unfortunately this is not intuitive and straight forward.

**Comment by andythomas** [comment]
I would suggest to do that in HA via, e.g., an [automation](https://www.home-assistant.io/docs/automation/). I did the following one for you as a starting point. Make a new automation, use the the top right dots to select `Edit in YAML`, save the code below and either select `Edit in visual editor` or simply leave the page and revisit your newly created automation to look at it. You will have to change the `entity` according to your naming scheme and, of course, the time you want to change it. Please note that the numbers are displayed in % in `esphome`, but set as a number of up to 100. 
```
alias: Panel brightness
description: ""
trigger:
  - platform: time
    at: "10:57:00"
condition: []
action:
  - service: number.set_value
    metadata: {}
    data:
      value: "95"
    target:
      entity_id: number.arbeitspanel_display_brightness
mode: single
```
