### DISCUSSION TITLE
Change to ESP - IDF

### DISCUSSION THREAD

**Discussion by rudgej** [Blackymas/NSPanel_HA_Blueprint#1631] [Q&A] [answered]
Could I please clarify a few things 

1. You add the below to the esp hone YAML file for the panel 
```yaml
# Change framework to `esp-idf`
esp32:
  framework:
    type: esp-idf
```

2. You then MUST update using the hard wired method from USB not wireless. Wireless may seem to work but wont change the partition which I assume causes issues 

3. Can you confirm we can do this now pre March 2024 without causing issues 

4. If we dont do this what are the long term implications ? Performance, features  or it simply wont work ? 

I have to remove some 15 panels from the wall hence asking the questions!
