### DISCUSSION TITLE
Home Page Sensors and Buttons

### DISCUSSION THREAD

**Discussion by rudgej** [Blackymas/NSPanel_HA_Blueprint#1653] [Q&A]
I have not used these until now and I am trying to make them work so I get more form the panels. 

However ...

If I enter a sensor in the blueprint or a light entity on a home page button nothing is happening on the screen.

I have got chips working. 

Is this a bug or am I missing something ?

Thank you

**Comment by edwardtfn** [comment]
Could you please report this as a bug? https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/new/choose

**Comment by illuzn** [comment]
This may sound obvious, but it can take up to 10 seconds for the panel to update once you've changed that setting. 

Have you tried manually sending a value to the relevant part of the screen?

This is done via a service calls (you can try these by changing nspanel with the name of your panel):
```yaml
service: esphome.nspanel_send_command_text_printf
data: 
  component: button01
  message: "\uE6A8"
```
This should put a Robot icon where button 1 is on the home screen. 

```yaml
service: esphome.nspanel_send_command_text_printf
data:
  component: home.value01_state
  message: "hello"
```
This should print hello where sensor 1 appears on your home screen.
