### DISCUSSION TITLE
PID usage for floor heater

### DISCUSSION THREAD

**Discussion by 4irm** [Blackymas/NSPanel_HA_Blueprint#1857] [Q&A]
Dear all,

I got the NSPanel up and running, now I’d like to replace my Homematic IP HmIP-BWTH thermostats (230V)] with it. It is used to control my floor heater (via a heat pump).

Since the floor heater is sluggish, which is normal, the Homematic component uses PID ([Esphome PID](https://esphome.io/components/climate/pid.html). From my perspective this is a absolute prerequisite to for a thermostat steering a floor heater. ESPHome has this built in.

In that regards I do have the following question.

How can I configure it with this blueprint? Clearly I need a climate/thermostat component in HA. The question is whether I can configure it directly or if I need a HACS component such as [ScratMan/HASmartThermostat: Smart Thermostat with PID controller for HomeAssistant (github.com)](https://github.com/ScratMan/HASmartThermostat)?

Obviously the built in solution is preferred :wink:

Thanks for your support!

**Comment by edwardtfn** [comment]
> PID Controller Setup
> To set up a PID climate controller, you need a couple of components:

>
> A [Sensor](https://esphome.io/components/sensor/#config-sensor) to read the current temperature (sensor).

>
> At least one [float output](https://esphome.io/components/output/#config-output) to drive for heating or cooling (or both). This could for > example be a PWM output via [Sigma-Delta Output](https://esphome.io/components/output/sigma_delta_output) or [Slow PWM Output] (https://esphome.io/components/output/slow_pwm) that drives a heating unit.

The NSPanel only have 2 dry contact relays, so I don't think you can use PID directly without modifying your hardware.

You are probably aware of the [Add-on: Climate](https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/docs/addon_climate.md) currently available, right? That is based on [ESPHome Thermostat Climate Controller](https://esphome.io/components/climate/thermostat.html).

**Reply by thomasheiser85** [reply]
I can not confirm. The PID component works fine together with Slow PWM on the NSPanel hardware. I was using it together with "NSPanel Lovelace UI" before i found this Blueprint.

I was using this configuration before i migrated to the Blueprint ( yesterday ):

```yaml

climate:
  - platform: pid
    id: thermostat_wohnzimmer
    name: "Wohnzimmer Thermostat"
    sensor: temperature
    default_target_temperature: 22°C
    heat_output: heater
    control_parameters:
      kp: 0.49460
      ki: 0.00487
      kd: 12.56301

output:
# PWM für Thermostat relay_2
  - platform: slow_pwm
    pin:
      number: 19 # Relay 2
    id: heater
    period: 30min

sensor:
  # Internal temperature sensor, adc value
  - platform: adc
    id: ntc_source
    pin: 38
    update_interval: 10s
    attenuation: 11db

  # Internal temperature sensor, adc reading converted to resistance (calculation)
  - platform: resistance
    id: resistance_sensor
    sensor: ntc_source
    configuration: DOWNSTREAM
    resistor: 11.2kOhm

  # Internal temperature sensor, resistance to temperature (calculation)
  - platform: ntc
    id: temperature
    sensor: resistance_sensor
    calibration:
      b_constant: 3950
      reference_temperature: 25°C
      reference_resistance: 10kOhm
    name: $friendly_devicename Temperature

```

**Reply by 4irm** [reply]
Thanks for your feedback!

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/28482836/5a6ee417-08a5-4efd-952e-6e97226f7028)

Since my graph does not look as good as andythomas' graph I probably try some tweeking

I guess I just need to add these parameters to ESPHome nspanel device configuration...

    control_parameters:
      kp: 0.49460
      ki: 0.00487
      kd: 12.56301

Any suggestions how to determine these parameters? (Besides the scientific way ;)

**Comment by andythomas** [comment]
> From my perspective this [PID] is a absolute prerequisite to for a thermostat steering a floor heater. 

At least in my case, this was not the case. After tweaking the parameters a little, a simple on-off heater control works nicely. I updated the documentation, added my implementation as an example and made a pull request. Please see the temperature stability here:

![addon_underfloor](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/995840/90e16a21-ed99-4123-8221-5f5ce9246be7)

Mar 5 at approx. 9.30pm, the window was opened and all heaters were set to 'off.'

**Reply by 4irm** [reply]
Big thank you for your feedback and update of the documentation. 

Could you please share your configuration so that I have a good starting point to work with? I do have a heat pump and the flow temperature is around 35°. I guess everything needs to be incorporated in the ESPHOME yaml file....

Thank you very much!

**Comment by andythomas** [comment]
Here comes the requested part from the (future, i.e. ~~4.2.7~~ 4.3) documentation:

The NSPanel works nicely as a replacement for existing water underfloor heating controllers, installed at eye level and often powered by 100-240VAC. In my specific use case, the control valve is of the 'normally closed' type, meaning that an open relay indicates 'no heating.' I have utilized relay #1 for this purpose. It's important to note that this setup does not act as a PID controller but operates on a simple on-off mechanism. The system initiates heating at a preset value below and turns it off at a value above the set point. I have set these values to `0.3°C` below and `0.1°C` above the target temperature, respectively. These adjustments, `0.3` and `0.1`, have been effectively maintaining the desired temperature in all of our four rooms. The thermostat's settings range from a minimum of `15°C` to a maximum of `22°C`, with a granularity of `0.1°C` for adjustments. Furthermore, I have selected `21.2°C` as the default target temperature.

```yaml
 ##### addon-configuration #####
  ## addon_climate ##
  heater_relay: "1" #Use relay 1
  temp_min: "15" 
  temp_max: "22" 
  temp_step: "0.1"
  cold_tolerance: "0.3"
  hot_tolerance: "0.1"
    
  ##### CHANGE ME END #####
climate:
  - id: !extend thermostat_embedded
    preset:
      - name: Home
        default_target_temperature_low: 21.2
        mode: "heat"
```

Please note that employing any filter to smooth the temperature readings, such as averaging, is discouraged.
Such filtering methods can delay the response times of an already slow underfloor heating system.
Despite this, the temperature stability achieved is quite satisfactory.

@4irm Please feel free to post your temperature profile and parameters here and I can try to have a look at it.
