### DISCUSSION TITLE
I cant change my wifi network

### DISCUSSION THREAD

**Discussion by pbranly** [Blackymas/NSPanel_HA_Blueprint#1894] [General]
Hi
I am migrating all my equipments from my wifi box to an external router.
therefore i have changedthe following lines in the configuration file:

  device_name: nspanel 
  wifi_ssid: !secret SSID_AX25_IoT
  wifi_password: !secret wifi_password_AX25_IoT

it is then supposed the nspanel to log to the nex network. (I already used that with success with a personal esp32)
Nevertheless, at the end of the compilation,; I get the following error:

**Error auth result: Error: Authentication invalid. Is the password correct?**

It seems that they are new lines to add in the configuration file but I dont know which ones and their syntax

Thank you for your help
Phil

**Comment by edwardtfn** [comment]
The problem is that from the beginning we are using the WiFi password as Ota password, so before changing the WiFi password you will have to change the ota password manually.

I’m on my phone now, but please take a look at this and let us know if you still need support:
https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/docs/customization.md#custom-ota-password

**Comment by pbranly** [comment]
Hi
I am afraid it does not work;
I have added the following lines in the configuration file:

```yaml
# change OTA password, remove after flashing
esphome:
  on_boot:
    - priority: 601.0
      then:
        - lambda: |-
            id(my_ota).set_auth_password("xxxxxxxxx"); <------------- with xxxxxxx equal to the new password
ota:
  password: !secret wifi_password  <------------ the old password
  id: my_ota  
```
Now esphome reports the nspanel as "online" but it is not possible to have the logs, and to reflash
furthemore, I cant find any ip connected to my network.
Any chance to prevent hard dowload ?

Phil
