### DISCUSSION TITLE
Control display (Wake up and activate alarm page) from home assistant

### DISCUSSION THREAD

**Discussion by patrick-foubert-56770** [Blackymas/NSPanel_HA_Blueprint#1987] [Q&A] [answered]
Hi all,

A want make an automation based on an event (opening door when alarm is away), on automation side no problem, i found api call to wake up display, but how to swap display to alarm page ?

**Comment by edwardtfn** [comment]
You can use [`entity_details_show`](https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/docs/api.md#entity-details-show-service-entity_details_show) service sending your alarm control panel's entity.

**Reply by patrick-foubert-56770** [reply]
Thanks, i try it but  in example i see:

service: esphome.<your_panel_name>_entity_details_show
data:
  entity_id: "light.living_room"
  back_page: "buttonpage01"
  
For alarm page, what entity id i need specify ? Alarm control panel ?

**Reply by edwardtfn** [reply]
Yeap. Something like this:

```yaml
service: esphome.<your_panel_name>_entity_details_show
data:
  entity_id: "alarm_control_panel.my_alarm_entity"
  back_page: "home"
```
