### DISCUSSION TITLE
Switching between screens

### DISCUSSION THREAD

**Discussion by proasnet** [Blackymas/NSPanel_HA_Blueprint#2065] [Q&A]
Hello, I managed to upload the firmware to NSPanel EU, import and set the blueprint, but I have a stupid question:
 How does it switch between screens? I've tried touching the display in all places, and the screens won't switch.

**Comment by edwardtfn** [comment]
Have you set the components of other screen in the automation (using the Blueprint)?

Let's start with the button pages... As soon you have a button set, you shoukd be able to swipe left or right to go to the button pages. The entities pages will be accessible via a specific button in the Home page. The detailed pages are based on pressing buttons of specific domains (lights, climate, fans, etc).
Ah, and the setup page is accessible via a long press over the time indication.
Weather page is accessible by clicking the weather icon.

**Comment by proasnet** [comment]
Yes, via blueprint.
The home page works fine for me. I also discovered the buttons page with a swipe of my finger.
Tried the settings page via long press on the clock today and that works too.
But where I can't get to is the Climate page that I configured in the blueprint, and I'm also interested in the power distribution diagram page, I didn't even find it in the blueprint, but I saw it in the nextion project, I think it's the last page.

**Reply by edwardtfn** [reply]
For the climate, a single click on the internal temperature.
For the utilities page, you should be seeing in your blueprint settings. Which version is shown at the beginning of the Blueprint settings?

**Reply by proasnet** [reply]
A last version. 4.3.4, flashed yesterday.

**Comment by proasnet** [comment]
I'm still wondering about one thing. In the buttons page I set up for scenes, in the blueprint I also assigned icon colors to the buttons, but in the NSPanel all the buttons are gray. I'm attaching a screenshot from the blueprint, unfortunately I don't have the NSPanel with me for a photo.
![btn_page](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/76579362/e17a03f2-da8c-48e9-863b-b577bc0f5f18)
```

alias: NSPanel Obývák 1NP
description: ""
use_blueprint:
  path: Blackymas/nspanel_blueprint.yaml
  input:
    nspanel_name: 512f12124a318e676451a62328293181
    language: cs
    timezone: Europe/Prague (CET-1CEST,M3.5.0,M10.5.0/3)
    weather_entity: weather.domov
    outdoortemp: sensor.bsb_lan_outside_temperature
    indoortemp: sensor.nspanel_obyvak_1np_temperature
    home_custom_button01: scene.obyvak_1np_bila
    home_custom_button01_icon: mdi:palette
    home_custom_button01_name: Bila
    home_custom_button02: scene.obyvak_1np_sky
    home_custom_button02_icon: mdi:palette
    home_custom_button02_name: Obloha
    home_custom_button03: scene.obyvak_1np_ruzova
    home_custom_button03_icon: mdi:palette
    home_custom_button03_name: Ruzova
    home_custom_button04: scene.obyvak_1np_vyp
    home_custom_button04_icon: mdi:alarm-light-off
    home_custom_button04_name: Vyp
    hw_buttons_bars_pages:
      - "2"
      - "61440"
      - "3932160"
      - "65536"
      - "131072"
      - "512"
      - "256"
      - "134217728"
      - "124"
      - "8388608"
      - "128"
      - "2048"
      - "4194304"
      - "1024"
      - "67108864"
      - "16777216"
      - "33554432"
    hw_button_bar_left_always_show: true
    left_button_entity: light.rgbcw_obyvak_1np
    left_button_name: ZAP/VYP
    left_button_hold_select: Default
    home_outdoor_temp_label_color:
      - 0
      - 128
      - 255
    home_indoor_temp_icon_color:
      - 255
      - 255
      - 0
    climate: climate.termostat_obyvak_1np_termostat
    climate_button08: switch.termostat_obyvak_1np_vypinac
    climate_button08_icon: mdi:thermometer-chevron-up
    climate_button08_icon_color:
      - 255
      - 0
      - 0
    left_button_hold_custom_action: []
    right_button_name: 1 MIN
    right_button_hold_select: Custom Action
    right_button_hold_custom_action: []
    right_button_state_entity: light.rgbcw_obyvak_1np
    right_button_color:
      - 0
      - 255
      - 255
    left_button_state_entity: light.rgbcw_obyvak_1np
    left_button_color:
      - 0
      - 255
      - 255
    home_value01: binary_sensor.input_0
    home_value01_label_color:
      - 0
      - 0
      - 255
    home_value01_icon: mdi:minus-circle-multiple-outline
    home_value02: binary_sensor.inverter_1_battery_mode
    home_value02_label_color:
      - 0
      - 255
      - 0
    home_value02_icon: mdi:battery-50
    button_pages_icon_size: "10"
    button_page01_label: Scény
    entity01: scene.obyvak_1np_bila
    entity01_name: Bila
    entity01_icon_color:
      - 255
      - 255
      - 255
    entity02: scene.obyvak_1np_sky
    entity02_name: More
    entity03: scene.obyvak_1np_ruzova
    entity03_name: Ruzova
    entity03_icon_color:
      - 207
      - 139
      - 196
    entity04: scene.obyvak_1np_cervena
    entity04_name: Cervena
    entity04_icon_color:
      - 255
      - 0
      - 0
    entity05: scene.obyvak_1np_zelena
    entity05_name: Zelena
    entity05_icon: ""
    entity05_icon_color:
      - 0
      - 255
      - 0
    entity06: scene.obyvak_1np_modra
    entity06_name: Modra
    entity06_icon_color:
      - 0
      - 0
      - 255
    utilities_page01_home_value1: sensor.inverter_1_pv_energy
    utilities_page01_home_value2: sensor.inverter_2_pv_energy
    chip01: binary_sensor.input_0
```

**Comment by edwardtfn** [comment]
On the custom buttons and button pages you have assigned scenes. Those are not dual-state entities, so when you click the button the scene will be executed and nothing else. On the button pages you will see the button changing for a fraction of second, but then it will come back to the original state.

I see in the hardware buttons you have assigned lights. If those lights supports adjustments on brightness, color or temperature, a long push on those buttons should bring you the detailed page (the same is valid for any button with light, cover, fan, climate, alarm or media player assigned).

About the utilities page, don't you see the gauge icon on the home page? That should bring you to the utilities page.

**Comment by proasnet** [comment]
I am sending the updated yaml settings.
There is nothing on the home page to direct me to utilities.
I confirm that a long press of the hw button triggered the light setting.
A long press on the internal temperature does nothing at all. I can't get into the temperature settings

```
alias: NSPanel Obývák 1NP
description: ""
use_blueprint:
  path: Blackymas/nspanel_blueprint.yaml
  input:
    nspanel_name: 512f12124a318e676451a62328293181
    language: cs
    timezone: Europe/Prague (CET-1CEST,M3.5.0,M10.5.0/3)
    weather_entity: weather.domov
    outdoortemp: sensor.bsb_lan_outside_temperature
    indoortemp: sensor.nspanel_obyvak_1np_temperature
    home_custom_button01: scene.obyvak_1np_bila
    home_custom_button01_icon: mdi:palette
    home_custom_button01_name: Bila
    home_custom_button02: scene.obyvak_1np_sky
    home_custom_button02_icon: mdi:palette
    home_custom_button02_name: Obloha
    home_custom_button03: scene.obyvak_1np_ruzova
    home_custom_button03_icon: mdi:palette
    home_custom_button03_name: Ruzova
    home_custom_button04: scene.obyvak_1np_vyp
    home_custom_button04_icon: mdi:alarm-light-off
    home_custom_button04_name: Vyp
    hw_buttons_bars_pages:
      - "2"
      - "61440"
      - "3932160"
      - "65536"
      - "131072"
      - "512"
      - "256"
      - "134217728"
      - "124"
      - "8388608"
      - "128"
      - "2048"
      - "4194304"
      - "1024"
      - "67108864"
      - "16777216"
      - "33554432"
    hw_button_bar_left_always_show: true
    left_button_entity: light.rgbcw_obyvak_1np
    left_button_name: ZAP/VYP
    left_button_hold_select: Default
    home_outdoor_temp_label_color:
      - 0
      - 128
      - 255
    home_indoor_temp_icon_color:
      - 255
      - 255
      - 0
    climate: climate.termostat_obyvak_1np_termostat
    climate_button08: switch.termostat_obyvak_1np_vypinac
    climate_button08_icon: mdi:thermometer-chevron-up
    climate_button08_icon_color:
      - 255
      - 0
      - 0
    left_button_hold_custom_action: []
    right_button_name: 1 MIN
    right_button_hold_select: Custom Action
    right_button_hold_custom_action: []
    right_button_state_entity: light.rgbcw_obyvak_1np
    right_button_color:
      - 0
      - 255
      - 255
    left_button_state_entity: light.rgbcw_obyvak_1np
    left_button_color:
      - 0
      - 255
      - 255
    home_value01: binary_sensor.input_0
    home_value01_label_color:
      - 0
      - 0
      - 255
    home_value01_icon: mdi:minus-circle-multiple-outline
    home_value02: binary_sensor.inverter_1_battery_mode
    home_value02_label_color:
      - 0
      - 255
      - 0
    home_value02_icon: mdi:battery-50
    button_pages_icon_size: "10"
    button_page01_label: Scény
    entity01: scene.obyvak_1np_bila
    entity01_name: Bila
    entity01_icon_color:
      - 255
      - 255
      - 255
    entity02: scene.obyvak_1np_sky
    entity02_name: More
    entity03: scene.obyvak_1np_ruzova
    entity03_name: Ruzova
    entity03_icon_color:
      - 207
      - 139
      - 196
    entity04: scene.obyvak_1np_cervena
    entity04_name: Cervena
    entity04_icon_color:
      - 255
      - 0
      - 0
    entity05: scene.obyvak_1np_zelena
    entity05_name: Zelena
    entity05_icon: ""
    entity05_icon_color:
      - 0
      - 255
      - 0
    entity06: scene.obyvak_1np_modra
    entity06_name: Modra
    entity06_icon_color:
      - 0
      - 0
      - 255
    chip01: binary_sensor.input_0
    utilities_page01_label: Distribuce energie
    utilities_page01_grid_value1: sensor.sum_line_energy
    utilities_page01_group01_value1: sensor.co2_intensity
    utilities_page01_group01_value2: sensor.grid_fossil_fuel_percentage
    utilities_page01_group03_label: PV Energy
    utilities_page01_group03_value1: sensor.sum_pv_energy
    utilities_page01_group01_label: Line Energy
    utilities_page01_group04_label: Battery Energy
    utilities_page01_group04_value1: sensor.bms_charging_energy
    utilities_page01_group04_value2: sensor.bms_discharging_energy
    utilities_page01_group05_label: Spotřeba plynu
    utilities_page01_group05_value1: sensor.gas_used
    utilities_page01_group06_label: Spotřeba vody
    utilities_page01_group06_icon: mdi:water
    utilities_page01_group05_icon: mdi:fire
    utilities_page01_group06_value1: sensor.water_used
    utilities_page01_group06_color:
      - 0
      - 0
      - 255
    utilities_page01_group05_color:
      - 255
      - 0
      - 0
    utilities_page01_group04_color:
      - 255
      - 128
      - 128
    utilities_page01_group03_color:
      - 255
      - 128
      - 0
    utilities_page01_group01_color:
      - 0
      - 255
      - 0
    utilities_page01_grid_color:
      - 0
      - 128
      - 255
    utilities_page01_group04_line_reference: sensor.bms_charging_current
    utilities_page01_group03_line_reference: sensor.sum_pv_current
```


![20240419_155926](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/76579362/a84fd05a-0f8e-43e9-bae4-36cb5f173477)
![20240419_155907](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/76579362/029a7523-1db3-4c1b-9b01-a436ffad0dd7)

![20240419_155836](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/76579362/9e701523-f1c9-4916-b795-71f6b90087ea)
