### DISCUSSION TITLE
Single pole, double throw (SPDT)

### DISCUSSION THREAD

**Discussion by IversenT** [Blackymas/NSPanel_HA_Blueprint#2105] [Q&A] [answered]
Hi,

Is there a way to use the NSpanel and both relays as a SPDT switch? 
So that one of the relays always are active and changes which one are active by one of the HW buttons?

**Comment by edwardtfn** [comment]
Please let me know if I understood it correctly...

1. One of the relays, and only one, will always be energized. You will never have two evergized at the same time, and you will never have both off at the same time.
2. When you press the left button, the relay 1 will be energised and relay 2 will be off, regardless of their previous state.
3. When you press the right button, the relay 2 will be energised and relay 1 will be off, regardless of their previous state.

Is that correct?

**Reply by IversenT** [reply]
Not exactly.
1 is correct.
When I press left button it changes which relay is energized. And when left button is pressed again it switches the relay again.

**Reply by edwardtfn** [reply]
And what should right button do? Nothing related to the relays?

**Reply by IversenT** [reply]
Correct.

**Reply by edwardtfn** [reply, marked as answer]
Sorry for the late reply here.

Adding this to your panel's yaml should do the trick:

```yaml
binary_sensor:
  - id: !extend right_button
    on_click:
      - switch.toggle: relay_1
switch:
  # Prevents the two relays to be on simultaneously
  - id: !extend relay_1
    interlock: [relay_1, relay_2]
    interlock_wait_time: 500ms  # Please adjust this accordingly
    on_turn_on:
      - switch.turn_off: relay_2
    on_turn_off:
      - switch.turn_on: relay_2
  - id: !extend relay_2
    interlock: [relay_1, relay_2]
    interlock_wait_time: 500ms  # Please adjust this accordingly
```

You can add to the customization area or to the very end of the file. It's up to you.
