### DISCUSSION TITLE
Initial firmware flashing

### DISCUSSION THREAD

**Discussion by elronzo** [Blackymas/NSPanel_HA_Blueprint#2123] [Q&A]
IMHO the firmware flashing process looks quite good:

```log
Creating esp32 image...
Successfully created esp32 image.
[...]
========================= [SUCCESS] Took 37.18 seconds =========================
INFO Successfully compiled program.
esptool.py v4.7.0
Serial port /dev/ttyUSB0
Connecting....
Chip is ESP32-D0WD-V3 (revision v3.0)
Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
Crystal is 40MHz
MAC: 78:e3:6d:ca:09:8c
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 460800
Changed.
Configuring flash size...
Auto-detected Flash size: 4MB
Flash will be erased from 0x00010000 to 0x00133fff...
Flash will be erased from 0x00001000 to 0x00007fff...
Flash will be erased from 0x00008000 to 0x00008fff...
Flash will be erased from 0x00009000 to 0x0000afff...
Compressed 1192960 bytes to 759720...
Wrote 1192960 bytes (759720 compressed) at 0x00010000 in 18.8 seconds (effective 508.6 kbit/s)...
Hash of data verified.
Compressed 25632 bytes to 16087...
Wrote 25632 bytes (16087 compressed) at 0x00001000 in 0.9 seconds (effective 222.9 kbit/s)...
Hash of data verified.
Compressed 3072 bytes to 134...
Wrote 3072 bytes (134 compressed) at 0x00008000 in 0.1 seconds (effective 328.9 kbit/s)...
Hash of data verified.
Compressed 8192 bytes to 31...
Wrote 8192 bytes (31 compressed) at 0x00009000 in 0.1 seconds (effective 448.0 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...
INFO Successfully uploaded program.
INFO UART logging is disabled (baud_rate=0). Not starting UART logs.
```

But... I do not see the device fetch an IP address. So it also does not show up in ESPhome. When I power the Panel after the process the information displayed on the display look pretty much like the original factory state...

So what am I missing here?
![TXwCVZNnT0Sn1OsBGbEANQ](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/28976792/9f553f05-2468-46a5-b6a2-0b03e39fb217)

Is this line in the device's YAML really optional?
`  nextion_update_url: "http://homeassistant.local:8123/local/nspanel_eu.tft"  # Optional`

Remark:
I do not use the ESPHome HA integration because HA is running in a container on K3s. Maybe this has an impact as well somehow...

**Comment by edwardtfn** [comment]
> Is this line in the device's YAML really optional? ` nextion_update_url: "http://homeassistant.local:8123/local/nspanel_eu.tft" # Optional`

Yes, that is needed only if your panel doesn't have Internet access, but it certainly not related to the issue you are reporting.


> Remark: I do not use the ESPHome HA integration because HA is running in a container on K3s. Maybe this has an impact as well somehow...

That shouldn't be an issue.

Do you have anything special in your network? Vlans, etc?

When it fails to connect to your WiFi, it should enable the AP mode. Can you see any AP/SSID published by your panel?

Maybe you could try to enforce an ip manually:
-  https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/docs/customization.md#manual-ip 
- https://esphome.io/components/wifi.html#manual-ips

**Reply by elronzo** [reply]
> When it fails to connect to your WiFi, it should enable the AP mode. Can you see any AP/SSID published by your panel?

Where would that be set? The AP-Part is also not in mydevice.yaml.

**Comment by elronzo** [comment]
I doubt that mydevice.yaml is correct.  [https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/docs/install.md#preparation](url) states "Clear all existing content and paste the following YAML configuration:" and I honestly doubt that this is entirely correct. (especially the "clear all existing content" part) What was left in my YAML file is 

```
substitutions:
  # Settings - Editable values
  device_name: "YOUR_NSPANEL_NAME"
  friendly_name: "Your panel's friendly name"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  nextion_update_url: "http://homeassistant.local:8123/local/nspanel_eu.tft"  # Optional
  # Add-on configuration (if needed)
  # heater_relay: "1"  # Possible values: "1" or "2"

# Customization area
##### My customization - Start #####
##### My customization - End #####

# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    refresh: 300s
    files:
      - nspanel_esphome.yaml # Basic package
      # Optional advanced and add-on configurations
      # - esphome/nspanel_esphome_advanced.yaml
      # - esphome/nspanel_esphome_addon_ble_tracker.yaml
      # - esphome/nspanel_esphome_addon_bluetooth_proxy.yaml
      # - esphome/nspanel_esphome_addon_climate_cool.yaml
      - esphome/nspanel_esphome_addon_climate_heat.yaml
      # - esphome/nspanel_esphome_addon_climate_dual.yaml
```

And I think this is missing essential parts like:

`esp32:
  board: esp32dev
  framework:
    type: arduino`

As this is my first time flashing an ESP32 by using ESPhome I cannot really tell which parts are essential and which ones can be omitted.
