### DISCUSSION TITLE
Can i change the colour based on a value

### DISCUSSION THREAD

**Discussion by asantaga** [Blackymas/NSPanel_HA_Blueprint#2142] [General]
Hey all,

Nice integration. Can i change the colour of an item based on a templated or something? 
e,.g.. I have one of the home page entitie states the value of a stock market symbol. I know I can set the colour of the text, but can i make it dynamic in someway ? ie more than 20 greed, less than 20 red and so on?

**Comment by asantaga** [comment]
I think I just worked iut out.. 

I worked out that from HA I can call a service mypanel_component_color  as part of automation , so Ive coded this

```
alias: nspanel1_orcl_trending_down
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.yahoofinance_orcl
    attribute: trending
condition: []
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: sensor.yahoofinance_msft
            attribute: trending
            state: down
        sequence:
          - service: esphome.mynspanel_component_color
            data:
              id: home.value01
              color:
                - 255
                - 0
                - 0
    default:
      - service: esphome.mynspanel_component_color
        data:
          id: home.value-01
          color:
            - 0
            - 255
            - 0
mode: single
```

i think it works...
