### DISCUSSION TITLE
NSPanel and custom climate page

### DISCUSSION THREAD

**Discussion by jurgenvp** [Blackymas/NSPanel_HA_Blueprint#2160] [General]
Hi guys,

I have a question regarding presenting custom climate template buttons in NSPanel.
To explain my situation, at home we are using a central duct air HVAC system. And to control this system I use Home Assistant to change different modes in different rooms. Here a screenshot of my custom HVAC control card.
![image|436x500](upload://rs0dNXjOhDq5OCHsKEfjO5Ul3ns.png)

My custom:mushroom-template-card, see settings below, is using automation who is controlling the HVAC settings and the valves per room. :-)

```
type: custom:mushroom-template-card
primary: >-
  {% if is_state('switch.ventiel_airco_ouders', 'on') and
  is_state('climate.air_conditioner_1', 'cool') %}
    Koelen Aan
  {% else %}
    Koelen
  {% endif %}
secondary: ''
icon: mdi:snowflake
tap_action:
  action: call-service
  service: automation.trigger
  target:
    entity_id: automation.hvac_slaapkamer_ouders_koelen_2
  data:
    skip_condition: true
entity: climate.air_conditioner_1
icon_color: >-
  {% if is_state('switch.ventiel_airco_ouders', 'on') and
  is_state('climate.air_conditioner_1', 'cool') %}
    blue
  {% else %}
    black
  {% endif %}
badge_color: ''
fill_container: true
multiline_secondary: false
badge_icon: ''
layout: vertical
card_mod:
  style: |
    ha-card {
      color: red;
      font-size: 10px;
    }

```
And here more info regarding the automations behind these template buttons.

I control 4 rooms, and each room has 4 automations, heating, cooling, ventilation and off.
Here a screenshot from 1 room.
![image|690x242](upload://u9tsrsWq53XBtfqaY4mDyoDWxXt.png)

And here the automation details for the setting "Heating"

```
alias: HVAC Slaapkamer ouders VERWARMEN
description: ""
trigger: []
condition: []
action:
  - type: turn_on
    device_id: 3c24433e214d191ffbe45c4aace8ee1f
    entity_id: 2db159cb2c28fb9b0a7669b2bc59dc35
    domain: switch
  - device_id: 460f2bca99d3df96c322e8d9cd59a0cd
    domain: climate
    entity_id: climate.air_conditioner_1
    type: set_hvac_mode
    hvac_mode: heat
mode: single
```

And here the automation details to turn off.

```
alias: HVAC Slaapkamer ouders UIT
description: ""
trigger: []
condition: []
action:
  - if:
      - condition: state
        entity_id: switch.shelly1_485519c90c65
        state: "off"
      - condition: state
        entity_id: switch.ventiel_airco_lukas
        state: "off"
      - condition: state
        entity_id: switch.shelly1_485519c8fe67
        state: "off"
    then:
      - type: turn_off
        device_id: 3c24433e214d191ffbe45c4aace8ee1f
        entity_id: 2db159cb2c28fb9b0a7669b2bc59dc35
        domain: switch
      - device_id: 460f2bca99d3df96c322e8d9cd59a0cd
        domain: climate
        entity_id: climate.air_conditioner_1
        type: set_hvac_mode
        hvac_mode: "off"
    else:
      - type: turn_off
        device_id: 3c24433e214d191ffbe45c4aace8ee1f
        entity_id: 2db159cb2c28fb9b0a7669b2bc59dc35
        domain: switch
mode: single
```
The automation wit setting "off" is looking if other rooms are still active, if yes, he will close only the air valve from this specific room and not the entire HVAC. if other rooms are also off, than he will also power off the HVAC. :-)

Is there any way, now or in the future to present these templates in a NSPanel?
My plan is to install in each room a NSPanel to control these settings, and of course other settings. :slight_smile: 

Regards,

      Jurgen
