### DISCUSSION TITLE
DIY Screen support

### DISCUSSION THREAD

**Discussion by monzsca** [Blackymas/NSPanel_HA_Blueprint#2162] [Ideas]
Hello, after finding this project, I decided to get a NSPanel. Very happy with the results and ease of installation. Since the hardware seemed relatively simple, I decided to try making one with a larger screen. So I acquired a 5" Nextion (nx8048p050-011c) display and give it a try.

I was able to get it working with just a few config/code changes. The TFT file needs to be modified for the larger screen, which isn't difficult, just time consuming. I'm using this with a ESP32-WROVER-E because it has psram, though I was able to get it working wiht a ESP32-WROOM by removing the psram option in the yaml file, this caused OTA TFT upload to not work, but seemed to work ok otherwise.

I was thinking this software could be easily modified to provide both an easy install for NSPanels, but also add the ability to provide configuration that overrides defaults for DIY panels, such as gpio assignments, turn features on and off, etc. In my case, I needed to change gpio pins for the tx/rx for the display and remove gpio settings for psram so it defaulted to the default. Features like buttons, relays and temperature I'm simply ignoring. They also make 7" and 10.1" screens, so there's quite a bit of potential to support many custom screens.

![IMG_0326](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/173107141/7e4c039d-003c-44d5-b7b2-d39007c6818f)

**Comment by thelord-akir** [comment]
Hi Monzsca,
I am trying to do the same. I have a wrover and a separate nextion tft. How can I compile this project and adapt uard pins?

**Reply by edwardtfn** [reply]
Please take a look at this:

- #2514

**Comment by monzsca** [comment]
I haven't looked at this in a wile but it looks like i modified a local copy of nspanel_esphome_core.yaml with the following:

```
##### UART FOR NEXTION DISPLAY #####
uart:
  - id: tf_uart
    tx_pin: 32 #16
    rx_pin: 33 #17
    baud_rate: 115200
```

Looks like I used 32 and 33.

**Reply by edwardtfn** [reply]
You don't have to use a local copy of those files. Instead, try to extend to your panel's yaml, so you can still use remote packages.

Something like this:

```
##### UART FOR NEXTION DISPLAY #####
uart:
  - id: !extend tf_uart
    tx_pin: 32 #16
    rx_pin: 33 #17
    baud_rate: 115200
```

**Reply by thelord-akir** [reply]
Hi, I have tried this configuration. After flashing the ESP Wrover does not start. I also cant see anything in the Log.

```yaml
#####################################################################################################
##### NSPANEL ESPHOME created by Blackymas - https://github.com/Blackymas/NSPanel_HA_Blueprint  #####
##### ESPHOME CORE                                                                              #####
##### PLEASE only make changes if it is necessary and also the required knowledge is available. #####
##### For normal use with the Blueprint, no changes are necessary.                              #####
#####################################################################################################
---
substitutions:
  ##############################
  ## Change only in your      ##
  ## local yaml substitutions ##
  device_name: sauna-steuerung
  name: ${device_name}
  friendly_name: ${device_name}
  ota_password: ${wifi_password}
  temp_units: "°C"
  invalid_cooldown: "100ms"
  bytes_per_char: "1"
  ##############################

esp32:
  board: esp32dev
  framework:
    type: arduino


#15-uart_nextion rx
#2-uart_nextion tx
#13-uart_dfplayer rx
#12-uart_dfplayer tx
#old_12-uart_dfplayer rx
#old_13-uart_dfplayer tx
#3-dallas sensor
#1-led ws2813


# Customization area
##### My customization - Start #####
##### My customization - End #####

# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    refresh: 300s
    files:
      - nspanel_esphome.yaml # Basic package
      # Optional advanced and add-on configurations
      # - esphome/nspanel_esphome_advanced.yaml
      # - esphome/nspanel_esphome_addon_ble_tracker.yaml
      # - esphome/nspanel_esphome_addon_bluetooth_proxy.yaml
      # - esphome/nspanel_esphome_addon_climate_cool.yaml
      # - esphome/nspanel_esphome_addon_climate_heat.yaml
      # - esphome/nspanel_esphome_addon_climate_dual.yaml
      # - esphome/nspanel_esphome_addon_cover.yaml

uart:
  - id: !extend tf_uart
    tx_pin: 15
    rx_pin: 2
    baud_rate: 115200

# Limit the amount of resources used for compiling
esphome:
  compile_process_limit: 1
```

Logs (after reset):
```txt
[12:21:24]boguscommand=0���DRAKJHSUYDGBNCJHGJKSHBDN���connect���boguscommand=0���DRAKJHSUYDGBNCJHGJKSHBDN���connect���boguscommand=0���DRAKJHSUYDGBNCJHGJKSHBDN���connect���boguscommand=0���DRAKJHSUYDGBNCJHGJKSHBDN���connect���boguscommand=0���DRAKJHSUYDGBNCJHGJKSHBDN���connect���ets����8 &���0�&���
[12:21:24]C!��:0�LB�=]ION_��UQ),b���0x3�B�A�_F�*�e�ASH%==Q)
```
