### DISCUSSION TITLE
My-new-nspanel.yaml configuration file

### DISCUSSION THREAD

**Discussion by kliko22** [Blackymas/NSPanel_HA_Blueprint#2172] [Q&A]
I'm new here and I want to install this on my NSpanel, but with the installation I can't find "My-new-nspanel.yaml" file. It's in the install manual only a picture.

**Comment by edwardtfn** [comment]
That file might have a different name in your system depending the name you gave when creating your panel on ESPHome Dashboard.

https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/docs/install.md#setting-up-a-device-on-esphome-dashboard

**Reply by kliko22** [reply]
It’s not in my system but in the installation manual. There is told to clean the configuration file and paste the text from the manual. But the new version is only a picture and not a text I can copy. (Step 8 of the install manual)

**Reply by edwardtfn** [reply]
Step 8 should contain the text-like code before the picture:
![IMG_6822](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/95f90af1-a631-45e3-abff-e3114279e5fa)

Anyways, this is the code: 😉
```yaml
substitutions:
  # Settings - Editable values
  device_name: "YOUR_NSPANEL_NAME"
  friendly_name: "Your panel's friendly name"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  nextion_update_url: "http://homeassistant.local:8123/local/nspanel_eu.tft"  # Optional
  # Add-on configuration (if needed)
  # heater_relay: "1"  # Possible values: "1" or "2"

# Customization area
##### My customization - Start #####
##### My customization - End #####

# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    refresh: 300s
    files:
      - nspanel_esphome.yaml # Basic package
      # Optional advanced and add-on configurations
      # - esphome/nspanel_esphome_advanced.yaml
      # - esphome/nspanel_esphome_addon_ble_tracker.yaml
      # - esphome/nspanel_esphome_addon_bluetooth_proxy.yaml
      # - esphome/nspanel_esphome_addon_climate_cool.yaml
      - esphome/nspanel_esphome_addon_climate_heat.yaml
      # - esphome/nspanel_esphome_addon_climate_dual.yaml
      # - esphome/nspanel_esphome_addon_cover.yaml
```
