### DISCUSSION TITLE
Send TCP Command when HA is Offline

### DISCUSSION THREAD

**Discussion by zyankali333** [Blackymas/NSPanel_HA_Blueprint#2183] [Q&A]
Hello,

I have a question and hope maybe there is just a simple Solution but my code Skills are too low for it :D

I have a TCP Server that converts TCP Packets to Modbus and then switchtes Relais, this works great with Node Red here is a little example how this looks in my Node Red: 

![tcp](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/69091626/e0dadeb1-2ab4-4b69-a45b-e2ca3fa47d69)

Since iam not often at home most time only for sleep my mini PC where HA is hosted is Off the most time.

Now i was wondering if it would be possible to send the TCP Packets from the NS Panel when HA is Offline.
I can also trigger the Relais like that via SSH in my Ubuntu PC :

`echo -e "\x01\x06\x00\x04\x00\x04\xc9\xc8" | nc 192.168.2.123 501`

Now i saw the Documentation and was thinking about something like that :

```
# Customization area
##### My customization - Start #####
binary_sensor:
  # Left button custom action: Push button / Momentary switch - Relay 1
  - id: !extend left_button
    on_click:
      then: echo -e "\x01\x06\x00\x04\x00\x04\xc9\xc8" | nc 192.168.2.123 501


  # Right button custom action: Push button / Momentary switch - Relay 2
  - id: !extend right_button
    on_click:
      then:



##### My customization - End #####
```

Since i only need 2 Buttons when HA is off the Hardware Buttons would be perfect, is this Possible to do ? can the NS Panel send something to my Network when HA isnt Online?

And if so how could i change the Customization Code that this would send the TCP ?

If anyone has an idea i would be rly thankfull and sry for my Bad English.

Edit:

I found the Solution with a little Help from Chatgpt, i post it if someone trys to do something similar

```
binary_sensor:
  # Left button custom action: Push button / Momentary switch - Relay 1
  - id: !extend left_button
    on_click:
      then:
        - lambda: |-
            using namespace esphome::socket;
            int sock = ::socket(AF_INET, SOCK_STREAM, 0);
            if (sock < 0) {
              ESP_LOGE("custom", "Failed to create socket");
              return;
            }
            struct sockaddr_in dest;
            dest.sin_family = AF_INET;
            dest.sin_port = htons(501);
            dest.sin_addr.s_addr = inet_addr("192.168.2.123");
            if (connect(sock, (struct sockaddr *)&dest, sizeof(dest)) < 0) {
              ESP_LOGE("custom", "Failed to connect to the server");
              close(sock);
              return;
            }
            uint8_t data[] = {0x02, 0x06, 0x00, 0x01, 0x00, 0x04, 0xD9, 0xFA};
            send(sock, data, sizeof(data), 0);
            close(sock);

  - id: !extend right_button
    on_click:
      then:
        - lambda: |-
            using namespace esphome::socket;
            int sock = ::socket(AF_INET, SOCK_STREAM, 0);
            if (sock < 0) {
              ESP_LOGE("custom", "Failed to create socket");
              return;
            }
            struct sockaddr_in dest;
            dest.sin_family = AF_INET;
            dest.sin_port = htons(501);
            dest.sin_addr.s_addr = inet_addr("192.168.2.123");
            if (connect(sock, (struct sockaddr *)&dest, sizeof(dest)) < 0) {
              ESP_LOGE("custom", "Failed to connect to the server");
              close(sock);
              return;
            }
            uint8_t data[] = {0x02, 0x06, 0x00, 0x00, 0x00, 0x04, 0x88, 0x3A};
            send(sock, data, sizeof(data), 0);
            close(sock);

```
