### DISCUSSION TITLE
Bluetooth Proxy Add-on Bricked Device

### DISCUSSION THREAD

**Discussion by Maxcodesthings** [Blackymas/NSPanel_HA_Blueprint#2197] [General]
I unintentionally enabled the configuration for the bluetooth proxy. It took my memory to 95% and the device wouldnt boot. When i went to flash it by serial adapter, ESPHome could no longer connect. I am not sure if this is intended but running out of memory is scarier that the documentation leads you to believe. It actually bricks your device

**Comment by edwardtfn** [comment]
You are always able to flash a new (cleaner?) firmware via serial. Please try again as this should work.
Could you please share the yaml used when your panel got out of memory? Please remove any sensitive info before sharing.

**Reply by Maxcodesthings** [reply]
I don't know what happened then, i definitely connected it correctly and it would not connect to the board.
```
substitutions:
  # Settings - Editable values
  device_name: "master-nspanel"
  friendly_name: "Master NSPanel"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  nextion_update_url: "http://192.168.1.50:8123/local/nspanel_eu.tft"  # Optional
  temp_units: "°F"
  # Add-on configuration (if needed)
  # heater_relay: "1"  # Possible values: "1" or "2"

# Customization area
##### My customization - Start #####
api:
  encryption:
    key: !secret master_nspanel_api
##### My customization - End #####

# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    refresh: 300s
    files:
      - nspanel_esphome.yaml # Basic package
      # Optional advanced and add-on configurations
      # - esphome/nspanel_esphome_advanced.yaml
      # - esphome/nspanel_esphome_addon_ble_tracker.yaml
      - esphome/nspanel_esphome_addon_bluetooth_proxy.yaml
      # - esphome/nspanel_esphome_addon_climate_cool.yaml
      # - esphome/nspanel_esphome_addon_climate_heat.yaml
      # - esphome/nspanel_esphome_addon_climate_dual.yaml
      # - esphome/nspanel_esphome_addon_cover.yaml
```
