### DISCUSSION TITLE
Stuck on Bootup - wrong ESPhome?

### DISCUSSION THREAD

**Discussion by thesebastianf** [Blackymas/NSPanel_HA_Blueprint#2210] [Q&A]
Hey
I just upgraded my NSPanel. Directly when I flash it it just boots up and shows the Home page.
When I power it off or reboot it it gets stuck while loading...
showing:

TFT: 4.3.9
ESP: 4.0.2
Bluep: waiting

where is ESP version it shows actually coming from?
I cleaned the build files and flashed it from ESP 2024.7.2

When I flash it again .. it again works normally until restart or reboot...

I think I miss something basic... but seems like I am blind here :(

**Comment by thesebastianf** [comment]
to add 
this is the part of my yaml and I think it should show ESP 4.3.9 after flashing? as this is the version of main?
```

##### DO NOT CHANGE ANYTHING! #####

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    refresh: 300s
    files:
      - nspanel_esphome.yaml # Basic package
      # Optional advanced and add-on configurations
      # - esphome/nspanel_esphome_advanced.yaml
      # - esphome/nspanel_esphome_addon_ble_tracker.yaml
      - esphome/nspanel_esphome_addon_bluetooth_proxy.yaml
      # - esphome/nspanel_esphome_addon_climate_cool.yaml
      # - esphome/nspanel_esphome_addon_climate_heat.yaml
      # - esphome/nspanel_esphome_addon_climate_dual.yaml
      # - esphome/nspanel_esphome_addon_cover.yaml

esp32:
  framework: 
    type: esp-idf
    

##### DO NOT CHANGE ANYTHING! #####
```
