### DISCUSSION TITLE
Stuck on Initializing Screen

### DISCUSSION THREAD

**Discussion by paganl** [Blackymas/NSPanel_HA_Blueprint#2216] [Q&A]
Stuck on the Initializing Screen "Blue Screen"; it doesn't connect to Wifi! I Don't get the IP address shown. The last line in the logs, viewed using Web - ESPHome; (updating using USB and Web ESPHome) 

[16:40:21]I (0) cpu_start: Starting scheduler on APP CPU.
[logs (2).txt](https://github.com/user-attachments/files/16564100/logs.2.txt)

The configuration YAML file is the default. 

after a minute, it recycles. 

If I use the default configuration, it connects to Wi-Fi, so the credentials are not the problem. I've deleted everything and reinstalled it, but it's still the same. I've removed all add-ons, so it's only loading the core components. 

Any help ideas would be appreciated. 

I have found similar issues, and I've tried things like "!remove network" (or was it wi-fi), etc, sorry if I've missed something. 

Paul

**Comment by edwardtfn** [comment]
Please don't use `!remove` for this.

Could you please share your panel's yaml and logs?

**Comment by paganl** [comment]
update:

I just used the v4.2.5b. I needed to add a platform key to the OTA section, but it worked—at least it connected.
@edwardtfn I've attached the YAML file, but it's changed frequently as I've been learning and experimenting. This is the one that worked with v4.2.5b.


```
substitutions:
  # Settings - Editable values
  device_name: "attic-nspanel"
  friendly_name: "Attic NSPanel"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  nextion_update_url: "http://10.0.0.3:8123/local/nspanel_eu.tft"  # Optional
  # Add-on configuration (if needed)
  # heater_relay: "1"  # Possible values: "1" or "2"
  
# Enable Home Assistant API
api:
  encryption:
    key: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

wifi:
  use_address: 10.0.0.56
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Attic-Nspanel Fallback Hotspot"
    password: "xxxxxxxxxxxxxxxxxx"


ota:
   - platform: esphome
#  password: "xxxxxxxxxxxxxx"

# Customization area
##### My customization - Start #####
##### My customization - End #####

# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: v4.2.5b
    refresh: 300s
    files:
      - nspanel_esphome.yaml # Basic package
      # Optional advanced and add-on configurations
      # - esphome/nspanel_esphome_advanced.yaml
      # - esphome/nspanel_esphome_addon_ble_tracker.yaml
      # - esphome/nspanel_esphome_addon_bluetooth_proxy.yaml
      # - esphome/nspanel_esphome_addon_climate_cool.yaml
      # - esphome/nspanel_esphome_addon_climate_heat.yaml
      # - esphome/nspanel_esphome_addon_climate_dual.yaml
      # - esphome/nspanel_esphome_addon_cover.yaml
```



Many Thanks for any help

Paul
