### DISCUSSION TITLE
Added own button on HMI; eshome customization not working...

### DISCUSSION THREAD

**Discussion by paddenstoeltje** [Blackymas/NSPanel_HA_Blueprint#2239] [Q&A]
Hi I've added a button on a test page (component id 1 on page id 28) to the HMI; so I could add some functionality to the HMI screen. The button press is logged to the ESPHome, hower I struggle getting it done anything. I would like to call a HA action when the button is pressed. Not to mess with the main code I've added the following in the customization section of the esphome config file:
```

binary_sensor:
  - platform: nextion
    page_id: 28         
    component_id: 1
    name: "Media Player Button"
    on_release:
      then:
        - homeassistant.service:
              service: media_player.play_media
              data:
                entity_id: media_player.denon_receiver_heos
                media_content_type: "favorite"
                media_content_id: "1"
```

When looking in the ESPhome log I have the following:

[17:57:19][D][nextion:457]: Got touch event:
[17:57:19][D][nextion:458]:   page_id:      28
[17:57:19][D][nextion:459]:   component_id: 2
[17:57:19][D][nextion:460]:   event type:   RELEASE

Any idea's what I'm dong wrong?

thanks!
