### DISCUSSION TITLE
keep media player in foreground during entity state = playing

### DISCUSSION THREAD

**Discussion by b2un0** [Blackymas/NSPanel_HA_Blueprint#2241] [Q&A]
i have an automation thats open the media player page 

```yaml
alias: Livingroom - Media Player NsPanel
description: ""
trigger:
  - platform: state
    entity_id:
      - media_player.livingroom_homepod
    to: playing
condition: []
action:
  - action: esphome.nspanel_livingroom_entity_details_show
    data:
      entity: media_player.livingroom_homepod
      back_page: home
mode: single
```

how can in keep this page in foreground until the entity is no more playing? is there any option i mssing?

i don't want to change the entity `nspanel_livingroom_timeout_page` in this automation

**Comment by techwatcher74** [comment]
I created an automation to manage this. I used the screen dimming as the trigger to check if the media was still playing. 
When music starts call the media player - esphome.nspanel1_entity_details_show
When music is paused wait 1min then return to home
When the screen brightness changes check the media state if playing return to the media player detail page. (this allows me to navigate to another page make a change or check a status and then it auto returns to the media player if still playing)

```
alias: NSPanel1 music sync
description: ""
trigger:
  - platform: device
    device_id: c1df7847f8cf65dcb1015029cdf65d6b
    domain: media_player
    entity_id: 3c6f13ba9efbe46602705cdfab18180a
    type: playing
    id: playing
  - platform: device
    device_id: c1df7847f8cf65dcb1015029cdf65d6b
    domain: media_player
    entity_id: 3c6f13ba9efbe46602705cdfab18180a
    type: paused
    id: paused
  - type: value
    platform: device
    device_id: be6b0e7f94b7e246e19c2660942ffbb6
    entity_id: 5104d0edae8d1a12443b936554abfb06
    domain: sensor
    for:
      hours: 0
      minutes: 1
      seconds: 0
    id: sleep
    below: 50
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - playing
        sequence:
          - action: esphome.nspanel1_entity_details_show
            data:
              entity: media_player.den
              back_page: home
      - conditions:
          - condition: trigger
            id:
              - paused
        sequence:
          - delay:
              hours: 0
              minutes: 2
              seconds: 0
              milliseconds: 0
          - action: esphome.nspanel1_command
            data:
              cmd: page home
      - conditions:
          - condition: and
            conditions:
              - condition: trigger
                id:
                  - sleep
              - condition: device
                device_id: c1df7847f8cf65dcb1015029cdf65d6b
                domain: media_player
                entity_id: 3c6f13ba9efbe46602705cdfab18180a
                type: is_playing
        sequence:
          - action: esphome.nspanel1_entity_details_show
            data:
              entity: media_player.den
              back_page: home
      - conditions:
          - condition: and
            conditions:
              - condition: trigger
                id:
                  - sleep
              - condition: device
                device_id: c1df7847f8cf65dcb1015029cdf65d6b
                domain: media_player
                entity_id: 3c6f13ba9efbe46602705cdfab18180a
                type: is_paused
        sequence:
          - action: esphome.nspanel1_command
            data:
              cmd: page home
mode: single

```
