### DISCUSSION TITLE
Setup BSSID instead of SSID for NSPANEL

### DISCUSSION THREAD

**Discussion by iamthe1st** [Blackymas/NSPanel_HA_Blueprint#2270] [Q&A]
Hi, i have a WIFI Mesh setup at home.
The Problem is, that the NS-Panel often connects to the for away accesspoint with low signal strength.
Using the Display is extremly slow and annoying then.

How can i setup the NSPANEL to connect to an fixed BSSID (indvidiual MAC-address for each Accesspoint) instead of the SSID (same for all Accesspoints) ?

it is possible in Standard ESPHOME, but i do not know how to translate it to the "blueprint".

```
wifi:
  networks:
  - bssid: A0:B7:35:54:D7:F8
```

Thanks a lot in advance!

**Comment by edwardtfn** [comment]
This should work:

```yaml
# Connect to a specific BSSID
wifi:
  networks:
    - id: !extend wifi_default
      bssid: A0:B7:35:54:D7:F8
```

Please try that and let me know your results.
