### DISCUSSION TITLE
FQDN usage

### DISCUSSION THREAD

**Discussion by Phalen** [Blackymas/NSPanel_HA_Blueprint#2352] [Q&A]
I am trying to get a FQDN to work as mdns does not work.  device is accessible with no issues on the network at its ip which is stated in the configh with the following  that were entered in the substitutions: section. 

domain:  .xxx.com
use_address: "10.x.x.x"

INFO Resolving IP address of nspanel1.local
ERROR Error resolving IP address of nspanel1.local. Is it connected to WiFi?

**Comment by edwardtfn** [comment]
Try to add the config you want directly as a Wi-Fi configuration and not in the substitutions.
Something like this:
```yaml
wifi:
  domain: .xxx.com
  use_address: "10.x.x.x"
  # Optional manual IP
  manual_ip:
    static_ip: 192.168.0.123
    gateway: 192.168.0.1
    subnet: 255.255.255.0
```

Or any other config you want...

You will find some examples in the documentations, specially in the customizations area.
