### DISCUSSION TITLE
What to do from Lovelace UI / Tasmota version

### DISCUSSION THREAD

**Discussion by coelhoricardo** [Blackymas/NSPanel_HA_Blueprint#2373] [General]
Hi,
My english is not very good and I don't what know I need to do from a NSPanel with Lovelace UI / Tasmota version.

I managed to apply nspanel_blank.tft then nspanel_eu.tft.

my current epshome yaml :
```
esphome:
  name: nspanel
  friendly_name: tasmato-nspanel-8144

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "KEYREPLACED"

ota:
  - platform: esphome
    password: "PASSWORD REPLACED"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Tasmato-Nspanel-8144"
    password: "Ozty1T3j1Emb"

  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.1.52
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.1.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0

captive_portal:
    
```

but compilation finishes with
```
INFO Successfully compiled program.
INFO Connecting to 192.168.1.52
ERROR Connecting to 192.168.1.52:3232 failed: [Errno 111] Connection refused
```

Thanks for the help
