### DISCUSSION TITLE
Timeout reset for hardware button actions

### DISCUSSION THREAD

**Discussion by Msmax2729LK** [Blackymas/NSPanel_HA_Blueprint#2405] [Q&A] [answered]
Hi there,

I like to switch off the actions (R1/R2) initiated by pressing the hardware buttons after a set time:

first press left button: R1 ON
second press left button: R1 OFF

Till so far it is clear for me how to do...but then:
Without a second press the relay (and indications on the display) should switch off after a set time.

Same for right button and R2.
How to do this locally on the panel so that it also works if connection to HA is lost?

Regards, Msmax

**Comment by edwardtfn** [comment]
So, you wanna limit the time the relay is on, right?

**Reply by edwardtfn** [reply, marked as answer]
Try adding this as a customization to your panel's yaml:

```yaml
switch:
  - id: !extend relay_1
    on_turn_on:
      - delay: 30s  # Select the time to be `on` before turn `off` automatically
      - switch.turn_off: relay_1
```
You can copy the same for relay 2, just change to `relay_2` accordingly.
