### DISCUSSION TITLE
Hardware buttons

### DISCUSSION THREAD

**Discussion by fuzzysb** [Blackymas/NSPanel_HA_Blueprint#243] [Ideas]
I currently have my own custom nspanel setup, however this project really does appeal to me. however there is a shortfall for this from the looks of it. 

I currently mainly use these switches in rooms where I have smart bulbs, I use the hardware buttons to power on and off the smart bulbs directly rather than the Relay.

So Short Press = Toggle Smart Light.
Long Press of 5 seconds = Toggle Relay.
Double short click = cycle through scenes.

if you could enable this sort expansion to the switch settings i would use as it looks like you have done a great job here.  I mainly use the toggle relay functionality as a backup for Home Assistant/ESPHome/Wifi outages, so I still have a standalone method of toggling the relay without requiring the the home assistant connection.

**Comment by ghost** [comment]
Hi fuzzy,
Myself and at least 1 of the other developers have a similar setup. In version 3.1.0 the switch will revert to toggling the really is the connection to Home Assistant is down if you enable this option (set per relay). For normal use you could add the relay as a switch on one of the pages if you want to be able to restart a bulb.

The scenes one is interesting as it's something I plan to look at very soon and discuss with rest of Dev team and it's something I would like too (I did hold to dim previously) but I need to check what I can make fit with the way this project is structured.

**Comment by fuzzysb** [comment]
Interesting, sorry i didnt realise the relay backup was a feature, I will try this out now. as for the scenes, currently I list the scenes as an input select as per the image below 
![image](https://user-images.githubusercontent.com/16162689/214552772-57f21315-8f20-4ac0-b5c8-8f1e3453c32e.png)

I then have an automation rule as per the following 

![image](https://user-images.githubusercontent.com/16162689/214553138-13ba679f-445c-4a58-8498-a67c19194bae.png)

then the esphome yaml for the double-click is as follows:

```
on_multi_click:
    - timing:
      - On for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at least 0.2s
      then:
        - logger.log: "$device_name Double Clicked"
        - homeassistant.service:
            service: input_select.select_next
            data:
              entity_id: input_select.orangery_scenes
```

so any integration should just have the ability to select the next entry in an input select helper, then the automation rules take care of the rest. not sure you need anything more encompassing. 

I will test and drop some further donations for any other questions/feature requests. many thanks .
