### DISCUSSION TITLE
Beginners Question. Which firmware should be used? First flash

### DISCUSSION THREAD

**Discussion by alphabravocharly72** [Blackymas/NSPanel_HA_Blueprint#2439] [General]
Hello,
I hava a few EU und one US NSPanel. It is all set up for the first flash with the esphome homepage. Now I am looking for the correct firmware. But which .bin should I take?
nspanel_esphome-prebuilt.bin
nspanel_esphome-prebuilt.bin.md5
wall_display.bin
wall_display.factory.bin
nspanel-esp32.factory.bin
nspanel-esp32.ota.bin
wall-display-esp32.factoty.bin
Thx for helping

**Comment by edwardtfn** [comment]
My first suggestion would always be on the direction of using the YAML provided in our [installation docs](https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/docs/install.md#setting-up-a-device-on-esphome-dashboard) and build your solution locally:
```yaml
substitutions:
  # Settings - Editable values
  device_name: "YOUR_NSPANEL_NAME"
  friendly_name: "Your panel's friendly name"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  nextion_update_url: "http://homeassistant.local:8123/local/nspanel_eu.tft"  # Optional
  # Add-on configuration (if needed)
  # heater_relay: "1"  # Possible values: "1" or "2"

# Customization area
##### My customization - Start #####
##### My customization - End #####

# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    refresh: 300s
    files:
      - nspanel_esphome.yaml # Basic package
      # Optional advanced and add-on configurations
      # - esphome/nspanel_esphome_advanced.yaml
      # - esphome/nspanel_esphome_addon_ble_tracker.yaml
      # - esphome/nspanel_esphome_addon_bluetooth_proxy.yaml
      # - esphome/nspanel_esphome_addon_climate_cool.yaml
      - esphome/nspanel_esphome_addon_climate_heat.yaml
      # - esphome/nspanel_esphome_addon_climate_dual.yaml
      # - esphome/nspanel_esphome_addon_cover.yaml
```

If you cannot build locally, then you have to consider the pre-built options, which we still considering "Experimental".
Anyways, the one named "Pre-built" is the public one, while "Wall Display" is a commercial version distributed by one of our users. The basic difference, apart of naming, is the inclusion of Add-On Climate Heat into the Wall Display. Both provides an option to upload the firmware via HTTP on this repo, so you don't need to compile the firmware when a new version is available. You don't have even to have ESPHome Builder installed in your side.
Once you decided for one of the pre-built (if you decide this way), then the binary will depend on how you are installing the firmware to your device. The most common way is using the [ESPHome Web](https://web.esphome.io/) flasher, which will use the file named "factory". Other installers may require the other file.
