### DISCUSSION TITLE
Old ota getting in the way

### DISCUSSION THREAD

**Discussion by mcfarlde** [Blackymas/NSPanel_HA_Blueprint#2441] [Q&A] [answered]
I am updating from the an old NSPanel solution using esphome in which I had set ota password.  I cannot determine how to add this to the new initial yaml to allow flashing over the air.   I have tried:
```yaml
ota:
 platform: "esphome"
 password: "password" 
```
and all variants with and without quotes.  The stock yaml, without the ota addition, seems to use my wifi password for the ota password when looking at the results of a validate.

**Comment by edwardtfn** [comment, marked as answer]
Please try this:

```yaml 
# Use my global OTA password
ota:
  - id: !extend ota_std
    password: your_ota_password
```

Source: https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/docs/customization.md#custom-ota-password
