### DISCUSSION TITLE
Call Climate Page

### DISCUSSION THREAD

**Discussion by ParanoiaCY** [Blackymas/NSPanel_HA_Blueprint#2443] [Q&A] [answered]
Hi there.
I'm trying to call the Climate page (like when you press the temperature on the home screen), externally. 
The way that i will like to do it, is to be displayed when i call a script for example. That script can be called by pressing one of the hardware buttons, or from an other event. 

I have tried many ways, including this one ( https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/docs/howto.md#call-a-page-directly ), but the best i could get, is an empty climate page with just the bar in the middle (see attachment)

is there any way of achieving this ?

Many thanks

![photo_2024-12-25_12-57-06](https://github.com/user-attachments/assets/c40d83b7-84c7-45ea-b1a1-a823338585be)

**Comment by edwardtfn** [comment]
It should be something like this:
```yaml
- action: esphome.xxxxx_entity_details_show
  data:
    entity_id: climate.your_entity_id
    back_page: home
```

**Reply by ParanoiaCY** [reply]
Thanks for your quick reply @edwardtfn .
Unfortunately i have the same result. it loads a blank page with just the bar in the middle( the picture from my first post)

here is my yaml code of the script

```
alias: show thermostat
sequence:
  - action: esphome.nspanel_vas_wake_up
    data:
      reset_timer: true
  - action: esphome.nspanel_vas_entity_details_show
    data:
      entity: climate.nspanel_vas_thermostat
      back_page: home
```

**Comment by ParanoiaCY** [comment, marked as answer]
I have finally manage to call the climate page correctly. The method i used was:

```
  - action: esphome.xxxxxx_details_show
    data:
      entity: embedded_climate
      back_page: home
```
