### DISCUSSION TITLE
How to add customisation in base yaml

### DISCUSSION THREAD

**Discussion by PedroKTFC** [Blackymas/NSPanel_HA_Blueprint#2470] [Q&A]
In the base yaml there's a section for customisation. I've tried adding the following to light up the screen when I press a physical button but trying to load it errors.

```
# Customization area
##### My customization - Start #####

binary_sensor:
  - name: Left Button
    platform: gpio
    pin:
      number: 14
    on_press:
      - lambda: goto_page->execute("home");

##### My customization - End #####
```
Specifically, and probably not surprisingly, the error is  _Pin 14 is used in multiple places._ Is there a syntax to get around this in yaml?
