### DISCUSSION TITLE
Is it possible to remove the Temperature entities?

### DISCUSSION THREAD

**Discussion by distante** [Blackymas/NSPanel_HA_Blueprint#2501] [Q&A] [answered]
I have external Temperature and Humidity sensors and I really do not need the internal temp and humidity sensors. Plus they return inconsistent values when using the BL proxy.

Is it possible to disable them to clear memory and remove them from home assistant?

**Comment by edwardtfn** [comment, marked as answer]
The panel doesn't have a humidity sensor, so could you please clarify on that question?

About temperature, as part of v4.4, I'm making easier to remove those components when not needed. Currently this is not that easy, however you can still "hide" that from Home Assistant, keeping your system cleaner.
For that, just add this to your yaml:
```yaml
number:
  - id: !extend temperature_adjustment
    internal: true
sensor:
  - id: !extend temp_nspanel
    internal: true
```
