### DISCUSSION TITLE
Blue bars used to indicate state of physical switchs do not stay on (go dim as if indicating the lights are off after a few seconds)

### DISCUSSION THREAD

**Discussion by st2000** [Blackymas/NSPanel_HA_Blueprint#2526] [General]
I am not sure if this is a configuration problem or if there is a bug, so I'm asking about this here.

I have 2 NSPanels and they behave differently. I expected them to behave the same as I believe they are configured similarly and should be running the same firmware.

My oldest NSPanel at one time behaved as expected. The Blue bars where bright when the lights were on and dim when the lights were off. But, now they are bright for a few seconds when the lights are turned on. Then the bright Blue bars dim. But the lights are still on. If I press the physical buttons again, the light go out.

I was expecting the Blue bars to be bright when the lights are on and dim when the light are off.

The newer NSPanel does work as expected.

**Comment by edwardtfn** [comment]
Could you please shat your automation yaml? Please hide any sensitive info before sharing... 😉

**Reply by st2000** [reply]
Sure, but I thought you posted a fix was already merged into the dev or beta branch. So soon it should be generally available?

**Comment by st2000** [comment]
```yaml
alias: NSPanel101 Back Hall
description: ""
use_blueprint:
  path: Blackymas/nspanel_blueprint.yaml
  input:
    nspanel_name: ********************************************
    time_format: ********************************************
    date_format: ********************************************
    timezone: ***************************************
    weather_entity: weather.forecast_home
    indoortemp: sensor.nspanel101_temperature
    left_button_entity: switch.back_yard_park_left
    left_button_name: Park Left
    left_button_state_entity: switch.back_yard_park_left
    right_button_entity: switch.back_yard
    right_button_name: Back Yard
    right_button_state_entity: switch.back_yard
    button_page01_label: Bark Yard Lights
    entity01: switch.back_yard
    entity01_name: Back Yard
    entity01_icon: mdi:lightbulb-spot
    entity02: switch.back_yard_park_left
    entity02_name: Park Left
    entity02_icon: mdi:lightbulb-spot
    entity03: switch.back_yard_park_right
    entity03_name: Park Right
    entity03_icon: mdi:lightbulb-spot
    button_page02_label: Living Room
    entity09: switch.living_room
    entity09_name: Living Room Lights
    entity09_icon: mdi:ceiling-light-multiple-outline
    entity10: switch.switch_five
    entity10_name: Stereo
    entity10_icon: mdi:radio
    button_page03_label: Den
    entity17: light.den
    entity17_name: Den Light
    entity17_icon: mdi:ceiling-fan-light
    entity18: fan.den
    entity18_name: Den Fan
    entity18_icon: mdi:ceiling-fan
```
