### DISCUSSION TITLE
Automation fails - Unkown action

### DISCUSSION THREAD

**Discussion by ChrisHinde** [Blackymas/NSPanel_HA_Blueprint#2546] [Q&A]
I'm trying to use and setup this on a NSPanel, but I'm having issues.

The automation throws an error about an unknown action, mostly: `esphome.nspanel_command`, but also `esphome.nspanel_icon`.
And if I haven't selected a weather entity I also get `Main choices: Weather - State changed: Error executing script. Service not found for if at pos 1: Action esphome.nspanel_component_text not found`,  but I don't want any weather info (and it's marked as optional).

AFAIK I've filled in everything that's not optional.

The version of the Blueprint is `4.3.13` (according to "Automation Config" in Trace), same for ESPHome and TFT (according to the 
ESPHome integration, but it shows the Blueprinit version as unknown).

I've recompiled and reinstalled the ESPHome firmware, updated the TFT display, removed the device from HA (plus the automation and blueprint), restarted (and made sure it's updated [2025.5.3]) and reimported the blueprint etc.  No difference.

Automation config:
```
alias: NSPanel LR2 Configuration
description: ""
use_blueprint:
  path: Blackymas/nspanel_blueprint.yaml
  input:
    nspanel_name: 72eeef06651f3784019dd6807703b1ee
    date_format: "%A, %-d/%-m"
    timezone: Europe/Stockholm (CET-1CEST,M3.5.0,M10.5.0/3)
    home_value01: sensor.outside_temperature_1_2
    home_value01_icon: mdi:temperature-celsius
    home_value02: sensor.nsplr2_temperature
    home_custom_button01: switch.hall_ceiling_light
    home_value02_icon: mdi:temperature-celsius
    home_value03: sensor.outside_temperature_1_2
    home_value03_icon: fas:temperature-full
    home_value04: sensor.outside_temperature_2_3
    home_value04_icon: fas:temperature-full
    home_indoor_temp_icon: ""
```

[home-assistant_2025-05-24T18-41-53.755Z.log](https://github.com/user-attachments/files/20427680/home-assistant_2025-05-24T18-41-53.755Z.log)
[logs_nsplr2_logs.txt](https://github.com/user-attachments/files/20427681/logs_nsplr2_logs.txt)

Anything I've may have missed, or what I should try?
