### DISCUSSION TITLE
Error saving preferences to flash.

### DISCUSSION THREAD

**Discussion by thgschwind** [Blackymas/NSPanel_HA_Blueprint#2566] [Q&A] [answered]
Since upgrading to 4.3.15, I regularly see this message in my logs (like every couple of seconds:
```
[E][esp32.preferences:145]: Error saving 5 preferences to flash. Last error=ESP_ERR_NVS_INVALID_HANDLE for key=1878979320
```
Is this me having done something wrong or a bug? Anybody else seeing this?

Thanks,
Thomas

**Comment by edwardtfn** [comment]
Could you please try adding this to your panel's Yaml:

```yaml
button:
  - platform: factory_reset
    name: Restart with Factory Default Settings
```
Then flash your panel again.
After it starts again, you will see the new button under the device page (Settings > Devices and Services > ESPHome).
Please press that button. It will clean all the saved settings from that page, including your panel's model and temperature offset (the info received from the Blueprint will be sent again on the next boot), then it will restart clean.
Could you please let me know if you still having issues after that?

**Comment by thgschwind** [comment]
Thanks for the answer - tried it today. Recompiling worked fine (did not clean though, no time, it compiled `main.cpp` only), upon restart, the panel worked fine and the button appeared.  Pressing the button brought the panel in a limbo state without rebooting (I believe since it was way to quick).  Panel was no longer reachable.  Power cycling it brought it back up (after one boot failure rebooting by itself) and the panel worked "fine" again but still with the preferences error.

If I should try with cleaning the build files, let me know (then again, will do anyway if I don't hear) but I will only have access to my panel again Monday evening.

Thanks,
Thomas

**Comment by thgschwind** [comment]
Just cleaned the build files, redid the whole procedure multiple times. Sometimes, when pressing Restart with Factory Defaults, the panel restarts but then during restart fails and reboots (the 2nd reboot always(?) succeeds), sometimes when pressing the button, the panel just does not nothing and needs to be power cycled (pressing reboot on the settings page would not help either).

What has changed though, it only tries to save 2 settings (but again both of them fail).
```
[23:12:28][D][esp32.preferences:114]: Saving 2 preferences to flash...
[23:12:28][D][esp32.preferences:142]: Saving 2 preferences to flash: 0 cached, 0 written, 2 failed
[23:12:28][E][esp32.preferences:145]: Error saving 2 preferences to flash. Last error=ESP_ERR_NVS_INVALID_HANDLE for key=3022721387
```

Now, what better way to do than to try the other NSPanel as well.  The other one is currently at 4.3.13 and according to the log currently says `Saving 1 preferences to flash: 1 cached, 0 written, 0 failed`, so obviously does not have the issue.  At least not yet.  Upgrading through homeassistant (not sure what it does or does not), and after about 5 reboots "in a loop" the panel is back online. I get the `Error saving 5 preferences...`.  Next clean build files and install and again after about 5 reboots "in a loop", the panel is back online and the logs show `Error saving 2 preferences to flash...` as for the first panel.  And that without any Restart with Factory Defaults restarts.

At least the behavior seems to be consistent.

If there is anything, I can help with please let me know.
Best & Thanks, Thomas

**Comment by edwardtfn** [comment]
Could you please share your panel's yaml? Please make sure you remove any sensitive info before sharing. 😉

**Comment by thgschwind** [comment]
Sure, here it is:
```
substitutions:
  # Settings - Editable values
  device_name: "nspanel11"
  friendly_name: "Living Room Panel"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  nextion_update_url: "http://homeassistant.local:8123/local/nspanel_eu.tft"  # Optional for `esp-idf` framework

  # Add-on configuration (if needed)
  heater_relay: "1"  # Possible values: "1" or "2"
  min_off_time: "60"
  min_run_time: "60"
  min_idle_time: "15"

##### My customization - Start #####
wifi:
  # Optional manual IP
  manual_ip:
    static_ip: 192.168.xxx.110
    gateway: 192.168.xxx.1
    subnet: 255.255.255.0

ota:
  platform: esphome
  password: xxx

api:
  encryption:
    key: xxx

##### My customization - End #####

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # Optional advanced and add-on configurations
      # - advanced/esphome/nspanel_esphome_advanced.yaml
      # - nspanel_esphome_addon_climate_cool.yaml
      - nspanel_esphome_addon_climate_heat.yaml
      # - nspanel_esphome_addon_climate_dual.yaml
    refresh: 60s

esp32:
  framework:
    type: esp-idf

button:
  - platform: factory_reset
    name: Restart with Factory Default Settings

# external_components:
#   - source:
#       type: git
#       url: https://github.com/esphome/esphome
#       ref: 2025.4.2
#     components:
#       - logger

# external_components:
#   - source: github://pr#8988
#     components:
#       - logger
```

The other panel is the same, except for names (nspanel01, Office Panel), IP address, and it's omitting the off/run/idle substitutions.

What I also noticed (maybe not related?) the panels are crashing from time to time.  Once the Office Panel completely blanked and was only able to be resurrected after power cycling it.  Am actually wondering whether I better revert to 4.3.13.

Thanks for both, maintaining the nspanels and looking into this issue!

**Reply by edwardtfn** [reply]
Have you had Tasmota installed on this panel before?

> Am actually wondering whether I better revert to 4.3.13.

In fact there is one change from v4.3.13 to v4.3.14 that could be related to this, as we allocated more flash space to store the friendly name of your climate entity friendly name (from 64 to 254 bytes).
You can try reverting this back by adding the following lines to your panel's Yaml, but in this case, please make sure the friendly name of your climate entity provided by the panel isn't exceeding the 64 chars.

```yaml
globals:
  ##### Embeded climate friendly name #####
  - id: !extend addon_climate_friendly_name
    max_restore_data_length: !remove
```

Please let me know if that helps.
