### DISCUSSION TITLE
Momentary switch

### DISCUSSION THREAD

**Discussion by IversenT** [Blackymas/NSPanel_HA_Blueprint#340] [Ideas]
Would there be possible to add an option so the psychical switches are momentary when linked to relay 1 or 2? 
have an dimmer stick behind the regular switch today which uses a momentary switch to turn of/on and dim the lights.

**Comment by Blackymas** [comment]
Do not understand the question. The blue line shows the status of the entity that is stored in the blueprint.

For the relays, the icon with 1 (Releay 1) and the icon with 2 (Releay 2) are displayed at the top of the top menu.

Both are separated by an asterisk and are displayed appropriately.

**Reply by IversenT** [reply]
Would like the relay to only be activated when holding down the button. When pushing the button the relay will be activated, when released the the relay releases.

Have an external dimmer module behind the manual switch today. 
When pushed the light activates/deactivates. If I hold the button the light is dimmed down or up.

**Comment by deejaybeam** [comment]
You can create a script with:
switch.turn_on
delay 0.3s
switch.turn_off

and assing that to the button

**Reply by IversenT** [reply]
0,3 seconds would feel like much delay. 
0,1 would be better. 
Should be an option to the have the fallback option on this as in case of no connection to HA. 
Are the buttons available in NSpanel in HA?

**Comment by edwardtfn** [comment]
Is this the same as this one? https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/968#discussioncomment-6662236

**Reply by IversenT** [reply]
Perfect. This solves the challenge when the buttons on the panel are used. The challenge now is to control this from home assistant. I've created a script that turns on, waits for 150ms, and turns off. Unfortunately, there are instances where home assistant takes a bit longer, resulting in the light either not turning on/off or starting to dim.
Could it be a solution to directly incorporate this into the Esphome configuration, which would also address this issue?

**Reply by edwardtfn** [reply]
> Could it be a solution to directly incorporate this into the Esphome configuration, which would also address this issue?

But this is exactly what that solution does. It will control the relay locally, to be `on` while the button is pressed and then `off` when the button is released, like a pulse/momentary switch.

```yaml
##### MY CUSTOMIZATIONS - START #####
binary_sensor:
  - id: !extend left_button
    on_click:
      then:
    on_press:
      then:
        switch.turn_on: relay_1
    on_release:
        switch.turn_off: relay_1

  - id: !extend right_button
    on_click:
      then:
    on_press:
      then:
        switch.turn_on: relay_2
    on_release:
        switch.turn_off: relay_2
##### MY CUSTOMIZATIONS - END #####
```

**Reply by edwardtfn** [reply]
Ok, I think I got your point... you are OK with the solution from the Blueprint side, but now you want a solution to control your relay to give a 150ms pulse from Home Assistant side, is that correct?

There are different ways of doing this. You can either create a custom service to call this or create a custom button. Or both. 😆 
I probably will go for the service, as that will give me some flexibility to define a different time per call, but the service call is a bit more complex than pressing a button if you wanna put this in HA UI.

For both cases, you can do like this:
```yaml
api:
  services:
    - service: pulse_relay
      variables:
        relay: int
        milliseconds: int
      then:
        - if:
            condition:
              - lambda: !lambda return (relay == 1);
            then:
              switch.turn_on: relay_1
        - if:
            condition:
              - lambda: !lambda return (relay == 2);
            then:
              switch.turn_on: relay_2
        - delay: !lambda return milliseconds;
        - if:
            condition:
              - lambda: !lambda return (relay == 1);
            then:
              switch.turn_off: relay_1
        - if:
            condition:
              - lambda: !lambda return (relay == 2);
            then:
              switch.turn_off: relay_2

button:
  - id: relay_1_pulse
    name: Relay 1 Pulse
    platform: template
    on_press:
      - switch.turn_on: relay_1
      - delay: 150ms
      - switch.turn_off: relay_1

  - id: relay_2_pulse
    name: Relay 2 Pulse
    platform: template
    on_press:
      - switch.turn_on: relay_2
      - delay: 150ms
      - switch.turn_off: relay_2
```

**Reply by IversenT** [reply]
Correct. It works like a charm from nspanel, but if I use automations or scripts to create the delay, it's inconsistent. This inconsistency either results in the light not working or turning the light on, but just at the minimum dimmed level. (The light/dimmer dims up and down if I hold the momentary switch).

I can create a custom service, don't need the button. 
I'll try to add this and test. Should work fine when lauched directly in esphome. 
I played around a bit yesterday and created this: 

```
switch:
  - id: !extend relay_1
    on_turn_on:
      - delay: 150ms
      - switch.turn_off: relay_1

```
This works flawless from HA, but then I am not able to dim up/down from the panel.
