### DISCUSSION TITLE
Best practice for Radio Browser to Sonos Multiroom

### DISCUSSION THREAD

**Discussion by SirFiChi** [Blackymas/NSPanel_HA_Blueprint#365] [Q&A] [answered]
Hi folks,
I have created three Sonos speakers (living room, bathroom and study) and a helper button (boolean) for each.I have created three Sonos speakers (living room, bathroom and study) and a helper button (boolean) for each.
I have created three Sonos speakers (living room, bathroom and study) and a helper button (boolean) for each.
I also have four radio station buttons (o89FM, Sunshine Live, 80s80s and Carivari) and a button for radio off.
These oh switches are on one screen.
I now want to enable and disable the Sonos buttons depending on where the status is to be changed, and the four radio stations and the off button to enable or disable the respective active booleans.

What is the easiest way to implement this?
Scenes? Automations?
Current status: My booleans are detected incorrectly and via the radio browser o89FM is started, but goes on at all three speakers, even if only the study is marked.
Maybe there is a simpler integrated solution for this?

Many thanks and best regards from munich

**Comment by SirFiChi** [comment, marked as answer]
I have found a solution.

I have eight tiles. Four are radio stations, three are the Sonos speakers and one turns the radio "off".

For this I have created eight helpers. All Boolean.
Three speakers (Speaker_AZ, Speaker_WZ, Speaker_Bad).
Five for audio (NS_80s80s, NS_Charivari, NS_o89FM, NS_Sunshine, NS_RadioAus).

In the NS_Panel configuration there are eight buttons on one side that activate these eight helpers.

In the automation there are now five automations created, which trigger the four radio stations or a switch off.

The sequence (an example):
* Trigger --> When NS_o89FM changes to on
* Actions --> 
** Perform an action if: Confirm Speaker_WZ is on
*** If --> Confirm Speaker_WZ is on
*** Then --> Play 089FM.de on WZ
** Perform an action if: Confirm Speaker_Bad is on
*** If --> Confirm Speaker_Bad is on
*** Then --> Play 089FM.de on Bad
** Perform an action if: Confirm Speaker_AZ is on
*** If --> Confirm Speaker_AZ is on
*** Then --> Play 089FM.de on AZ
** Enter boolean value: Turn off NS_o89FM

Radio Off plays the Google voice output with "Radio off". After that the playback is finished, so that the Sonos speakers off.

Here is the sample code of an automation:

```
alias: Play o89FM
description: ""
trigger:
  - platform: state
    entity_id:
      - input_boolean.ns_o89fm
    to: "on"
condition: []
action:
  - if:
      - condition: state
        entity_id: input_boolean.speaker_wz
        state: "on"
    then:
      - service: media_player.play_media
        target:
          entity_id: media_player.kuche
        data:
          media_content_id: media-source://radio_browser/fd72f021-5bc6-4201-809c-8be67f4fdbd3
          media_content_type: audio/mpeg
        metadata:
          title: 089FM.de
          thumbnail: ""
          media_class: music
          children_media_class: null
          navigateIds:
            - {}
            - media_content_type: app
              media_content_id: media-source://radio_browser
            - media_content_type: music
              media_content_id: media-source://radio_browser/language
            - media_content_type: music
              media_content_id: media-source://radio_browser/language/de
  - if:
      - condition: state
        entity_id: input_boolean.speaker_bad
        state: "on"
    then:
      - service: media_player.play_media
        target:
          entity_id: media_player.bad
        data:
          media_content_id: media-source://radio_browser/fd72f021-5bc6-4201-809c-8be67f4fdbd3
          media_content_type: audio/mpeg
        metadata:
          title: 089FM.de
          thumbnail: ""
          media_class: music
          children_media_class: null
          navigateIds:
            - {}
            - media_content_type: app
              media_content_id: media-source://radio_browser
            - media_content_type: music
              media_content_id: media-source://radio_browser/language
            - media_content_type: music
              media_content_id: media-source://radio_browser/language/de
  - if:
      - condition: state
        entity_id: input_boolean.speaker_az
        state: "on"
    then:
      - service: media_player.play_media
        target:
          entity_id: media_player.arbeitszimmer
        data:
          media_content_id: media-source://radio_browser/fd72f021-5bc6-4201-809c-8be67f4fdbd3
          media_content_type: audio/mpeg
        metadata:
          title: 089FM.de
          thumbnail: ""
          media_class: music
          children_media_class: null
          navigateIds:
            - {}
            - media_content_type: app
              media_content_id: media-source://radio_browser
            - media_content_type: music
              media_content_id: media-source://radio_browser/language
            - media_content_type: music
              media_content_id: media-source://radio_browser/language/de
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.ns_o89fm
mode: single

```

Now you can select on which Sonos speaker the program should change, and when the selection is made you can tap the button for the station or radio off, and the speakers will change the radio station accordingly.

On a second page I put various playlists from Spotify to cover the needs for radio plays, Christmas music and other specialties.

Nevertheless, I am happy when issue #64 is implemented (;
