### DISCUSSION TITLE
Can't connect to ESPHome API for nspanel.local

### DISCUSSION THREAD

**Discussion by bakito** [Blackymas/NSPanel_HA_Blueprint#383] [Q&A]
In some networks and between different VLANS ESPHome might not be able to connect to the NSPanel and will fail with the following or similar error.
`Can't connect to ESPHome API for nspanel.local: Error resolving IP address: [Errno -5] No address associated with hostname`

This can be resolved by modifying the nspanel_esphome.yaml and adding the `use_address` property to the wifi section.

```yaml
wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}
  power_save_mode: none
  use_address: ${use_address}
```
Int the ESPHome configuration of the panel the IP address of the Panel can then be defined in the substitutions section.
```yaml
substitutions:

###### CHANGE ME START ######
  use_address: 1.2.3.4
##### CHANGE ME END #####
```

Also change the remote package to your modified config.
```yaml
packages:
  remote_package:
    url: https://github.com/<your-project-name>/NSPanel_HA_Blueprint
```
