### DISCUSSION TITLE
hiden SSID

### DISCUSSION THREAD

**Discussion by BlueScreenTT** [Blackymas/NSPanel_HA_Blueprint#387] [General]
Hi

how do i get the nspanel to connect to a hidden SSID ?
i know i need to do this 

wifi:
  fast_connect: true
  networks:
    - hidden: true
      ssid: !secret wifi_ssid
      password: !secret wifi_password

but where do i put it ?

**Comment by edwardtfn** [comment]
Although this will be considered an advanced configuration without support, something like this should work:

```yaml
substitutions:

###### CHANGE ME START ######

  device_name: "YOUR NSPANEL_NAME" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: "http://HOME-ASSISTANT-IP:8123/local/nspanel_us.tft" # URL to local tft File
#  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_us.tft" # URL to Github

##### CHANGE ME END #####

##### CUSTOM/ADVANCED SETTINGS #####
wifi:
  fast_connect: true
  networks:
    - hidden: true
      ssid: !secret wifi_ssid
      password: !secret wifi_password
##### END OF ADVANCED SETTINGS #####

##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####
```
