### DISCUSSION TITLE
What is the right way to install/use older versions?

### DISCUSSION THREAD

**Discussion by T3mplate-wow** [Blackymas/NSPanel_HA_Blueprint#609] [Q&A]
Hey there,
there could be several reasons why to use not the latest version. 
I know how to use the older/stable 
* blueprint 
and
* nspanel_eu.tft

But I am not sure how to use for example the version 3.1 nspanel_esphome.yaml instead of 3.2.2. 
What I do is exchange the whole esphome configuration 
```
substitutions:

###### CHANGE ME START ######

  device_name: "YOUR NSPANEL_NAME" 
  wifi_ssid: "YOUR WIFI SSID"
  wifi_password: "YOUR WIFI PASSWORD"

  nextion_update_url: "http://HOME-ASSISTANT-IP:8123/local/nspanel_eu.tft" # URL to local tft File
#  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft" # URL to Github

##### CHANGE ME END #####



##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####
```

against the whole "nspanel_esphome.yaml“ I want to use. Is this the right way to do this?
