### DISCUSSION TITLE
Fallback thermostat without HA?

### DISCUSSION THREAD

**Discussion by neuhausf** [Blackymas/NSPanel_HA_Blueprint#646] [Ideas]
I mounted the display in place of an existing 230V thermostat.
This works well, because via Homeassistant (generic_thermostat) the relays can still be controlled.
However, I would like to have a stable solution that also works independently of Homeassistant. Is it possible to implement some kind of fallback mode so that the display works like a dumb normal thermostat - even without Wifi/Homeassistant and co. The desired target temp does not have to be displayed nicely.

So far there is some kind of fallback yes, but only on/off. This does not take into account the current temperature and the target temperature.

Is that even possible with esphome? I'm even willing to spend some money for this...

**Comment by andersagerskov** [comment]
I have the exact same ask 🙏

/Anders

**Comment by Blackymas** [comment]
Hi @neuhausf 
Many things are possible. The problem is usually the low memory of the NSpanel that causes us problems and forces us to move a lot to HA.

But there will be a complete redesign of the climate. We can see if we get it somehow regulated.

I myself use the nspanel exactly like you ah and was also the basis why I started with this Github version.

**Reply by neuhausf** [reply]
It would be awesome if you could make a HA-independent thermostat (just a basic)!

**Comment by Statusbit** [comment]
> I mounted the display in place of an existing 230V thermostat. This works well, because via Homeassistant (generic_thermostat) the relays can still be controlled. However, I would like to have a stable solution that also works independently of Homeassistant. Is it possible to implement some kind of fallback mode so that the display works like a dumb normal thermostat - even without Wifi/Homeassistant and co. The desired target temp does not have to be displayed nicely.
> 
> So far there is some kind of fallback yes, but only on/off. This does not take into account the current temperature and the target temperature.
> 
> Is that even possible with esphome? I'm even willing to spend some money for this...

May I ask how you did that? The switched line simply to a relay?

Then with Better Thermostat evaluated the temperature from the panel?

**Comment by neuhausf** [comment]
Yes, wire the switched line to the output of relay_1.
I did not use Better Thermostat for now, but it's an option. Righ now, its just a generic_thermostat which controls the relay:
```
climate:
  - platform: generic_thermostat
    name: Gang Thermostat
    heater: switch.panelgang_relay_1
    target_sensor: sensor.panelgang_temperature
    min_temp: 15
    max_temp: 27
    ac_mode: false
    target_temp: 20
    cold_tolerance: 0.3
    hot_tolerance: 0.3
    min_cycle_duration:
      seconds: 5
    initial_hvac_mode: "off"
    away_temp: 17
    home_temp: 22
    sleep_temp: 19
    precision: 0.5
```
<img width="203" alt="image" src="https://user-images.githubusercontent.com/7963239/231972015-594833b5-11ad-4b46-96e9-4cbb23cecc2b.png">

You can add further optimizations with the [scheduler component](https://github.com/nielsfaber/scheduler-component) and [card](https://github.com/nielsfaber/scheduler-card).

**Reply by Statusbit** [reply]
Habe es soeingestellt, zwei Fragen dazu:

- Die Steuerleitung habe ich an Relais 1 angeschlossen .... Obwohl das Thermostat aus sein sollte sind die Motoren mit Strom versorgt. Was muss im Blueprint 4.0.2 dazu eingestellt sein?
-  Wie kann ich eine Temperaturkorrektur im generic Thermostat bewerkstelligen? Kann man da ein Offset definieren? Der internTemperatursensor zeigt 3 Grad zu viel an. (Ja ich kanneine andere Entität dafür nutzen, aber wenn da die Batterie leer ist oder kein Signal ...

**Comment by Statusbit** [comment]
Okay, thanks ... I will look at. I have almost all thermostats replaced with a Zigbee variant of Sonoff. Controlled with the extension you mentioned.

Now I have three in the "Treppenhaus" which are actually never on. Here I can imagine well the NSpanel ... which are also better placed from the height than light switches. ( no shelly needn't ... nice)

**Comment by edwardtfn** [comment]
Remember your panel still an ESPHome device and you can do some things by yourself, although this will become a "Non supported" installation from the perspective of this project. And be aware of the memory limitation on the panel.

ESPHome have 2 different controllers for thermostat:
- [Thermostat Climate Controller](https://esphome.io/components/climate/thermostat.html)
- [Bang-Bang Controller](https://esphome.io/components/climate/bang_bang.html)

You can read the difference about those two here:
- https://esphome.io/components/climate/bang_bang.html#bang-bang-vs-thermostat
- https://en.wikipedia.org/wiki/Bang%E2%80%93bang_control

If you see the docs for both, you need a switch to turn on the cooler, another switch to turn on the heater and a temperature sensor. You have all of those available in your panel and already set by this project files:
- `relay_1`
- `relay_2`
- `temp_nspanel` - The internal temperature sensor on the NSPanel

So your ESPHome settings file will look like this: (you can have a million variations of this)
```yaml
substitutions:

###### CHANGE ME START ######

  device_name: "YOUR NSPANEL_NAME" 
  wifi_ssid: "YOUR WIFI SSID"
  wifi_password: "YOUR WIFI PASSWORD"

  nextion_update_url: "http://HOME-ASSISTANT-IP:8123/local/nspanel_us.tft" # URL to local tft File
#  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_us.tft" # URL to Github

##### CHANGE ME END #####



##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####

##### HERE STARTS YOUR THERMOSTAT SETTINGS #####
climate:
  - platform: thermostat
    name: "Thermostat Climate Controller"
    sensor: temp_nspanel
    min_cooling_off_time: 300s
    min_cooling_run_time: 300s
    min_heating_off_time: 300s
    min_heating_run_time: 300s
    min_idle_time: 30s
    cool_action:
      - switch.turn_on: relay_1
    heat_action:
      - switch.turn_on: relay_2
    idle_action:
      - switch.turn_off: relay_1
      - switch.turn_off: relay_2
    default_preset: Home
    preset:
      - name: Home
        default_target_temperature_low: 20 °C
        default_target_temperature_high: 22 °C
```

This will create a climate entity on Home Assistant that you will be able to use on the Climate page on this blueprint and then set directly from your panel, although this changing of settings will be depending on the blueprint and won't be available when your WiFi is out. But the panel will work as a thermostat even without WiFi.

Again, this is not supported by this project. ;)
