### DISCUSSION TITLE
NSPanel - TFT Update display, nothing happens

### DISCUSSION THREAD

**Discussion by Kelhojc** [Blackymas/NSPanel_HA_Blueprint#687] [Q&A] [answered]
Have flashed the nspanel with esphome and am able to see it under devices & integration
I am also able to control the relay via device page

However when i tried to update tft display, sensors become unavailabe for a few seconds and nothing happens on the panel
I have flashed 2 nspanel and the same happens, stuck on default ewelink page wit no time or weather update

Can someone point me where did i do wrong?

below is the yaml for my blueprint
alias: nspanelbedroom
description: ""
use_blueprint:
  path: Blackymas/nspanel_blueprint.yaml
  input:
    language: ENG
    nspanel_name: nspanelbedroom
    date_format: "%d/%m"
    time_format: "%-I:%M"
    weather_entity: weather.forecast_home
    outdoortemp: sensor.aircon_outside_temperature
    indoortemp: sensor.aircon_inside_temperature

and the following is my nspanel yaml file

substitutions:

###### CHANGE ME START ######

  device_name: "nspanelbedroom" 
  wifi_ssid: ""
  wifi_password: ""

  nextion_update_url: "http://192.168.10.138/:8123/local/nspanel_eu.tft" # URL to local tft File
  #nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft" # URL to Github

##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####

**Comment by edwardtfn** [comment, marked as answer]
Please try this: (please make sure you enter your Wi-Fi settings and you have `nspanel_blank.tft` in your local server)

```yaml
substitutions:
  device_name: "nspanelbedroom" 
  wifi_ssid: ""
  wifi_password: ""

  nextion_update_url: "http://192.168.10.138:8123/local/nspanel_blank.tft"
  #nextion_update_url: "http://192.168.10.138:8123/local/nspanel_eu.tft"

###### USE THIS ONLY FOR YOUR FIRST TFT UPLOAD, ONCE IT WORKED, REMOVE THOSE LINES ######
external_components:
  - source: github://pr#2956
    components: [nextion]
    refresh: 1h
###############################################################################

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s
```

**Reply by Kelhojc** [reply]
Thanks for reply!

I have my wifi setting removed from post

below are the logs

[19:25:48][D][button:013]: 'nspanelbedroom Update TFT display' Pressed.
[19:25:48][D][nextion_upload:169]: Connected
[19:25:48][D][nextion_upload:175]: Requesting URL: http://192.168.10.138/:8123/local/nspanel_eu.tft
[19:25:48][W][nextion_upload:186]: HTTP Request failed; URL: http://192.168.10.138/:8123/local/nspanel_eu.tft; Error: connection refused, retrying (1/5)
[19:25:48][W][nextion_upload:186]: HTTP Request failed; URL: http://192.168.10.138/:8123/local/nspanel_eu.tft; Error: connection refused, retrying (2/5)
[19:25:49][W][nextion_upload:186]: HTTP Request failed; URL: http://192.168.10.138/:8123/local/nspanel_eu.tft; Error: connection refused, retrying (3/5)
[19:25:49][W][nextion_upload:186]: HTTP Request failed; URL: http://192.168.10.138/:8123/local/nspanel_eu.tft; Error: connection refused, retrying (4/5)
[19:25:49][W][nextion_upload:186]: HTTP Request failed; URL: http://192.168.10.138/:8123/local/nspanel_eu.tft; Error: connection refused, retrying (5/5)
[19:25:50][D][nextion_upload:310]: Restarting Nextion
[19:25:51][D][nextion_upload:313]: Restarting esphome

**Reply by Kelhojc** [reply]
ok i found a stupid mistake!

i have an additional /  after my ip address!

**Reply by edwardtfn** [reply]
> Thanks for reply!
> 
> I have my wifi setting removed from post
> 
> below are the logs
> 
> [19:25:48][D][button:013]: 'nspanelbedroom Update TFT display' Pressed. [19:25:48][D][nextion_upload:169]: Connected [19:25:48][D][nextion_upload:175]: Requesting URL: http://192.168.10.138/:8123/local/nspanel_eu.tft [19:25:48][W][nextion_upload:186]: HTTP Request failed; URL: http://192.168.10.138/:8123/local/nspanel_eu.tft; Error: connection refused, retrying (1/5) [19:25:48][W][nextion_upload:186]: HTTP Request failed; URL: http://192.168.10.138/:8123/local/nspanel_eu.tft; Error: connection refused, retrying (2/5) [19:25:49][W][nextion_upload:186]: HTTP Request failed; URL: http://192.168.10.138/:8123/local/nspanel_eu.tft; Error: connection refused, retrying (3/5) [19:25:49][W][nextion_upload:186]: HTTP Request failed; URL: http://192.168.10.138/:8123/local/nspanel_eu.tft; Error: connection refused, retrying (4/5) [19:25:49][W][nextion_upload:186]: HTTP Request failed; URL: http://192.168.10.138/:8123/local/nspanel_eu.tft; Error: connection refused, retrying (5/5) [19:25:50][D][nextion_upload:310]: Restarting Nextion [19:25:51][D][nextion_upload:313]: Restarting esphome

Your url is incorrect, it should be `http://192.168.10.138:8123/local/nspanel_eu.tft`.

You can always copy and paste into your browser and you should be able to download the file to your computer.

**Reply by edwardtfn** [reply]
And by the way, have you used the code I've shared? I understood the reason for not having wifi setting, I was just reminding to not forget to add those back, but in the settings I've shred I've fixed the url and added some extra code to help with the upload of a TFT for the first time.

And again, try the `nspanel_blank.tft` first as that is much smaller file and will reduce the chances for errors. After installing that, you can remove that extra code and then proceed with the upload of `nspanel_eu.tft`.

**Reply by Kelhojc** [reply]
hi edwardtfn

I have yet to upload the nspanel_blank.tft file to my folder (will try that next and use your code)

however after fixing my url 
i get the following

[19:40:02][D][button:013]: 'nspanelbedroom Update TFT display' Pressed.
[19:40:02][D][nextion_upload:169]: Connected
[19:40:02][D][nextion_upload:175]: Requesting URL: http://192.168.10.138:8123/local/nspanel_eu.tft
[19:40:02][D][nextion_upload:209]: Updating Nextion ...
[19:40:02][D][nextion_upload:235]: Waiting for upgrade response
[19:40:02][E][uart:015]: Reading from UART timed out at byte 0!
[19:40:02][E][uart:015]: Reading from UART timed out at byte 0!
[19:40:02][E][uart:015]: Reading from UART timed out at byte 0!
[19:40:02][E][uart:015]: Reading from UART timed out at byte 0!
[19:40:03][E][uart:015]: Reading from UART timed out at byte 0!
[19:40:03][E][uart:015]: Reading from UART timed out at byte 0!
[19:40:03][E][uart:015]: Reading from UART timed out at byte 0!
[19:40:03][E][uart:015]: Reading from UART timed out at byte 0!
[19:40:03][E][uart:015]: Reading from UART timed out at byte 0!
[19:40:03][E][uart:015]: Reading from UART timed out at byte 0!
[19:40:03][E][uart:015]: Reading from UART timed out at byte 0!
[19:40:03][E][uart:015]: Reading from UART timed out at byte 0!
[19:40:03][E][uart:015]: Reading from UART timed out at byte 0!
[19:40:03][E][uart:015]: Reading from UART timed out at byte 0!
[19:40:04][E][uart:015]: Reading from UART timed out at byte 0!
[19:40:04][E][uart:015]: Reading from UART timed out at byte 0!
[19:40:04][E][uart:015]: Reading from UART timed out at byte 0!
[19:40:04][E][uart:015]: Reading from UART timed out at byte 0!
[19:40:04][E][uart:015]: Reading from UART timed out at byte 0!
[19:40:04][E][uart:015]: Reading from UART timed out at byte 0!
[19:40:04][D][nextion_upload:239]: Upgrade response is  20
[19:40:04][D][nextion_upload:242]: Available 0 : 0x00
[19:40:04][D][nextion_upload:242]: Available 1 : 0x00
[19:40:04][D][nextion_upload:242]: Available 2 : 0x00
[19:40:04][D][nextion_upload:242]: Available 3 : 0x00
[19:40:04][D][nextion_upload:242]: Available 4 : 0x00
[19:40:04][D][nextion_upload:242]: Available 5 : 0x00
[19:40:04][D][nextion_upload:242]: Available 6 : 0x00
[19:40:04][D][nextion_upload:242]: Available 7 : 0x00
[19:40:04][D][nextion_upload:242]: Available 8 : 0x00
[19:40:04][D][nextion_upload:242]: Available 9 : 0x00
[19:40:04][D][nextion_upload:242]: Available 10 : 0x00
[19:40:04][D][nextion_upload:242]: Available 11 : 0x00
[19:40:04][D][nextion_upload:242]: Available 12 : 0x00
[19:40:04][D][nextion_upload:242]: Available 13 : 0x00
[19:40:04][D][nextion_upload:242]: Available 14 : 0x00
[19:40:04][D][nextion_upload:242]: Available 15 : 0x00
[19:40:04][D][nextion_upload:242]: Available 16 : 0x00
WARNING nspanelbedroom.local: Connection error occurred: [Errno 104] Connection reset by peer
INFO Processing unexpected disconnect from ESPHome API for nspanelbedroom.local
WARNING Disconnected from API
INFO Successfully connected to nspanelbedroom.local

**Reply by edwardtfn** [reply]
Try to use my code, even if you want to try directly with `nspanel_eu.tft`. That is forcing the use of an older screen library which override some of the Sonoff settings. 

And try the url first in your browser and make sure you get the file with the right size (around 6.18mb).

**Reply by Kelhojc** [reply]
@edwardtfn Thanks for the code!
it seems it's updating now

**Reply by Kelhojc** [reply]
@edwardtfn 

the code says to remove the section after first update. Does that mean that we have to remove that line and reflash?

**Reply by edwardtfn** [reply]
Yes. Please remove those extra lines, otherwise you will be using an older library. Then reflash with something like this:

```yaml 
substitutions:
  device_name: "nspanelbedroom" 
  wifi_ssid: ""
  wifi_password: ""

  #nextion_update_url: "http://192.168.10.138:8123/local/nspanel_blank.tft"
  nextion_update_url: "http://192.168.10.138:8123/local/nspanel_eu.tft"

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s
```

**Reply by kcossabo** [reply]
I am getting the same issue, US Panel. I will check the "nspanel_blank.tft", but 

**QUESTION: where should it be?** 

I followed the youtube video and did not see to load anything special, but I did hose up the first attempt using the EU file in the ESP configuration, and not uncommenting the US and commenting out the EU.

Exact same issue, buttons  work in the device screen (I push a button and I see it react in HA) but no lovelace / page on the device still showing the eWe page with no time

**Reply by edwardtfn** [reply]
@kcossabo, could you please share the ESPHome yaml you are using? Please make sure you removed any private info like wifi credentials before sharing.

**Reply by kcossabo** [reply]
@edwardtfn Thank You for the help. The "/config/esphome/nspanel1.yaml"

```
substitutions:

###### CHANGE ME START ######

  device_name: "nspanel1" 
  wifi_ssid: "Cossaboon-2022"
  wifi_password: "xxxxx"

#  nextion_update_url: "http://HOME-ASSISTANT-IP:8123/local/nspanel_us.tft" # URL to local tft File
  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_us.tft" # URL to Github

##### CHANGE ME END #####



##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####
```

**Reply by edwardtfn** [reply]
Ok. Please try this and then try to upload the `nspanel_blank.tft` to your panel.

By the way, I would recommend you use a local www server (your Home Assistant can be that) for this transfer. You might have a chance when trying to transfer `nspanel_blank.tft` directly from GitHub to your panel, as this is a small file, but the chances of an error for `nspanel_us.tft` are quite big.
There's no harm to try from GitHub, if you get an error you can just retry, but the chances of error are not small.
Here you can find instructions to have the files in your local server: https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-First-Steps---Installation-and-Setup#2-you-have-to-download-the-file-nspanel_ustft-or-nspanel_eutft-from-github

```yaml
substitutions:

###### CHANGE ME START ######

  device_name: "nspanel1" 
  wifi_ssid: "Cossaboon-2022"
  wifi_password: "xxxxx"

  nextion_update_url: "https://github.com/Blackymas/NSPanel_HA_Blueprint/raw/main/custom_configuration/nspanel_blank.tft"
  #nextion_update_url: "http://homeassistant.local:8123/local/nspanel_blank.tft"
  #nextion_update_url: "https://github.com/Blackymas/NSPanel_HA_Blueprint/raw/main/nspanel_us.tft"
  #nextion_update_url: "http://homeassistant.local:8123/local/nspanel_us.tft"

##### CHANGE ME END #####


###### USE THIS ONLY FOR YOUR FIRST TFT UPLOAD, ONCE IT WORKED, REMOVE THOSE LINES ######
external_components:
  - source: github://pr#2956
    components: [nextion]
    refresh: 1h
###############################################################################


##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####

```

**Reply by kcossabo** [reply]
I did the following
- overwrote the naspanel1.yaml in the ESPHome device (edit) with above, changing wifi password.
- hit update all on the ESPHome screen
- compiled
- sent the file to the panel and rebooted the panel

```
<snip>
======================== [SUCCESS] Took 102.77 seconds ========================
INFO Successfully compiled program.
INFO Resolving IP address of nspanel1.local
INFO  -> 10.10.101.195
INFO Uploading /data/nspanel1/.pioenvs/nspanel1/firmware.bin (1159472 bytes)
Uploading: [============================================================] 100% Done...

INFO Waiting for result...
INFO OTA successful
INFO Successfully uploaded program.
========= [SUCCESS] /config/esphome/nspanel1.yaml =========



======================== [SUMMARY] ========================
  - /config/esphome/nspanel1.yaml: SUCCESS
```

it is working different, in that 
- press "Update TFT display" 
- now reboots the panel, 
- shows a spinning sonoff symbol
- then a green circle that completes with a check mark
- then back to the (I assume) ewe page. Shows 0C and 12:00 no change. 
- press a physical button, and HA sees the action.

I then added local www server  transfer

```

 # nextion_update_url: "https://github.com/Blackymas/NSPanel_HA_Blueprint/raw/main/custom_configuration/nspanel_blank.tft"
 
  nextion_update_url: "http://10.10.0.20:8123/local/nspanel_us.tft" # URL to local tft File

```

repeated the rebuild

```
NFO Successfully compiled program.
INFO Resolving IP address of nspanel1.local
INFO  -> 10.10.101.195
INFO Uploading /data/nspanel1/.pioenvs/nspanel1/firmware.bin (1159424 bytes)
Uploading: [============================================================] 100% Done...

INFO Waiting for result...
INFO OTA successful
INFO Successfully uploaded program.
========= [SUCCESS] /config/esphome/nspanel1.yaml =========



======================== [SUMMARY] ========================
  - /config/esphome/nspanel1.yaml: SUCCESS
  
```

press the "Update TFT display"

- same as before, there was typing on one of the boot screens, so I thought I would video the boot, to read all the quick screens.

press the "Update TFT display"

- updating, as I see the writing DATA and percentage changing

to a **Blank Screen** no controls :( buttons still cause HA to react, but now a blank screen.

unplug the panel from power and re power

# System Data ERROR! 
written upside down

buttons still react in HA though. I have left mapped to a cabinet light and it operates it, and I see the presses in the HA dashboard.

**Reply by kcossabo** [reply]
noticed I did not use the blank tft

```
# nextion_update_url: "https://github.com/Blackymas/NSPanel_HA_Blueprint/raw/main/custom_configuration/nspanel_blank.tft"
 
 # nextion_update_url: "http://10.10.0.20:8123/local/nspanel_us.tft" # URL to local tft File
  nextion_update_url: "http://10.10.0.20:8123/local/nspanel_blank.tft" # URL to local tft File
```

**Reply by edwardtfn** [reply]
While you have the screen from Sonoff shown, you will need need the following added to your ESPHome (and compiled and flashed to your panel):

```yaml 
###### USE THIS ONLY FOR YOUR FIRST TFT UPLOAD, ONCE IT WORKED, REMOVE THOSE LINES ######
external_components:
  - source: github://pr#2956
    components: [nextion]
    refresh: 1h
###############################################################################
```
This is to bypass a mode used by Sonoff but now supported by ESPHome.

That code will allow you installing the new TFT into your new panel. Always try the `nspanel_blank.tft` first, as that file is only 258kb compared to 6.19mb of `nspanel_eu.tft`, so the chance of an external isuues (a network problem, etc) is extremely reduced.

Once you have installed `nspanel_blank.tft`, you will see a white screen, with nothing written. That is the simplest screen we could create to be capable to remove the original settings from Sonoff, so you will not see any text at that screen, and you won't be able to interact with that white screen. If you got to that point, then you can remove the extra code with the reference to the external component. Then you can proceed to the upload of `nspanel_eu.tft` (always prefer a local www server).
If you didn't got to this pure white screen, then something when wrong in the process. Try to download `nspanel_blank.tft` again and transfer to your local server, try to access the local url with your computers browser and check if the file download is the same size as the file from GitHub.

The message `System data error!` means you don't have a valid TFT file. No need to compile ESPHome again, just make sure you have the file in a local server (the chances of an error download dorectky from GitHub are just too high) and the file have the right size.
Then try to  transfer the file again.
If your network is not stable enough, you can always try again, but you could also try another Wifi network just for the TFT transfer (you can change all the ESPHome setting later without the need of uploading TFT again). You can also try to deploy another www server locally.

Please take a look at those points I mentioned and come back if you still having issues.

**Reply by kcossabo** [reply]
Thank You for all the help.

I have not bricked it yet. but it is in a world of pain

--- 

Changed yaml

```
  
# nextion_update_url: "https://github.com/Blackymas/NSPanel_HA_Blueprint/raw/main/custom_configuration/nspanel_blank.tft"

nextion_update_url: "http://10.10.0.20:8123/local/nspanel_us.tft" # URL to local tft File

# nextion_update_url: "http://10.10.0.20:8123/local/nspanel_blank.tft" # URL to local tft File

```

Then used the three dots to wirelessly install.

Screen did not change still upside down text.

Went to the device, and press "Update TFT display"

Went into the USART Update screen (Text upside down) and quickly / immediately went to 91% 
```
USART Update...
115200
SIZE:
8296448
writing DATA...
91 %           7622656
```

4:34:45 PM  91%
4:37:28 PM 92%
4:47:47 PM 92% board, leaving it to do it's thing
4:54:09 PM 93%
5:12:56 PM 94%
5:44:10 PM 96%
7:18:18 PM 

Checking data rolls from 0-100% then Update Failed.... <upside down>

--- 


I think I am going to start from the beginning and use the serial cable to reload the image (local) and see where that goes

**Big thanks for the help on the delta of the nspanel_blank.tft verse nspanel_eu.tft or in my case nspanel_us.tft

**Reply by edwardtfn** [reply]
> Checking data rolls from 0-100% then Update Failed....

Looks like you have a corrupt TFT file.
1. Try to upload the `nspanel_blank.tft` first. That is much smaller and will force the system to start from 0% next time you try uploading the `nspanel_us.tft` instead of starting from 90% as you see now.
1. Try to download your TFT file from GitHub again and upload this to your local www server again. I've seen corrupted files a few times, so don't ignore this chance.
After uploading to your local www server, you can download the file using your browser in your computer, just to make sure the process is working fine and in the end you get the file with the same size as the original one you got from GitHub.

**Reply by kcossabo** [reply]
Apr 22, 2023 10:52:11 AM 

Prepare for first use

## Added self signed cert so that I could follow video


--- 

BUILT  new device 

Flashed with the yaml from the web

**Back to System Data ERROR!** upside down

Changed yaml to

```
substitutions:
  device_name: "nspanelbedroom" 
  wifi_ssid: ""
  wifi_password: ""

  nextion_update_url: "http://192.168.10.138:8123/local/nspanel_blank.tft"
  #nextion_update_url: "http://192.168.10.138:8123/local/nspanel_eu.tft"

###### USE THIS ONLY FOR YOUR FIRST TFT UPLOAD, ONCE IT WORKED, REMOVE THOSE LINES ######
external_components:
  - source: github://pr#2956
    components: [nextion]
    refresh: 1h
###############################################################################

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s
```

Then 
- Install wirelessly

Then to Devices
- update tft, screen blinks 
- returns to "System Data ERROR!"

In the logs I am getting 

> [10:46:52][W][nextion:341]: Nextion reported page ID invalid!

Will kick at this again in a few hours.

**Reply by edwardtfn** [reply]
> update tft, screen blinks

This is a good indication that Sonoff protections are gone. Then you don't need that external component anymore, but keeping those for now are not causing any harm, so let's wait for your first successful TFT transfer before removing that. So, no need to compile or flash ESPHome for now... The problem is probably somewhere else.


> http://192.168.10.138:8123/local/nspanel_blank.tft

When you paste this address in your browser (in your computer), what happens? I would expect it will download the `nspanel_blank.tft` to your computer and, if that is the case, make sure this newly downloaded file have the same size as the original one fro, GitHub (around 258kb).

**Reply by kcossabo** [reply]
> > <http://192.168.10.138:8123/local/nspanel_blank.tft>](http://192.168.10.138:8123/local/nspanel_blank.tft)
> 
> When you paste this address in your browser (in your computer), what happens? I would expect it will download the `nspanel_blank.tft` to your computer and, if that is the case, make sure this newly downloaded file have the same size as the original one fro, GitHub (around 258kb).
> 

nothing, but if I change it to https:// it does down load.... hummm

**Reply by kcossabo** [reply]
Removed the self-signed cert and https, now it downloads.

**Reply by edwardtfn** [reply]
So, do you have your panel working fine with the Blueprint now?

**Reply by kcossabo** [reply]
sorry no, I am still at the "System Data ERROR!" upside down. I can now read the TFT file via "http://192.168.10.138:8123/local/nspanel_blank.tft". I thought that adding the HTTPS may have mixed up the YAML as HTTP: no longer worked.

-- Current situation--
- picked a name without a number in it
- deleted all configs card from the ESPHome page
- Deleted the Device on Device Page
- started from scratch following the instructions (the original yaml, not the enhanced one here)
- rebooted, same error
- Integration not picking up the panel (aka not offering to add it)
- Added it manually (assume it is because it is still grabbing the same IP)

-- at this point --

- Panel showing the error
- 'nspanelone' is a device
- the device senses the physical button clicks

**pressed the TFT update**

- back to the jump up to 91% and then slow..........

--- 

after a day, I am back where I was, do not expect this to work as there are others that hit and they went off and soldered pins, used the Nexion Editor and downloaded the TFT, which is way out of my knowledge, right now, and need to find a Windows Machine even to try it.

--- 

once the USART update fails (assume) I will re-try your **yaml code** and see if I can force down the TFT files to the unit.

--- 

Assumptions at this time;
- ESPHome is working on the unit, I do see it
- TFT files are the 'artwork' or 'screen data'
- those files are not getting to the right place on the panel's memory

once again, **Thank You for all the help and guidance**

**Reply by kcossabo** [reply]
--while I wait--

You are correct on the TFT being different (I think). working with a Mac 
1) Download from GIT 
2) Connect SMB to the Raspberry Pi's files
3) Drag the TFT to the WWW directory
4) Move the GIT TFT to a subdirectory in download
5) Download the TFT using "http://10.10.0.20:8123/local/nspanel_blank.tft"
6) open terminal and do a diff
```
diff nspanel_blank.tft ./y/nspanel_blank.tft
Binary files nspanel_blank.tft and ./y/nspanel_blank.tft differ
```
7) repeated this with two downloads from GIT and they do not differ
8) delete the one on the PI, upload a new one
9) **SAME** the files are different?

Need to work on why the files are changing when transferring using SMB file share.

**Reply by kcossabo** [reply]
Both files were exactly the same size (or to FINDER's) level of file size, but the SMB transfer did something to them.

Mac os no longer supports FTP, so I needed to install homebrew, then FTP (binary), but now if I FTP to and from the PI the files pass with 'cmp' command. 

If I FTP (binary) to the Pi, then use the HTTP command to download the file;

> cmp nspanel_blank.tft nspanel_blank2.tft
> nspanel_blank.tft nspanel_blank2.tft differ: char 24, line 1

humm....
<EDIT>

File1 - downloaded from GIT via Safari
File2 - downloaded from PI via Chrom
**File1 is different than File2**

File3 - downloaded from PI via safari
**File1 and File3 are the SAME**

If I download the file from the PI using Chrome the file is different than the one I downloaded from GIT via Safari. If I download from PI with Safari the file is the same as the one downloaded from GIT with Safari.

A few file transfers and it seems that Chrome and Safari transfer the files differently.

If I download from Git then FTP to the PI, then HTTP download from the PI the 'cmp' is perfect when I use the exact same browser. If I download from GIT with Chrome, then download from PI with Safari the files are different. They are different depending on the browser I start with

> differ: char 24, line 1
> differ: char 263, line 1

**Question** is there a hash for the real file

**Reply by kcossabo** [reply]
## Today is a good day
# Working

I am going to say the issue was with the TFT file transfers.

--- 

Resolution

--- 

1) cloned the Git repository to my Mac

> git clone https://github.com/Blackymas/NSPanel_HA_Blueprint

2) then FTP'd the files to HA on the Pi.
3) Did a 'cmp' to confirm file integrity

> cmp nspanel_blank.tft ~/Documents/Git_Libs/NSPanel_HA_Blueprint/custom_configuration/nspanel_blank.tft

4) in the ESPHome YAML I FIRST used the nspanel.tft. 

```
 nextion_update_url: "http://10.10.0.20:8123/local/nspanel_us.tft" # URL to local tft File
 
###### USE THIS ONLY FOR YOUR FIRST TFT UPLOAD, ONCE IT WORKED, REMOVE THOSE LINES ######
external_components:
  - source: github://pr#2956
    components: [nextion]
    refresh: 1h
```

5) ESPHome -> Card for panel, three dots -> install (Wirelessly as I had ESP up and running via the serial cable)
6) Install logs did show, but ignored them;

```
[09:01:21][E][uart:015]: Reading from UART timed out at byte 0!
[09:01:21][W][nextion:078]: Nextion is not connected! 
```

7) Device page, 'Update TFT Display' -> Fule gage of install -> White page, buttons showed a response in HA after reboot.
8) Back to ESPHome YAML, change to 'nspanel_us.tft'

```
#  nextion_update_url: "http://10.10.0.20:8123/local/nspanel_blank.tft" # URL to local tft File
  nextion_update_url: "http://10.10.0.20:8123/local/nspanel_us.tft" # URL to local tft File
```

9) ESPHome -> Card for panel, three dots -> install (Wirelessly as I had ESP up and running via the serial cable), no errors in the install log.
10) Device page, 'Update TFT Display' -> Fule gage of install -> **HA Initializing, Please Wait** SCREEN!!!
11) weather card loaded, with rainfall and inside temperature, as configured in the blueprint.

**Thank You to @edwardtfn for the help**
_Hope this helps others_

off to the git home page to donate to the project!
