### DISCUSSION TITLE
Polish language

### DISCUSSION THREAD

**Discussion by cr4shydlo** [Blackymas/NSPanel_HA_Blueprint#695] [General]
Hello. If you can give here file with english text i can translate it to Polish.

**Comment by edwardtfn** [comment]
This is what we have now:
```yaml
    ENG:
      weekdays:
        mon: Monday
        tue: Tuesday
        wed: Wednesday
        thu: Thursday
        fri: Friday
        sat: Saturday
        sun: Sunday
      relative_day:
        today: Today
        tomorrow: Tomorrow
        in_2_days: In 2 days
        in_3_days: In 3 days
        in_4_days: In 4 days
      climate:
        states:
          "on": on
          "off": off
        heat: heat
      please_confirm: Please confirm
      unavailable: Unavailable
      no_name: No name

    POL:
      weekdays:
        mon: Poniedziałek
        tue: Wtorek
        wed: Środa
        thu: Czwartek
        fri: Piątek
        sat: Sobota
        sun: Niedziela
      relative_day:
        today: Dzisiaj
        tomorrow: Jutro
        in_2_days: za 2 dni
        in_3_days: za 3 dni
        in_4_days: za 4 dni
      climate:
        states:
          "on": na
          "off": off
        heat: ciepło
      please_confirm: Proszę o potwierdzenie
      unavailable: Unavailable
      no_name: No name
```
