### DISCUSSION TITLE
Just sharing my experience setting up a new NSPanel using v3.2.2

### DISCUSSION THREAD

**Discussion by rleongcs** [Blackymas/NSPanel_HA_Blueprint#726] [General]
Sorry for the long post...Just wanted to share my experience as I just flashed a new NSPanel and hopefully can help others. I have previously posted not realizing it is in a ESPHome github (https://github.com/esphome/issues/issues/3519#issuecomment-1522234101). Thus posting here again.

Everything went quite well following what I did previously when I setup my 2 NSPanels using v3.2.1. Some issues started when I was updating the nspanel_eu.tft file. It would update to some 20+% and then the log would say disconnected by peer. I tried a few more times of loading the blank and then full and same thing happened. I am always able to upload the nspanel_blank.tft file.

Searching through the issues section, I found https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/706#issuecomment-1517979295. Unfortunately, the `nextion_update_url: "https://weap.nl/ha/nspanel_blank.tft"` gave me more issues than the blank tft file I have. The TFT Update seems to be super fast and it no longer gives a White screen but another error screen. I then tried updating the full tft file and also went super fast and then would have lots of errors on the log.

By this time I was quite frustrated and disappointed thinking i might have bricked my NSPanel. I again searched and landed on this thread. The below post helped me solve the issue! Thanks @Piramidowy. I reverted to my previous settings of using my local blank_tft file and once again the White screen is back. With the name of the full tft renamed without the "_", the update went smoothly. I am so happy and relieved! Not sure why the blank tft works and not the eu tft? Maybe due to file size?

> Funny thing, I was struggling with this problem for over 3 hours and the reason for tft not uploading, was underscore symbol in it's name. Changing file name from "nspanel_eu.tft" to "nspaneleu.tft" (without underscore!) fixed everything.

**Below are the versions I have and the steps I used to setup...** 

ESPHome: v2023.4.1
NSPanel ESPHome: v3.2.2
NSPanel Blueprint: v3.2.2
Blank TFT: http://192.168.xxx.xxx:8123/local/nspanelblank.tft (downloaded mine during v3.2.1)
EU TFT: v3.2.2 http://192.168.xxx.xxx:8123/local/nspaneleu.tft

1. Create a new ESPHome device.
2. Give the device a name for example "room3_nspanel". Use "_" and not "-"
3. Choose ESP32 and then "SKIP".
4. ESPHome will create a "room3_nspanel" device with "room3-nspanel.yaml" as the filename.
5. Edit the device and paste settings from https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-First-Steps---Installation-and-Setup#code.
6. Make changes to the device name, wifi and tft url settings. Example mine is as below...
```
substitutions:

###### CHANGE ME START ######

  device_name: "room3_nspanel" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: "http://192.168.xxx.xxx:8123/local/nspanelblank.tft"
  #nextion_update_url: "http://192.168.xxx.xxx:8123/local/nspaneleu.tft" # URL to local tft File
  #nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft" # URL to Github

##### CHANGE ME END #####



##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####
```
7. Save and install. I flashed mine through the "Connected to this compueter method".
8. Fix back the panel to the backplate and power up. You should see the original Sonoff UI.
9. Go to HA "Devices & Services" and you should see a new ESPHome device "room3_nspanel" to be configured. Go ahead and configure it.
10. Click on the ESPHome device, eg. "room3_nspanel" and scroll till you see the "Update TFT display".
11. Open another HA web instance and go to ESPHome and click the "LOGS" of the "room3_nspanel" device to make sure that the Nextion TFT is detected. If you do not see the below, power cycle the switch and then try again.
![image](https://user-images.githubusercontent.com/61628312/234355475-c898164a-2328-4d81-bc97-31fd463bd0eb.png)
12. Once you see the Nextion TFT is detected, go back to the other HA instance and click on "Update TFT display". You should see the NSPanel screen showing update with %. Once 100%, the screen will initialize and show a White screen as it is a blank tft file.
13. Now go edit the ESPHome device and change the tft url from the blank to the actual version.
```
  #nextion_update_url: "http://192.168.xxx.xxx:8123/local/nspanelblank.tft"
  nextion_update_url: "http://192.168.xxx.xxx:8123/local/nspaneleu.tft" # URL to local tft File
```
14. Save and install. This time I did it over wireless.
15. Repeat steps 11-12. Do not freak if there are errors. You can always power cycle the NSPanel and update the tft again.
16. The actual TFT file will take maybe 10mins if everything went well. You will see the new UI showing you the version screen and then will stuck at loading screen as we have yet to setup the Blueprint. 
17. Go to Automation and create a new automation using the NSPanel Blueprint. Make sure the Node Name matches the device name you used in ESPHome earlier.
![image](https://user-images.githubusercontent.com/61628312/234360345-4d65d607-3a23-4aba-826f-5f19159c0d6b.png)
18. Celebrate!
