### DISCUSSION TITLE
How to have either of the Relay default to turn on after power up?

### DISCUSSION THREAD

**Discussion by rleongcs** [Blackymas/NSPanel_HA_Blueprint#770] [Q&A] [answered]
Not sure if this is already something the blueprint can do? I do not find any settings about it in the blueprint.

Use Case is the relay can be connected to some smart bulbs or even another smart relay that control multiple devices. So would want some settings where I can set the Relay to always turn on after power up.

**Comment by edwardtfn** [comment, marked as answer]
You will have to use in advanced mode, for which you will find some instructions on Wiki.

But basically, copy the full content of the file `nspanel_esphome.yaml` and paste replacing your currently esphome yaml, then fix the substitutions in the beginning of the file (wifi credentials, device name, TFT url, etc) and look for the `switch` area of that file, where you will find one entry for `relay_1` and one for `relay_2`. Those have `restore_mode: RESTORE_DEFAULT_OFF`, which you can change to `restore_mode: ALWAYS_ON`. Then you install that into your panel.

https://esphome.io/components/switch/index.html

**Comment by deejaybeam** [comment]
this is not required - see: https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/352#issuecomment-1435551622
Just turn on the relay, and with the default in our config (restore_mode: RESTORE_DEFAULT_OFF) it remembers the state - works for me too, I have the same requirement

**Reply by edwardtfn** [reply]
`RESTORE_DEFAULT_OFF` will remember last state, with could be `on` or `off`. This is different than _"some settings where I can set the Relay to always turn on after power up"_, which is `ALWAYS_ON`.

😉

**Reply by rleongcs** [reply]
@deejaybeam I did read about restoring to the last state as part of 3.3 but that does not always work in the situation I want.

For example, if I have the relay control the room lights, I would not want it to default to the last state as if there was a power failure during the night like 10pm and power only came back in the middle of the night like 2am, I do not want the lights to suddenly all turned on when power resumes.

On the other hand, for another NSPanel that I have, one of the relay is controlling another Sonoff DualR3 which I do want to default to ON when power resumes.

Thus I think what @edwardtfn suggested would let users have more control for the different scenarios they might need. 😄

**Reply by deejaybeam** [reply]
> @deejaybeam I did read about restoring to the last state as part of 3.3 but that does not always work in the situation I want.
> 
> For example, if I have the relay control the room lights, I would not want it to default to the last state as if there was a power failure during the night like 10pm and power only came back in the middle of the night like 2am, I do not want the lights to suddenly all turned on when power resumes.
> 
> On the other hand, for another NSPanel that I have, one of the relay is controlling another Sonoff DualR3 which I do want to default to ON when power resumes.
> 
> Thus I think what @edwardtfn suggested would let users have more control for the different scenarios they might need. 😄

Of course, as always - it depends...

I is not a normal situation, that you have a power-outage for ~4h as you described, but maybe in your region - this is a special case.

For me, the best solution is to return to the last state.
If it was on, than it is on again after reboot, and off when it was off bevore.
This also works with smart-bulbs, that are connected via panel-relay.
They self are set to restore last state...

If you have a special case where your want/need ALWAYS_OFF/ALWAYS_ON - then you have to edit the ESPHome-Config-File by your own, thats right.

**Reply by rleongcs** [reply]
Thanks so much @deejaybeam. I do agree for the most part, what you suggested is probably good enough as having long power outages does not occur all the time as well.

**Comment by bennydiamond** [comment]
Just to chime in, in case anyone ever needs this info.

The "easiest" way I found on how to customize the yaml is to fork this repo, make the desired changes and reference your fork in the top-level yaml of your ESPHome device.

Here's an example. **I strongly suggest to not reference my fork in your project as it's pretty much tailored to my needs and I won't notify anyone if I make any changes to it.**

Here's my fork:
https://github.com/bennydiamond/NSPanel_HA_Blueprint_Dining_Room

Here's the commit I customized the behavior of Relay 2:
https://github.com/Blackymas/NSPanel_HA_Blueprint/compare/main...bennydiamond:NSPanel_HA_Blueprint_Dining_Room:main

And here's how it looks in ESPHome

```
substitutions:
  # Settings - Editable values
  device_name: "nspanel_salle_a_manger"
  friendly_name: "NSPanel - Salle à Manger"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  nextion_update_url: "http://xxx.xxx.xxx.xxx:8123/local/nspanel_us.tft"  # Optional
  # Add-on configuration (if needed)
  # heater_relay: "1"  # Possible values: "1" or "2"

# Customization area
##### My customization - Start #####
api:
  encryption:
    key: "--------------------"
##### My customization - End #####

# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/bennydiamond/NSPanel_HA_Blueprint_Dining_Room
    ref: main
    refresh: 300s
    files:
      - nspanel_esphome.yaml # Basic package
      # Optional advanced and add-on configurations
      # - esphome/nspanel_esphome_advanced.yaml
      # - esphome/nspanel_esphome_addon_ble_tracker.yaml
      # - esphome/nspanel_esphome_addon_bluetooth_proxy.yaml
      # - esphome/nspanel_esphome_addon_climate_cool.yaml
      # - esphome/nspanel_esphome_addon_climate_heat.yaml
      # - esphome/nspanel_esphome_addon_climate_dual.yaml
      # - esphome/nspanel_esphome_addon_cover.yaml
```

Notice the package reference URL points to my forked github repo.


To update with upcoming version updates from the original repo, you would just need to merge upstream into your fork and fix conflicts if any.

**Comment by edwardtfn** [comment]
Well, with the latest versions this can be much easier...
Just add this to the customizations area in your panel's yaml, so you can keep using the original repository (no need to fork or copy the `nspanel_esphome.yaml` file to local):

```yaml
switch:
  - id: !extend relay_2
    restore_mode: RESTORE_DEFAULT_ON  # or ALWAYS_ON
```

**Comment by bennydiamond** [comment]
as such?

```
substitutions:
  # Settings - Editable values
  device_name: "nspanel_salle_a_manger"
  friendly_name: "NSPanel - Salle à Manger"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  nextion_update_url: "http://xxx.xxx.xxx.xxx:8123/local/nspanel_us.tft"  # Optional
  # Add-on configuration (if needed)
  # heater_relay: "1"  # Possible values: "1" or "2"

# Customization area
##### My customization - Start #####
api:
  encryption:
    key: "--------------------"

switch:
  - id: !extend relay_2
    restore_mode: RESTORE_DEFAULT_ON
##### My customization - End #####

# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    refresh: 300s
    files:
      - nspanel_esphome.yaml # Basic package
      # Optional advanced and add-on configurations
      # - esphome/nspanel_esphome_advanced.yaml
      # - esphome/nspanel_esphome_addon_ble_tracker.yaml
      # - esphome/nspanel_esphome_addon_bluetooth_proxy.yaml
      # - esphome/nspanel_esphome_addon_climate_cool.yaml
      # - esphome/nspanel_esphome_addon_climate_heat.yaml
      # - esphome/nspanel_esphome_addon_climate_dual.yaml
      # - esphome/nspanel_esphome_addon_cover.yaml
```
