### DISCUSSION TITLE
Attribute of Entities

### DISCUSSION THREAD

**Discussion by thesebastianf** [Blackymas/NSPanel_HA_Blueprint#802] [Q&A] [answered]
Hey is it also possible to add an attribute of an entity?
I e.g. would like to show the attribute from local.weather ?

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/13987575/ba9882b5-738f-401f-978d-bea78b7d817e)
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/13987575/56e69764-ccf6-4af8-9ec2-65cdd4dee73a)

**Comment by doron1** [comment, marked as answer]
I did that by creating a template sensor from the weather attribute. Then I
could use it in the blueprint.

EDIT: here's an example

```
template:
  - sensor:
    - name: Myhome Humidity
      unique_id: sensor.myhome.humidity
      device_class: humidity
      unit_of_measurement: '%'
      icon: mdi:water-percent
      state_class: measurement
      state: >
        {{ (state_attr('weather.myhome', 'humidity') | int(default=0)) | round(0,default=0)}}
```
