### DISCUSSION TITLE
Translation update needed

### DISCUSSION THREAD

**Discussion by edwardtfn** [Blackymas/NSPanel_HA_Blueprint#829] [General]
Hi, for the next release we will need your support with translations of some new strings, so I'd like to ask for your help here.

These are the new strings:

```yaml
      weekdays_short:
        mon: Mon
        tue: Tue
        wed: Wed
        thu: Thu
        fri: Fri
        sat: Sat
        sun: Sun
      months:
        jan: January
        feb: February
        mar: March
        apr: April
        may: May
        jun: June
        jul: July
        aug: August
        sep: September
        oct: October
        nov: November
        dec: December
      months_short:
        jan: Jan
        feb: Feb
        mar: Mar
        apr: Apr
        may: May
        jun: Jun
        jul: Jul
        aug: Aug
        sep: Sep
        oct: Oct
        nov: Nov
        dec: Dec
```

Please provide your language name, so I know where to store your translations strings and translate just the right side of ":" (the part in blueish, not the part in green).

**Comment by edwardtfn** [comment]
As an example, this is the one for Portuguese:

```yaml
      weekdays_short:
        mon: Seg
        tue: Ter
        wed: Qua
        thu: Qui
        fri: Sex
        sat: Sáb
        sun: Dom
      months:
        jan: Janeiro
        feb: Fevereiro
        mar: Março
        apr: Abril
        may: Maio
        jun: Junho
        jul: Julho
        aug: Augosto
        sep: Setembro
        oct: Outubro
        nov: Novembro
        dec: Dezembro
      months_short:
        jan: Jan
        feb: Fev
        mar: Mar
        apr: Abr
        may: Mai
        jun: Jun
        jul: Jul
        aug: Ago
        sep: Set
        oct: Out
        nov: Nov
        dec: Dez
```

**Comment by costakis79** [comment]
Greek:

   weekdays_short:
        mon: ΔΕΥ
        tue: ΤΡΙ
        wed: ΤΕΤ
        thu: ΠΕΜ
        fri: ΠΑΡ
        sat: ΣΑΒ
        sun: ΚΥΡ
      months:
        jan: Ιανουάριος
        feb: Φεβρουάριος
        mar: Μάρτιος
        apr: Απρίλος
        may: Μάιος
        jun: Ιούνιος
        jul: Ιούλιος
        aug: Αύγουστος
        sep: Σεπτέμβριος
        oct: Οκτώβριος
        nov: Νοέμβριος
        dec: Δεκέμβριος
      months_short:
        jan: ΙΑΝ
        feb: ΦΕΒ
        mar: ΜΑΡ
        apr: ΑΠΡ
        may: ΜΑΙ
        jun: ΙΟΥΝ
        jul: ΙΟΥΛ
        aug: ΑΥΓ
        sep: ΣΕΠ
        oct: ΟΚΤ
        nov: ΝΟΕ
        dec: ΔΕΚ

**Comment by costakis79** [comment]
Greek lower case, but we preffer capital. For the days you can use 2 letters instead of three

weekdays_short:
mon: Δευ
tue: Τρι
wed: Τετ
thu: Πεμ
fri: Παρ
sat: Σαβ
sun: Κυρ
months:
jan: Ιανουάριος
feb: Φεβρουάριος
mar: Μάρτιος
apr: Απρίλος
may: Μάιος
jun: Ιούνιος
jul: Ιούλιος
aug: Αύγουστος
sep: Σεπτέμβριος
oct: Οκτώβριος
nov: Νοέμβριος
dec: Δεκέμβριος
months_short:
jan: Ιαν
feb: Φεβ
mar: Μαρ
apr: Απρ
may: Μαι
jun: Ιουν
jul: Ιουλ
aug: Αυγ
sep: Σεπ
oct: Οκτ
nov: Νοε
dec: Δεκ

**Reply by edwardtfn** [reply]
Thank you for your quick reply.
Is there an official rule for using lower case or capitals on the shortened names? I think we should just follow whatever is the rule in Greek.

This is how it is the full strings now in Greek. Please note that a couple of strings by the end are not translated. Could you please help with those also?
And please let me know if something else should be changed.

```yaml
    GRC:
      weekdays:
        mon: Δευτέρα
        tue: Τρίτη
        wed: Τετάρτη
        thu: Πέμπτη
        fri: Παρασκευή
        sat: Σάββατο
        sun: Κυριακή
      weekdays_short:
        mon: Δευ
        tue: Τρι
        wed: Τετ
        thu: Πεμ
        fri: Παρ
        sat: Σαβ
        sun: Κυρ
      months:
        jan: Ιανουάριος
        feb: Φεβρουάριος
        mar: Μάρτιος
        apr: Απρίλος
        may: Μάιος
        jun: Ιούνιος
        jul: Ιούλιος
        aug: Αύγουστος
        sep: Σεπτέμβριος
        oct: Οκτώβριος
        nov: Νοέμβριος
        dec: Δεκέμβριος
      months_short:
        jan: Ιαν
        feb: Φεβ
        mar: Μαρ
        apr: Απρ
        may: Μαι
        jun: Ιουν
        jul: Ιουλ
        aug: Αυγ
        sep: Σεπ
        oct: Οκτ
        nov: Νοε
        dec: Δεκ
      relative_day:
        today: Σήμερα
        tomorrow: Αύριο
        in_2_days: σε 2 ημέρες
        in_3_days: σε 3 ημέρες
        in_4_days: σε 4 ημέρες
      climate:
        states:
          "on": Ενεργό
          "off": Ανενεργό
        heat: Θέρμανση
      please_confirm: Παρακαλώ επιβεβαιώστε
      unavailable: Unavailable
      no_name: No name
```

**Reply by costakis79** [reply]
No there is no official rule regarding capital abbreviations, so you can choose whichever. 

unavailable: Μη διαθέσιμο
no_name: Ανώνυμο | Χωρίς όνομα

**Comment by pbranly** [comment]
Hi
In French 

FRA:
      weekdays:
        mon: Lundi
        tue: Mardi
        wed: Mercredi
        thu: Jeudi
        fri: Vendredi
        sat: Samedi
        sun: Dimanche
      weekdays_short:
        mon: Lun
        tue: Mar
        wed: Mer
        thu: Jeu
        fri: Ven
        sat: Sam
        sun: Dim
      months:
        jan: Janvier
        feb: Février
        mar: Mars
        apr: Avril
        may: Mai
        jun: Juin
        jul: Juillet
        aug: Août
        sep: Septembre
        oct: Octobre
        nov: Novembre
        dec: Decembre
      months_short:
        jan: Jan
        feb: Fev
        mar: Mar
        apr: Avr
        may: Mai
        jun: Jun
        jul: Jul
        aug: Aoû
        sep: Sep
        oct: Oct
        nov: Nov
        dec: Dec
      relative_day:
        today: Aujourd hui
        tomorrow: Demain
        in_2_days: Dans 2 jours
        in_3_days: Dans 3 jours
        in_4_days: Dans 4 jours
      climate:
        states:
          "on": on
          "off": off
        heat: Chaleur
      please_confirm: Veuillez confirmer
      unavailable: Indisponible 
      no_name: sans nom

It will surely need some tweaking depending upon the context
Phil

Envoyé de mon iPad

**Reply by bentouspam** [reply]
months:
dec: Décembre

-regards,
Benoit.

**Reply by edwardtfn** [reply]
Fixed on `dev`

**Comment by alirow** [comment]
```
# Polish
# The names of days and months in Polish are written with a lowercase letter, 
# except when a word begins a sentence - then with a capital letter.

weekdays_short:
  mon: pon.   # (alternatively pn. )
  tue: wt.
  wed: śr.
  thu: czw.
  fri: pt.    # (alternatively piąt. )
  sat: sob.
  sun: niedz.
months:
  jan: styczeń
  feb: luty
  mar: marzec
  apr: kwiecień
  may: maj
  jun: czerwiec
  jul: lipiec
  aug: sierpień
  sep: wrzesień
  oct: październik
  nov: listopad
  dec: grudzień
months_short:
  jan: sty.
  feb: lut.
  mar: mar.
  apr: kwi.
  may: maj
  jun: cze.
  jul: lip.
  aug: sie.
  sep: wrz.
  oct: paź.
  nov: lis.
  dec: gru.
```

**Comment by Blackymas** [comment]
DE <3
      weekdays_short:
        mon: Mo.
        tue: Di.
        wed: Mi.
        thu: Do.
        fri: Fr.
        sat: Sa.
        sun: So.
      months:
        jan: Januar
        feb: Februar
        mar: März
        apr: April
        may: Mai
        jun: Juni
        jul: Juli
        aug: August
        sep: September
        oct: Oktober
        nov: November
        dec: Dezember
      months_short:
        jan: Jan.
        feb: Feb.
        mar: März
        apr: Apr.
        may: Mai
        jun: Jun.
        jul: Jul.
        aug: Aug.
        sep: Sept.
        oct: Okt.
        nov: Nov.
        dec: Dez.

**Comment by ajghor** [comment]
Croatian:
weekdays_short:
      mon: Pon
        tue: Uto
        wed: Sri
        thu: Čet
        fri: Pet
        sat: Sub
        sun: Ned
      months:
        jan: Siječanj
        feb: Veljača
        mar: Ožujak
        apr: Travanj
        may: Svibanj
        jun: Lipanj
        jul: Srpanj
        aug: Kolovoz
        sep: Rujan
        oct: Listopad
        nov: Studeni
        dec: Prosinac
      months_short:
        jan: Sij
        feb: Velj
        mar: Ožu
        apr: Tra
        may: Svi
        jun: Lip
        jul: Srp
        aug: Kol
        sep: Ruj
        oct: Lis
        nov: Stu
        dec: Pro

**Comment by gryzzor** [comment]
Spanish

weekdays_short:
        mon: Lun  
        tue: Mar
        wed: Mie
        thu: Jue
        fri: Vie
        sat: Sab
        sun: Dom
      months:
        jan: Enero
        feb: Febrero
        mar: Marzo
        apr: Abril
        may: Mayo
        jun: Junio
        jul: Julio
        aug: Agosto
        sep: Septiembre
        oct: Octubre
        nov: Noviembre
        dec: Diciembre
      months_short:
        jan: Ene
        feb: Feb
        mar: Mar
        apr: Abr
        may: May
        jun: Jun
        jul: Jul
        aug: Ago
        sep: Sep
        oct: Oct
        nov: Nov
        dec: Dic

**Comment by adamengineering** [comment]
Italian

weekdays_short:
mon: Lun
tue: Mar
wed: Mer
thu: Gio
fri: Ven
sat: Sab
sun: Dom
months:
jan: Gennaio
feb: Febbraio
mar: Marzo
apr: Aprile
may: Maggio
jun: Giugno
jul: Luglio
aug: Agosto
sep: Settembre
oct: Ottobre
nov: Novembre
dec: Dicembre
months_short:
jan: Gen
feb: Feb
mar: Mar
apr: Apr
may: Mag
jun: Giu
jul: Lug
aug: Ago
sep: Set
oct: Ott
nov: Nov
dec: Dic

**Comment by doron1** [comment]
Hebrew (he-il/he/Heb)

weekdays_short:
        mon: ב
        tue: ג
        wed: ד
        thu: ה
        fri: ו
        sat: ש
        sun: א
      months:
        jan: ינואר
        feb: פברואר
        mar: מרץ
        apr: אפריל
        may: מאי
        jun: יוני
        jul: יולי
        aug: אוגוסט
        sep: ספטמבר
        oct: אוקטובר
        nov: נובמבר
        dec: דצמבר
      months_short:
        jan: ינו
        feb: פבר
        mar: מרץ
        apr: אפר
        may: מאי
        jun: יונ
        jul: יול
        aug: אוג
        sep: ספט
        oct: אוק
        nov: נוב
        dec: דצמ

**Comment by yhi264** [comment]
Japanese (I hope you will add Japanese language support for the future.)
```
      weekdays:
        mon: 月曜日
        tue: 火曜日
        wed: 水曜日
        thu: 木曜日
        fri: 金曜日
        sat: 土曜日
        sun: 日曜日
      weekdays_short:
        mon: 月
        tue: 火
        wed: 水
        thu: 木
        fri: 金
        sat: 土
        sun: 日
      months:
        jan: 1月
        feb: 2月
        mar: 3月
        apr: 4月
        may: 5月
        jun: 6月
        jul: 7月
        aug: 8月
        sep: 9月
        oct: 10月
        nov: 11月
        dec: 12月
      months_short:
        jan: 1月
        feb: 2月
        mar: 3月
        apr: 4月
        may: 5月
        jun: 6月
        jul: 7月
        aug: 8月
        sep: 9月
        oct: 10月
        nov: 11月
        dec: 12月
	  relative_day:
        today: 今日
        tomorrow: 明日
        in_2_days: 明後日
        in_3_days: 3日間
        in_4_days:  4日間
      climate:
        states:
          "on": 入
          "off": 切
        heat: 温水器
      please_confirm: ご確認下さい
      unavailable: 無効
      no_name: 名称未設定
```

**Reply by Howardno** [reply]
Norwegian
      nb_NO:
      weekdays_short:
        mon: Man
        tue: Tir
        wed: Ons
        thu: Tor
        fri: Fre
        sat: Lør
        sun: Søn
      months:
        jan: Januar
        feb: Februar
        mar: Mars
        apr: April
        may: Mai
        jun: Juni
        jul: Juli
        aug: August
        sep: September
        oct: Oktober
        nov: November
        dec: Desember
      months_short:
        jan: Jan
        feb: Feb
        mar: Mar
        apr: Apr
        may: Mai
        jun: Jun
        jul: Jul
        aug: Aug
        sep: Sep
        oct: Okt
        nov: Nov
        dec: Des

**Reply by edwardtfn** [reply]
[Chinese, Japanese and Korean (CJK) languages - We need help with translations · Blackymas/NSPanel_HA_Blueprint · Discussion #1447 (github.com)](https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/1447)

**Comment by quenthal** [comment]
Finnish
      weekdays_short:
        mon: Ma
        tue: Ti
        wed: Ke
        thu: To
        fri: Pe
        sat: La
        sun: Su
      months:
        jan: Tammikuu
        feb: Helmikuu
        mar: Maaliskuu
        apr: Huhtikuu
        may: Toukokuu
        jun: Kesäkuu
        jul: Heinäkuu
        aug: Elokuu
        sep: Syyskuu
        oct: Lokakuu
        nov: Marraskuu
        dec: Joulukuu
      months_short:
        jan: Tammi
        feb: Helmi
        mar: Maalis
        apr: Huhti
        may: Touko
        jun: Kesä
        jul: Heinä
        aug: Elo
        sep: Syys
        oct: Loka
        nov: Marras
        dec: Joulu

**Comment by lavi02** [comment]
#### Korean
```
weekdays_short:
        mon: 월
        tue: 화
        wed: 수
        thu: 목
        fri: 금
        sat: 토
        sun: 일
      months:
        jan: 1월
        feb: 2월
        mar: 3월
        apr: 4월
        may: 5월
        jun: 6월
        jul: 7월
        aug: 8월
        sep: 9월
        oct: 10월
        nov: 11월
        dec: 12월
      months_short:
        jan: 1월
        feb: 2월
        mar: 3월
        apr: 4월
        may: 5월
        jun: 6월
        jul: 7월
        aug: 8월
        sep: 9월
        oct: 10월
        nov: 11월
        dec: 12월
```

**Reply by edwardtfn** [reply]
Korean isn't currently supported, so I will have to make some test to check if the fonts used in the display are including the Korean's charset.

Anyway, could you please translate the other (older) strings also:
```yaml
    KOR: #Korean
      weekdays:
        mon: Monday
        tue: Tuesday
        wed: Wednesday
        thu: Thursday
        fri: Friday
        sat: Saturday
        sun: Sunday
      weekdays_short:
        mon: Mon
        tue: Tue
        wed: Wed
        thu: Thu
        fri: Fri
        sat: Sat
        sun: Sun
      months:
        jan: January
        feb: February
        mar: March
        apr: April
        may: May
        jun: June
        jul: July
        aug: August
        sep: September
        oct: October
        nov: November
        dec: December
      months_short:
        jan: Jan
        feb: Feb
        mar: Mar
        apr: Apr
        may: May
        jun: Jun
        jul: Jul
        aug: Aug
        sep: Sep
        oct: Oct
        nov: Nov
        dec: Dec
      relative_day:
        today: Today
        tomorrow: Tomorrow
        in_2_days: In 2 days
        in_3_days: In 3 days
        in_4_days: In 4 days
      climate:
        states:
          "on": on
          "off": off
        heat: heat
      please_confirm: Please confirm
      unavailable: Unavailable
      no_name: No name
```

**Reply by lavi02** [reply]
> 
> ```yaml
>     KOR: #Korean
>       relative_day:
>         today: 오늘 or 금일(formal)
>         tomorrow: 내일 or 익일(formal)
>         in_2_days: 2일 후(formal) or 이틀 뒤
>         in_3_days: 3일 후(formal) or 사흘 뒤
>         in_4_days: 4일 후(formal) or 나흘 뒤
>       climate:
>         states:
>           "on": on
>           "off": off
>         heat: 열
>       please_confirm: 확인 부탁드립니다
>       unavailable: 불가능
>       no_name: 공백
> ```

Korean should be available if euc-kr or utf8 is supported for charset tho, idk :p

**Reply by skipper79** [reply]
NL-nl --> Dutch:
     weekdays_short:
        mon: Ma
        tue: Di
        wed: Wo
        thu: Do
        fri: Vr
        sat: Za
        sun: Zo
      months:
        jan: Januari
        feb: Februari
        mar: Maart
        apr: April
        may: Mei
        jun: Juni
        jul: Juli
        aug: Augustus
        sep: September
        oct: Oktober
        nov: November
        dec: December
      months_short:
        jan: Jan
        feb: Feb
        mar: Mar
        apr: Apr
        may: Mei
        jun: Jun
        jul: Jul
        aug: Aug
        sep: Sep
        oct: Okt
        nov: Nov
        dec: Dec

**Reply by edwardtfn** [reply]
[Chinese, Japanese and Korean (CJK) languages - We need help with translations · Blackymas/NSPanel_HA_Blueprint · Discussion #1447 (github.com)](https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/1447)

**Comment by prigorus** [comment]
Slovenian:

      weekdays_short:
        mon: Pon
        tue: Tor
        wed: Sre
        thu: Čet
        fri: Pet
        sat: Sob
        sun: Ned
      months:
        jan: Januar
        feb: Februar
        mar: Marec
        apr: April
        may: Maj
        jun: Junij
        jul: Julij
        aug: Avgust
        sep: September
        oct: Oktober
        nov: November
        dec: December
      months_short:
        jan: Jan
        feb: Feb
        mar: Mar
        apr: Apr
        may: Maj
        jun: Jun
        jul: Jul
        aug: Avg
        sep: Sep
        oct: Okt
        nov: Nov
        dec: Dec

**Comment by joztoz** [comment]
Slovak:
 weekdays_short:
        mon: Po
        tue: Ut
        wed: St
        thu: Št
        fri: Pi
        sat: So
        sun: Ne
      months:
        jan: Január
        feb: Február
        mar: Marec
        apr: Apríl
        may: Máj
        jun: Jún
        jul: Júl
        aug: August
        sep: September
        oct: Október
        nov: November
        dec: December
      months_short:
        jan: Jan
        feb: Feb
        mar: Mar
        apr: Apr
        may: Máj
        jun: Jún
        jul: Júl
        aug: Aug
        sep: Sep
        oct: Oct
        nov: Nov
        dec: Dec
relative_day:
        today: Dnes
        tomorrow: Zajtra
        in_2_days: O 2 dni
        in_3_days: O 3 dni
        in_4_days: O 4 dni
      climate:
        states:
          "on": Zap.
          "off": Vyp.
        heat: Kúrenie
      please_confirm: Prosím potvrďte
      unavailable: Nedostupné
      no_name: Bez názvu

**Reply by bittengl** [reply]
Czech:
weekdays_short:
mon: Po
tue: Út
wed: St
thu: Čt
fri: PÁ
sat: So
sun: Ne
months:
jan: Leden
feb: Únor
mar: Březen
apr: Duben
may: Květen
jun: Červen
jul: Červenec
aug: Srpen
sep: Září
oct: Říjen
nov: Listopad
dec: Prosinec
months_short:
jan: Led
feb: Úno
mar: Bře
apr: Dub
may: Kvě
jun: Črn
jul: Črc
aug: Srp
sep: Zář
oct: Říj
nov: Lis
dec: Pro
relative_day:
today: Dnes
tomorrow: Zítra
in_2_days: Za dni
in_3_days: Za 3 dni
in_4_days: Za 4 dni
climate:
states:
"on": Zap.
"off": Vyp.
heat: Topení
please_confirm: Prosím potvrďte
unavailable: Nedostupné
no_name: Bez názvu

**Reply by edwardtfn** [reply]
Thanks!
It would be nice if you can also help with the new strings:

```yaml
      alarm:
        home: home
        away: away
        night: night
        vacation: vacation
        bypass: bypass
        disarm: disarm
      settings:
        reboot: Reboot
        sleep: Sleep
        brightness: Brightness
        bright: Bright
        dimming: Dimming
        dim: Dim
```
