### DISCUSSION TITLE
Alarm page - We need help with translations

### DISCUSSION THREAD

**Discussion by edwardtfn** [Blackymas/NSPanel_HA_Blueprint#940] [General]
Please help me with the translation for the following strings (used for alarm states):

```yaml
  en: #English
      alarm:
        home: Home
        away: Away
        night: Night
        vacation: Vacation
        bypass: Bypass
        disarm: Disarm
```

An example of those strings being used on an alarm in Home Assistant:
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/871fa493-8caa-4907-99fe-0aa35fc95962)

**Comment by primeroz** [comment]
my proposal for italian translations ... even though they sound so bad and i would personally leave them all in english :)

```
  it: #Italiano
      alarm:
        home: casa
        away: completo
        night: notte
        vacation: vacanza
        bypass: bypass # I would leave this as bypass in italian as well
        disarm: disarmato
```

**Comment by deku-m** [comment]
For dutch:

```
nl: #Dutch
      alarm:
        home: Thuis
        away: Afwezig
        night: Nacht
        vacation: Vakantie
        bypass: Omzeil
        disarm: Ontgrendel
```

**Reply by fugazzy** [reply]
für deutsch:
  
```
de: #german
      alarm:
        home: Zuhause
        away: Abwesend
        night: Nacht
        vacation: Urlaub
        bypass: Bypass # (Umgehung)
        disarm: Deaktiviert
```

**Reply by skipper79** [reply]
A better translation (in Dutch) of ‘Disarm’ is ‘Deactiveren’

**Comment by cjeanne-code** [comment]
For french:
fr: #French
      alarm:
        home: Maison
        away: Absent
        night: Nuit
        vacation: Vacances
        bypass: Bypass # (Contourné)
        disarm: Désactivé

**Comment by formatBCE** [comment]
Ukrainian:

> ua: #Ukrainian
      alarm:
        home: Вдома
        away: Не вдома
        night: Ніч
        vacation: Відпустка
        bypass: Обхід
        disarm: Відключено

**Comment by KoKolaj** [comment]
cz: #Czech
      alarm:
        home: Doma
        away: Pryč
        night: Noc
        vacation: Dovolená
        bypass: Vypnutí Detekce
        disarm: Deaktivovat

**Comment by fzambroni** [comment]
pt: #Portuguese
      alarm:
        home: Casa
        away: Longe
        night: Noite
        vacation: Férias
        bypass: Ignorar
        disarm: Disarmar

**Comment by echopage** [comment]
Italian

 it: #Italiano
    alarm:
      home: casa
      away: fuori
      night: notte
      vacation: vacanza
      bypass: bypass or bypassato
      disarm: disarmato or disattivato

**Comment by pacxxi** [comment]
In spanish.

  es: #Español
      alarm:
        home: Casa
        away: Fuera
        night: Noche
        vacation: Vacaciones
        bypass: Bypass # Can be used in spanish as well
        disarm: Desarmar

**Comment by prigorus** [comment]
si: #Slovenian
      alarm:
        home: Doma
        away: Odsoten
        night: Noč
        vacation: Dopust
        bypass: Območje izlopljeno
        disarm: Izklop


@edwardtfn can you please explain the bypass function? Is this temporarily deactivating only certain areas?

**Reply by edwardtfn** [reply]
I'm probably not the best one to explain custom bypass, as I don't use it (I'm just implementing based on [HA definitions for this entity type](https://developers.home-assistant.io/docs/core/entity/alarm-control-panel/#alarm-custom-bypass)) but I believe this is supported by some alarm system where you can, as an example, select specific areas to bypass (not trigger) the alarm, so it will be enable to the entire house, but not for specific areas.

**Reply by prigorus** [reply]
Thanks, I though so too, looking at manuals for commercial systems. I have updated the translation above.

**Comment by quenthal** [comment]
fi: #Finnish
      alarm:
        home: Kotona
        away: Poissa
        night: Yö
        vacation: Loma
        bypass: Ohitus
        disarm: Pois

**Comment by ktostam** [comment]
```
 pl: #Polish
      alarm:
        home: Dom
        away: Poza domem
        night: Noc
        vacation: Wakacje
        bypass: Bypass
        disarm: Rozbojenie
```
