### DISCUSSION TITLE
Set manual IP howto in esphome addon

### DISCUSSION THREAD

**Discussion by kroon040** [Blackymas/NSPanel_HA_Blueprint#956] [General]
Hi,

I try to set the manual ip in the yaml, beacause with hostname it won't work (mdns), with different vlans and domains.

In other devices I have below config, and than in homeassistant it is online and when click visiti it uses it's ip address.

```
  manual_ip:
  # Set this to the IP of the ESP
    static_ip: 192.168.170.69
  # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.170.254
  # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0
```

In nspanel, this doenn't work, and I found this:

```
  ip: "192.168.170.57"
  gw: "192.168.170.254"
  subnet: "255.255.255.0"
```

But device keerps offline, uses still the dns name instead of ip address in the esphome add on. Is there a way that it can work with the esphome addon in homeassistant with ip instead of dns name?

**Comment by edwardtfn** [comment]
#908 (to be included in the next release) will probably help with this, but for now you will have to use a local custom `nspanel_esphome.yaml` file and edit the `wifi` section by your own.

Then your yaml will be something like this:

```yaml
substitutions:
  device_name: office-workstation-panel
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  nextion_update_url: "http://homeassistant.local:8123/local/nspanel/dev/nspanel_eu.tft"

packages:
  local_package: !include packages/nspanel_esphome.yaml
  #remote_package:
  #  url: https://github.com/Blackymas/NSPanel_HA_Blueprint
  #  ref: main
  #  files: [nspanel_esphome.yaml]
  #  refresh: 300s
```

**Comment by edwardtfn** [comment]
> uses still the dns name instead of ip address in the esphome add on. Is there a way that it can work with the esphome addon in homeassistant with ip instead of dns name?

Have you tried removing the device from ESPHome and then adding it manually using the IP address?

**Comment by kroon040** [comment]
I have this in my local yaml. But fails compiling . Also tried te compile with on local workstation in venv with esphome run test.yaml

INFO ESPHome 2023.7.0
INFO Reading configuration nspanelwoon.yaml...
INFO Updating https://github.com/Blackymas/NSPanel_HA_Blueprint@main
Failed config

substitutions: None
  baud_rate: 115200
  device_name: nspanelwoon
  wifi_ssid: secret
  wifi_password: secret
  
  Must be string, got <class 'esphome.helpers.OrderedDict'>. did you forget putting quotes around the value?.
  manual_ip: 
    static_ip: 192.168.170.69
    gateway: 192.168.170.254
    subnet: 255.255.255.0
  nextion_update_url: http://192.168.180.150:8123/local/nspanel_eu.tft


```

substitutions:
###### DIT GEDEELTE AANPASSEN ######
  device_name: nspanelwoon
  wifi_ssid: secret
  wifi_password: secret
  manual_ip:
    static_ip: 192.168.170.69
    gateway: 192.168.170.254
    subnet: 255.255.255.0



##### EIND AANPASBARE SECTIE #####

  nextion_update_url: "http://192.168.180.150:8123/local/nspanel_eu.tft"
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s
```

**Reply by edwardtfn** [reply]
Your yaml have an indentation issue. You can try this:

```yaml
substitutions:
###### DIT GEDEELTE AANPASSEN ######
  device_name: nspanelwoon
  wifi_ssid: secret
  wifi_password: secret
  nextion_update_url: "http://192.168.180.150:8123/local/nspanel_eu.tft"
wifi:
  manual_ip:
    static_ip: 192.168.170.69
    gateway: 192.168.170.254
    subnet: 255.255.255.0
##### EIND AANPASBARE SECTIE #####
 
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s
```
