### DISCUSSION TITLE
Shutter control via NSPanel Relais / Rollladensteuerung direkt über Relais des Panels

### DISCUSSION THREAD

**Discussion by DerBo19** [Blackymas/NSPanel_HA_Blueprint#965] [Q&A] [answered]
English version below!

Hallo Leute, hat jemand von euch schonmal getestet, ob man eine elektrische Rollladensteuerung direkt an die beiden Relais anschließen kann? Link = hoch, Rechts = runter. Bisher wollte ich einen Shelly 2PM dazwischen schalten, frage mich gerade jedoch, ob das notwendig ist. Allerdings müsste man dann im Panel den Schalter so programmieren können, dass er mit einem Tipp einen Befehl gibt, den Rolladen X Sekunden hoch- bzw. runterzufahren, damit er rechtzeitig stoppt und der Motor nicht weiterläuft. Außerdem sollte man beim erneuten tippen die Möglichkeiten haben, den Vorgang zu stoppen. Hat jemand eine Idee, ob das klappen kann habe ich einen Denkfehler?
Und die Frage wäre auch, was passieren würde, wenn jemand auf die Idee kommt beide Schalter gleichzeitig zu drücken...

Über Hilfe wäre ich euch sehr dankbar! Theoretisch könnte man damit VIEL Geld sparen und man hätte damit sogar ein Offline-Backup, falls der Shelly versagt oder das System offline ist.

----------------------------
English: Hello guys, have any of you ever tested whether you can connect an electric roller shutter control to the two relays? Left = up, right = down. So far I wanted to put a Shelly 2PM in between, but I'm just wondering if that's necessary. However, you would then have to be able to program the switch on the panel so that it gives a command with a tip to move the roller shutter up or down for X seconds so that it stops in time and the motor does not continue to run. You should also be able to stop the process when you type again. Does anyone have an idea whether this can work, do I have a mistake in thinking? Thanks!
And the question would also be what would happen if someone had the idea of pressing both switches at the same time...

I would be very grateful for any help! Theoretically you could save a LOT of money with this and you would even have an offline backup in case the Shelly get broken or the system is offline.

**Comment by edwardtfn** [comment]
So, we have discussed about this case with a Shelly 2PM on #968 and #969, so I will focus here on this use case where the panel will be controlling the cover without the Shelly.

What you are asking for is already covered by [ESPHome Time based cover](https://esphome.io/components/cover/time_based) and I would recommend to work with that as a customization of your ESPHome settings. Something like this:

```yaml
substitutions:

###### CHANGE ME START ######

  device_name: "YOUR NSPANEL_NAME" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: "http://homeassistant.local:8123/local/nspanel_eu.tft"

##### CHANGE ME END #####



##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####


##### MY CUSTOMIZATION - START #####
cover:
  - platform: time_based
    name: "Time-Based Cover"

    open_action:
      - switch.turn_on: relay_1
    open_duration: 2.1min

    close_action:
      - switch.turn_on: relay_2
    close_duration: 2min

    stop_action:
      - switch.turn_off: relay_1
      - switch.turn_off: relay_2
##### MY CUSTOMIZATION - END #####
```

**Comment by DerBo19** [comment]
Thanks Edward!There a two questions about that:1. To use it without the Shelly, you have to add a security option like "if button 1 is in action, button 2 can't be triggered". Shelly makes this in his software. When triggering both buttons at the same time, the shutter will get damaged immediately.2. Can you tell me what I have to type in, when the shutter needs, e.g. 96seconds.I'll try this code without the Shelly in between, since it is a really welcome addition of usecase to the panel!Again, thank you so much!Am 09.08.23, 23:40 schrieb Edward Firmo ***@***.***>:

   
  So, we have discussed about this case with a Shelly 2PM on #968 and #969, so I will focus here on this use case where the panel will be controlling the cover without the Shelly. 
  What you are asking for is already covered by ESPHome Time based cover and I would recommend to work with that as a customization of your ESPHome settings. Something like this: 
  
   substitutions:

###### CHANGE ME START ######

  device_name: "YOUR NSPANEL_NAME" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: "http://homeassistant.local:8123/local/nspanel_eu.tft"

##### CHANGE ME END #####



##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####


##### MY CUSTOMIZATION - START #####
cover:
  - platform: time_based
    name: "Time-Based Cover"

    open_action:
      - switch.turn_on: relay_1
    open_duration: 2.1min

    close_action:
      - switch.turn_on: relay_2
    close_duration: 2min

    stop_action:
      - switch.turn_off: relay_1
      - switch.turn_off: relay_2
##### MY CUSTOMIZATION - END #####

**Reply by edwardtfn** [reply]
I know I'm really late to this. I missed it for some reason.

As @kroon040 mentioned, there is a [switch interlocking](https://esphome.io/components/switch/gpio.html#interlocking) option on ESPHome, but please take a look there so you can understand more how it works and the considerations about a software interlock (probably just like in the Shelly): https://esphome.io/components/switch/gpio.html#interlocking

If you wanna set that, you can add as a customization in your device's yaml:

```yaml
switch:
  - id: !extend relay_1
    interlock: [relay_1, relay_2]
    interlock_wait_time: 500ms  # Please adjust this accordingly
  - id: !extend relay_2
    interlock: [relay_1, relay_2]
    interlock_wait_time: 500ms  # Please adjust this accordingly
```

**Reply by kroon040** [reply]
It should be nice to have the shutter mode with interlock on the blueprint. (or addon)  And that the 2 buttons can act as up and down.

**Reply by edwardtfn** [reply]
That isn't impossible, bit there are some points specially during a boot to take into consideration.
Basically, the difference will be related to the time this will be set after a boot. The configuration in the way I've shared to you is loaded together with other hardware settings, which is one of the first things happening during the boot, so I believe it is pretty safe.
This can be set on the fly from ESPHOME side. I could store the state in a variable and load it at boot. This will all be loaded and processed a bit later ij the boot sequence. We are probably talking in milliseconds here, but still some delay which will require a really good planning.
The Blueprint is loaded much later. Maybe 5 to 20s after the boot sequence is completed. We could again change to not wait for the screen to be ready, so it will be onky the api, but again, we are still talking about seconds, not milliseconds.
So, I will definitely feel more comfortable as a customization to the hardware level as I've shared above. We can put some nice documentation together in the [customization guide](https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/docs/customization.md).

**Reply by edwardtfn** [reply]
> We can put some nice documentation together in the [customization guide](https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/docs/customization.md).

Done! 😃

**Reply by DerBo19** [reply, marked as answer]
Dear @edwardtfn and @kroon040 ,
thank you for your help and for staying on topic. Our house is now up and I'll be installing the panels in the next two weeks. A test panel has already worked with the roller shutter. So I'm in good spirits!

One last question: Is my configuration correct?

```
substitutions:
  # Settings - Editable values
  device_name: "nspanelwohnzimmer" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  nextion_update_url: "http://homeassistant.local:8123/local/nspanel_eu.tft"  # Optional for `esp-idf` framework
  # Add-on configuration (if needed)
  # heater_relay: "1"  # Possible values: "1" or "2"

# Customization area
##### My customization - Start #####
binary_sensor:
  - id: !extend left_button
    on_click:
      then:
    on_press:
      then:
        switch.turn_on: relay_1
    on_release:
        switch.turn_off: relay_1

  - id: !extend right_button
    on_click:
      then:
    on_press:
      then:
        switch.turn_on: relay_2
    on_release:
        switch.turn_off: relay_2

# Interlock for shutters:
switch:
  - id: !extend relay_1
    interlock: [relay_1, relay_2]
    interlock_wait_time: 500ms 
  - id: !extend relay_2
    interlock: [relay_1, relay_2]
    interlock_wait_time: 500ms  
##### My customization - End #####

# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # Optional advanced and add-on configurations
      # - advanced/esphome/nspanel_esphome_advanced.yaml
      # - nspanel_esphome_addon_climate_cool.yaml
      # - nspanel_esphome_addon_climate_heat.yaml
      # - nspanel_esphome_addon_climate_dual.yaml
    refresh: 300s

esp32:
  framework:
    type: esp-idf
    
```

**Reply by edwardtfn** [reply]
I think it's all right.
The most critical is the interlock, and that looks right. Anything else you can fix if it's not 100%, although it looks all right already.

**Reply by kroon040** [reply]
I try this week of I get something to work with the covers/shutters. I want to have it also time based  with interlock

https://esphome.io/components/cover/time_based

**Reply by DerBo19** [reply]
For me personally, I installed a Shelly 2pm behind the panel. That gives me the opportunity to make detailed positions like 52% and all that other Shelly stuff.

**Reply by kroon040** [reply]
I hope that is can do the same as a shelly2pm, with also the position of the shutters

I only get errors when adding covers to the config.

```
switch:
  - id: !extend relay_1
    interlock: [relay_1, relay_2]
    interlock_wait_time: 500ms
  - id: !extend relay_2
    interlock: [relay_1, relay_2]
    interlock_wait_time: 500ms

cover:
 - platform: time_based
   name: "testcover"
   id: testcover
   has_built_in_endstop: true
   open_action:
     - switch.turn_on: relay_2
   open_duration: 35s
   close_action:
     - switch.turn_on: relay_1
   close_duration: 33s

   stop_action:
     - switch.turn_off: relay_1
     - switch.turn_off: relay_2
```

Errors while compiling

```
|-- ArduinoJson @ 6.18.5
Compiling .pioenvs/nspanelwoon/src/main.o
Linking .pioenvs/nspanelwoon/firmware.elf
/home/richard/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/nspanelwoon/src/esphome/components/api/api_connection.o:(.literal._ZN7esphome3api13APIConnection13cover_commandERKNS0_19CoverCommandRequestE+0x8): undefined reference to `esphome::cover::Cover::make_call()'
/home/richard/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/nspanelwoon/src/esphome/components/api/api_connection.o:(.literal._ZN7esphome3api13APIConnection13cover_commandERKNS0_19CoverCommandRequestE+0xc): undefined reference to `esphome::cover::CoverCall::set_position(float)'
/home/richard/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/nspanelwoon/src/esphome/components/api/api_connection.o:(.literal._ZN7esphome3api13APIConnection13cover_commandERKNS0_19CoverCommandRequestE+0x10): undefined reference to `esphome::cover::CoverCall::set_tilt(float)'
/home/richard/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/nspanelwoon/src/esphome/components/api/api_connection.o:(.literal._ZN7esphome3api13APIConnection13cover_commandERKNS0_19CoverCommandRequestE+0x14): undefined reference to `esphome::cover::CoverCall::set_command_stop()'
/home/richard/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/nspanelwoon/src/esphome/components/api/api_connection.o:(.literal._ZN7esphome3api13APIConnection13cover_commandERKNS0_19CoverCommandRequestE+0x18): undefined reference to `esphome::cover::CoverCall::perform()'
/home/richard/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/nspanelwoon/src/esphome/components/api/api_connection.o:(.literal._ZN7esphome3api13APIConnection13cover_commandERKNS0_19CoverCommandRequestE+0x1c): undefined reference to `esphome::cover::CoverCall::set_command_open()'
/home/richard/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/nspanelwoon/src/esphome/components/api/api_connection.o:(.literal._ZN7esphome3api13APIConnection13cover_commandERKNS0_19CoverCommandRequestE+0x20): undefined reference to `esphome::cover::CoverCall::set_command_close()'
/home/richard/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/nspanelwoon/src/esphome/components/api/api_connection.o:(.literal._ZN7esphome3api13APIConnection16send_cover_stateEPNS_5cover5CoverE+0x8): undefined reference to `esphome::cover::COVER_OPEN'
/home/richard/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/nspanelwoon/src/esphome/components/api/api_connection.o: in function `esphome::api::APIConnection::cover_command(esphome::api::CoverCommandRequest const&)':
/home/richard/.esphome/build/nspanelwoon/src/esphome/components/api/api_connection.cpp:272: undefined reference to `esphome::cover::Cover::make_call()'
/home/richard/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /home/richard/.esphome/build/nspanelwoon/src/esphome/components/api/api_connection.cpp:287: undefined reference to `esphome::cover::CoverCall::set_position(float)'
/home/richard/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /home/richard/.esphome/build/nspanelwoon/src/esphome/components/api/api_connection.cpp:289: undefined reference to `esphome::cover::CoverCall::set_tilt(float)'
/home/richard/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /home/richard/.esphome/build/nspanelwoon/src/esphome/components/api/api_connection.cpp:291: undefined reference to `esphome::cover::CoverCall::set_command_stop()'
/home/richard/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /home/richard/.esphome/build/nspanelwoon/src/esphome/components/api/api_connection.cpp:292: undefined reference to `esphome::cover::CoverCall::perform()'
/home/richard/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /home/richard/.esphome/build/nspanelwoon/src/esphome/components/api/api_connection.cpp:276: undefined reference to `esphome::cover::CoverCall::set_command_open()'
/home/richard/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /home/richard/.esphome/build/nspanelwoon/src/esphome/components/api/api_connection.cpp:279: undefined reference to `esphome::cover::CoverCall::set_command_close()'
/home/richard/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /home/richard/.esphome/build/nspanelwoon/src/esphome/components/api/api_connection.cpp:282: undefined reference to `esphome::cover::CoverCall::set_command_stop()'
/home/richard/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/nspanelwoon/src/esphome/components/web_server/web_server.o:(.literal._ZNSt17_Function_handlerIFvN18ArduinoJson6185_719ObjectRefEEZN7esphome10web_server9WebServer10cover_jsonB5cxx11EPNS3_5cover5CoverENS4_10JsonDetailEEUlS1_E_E9_M_invokeERKSt9_Any_dataOS1_+0x10): undefined reference to `esphome::cover::Cover::is_fully_closed() const'
/home/richard/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/nspanelwoon/src/esphome/components/web_server/web_server.o:(.literal._ZNSt17_Function_handlerIFvN18ArduinoJson6185_719ObjectRefEEZN7esphome10web_server9WebServer10cover_jsonB5cxx11EPNS3_5cover5CoverENS4_10JsonDetailEEUlS1_E_E9_M_invokeERKSt9_Any_dataOS1_+0x14): undefined reference to `esphome::cover::cover_operation_to_str(esphome::cover::CoverOperation)'
/home/richard/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/nspanelwoon/src/esphome/components/web_server/web_server.o: in function `std::_Function_handler<void (), esphome::web_server::WebServer::handle_cover_request(esphome::web_server_idf::AsyncWebServerRequest*, esphome::web_server::UrlMatch const&)::{lambda()#1}>::_M_invoke(std::_Any_data const&)':
/home/richard/.esphome/build/nspanelwoon/src/esphome/components/web_server/web_server.cpp:768: undefined reference to `esphome::cover::CoverCall::perform()'
/home/richard/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/nspanelwoon/src/esphome/components/web_server/web_server.o: in function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()':
/home/richard/.platformio/packages/toolchain-xtensa-esp32/xtensa-esp32-elf/include/c++/8.4.0/bits/basic_string.h:657: undefined reference to `esphome::cover::Cover::make_call()'
/home/richard/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/nspanelwoon/src/esphome/components/web_server/web_server.o: in function `esphome::web_server::WebServer::handle_cover_request(esphome::web_server_idf::AsyncWebServerRequest*, esphome::web_server::UrlMatch const&)':
/home/richard/.esphome/build/nspanelwoon/src/esphome/components/web_server/web_server.cpp:737: undefined reference to `esphome::cover::CoverCall::set_command_open()'
/home/richard/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /home/richard/.esphome/build/nspanelwoon/src/esphome/components/web_server/web_server.cpp:751: undefined reference to `esphome::cover::CoverCall::set_command_close()'
/home/richard/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /home/richard/.esphome/build/nspanelwoon/src/esphome/components/web_server/web_server.cpp:739: undefined reference to `esphome::cover::CoverCall::set_command_stop()'
/home/richard/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/nspanelwoon/src/esphome/components/web_server/web_server.o: in function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()':
/home/richard/.platformio/packages/toolchain-xtensa-esp32/xtensa-esp32-elf/include/c++/8.4.0/bits/basic_string.h:657: undefined reference to `esphome::cover::CoverCall::set_position(float)'
/home/richard/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/nspanelwoon/src/esphome/components/web_server/web_server.o: in function `esphome::web_server::WebServer::handle_cover_request(esphome::web_server_idf::AsyncWebServerRequest*, esphome::web_server::UrlMatch const&)':
/home/richard/.esphome/build/nspanelwoon/src/esphome/components/web_server/web_server.cpp:761: undefined reference to `esphome::cover::CoverCall::set_tilt(float)'
/home/richard/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/nspanelwoon/src/esphome/components/web_server/web_server.o: in function `ArduinoJson6185_71::Converter<esphome::StringRef, void>::toJson(esphome::StringRef const&, ArduinoJson6185_71::VariantRef)':
/home/richard/.esphome/build/nspanelwoon/.piolibdeps/nspanelwoon/ArduinoJson/src/ArduinoJson/Variant/ConverterImpl.hpp:17: undefined reference to `esphome::cover::Cover::is_fully_closed() const'
/home/richard/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/nspanelwoon/src/esphome/components/web_server/web_server.o: in function `std::_Function_handler<void (ArduinoJson6185_71::ObjectRef), esphome::web_server::WebServer::cover_json[abi:cxx11](esphome::cover::Cover*, esphome::web_server::JsonDetail)::{lambda(ArduinoJson6185_71::ObjectRef)#1}>::_M_invoke(std::_Any_data const&, ArduinoJson6185_71::ObjectRef&&)':
/home/richard/.esphome/build/nspanelwoon/src/esphome/components/web_server/web_server.cpp:776: undefined reference to `esphome::cover::cover_operation_to_str(esphome::cover::CoverOperation)'
/home/richard/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/nspanelwoon/src/main.o:(.literal._Z5setupv+0xad8): undefined reference to `vtable for esphome::time_based::TimeBasedCover'
/home/richard/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/nspanelwoon/src/main.o:(.literal._Z5setupv+0xadc): undefined reference to `vtable for esphome::time_based::TimeBasedCover'
/home/richard/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/nspanelwoon/src/main.o:(.literal._Z5setupv+0x1e64): undefined reference to `esphome::cover::Cover::Cover()'
/home/richard/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/nspanelwoon/src/main.o: in function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/home/richard/.platformio/packages/toolchain-xtensa-esp32/xtensa-esp32-elf/include/c++/8.4.0/bits/basic_string.h:1366: undefined reference to `esphome::cover::Cover::Cover()'
/home/richard/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/nspanelwoon/src/esphome/core/controller.o:(.literal._ZN7esphome10Controller16setup_controllerEb+0x38): undefined reference to `esphome::cover::Cover::add_on_state_callback(std::function<void ()>&&)'
/home/richard/.platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/nspanelwoon/src/esphome/core/controller.o: in function `esphome::Controller::setup_controller(bool)':
/home/richard/.esphome/build/nspanelwoon/src/esphome/core/controller.cpp:41: undefined reference to `esphome::cover::Cover::add_on_state_callback(std::function<void ()>&&)'
collect2: error: ld returned 1 exit status
*** [.pioenvs/nspanelwoon/firmware.elf] Error 1
```
