### ISSUE TITLE
physical switch doesn't work

### ISSUE THREAD

**Issue by chpego** [Blackymas/NSPanel_HA_Blueprint#100]
Hi Guys,
If i don't set entities on left or right button, i can use the physical switch button, right ?
Because, on my left button i've a light is wired behind this button, but when i press, nothing appears.
In esp home device, i can toggle the switch of (ns relay 1 / 2).

In my previously config esp device yaml config, which works, in the binary_sensor settings, it's set like this

```
###### LEFT BUTTON BELOW DISPLAY TO TOGGLE RELAY#####
- platform: gpio
  name: ${device_name} Left Button
  pin:
    number: 14
    inverted: true
  on_click:
        - switch.toggle: relay_1
```

Maybe i've forget something ?

Nice job for this project ! Really !
