### ISSUE TITLE
Feature Request: Blank TFT Button or alternative tft.

### ISSUE THREAD

**Issue by fordcrews** [Blackymas/NSPanel_HA_Blueprint#1048]
It seems greater that half the time I try to update the display, it hangs somewhere while flashing, and I can't get it to start back flashing, without powering it completely off and loading a black tft to it.    Currently you have to either reflash it, or upload a blank tft file called the same as the one you were trying to flash, flashing it blank, then uploading the one you really want to flash, and flashing it.

**Comment by edwardtfn** [comment]
I liked the idea and will look for a way to implement it in the future.
Are you aware of the service `esphome.xxxxx_upload_tft_url`? You can use that to transfer a different TFT without the need to reflash.

> It seems greater that half the time I try to update the display, it hangs somewhere while flashing, and I can't get it to start back flashing, without powering it completely off and loading a black tft to it.

This shouldn't happen.
Are you transferring the TFT locally or are you using GitHub to hos the files?

**Comment by fordcrews** [comment]
I remember seeing that, didn't think about it.   The button would be cool, but it may be just me. 

I think it's my wifi.  Old house, with 2 layers lath and steel mesh between walls, and one on the ceiling, it's like trying to use wifi in a faraday cage.

**Comment by edwardtfn** [comment]
I'd like to have that button also.

**Comment by edwardtfn** [comment]
You can also add this as a "customization" in your ESPHome settings:

```yaml
button:
  ##### UPDATE TFT BLANK DISPLAY #####
  - name: ${device_name} Update TFT display (blank)
    platform: template
    icon: mdi:file-sync
    id: tft_update_blank
    entity_category: config
    on_press:
      - logger.log: "Button pressed: Update TFT display (blank)"
      - binary_sensor.template.publish:
          id: nextion_init
          state: false
      - delay: 16ms
      - lambda: |-
          id(disp1)->set_tft_url("${nextion_update_blank_url}");
          id(disp1).upload_tft();
```

You will need the url in your substitutions, like this:
```yaml
  nextion_update_blank_url: "http://homeassistant.local:8123/local/nspanel/dev/nspanel_blank.tft"
```

It should work.

On v4.0 we are adding a whole page about those customizations, maybe this could be just one additional option there.
