### ISSUE TITLE
is "refresh_relays" called twice iv v4?

### ISSUE THREAD

**Issue by bkbartk** [Blackymas/NSPanel_HA_Blueprint#1068]
Hello?

I see
```
              then:
                - switch.toggle: relay_1
                - script.execute: refresh_relays
```
on button click, when local is activated.

but at the same time I see
```
    on_turn_on:
      then:
        - script.execute:
            id: refresh_relays
    on_turn_off:
      then:
        - script.execute:
            id: refresh_relays
```
on the relay itself

I would assume, the action on the button is obsolete and triggers automations more
