### ISSUE TITLE
call esphome service from esphome

### ISSUE THREAD

**Issue by bkbartk** [Blackymas/NSPanel_HA_Blueprint#1071]
Hello,

I know modifications are not supported so I will ask anyway

I want to make a modification like this on the relays
```
    on_turn_on:
      then:
        - homeassistant.service:
            service: esphome.lamp_kamer_voor_open_entity_settings_page
            data:
              page: light
              entity: light.bulb_kamer_achter_bulb_kamer_achter
              page_icon_color: "[0]"
              page_label: light
              back_page: home
              page_icon: mdi:light
        # - script.execute:
        #     id: refresh_relays
    on_turn_off:
      then:
        - script.execute:
            id: refresh_relays
```
but for some reason it doesn't work.
HA notified I need to allow the device to make service calls,
So I did.
but still nothing happends,
and also, I think it should be possible to keep a service call like this local, however the entity details are needed, so maybe not.

**Comment by edwardtfn** [comment]
This screen will work onky when the panel is Connected to Home Assistant, so why don't you create an automation in Home Assistant to call this service when the relay changes. You have the relay status in a binary sensor and can use that as your trigger.

**Comment by edwardtfn** [comment]
Tomorrow I will take a look on how complex would be to have this running locally... Certainly calling this service isn't the best.

**Comment by edwardtfn** [comment]
Let's go... I haven't tested this, but you can try and please let me know...

Instead of editing the `nspanel_esphome.yaml`, which changes on every release, I would suggest to do a customization from your regular ESPHome settings for this device.
Just add this at the end of your settings:

```yaml
switch:
  - id: !extend relay_1
    on_turn_on:
      then:
        - lambda: |-
            id(entity_id) = "light.bulb_kamer_achter_bulb_kamer_achter";
            id(disp1).goto_page("light");
            id(disp1).set_component_text_printf("page_label", "Light");
            id(disp1).set_component_text_printf("back_page", "home");
            id(disp1).set_component_text_printf("icon_state", "\uE334"); // mdi:lightbulb - https://htmlpreview.github.io/?https://github.com/jobr99/Generate-HASP-Fonts/blob/master/cheatsheet.html
```

You can read more about customizations (with examples) here: https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/docs/en/customization.md
