### ISSUE TITLE
error when trying to validate nspanel

### ISSUE THREAD

**Issue by Maxtr1n** [Blackymas/NSPanel_HA_Blueprint#1075]
Hello i am trying to update my nspanels when coming to the step validate nspanel I get error se below.
What am I doing wrong?

INFO ESPHome 2023.8.2
INFO Reading configuration /config/esphome/nspanel2.yaml...
INFO Updating https://github.com/Blackymas/NSPanel_HA_Blueprint@main
Failed config

packages: [source /config/esphome/nspanel2.yaml:20]
  
  index-pack failed.
  remote_package: 
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: 
      - nspanel_esphome.yaml
    refresh: 300s

**Comment by Maxtr1n** [comment]
Just got that part to work after some attempts but now I get this ERROR

tensa-esp32-elf-g++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
*** [/data/nspanel/.pioenvs/nspanel/src/main.cpp.o] Error 1
======================== [FAILED] Took 1005.96 seconds

**Comment by edwardtfn** [comment]
Try to clean up your building files:

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/d6374133-f9b2-443d-acc6-c0a4f95e49d3)

**Comment by edwardtfn** [comment]
> [FAILED] Took 897.58 seconds

This is a quite long time...
Do you have sufficient memory on ESPHome host?
Maybe a reboot would free up some memory.

**Comment by Maxtr1n** [comment]
not working, do I need to change anything in the new blueprint file? I have just copied the new file into home assistant. if that has any thing to do with it?

**Comment by edwardtfn** [comment]
This error compiling ESPHome have nothing to do with the Blueprint. It is something local to your ESPHome.

Do you mind sharing your ESPHome settings used to flash this panel? Please remove any sensitive information before sharing.

**Comment by Maxtr1n** [comment]
ofcorse how I am a real newbe on this but for a couples of months ago I got 2 panels to work and now I want to update to the new firmware. so how do I get what you want to see?

**Comment by edwardtfn** [comment]
On your ESPHome dashboard, click edit on the device you are having trouble, copy that text, paste here, format as code and remove sensitive info (like your Wi-Fi password).

The screen looks like this:
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/90b9a88b-76b0-414f-b327-44599ae4c966)

And the code I'm expecting is like this:

```yaml
substitutions:

###### CHANGE ME START ######

  device_name: "YOUR NSPANEL_NAME" 
  wifi_ssid: "YOUR WIFI SSID"
  wifi_password: "YOUR WIFI PASSWORD"

  nextion_update_url: "http://HOME-ASSISTANT-IP:8123/local/nspanel_us.tft" # URL to local tft File
#  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_us.tft" # URL to Github

##### CHANGE ME END #####


##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####
```

**Comment by Maxtr1n** [comment]
substitutions:

###### CHANGE ME START ######

  device_name: "nspanel"
  wifi_ssid: ”Namn”
  wifi_password: ”Lösenord”

  nextion_update_url: "http://homeassistant.local:8123/local/nspanel_eu.tft" # URL to local tft File
#  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft" # URL to Github

##### CHANGE ME END #####



##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####

**Comment by Maxtr1n** [comment]
substitutions:

###### CHANGE ME START ######

  device_name: "nspanel"
  wifi_ssid: "Telia-311949"
  wifi_password: "APMcr1p886hZcE9y"

  nextion_update_url: "http://homeassistant.local:8123/local/nspanel_eu.tft" # URL to local tft File
#  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft" # URL to Github

##### CHANGE ME END #####



##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####

**Comment by edwardtfn** [comment]
By the way, do you have any firewall restricting Internet access to the server running ESPHome compiler?

**Comment by Maxtr1n** [comment]
substitutions:

###### CHANGE ME START ######

  device_name: "nspanel"
  wifi_ssid: "Telia-311949"
  wifi_password: "APMcr1p886hZcE9y"

  nextion_update_url: "http://homeassistant.local:8123/local/nspanel_eu.tft" # URL to local tft File
#  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft" # URL to Github

##### CHANGE ME END #####



##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####

**Comment by Maxtr1n** [comment]
Du har inte möjlighet att hjälpa mig över Temwiever så får du kika vad sjutton jag gör för fel?

**Comment by edwardtfn** [comment]
I don't see anything wrong with your settings... It is something with your ESPHome.

My next try:

Under your file system, where you have ESPHome, create a subfolder, let say you call it "packages".
Download the file `nspanel_esphome.yaml` from GitHub and save it on that new folder.
Edit your yaml to use the local file instead. It will look like this:

```yaml
substitutions:
  device_name: "nspanel"
  wifi_ssid: "Telia-311949"
  wifi_password: "APMcr1p886hZcE9y"
  nextion_update_url: "http://homeassistant.local:8123/local/nspanel_eu.tft"

packages:
  local_package: !include packages/nspanel_esphome.yaml
  #remote_package:
  #  url: https://github.com/Blackymas/NSPanel_HA_Blueprint
  #  ref: dev
  #  files:
  #    - nspanel_esphome.yaml # Core package
  #    #- nspanel_esphome_addon_climate_cool.yaml # activate for local climate (cooling) control
  #    #- nspanel_esphome_addon_climate_heat.yaml # activate for local climate (heater) control
  #  refresh: 300s
```

Then try to install again.

**Comment by edwardtfn** [comment]
> Du har inte möjlighet att hjälpa mig över Temwiever så får du kika vad sjutton jag gör för fel?

Not today, unfortunately. I have an appointment pretty soon.
But if that last option also fails we can try to find some time during the weekend or early next week.

**Comment by Maxtr1n** [comment]
i don't get it to work

**Comment by Zealand67** [comment]
Same problem here since the upgrade to version 4.0

**Comment by edwardtfn** [comment]
@Maxtr1n, I've compiled using your settings and got no issues.
I've attached the files here. You will have to unzip and then choose one of those (they are the same with different format modern/legacy, so you can try the other if one fails) and install it. Probably the easiest way to install is going to your device's web page (click on the button "Visit" on your ESPHome dashboard, log with "ADMIN" and your wifi password) and you will have an OTA update button at the bottom.
[nspanel.zip](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/12705732/nspanel.zip)

Attention, those files will work only for @Maxtr1n, as the OTA password will be specific for his case. Don't try to use outside. ;)

**Comment by edwardtfn** [comment]
After that, let's go deeper on solve the problem you have to compile yourself.
Could you please provide more details/specifications about the device running your ESPHome server?

**Comment by edwardtfn** [comment]
> Same problem here since the upgrade to version 4.0

@Zealand67, do you mind creating another issue specifically for your case and provide more details? I will be happy to help.

**Comment by maxtrin87** [comment]
Update Successful!

I am runing homeassistant, ESP home on a rsp

**Comment by edwardtfn** [comment]
RPi3 or RPi4? How much memory?

**Comment by Maxtr1n** [comment]
Raspberry Pi 3B+  
believe it is 64 gb or 32

**Comment by maxtrin87** [comment]
xtensa-esp32-elf-g++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
*** [/data/nspanel/.pioenvs/nspanel/src/main.cpp.o] Error 1
========================= [FAILED] Took 62.15 seconds

**Comment by edwardtfn** [comment]
> believe it is 64 gb or 32

This is probably your SD card size, my concern is more about RAM memory, which I believe is typically 1Gb for a RPi3b+.0 (and is a quite common system, so other people should be reporting the same problem if this is the issue).

I will try to emulate this environment and run this process...

**Comment by ivanovd** [comment]
I can confirm that I also have issues compiling with RPi 3b+ with 1 GB of memory. I don't observe the same with RPi 4 with 2 GB of memory.

**Comment by edwardtfn** [comment]
Please try adding this to your ESPHome yaml:

```yaml
esphome:
  compile_process_limit: 1
```

It can be at the end of the file, after the whole `packages` thing.

**Comment by edwardtfn** [comment]
Exactly!

**Comment by edwardtfn** [comment]
It would be like this:

```yaml

substitutions:
  ###### CHANGE ME START ######
  device_name: "nspanel"
  wifi_ssid: "Telia-311949"
  wifi_password:""

  nextion_update_url: "http://homeassistant.local:8123/local/nspanel_eu.tft"

  ##### addon-configuration #####
  ## addon_climate ##
  # addon_climate_heater_relay: "1" # possible values: 1/2

  ##### CHANGE ME END #####

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # - nspanel_esphome_addon_climate_cool.yaml # activate for local climate (cooling) control
      # - nspanel_esphome_addon_climate_heat.yaml # activate for local climate (heater) control
    refresh: 300s

##### My customization - Start #####
# Limit the amount of resources used for compiling
esphome:
  compile_process_limit: 1
##### My customization - End #####
```
