### ISSUE TITLE
`Feature request` Time and date format

### ISSUE THREAD

**Issue by edwardtfn** [Blackymas/NSPanel_HA_Blueprint#1083]
Local official format for Finnish way of formatting time and date are slightly different that what is available in the blueprint. Is it possible to have the following:

Date format:
weekday D.M (non-capital first letter in weekday, no comma after weekday, no leading zeroes on day or month and dot as separator instead of ':')

Time format:
H.MM (24h, no leading zero on hours, dot seperating hours and minutes).

_Originally posted by @quenthal in https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/1078_

**Comment by edwardtfn** [comment]
> non-capital first letter in weekday

For this, we have to work with the translations.
Could you please take a look in the translations to Finnish and let me know what should be fixed?

```yaml
    fi: #Finnish
      weekdays:
        mon: Maanantai
        tue: Tiistai
        wed: Keskiviikko
        thu: Torstai
        fri: Perjantai
        sat: Lauantai
        sun: Sunnuntai
      weekdays_short:
        mon: Ma
        tue: Ti
        wed: Ke
        thu: To
        fri: Pe
        sat: La
        sun: Su
      months:
        jan: Tammikuu
        feb: Helmikuu
        mar: Maaliskuu
        apr: Huhtikuu
        may: Toukokuu
        jun: Kesäkuu
        jul: Heinäkuu
        aug: Elokuu
        sep: Syyskuu
        oct: Lokakuu
        nov: Marraskuu
        dec: Joulukuu
      months_short:
        jan: Tammi
        feb: Helmi
        mar: Maalis
        apr: Huhti
        may: Touko
        jun: Kesä
        jul: Heinä
        aug: Elo
        sep: Syys
        oct: Loka
        nov: Marras
        dec: Joulu
      relative_day:
        today: Tänään
        tomorrow: Huomenna
        in_2_days: 2 päivän päästä
        in_3_days: 3 päivän päästä
        in_4_days: 4 päivän päästä
      climate:
        states:
          "on": "On"
          "off": "Off"
        heat: lämpö
      please_confirm: Vahvista
      unavailable: Unavailable
      no_name: No name
      alarm:
        home: Kotona
        away: Poissa
        night: Yö
        vacation: Loma
        bypass: Ohitus
        disarm: Pois
      settings:
        reboot: Uudelleenkäynnistys
        sleep: Lepotila
        brightness: Kirkkaus
        bright: Kirkas
        dimming: Himmennys
        dim: Himmeä
        #Finnish is sometimes difficult language to get short words out of... :)
        #Uudelleenkäynnistys could be shortened as "Uudelleenkäynn." (if there is room for that dot), 2nd best would be "Uud.käynnistys", lastly "Uud.käynn.". Then there is this non-official translation "Boottaus" (but I'd prefer not).
        #If in current version there is this title (Brightness, Kirkkaus in Finnish) before those two sliders, you can use "Kirkas" and "Himmeä" for them.
```
