### ISSUE TITLE
Bad time displaed after update to 4.0

### ISSUE THREAD

**Issue by bgga** [Blackymas/NSPanel_HA_Blueprint#1092]
Hi.
After updating nspanel to 4.0 the time is displayed wrog. 
My timezone is Europe/Warsaw and the time on nspanel is -2h than my time zone.
Before update was good.
HA ver: 2023.9.2
ESP Home ver: 2023.8.3

Thanks

**Comment by edwardtfn** [comment]
We moved the time engine from Blueprint to ESPHome, so time keeps updated even when network is out.
ESPHome should get the timezone from your server where you compiled the code, however, if this is not working properly, you can Enforce the timezone by adding this to your ESPHome settings (at the end of the file is OK):

```yaml 
time:
  - id:!extend time_provider
    timezone: "America/Cancun"
```
