### ISSUE TITLE
Action that calls an unknown service: esphome.<name>_send_command_font_color

### ISSUE THREAD

**Issue by Mithrox** [Blackymas/NSPanel_HA_Blueprint#1112]
Hi,

After upgrade of the latest ESPHome to 2023.9.0 I get this error below (it's from Spooks, giving the clear error).

I have not collected logs as this seems to be a clear issue, calling an unknown service, but I can get necessary logs if need be as well. I assume more than me will have this issue now post upgrade? I have also upgraded my HA now today to the latest 2023.9.3 just to check if it had any correlation, but same issue there.

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/58890682/b9ba4850-af79-458d-a22f-b4f230ba844d)

**Comment by edwardtfn** [comment]
When you restart your panel you have a blue boot screen where the versions are shown. Please take a look there and let us know the versions for TFT, ESPHome and Blueprint.

Based on the error message I believe you have Blueprint v3.x trying to communicate with ESPHome v4.0 or v4.0.1.
My suggestion would be to update everything to the latest version (currently v4.0.1).

https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-HowTo---All-important-thing-you-should-know#2-update-blueprint

**Comment by Mithrox** [comment]
HI and thank you for quick reply.

I have TFT: 3.4
ESPHome 4.0.1
Blueprint 3.4

It looks like I then have an older version (though I just installed this a few weeks ago).

I will look at your link and try to get it updated from it, thank you.

**Comment by Mithrox** [comment]
Well, that was quick and easy it seems. The switch next to me just came straight up with everything as it should. Thank you so much for the quick response.

**Comment by Mithrox** [comment]
Actually, one more question. I now get this message in Notifications:

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/58890682/bcb89129-0f87-4b15-aa3f-696fdfff3d14)

Do I have to update the TFT or something as well, or is that controlled by the blueprint? Sorry for being noobish.

**Comment by Mithrox** [comment]
I will assume so and close it again, sorry.

**Comment by Mithrox** [comment]
Unfortunately that did not go well. Now my panel is stuck on looking "Check data (counting up %)" and then "Updated Failed: Check Error". Is there a good way to recover from it? All I did was the Press Update TFT through the device page.

**Comment by edwardtfn** [comment]
This is not as bad as it looks like. 😉
Restart and upload TFT again.
If you still getting the same errol try to power cycle your device or upload `nspanel_blank.tft` first.

**Comment by Mithrox** [comment]
The Update TFT starts on 88% (and this time it looks to be halted there too), is that normal? The first time I did it, it started around the same and then showed the bar progress and counted up to 99%, then hung there for several minutes and then the error came. I assume it's normal not to start on 0%?

It has been halted on the 88% now for about 5 minutes, should I power cycle and try a Validate/install from ESPHome again first before updating TFT? When you say upload nspanel_blank.tft first I am not 100% sure what you mean.

**Comment by Mithrox** [comment]
I ended up power cycling it, and then I validated and installed over again from ESPhome. It went through as it should, but from the ESPHome logging I get a lot of these "Nextion reported variable name invalid!" messages. Is that symptomatic for something here?

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/58890682/5f2e45f4-4e74-4d54-92bf-97b022937bc6)

**Comment by edwardtfn** [comment]
> The Update TFT starts on 88% (and this time it looks to be halted there too), is that normal? The first time I did it, it started around the same and then showed the bar progress and counted up to 99%, then hung there for several minutes and then the error came. I assume it's normal not to start on 0%?

Yes, it is normal to start from something like 80% when you are uploading just an update of the same file.

> It has been halted on the 88% now for about 5 minutes, should I power cycle and try a Validate/install from ESPHome again first before updating TFT? 

Yes, a power cycle may help, but there no need to flash ESPHome again... It is onky about the TFT.
If you are uploading from a local server, make sure the file is not corrupt.

> When you say upload nspanel_blank.tft first I am not 100% sure what you mean.

You will find this file under "custom_configuration" folder on the GitHub repository. This is not a functional file, it's just a small dummy TFT showing a QR code. It will force your TFT transfer to start from 0%.

**Comment by Mithrox** [comment]
yes, I have the nspanel_blank.tft and nspanel_eu.tft on my local server under /config/www/nspanel folder. So I should download both of those over again just to make sure incase something has happend to the local files, correct?

How do I initiate the upload of the nspanel_blank.tft, it's in the ESPHome code set to use the nspanel_eu.tft right?

**Comment by edwardtfn** [comment]
https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/846#discussioncomment-7121211

**Comment by Mithrox** [comment]
I did upload the blank.tft and it worked perfectly, the panel came up with a QR code, which I believe is the normal behavior. After restart I then uploaded the same way with the nspanel_eu.tft but it stops at 6% and won't continue. Any good tricks I can try?

**Comment by Mithrox** [comment]
Actually, I let the panel just be earlier today as I had a lot of meetings, and it's still moving forward but with snails pace. So when it was at 26% earlier, 3 hours ago, it's now at 42% and still not halted. It's not meant to be like this I assume, but I'll just leave it there and maybe it will finish at some point. The second panel which is in daily use is up and running, but the defined buttons aren't pressable, and the icons looks weird (like broken up). I was going to get this one upgraded and working again before I fix the other one, but it remains to be seen if it will finish at some point.

**Comment by edwardtfn** [comment]
> So when it was at 26% earlier, 3 hours ago, it's now at 42% and still not halted. It's not meant to be like this I assume, but I'll just leave it there and maybe it will finish at some point.

These life-long transfers always fails at the end. You probably have a message "Nextion is not connected" in the ESPHome logs and nothing is really being transferred to the display.
Unfortunately ESPHome is pretty weak on this... It should detect when this happens and send an error message quickly, so you don't waste hours.

Anyways, I would suggest you to stop this, reboot your panel and start the upload again.

**Comment by edwardtfn** [comment]
> The second panel which is in daily use is up and running, but the defined buttons aren't pressable, and the icons looks weird (like broken up).

You have a version mismatch.
On the blue boot screen you will be able to see the versions for TFT, ESPHome and Blueprint. Please make sure you have all in the same version.
The latest version right now is v4.0.2.

**Comment by Mithrox** [comment]
> > The second panel which is in daily use is up and running, but the defined buttons aren't pressable, and the icons looks weird (like broken up).
> 
> You have a version mismatch. On the blue boot screen you will be able to see the versions for TFT, ESPHome and Blueprint. Please make sure you have all in the same version. The latest version right now is v4.0.2.

Hehe yes, it's hard to keep up with you. I did download the 4.0.1 earlier today when I started this, and didn't see that you had a 4.0.2 that had come out just after ;) I will try again...

**Comment by edwardtfn** [comment]
It's always good to be with the latest, but there's no real need to update from v4.0
to v4.0.2 unless you are affected by one of the bugs (and the critical ones are on `nspanel_us.tft` only).

**Comment by Mithrox** [comment]
Downloaded the newest of nspanel_eu.tft and nspanel_blank.tft. Flashing with blank works perfectly every time, but with the nspanel_eu.tft it progress for a while but then it grinds to a slow progress, which you above said will fail. Is there any other way than Update TFT or the method in the other post to get the right version on it? I am not sure what else to try at this time.

**Comment by Mithrox** [comment]
> Any chance you have the logs from this transfer where it started fast and then slowed down? I wanna see if we can detect this state in some way.

I can start it over again if you tell me where to get the logs and how to? :)

**Comment by edwardtfn** [comment]
On your ESPHome dashboard, on the box related to your device, there's a button for "Logs". Click there and select wireless, then when the logs started open another window to press Upload TFT, then when the system slows down copy that text and paste here, please.

**Comment by edwardtfn** [comment]
By the way, there's people using Tasmota to transfer TFT and then coming back to ESPHome. Tasmota handles this pretty well, however you will have this extra work of flash ING Tasmota and then ESPHome later.

**Comment by Mithrox** [comment]
> By the way, there's people using Tasmota to transfer TFT and then coming back to ESPHome. Tasmota handles this pretty well, however you will have this extra work of flash ING Tasmota and then ESPHome later.

I hope I can avoid that, I don't want to keep opening these panels and patch over and over again. And everything else I have is running in ESPHome, so it would be preferrable to get there.

I'll open the log window and copy everything out for you, give me a couple minutes.

**Comment by Mithrox** [comment]
[logs_nsp02_logs.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/12742442/logs_nsp02_logs.txt)

**Comment by edwardtfn** [comment]
Look, I'm using my phone now, so I have limitrd resources, but I will try to review this later and make sure I'm not missing anything.

But let's go trhu my findings from your logs.

```

[21:05:37][D][nextion_upload:291]: Updating tft from "http://10.1.1.15:8123/local/nspanel_eu.tft" with a file size of 6551964 using 65536 chunksize, Heap Size 88892
```
This shows you are trying to transfer `nspanel_eu.tft` with 6.5 MB. I would expect something above 7mb, so either you have an older version in your local server or you have a corrupt file. This is not the cause of the transfer being interrupted (I talk about that later), but please make sure you are trying to transfer the right file, so you don't have to repeat this whole process later.
You can find the latest file from here: https://github.com/Blackymas/NSPanel_HA_Blueprint/raw/main/nspanel_eu.tft

```

[21:07:02][D][nextion_upload:048]: Requesting range: bytes=868352-933887
WARNING nsp02.local: Connection error occurred: [Errno 104] Connection reset by peer
INFO Processing unexpected disconnect from ESPHome API for nsp02.local
WARNING Disconnected from API
INFO Successfully connected to nsp02.local
[21:07:21][E][uart:015]: Reading from UART timed out at byte 0!
[21:07:21][W][nextion:072]: Nextion is not connected!
```
At this point I see your panel losing connection to Home Assistant. It's hard to know exactly the cause of this, but I don't think it was HA interrupting, so I will go more for a network (Wi-Fi) issue (either losing packages or too slow).
I can look for some ways to make the communication more robust in this case, but I have to say this is handled by ESPHome, and not by our project, so I have no idea where to start, which means it could take some time. If you can move your Wi-Fi router closer to your panel would be a faster test to validate this hypothesis.

I will take another look when I got back home (or maybe tomorrow).

**Comment by edwardtfn** [comment]
I see exactly the same pattern in the other log... Just stopped in a different point:

```

bytes=1392640-1458175
[21:21:57][D][nextion_upload:302]: Heap Size 55900, Bytes left 5984576
[21:21:57][D][nextion_upload:048]: Requesting range: bytes=1458176-1523711
WARNING nsp02.local: Connection error occurred: [Errno 104] Connection reset by peer
INFO Processing unexpected disconnect from ESPHome API for nsp02.local
WARNING Disconnected from API
INFO Successfully connected to nsp02.local
[21:22:17][E][uart:015]: Reading from UART timed out at byte 0!
[21:22:17][W][nextion:072]: Nextion is not connected! 
```

I will take a look in Tasmota code to understand how they handle this (as looks like this is much better there compared to ESPHome).

**Comment by Mithrox** [comment]
Thank you for your willingness to help, I absolutely appreciate it.

In the first logs I think it still picked up the wrong file (the previous one) like I wrote above, but in the second log file it should absolutely use the correct one, or did it also come up with the wrong size?

I hear you on the Wifi and I would absolutely say look there first (30 years in IT). I do however have a pretty comprehensive mesh with Unifi APs and I have a dedicated 2.4GHz SSID network for IoT devices, and I do not really have any issues with any of my units. I am about 80 Wifi units in my home now, and they are all very stable as far as I can tell. This is also the first issue I have had with patching these panels, I did it a few times the first time I was getting them up and running, and they never stopped like this. Only happening now after the upgrade.

**Comment by edwardtfn** [comment]
Ok. Good to know the Wifi is not a problem... one less thing to keep in the radar.

May I ask you to do a test for me? I cannot reproduce this issue here, so it would be nice if you can try it.
My intention is to try to transfer this in a higher baud rate, the same used by Tasmota, so we reduce the chances for this communication error. The higher baud rate is between ESPHome and the display, while the disconnection is between ESPHome and Home Assistant, so I believe increasing speed could be a way to improve.

In order to do that, I'd like to ask you uploading to your panel the file [`nspanel_blank_921600bps.tft`](https://github.com/Blackymas/NSPanel_HA_Blueprint/raw/tft-transfer/custom_configuration/nspanel_blank_921600bps.tft).
Your system is currently set to do all the communication using 115200bps. This file will be transferred at this speed to Nextion, but then will restart Nextion and set it to start communicating with 921600bps.
When this new transfer rate is set in Nextion, it will completelly lose connection to ESPHome, so you will have to reflash your panel adding this to the ESPHome yaml:

```yaml
# Set Nextion comm's baud rate to 921600 bps
uart:
  baud_rate: 921600
``` 

Then after flashing you ESPHome, it should recover the communication with Nextion (although you will still see messages saying about invalid variable names as this is nspanel_blank.
Once you have stablished the communication with Nextion, try to transfer your big file (`nspanel_eu.tft`) again. It should be much faster this time and if it fails, please just restart the panel and try again (no need to install blank again this time).
If you succeed installing `nspanel_eu.tft` with this way, you will have to return you ESPHome to 115200 (by editing or removing the lines you have added above) and restart it.
If everything goes well, it should work after that and, working or not, we will get additional info to improve the system.

Please let me know if you have further questions or if you don't wanna run this try... I still can look for some other things to try.

**Comment by Mithrox** [comment]
I will absolutely give it a go. So just to make sure I do the steps in the right order:

1. Upload the file you link to with the Developer Tools Services tab
2. Edit the ESPhome yaml file to look like what I paste below
3. Once it's back up and running (ideally I would see this in the log window?) I will reupload the nspanel_eu.tft (4.0.2 version) by using Developer Tools Services tab
4. Chose update TFT through the Device window?

Is that correct order and procedure?

```
substitutions:

###### CHANGE ME START ######

  device_name: "nsp02" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: "http://10.1.1.15:8123/local/nspanel_eu.tft" # URL to local tft File
#  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_us.tft" # URL to Github

# Set Nextion comm's baud rate to 921600 bps
uart:
  baud_rate: 921600

##### CHANGE ME END #####

##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: tft-transfer
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####
```

**Comment by edwardtfn** [comment]
That is correct, but remember you must set the baud rate (115200 or 921600) based on the TFT currently installed, not on the one you want install.
Any TFT with v4.0.2 or less will be 115200. Any v4.1 or more will be 921600.

**Comment by edwardtfn** [comment]
Sorry, that is not correct. I missed something.

**Comment by Mithrox** [comment]
I need to get to bed now (you should most likely too), but I will test tomorrow when I am more awake and can think straight again :)

**Comment by edwardtfn** [comment]
Please try this:

```yaml
substitutions:

###### CHANGE ME START ######

  device_name: "nsp02" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: "http://10.1.1.15:8123/local/nspanel_eu.tft" # URL to local tft File
#  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_us.tft" # URL to Github

# Set Nextion comm's baud rate to 921600 bps
uart:
  - id: !extend tf_uart
    baud_rate: 921600

##### CHANGE ME END #####

##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: tft-transfer
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####
```

**Comment by edwardtfn** [comment]
> you should most likely too

You are totally right. 😆

**Comment by avassem85** [comment]
> > Any chance you have the logs from this transfer where it started fast and then slowed down? I wanna see if we can detect this state in some way.
> 
> I can start it over again if you tell me where to get the logs and how to? :)
> 
> Btw, this is the latest notification I get in HA, it seems the versions match, but it doesn't say anything on TFT, most likely because it never gets updated properly?
> 
> ![image](https://user-images.githubusercontent.com/58890682/271085765-32524c5b-d6f4-424c-a3df-f4034df2c85b.png)

You can also download to the esphome version you had:

```
packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: v3.4.1
    files: [nspanel_esphome.yaml]
    refresh: 300s
```

**Comment by Mithrox** [comment]
Maybe I am bringing up something old that IS fixed already and that I just don't see it, but I am once again back struggling with getting my panels up and running (I have not had time to do anything since September so they weren't a priority).

Status: My panel nps02 was stuck at getting this error when I tried updating it through ESPhome:

> INFO ESPHome 2023.11.1
> INFO Reading configuration /config/esphome/nsp02.yaml...
> INFO Updating https://github.com/Blackymas/NSPanel_HA_Blueprint@tft-transfer
> INFO Detected timezone 'Europe/Oslo'
> Failed config
> 
> api: [source /data/packages/89f37024/nspanel_esphome.yaml:142]
>   id: api_server
>   reboot_timeout: 0s
>   services: 
>     - service: upload_tft
>       then: ................................

But with the update to ESPhome 2023.11.1 the update went through nicely. However, at that point I was back to where I was earlier, when I could Install the updated software on the panel, but once I press "Update TFT display" it goes for a while and then stops (as per this log file).

[logs_nsp02_run (4).txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/13392346/logs_nsp02_run.4.txt)

My config file is currently this, I have tried local file of course, and I also tried using the blank file, but now I just come back into the vertical message of "System data ERROR!" after trying to update TFT.

[nsp02.yaml.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/13392376/nsp02.yaml.txt)

What is it I am not getting here? I have gone through all the previous tips and tricks, and I have tried all of them, but right now I am not sure where I get stuck. There are no Wifi issues in the house, the panel is less than 2 meters from the nearest AP so it should be perfectly fine. Any new info I have missed, or any new tips I could try?

**Comment by Mithrox** [comment]
> My config file is currently this, I have tried local file of course, and I also tried using the blank file, but now I just come back into the vertical message of "System data ERROR!" after trying to update TFT.

I did test with local as well as I mentioned above, I just wanted to see if it did make any sort of difference. I have been using local the whole time before I snapshotted the config file 😃

**Comment by edwardtfn** [comment]
So please try adding this to your yaml, flash it and try upload again:

```yaml
esp32:
  framework:
    type: esp-idf
```

Please capture logs of the upload if possible.

**Comment by Mithrox** [comment]
Here is the results after adding it to the config file, it did a lot of things first, apparently something was missing from my install and it got put in there. It disconnected after near 4% this time.

[logs_nsp02_run (6).txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/13393024/logs_nsp02_run.6.txt)

[nsp02.yaml.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/13393027/nsp02.yaml.txt)

I know we did testing on 115200 and 921600, can there be an issues where this is still wrong? Is there a way I can make 100% sure it's 115200 on the Nextion, it has to be the same right? (sorry, my memory is a bit fuzzy in that part)

**Comment by edwardtfn** [comment]
The trains won't start unless the 2 parts are at the same baud rate. Anyways, during the transfer the baud rate is shown in the screen.

Have you tried transferring the new blank TFT after changing to esp-idf? After uploading the new blank TFT you will be able to transfer at 921600bps, which might be better in some situations.

So, these are the steps:

1. Upload the new blank TFT at 115200bps 
2. Change your ESPHome to 921600bps and flash it
3. Wait until the blank TFT shows info about ESPHome  (it might take up to a minute) and double check after that the baud rate shown on screen is 921600bps
4. Transfer the new nspanel_eu.tft at 921600bps 
5. Remove the framework esp-idf and flash your panel again

**Comment by Mithrox** [comment]
I installed it with the same config as earlier, with the new blank TFT with 115200 in the config file, it worked fine and this is the blank info screen I got after pressing the Update TFT display button (went pretty quick).

![400755582_901321230889220_5407388550690818213_n](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/58890682/9d183837-4d5f-4844-8e0f-e356d41aab0b)

Then I changed the config file to 921600 and kept everything else the same in the config file, and this is the log file when I did.

[logs_nsp02_run (7).txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/13394038/logs_nsp02_run.7.txt)

Config file, just for reference.

[nsp02.yaml.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/13394070/nsp02.yaml.txt)

I tried then Update TFT display again, but it just came back with the same values, and 115200 baud in the top right corner.

**Comment by Mithrox** [comment]
> It will show 115200bps first and "ESP: Waiting...", after a minute it will change to 921600bps and then establish communication to ESPHome, then you can press upload TFT.

So you are saying I need to be patient? 😄 So when it spams Nextion is not connected I should just let it be, and then wait a minute and see?

**Comment by Mithrox** [comment]
I had such high hopes this time, it flew through all the way up to 65%, but then it stopped and disconnected 😦 

[logs_nsp02_run (2).txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/13394232/logs_nsp02_run.2.txt)

And then of course back to System Data ERROR message as before.

**Comment by Mithrox** [comment]
I tried one more time without the framework as well, just to see. I saw that it then requested blocks in much quicker succession, but it also got toa round 60% and then stopped. However, it did stop for a few seconds, then did one more block, and then it stopped completely and disconnected (log file below). 

[logs_nsp02_run (1).txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/13394297/logs_nsp02_run.1.txt)

**Comment by edwardtfn** [comment]
> So you are saying I need to be patient? 😄 So when it spams Nextion is not connected I should just let it be, and then wait a minute and see?

>The best part here is that you are so right, after a lot of spam, it suddenly came up with 921600 and same ESP version. So next step now is just change the file from _blank to _eu and then run the update and see if it disconnects or go through again then?

😂

On v4.1 I've tried to map lots of those connection errors and try lots of diferent things in a long boot sequence, however each try requires waiting up to 20 sec, so this sequence can be quite long.

**Comment by edwardtfn** [comment]
About the framework, they are using totally diferent implementations of this Upload TFT. The one with Arduino tries to calculate the available memory and transfer by chunks at the verge of the memory available, and loads the entire chunk, transfer everything to the display, then it requests the next chunk from your www server, while the IDF versions works with the minimum chunk size supported by Nextion, but with a single request to the server.

It was common to see with Arduino the device losing connection, as it is happening in yours, and this was usually due to lack of memory, esp crashes. I haven't seen this with idf yet, although your log shows something very similar.

**Comment by Mithrox** [comment]
Sounds like this may not be very normal behavior then. Any other things I can try? I believe I am doing it correctly, and the surrounding things like Wifi is 100% stable for every device, so I doubt it is just up to choppy connection too. Any way to increase this timeout further to account for longer hangs, or will that not have any effect?

**Comment by avassem85** [comment]
What helped me was flashing the new esphome with framwork "esp-idf" by serial and not over wifi. And that together with the steps mentioned by edwardtfn on https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/1112#issuecomment-1816611758

**Comment by Mithrox** [comment]
> What helped me was flashing the new esphome with framwork "esp-idf" by serial and not over wifi. And that together with the steps mentioned by edwardtfn on [#1112 (comment)](https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/1112#issuecomment-1816611758)

I tried now but I cannot get my USB adapter to work with it. I have the home-made cable and it connects and it turns on the display, but no matter what I do I cannot get it to install/update. But the install/update has not been a problem though, it's been when I go to update the TFT, it just won't go through. And that won't help with cable anyways as far as I can tell?

**Comment by edwardtfn** [comment]
I think I got lost with this thread, sorry… 😞 
What you see in your screen now?
If you got to install the new blank tft, flash your panel with url to `nspanel_xx.tft` in your local server, and baud_rate at 921600bps.
After your panel starts, wait until it establishes communication to Nextion before start transferring the new TFT.

**Comment by Mithrox** [comment]
Morning. This is what it looks like now, after installing the config with the nspanel_eu.tft, but before I press Update TFT. I am leaving it for 10 minutes now after install before I press Update TFT, just to make sure there is no issue due to not waiting long enough.

![400245039_330097729736572_7601425391934849187_n](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/58890682/af7e9124-6028-4117-895c-a26410bebe5a)

**Comment by edwardtfn** [comment]
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/e15cddb7-c533-4f91-9275-d7ede28797e5)

When you are able to see the ESPHome version, you are good to start the TFT transfer. 😉

**Comment by edwardtfn** [comment]
> Referring to the post above, the Update TFT has to be done over Wifi as far as I know, it's just the install/update that can be done through USB, correct? The install and update is not a problem, it always go through as it should, and especially the nspanel_blank always comes up correctly (the Update TFT transfer always goes through).

Technically, you can transfer TFT also via usb/serial or even via a SD card, but it is much easier to do via Wi-Fi. On #166 you can see how to transfer that via wire.

Only for the first time installing ESPHoOME you need to do via wire (USB/serial), after that everything can be done via Wi-Fi. There are, however, a recommendation to do wired flash every time you are changing framework. Once the new framework partitions are there, everything can be done via Wi-Fi again.

**Comment by Mithrox** [comment]
> 
> When you are able to see the ESPHome version, you are good to start the TFT transfer. 😉

I thought so, but this time I also let it wait another 10 minutes just to make sure 😃

In reference to your other post below, the install and update works perfectly, so it looks not like it's a problem, and it also did change framework without any issues (I see the difference when trying to do the Update TFT). My issue is the disconnect/hang when I do the Update TFT command, and then consequently it just comes back up with error.

**Comment by edwardtfn** [comment]
I'm in a trip now and will be very limited in the coming couple of days, but I wanna investigate it a bit more when I get back home... Add logs, limit memory usage, etc...

Meanwhile, one thing you could try is to run it with verbose log and see if you get any clue.

```yaml
logger:
  level: VERBOSE
```

You can also try to add the "Heap free" and "Reset reason" sensors from debug: https://esphome.io/components/debug.html

**Comment by Mithrox** [comment]
Added what you said above in the config file so it looks like this:

[nsp02.yaml.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/13417780/nsp02.yaml.txt)

It did stop around 15% again, but I had verbose logging on, this is the output of the log:

[logs_nsp02_run (6).txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/13417781/logs_nsp02_run.6.txt)

**Comment by edwardtfn** [comment]
@Mithrox, my apologies for the late reply here.

Are you still fighting this or it worked in the end?

**Comment by Mithrox** [comment]
@edwardtfn no I have not done anything else after those last logs.

**Comment by edwardtfn** [comment]
So, my apologies again for the late reply here, and I will step back a bit to get more info that could help solving this.

So, first, I'd like to ask you running a cleaner yaml and refreshing with the latest code (which contains a bit more logging):

```yaml
substitutions:
###### CHANGE ME START ######
  device_name: "nsp02" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

#  nextion_update_url: "http://10.1.1.15:8123/local/nspanel_blank.tft"
  nextion_update_url: "http://10.1.1.15:8123/local/nspanel_eu.tft"

  ##### CHANGE ME END #####

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # - nspanel_esphome_advanced.yaml # activate advanced (legacy) elements - can be useful for troubleshooting
      # - nspanel_esphome_addon_climate_cool.yaml # activate for local climate (cooling) control
      # - nspanel_esphome_addon_climate_heat.yaml # activate for local climate (heater) control
    refresh: 300s

##### My customization - Start #####
esp32:
  framework:
    type: esp-idf
##### My customization - End #####
```

Could you please install this, wait for 3min after it starts and then press the Upload TFT, then send us all the logs related to this?

**Comment by Mithrox** [comment]
Another attempt, first with nspanel_blank.tft then with nspanel_eu.tft. Both logfiles included for refererence.

[logs_nsp02_run install nspanel_blank.tft.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/13636745/logs_nsp02_run.install.nspanel_blank.tft.txt)

[logs_nsp02_run install nspanel_eu.tft.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/13636743/logs_nsp02_run.install.nspanel_eu.tft.txt)

**Comment by Mithrox** [comment]
Another note, I did not test with my other panel, the one mounted in my sons room. I tried the normal transfer again, and it also failed at only 8% (that was still in 115k baudrate). So it's not isolated to just one panel, I wanted to test just to rule out an issue with one piece of hardware.

**Comment by edwardtfn** [comment]
I'm afraid this could be not in the panel, but something related to an instable Wi-Fi or your http server crashing for some reason.

One thing we could do to improve the network would be adding this to your yaml (custom area):

```yaml
```

Another thing is to try another web server. If you want, you can try this url for your file: `http://nspanel.costafirmo.com/tft/v4.1.4/nspanel_eu.tft`

**Comment by edwardtfn** [comment]
Sorry, I missed the text there. Just fixed.

In the end, your yaml will be like this for the next test:
```yaml
substitutions:
###### CHANGE ME START ######
  device_name: "nsp02" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

#  nextion_update_url: "http://10.1.1.15:8123/local/nspanel_blank.tft"
#  nextion_update_url: "http://10.1.1.15:8123/local/nspanel_eu.tft"
  nextion_update_url: "http://nspanel.costafirmo.com/tft/v4.1.4/nspanel_eu.tft"  # Just for a temporary test, don't use it later

  ##### CHANGE ME END #####

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # - nspanel_esphome_advanced.yaml # activate advanced (legacy) elements - can be useful for troubleshooting
      # - nspanel_esphome_addon_climate_cool.yaml # activate for local climate (cooling) control
      # - nspanel_esphome_addon_climate_heat.yaml # activate for local climate (heater) control
    refresh: 300s

##### My customization - Start #####
esp32:
  framework:
    type: esp-idf
wifi:
  power_save_mode: NONE
##### My customization - End #####
```
