### ISSUE TITLE
Version substitution missing when including .nspanel_esphome.yaml

### ISSUE THREAD

**Issue by Plawasan** [Blackymas/NSPanel_HA_Blueprint#1118]
I have 5 panels around the house, the ESPhome yaml for each of them looks like this:

```
substitutions:
  device_name: "nspanel_office" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  nextion_update_url: "http://192.168.1.10:8123/local/nspanel_eu.tft" # URL to local tft File

<<: !include .nspanel_esphome.yaml
```

The .nspanel_esphome.yaml files is an exact copy of the file from the latest (at this point 4.0.2) release. When I try to compile the FW, I get the following error:

```
INFO ESPHome 2023.9.0
INFO Reading configuration /config/esphome/nspanel-office.yaml...
WARNING Found 'id(disp1).goto_page("boot");
id(disp1).set_component_text_printf("boot.esph_version", "%s", "${version}"); // ### esphome-version ###
id(disp1).show_component("bt_reboot");
id(timer_reset_all).execute("boot");' (see display->0->on_setup->then->0->lambda) which looks like a substitution, but 'version' was not declared
```

The workaround to that is pretty simple - adding the version substitution line directly into the "parent" yaml:

```
substitutions:
  device_name: "nspanel_office" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  nextion_update_url: "http://192.168.1.10:8123/local/nspanel_eu.tft" # URL to local tft File
  version: "4.0.2"

<<: !include .nspanel_esphome.yaml
```
With this everything compiles correctly however it's not exactly an elegant solution... I'm pretty confident this was not needed in version pre 4.0, has been an issue for me since 4.0.

ESPHome - 2023.9.0 (was an issue even with 2023.8.x)
NSPanel version - 4.0.2 (in an issue since 4.0)

Thanks

**Comment by edwardtfn** [comment]
Please try this:

```yaml
substitutions:
  device_name: "nspanel_office" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  nextion_update_url: "http://192.168.1.10:8123/local/nspanel_eu.tft" # URL to local tft File
  version: "4.0.2"

packages:
  local_package: !include .nspanel_esphome.yaml
```
