### ISSUE TITLE
Open entity settings page from a node red automation

### ISSUE THREAD

**Issue by rbr101** [Blackymas/NSPanel_HA_Blueprint#1135]
Hi ,

I used to show an entity setting on the nspanel using an automation with _set_settings_entity and the following data:

{"entity":"{\"page\": \"home\", \"entity\": \"light.keuken_aanrecht\"}"}

After upgrading to 4.0.2 this does not work anymore and i see the service is replaced with:

open_entity_settings_page:

```
service: esphome.nspanel_woonkamer_open_entity_settings_page
data:
  page_icon_color: color
  page: page
  page_label: label
  page_icon: icon
  entity: entity
  back_page: back_page
```

Can you please give an example how to show an entity with this service ?
I want to show an the entity settings for lights when a non nspanel button is pressed (wall switch) , so i can easily access the brightness settings on the nspanel.

**Comment by edwardtfn** [comment]
Please try this:

```yaml

service: esphome.nspanel_woonkamer_open_entity_settings_page
data:
  page_icon_color: []
  page: light
  page_label: My light
  page_icon: ""
  entity: light.keuken_aanrecht
  back_page: home
```
