### ISSUE TITLE
Dutch weather service buienradar not working in nspanel 4.0.2

### ISSUE THREAD

**Issue by rbr101** [Blackymas/NSPanel_HA_Blueprint#1139]
I noticed the weather forecast for the dutch buienradar integration is not working in the nspanel.
It does show the first page, but when swiping to day 2, 3 and 4 no data is displayed.

Changed buienradar to openweather in the nspanel configuration and then it works fine.

This did work in version 3.x

**Comment by rbr101** [comment]
Here are the values for weather.br:

```
temperature: 14.4
apparent_temperature: 14.4
temperature_unit: °C
humidity: 76
pressure: 1024.8
pressure_unit: hPa
wind_bearing: 248
wind_speed: 12.6
wind_speed_unit: km/h
visibility: 31.3
visibility_unit: km
precipitation_unit: mm
forecast: 
- datetime: '2023-09-26T00:00:00+02:00'
  condition: partlycloudy
  wind_bearing: 180
  temperature: 21
  templow: 11
  wind_speed: 12.96
  precipitation: 0
- datetime: '2023-09-27T00:00:00+02:00'
  condition: partlycloudy
  wind_bearing: 180
  temperature: 23
  templow: 13
  wind_speed: 7.42
  precipitation: 0
- datetime: '2023-09-28T00:00:00+02:00'
  condition: cloudy
  wind_bearing: 225
  temperature: 21
  templow: 16
  wind_speed: 20.38
  precipitation: 0.5
- datetime: '2023-09-29T00:00:00+02:00'
  condition: rainy
  wind_bearing: 270
  temperature: 21
  templow: 14
  wind_speed: 20.38
  precipitation: 1.5
- datetime: '2023-09-30T00:00:00+02:00'
  condition: partlycloudy
  wind_bearing: 270
  temperature: 20
  templow: 11
  wind_speed: 12.96
  precipitation: 0

attribution: Data provided by buienradar.nl
friendly_name: Buienradar
supported_features: 1
```
