### ISSUE TITLE
Feature request: additional configuration for embedded (fallback) thermostat

### ISSUE THREAD

**Issue by quenthal** [Blackymas/NSPanel_HA_Blueprint#1171]
1) I'd like to make HEAT default instead of  "OFF". This way it would default to heating (if there is for example power interruption) within the parameters of thermostat. I assume this would be achieved as follows in  ..heat.yaml:
Make  default_preset: "Home"
Add mode: HEAT to Home-preset:
      - name: Home
        default_target_temperature_low: 22 ${temp_units}
        mode: HEAT

2) I'd like to overwrite also Thermostat's friendly name from main yaml. Current implementation makes it so that if I change the thermostat's name in HA, it "flickers" in NSPanel (ie. it shows for short instant the "nspanelname Thermostat" string and then quickly replaces it by the friendly name. This can be avoided by renaming the thermostat title to whatever user wants in esphome's yaml.

3) I'd also like to make the default target temp configurable.

QUESTION: I'm currently pointing blueprint to this embedded one, I assume this is the correct way?

**Comment by edwardtfn** [comment]
My apologies for my late reply here... it's a busy week. :(

You can get most of the things you are asking for with [customizations](https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/docs/en/customization.md). I would try this:

```yaml
##### My customization - Start #####
climate:
  - id: !extend thermostat_embedded
    name: "Any friendly name you want"
    default_preset: Home
    on_boot_restore_from: memory
    preset:
      - name: Home
        default_target_temperature_low: 22 ${temp_units}
        mode: "heat"
##### My customization - End #####
```

> I'd like to make HEAT default instead of "OFF". This way it would default to heating (if there is for example power interruption) within the parameters of thermostat. I assume this would be achieved as follows in ..heat.yaml:

I haven't used this myself, but I would expect the previous set to be recovered after a power outage, but that probably requires that `on_boot_restore_from` (see my example above) which probably should be part of the main implementation.
Please let me know if that works for you and I can add that to the code for everyone.

> Current implementation makes it so that if I change the thermostat's name in HA, it "flickers" in NSPanel (ie. it shows for short instant the "nspanelname Thermostat" string and then quickly replaces it by the friendly name.

This sounds like a bug. I will take a look later.

> I'd also like to make the default target temp configurable.

Here we are limited to [what ESPHome makes available](https://esphome.io/components/climate/thermostat.html), but we can certainly add some additional control and solve this...
Could you please explain better what would you expect from this so I can try to play around?

> I'm currently pointing blueprint to this embedded one, I assume this is the correct way?

Yes, that is the correct way.
