### ISSUE TITLE
How can i transfer a flashed NSPanel to a new wifi / home without flashing it?

### ISSUE THREAD

**Issue by TeDeVPrime** [Blackymas/NSPanel_HA_Blueprint#1177]
Hi, 

i am not sure how i can flash an nspanel pro... make sure that it works and then move it to another location to a different wifi and just integrate it to that home assistant.

any guides or do i always have to reflash with cables the entire thing?

thanks

**Comment by bkbartk** [comment]
Do you want to know for the pro or the non-pro?
Because those are 2 completely different devices. 
for non-pro. 
if you have Ap an captive portal installed. The esp should provide an so where you can connect to. 
For the pro. I don’t know.

**Comment by edwardtfn** [comment]
As far as I know, NSPanel PRO is not ESP based and therefore is not compatible with ESPHome and this project.

But if you are talking about the older NSPanel, are you trying to do this only once or are you planing to do multiple times for redistributing panels?
For the first case, the suggestion from @bkbartk should be the way to go, but if you are planing to redistribute, I would suggest something like this: https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/pre-built/nspanel_esphome_prebuilt.yaml

**Comment by TeDeVPrime** [comment]
sorry i meant NSPanel. not pro.

i want to prepare some nspanels for a couple of friends. so i want to flash them... make sure that they work and then send them to them. 

i don't know what the next step would be

**Comment by bkbartk** [comment]
probably you have to do some customization,
I always copy the esphome yaml locally and strip thos component
```
wifi
captive_portal
web_server
ota
```
and load them from my own base config.
so it's al tease the same as everything else
my config in the would look something like this
```
substitutions:
  device_name: "My-name" 

packages:
  base: !include .base.yaml
  device: !include .nspanel.yaml
####
# some custom config per device
```
but the main goal is that you need to understand how esphome works using wifi, ap and captive_portal.
you can try to work with that and once that works like you hope you can just install the full yaml.

I actually thing cahnging wifi to this
```
wifi:
  ap:
    ssid: "${device_name}"
    password: ${wifi_password}
```
would work, Keep in mind to not use your own wifi_password here.

**Comment by TeDeVPrime** [comment]
@bkbartk well i don't really know how ESPHome works so not that clear for me yet.

at the moment i have 3 places (my main home, office, "weekend house") and two friends' houses that want to flash their nspanel as well.

they don't have the tools or even the skills to flash the device. i have done it three times up until now and it has been a pain every time. i don't want to go to their home in order to flash the device and then pass the parameters through Home Assistant.

i want to find a way to flash it at my place with TFT and then ship it to them. 
somehow they need to install the device and connect it to their ESPHome and wirelessly install their config to the devices that i will send them.

so if you guys can help me with the steps, it would be great. @edward i saw your last link but i am not sure what's the next step after i flash the device with that.

**Comment by bkbartk** [comment]
well, the easiest way,
ask your friends for there wifi credentials.
and add both yours and theirs,
https://esphome.io/components/wifi.html#connecting-to-multiple-networks
then you can test and ship, 
and if it fails to work they should have provided the correct credentials.

but main advise, before helping some friends with something you don't know that much about is to read a little bit of documentation, how does the yaml work
and how does https://esphome.io/components/captive_portal.html work
if you know that you can help them much better.

**Comment by TeDeVPrime** [comment]
thank you i will test it out first with multiple wifi credentials.
i suppose that when they power it up, all they have to do is go to esphome.... add new device and then they will discover it.

**Comment by fordcrews** [comment]
Can you set the ota password to something different from the wifi with a substitution?

**Comment by edwardtfn** [comment]
Yeah, you can do that. Not with a substitution, but it is possible.

Please take a look at this: https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-Customization#custom-ota-password

**Comment by fordcrews** [comment]
> Yeah, you can do that. Not with a substitution, but it is possible.
> 
> Please take a look at this: https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-Customization#custom-ota-password

I had seen that, but that means I have to load the code locally, edit it, then have to repeat every time a new version comes out.   

Guess I was thinking out loud, trying to figure out how to break the ota password to wifi password link, cause that sure makes it hard to change wifi networks.

**Comment by edwardtfn** [comment]
> I had seen that, but that means I have to load the code locally, edit it, then have to repeat every time a new version comes out.

Nope. Please see the example at the beginning of that page. You add just those lines to your local yaml, but still with the reference for the server.

Take a look there, if you still have questions,please share here your yaml (hide passwords) and I can propose the changes for you.

**Comment by fordcrews** [comment]
Ok I had assumed that as

ota:
  id: ota_std
  password: ${wifi_password}
  safe_mode: true
  reboot_timeout: 3min
  num_attempts: 3

was in nspanel_esphome.yaml I couldn't have an ota: section in my code that then loaded nspanel_esphome.yaml, I figured it would either error, or used the last one loaded.

**Comment by edwardtfn** [comment]
Currently, your OTA password is your Wi-Fi password. In order to change that, you have to send a new OTA, but to sent that you must use the older one otherwise it will fail. Unless you want to flash using serial, as the OTA password is not tested in that case (that is not OTA).
To change the OTA, add this to your ESPHome yaml:

```yaml
##### My customization - Start #####
# change OTA password, remove after flashing
esphome:
  on_boot:
    - lambda: |-
        id(my_ota).set_auth_password("YourNewOTApassword");
ota:
  password: !secret wifi_password
  id: my_ota
##### My customization - End #####

Flash you device with this, then remove the code above and instead you should have the following (now, using the new OTA):
```yaml 
##### My customization - Start #####
# Use my own OTA password
ota:
  password: "YourNewOTApassword"
```
Or if you want to keep it in a secrets file (as recommended by ESPHome docs), use `password: !secret ota_password` instead.
You will keep this last version of ota customization forever (or at least until you decide to change it again).
