### ISSUE TITLE
Feature Request: Ability to load specific page/entity from home assistant service

### ISSUE THREAD

**Issue by dkvhin** [Blackymas/NSPanel_HA_Blueprint#1197]
Would be nice to have a service that can open specific page/entity.  (Not sure if this already exists, as I cannot find any documentation or available service)

example:
When I trigger a music automation or script, I can force specific panels to display the media player entity

**Comment by edwardtfn** [comment]
For opening a generic page, you can use service `esphome.xxxxx_send_command_printf`.
For more details: https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-HowTo---All-important-thing-you-should-know#11-call-certain-pages-directly

If you wanna open one of the detailed entity pages, use `esphome.xxxxx_open_entity_settings_page` like this:
```yaml
service: esphome.office_workstation_panel_open_entity_settings_page
data:
  page: light
  page_label: My light name
  page_icon_color: 246, 34, 27
  page_icon: \uF8DC
  entity: light.my_light
  back_page: home
```
You can find the icon's codes on this page: https://htmlpreview.github.io/?https://github.com/jobr99/Generate-HASP-Fonts/blob/master/cheatsheet.html
