### ISSUE TITLE
Question: Can I add a static_ip to the wifi section of esphome yaml?

### ISSUE THREAD

**Issue by smarthomefamilyverrips** [Blackymas/NSPanel_HA_Blueprint#1198]
Is it possible to add the below lines at the bottom of the wifi section of my nspanel config yaml in esphome to set and use a static_ip?

```
wifi:
  networks:
    - id: wifi_default
      ssid: ${wifi_ssid}
      password: ${wifi_password}
  power_save_mode: none
  ap:
    ssid: "${device_name}"
    password: ${wifi_password}
  manual_ip:
    static_ip: 192.168.0.102
    gateway: 192.168.0.1
    subnet: 255.255.255.0
```
