### ISSUE TITLE
Feature Request: Alarm - Ability to call disarm panel directly from button

### ISSUE THREAD

**Issue by HolmbomDK** [Blackymas/NSPanel_HA_Blueprint#1199]
I want the 2 physical buttons on the NSpanel to control the alarm. 

Left physical button to set the alarm
I have no problem to set the alarm, because I do not need input to set the alarm from NSpanel, except from touching the left button.

Right physical button to disarm.
But I have a code to disarm, and I do not want to hard code it into the system because thís is bad security. and a bad practice to start on. 
I want to go direct to the disarm keyboard , and I know it is page "keyb_num" but but this call does not work:

`service: esphome.nspanel_send_command_printf
data:
  cmd: page keyb_num
`
If possible please help or else it is a feature request

**Comment by edwardtfn** [comment]
Those "pop-up" pages are a bit more complex, as you must first open the entity detailed page, and "alarm" page is a special case also.

Right now, there's no support for alarms in the button pages, so calling the alarm page will take care of finding the `entity_id`, etc., and then you can just simulate a button press, but this might change in the near future (and then come back here 😄 ).

For now, please try this:
```yaml
- service: esphome.xxxxx_send_command_printf
  data:
    cmd: page alarm
- delay:
    milliseconds: 100
- service: esphome.xxxxx_send_command_printf
  data:
    cmd: click bt_disarm,1
- delay:
    milliseconds: 50
- service: esphome.xxxxx_send_command_printf
  data:
    cmd: click bt_disarm,0
```
This is opening the alarm page, waiting 0.1 sec, then clicking the button disarm for 0.5 sec then releasing it.
