### ISSUE TITLE
How to change wifi?

### ISSUE THREAD

**Issue by kchiem** [Blackymas/NSPanel_HA_Blueprint#1201]
When I update the secrets wifi_ssid and wifi_password, trying to update the nspanel gives me:

`ERROR Error auth result: Error: Authentication invalid. Is the password correct?`

**Comment by edwardtfn** [comment]
This is due to the change of OTA, as wifi password is used for OTA password.

Please take a look at this: https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-Customization#custom-ota-password

**Comment by kchiem** [comment]
Ah, that makes sense.  Thank you!

But question:

If I use this:

```
##### My customization - Start #####
# change OTA password, remove after flashing
esphome:
  on_boot:
    - lambda: |-
        id(my_ota).set_auth_password("YourNewOTApassword");
ota:
  password: !secret wifi_password
  id: my_ota
##### My customization - End #####
```

So that `YourNewOTApassword` was my new wifi password for the new ssid, would I still need this later when I change the wifi_ssid and wifi_password secrets?

```
##### My customization - Start #####
# Use my own OTA password
ota:
  password: "YourNewOTApassword"
##### My customization - End #####
```

I'm thinking no, but thought I'd confirm.
