### ISSUE TITLE
Relay scheduled fallback

### ISSUE THREAD

**Issue by spaetzel10** [Blackymas/NSPanel_HA_Blueprint#1209]
Is there a possibility to implement a scheduled fallback in case of connection loss? Since my case is sensitive, it would be great to have an option to switch the relays based on a schedule, if there is no connection.

**Comment by edwardtfn** [comment]
Are you using your relay for an embedded climate control or something else?

ESPHome doesn't have a scheduler component for this, so it would be needed to develop a nice user interface for this to work autonomously. This would be some work.
However, you can easily achieve this with customizations. Something like this:

```yaml
##### My customization - Start #####
time:
  - id: !extend time_provider
    on_time:
      - hours: 7
        minutes: 0
        seconds: 0
        then:
          - climate.control:
            id: thermostat_embedded
            mode: auto
            target_temperature: 22°C
      - hours: 19
        minutes: 0
        seconds: 0
        then:
          - climate.control:
            id: thermostat_embedded
            mode: auto
            target_temperature: 20°C
      - hours: 23
        minutes: 0
        seconds: 0
        then:
          - climate.control:
            id: thermostat_embedded
            mode: auto
            target_temperature: 18°C
##### My customization - End #####
```

**Comment by spaetzel10** [comment]
Thanks for your quick answer.
I replaced a light switch next to my entrance with the panel. This is switching the light for a living wall in my hallway. Since i do not have a permanent live wire at the living wall, I had to install a second smart relay powered by the light, to implement a scheduled irrigation for the plants. So, if the light is off, there won't be power for the irrigation.

Do I simply have to add the adapted code above to the esphome code for the blueprint?

Big Thx

**Comment by edwardtfn** [comment]
You can add to your local ESPHome yaml, so no need to play with the huge (and constantly changing) remote file, which will save you to have to edit every time a new version is available.

Something like this:

```yaml
substitutions:
  ###### CHANGE ME START ######
  device_name: "YOUR_NSPANEL_NAME" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: "http://homeassistant.local:8123/local/nspanel_us.tft"

  ##### addon-configuration #####
  ## addon_climate ##
  # addon_climate_heater_relay: "1" # possible values: 1/2

  ##### CHANGE ME END #####

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # - nspanel_esphome_addon_climate_cool.yaml # activate for local climate (cooling) control
      # - nspanel_esphome_addon_climate_heat.yaml # activate for local climate (heater) control
    refresh: 300s

##### My customization - Start #####
# Irrigation scheduler
time:
  - id: !extend time_provider
    on_time:
      - hours: 7
        minutes: 30
        seconds: 0
        then:
          - switch.turn_on: relay_1
      - hours: 20
        minutes: 4
        seconds: 0
        then:
          - switch.turn_off: relay_1
##### My customization - End #####
```
