### ISSUE TITLE
Device gets stuck on the initialisation screen

### ISSUE THREAD

**Issue by edwardtfn** [Blackymas/NSPanel_HA_Blueprint#1224]
It seems like after I cycled the power of the device it al;ways gets stuck on the initialisation screen and the esp home log shows 

And the ESPHome log has this
[19:02:08][W][nextion:072]: Nextion is not connected! 
[19:02:09][W][nextion:072]: Nextion is not connected! 
[19:02:09][W][nextion:072]: Nextion is not connected! 

If then I trigger a reset of  ESP device from HA via the button it boots to the home screen with black button pages

_Originally posted by @FrankBakkerNl in https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/1223#issuecomment-1792899055_

**Comment by FrankBakkerNl** [comment]
Tnx for re-posting. 

As a workaround I created a small automation in HA that restarts the device when I hold the right hardware button for 10 seconds. This allows me to manually get it to start up after a power cycle which should be rare. Ofc it would be way better if the device itself would detect this situation and do a restart if needed.

**Comment by edwardtfn** [comment]
I will try to find a way to handle this situation without having to restart, otherwise we either have to implement a restart counter (which costs memory) or will risk to have it restarting in a loop.

**Comment by FrankBakkerNl** [comment]
Cool, now the basic stuff is working I have to say this blueprint solution works awesome!

**Comment by FrankBakkerNl** [comment]
EspHome has a restart counter internally, maybe there is a way to hook into that?

**Comment by edwardtfn** [comment]
Yeah, but anyways I will have to register how many of those are due to this issue, to prevent the loop.
I believe it can be solved without a restart. As we can control the power to the display, I've played a bit with that and looks promising.

**Comment by edwardtfn** [comment]
By the way, I liked your idea of having a reset with the hardware button. I'm now thinking about implementing this for everyone.

You mentioned you have this in an automation on Home Assistant, but you can instead have it controlled locally by ESPHome, so it will work even when Wi-Fi is out.
Just add this to your yaml:

```yaml
##### My customization - Start #####
binary_sensor:
  - id: !extend right_button
    on_multi_click:
      - timing:
          - ON for at least 10.0s
        then:
          - button.press: restart_nspanel
##### My customization - End #####
```

It is simpler and more reliable than having this from HA.
