### ISSUE TITLE
Minor: Weather forecast icon for snowy rain not showing

### ISSUE THREAD

**Issue by Floppe** [Blackymas/NSPanel_HA_Blueprint#1245]
Both the old stable and new dev versions have missing icons in the weather page.

Could be related to the weather integration as I am using "met.no". In the 4.1dev5 version it's the "snowy, rain" icon that is not showing in both home screen and weather screens.

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/238729/0447f100-bc74-4191-a791-b09c74df2ab8)

**Comment by edwardtfn** [comment]
Could you please go to Developer Tools, tab States, search for this entity and let me know how is the state shown on that page?

**Comment by Floppe** [comment]
current state: snowy-rainy
attributes:

```
temperature: 1.4
dew_point: 0.6
temperature_unit: °C
humidity: 96
cloud_coverage: 100
pressure: 1001.5
pressure_unit: hPa
wind_bearing: 76.3
wind_gust_speed: 8.69
wind_speed: 5.19
wind_speed_unit: m/s
visibility_unit: km
precipitation_unit: mm
forecast: 
- condition: rainy
  precipitation_probability: 100
  datetime: '2023-11-10T10:00:00+00:00'
  wind_bearing: 80.1
  temperature: 2.3
  templow: 1.4
  wind_gust_speed: 9.31
  wind_speed: 5.5
  precipitation: 7.8
  humidity: 96
- condition: snowy-rainy
  precipitation_probability: 87.8
  datetime: '2023-11-11T10:00:00+00:00'
  wind_bearing: 64.4
  temperature: 1.9
  templow: 0.7
  wind_gust_speed: 9
  wind_speed: 5.31
  precipitation: 5.5
  humidity: 95
- condition: snowy-rainy
  precipitation_probability: 75.6
  datetime: '2023-11-12T10:00:00+00:00'
  wind_bearing: 79.7
  temperature: 1.1
  templow: -0.5
  wind_gust_speed: 9.19
  wind_speed: 5.39
  precipitation: 7.2
  humidity: 92
- condition: cloudy
  precipitation_probability: 21.6
  datetime: '2023-11-13T10:00:00+00:00'
  wind_bearing: 20.3
  temperature: -1.2
  templow: -1.9
  wind_speed: 4.69
  precipitation: 0
  humidity: 83
- condition: cloudy
  precipitation_probability: 5.9
  datetime: '2023-11-14T10:00:00+00:00'
  wind_bearing: 26.6
  temperature: -3.2
  templow: -6.1
  wind_speed: 4.61
  precipitation: 0
  humidity: 78
- condition: partlycloudy
  precipitation_probability: 3.9
  datetime: '2023-11-15T10:00:00+00:00'
  wind_bearing: 62.5
  temperature: -4.4
  templow: -7.8
  wind_speed: 3.19
  precipitation: 0
  humidity: 78

attribution: Weather forecast from met.no, delivered by the Norwegian Meteorological Institute.
friendly_name: Forecast Home
supported_features: 3
```
