### ISSUE TITLE
Calendar/Schedule icon permanently displayed when using climate entity.

### ISSUE THREAD

**Issue by Plawasan** [Blackymas/NSPanel_HA_Blueprint#1265]
I'm running all 5 of my displays now on 4.1 however I've noticed this issue on two of them even on earlier versions - there is a "stray" mdi:calendar-refresh icon permanently displayed on the home screen, without any (obvious to me) reason for it.

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/73796046/e03e1453-bf7c-43c6-b017-7d66f50d11ca)

 I tried to gradually single out what line in my yaml causes it (since I've carried that config over from early versions), as far as I can tell it shows up the moment I add a climate entity, in my case:

```
alias: NSPanel Office
description: ""
use_blueprint:
  path: Blackymas/nspanel_blueprint.yaml
  input:
    nspanel_name: 0fe7541674415f222c988eb12cddd100
    weather_entity: weather.forecast_stodulky
    outdoortemp: sensor.external_temperature
    climate: climate.atrea_modbus   <---- this line
```

Is this by design or a bug?

**Comment by edwardtfn** [comment]
Since the beginning, the 3rd chips was reserved for the climate entity, while 1st and 2nd are reserved for relays, and the others are customizable.
What changes in v4.0 was the icon shown, which is now based on the state of your climate, which in your case is probably 'scheduled'.

**Comment by Plawasan** [comment]
FWIW, this is what the entity state/attributes look like - nothing suggesting a "scheduled" state

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/73796046/e5ccce3e-8e6d-441c-be5d-2f492805acda)

**Comment by edwardtfn** [comment]
Mmmm
I will have to take a look when back home.

**Comment by edwardtfn** [comment]
I'm trying to duplicate this without success. Probably something missing from my side.

Could you please share your ESPHome yaml so I can duplicate exactly the same here? Please make sure to hide any sensitive info before sharing.

**Comment by Plawasan** [comment]
Sure, should be very standard:

nspanel-office.yaml:

```
substitutions:
  device_name: "nspanel_office" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
packages:
  core_package: !include nspanel_esphome_core.yaml
  upload_tft_package: !include nspanel_esphome_addon_upload_tft.yaml
```

both the included files are taken directly from the 4.2 release, with the only exception of the tft url, which points to my local HA instance which hosts the latest 4.2 tft file (getting that from github never worked for me).
