### ISSUE TITLE
Switching heater on on thermostat page doesn't work anymore.

### ISSUE THREAD

**Issue by 0hax** [Blackymas/NSPanel_HA_Blueprint#1266]
I switched to v4.1 few hours ago and setting the climate in the thermostat page to "ON" doesn't switch on the relay anymore.
Here is my config:
```
substitutions:
  wifi_ssid: "aa"
  wifi_password: "aa"
  device_name: "salon"
  nextion_update_url: "http://homeassistant.local:8123/local/nspanel_eu.tft"
  heater_relay: "1" # Select 1 for "Relay 1", 2 for "Relay 2" or "0" to a dummy switch/disabled
packages:
  main: !include nspanel_esphome.yaml
  addon_climate: !include nspanel_esphome_addon_climate_heat.yaml
```
