### ISSUE TITLE
After Update "NSPanel sensor unavailable"

### ISSUE THREAD

**Issue by pillemats** [Blackymas/NSPanel_HA_Blueprint#1277]
hi together

last days HA has updated esphome, ha itself and many other apps.

after that  i get this message and tried to fix it but i cant activate the sensor!

<img width="496" alt="Bildschirmfoto 2023-11-15 um 20 16 49" src="https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/26164977/c3070ece-00ef-44f2-ab0c-704acd32463c">

<img width="1005" alt="Bildschirmfoto 2023-11-15 um 20 16 57" src="https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/26164977/235aaecf-c508-44aa-baa6-14b1730d821a">

the display on the panel is complely empty. only shows the background.

What should i do now?

here is the log file from esphome

[logs_nspanel-dachboden_logs-2.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/13368827/logs_nspanel-dachboden_logs-2.txt)
and my nspanel config:

```
substitutions:

###### CHANGE ME START ######

  device_name: "nspanel-dachboden" 
  wifi_ssid: "xx"
  wifi_password: "xx"

  nextion_update_url: "http://192.168.178.205:8123/local/nspaneleu.tft" # URL to local tft File
#  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft" # URL to Github

##### CHANGE ME END #####



##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####

```
Thanks for some help
