### ISSUE TITLE
Cannot update TFT (at least with SSL)

### ISSUE THREAD

**Issue by SheepKnight** [Blackymas/NSPanel_HA_Blueprint#1282]
**ESPHome version** : 2023.11.0
**NSPanel_HA_Blueprint Version** : 4.1 
**NSPanel label** : "E32-MSW-NX 100148ae51 P/N:WW210687 NSPanel-EU"

After a fresh install following the quick setup guide, I had an issue with updating the nextion TFT.

After about 70 seconds after pressing the update TFT button, the ESP32 panic'ed. 
It only reached ~15% of the download
(I've got a Traceback thanks to the boot message forwarded on a through the serial port on the ESP_TX test pad)
I used this config : 
```
substitutions:
  ###### CHANGE ME START ######
  device_name: "nspanel" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: "https://192.168.69.2:8123/local/nspanel_eu.tft"

  ##### addon-configuration #####
  ## addon_climate ##
  # addon_climate_heater_relay: "1" # possible values: 1/2

  ##### CHANGE ME END #####

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # - nspanel_esphome_advanced.yaml # activate advanced (legacy) elements - can be useful for troubleshooting
      # - nspanel_esphome_addon_climate_cool.yaml # activate for local climate (cooling) control
      # - nspanel_esphome_addon_climate_heat.yaml # activate for local climate (heater) control
    refresh: 300s

##### My customization - Start #####
##### My customization - End #####
```
Please note I also tried to upload the blank tft, the nspanel_eu.tft hosted directly on github, and with my proper domain name.

Following this issue #1272, I added the following lines to my configuration :
```
esp32:
  framework:
    type: esp-idf
```
However, it doesn't seem to be compatible with SLL returning following error :

```
No server verification option set in esp_tls_cfg_t structure. Check esp_tls API reference
```

When hosting the .tft file on a plain apache2 http server without ssl, it finally seemed to work, but I would like to be able to set up a proper hosting.

I don't know if I can configure the ssl parameters that are missing with ESPHome & esp-idf framework, in order to configure a more "long term & clean" hosting.

(BTW, thanks for this awesome project ! :heart: )

**Comment by danir-de** [comment]
I'm having the same problem with some devices, but it's only affecting those that already had TFT download problems previously and where I had to use the workaround that was tested in the discussion thread.

**Comment by edwardtfn** [comment]
I could duplicate and the version with ESP-IDF framework isn't supporting HTTPS, so you have to use HTTP.
If you use arduino framework then HTTPS is supported, although it still not recommended (by ESPHome team).

**Comment by danir-de** [comment]
> I could duplicate and the version with ESP-IDF framework isn't supporting HTTPS, so you have to use HTTP. If you use arduino framework then HTTPS is supported, although it still not recommended (by ESPHome team).

So some of my devices must be on the Arduino framework and some on the ESP-IDF framework then.
How do I switch between them?

**Comment by edwardtfn** [comment]
You can force the framework by adding this to your ESPHome yaml:

### Arduino
```yaml
esp32:
  framework:
    type: arduino
```

### ESP-IDF
```yaml
esp32:
  framework:
    type: esp-idf
```
