### ISSUE TITLE
addon_climate

### ISSUE THREAD

**Issue by Foxinbox375** [Blackymas/NSPanel_HA_Blueprint#1286]
Good afternoon, I want to use an nspanel thermostat, but I would like to be able to adjust parameters such as: 

set_point_minimum_differential:
heat_deadband:
heat_overrun:
default_preset: 
on_boot_restore_from: 

And I also want to set the values ​​for the presets myself (home, away)
    preset:
      - name: "Off"
        default_target_temperature_low: ${temp_min} ${temp_units}
        mode: "off"
      - name: Home
        default_target_temperature_low: 21.8 ${temp_units}
        mode: "heat"
      - name: away
        default_target_temperature_low: 19 ${temp_units}
        mode: "heat" 
   
Please tell me how to do this from the nspanel ESPHome configuration file?

**Comment by sheaur** [comment]
nspanel_esphome_addon_climate_base.yaml:

climate:
  - platform: thermostat
    name: ${device_name} Thermostat
    heat_deadband: 0.3
    heat_overrun: 0.0
    id: thermostat_embedded
    sensor: temp_nspanel
    min_idle_time: ${min_idle_time}s

nspanel_esphome_addon_climate_heat.yaml:

climate:
  - id: !extend thermostat_embedded
    min_heating_off_time: ${min_off_time}s
    min_heating_run_time: ${min_run_time}s
    heat_action:
      - switch.turn_on: relay_${heater_relay}
    preset:
      - name: "Off"
        default_target_temperature_low: ${temp_min} ${temp_units}
        mode: "off"
      - name: Home
        default_target_temperature_low: 21 ${temp_units}
        mode: "heat"
      - name: Away
        default_target_temperature_low: 16.5 ${temp_units}
        mode: "heat"
      - name: Sleep
        default_target_temperature_low: 17.5 ${temp_units}
        mode: "heat"
packages:
  core_package: !include nspanel_esphome_addon_climate_base.yaml

**Comment by Foxinbox375** [comment]
> nspanel_esphome_addon_climate_base.yaml:
> 
> climate:
> 
> * platform: thermostat
>   name: ${device_name} Thermostat
>   heat_deadband: 0.3
>   heat_overrun: 0.0
>   id: thermostat_embedded
>   sensor: temp_nspanel
>   min_idle_time: ${min_idle_time}s
> 
> nspanel_esphome_addon_climate_heat.yaml:
> 
> climate:
> 
> * id: !extend thermostat_embedded
>   min_heating_off_time: ${min_off_time}s
>   min_heating_run_time: ${min_run_time}s
>   heat_action:
>   
>   * switch.turn_on: relay_${heater_relay}
>     preset:
>   * name: "Off"
>     default_target_temperature_low: ${temp_min} ${temp_units}
>     mode: "off"
>   * name: Home
>     default_target_temperature_low: 21 ${temp_units}
>     mode: "heat"
>   * name: Away
>     default_target_temperature_low: 16.5 ${temp_units}
>     mode: "heat"
>   * name: Sleep
>     default_target_temperature_low: 17.5 ${temp_units}
>     mode: "heat"
>     packages:
>     core_package: !include nspanel_esphome_addon_climate_base.yaml

Could you write where exactly these lines need to be added, or attach a screenshot?
Thank you.

**Comment by edwardtfn** [comment]
@sheaur, why have you edited the `nspanel_esphome_addon_climate_base.yaml`? Couldn't all the changes be as a customization on the ESPHome yaml?

Something like this:
```yaml
climate:
  - id: !extend thermostat_embedded
    preset:
      - name: "Off"
        default_target_temperature_low: ${temp_min} ${temp_units}
        mode: "off"
      - name: Home
        default_target_temperature_low: 21 ${temp_units}
        mode: "heat"
      - name: Away
        default_target_temperature_low: 16.5 ${temp_units}
        mode: "heat"
      - name: Sleep
        default_target_temperature_low: 17.5 ${temp_units}
        mode: "heat"
```

@Foxinbox375, you add this at your ESPHome yaml. The one you use to set your wifi password, device name, TFT url, etc.
You can add those lines at the end of your file and install it to your panel (wireless is ok).
I believe only those changes I sent here are sufficient. No need to do all those changes indicated by @sheaur, I believe.
