### ISSUE TITLE
Double Click Physical  Buttons  - New Feature 

### ISSUE THREAD

**Issue by rudgej** [Blackymas/NSPanel_HA_Blueprint#1301]
The buttons currently support press and long press.

I uses these for scene section ( Off / Room Low/ Room Mid / Room Hi) across all panels and rarely use the actual display.

Could this be expended to allow for double click, and whilst you are at it triple click?

Double click for me would be blinds open / close and triple click would be air con on/off.

The displays are great but for most actions standard button presses across all panels is simpler for everyone in the house.

**Comment by deejaybeam** [comment]
https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/259

**Comment by rudgej** [comment]
Ok thank you - so the answer is no but there is a work around if I can figure it out!

**Comment by edwardtfn** [comment]
As you can see in the discussion pointed by @deejaybeam, it's a bit hard to find the one solution which fits all on this, but you probably can achieve this as a [customization](https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-Customization) to your system without big effort.

One example to send a command to toggle a blind with a double click on left button will be like this:
```yaml
binary_sensor:
  - id: !extend left_button
    on_multi_click:
      #Double Click
      - timing:
          - ON for at most 0.5s
          - OFF for at most 0.3s
          - ON for at most 0.5s
          - OFF for at least 0.2s
        then:
          - script.execute:
              id: ha_call_service
              service: "cover.toggle"
              entity: "cover.the_cover_to_toggle"
              key: ""
              value: ""
```

I haven't tested, but please let me know if you have issues implementing this and I probably can help a bit.

**Comment by rudgej** [comment]
I am so sorry for my slow reply. I just did this and it worked - thank you. 

I assume to customise for a light I could do

service: "cover.toggle"

service: "light.toggle"

service: "Light.off"

Etc

**Comment by rudgej** [comment]
I tried to add another one for the right button but I got a duplicate error

The code and reply is below

How do I allow a second action please?


INFO ESPHome 2023.11.6
INFO Reading configuration /config/esphome/topstairsfirst.yaml...
ERROR Error while reading config: Invalid YAML syntax:

Duplicate key "binary_sensor"
  in "/config/esphome/topstairsfirst.yaml", line 48, column 1:
    binary_sensor:
    ^
NOTE: Previous declaration here:
  in "/config/esphome/topstairsfirst.yaml", line 31, column 1:
    binary_sensor:
    ^

binary_sensor:
  - id: !extend right_button
    on_multi_click:
      #Double Click
      - timing:
          - ON for at most 0.5s
          - OFF for at most 0.3s
          - ON for at most 0.5s
          - OFF for at least 0.2s
        then:
          - script.execute:
              id: ha_call_service
              service: "cover.toggle"
              entity: "cover.landing_dimout"
              key: ""
              value: ""

binary_sensor:
  - id: !extend left_button
    on_multi_click:
      #Double Click
      - timing:
          - ON for at most 0.5s
          - OFF for at most 0.3s
          - ON for at most 0.5s
          - OFF for at least 0.2s
        then:
          - script.execute:
              id: ha_call_service
              service: "cover.toggle"
              entity: "cover.landing_blackout"
              key: ""
              value: ""

**Comment by edwardtfn** [comment]
Do you wanna have two actions executed when you double click?

**Comment by edwardtfn** [comment]
Please try this:

```yaml
binary_sensor:
  - id: !extend left_button
    on_multi_click:
      #Double Click
      - timing:
          - ON for at most 0.5s
          - OFF for at most 0.3s
          - ON for at most 0.5s
          - OFF for at least 0.2s
        then:
          - script.execute:
              id: ha_call_service
              service: "cover.toggle"
              entity: "cover.landing_dimout"
              key: ""
              value: ""
          - script.execute:
              id: ha_call_service
              service: "cover.toggle"
              entity: "cover.landing_blackout"
              key: ""
              value: ""
```

**Comment by edwardtfn** [comment]
> I assume to customise for a light I could do
> service: "cover.toggle"
> service: "light.toggle"
> service: "Light.off"
> Etc

Yes! Is should work in most of those services.

**Comment by rudgej** [comment]
Thank you - the aim was to have a function for the right hand button also - hence I assumed I could just duplicate it and change left to right. Clearly not!

**Comment by edwardtfn** [comment]
Try this:

```yaml
binary_sensor:
  - id: !extend left_button
    on_multi_click:
      #Double Click
      - timing: &hw_btn_double_click
          - ON for at most 0.5s
          - OFF for at most 0.3s
          - ON for at most 0.5s
          - OFF for at least 0.2s
        then:
          - homeassistant.service:
              service: cover.toggle
              data:
                entity_id: cover.landing_blackout

  - id: !extend right_button
    on_multi_click:
      #Double Click
      - timing: *hw_btn_double_click
        then:
          - homeassistant.service:
              service: cover.toggle
              data:
                entity_id: cover.landing_dimout
```
