### ISSUE TITLE
Frequent reboots 

### ISSUE THREAD

**Issue by Linwood-F** [Blackymas/NSPanel_HA_Blueprint#1303]
I monitor reboots by setting up a sensor with the time of last reboot based on HA time.

![reboots](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/13143855/8c3cbd7d-10ec-44bb-bd29-f5f0c24d917e)

I left the log output running in the esphome panel so I could see what is happening, and the answer appears to be "not much", though there is an HA API disconnect (but it appears to be effect not cause, as the refused connection is the panel): 

    [12:55:42][D][sensor:094]: 'ntc_source': Sending state 1.65800 V with 2 decimals of accuracy
    [12:55:42][D][resistance:039]: 'resistance_sensor' - Resistance 11309.1Ω
    [12:55:42][D][sensor:094]: 'resistance_sensor': Sending state 11309.13574 Ω with 1 decimals of accuracy
    [12:55:42][D][ntc:026]: '  Temperature' - Temperature: 22.3°C
    WARNING 192.168.130.53: Connection error occurred: [Errno 104] Connection reset by peer
    INFO Processing unexpected disconnect from ESPHome API for 192.168.130.53
    WARNING Disconnected from API
    INFO Successfully connected to 192.168.130.53 in 0.007s
    INFO Successful handshake with 192.168.130.53 in 0.036s
    [12:56:37][D][script.set_brightness:1627]: brightness: 6%
    [12:56:43][D][sensor:094]: 'ntc_source': Sending state 1.66600 V with 2 decimals of accuracy
    [12:56:43][D][resistance:039]: 'resistance_sensor' - Resistance 11419.3Ω
    [12:56:43][D][sensor:094]: 'resistance_sensor': Sending state 11419.33984 Ω with 1 decimals of accuracy
    [12:56:43][D][ntc:026]: '  Temperature' - Temperature: 22.0°C
    [12:56:43][D][sensor:094]: '  Temperature': Sending state 22.04273 °C with 1 decimals of accuracy
    [12:57:43][D][sensor:094]: 'ntc_source': Sending state 1.66800 V with 2 decimals of accuracy
    [12:57:43][D][resistance:039]: 'resistance_sensor' - Resistance 11447.1Ω
    [12:57:43][D][sensor:094]: 'resistance_sensor': Sending state 11447.05859 Ω with 1 decimals of accuracy
    [12:57:43][D][ntc:026]: '  Temperature' - Temperature: 22.0°C
    [12:57:43][D][sensor:094]: '  Temperature': Sending state 21.98925 °C with 1 decimals of accuracy
    [12:57:43][W][component:214]: Component adc.sensor took a long time for an operation (0.06 s).
    [12:57:43][W][component:215]: Components should block for at most 20-30ms.
    [12:57:45][D][sensor:094]: 'Signal': Sending state -56.28571 dBm with 0 decimals of accuracy
    [12:57:45][I][main:070]: Raw Value signal will not cause reboot: -57.000000
    [12:58:43][I][ota:117]: Boot seems successful, resetting boot loop counter.
    [12:58:43][D][esp32.preferences:114]: Saving 1 preferences to flash...
    [12:58:43][D][esp32.preferences:143]: Saving 1 preferences to flash: 0 cached, 1 written, 0 failed

I included the stuff afterwards to get the "resetting boot loop counter" which is the normal indicator after esphome reboots.  So it wasn't just a disconnect but also a reboot. 

I do have code in there which can reboot, you see evidence of it at 12:57:45, it will reboot if the signal falls below -85db, so it is not doing anything (and I've checked its history). 

It very well could be some of the modifications I have made are causing this.  I will start pulling them out and watching, but I thought I would first post and see if this matches any known issues. 

I went back through a dozen or so of these and all are around sending the temperature.  But since that's also about 80% of the log and the primary sensor updated to HA, that may just be coincidence.  I do get a lot of the adc.sensor messages about it taking a long time, but all seem in the 50-80ms range not like it is hung. 

I'm assuming if all else fails I could take it down, re-wire it to USB, and hope that log would show something, but (a) I did it finger-holding breadboard wires in place, so I can't leave it sitting a long time without some other technique, and (b) experience tells me it will then run without ever rebooting because Murphy hates me.

Any other techniques that might yield useful debugging? 

Linwood

PS. ESPHome 2023.11.0, ha 2023.11.2, supervisor 2023.11.3, os 11; USA version of the panel powered by 110v mains, relays not in use.

**Comment by edwardtfn** [comment]
Can you share your ESPHome yaml? I wanna understand better your framework, other components, etc.
Please make sure you removed any private info before sharing.

**Comment by edwardtfn** [comment]
> I do have code in there which can reboot, you see evidence of it at 12:57:45, it will reboot if the signal falls below -85db, so it is not doing anything (and I've checked its history).

ESP have some optimisations which causes the wifi to not be connected all the time. This project used to disable this until v4,0, but on v4.1 we enable this optimisation (which is default for ESP) to add support to `bluetooth_proxy`, as BT shares the same radio as Wi-Fi on ESP32 and none are really connected all the time.

**Comment by Linwood-F** [comment]
I think I am connected all the time except during the reboot.   I monitor all the devices via pings from zabbix, though i am doing it only once every 60s, maybe I need to do it faster.  

I'm happy to share the yaml, though I also realize I have butchered it a lot, so I am happy to start backing this out to see if it I can fix it by removing some item. I am really not asking you to debug my stuff, just if this is already a known issue. 

Here's the top level yaml: 

```
substitutions:
  ###### CHANGE ME START ######
  # Device name is used by the project kind of like friendly name but explicit, this prepends a space but the space is ignored 
  device_name: " " 
  # This is used now by everything (due to esphome below) but in particular my includes
  friendly_name: "Front Door Panel"
  description: "Front Door Panel"
  name: front-door-panel
  ipaddr: 192.168.130.53
#  wifi_ssid: <<< overridden by standard template below 
#  wifi_password: <<< Same 

  nextion_update_url: "http://ha.leferguson.com:8123/local/nspanel_us.tft"

esphome: 
  friendly_name: ${friendly_name}
  name: ${name}

  ##### addon-configuration #####
  ## addon_climate ##
  # addon_climate_heater_relay: "1" # possible values: 1/2

  ##### CHANGE ME END #####

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # - nspanel_esphome_advanced.yaml # activate advanced (legacy) elements - can be useful for troubleshooting
      # - nspanel_esphome_addon_climate_cool.yaml # activate for local climate (cooling) control
      # - nspanel_esphome_addon_climate_heat.yaml # activate for local climate (heater) control
    refresh: 300s

##### My customization - Start #####

  stuff: !include standard-setup-template.yaml
  more:  !include ha-time-template.yaml
 
### Remove unneeded sensors 

switch: 
  - id: !extend relay_1
    internal: true
  - id: !extend relay_2
    internal: true
  - id: !extend notification_unread
    internal: true
  - id: !extend notification_sound
    internal: true

button: 
  - id: !extend restart_nspanel
    internal: true 

number: 
  - id: !extend display_dim_brightness
    internal: true
  - id: !extend display_brightness
    internal: true
  - id: !extend timeout_dim
    internal: true
  - id: !extend timeout_sleep
    internal: true
  - id: !extend timeout_page
    internal: true
  - id: !extend temperature_correction
    internal: true

text_sensor: 
  - id: !extend detailed_entity
    internal: true
  - id: !extend notification_label
    internal: true
  - id: !extend notification_text
    internal: true
  

binary_sensor: 
#   Note: cannot remove - id: !extend nextion_init as this causes issues with blueprint
  - id: !extend api_status
    internal: true
  - id: !extend right_button
    internal: true 
  - id: !extend left_button
    internal: true 
#  - id: !extend nextion_init
#    internal: true 

uart: 
  - id: !extend tf_uart
    baud_rate: 921600 

##### My customization - End #####
```

Here are the two (slightly redacted) included templates: 

```
logger:

# Enable Home Assistant API
api:

ota:
  password: "xxxxxxxx"

#captive_portal:

web_server:
  port: 80
  include_internal: true

wifi:
  reboot_timeout: 10min
  power_save_mode: none
  manual_ip:
    static_ip: ${ipaddr}
    gateway: 192.168.130.1
    subnet: 255.255.255.0
  networks: 
  - ssid: "Reboot"
    password: "TreviliansIsNotPoindexter"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendly_name} Fallback"
    password: "xxxxxx"

sensor:
  # Reports the WiFi signal strength
  # Also will reboot if signal is too low after it checks a while (see loop counts below)
  - platform: wifi_signal
    name: Signal
    id: wifisignalid
    update_interval: 20s
    accuracy_decimals: 0
    filters:
      - sliding_window_moving_average: 
          window_size: 12
          send_every: 6
    on_value:
      then: 
        - lambda: |-
            static int loops=0; 
            static int maxLoop = 5;
            float rawdb = id(wifisignalid).raw_state; 
            if(rawdb < -80) {
              if(++loops > maxLoop) {
                ESP_LOGI("main", "Raw Value signal will cause reboot: %f", id(wifisignalid).raw_state);
                id(restartid).turn_on(); 
              } else {
                ESP_LOGI("main", "Raw Value signal would cause reboot but only on loop %d of %d: %f", loops, maxLoop, id(wifisignalid).raw_state);
              }
            } else {
              ESP_LOGI("main", "Raw Value signal will not cause reboot: %f", id(wifisignalid).raw_state);
              loops=0;
            }

          
text_sensor: 
  - platform: wifi_info
    bssid:
      update_interval: 60s
      name: BSSID

switch:
  - platform: restart
    id: restartid
    name: reboot
    restore_mode: restore_default_off

```

And the time one: 

```

time:
  - platform: homeassistant
    id: LEF_hasTime
    timezone: America/New_York

interval: 
  - interval: 60s 
    then:
      - lambda: |-
          static int reportedBoot = 0;
          if(!reportedBoot) {
            if(id(LEF_hasTime).utcnow().is_valid()) {
              reportedBoot = 1;
          //               id(LEF_rebootTime).publish_state(id(LEF_hasTime).utcnow().timestamp);
              char str[20];
              time_t currTime = id(LEF_hasTime).now().timestamp;
              strftime(str, sizeof(str), "%Y-%m-%d %H:%M:%S", localtime(&currTime));
              id(LEF_Reboot).publish_state(str);
            }
          }

text_sensor:
  - platform: template
    update_interval: never
    name: Rebooted
    id: LEF_Reboot
```
