### ISSUE TITLE
Update failed (from 3.4.1 to 4.1.1)

### ISSUE THREAD

**Issue by X-Ryl669** [Blackymas/NSPanel_HA_Blueprint#1309]
I've a panel I haven't updated for a while. I've tried to update it and it fails, but very strangely.
I'm using this configuration:
```yaml
substitutions:
  device_name: "nspanel1" 
  wifi_ssid: !secret wifi_ssid 
  wifi_password: !secret wifi_password 
  ota_password: !secret ota_password 
  api_password: !secret api_key 
  nextion_update_url: whatever

  # ## static ip config ##
  ip: "192.168.1.161"
  gw: "192.168.1.254"
  subnet: "255.255.255.0"
  dns: "192.168.1.254"
  # domain: ".local"


packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      - nspanel_esphome_advanced.yaml # activate advanced (legacy) elements - can be useful for troubleshooting
    refresh: 300s

##### My customization - Start #####
wifi:
  networks:
    - id: !extend wifi_default
      ssid: ${wifi_ssid}
      password: ${wifi_password}
      manual_ip:
        static_ip: ${ip}
        gateway: ${gw}
        subnet: ${subnet}
        dns1: ${dns}
  ap:
    ssid: "${device_name}"
    password: ${wifi_password}

ota:
  password: ${ota_password}

uart:
  - id: !extend tf_uart
    baud_rate: 115200

api:
  encryption:
    key: ${api_password}
```
It built correctly, OTA is successful, and the device boot. I had to refresh the device in automation and it worked.
Just a remark, when using the advanced config, it sets the UART bitrate to 921000 or something like this, but this doesn't work, nextion display isn't detected, so I can't update the Nextion firmware. I had to force back to 115200 for the Nextion display to be detected. 

Yet, the main issue is when I hit restart on the webserver or HA. In that case, the panel boots up as old version (3.4.1) just like it decided to use the other firmware partition and not the last one. I have to install the panel in ESPHome again to it to boot correctly.

I wonder if it due to the fact that 4.1 switch from arduino to esp-idf framework (in advanced configuration). Shouldn't the partition be erased and rewritten in that case?

Boot logs (first boot):
```
[14:19:11][D][script.check_versions:2068]: ESPHome version: 4.1.1
[14:19:11][D][script.check_versions:2069]: TFT version: 4.1.1
[14:19:11][D][script.check_versions:2071]: Blueprint version: 4.1.1
[14:19:11][D][script.check_versions:2080]: Framework: esp-idf
[14:19:11][D][script.check_versions:2081]: Baud rate: 115200
[...]
```

Boot logs (second boot):
```
[14:19:11][D][script.check_versions:2068]: ESPHome version: 3.4.1
[14:19:11][D][script.check_versions:2069]: TFT version: 4.1.1
[14:19:11][D][script.check_versions:2071]: Blueprint version: 4.1.1
[...]
```

**Comment by edwardtfn** [comment]
> It built correctly, OTA is successful, and the device boot. I had to refresh the device in automation and it worked.
Just a remark, when using the advanced config, it sets the UART bitrate to 921000 or something like this, but this doesn't work, nextion display isn't detected, so I can't update the Nextion firmware. I had to force back to 115200 for the Nextion display to be detected.

You have to upload TFT v4.1 (or the new TFT blank) first using 115200bps, then you can change baud_rate to 921600bps and all future transfers will be faster.
The first time you boot with a new baud rate it will take up to a minute for ESP establish communication to Nextion, then the following boots will be faster.

**Comment by edwardtfn** [comment]
> Yet, the main issue is when I hit restart on the webserver or HA. In that case, the panel boots up as old version (3.4.1) just like it decided to use the other firmware partition and not the last one. I have to install the panel in ESPHome again to it to boot correctly

I believe this is due to idf framework installed via ota. The advanced package includes framework esp-idf, but then that is recommended to be installed via serial for the first time, as the partitioning changes with the framework.

**Comment by X-Ryl669** [comment]
This is clearly a PITA. The panel is installed on the wall, if I have to disassemble it to update it. 

Is there a way to update the flash partition layout via OTA?

**Comment by edwardtfn** [comment]
You can use Arduino...
Either remove the advanced package or add this to your yaml:

```yaml
esp32:
  framework:
    type: arduino
```
