### ISSUE TITLE
NSpanels gets "System data error" - HELP needed

### ISSUE THREAD

**Issue by ghostridernrw40** [Blackymas/NSPanel_HA_Blueprint#1311]
Hi,

i've changed to esp-idf.
https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-Customization#framework-esp-idf

Now i installed the patchlevel 4.1.1 and my panels get "System data errors" when I update the tft.
[logs_nscorridor_logs.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/13407944/logs_nscorridor_logs.txt)

After ESP-Update
![20231120_085221](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/117640399/0f2eb0c4-3020-4eeb-b23f-1f85ad95e7e0)

During TFT (Hangs at 86%)
![20231120_085426](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/117640399/d9568d7d-2aba-4c68-b5e0-38b677fd43c0)

The End
![20231120_085513](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/117640399/43fb7f1b-8ca1-4e5f-9229-9dd12f6e9a91)

```log
WARNING nscorridor: Connection error occurred: [Errno 104] Connection reset by peer
INFO Processing unexpected disconnect from ESPHome API for nscorridor
WARNING Disconnected from API
INFO Successfully connected to nscorridor in 0.010s
INFO Successful handshake with nscorridor in 0.093s
[09:05:37][W][nextion:077]: Nextion is not connected! 
[09:05:37][W][nextion:077]: Nextion is not connected! 
[09:05:38][W][nextion:077]: Nextion is not connected! 
[09:05:39][W][nextion:077]: Nextion is not connected! 
```

This is my config.
```yaml
substitutions:

###### CHANGE ME START ######

  device_name: "nscorridor" 
  wifi_ssid: !secret nspanel_wifi_ssid
  wifi_password: !secret nspanel_wifi_password
  nextion_update_url: !secret nspanel_update_url
  #nextion_update_url: "http://192.168.178.20:8123/local/nspanel_blank.tft" # URL to local tft File
  #nextion_update_url: https://github.com/Blackymas/NSPanel_HA_Blueprint/raw/main/nspanel_eu.tft

##### CHANGE ME END #####



##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####

esp32:
  framework:
    type: esp-idf
bluetooth_proxy:
  active: true

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true
```
