### ISSUE TITLE
TFT upload funktioniert nicht 

### ISSUE THREAD

**Issue by Qidi-max** [Blackymas/NSPanel_HA_Blueprint#1326]
@
![IMG_2528](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/75774767/19b29412-e96f-4acd-8d24-1068d25272ff)
![IMG_2525](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/75774767/074472cc-71e4-4f0d-aa2d-5991d9b2a653)
![IMG_2527](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/75774767/28bd9de6-9593-45f8-8f04-3e27ff743ca6)
Der TFT uplod funkioniert nicht und in den Logs gibt es folgende Fehlermeldungen: 22:25:00 W nextion:719: Received unknown event from nextion: 0×55
22:25:00 W nextion:394: Nextion reported variable name invalid!
Könnt ihr mir hier helfen?

**Comment by edwardtfn** [comment]
This message from Nextion is due to an incompatible TFT on your screen. Uploading TFT should solve the problem.

Could you please share the logs from when you press the Upload TFT button?

**Comment by Qidi-max** [comment]
![IMG_2529](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/75774767/4d46efa2-00db-4490-8efe-bdf3a979a62c)
![IMG_2530](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/75774767/c1143aa0-254f-450a-bcca-c18925423f2a)
Hier sind die Logs wenn man Update TFT display klickt

**Comment by edwardtfn** [comment]
It looks very similar to #1324 

For some reason, the native ESPHome Nextion component is failing to setup the display, although the display is clearly getting connected.
I can work in a code to bypass this check for setup, but I will need your help with more logs, as I cannot duplicate this issue here.

Could you please add the following to your ESPHome yaml, install, boot, wait 2min, try to upload and then send all the logs?

```yaml
esp32:
  framework:
    type: esp-idf

external_components:
  - source: github://pr#5825
    components: [nextion]
    refresh: 1s

time:
  - id: !extend time_provider
    on_time:
      - seconds: /3
        then:
          - lambda: |-
              ESP_LOGD("DEBUG", "disp1->is_detected(): %s", disp1->is_detected() ? "True" : "False");
              ESP_LOGD("DEBUG", "disp1->is_setup(): %s", disp1->is_setup() ? "True" : "False");
```

**Comment by Qidi-max** [comment]
![IMG_2533](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/75774767/61921419-bd43-4911-833b-3f356e95b602)
Kannst du mir Helfen wie ich den Code korrekt eintragen kann. Ich habe dies nicht geschafft. 
Oder muss ich den an einem anderen ort eintragen?

**Comment by edwardtfn** [comment]
Please try like this:

```yaml
substitutions:
  ###### CHANGE ME START ######
  device_name: "screen" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: "http://homeassistant.local:8123/local/nspanel_us.tft"

  ##### addon-configuration #####
  ## addon_climate ##
  # addon_climate_heater_relay: "1" # possible values: 1/2

  ##### CHANGE ME END #####

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # - nspanel_esphome_addon_climate_cool.yaml # activate for local climate (cooling) control
      # - nspanel_esphome_addon_climate_heat.yaml # activate for local climate (heater) control
    refresh: 300s

##### My customization - Start #####
esp32:
  framework:
    type: esp-idf

external_components:
  - source: github://pr#5825
    components: [nextion]
    refresh: 1s

time:
  - id: !extend time_provider
    on_time:
      - seconds: /3
        then:
          - lambda: |-
              ESP_LOGD("DEBUG", "disp1->is_detected(): %s", disp1->is_detected() ? "True" : "False");
              ESP_LOGD("DEBUG", "disp1->is_setup(): %s", disp1->is_setup() ? "True" : "False");
##### My customization - End #####
```
