### ISSUE TITLE
No ESPHome: DEVICE_NAME_upload_tft service in HA

### ISSUE THREAD

**Issue by MaxR8684** [Blackymas/NSPanel_HA_Blueprint#1330]
I have nspanel-lovelace-ui" von joBr99 installed and i try to execute step 2 in your wonderful manual.
But when going to developertools > services there is no service "esphome.device_name_upload_tft" or "ESPHome: DEVICE_NAME_upload_tft".

please excuse if this is a total noob question, because i am a total noob and tri to muddle along and leran things.

**Comment by edwardtfn** [comment]
`esphome.device_name_upload_tft` is deprecated, but you can use `esphome.device_name_upload_tft_url`.

**Comment by MaxGroh8684** [comment]
Sorry for beeing vague. There is no esp service at all. 
Usually by starting to type "esp" all available services show up in the list below the input field. Or am i wrong by expecting this?

If this is the case do i have to type "esphome.**nspnlone**upload_tft_<the url where the tft file is>

**Comment by edwardtfn** [comment]
Mmmm
🤔

If you don't have the service to upload TFT from nspanel-lovelace, then just proceed to flash ESPHome with the firmware from this project here and you will find this service after the panel is detected by your Home Assistant.

**Comment by MaxR8684** [comment]
thx so far but where do i find that firmware?

**Comment by edwardtfn** [comment]
https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-First-Steps---Installation-and-Setup#code

**Comment by edwardtfn** [comment]
Have you succeeded installing everything?

**Comment by MaxR8684** [comment]
No i didnt, Sorry i messed up this issue and deleted everything.

Iwill try again later and give you the logs again.

I ran out of time for now.

**Comment by edwardtfn** [comment]
Try to add this customization to your yaml to get more detailed logs:

```yaml
substitutions:
  ###### CHANGE ME START ######
  device_name: "YOUR_PANEL_NAME" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: "http://homeassistant.local:8123/local/nspanel_us.tft"

  ##### addon-configuration #####
  ## addon_climate ##
  # addon_climate_heater_relay: "1" # possible values: 1/2

  ##### CHANGE ME END #####

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # - nspanel_esphome_addon_climate_cool.yaml # activate for local climate (cooling) control
      # - nspanel_esphome_addon_climate_heat.yaml # activate for local climate (heater) control
    refresh: 300s

##### My customization - Start #####
esp32:
  framework:
    type: esp-idf

external_components:
  - source: github://pr#5825
    components: [nextion]
    refresh: 1s

time:
  - id: !extend time_provider
    on_time:
      - seconds: /3
        then:
          - lambda: |-
              ESP_LOGD("DEBUG", "disp1->is_detected(): %s", disp1->is_detected() ? "True" : "False");
              ESP_LOGD("DEBUG", "disp1->is_setup(): %s", disp1->is_setup() ? "True" : "False");
##### My customization - End #####
```

**Comment by MaxR8684** [comment]
So i did that by trying to instal it the logs are as following
[logs_ns-panel_run.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/13536384/logs_ns-panel_run.txt)

**Comment by edwardtfn** [comment]
Please try this and send the logs again:

```yaml
substitutions:
  ###### CHANGE ME START ######
  device_name: "YOUR_PANEL_NAME" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: "http://homeassistant.local:8123/local/nspanel_us.tft"

  ##### addon-configuration #####
  ## addon_climate ##
  # addon_climate_heater_relay: "1" # possible values: 1/2

  ##### CHANGE ME END #####

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: beta
    files:
      - nspanel_esphome.yaml # Core package
      # - nspanel_esphome_addon_climate_cool.yaml # activate for local climate (cooling) control
      # - nspanel_esphome_addon_climate_heat.yaml # activate for local climate (heater) control
    refresh: 1s

##### My customization - Start #####
esp32:
  framework:
    type: esp-idf

time:
  - id: !extend time_provider
    on_time:
      - seconds: /3
        then:
          - lambda: |-
              //ESP_LOGD("DEBUG", "disp1->is_detected(): %s", disp1->is_detected() ? "True" : "False");
              ESP_LOGD("DEBUG", "disp1->is_setup(): %s", disp1->is_setup() ? "True" : "False");
##### My customization - End #####
```

**Comment by MaxR8684** [comment]
Now my config looks like this:

substitutions:

###### CHANGE ME START ######

  device_name: "nspnlone" 
  wifi_ssid: "UPC8972555"
  wifi_password: "L%r%m#182408#Family!?"

#  nextion_update_url: "http://192.168.0.23:8123/local/nspanel_eu.tft" # URL to local tft File
  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft" # URL to Github

##### CHANGE ME END #####



##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####

##### My customization - Start #####
esp32:
  framework:
    type: esp-idf

time:
  - id: !extend time_provider
    on_time:
      - seconds: /3
        then:
          - lambda: |-
              //ESP_LOGD("DEBUG", "disp1->is_detected(): %s", disp1->is_detected() ? "True" : "False");
              ESP_LOGD("DEBUG", "disp1->is_setup(): %s", disp1->is_setup() ? "True" : "False");
##### My customization - End #####

And the Loggs are the following:

INFO ESPHome 2023.11.6
INFO Reading configuration /config/esphome/ns-panel.yaml...
INFO Detected timezone 'Europe/Berlin'
INFO Generating C++ source...
INFO Compiling app...
Processing nspnlone (board: esp32dev; framework: espidf; platform: platformio/espressif32@5.4.0)
--------------------------------------------------------------------------------
Removing unused dependencies...
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - framework-espidf @ 3.40405.230623 (4.4.5) 
 - tool-cmake @ 3.16.9 
 - tool-ninja @ 1.10.2 
 - toolchain-esp32ulp @ 2.35.0-20220830 
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
Reading CMake configuration...
-- Found Git: /usr/bin/git (found version "2.39.2") 
-- The C compiler identification is GNU 8.4.0
-- The CXX compiler identification is GNU 8.4.0
-- The ASM compiler identification is GNU
-- Found assembler: /data/cache/platformio/packages/toolchain-xtensa-esp32@8.4.0+2021r2-patch5/bin/xtensa-esp32-elf-gcc
-- Check for working C compiler: /data/cache/platformio/packages/toolchain-xtensa-esp32@8.4.0+2021r2-patch5/bin/xtensa-esp32-elf-gcc
-- Check for working C compiler: /data/cache/platformio/packages/toolchain-xtensa-esp32@8.4.0+2021r2-patch5/bin/xtensa-esp32-elf-gcc -- broken
-- Configuring incomplete, errors occurred!
See also "/data/build/nspnlone/.pioenvs/nspnlone/CMakeFiles/CMakeOutput.log".
See also "/data/build/nspnlone/.pioenvs/nspnlone/CMakeFiles/CMakeError.log".

fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
CMake Error at /data/cache/platformio/packages/tool-cmake/share/cmake-3.16/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler

    "/data/cache/platformio/packages/toolchain-xtensa-esp32@8.4.0+2021r2-patch5/bin/xtensa-esp32-elf-gcc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /data/build/nspnlone/.pioenvs/nspnlone/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/data/cache/platformio/packages/tool-ninja/ninja cmTC_892b0 && [1/2] Building C object CMakeFiles/cmTC_892b0.dir/testCCompiler.c.obj
    [2/2] Linking C executable cmTC_892b0
    FAILED: cmTC_892b0 
    : && /data/cache/platformio/packages/toolchain-xtensa-esp32@8.4.0+2021r2-patch5/bin/xtensa-esp32-elf-gcc -mlongcalls -Wno-frame-address   CMakeFiles/cmTC_892b0.dir/testCCompiler.c.obj  -o cmTC_892b0   && :
    /data/cache/platformio/packages/toolchain-xtensa-esp32@8.4.0+2021r2-patch5/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /data/cache/platformio/packages/toolchain-xtensa-esp32@8.4.0+2021r2-patch5/bin/../libexec/gcc/xtensa-esp32-elf/8.4.0/liblto_plugin.so: error loading plugin: /data/cache/platformio/packages/toolchain-xtensa-esp32@8.4.0+2021r2-patch5/bin/../libexec/gcc/xtensa-esp32-elf/8.4.0/liblto_plugin.so: cannot open shared object file: No such file or directory
    collect2: error: ld returned 1 exit status
    ninja: build stopped: subcommand failed.
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  /data/cache/platformio/packages/framework-espidf/tools/cmake/project.cmake:298 (__project)
  CMakeLists.txt:3 (project)



========================== [FAILED] Took 8.86 seconds ==========================

**Comment by MaxR8684** [comment]
I am not able to install **ANY** config. Everything fails with:
[logs_ns-panel_run1.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/13536619/logs_ns-panel_run1.txt)

**Comment by edwardtfn** [comment]
Please try adding this:

```yaml
# Limit the amount of resources used for compiling
esphome:
  compile_process_limit: 1
```

**Comment by edwardtfn** [comment]
Restarting your host system, cleaning building files, stopping other add-ons, etc. also could help.
Looks like the compiler is crashing, the most common cause is lack of resources.
You can also try to use a PC to compile it.

**Comment by edwardtfn** [comment]
Please try again.

**Comment by edwardtfn** [comment]
It's something with your ESPHome compiler... Maybe you can try to reinstall it, 😉

Another thing you can try is to change the framework to arduino, as totally different files will be used, but that is not really solving the core of that problem:
```yaml
esp32:
  framework:
    type: arduino
```
