### ISSUE TITLE
Feature request: add falback input option

### ISSUE THREAD

**Issue by tikismoke** [Blackymas/NSPanel_HA_Blueprint#1349]
This is a particular case.
As in french we've got a special energy price witch is 6* the normal price on someday (~21 in winter) and lesser all other time as normal price, called Tempo (old ejp).
Is goal is to force people made some energy save when the production off energy is hard or big demand.

So as a lot of people I think I have connected bulb behind my nspanel and you had a big big support with the fallback mode that made them even work when HA is off (if bulb are configure correctly to light on on power restore).

So those bulb consume energy even if off to maintain wifi.

So I was thinking of adding an option to force the fallback mode in certain case (when price is high) to cut completely the power off bulb.

Do you know if this is possible or if I simply need to force relay off in this special case. And still in that case find a way to made physical button power on/off the relay.

Maybe I'm not clear so do not hesitate to ask more detail. In my brain it looks as simple as activate fallback mode 🤣

**Comment by edwardtfn** [comment]
I understand your point... Here in Sweden we have hourly prices, and it can change from 0.07 to 10.00kr/kwh in the same day. And now they are talking about implement 15min prices. 😳

But as I understood, you wanna use the panel's relays to cut off the power supply of your smart bulbs. This is totally possible and you don't even need the fallback mode while your panel still connected to the wifi.
If what you are looking for is a way to schedule this power off on the panel (locally), please take a look at [this](https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-Customization#scheduled-relay).

You can use a similar schedule (or just the same), to also turn off the wifi in the panel itself, then it will be in the fallback mode. You can schedule the wifi using wifi.enable and wifi.disable.
In addition to this, you can also cut off the power of the panel's display. The hardware buttons should still work, and all ij fallback mode, but nothing would be shown in the display.

In the end it would be something like this:

```yaml
# Scheduled  wifi and relay
time:
  - id: !extend time_provider
    on_time:
      - hours: 7
        minutes: 30
        seconds: 0
        then:
          - switch.turn_on: relay_1
          - switch.turn_on: screen_power
          - wifi.enable:
      - hours: 12
        minutes: 15
        seconds: 0
        then:
          - switch.turn_off: relay_1
          - switch.turn_off: screen_power
          - wifi.disable:
      - hours: 19
        minutes: 0
        seconds: 0
        then:
          - switch.turn_on: relay_1
          - switch.turn_on: screen_power
          - wifi.enable:
      - hours: 23
        minutes: 30
        seconds: 0
        then:
          - switch.turn_off: relay_1
          - switch.turn_off: screen_power
          - wifi.disable:
  ```

And remember that pressing the left button for 15s will restart your panel with wifi and screen on, so if you want to connect to it when on that low energy mode, that could be a way.
