### ISSUE TITLE
Nextion connection lost after esphome 2023.11.6 update (local files)

### ISSUE THREAD

**Issue by xagos** [Blackymas/NSPanel_HA_Blueprint#1353]
version 4.1.1. was working great until esphome 2023.11.6 was released -
the nextion panel was not reachable any more...

updating to the version 4.1.2 with local files (static ip and encryption) did not solve the problem.
My esphome config file:

```yaml
#################################
substitutions:
  device_name: "nspanel4kueche" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  ota_password: "..."
  key_base64: "..."

  nextion_update_url: "http://192.168.2.17:8123/local/nspanel_eu.tft"

  #static ip config
  ip: "192.168.2.27"
  gw: "192.168.2.1"
  subnet: "255.255.255.0"
  dns: "192.168.2.1"

packages:
  core_package: !include nspanel/nspanel_esphome_core.yaml
  advanced_package: !include nspanel/nspanel_esphome_advanced.yaml
  upload_tft_package: !include nspanel/nspanel_esphome_addon_upload_tft.yaml

##################################
```

all files in the folder nspanel/... are renewed to the latest hotfix 4.1.2

**Comment by CH-Tefi** [comment]
I have the same issue for all 5 nspanel after the new update

**Comment by drgonz0** [comment]
Addressed this morning here,  Need to update again. 

https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/1350

**Comment by edwardtfn** [comment]
@xagos, could you please capture the logs from the moment the panel boots for around 2 minutes?

**Comment by edwardtfn** [comment]
And is there a reason you want a local copy of all those files or is this just to comply with your customizations?

**Comment by edwardtfn** [comment]
@pillemats, let's create another issue for your "Updating TFT fails"? It sounds a bit different that the one reported here and would be easier if we have in another thread, please.

**Comment by pillemats** [comment]
@edwardtfn 
It works right now! I used your workaround with ref: beta

**Comment by edwardtfn** [comment]
`ref: beta` is exactly the same as `ref:  main` at this moment. 😂
But I'm happy it worked. 😉

**Comment by pillemats** [comment]
Strange :-) after I changed to beta it works…

**Comment by xagos** [comment]
@edwardtfn: there are only two reasons:
- I prefer to use a static IP and
- I have always used the encryption on my esphome controllers
Those settings can not be accessed with the standard files...

**Comment by xagos** [comment]
hello edwardtfn - attached there is a log from programming the device until "normal" operation (without working panel)

[20231128_nspanel4kueche_log_prog2run.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/13493030/20231128_nspanel4kueche_log_prog2run.txt)

Kind regards

**Comment by xagos** [comment]
I have installed five nspanel locally - I have tested this behavior on two of them and the problem is exactly the same.
Attached you can find another log from a nspanel. If there is an additional debug mode or a define to get more infos you need, please feel free to give me another job vor collecting logs ;)

[20231117_nspanel4badeg_log_prog2run.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/13493101/20231117_nspanel4badeg_log_prog2run.txt)

**Comment by xagos** [comment]
the next log shows how the system reacts, if you trigger a tft-update:
[20231128_nspanel4badeg_prog2run2updateTFT.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/13493142/20231128_nspanel4badeg_prog2run2updateTFT.txt)

**Comment by edwardtfn** [comment]
Please try this:

```yaml
#################################
substitutions:
  device_name: "nspanel4kueche" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  nextion_update_url: "http://192.168.2.17:8123/local/nspanel_eu.tft"

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Base package
      - nspanel_esphome_advanced.yaml
    refresh: 1s
##################################

##### Customizations - Start #####
# Set IP address manually
wifi:
  networks:
    - id: !extend wifi_default
      manual_ip:
        static_ip: 192.168.2.27
        gateway: 192.168.2.1
        subnet: 255.255.255.0
        dns1: 192.168.2.1

# Use my global OTA password
ota:
  password: "..."

# Encrypt the communication between ESPHome and Home Assistant
api:
  encryption:
    key: "..."
##### Customizations - End #####
```

**Comment by xagos** [comment]
thank you for your fast reply - I have modified the config file with your adjustments:
still not working. Attached you can see the log:
[20231128_nspanel4badeg_prog2run2updateTFT.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/13496703/20231128_nspanel4badeg_prog2run2updateTFT.txt)

**Comment by edwardtfn** [comment]
Could you please add this to your yaml and repeat the tests? (Logs, please)

```yaml
external_components:
  - source: github://pr#5825
    components: [nextion]
    refresh: 1s

time:
  - id: !extend time_provider
    on_time:
      - seconds: /3
        then:
          - lambda: |-
              ESP_LOGD("DEBUG", "disp1->is_detected(): %s", disp1->is_detected() ? "True" : "False");
              ESP_LOGD("DEBUG", "disp1->is_setup(): %s", disp1->is_setup() ? "True" : "False");
              ESP_LOGD("DEBUG", "ESPHome version: ${version}");
```
