### ISSUE TITLE
 Detailed thermostat settings

### ISSUE THREAD

**Issue by Foxinbox375** [Blackymas/NSPanel_HA_Blueprint#1354]
Please tell me what I need to write in the My customization field
![Снимок](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/124099364/8b89b6bb-0bae-4ea7-8ab1-9c460369044d)
To make changes to configuration files:
nspanel_esphome_addon_climate_base.yaml
and
nspanel_esphome_addon_climate_heat.yaml

The following lines are of interest:
 default_preset:
 set_point_minimum_differential:
 heat_deadband: 
 heat_overrun:

```yaml
climate:
  - id: !extend thermostat_embedded
    min_heating_off_time: ${min_off_time}s
    min_heating_run_time: ${min_run_time}s
    heat_action:
      - switch.turn_on: relay_${heater_relay}
    preset:
      - name: "Off"
        default_target_temperature_low: ${temp_min} ${temp_units}
        mode: "off"
      - name: Home
        default_target_temperature_low: 22 ${temp_units}
        mode: "heat"
      - name: away
        default_target_temperature_low: 19.5 ${temp_units}
        mode: "heat"
      - name: sleep 
        default_target_temperature_low: 21.4 ${temp_units}
        mode: "heat"
```
