### ISSUE TITLE
How to setup the climate device when using the internal relay

### ISSUE THREAD

**Issue by Rainerlan** [Blackymas/NSPanel_HA_Blueprint#136]
Where can I find additional info, wrt. "how to setup a climate entity when it shall be realized via the Nspanel relay?"
Under the blueprint-section "Climate to control", it is stated "See HowTo"  - Can anyone tell me where to find this Howto?

I have defined several MQTT climate entities already - but as it is mentioned in the blueprint, others had the same "idea" before me and can provide a nice config including (weekly) schedules, etc? (Which I was hoping to find in the HowTo)

My climate device used for NSplanel looks as follows:
```
climate:
  - platform: generic_thermostat
    name: Wohnzimmer_NsPanel_Thermostat
    heater: switch.nspanel_wz_relay_1
    target_sensor: sensor.nspanel_wz_temperature
    min_temp: 18
    max_temp: 25
    target_temp: 21
```

**Comment by Blackymas** [comment]
Yes, I have not yet written the documentary due to lack of time.

I also use the NSPanel to control my floor heating.

You only have to insert the following code. After that you can select in the Blueprint at Climate your newly created Climate


```
climate:
  - platform: generic_thermostat
    unique_id: 5af13aef-0518-4276-93d2-837a6deb0ce5
    name: Climate NSPanel Lea
    heater: switch.nspanel_lea_relay_2
    target_sensor: sensor.nspanel_lea_temperature
    min_temp: 13
    max_temp: 27
    ac_mode: false
    target_temp: 22
    cold_tolerance: 0.5
    hot_tolerance: 0.5
    min_cycle_duration:
      seconds: 60
    keep_alive:
      minutes: 3
    initial_hvac_mode: "heat"
    precision: 0.5
```

**Comment by Rainerlan** [comment]
@Blackymas, thanks for the reply - if I could support by writing some wiki page, I'll be glad to do so (Although I am not into all the functions for sure)
I got it the relay to work using a similar setup (sniplet from configuration.yaml):
```
climate:
  - platform: generic_thermostat
    name: Wohnzimmer_NsPanel_Thermostat
    heater: switch.nspanel_wz_relay_1
    target_sensor: sensor.nspanel_wz_temperature
    min_temp: 18
    max_temp: 25
    target_temp: 21
```
This is when I added the issue that min/max_temps are not used by the panel ;) (Which I understood is hard to change)
