### ISSUE TITLE
Climate panel feature request and HMI inconsistency

### ISSUE THREAD

**Issue by Rainerlan** [Blackymas/NSPanel_HA_Blueprint#137]
### Bug?
When defining a HA-climate entity to be used in NSpanel, the settings "min-temp" and "max-temp" are being disregarded when using the touch buttons "^" and "v". Instead, the temperature can be set to any value above/below the configured values in the device.
The "dial-wheel" satuarates at the defined min/max temperatures though.
But as per  [HA climate documentation](https://www.home-assistant.io/integrations/generic_thermostat/), min/max temp are meant to define the "Set minimum set point available" and "Set maximum set point available", it might be more consistent to NOT let the temperature be set above/below the configured values. even when using the touch buttons "^" and "v"

### Feature request for thermostat page:
Imho it would be nicer, if the (internal) relay would switch immediately, when the "set-temperature" is being changed - I.e. when the new set-temperature is set to a higher or lower temperature as current room temperature

**Comment by Blackymas** [comment]
Hi :)

1. Yes, we do not observe the value or the limits. In my opinion, it is not necessary, at least it is not a priority.

2. you can easily do - by creating your own Climate or by creating another automation.

The relay can be controlled by any automation in HA.

There are enough possibilities. A fixed connection of the relay we do not want, that these Relai as well as the keys are freely assignable and controllable

```
climate:
  - platform: generic_thermostat
    unique_id: 5af13aef-0518-4276-93d2-837a6deb0ce5
    name: Climate NSPanel Lea
    heater: switch.nspanel_lea_relay_2
    target_sensor: sensor.nspanel_lea_temperature
    min_temp: 13
    max_temp: 27
    ac_mode: false
    target_temp: 22
    cold_tolerance: 0.5
    hot_tolerance: 0.5
    min_cycle_duration:
      seconds: 60
    keep_alive:
      minutes: 3
    initial_hvac_mode: "heat"
    precision: 0.5
```
