### ISSUE TITLE
nspanel_us.tft Will Not Load

### ISSUE THREAD

**Issue by charbottle** [Blackymas/NSPanel_HA_Blueprint#1373]
I have tried several different ways to upload the tft file, but instead, the nspanel reboots 4 times in a row, all starting out with the Nexiton/Sonoff/E Logo screen, then waits 30 seconds and boots one last time and states "Please add devices with Bluetooth pairing in eWeLink app with a status circle above it, then the text disappears and a circle with a check mark shows up, to then change back to the Sonoff main startup page.
I have verified the nspanel_us.tft panel is in the right place locally, and it's size, about 7MB.  Even tried using the github version with no luck.
Here is snippet from the yaml file:

```
substitutions:
  ###### CHANGE ME START ######
  device_name: "nsoffice" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_pass

  nextion_update_url: "https://192.168.4.11:8123/local/nspanel_us.tft"
  #nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_us.tft"
```

I have made sure that the name from the yaml file matches that name in the blueprint "_nsoffice_"
I do notice that under Diagnostic, it shows Nexiton diplay - Disconnected.  Not sure if that means anything.
I had no errors during flash.
Any guidance would be appreciated, it's probably something simple that I am overlooking.
ESPHome Firmware: 2023.11.6
Blueprint: v4.1.2
