### ISSUE TITLE
Settings page translation to Spanish

### ISSUE THREAD

**Issue by edwardtfn** [Blackymas/NSPanel_HA_Blueprint#1376]
I think that Spanish is not available:
```yaml
    es: #Spanish
      settings:
        reboot: Reiniciar
        sleep: Modo ECO
        brightness: Iluminación
        bright: Brillo
        dimming: Atenuación #Not in use at the moment
        dim: Atenuado
```

_Originally posted by @Dragonfir3 in https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/1002#discussioncomment-7746955_
