### ISSUE TITLE
FR: Relais should give only an impulse and not stay on

### ISSUE THREAD

**Issue by NikolasRupp** [Blackymas/NSPanel_HA_Blueprint#1385]
Hi,
I don't know if this was asked already but I can't find it.

With the original firmware you can set, that when you press the hardware button the relay will only stay on for a specifiv time and then go off again. I need that for my light setting.

I know that when home assistant is online i can make a automatisation, that when it's switched on will be switched off after half a secound. But the problem is when Home assistant is not responing or offline it will stay on.

I have seen that you can hardcode them in the yaml but i dont really know how to do that.

**Comment by edwardtfn** [comment]
You can easily set this as a customization to run locally in your panel.

Try something like this:
```yaml
switch:
  - id: !extend relay_1
    on_turn_on:
      then:
        - delay: 500
        - switch.turn_off: relay_1
```
