### ISSUE TITLE
nspanel_esphome.yaml is not a valid YAML file. Please check the file contents.

### ISSUE THREAD

**Issue by tramantana** [Blackymas/NSPanel_HA_Blueprint#1408]
Hello,

I am trying to compile the files for the nspanel on my laptop with esphome installed, but it always fails with the following error:
"nspanel_esphome.yaml is not a valid YAML file. Please check the file contents."

I have tried to find the solution on the internet, but it doesn't seem like anyone had this before or I am not familiar enough with esphome to compile this myself. Is anyone able to help me please?

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/13497117/166afa3a-5706-4380-a55d-e046c229d1ec)

My nspanel code:
```
substitutions:
  ###### CHANGE ME START ######
  device_name: "YOUR_NSPANEL_NAME" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: "http://homeassistant.local:8123/local/nspanel_eu.tft"
  nextion_blank_url: "http://homeassistant.local:8123/local/nspanel_blank.tft"

  ##### addon-configuration #####
  ## addon_climate ##
  # addon_climate_heater_relay: "1" # possible values: 1/2

  ##### CHANGE ME END #####

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # - advanced/esphome/nspanel_esphome_advanced.yaml # activate advanced (legacy) elements - can be useful for troubleshooting
      # - nspanel_esphome_addon_climate_cool.yaml # activate for local climate (cooling) control
      # - nspanel_esphome_addon_climate_heat.yaml # activate for local climate (heater) control
    refresh: 1s

esp32:
  framework:
    type: esp-idf

##### My customization - Start #####
##### My customization - End #####
```
