### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by BigBobbas** [Blackymas/NSPanel_HA_Blueprint#1410]
Hi, trying to upgrade a panel to latest release and getting the following errors
[logs_hallpanel_run.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/13628574/logs_hallpanel_run.txt)

config worked fine a few weeks ago on another panel too. but when trying to upgrade that panel to latest esphome i get the same compile errors.

Config
```
substitutions:
  ###### CHANGE ME START ######
  device_name: "hallpanel" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: "http://192.168.1.8:8123/local/nspanel_eu.tft"

  ##### addon-configuration #####
  ## addon_climate ##
  # addon_climate_heater_relay: "1" # possible values: 1/2

  ##### CHANGE ME END #####

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # - nspanel_esphome_addon_climate_cool.yaml # activate for local climate (cooling) control
      # - nspanel_esphome_addon_climate_heat.yaml # activate for local climate (heater) control
    refresh: 300s

##### My customization - Start #####
esp32:
  framework:
    type: esp-idf

external_components:
  - source: github://pr#5825
    components: [nextion]
    refresh: 1s

time:
  - id: !extend time_provider
    on_time:
      - seconds: /3
        then:
          - lambda: |-
              ESP_LOGD("DEBUG", "disp1->is_detected(): %s", disp1->is_detected() ? "True" : "False");
              ESP_LOGD("DEBUG", "disp1->is_setup(): %s", disp1->is_setup() ? "True" : "False");
##### My customization - End #####
```
