### ISSUE TITLE
I can't upload nspanelus.tft

### ISSUE THREAD

**Issue by edwardtfn** [Blackymas/NSPanel_HA_Blueprint#1417]
I can't upload nspanelus.tft
```
substitutions:

###### CHANGE ME START ######

  device_name: "nspanelus" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: "http://192.168.1.38:8123/local/nspanelus.tft" # URL to local tft File
#  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_us.tft" # URL to Github

#  nextion_update_url: "http://192.168.1.38:8123/local/nspanelblank.tft" # nspanelus bak

##### CHANGE ME END #####   nspanelusbak.tft

time:
  - id: !extend time_provider
    timezone: "Europe/Moscow"

uart:
  - id: !extend tf_uart
    baud_rate: 512000

esp32:
  framework:
    type: arduino

##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      - nspanel_esphome_advanced.yaml # activate advanced (legacy) elements - can be useful for troubleshooting
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####

```
[logs_nspanelus_run (4.1.4).txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/13665774/logs_nspanelus_run.4.1.4.txt)

_Originally posted by @Anzic23 in https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/1138#issuecomment-1854710216_

**Comment by edwardtfn** [comment]
```yaml
uart:
  - id: !extend tf_uart
    baud_rate: 512000
```
This won't work with any of the TFT we expect. Both the TFT from Sonoff as all the TFTs from this projects prior to v4.1 are 115200bps only, and v4.1 is 115200bps or 921600bps only, so 512000bps is very unlikely to work.
I woukd suggest you to remove those lines.

```yaml 
esp32:
  framework:
    type: arduino
```
The default framework is Arduino, so those lines aren't making any difference. You just have to explicitly provide framework if you wanna try `esp-idf` (which is probably more reliable for uploading TFT).

```yaml
      - nspanel_esphome_advanced.yaml # activate advanced (legacy) elements - can be useful for troubleshooting
 ```
I woukd suggest you to disable advanced mode until you solve the TFT upload. That is not gonna help and will complete from the limited memory also required by the TFT upload.

Is this the first time you upload a TFT from this project (do you have Sonoff page in your display) or are you upgrading from a previous version?
