### ISSUE TITLE
Buttons not working climate entity/ Media player

### ISSUE THREAD

**Issue by Maedmax** [Blackymas/NSPanel_HA_Blueprint#1421]
HI, i have a Problem with my NSPanel on v 4.1.4

No matter what Button i put on the Homepage screen, they are not responding and won´t open up.
Only some times after several reboots i get control of them and can use them.
The activated entity Page on the home screen is working flawlessly all the time.
So it is not an hardware fault.

Also, when i set them up on like button page 1, and use for example the media integration from my sonos i can´t use the play/pause function.
Every other Function like louder, mute is working. Also the current title is correctly displayed.

when i cut them off power for several minutes and boot the panel up again it is all working fine.
Wait like 10 Minutes and the Problem comes up again, no control over the media integration, or climate entity.

Have tried multiple times to flash over a clean build, blanc tft, everything.

**Comment by Maedmax** [comment]
Okay, a little bit more information i got from the logs:

when its not working i get this from ESP:
tried buttons on the home page:
[10:19:54][D][nextion:436]: Got touch page=0 component=0 type=PRESS
[10:19:54][D][nextion:436]: Got touch page=0 component=0 type=RELEASE
[10:19:55][D][nextion:436]: Got touch page=0 component=0 type=PRESS
[10:19:55][D][nextion:436]: Got touch page=0 component=0 type=RELEASE
[10:19:56][D][nextion:436]: Got touch page=0 component=0 type=PRESS
[10:19:57][D][nextion:436]: Got touch page=0 component=0 type=RELEASE
[10:19:57][D][nextion:436]: Got touch page=0 component=0 type=PRESS
[10:19:57][D][nextion:436]: Got touch page=0 component=0 type=RELEASE
[10:19:58][D][nextion:436]: Got touch page=0 component=0 type=PRESS
[10:19:58][D][nextion:436]: Got touch page=0 component=0 type=RELEASE
[10:19:59][D][nextion:436]: Got touch page=0 component=0 type=PRESS
[10:20:00][D][nextion:436]: Got touch page=0 component=0 type=RELEASE
[10:20:00][D][nextion:436]: Got touch page=0 component=0 type=PRESS
[10:20:00][D][nextion:436]: Got touch page=0 component=0 type=RELEASE

tried the list entity
[10:20:01][D][nextion:436]: Got touch page=0 component=32 type=PRESS
[10:20:02][D][nextion:436]: Got touch page=0 component=32 type=RELEASE
[10:20:02][D][text_sensor:064]: 'nspwoz Current page': Sending state 'entitypage01'
[10:20:02][D][text_sensor:064]: 'nspwoz Detailed Entity': Sending state ''
[10:20:02][D][script.page_changed:2228]: New page: entitypage01
[10:20:02][D][script:077]: Script 'timer_dim' restarting (mode: restart)
[10:20:02][D][script:077]: Script 'timer_sleep' restarting (mode: restart)
[10:20:02][D][nextion_textsensor:014]: Processed text_sensor "currentpage" state "entitypage01"

so its not seeing any component, but they are set on the screen and in the config.

Any Idea why the component are not working ?

**Comment by edwardtfn** [comment]
On the blue boot page, which versions you see for TFT, ESPHome and Blueprint?

Do you see any error message under Home Assistant logs (Settings > System > Logs)?

**Comment by Maedmax** [comment]
All 3 are same Version, 4.1.4

No errors in Log, only when the ESPHome is not available due to voltage cutoff.

**Comment by edwardtfn** [comment]
Could you please share your ESPHome yaml? Please hide any private info (Wi-Fi settings, etc).

By the way, which version of Home Assistant and ESPHome compiler are you using?

**Comment by Maedmax** [comment]
Hello, current version of Home Assistant

Core 2023.12.3
Supervisor 2023.11.6 

ESPHome also current Version as the errors comes up since the update to 2023.11.6.
Component nextion.display took a long time for an operation (0.05 s).
Components should block for at most 20-30ms.

With the older ESPHome Version this error didn´t showed up.

ESPHOMEyaml

```
substitutions:

###### CHANGE ME START ######

  device_name: "nspwoz" 
  wifi_ssid: "********"
  wifi_password: "**********"

  nextion_update_url: "http://192.168.178.61:8123/local/nspaneleu.tft" # URL to local tft File
#  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft" # URL to Github

##### CHANGE ME END #####



##### DO NOT CHANGE ANYTHING! #####

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # - nspanel_esphome_advanced.yaml # activate advanced (legacy) elements - can be useful for troubleshooting
      # - nspanel_esphome_addon_climate_cool.yaml # activate for local climate (cooling) control
      - nspanel_esphome_addon_climate_heat.yaml # activate for local climate (heater) control
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####
```
