### ISSUE TITLE
Cannot update TFT

### ISSUE THREAD

**Issue by mtjweb** [Blackymas/NSPanel_HA_Blueprint#1430]
When I click the "Update TFT display" link the NS Panel restarts, but it is not installing the new TFT-file.

Any idea what the problem is?

My YAML-file:
```
substitutions:
  ###### CHANGE ME START ######
  device_name: nshuiskamer 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: "http://homeassistant.local:8123/local/nspanel_eu.tft"
  nextion_blank_url: "http://homeassistant.local:8123/local/nspanel_blank.tft"

  ##### addon-configuration #####
  ## addon_climate ##
  # addon_climate_heater_relay: "1" # possible values: 1/2

uart:
  - id: !extend tf_uart
    baud_rate: 9600

  ##### CHANGE ME END #####

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # - advanced/esphome/nspanel_esphome_advanced.yaml # activate advanced (legacy) elements - can be useful for troubleshooting
      # - nspanel_esphome_addon_climate_cool.yaml # activate for local climate (cooling) control
      # - nspanel_esphome_addon_climate_heat.yaml # activate for local climate (heater) control
    refresh: 1s

esp32:
  framework:
    type: esp-idf

##### My customization - Start #####
##### My customization - End #####
```

I attached the log file.
[home-assistant_esphome_2023-12-16T18-10-44.422Z.log](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/13693525/home-assistant_esphome_2023-12-16T18-10-44.422Z.log)

**Comment by edwardtfn** [comment]
```yaml
uart:
  - id: !extend tf_uart
    baud_rate: 9600
```

Please remove those lines, as this baud rate isn't supported by any of the TFT from Sonoff or from this project.
Only use that if you know the TFT in use requires 9600bps.

And could you please share the ESPHome logs? The logs you shared are from Home Assistant, but in the case of uploading TFT issues, the logs from ESPHome will be more useful.
You can follow those steps:
1. Start recording the logs (On ESPHome dashboard, you can either click "Logs" on your device's box or you can just keep the log window opened after installing the latest firmware)
1. Restart the device if you haven't just installed the new firmware (You can click on restart button under Settings > Devices and Services > ESPHome)
1. After the display is back, wait 2 minutes for the boot sequence finishes. Please capture logs all this time.
1. While you still capturing logs, press the Upload TFT button on the device's page
1. Wait about 15sec after the system restarts (regardless if the transfer was successful or not)
1. Save all the logs and share it here, please.

**Comment by mtjweb** [comment]
I deleted the lines, but then the NS Panel gets stuck on the Home Assistant logo.

Here is the log:
[logs_nshuiskamer_run.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/13693742/logs_nshuiskamer_run.txt)

**Comment by edwardtfn** [comment]
I couldn't see the event of the Upload TFT button being pressed on your log. Could you please repeat the steps above (including the steps 4 to 6) and share it again?

Some additional questions:
1. Are you installing a TFT for the first time on this panel or are you upgrading from a previous version?
2. What can you see in your panel? Could you please share a picture?

**Comment by mtjweb** [comment]
I repeated the steps, here is a new log:
[logs_nshuiskamer_run.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/13694081/logs_nshuiskamer_run.txt)

I am upgrading from the Marc Frager repo: https://github.com/marcfager/nspanel-mf

This is the logo it gets stuck on:
![cb431991-f1e8-4e61-bf09-5e3362db5555](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/16004337/2990ab0b-c4ab-4ee3-8c15-6e0e6f4fb797)

**Comment by edwardtfn** [comment]
Ok, looking at that project files I can see they also works with 115200 bps, so that should be the baud rate to use here (already the default). https://github.com/marcfager/nspanel-mf/blob/main/esphome/nspanel-mf.yaml#L122C14-L122C20

There is one thing I'd like you to try for the upload. In you yaml, please change this:
```yaml
esp32:
  framework:
    type: esp-idf
```
To this:
```esp32:
  framework:
    type: arduino
```

Then flash your panel again and repeat the same steps from before to capture the new logs.
