### ISSUE TITLE
Alarm clock

### ISSUE THREAD

**Issue by edwardtfn** [Blackymas/NSPanel_HA_Blueprint#1441]
I have 2 panels, one on each nightstand.
would like to add an alarm clock feature and a short planning of the day.

in a future house, I would have some panels in the living room an the entry.

_Originally posted by @bentouspam in https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/1206#discussioncomment-7901523_

**Comment by bentouspam** [comment]
I made a small script for testing, 
```
alias: Play rtttl
sequence:
  - service: esphome.nspanelxxxxx_play_rtttl
    data:
      song_str: >-
        aadams:d=4,o=5,b=160:8c,f,8a,f,8c,b4,2g,8f,e,8g,e,8e4,a4,2f,8c,f,8a,f,8c,b4,2g,8f,e,8c,d,8e,1f,8c,8d,8e,8f,1p,8d,8e,8f#,8g,1p,8d,8e,8f#,8g,p,8d,8e,8f#,8g,p,8c,8d,8e,8f
mode: single
icon: mdi:music
```
is missing a page "wake_call" page on the panel with one button for stopping the alarm clock and any other place touch for postponning the alarm clock 5 minutes...
maybe a "media player" call for those that don't like the RTTTL ???
