### ISSUE TITLE
Thermostat cold and hot tolerance

### ISSUE THREAD

**Issue by zdenekchobot** [Blackymas/NSPanel_HA_Blueprint#1445]
Would it be possible to add "hot_tolerance" and "cold_tolerance" parameters/substitutions to the thermostat - see [https://www.home-assistant.io/integrations/generic_thermostat/](https://www.home-assistant.io/integrations/generic_thermostat/ ) ?
Thank you for your great work

**Comment by sheaur** [comment]
\\\
climate:
    heat_deadband: 0.3
    heat_overrun: 0.0

**Comment by sheaur** [comment]
Add this on your nspanel.yaml

**Comment by edwardtfn** [comment]
No need to add `substitucions`.

It would be just this:

```yaml
climate:
  - id: !extend thermostat_embedded
    heat_deadband: 0.3 # you can change
    heat_overrun: 0.0 # you can change
```
