### ISSUE TITLE
Thermostat: using local temperature sensor only as fallback sensor

### ISSUE THREAD

**Issue by quenthal** [Blackymas/NSPanel_HA_Blueprint#1446]
I'm not sure how to make it possible, but it would be nice if one could use external temperature sensor, but still allow local thermostat that is not dependant of Home Assistant to work with internal temperature sensor.

If this was possible, one could:
- use more accurate and better placed temperature sensor for thermostat when connections and Home Assistant works as they should (which is probably over 99% of time for most the users)
- even when Home Assistant or network is down, thermostat would use internal temperature sensor, i.e. for those rare situations there would be atleast some functionality for the thermostat without need to compromise the effectivity of thermostat

**Comment by edwardtfn** [comment]
Try this as a customization:

```yaml
sensor:
  - id: ha_temperature
    platform: homeassistant
    entity_id: sensor.temperature_sensor   # Please change this by your temperature sensor in Home Assistant

  - id: combined_temperature
    platform: template
    lambda: |-
      if (wifi_component->is_connected() and api_server->is_connected()) {  // Testing both as WiFi is faster to detect issues
        return ha_temperature->state;
     else
        return temp_nspanel->state;

climate:
  - id: !extend thermostat_embedded
    sensor: combined_temperature
```
