### ISSUE TITLE
Alternate tft example broken in new 2023.12.1

### ISSUE THREAD

**Issue by haywiremk** [Blackymas/NSPanel_HA_Blueprint#1451]
Receive the following error 
<unicode string>: In lambda function:
<unicode string>:39:14: error: 'class esphome::nextion::Nextion' has no member named 'set_tft_url'; did you mean 'set_retry'?

goes away when commenting out the below blank TFT button example.

button:
  ##### UPDATE TFT BLANK DISPLAY #####
  - name: ${device_name} Update TFT display (blank)
    platform: template
    icon: mdi:file-sync
    id: tft_update_blank
    entity_category: config
    on_press:
      - logger.log: "Button pressed: Update TFT display (blank)"
      - binary_sensor.template.publish:
          id: nextion_init
          state: false
      - delay: 16ms
      - lambda: |-
          id(disp1)->set_tft_url("${nextion_update_blank_url}");
          id(disp1).upload_tft();

**Comment by edwardtfn** [comment]
I've tried that with no issues.

Could you please share your full yaml. Please remove any sensitive info.

**Comment by edwardtfn** [comment]
Hey @haywiremk, are you still facing this issue?

**Comment by haywiremk** [comment]
Yes even with the most recent ESPhome update  I tried re-typing the list with set_tft_url to make sure not cut and paste unicode.  This used to work before the update stated in the initial posting. At present I have just commented out to get a clean compile.  Here is the yaml

```
substitutions:
###### CHANGE ME START ######
  device_name: "livingbdnsp" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: "https://...:8123/local/nspanel_us.tft" # URL to local tft File
  nextion_update_blank_url: "https://...:8123/local/nspanel_blank.tft"

##### CHANGE ME END #####

##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####

button:
  ##### UPDATE TFT BLANK DISPLAY #####
  - name: ${device_name} Update TFT display (blank)
    platform: template
    icon: mdi:file-sync
    id: tft_update_blank
    entity_category: config
    on_press:
      - logger.log: "Button pressed: Update TFT display (blank)"
      - binary_sensor.template.publish:
          id: nextion_init
          state: false
      - delay: 16ms
      - lambda: |-
          id(disp1)->set_tft_url("${nextion_update_blank_url}");
          id(disp1).upload_tft();

# Set Nextion comms baud rate to 921600 bps
uart:
  - id: !extend tf_uart
    baud_rate: 921600
```

**Comment by edwardtfn** [comment]
Ok, now using your yaml I could duplicate the issue.

Please try adding this to your yaml:

```yaml
display:
  - id: !extend disp1
    tft_url: ${nextion_update_url}
```
[logs_virtual-02_run.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/13792538/logs_virtual-02_run.txt)
