### ISSUE TITLE
Feature Request - feedback acknowledgment of notification to HA

### ISSUE THREAD

**Issue by thefirstavi** [Blackymas/NSPanel_HA_Blueprint#1474]
### Discussed in https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/1473

<div type='discussions-op-text'>

<sup>Originally posted by **thefirstavi** December 24, 2023</sup>
Sorry if this is already suggested elsewhere. I also wasnt quite sure where to post this , originally under ideas, but there seemsto be feature requests raised as issues.

My example is I have a simple toggle in HA which gives me whether the Recycling has been taken out. Ideally i would notify to NSPanel that recycling needs taking out today for collection. If the notification is ticked on the Panel, then i could change the status of the toggle. in HA. Then if the notification is not acknowledged i can ramp up the alerting to voice announcements and messages to phones etc.</div>

**Comment by edwardtfn** [comment]
Look, we don't have this feature right now, but all the pieces for you create your own automatiin doing this are the. You can use a service to force a notification to be shown (triggered in your automation by the toggle entity getting `on`) and you can have another automation triggered by the button with checkmark being clicked. That sends an event to your Home Assistant and this can be used in an automation to turn off the toggle.

**Comment by thefirstavi** [comment]
Thanks. i did wonder if there was already a way. I am using the notification servoce to send notifications, but i can;t work out how to communicate back to HA . How do i trigger an automation from the notification being confirmed ?

**Comment by edwardtfn** [comment]
Most of the information from the panel (ESPHome) to the Blueprint will come with Home Assistant events of type `esphome.nspanel_ha_blueprint`, so you can always discover a "notification" by monitoring for that event under the tab "Events" under Developer Tools. Just select to listen this event and click "Start listening", then play with your panel. You will get something like this:

```yaml
event_type: esphome.nspanel_ha_blueprint
data:
  device_id: 9dcfee873c17035039322267d329c161
  component: accept
  entity: ""
  page: notification
  type: generic
  value: release
origin: LOCAL
time_fired: "2023-12-27T18:58:47.851324+00:00"
context:
  id: 01HJPA9GDBW7TS8ZTDJPRVRZP9
  parent_id: null
  user_id: null
```

´device_id` is a unique id for your panel, so this is how you know which panel sent that (if you have more than one).
In this case, page was `notification` and component was `accept` (the check button), the value of the event was `release` (the event is triggered when the button was released).

So, in your automation, you will have a trigger like this (please change `device_id` for your device, if you have more than one - you can find the id under your `automations.yaml`, it is the `device_name` of the automation using our blueprint):

```yaml
trigger:
    - platform: event
      event_type: esphome.nspanel_ha_blueprint
      event_data:
        device_id: 9dcfee873c17035039322267d329c161
        page: notification
        component: accept
        value: release
```

So every time this combination happens, your automation will be triggered.

If you have only one panel, you can remove that line with `device_id`.
