### ISSUE TITLE
Display/Nextion issue

### ISSUE THREAD

**Issue by cremer42** [Blackymas/NSPanel_HA_Blueprint#1475]
Hello and thank you in advance for the help...

I recently did an update to my NSPanel and it broke the working install I had... I decided it would be a good time to get up to date on the TFT/Yaml files, so I went ahead and flashed the NSPanel with the up to date information/files from here... All seems well, but I cannot get the TFT to update... I have a slightly irritated spouse since this NSPanel controls the lights to the baby's room, so I need to get this fixed ASAP..... hahah.

attached are logs...

Thanks again for the help.
[logs_nspanelwhite_logs (2).txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/13763887/logs_nspanelwhite_logs.2.txt)

**Comment by edwardtfn** [comment]
What do you see in your display? A picture is welcome. 😉

**Comment by cremer42** [comment]
![IMG_4358](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/128273443/d660e6bd-da6a-444b-852a-d90f87d50fa9)

**Comment by edwardtfn** [comment]
Could you please share the yaml used for your panel esphome? Please remove any sensitive information before sharing.

**Comment by cremer42** [comment]
> Could you please share the yaml used for your panel esphome? Please remove any sensitive information before sharing.

substitutions:
  ###### CHANGE ME START ######
  device_name: "nspanelwhite" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: "http://192.168.50.33:8123/local/nspanelus.tft"
  nextion_blank_url: "http://192.168.50.33:8123/local/nspanelblank.tft"

  ##### addon-configuration #####
  ## addon_climate ##
  # addon_climate_heater_relay: "1" # possible values: 1/2

  ##### CHANGE ME END #####

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # - advanced/esphome/nspanel_esphome_advanced.yaml # activate advanced (legacy) elements - can be useful for troubleshooting
      # - nspanel_esphome_addon_climate_cool.yaml # activate for local climate (cooling) control
      # - nspanel_esphome_addon_climate_heat.yaml # activate for local climate (heater) control
    refresh: 1s

esp32:
  framework:
    type: esp-idf

# Set Nextion comms baud rate to 921600 bps
uart:
  - id: !extend tf_uart
    baud_rate: 921600

##### My customization - Start #####
##### My customization - End #####

**Comment by cremer42** [comment]
> Could you please share the yaml used for your panel esphome? Please remove any sensitive information before sharing.

please see the attached. 
[nspanel_white_yaml.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/13767624/nspanel_white_yaml.txt)

**Comment by edwardtfn** [comment]
The TFT v3.3 cannot support 921600bps.

Please try this:
```yaml
substitutions:
  ###### CHANGE ME START ######
  device_name: "nspanelwhite" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: "http://192.168.50.33:8123/local/nspanelus.tft"
  nextion_blank_url: "http://192.168.50.33:8123/local/nspanelblank.tft"

  ##### addon-configuration #####
  ## addon_climate ##
  # addon_climate_heater_relay: "1" # possible values: 1/2

  ##### CHANGE ME END #####

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # - advanced/esphome/nspanel_esphome_advanced.yaml # activate advanced (legacy) elements - can be useful for troubleshooting
      # - nspanel_esphome_addon_climate_cool.yaml # activate for local climate (cooling) control
      # - nspanel_esphome_addon_climate_heat.yaml # activate for local climate (heater) control
    refresh: 300s

esp32:
  framework:
    type: esp-idf

##### My customization - Start #####
##### My customization - End #####
```
