### ISSUE TITLE
Alarm panel allways shows, even when nothing is filled in

### ISSUE THREAD

**Issue by robbiedehand** [Blackymas/NSPanel_HA_Blueprint#1489]
The alarm panel allway opens when i touch the screen.

if i fill out my alarm panel detail it becomes filled, if i leave it blank it is still there, but blank.

also termperature page is displayed as icon in the left upper corner, but i cannot "reach" the page.

```yaml
alias: nspanel01 config
description: ""
use_blueprint:
  path: Blackymas/nspanel_blueprint.yaml
  input:
    language: nl
    date_format: "%A, %d/%m"
    weather_entity: weather.buienradar
    home_value01: sensor.power_consumed
    home_value01_icon: mdi:lightning-bolt
    home_value02: sensor.gas_consumed
    home_value02_icon: mdi:gas-burner
    home_value01_icon_color:
      - 221
      - 236
      - 9
    home_value02_icon_color:
      - 231
      - 64
      - 8
    home_value03: sensor.power_production_now
    home_value03_icon: mdi:solar-power-variant
    home_value03_icon_color:
      - 10
      - 24
      - 214
    chip01_icon: ""
    chip02_icon: ""
    chip03_icon: ""
    chip04_icon: ""
    home_custom_button01: script.mv_preset_low
    home_custom_button01_icon: mdi:fan-speed-1
    home_custom_button02: script.mv_preset_medium
    home_custom_button03: script.mv_preset_high
    button_page01_label: Keuken
    entity01: scene.lampen_keuken_dimlicht_aan
    entity01_name: DIM
    entity02: scene.remotec_1_lampen_keuken_wit_aan
    entity02_name: AAN
    entity03: scene.remotec_1_lampen_keuken_uit
    entity03_name: UIT
    entity04: scene.lampen_keuken_regenboog_aan
    entity04_name: COLOR
    entity05: scene.lampen_keuken_aqua_aan
    entity05_name: AQUA
    entity06: scene.lampen_keuken_oranje_aan
    entity06_name: ORANJE
    entity06_icon: ""
    entity07: scene.remotec_1_lampen_keuken_paars_aan
    entity07_name: PAARS
    entity08: scene.lampen_keuken_warm_licht_aan
    entity08_name: WARM
    button_page02_label: Begane Grond
    entity09: light.lampen_voordeur
    entity09_name: VOORDEUR
    entity10: light.lampen_entree
    entity10_name: ENTREE
    entity10_icon: ""
    entity11: light.lampen_eethoek
    entity11_name: EETHOEK
    entity11_icon: ""
    entity12: switch.shellyplus1_7c87ce721bec_switch_0
    entity12_name: TV-MEUBEL
    entity12_icon: mdi:light-switch
    entity13_icon: ""
    entity14_icon: ""
    nspanel_name: 57a1a236d2e1f089c04cb1478652a9a6
    relay_1_local_fallback: true
    relay_2_local_fallback: true
    button_page03_label: 1e VD
    entity17: light.led_strip_kamer_jim_licht
    entity17_name: JIM LED
    entity17_icon: mdi:led-strip-variant
    entity18: input_boolean.led_loop
    entity18_name: JIM LED LOOP
    entitypages_enabled: false
    left_button_entity: switch.nspanel01_relay_1
    right_button_entity: switch.nspanel01_relay_2
    right_button_name: Woonkamer
    left_button_name: Eethoek
    entity18_icon: mdi:led-strip-variant
    entity19: light.lamp_jim_licht
    entity19_name: JIM LAMP
    entity20: light.lampen_badkamer
    entity21: script.mv_preset_high
    entity21_name: AFZUIGING HOOG
    entity21_icon: mdi:fan-speed-3
    entity22: script.mv_preset_low
    entity22_name: AFZUIGING AUTO
    entity22_icon: mdi:fan-speed-2
    button_page04_label: 2e VD
    entity25: light.leddriver_hal_2evd_licht
    entity25_name: LED TRAP ZOLDER
    entity25_icon: mdi:led-strip-variant
    entity26: light.werkkamer_tom
    entity26_name: WERKKAMER TOM
    home_custom_button02_icon: mdi:fan-speed-2
    home_custom_button03_icon: mdi:fan-speed-3
    climate_value01: sensor.thermostaat_woonkamer_temperatuur
    climate_value02: sensor.thermostaat_werkkamer_renate_temperatuur
    climate_value03: sensor.kamer_r_t_temperatuur
    climate_value04: sensor.thermostaat_jim_temperatuur
    qrcode_enabled: true
    qrcode_value: BKw3V!g6tzPYn5%ik67#QX88
    qrcode_label: WiFi Gast | GST83
    home_button05_icon_color:
      - 4
      - 113
      - 215
    left_button_hold_select: Default
    left_button_color:
      - 54
      - 2
      - 242
    right_button_color:
      - 54
      - 2
      - 242
    entitypages_value_alignment: "2"
    entities_entity01_icon: ""
    entities_entity02_icon: ""
    entities_entity03_icon: ""
    entities_entity04_icon: ""
    climate: climate.thermostaat_woonkamer
    home_button06_icon: ""
    chip_font_size: "8"
    alarm: alarm_control_panel.master
    entity20_name: BADKAMER
```
