### ISSUE TITLE
Cannot Connect to wifi

### ISSUE THREAD

**Issue by vitalikkh** [Blackymas/NSPanel_HA_Blueprint#1493]
Hi,

And Happy New Year!

For a couple days I am desperately trying to install ESP Home on the original US version of NSPanel (not Pro).
Everything looks nice and clean. Validation did not show any errors. Also project compiles clean.
Here is a Configuration File I am using:
```
substitutions:
  ###### CHANGE ME START ######
  device_name: "nspanel" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: "http://homeassistant.local:8123/local/nspanel_us.tft"
  nextion_blank_url: "http://homeassistant.local:8123/local/nspanel_blank.tft"

  ##### addon-configuration #####
  ## addon_climate ##
  # addon_climate_heater_relay: "1" # possible values: 1/2

  ##### CHANGE ME END #####

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # - advanced/esphome/nspanel_esphome_advanced.yaml # activate advanced (legacy) elements - can be useful for troubleshooting
      # - nspanel_esphome_addon_climate_cool.yaml # activate for local climate (cooling) control
      # - nspanel_esphome_addon_climate_heat.yaml # activate for local climate (heater) control
    refresh: 1s

esp32:
  framework:
    type: esp-idf

##### My customization - Start #####
##### My customization - End #####

```
Flashing went without any issues. But obviously some thing is not right.
The unexpected device "ESPHome Web 549ee4" appeared under ESP Home tab: 
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/105172911/600c79a4-3f65-4865-86e3-29af832827f2)

This one is actually on line and it is definitely physical NSPanel device.
Here is what I can see when connection to this device:
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/105172911/4a70f77d-6659-4c52-b3bd-66679b38696e)

However my device "nspanel" is unresponsive and produces next log on the reboot:

INFO ESPHome 2023.12.5
INFO Reading configuration /config/esphome/nspanel.yaml...
INFO Updating https://github.com/Blackymas/NSPanel_HA_Blueprint@main
INFO Detected timezone 'America/New_York'
INFO Starting log output from nspanel.local using esphome API
WARNING Can't connect to ESPHome API for nspanel.local: Error resolving IP address: [Errno -5] No address associated with hostname (APIConnectionError)
INFO Trying to connect to nspanel.local in the background

What I am doing wrong or what steps I am missing?

Thank you in advance,

- Vitaliy

PS.
Basically I heed very simple Scene Controller with 6 to 8 user configurable Buttons. I need to assign Icon and Description Text
to each Button individually. And of course, I am planning to control 2 built-in relays by command (not from panel physical buttons).
