### ISSUE TITLE
Update TFT button available only after fresh install

### ISSUE THREAD

**Issue by VBMek** [Blackymas/NSPanel_HA_Blueprint#1494]
Im always reworking your tft alarm pages to suit my needs better and I noticed that button to update Nextion TFT screen pages with version 4.1.4 is only available after reinstalling esphome with your yaml file. After issuing Update of TFT screen this button disappears from esphome and its no more exposed is some issue on my side ? or a bug ?

![missing_button](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/10755145/aaec9746-9b9a-4e74-94bd-fb711dae0d6b)

**Comment by edwardtfn** [comment]
This button should be always available while esphome is connected to Home Assistant. We don't have anything in our code to disable it.

**Comment by edwardtfn** [comment]
Hey @VBMek, are you still having this issue?

If so, could you please share your device's yaml? Please remove any sensitive info (Wi-Fi credentials, etc.) before sharing.

**Comment by VBMek** [comment]
Hi @edwardtfn sorry for long delay im on vacations and not checking emails so often.

Button is still not available on version 4.1.4. I also checked if any tft service is available in home assistant and it isn`t there aswell. after reinstalling esphome on nspanel it shows up and can be used but only once. Here is my yaml file

```
substitutions:
  device_name: "nspanelwejscie" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  #nextion_update_url: "http://[ip_redacted]:8123/local/nspanel.4.1.4.tft"
  nextion_update_url: "http://[ip_redacted]:8123/local/nspanel.4.1.4.vbm.tft"
  nextion_blank_url: "http://[ip_redacted]:8123/local/nspanel_blank.tft"

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # - advanced/esphome/nspanel_esphome_advanced.yaml # activate advanced (legacy) elements - can be useful for troubleshooting
      # - nspanel_esphome_addon_climate_cool.yaml # activate for local climate (cooling) control
      # - nspanel_esphome_addon_climate_heat.yaml # activate for local climate (heater) control
    refresh: 1s

esp32:
  framework:
    type: esp-idf

##### My customization - Start #####
##### My customization - End #####
```

Also i noticed on another ESP that www is no longer available on esphome devices by default i had to add it manually

```
web_server:
  port: 80
  auth:
    username: "admin"
    password: !secret wifi_password
``` 

Please notice that i didn`t updated your yaml with web server on nspanel but im wondering when and if its not available in home assistant during that time then its propably not available on nspanels esphome web page too. BTW currently have that situation where button is not available if you want to debug it we can meet on zoom or something, just let me know.

**Comment by edwardtfn** [comment]
You can aways add the Web server as a customization like this:

```yaml
substitutions:
  device_name: "nspanelwejscie" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  #nextion_update_url: "http://[ip_redacted]:8123/local/nspanel.4.1.4.tft"
  nextion_update_url: "http://[ip_redacted]:8123/local/nspanel.4.1.4.vbm.tft"
  nextion_blank_url: "http://[ip_redacted]:8123/local/nspanel_blank.tft"

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # - advanced/esphome/nspanel_esphome_advanced.yaml # activate advanced (legacy) elements - can be useful for troubleshooting
      # - nspanel_esphome_addon_climate_cool.yaml # activate for local climate (cooling) control
      # - nspanel_esphome_addon_climate_heat.yaml # activate for local climate (heater) control
    refresh: 1s

esp32:
  framework:
    type: esp-idf

##### My customization - Start #####

web_server:
  port: 80
  auth:
    username: "admin"
    password: !secret wifi_password

##### My customization - End #####
```

It shoukd work and it shoukd survive to updates. 😂
