### ISSUE TITLE
HW button indication fails when waking up

### ISSUE THREAD

**Issue by edwardtfn** [Blackymas/NSPanel_HA_Blueprint#1495]
> > @edwardtfn is there a way to delay turning on the display for 10ms after clicking? Sometimes the nspanel doesn't recognize the light is on straight away (so the bar stays white instead of light blue).
> 
> Looks like you found a bug. Which version are you running?

Version 4.1.4
I flashed the device 2 days ago and this is my first nspanel, so I've got everything to the (current) latest version.

The bug only happens when you are turning the screen on at the moment the light goes on, with this code:
```yaml
binary_sensor:
  - id: !extend left_button
    on_click:
      - lambda: |-
          if (current_page->state == "screensaver") disp1->goto_page("home");
  - id: !extend right_button
    on_click:
      - lambda: |-
          if (current_page->state == "screensaver") disp1->goto_page("home");
```

50% chance that the stripe above the button will go to lightblue, if not it takes some time until it recognizes it.

_Originally posted by @Xitro01 in https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/1281#issuecomment-1872809357_
