### ISSUE TITLE
Wifi set as accesspoint instead of client?

### ISSUE THREAD

**Issue by arkimov** [Blackymas/NSPanel_HA_Blueprint#1496]
Hello,
First of all, thanks for the work!
I've been stuck on the NSPanel flash for a couple of days now, banging my head against the walls.
**Device**: NSPanel EU
**ESPHome** : 2023.12.5

The device seems to work properly, however, I can't get it to connect to my home WiFi.
I tried the following:
- setting up the ssid and password with !secret
- setting them up hardcoded
- setting them up with "" and without
- Disable band steering
- Disable 5/6Ghz bands (only 2.4GHz
- device name with "_", "-" and only alphanumeric

And  still, the device won't connect to the wifi (Checked on the device and on my router).
**Disclaimer** : SSID and password are OK.

This morning I had the idea to check the surrounding wifi networks and there it was : a new network with the device name indicated in the yaml file.... Using the wifi password defined as wifi password.

Here is the last config used
```
substitutions:
  ###### CHANGE ME START ######
  device_name: "iot_nspanel_pav_01"    ####-> New ssid name discovered
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: "https://github.com/Blackymas/NSPanel_HA_Blueprint/raw/main/nspanel_eu.tft"
  nextion_blank_url: "https://github.com/Blackymas/NSPanel_HA_Blueprint/raw/main/nspanel_blank.tft"

  ##### addon-configuration #####
  ## addon_climate ##
  # addon_climate_heater_relay: "1" # possible values: 1/2

  ##### CHANGE ME END #####

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # - advanced/esphome/nspanel_esphome_advanced.yaml # activate advanced (legacy) elements - can be useful for troubleshooting
      #- nspanel_esphome_addon_climate_cool.yaml # activate for local climate (cooling) control
      #- nspanel_esphome_addon_climate_heat.yaml # activate for local climate (heater) control
    refresh: 1s

esp32:
  framework:
    type: esp-idf

##### My customization - Start #####
api:
  encryption:
    key: "somekey"

ota:
  password: "somepassword"
##### My customization - End #####
``` 

Thanks and as we say in Provence (south of France) at this time of the year : Bon bout d'an et à l'an qué vèn

**Comment by accompso-ltd** [comment]
Hey Arkimov, I'm no pro but I believe the device name can't have any special chars, Also check your secrets.yaml as mine had duplicated them and was causing a similar issue.

**Comment by edwardtfn** [comment]
I don't think this is related to the device name. It shoukd support both "-" or "_", although "_" is not recommended by ESPHOME, I think.
Anyhow, it looks more like something with your Wi-Fi password or network name... One thing you could try is to add those directly as a customization, without using the substitutions.
Something like this:
```yaml
wifi:
  networks:
    - id: !extend wifi_default
      ssid: !secret wifi_ssid
      password: !secret wifi_password
  ap:
    ssid: "${device_name}"
    password: !secret wifi_password
```
