### ISSUE TITLE
How to inverse relays state?

### ISSUE THREAD

**Issue by RASPIAUDIO** [Blackymas/NSPanel_HA_Blueprint#1498]
Hello and thanks for your great work!

I'm using nspanel_esphome_addon_climate_heat.yaml and I configured a generic thermostat and all is working fine.
Issue is that where I live in France Heating system is using an inversed logic to be controlled (fil pilote).

Question how could I inverse the relays state? meaning when ON the GPIO for relay is 0, and OFF GPIO is 1?

Thanks in advance for your help

**Comment by edwardtfn** [comment]
Please try adding this to your yaml as a customization:

```yaml
switch:
  - id: !extend relay_1
    pin:
      inverted: true
```

Please change to relay_2 accordingly.
