### ISSUE TITLE
How to trigger both relays with generic thermostat?

### ISSUE THREAD

**Issue by RASPIAUDIO** [Blackymas/NSPanel_HA_Blueprint#1499]
Hello and thanks for your great work again!

I'm using nspanel_esphome_addon_climate_heat.yaml and I configured a generic thermostat and all is working fine.

How could I trigger both relay 1 and 2 at the same time ? as the documentation only talk about 1 or 2 

thanks

**Comment by edwardtfn** [comment]
Could you please give more details on what you are trying to achieve with this?

**Comment by RASPIAUDIO** [comment]
Sure, I have 2 heaters one on relay1 and the other on relay2 in 2 different rooms and only one temperature sensor so until I get a second temperature sensor I would like to my generic thermostat setup for relay 1 to also control relay 2.

**Comment by edwardtfn** [comment]
You probably can have something like this:

```yaml
switch:
  - id: !extend relay_1
    on_turn_on:
      - switch.turn_on: relay_2
    on_turn_off:
      - switch.turn_off: relay_2
  
  - id: !extend relay_2
    on_turn_on:
      - switch.turn_on: relay_1
    on_turn_off:
      - switch.turn_off: relay_1
  ```

**Comment by edwardtfn** [comment]
Or, as you are using inverted pins, it will be like this:

```yaml
  - id: !extend relay_1
    pin:
      inverted: true
    on_turn_on:
      - switch.turn_on: relay_2
    on_turn_off:
      - switch.turn_off: relay_2
```
