### ISSUE TITLE
Temperature sensor accuracy issue 

### ISSUE THREAD

**Issue by RASPIAUDIO** [Blackymas/NSPanel_HA_Blueprint#1527]
Hello
I'm not sure if it is coming from your software but I see a big difference in the temperature of the sensor of the Nspanel and a thermometer just next to it, sometime more than 3 degrees. Compensation setting does not work as it is not linear even if I set it up to +3 C the next hour it is still off.

Maybe something in the ADC? Am I the only one seeing this?

Thx

**Comment by edwardtfn** [comment]
This NTC sensor can be tricky, specially due to the fact it is always powered and it can heat itself. As far as I know, there's no GPIO that can be used to power it off while not measuring.

Anyhow, as you have a reference temperature sensor close to it, you can use that to refine the NTC calibration.
First, add this to your yaml and flash your panel:
```yaml
sensor:
  - id: !extend resistance_sensor
    name: ${device_name} NTC resistence
    internal: false
```
This will expose the resistance from the NTC sensor. Try to create a table comparing the measure resistance to the measured temperature from your reference sensor. The wider the temperature range the better.
If that temperature sensor is also connected to Home Assistant, you can just keep it monitoring for a few days and then, later, plot the 2 together and look for the temperature extremes to find the correspondent resistance values.

Once you have that table, you ca set the calibration to your temperature sensor like this:
```yaml
sensor:
  - id: !extend temp_nspanel
    calibration:
      - 8.332kOhm -> 25°C
      - 10.605kOhm -> 22.5°C
      - 14.674kOhm -> 15°C
```

And in that case you probably have to move the compensation temperature control to 0, so it's not used anymore.
