### ISSUE TITLE
Climate: Get Temperature from external Sensor.

### ISSUE THREAD

**Issue by DerT94** [Blackymas/NSPanel_HA_Blueprint#1545]
Hey,

I would like to use a different entity as a temperature sensor for the thermostat.
Is this intended? Where can I adjust this?

**Comment by edwardtfn** [comment]
That's possible, but in this case you will have to rely on your Wi-Fi and Home Assistant to have it working, so you probably will find easier to configure a [Generic Thermostat](https://www.home-assistant.io/integrations/generic_thermostat/) on Home Assistant, using the panel's relays, so the control will be on HA side.

But I will look at the discussions here as I remember a recent conversation where someone else used an external sensor as the main temperature sensor, but kept the panel's sensor as a backup, so the system can work while the WiFi is out.

**Comment by edwardtfn** [comment]
There is:
- #1446

**Comment by DerT94** [comment]
Okay, Thanks.
Would like to test you solution from #1446 
But where I have to make the config?
In my HA YAML files or in the Blueprint?

Thank you

**Comment by DerT94** [comment]
Like every time
5 minutes after asking the question, I found it myself :)
I need to add it to my esphome yaml file for the nspanel.

But there is a compile error

```
INFO ESPHome 2023.12.5
INFO Reading configuration /config/esphome/nspanel-white.yaml...
INFO Updating https://github.com/DerT94/NSPanel_HA_Blueprint@main
INFO Detected timezone 'Europe/Berlin'
INFO Generating C++ source...
INFO Compiling app...
Processing nspanelwhite (board: esp32dev; framework: espidf; platform: platformio/espressif32@5.4.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - framework-espidf @ 3.40405.230623 (4.4.5) 
 - tool-cmake @ 3.16.4 
 - tool-ninja @ 1.7.1 
 - toolchain-esp32ulp @ 2.35.0-20220830 
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
Reading CMake configuration...
Dependency Graph
|-- ArduinoJson @ 6.18.5
Compiling .pioenvs/nspanelwhite/src/main.o
<unicode string>: In lambda function:
<unicode string>:50:11: error: 'wifi_component' was not declared in this scope
<unicode string>:50:11: note: suggested alternative: 'wifi_wificomponent'
<unicode string>:52:7: error: expected '}' before 'else'
<unicode string>:50:74: note: to match this '{'
<unicode string>:54:3: error: control reaches end of non-void function [-Werror=return-type]
cc1plus: some warnings being treated as errors
*** [.pioenvs/nspanelwhite/src/main.o] Error 1
========================== [FAILED] Took 8.74 seconds ==========================
```

My config file

```
substitutions:

###### CHANGE ME START ######

  device_name: "nspanelwhite" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

#  nextion_update_url: "http://HOME-ASSISTANT-IP:8123/local/nspanel_eu.tft" # URL to local tft File
  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft" # URL to Github
  nextion_blank_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_blank.tft"

  ##### addon-configuration #####
  ## addon_climate ##
  heater_relay: "1"
  temp_min: "5"
  temp_max: "30"

##### CHANGE ME END #####



##### DO NOT CHANGE ANYTHING! #####
packages:
  remote_package:
    url: https://github.com/DerT94/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # - advanced/esphome/nspanel_esphome_advanced.yaml # activate advanced (legacy) elements - can be useful for troubleshooting
      # - nspanel_esphome_addon_climate_cool.yaml # activate for local climate (cooling) control
      - nspanel_esphome_addon_climate_heat.yaml # activate for local climate (heater) control
    refresh: 1s

esp32:
  framework:
    type: esp-idf

##### DO NOT CHANGE ANYTHING! #####

##### My customization - Start #####
sensor:
  - id: ha_temperature
    platform: homeassistant
    entity_id: sensor.espresense_08e1aa_temperature   # Please change this by the entity_id of your temperature sensor in Home Assistant

  - id: combined_temperature
    platform: template
    lambda: |-
      if (wifi_component->is_connected() and api_server->is_connected()) {  // Testing both as WiFi is faster to detect issues
        return ha_temperature->state;
      else
        return temp_nspanel->state;

climate:
  - id: !extend thermostat_embedded
    sensor: combined_temperature
##### My customization - End #####
```
I had to fork the project and use my own core.yaml because my wifi is hidden.

**Comment by DerT94** [comment]
Ok, after I found the customisation documentation, I realised that it was not necessary to fork the project to add my hidden wifi config :)

I changed my yaml back to the original and added

```
##### My customization - Start #####
# Connect to a hidden Wi-Fi network.
wifi:
  networks:
    - id: !extend wifi_default
      hidden: true
  fast_connect: true

sensor:
- id: ha_temperature
  platform: homeassistant
  entity_id: sensor.espresense_08e1aa_temperature   # Please change this by the entity_id of your temperature sensor in Home Assistant

- id: combined_temperature
  platform: template
  lambda: |-
    if (wifi_component->is_connected() and api_server->is_connected()) {  // Testing both as WiFi is faster to detect issues
      return ha_temperature->state;
    else
      return temp_nspanel->state;

climate:
- id: !extend thermostat_embedded
  sensor: combined_temperature
##### My customization - End #####
```

But the error is the same

```
<unicode string>: In lambda function:
<unicode string>:57:11: error: 'wifi_component' was not declared in this scope
<unicode string>:57:11: note: suggested alternative: 'wifi_wificomponent'
<unicode string>:59:7: error: expected '}' before 'else'
<unicode string>:57:74: note: to match this '{'
<unicode string>:61:3: error: control reaches end of non-void function [-Werror=return-type]
cc1plus: some warnings being treated as errors
*** [.pioenvs/nspanelwhite/src/main.o] Error 1
```

**Comment by edwardtfn** [comment]
Please try this:

```yaml
##### My customization - Start #####
# Connect to a hidden Wi-Fi network.
wifi:
  id: wifi_component
  networks:
    - id: !extend wifi_default
      hidden: true
  fast_connect: true

sensor:
- id: ha_temperature
  platform: homeassistant
  entity_id: sensor.espresense_08e1aa_temperature   # Please change this by the entity_id of your temperature sensor in Home Assistant

- id: combined_temperature
  platform: template
  lambda: |-
    if (wifi_component->is_connected() and api_server->is_connected()) {  // Testing both as WiFi is faster to detect issues
      return ha_temperature->state;
    else
      return temp_nspanel->state;

climate:
- id: !extend thermostat_embedded
  sensor: combined_temperature
##### My customization - End #####
```

**Comment by DerT94** [comment]
Error
```
<unicode string>: In lambda function:
<unicode string>:60:7: error: expected '}' before 'else'
<unicode string>:58:74: note: to match this '{'
```

Added a } before else

```
##### My customization - Start #####
# Connect to a hidden Wi-Fi network.
wifi:
  id: wifi_component
  networks:
    - id: !extend wifi_default
      hidden: true
  fast_connect: true

sensor:
- id: ha_temperature
  platform: homeassistant
  entity_id: sensor.espresense_08e1aa_temperature   # Please change this by the entity_id of your temperature sensor in Home Assistant

- id: combined_temperature
  platform: template
  lambda: |-
    if (wifi_component->is_connected() and api_server->is_connected()) {  // Testing both as WiFi is faster to detect issues
      return ha_temperature->state;}
    else
      return temp_nspanel->state;
        
climate:
- id: !extend thermostat_embedded
  sensor: combined_temperature
##### My customization - End #####
```

Another Error

```
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/nspanelwhite/src/main.o:(.literal._Z5setupv+0x5e4): undefined reference to `vtable for esphome::homeassistant::HomeassistantSensor'
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/nspanelwhite/src/main.o:(.literal._Z5setupv+0x5e8): undefined reference to `vtable for esphome::homeassistant::HomeassistantSensor'
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/nspanelwhite/src/main.o:(.literal._Z5setupv+0x5f8): undefined reference to `vtable for esphome::template_::TemplateSensor'
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/nspanelwhite/src/main.o:(.literal._Z5setupv+0x5fc): undefined reference to `vtable for esphome::template_::TemplateSensor'
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/nspanelwhite/src/main.o:(.literal._Z5setupv+0x15cc): undefined reference to `esphome::template_::TemplateSensor::set_template(std::function<esphome::optional<float> ()>&&)'
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/nspanelwhite/src/main.o: in function `setup()':
/data/build/nspanelwhite/<unicode string>:1307: undefined reference to `esphome::template_::TemplateSensor::set_template(std::function<esphome::optional<float> ()>&&)'
collect2: error: ld returned 1 exit status
*** [.pioenvs/nspanelwhite/firmware.elf] Error 1
```

**Comment by edwardtfn** [comment]
Try cleaning your build files and then compiling again.

**Comment by edwardtfn** [comment]
This is compiling with no issues:

```yaml
substitutions:
  ###### Settings - You can edit these values ######
  device_name: my-new-nspanel
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: "http://homeassistant.local:8123/local/nspanel_eu.tft"

  ##### addon-configuration #####
  # heater_relay: "1" # possible values: 1/2 - Used by add-on climate

  ###### Settings - End #####

##### My customization - Start #####

# Connect to a hidden Wi-Fi network.
wifi:
  id: wifi_component
  networks:
    - id: !extend wifi_default
      hidden: true
  fast_connect: true

sensor:
- id: ha_temperature
  platform: homeassistant
  entity_id: sensor.espresense_08e1aa_temperature   # Please change this by the entity_id of your temperature sensor in Home Assistant

- id: combined_temperature
  platform: template
  lambda: |-
    if (wifi_component->is_connected() and api_server->is_connected())  // Testing both as WiFi is faster to detect issues
      return ha_temperature->state;
    else
      return temp_nspanel->state;

climate:
- id: !extend thermostat_embedded
  sensor: combined_temperature

##### My customization - End #####

###### Do not change area - Start ######
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # - advanced/esphome/nspanel_esphome_advanced.yaml # activate advanced (legacy) elements - can be useful for troubleshooting
      # - nspanel_esphome_addon_climate_cool.yaml # activate for local climate (cooling) control
      - nspanel_esphome_addon_climate_heat.yaml # activate for local climate (heater) control
      # - nspanel_esphome_addon_climate_dual.yaml # activate for local climate (dual) control
    refresh: 300s

esp32:
  framework:
    type: esp-idf
###### Do not change area - End ######
```

```logs
INFO ESPHome 2023.12.5
INFO Reading configuration /config/esphome/my-new-nspanel.yaml...
INFO Detected timezone 'Europe/Stockholm'
INFO Generating C++ source...
INFO Compiling app...
Processing my-new-nspanel (board: esp32dev; framework: espidf; platform: platformio/espressif32@5.4.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - framework-espidf @ 3.40405.230623 (4.4.5) 
 - tool-cmake @ 3.16.4 
 - tool-ninja @ 1.7.1 
 - toolchain-esp32ulp @ 2.35.0-20220830 
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
Reading CMake configuration...
Dependency Graph
|-- ArduinoJson @ 6.18.5
Compiling .pioenvs/my-new-nspanel/src/main.o
Linking .pioenvs/my-new-nspanel/firmware.elf
RAM:   [=         ]   9.9% (used 32420 bytes from 327680 bytes)
Flash: [======    ]  60.3% (used 1105777 bytes from 1835008 bytes)
Building .pioenvs/my-new-nspanel/firmware.bin
Creating esp32 image...
Successfully created esp32 image.
esp32_create_combined_bin([".pioenvs/my-new-nspanel/firmware.bin"], [".pioenvs/my-new-nspanel/firmware.elf"])
Wrote 0x11f5e0 bytes to file /data/build/my-new-nspanel/.pioenvs/my-new-nspanel/firmware-factory.bin, ready to flash to offset 0x0
========================= [SUCCESS] Took 42.86 seconds =========================
INFO Successfully compiled program.
INFO Resolving IP address of my-new-nspanel.local
```
