### ISSUE TITLE
Time not correct 

### ISSUE THREAD

**Issue by crls00** [Blackymas/NSPanel_HA_Blueprint#1564]
My panel is always showing an incorrect Time. Current local time is 2024-01-08 18:13 (GMT -5) but the panel shows:

2024-01-08 04:14  ????

I can't think of any time zone in the world that would yield that local time at this moment (GMT -19). It's very strange... When starting the panel, the time zone value seems to be correct according to the logs:
```
[18:17:46][C][ntc:014]:   Accuracy Decimals: 1
[18:17:47][C][homeassistant.time:010]: Home Assistant Time:
[18:17:47][C][homeassistant.time:011]:   Timezone: '<-05>5'
[18:17:47][C][status:034]: Status Binary Sensor 'nspanel-2 Status'
[18:17:47][C][status:034]:   Device Class: 'connectivity'
[18:17:47][C][mdns:115]: mDNS:
```

Take a look at the log time, it is correct which indicates that the home assistant server time is correct, but the panel still shows 2024-01-08 04:19. As you will see in nspanel yaml below, I have tried to force the Time Zone ([using this](https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-Customization#enforce-time-zone)) in the customization but it does not make any difference. 

I have also tried to change the time provider to sntp ([using this](https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-Customization#sntp-time-server)), but when I do that, the compiler throws an error:
```
INFO ESPHome 2023.12.5
INFO Reading configuration /config/esphome/nspanel-2.yaml...
INFO Updating https://github.com/Blackymas/NSPanel_HA_Blueprint@main
INFO Generating C++ source...
INFO Compiling app...
Processing nspanel-2 (board: esp32dev; framework: espidf; platform: platformio/espressif32@5.4.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - framework-espidf @ 3.40405.230623 (4.4.5) 
 - tool-cmake @ 3.16.4 
 - tool-ninja @ 1.7.1 
 - toolchain-esp32ulp @ 2.35.0-20220830 
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
Reading CMake configuration...
Dependency Graph
|-- ArduinoJson @ 6.18.5
Compiling .pioenvs/nspanel-2/src/esphome/components/adc/adc_sensor.o
Compiling .pioenvs/nspanel-2/src/esphome/components/api/api_connection.o
Compiling .pioenvs/nspanel-2/src/esphome/components/api/api_frame_helper.o
Compiling .pioenvs/nspanel-2/src/esphome/components/api/api_pb2.o
Compiling .pioenvs/nspanel-2/src/esphome/components/api/api_pb2_service.o
Compiling .pioenvs/nspanel-2/src/esphome/components/api/api_server.o
Compiling .pioenvs/nspanel-2/src/esphome/components/api/list_entities.o
Compiling .pioenvs/nspanel-2/src/esphome/components/api/proto.o
Compiling .pioenvs/nspanel-2/src/esphome/components/api/subscribe_state.o
Compiling .pioenvs/nspanel-2/src/esphome/components/api/user_services.o
Compiling .pioenvs/nspanel-2/src/esphome/components/binary_sensor/automation.o
Compiling .pioenvs/nspanel-2/src/esphome/components/binary_sensor/binary_sensor.o
Compiling .pioenvs/nspanel-2/src/esphome/components/binary_sensor/filter.o
Compiling .pioenvs/nspanel-2/src/esphome/components/button/button.o
Compiling .pioenvs/nspanel-2/src/esphome/components/display/display.o
Compiling .pioenvs/nspanel-2/src/esphome/components/display/display_buffer.o
Compiling .pioenvs/nspanel-2/src/esphome/components/display/rect.o
Compiling .pioenvs/nspanel-2/src/esphome/components/esp32/gpio.o
Compiling .pioenvs/nspanel-2/src/esphome/components/esp32/preferences.o
Compiling .pioenvs/nspanel-2/src/esphome/components/gpio/binary_sensor/gpio_binary_sensor.o
Compiling .pioenvs/nspanel-2/src/esphome/components/gpio/switch/gpio_switch.o
*** [.pioenvs/nspanel-2/src/esphome/components/homeassistant/time/homeassistant_time.o] Source `src/esphome/components/homeassistant/time/homeassistant_time.cpp' not found, needed by target `.pioenvs/nspanel-2/src/esphome/components/homeassistant/time/homeassistant_time.o'.
========================= [FAILED] Took 13.74 seconds =========================
```

I have run out of ideas. Any help will be welcome.

I'm using the latest HA versions: 

Core 2024.1.2
Supervisor 2023.12.0
Operating System 11.3
Frontend 20231208.2

ESPHome version: 2013.12.15
Blueprint Version: v4.1.4

NSPanel yaml:
```
substitutions:
  ###### CHANGE ME START ######
  device_name: "nspanel-2" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: "http://homeassistant.local:8123/local/hmi/nspanel_us.tft"
  nextion_blank_url: "http://homeassistant.local:8123/local/hmi/nspanel_blank.tft"


  ##### addon-configuration #####
  ## addon_climate ##
  # addon_climate_heater_relay: "1" # possible values: 1/2

  ##### CHANGE ME END #####

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # - advanced/esphome/nspanel_esphome_advanced.yaml # activate advanced (legacy) elements - can be useful for troubleshooting
      # - nspanel_esphome_addon_climate_cool.yaml # activate for local climate (cooling) control
      # - nspanel_esphome_addon_climate_heat.yaml # activate for local climate (heater) control
    refresh: 1s

esp32:
  framework:
    type: esp-idf

##### My customization - Start #####
time:
  - id: !extend time_provider
    timezone: "America/Lima"
##### My customization - End #####
``` 

Blueprint yaml:
```
alias: NSPanel Entrance Configuration
description: ""
use_blueprint:
  path: Blackymas/nspanel_blueprint.yaml
  input:
    nspanel_name: c4ecb0124cff4303857a4eaf0f3ab414
    date_format: "%A, %d/%m"
    delay: 50
    time_format: "%H:%M"
    weather_entity: weather.cayma
    indoortemp: sensor.nspanel_2_temperature
    home_value01: sensor.water_boiler_external_temperature_1
    home_value01_icon: mdi:thermometer-water
    home_value01_icon_color:
      - 0
      - 140
      - 180
    home_value01_label_color:
      - 0
      - 140
      - 180
    chip01: binary_sensor.kitchen_door
    chip01_icon: mdi:door
    chip01_icon_color:
      - 255
      - 251
      - 0
    chip02: switch.water_boiler_relay_0
    chip02_icon: mdi:water-boiler
    chip02_icon_color:
      - 0
      - 163
      - 215
    home_custom_button01: switch.front_gate_lock_relay_0
    home_custom_button01_icon: mdi:lock-open
    alarm: alarm_control_panel.alarm
    qrcode_enabled: true
    qrcode_label: "WiFi: CRLS_Guest"
    qrcode_value: WIFI:S:CRLS_Guest;T:WPA;P:xxxxxxxxxxxxxxxx;;
    button_page01_label: Living/Dining Room
    entity01: light.main_entrance_light_relay_0
    entity01_name: Entrance
    entity01_icon: mdi:light-recessed
    entity02: light.kitchen_light_relay_0
    entity02_name: Kitchen
    entity02_icon: mdi:ceiling-light
    entity03: light.dining_table_light_relay_0
    entity03_name: Dining Table
    entity03_icon: ""
    entity04: light.living_room_light_relay_0
    entity04_name: Living Room
    entity05: light.dining_room_window_light_relay_0
    entity05_name: Dining Window
    entity06: scene.all_kitchen_off
    entity06_name: Kitchen Off
    entity06_icon: mdi:lightbulb-off
    entity07: scene.hallway_off
    entity07_name: Hallway Off
    entity07_icon: mdi:lightbulb-off
    entity08: scene.living_lights_off
    entity08_name: Living Off
    entity08_icon: mdi:lightbulb-group-off-outline
    home_custom_button02: light.bar_area_light_relay_0
    home_custom_button02_icon: ""
    home_custom_button03: light.outside_stairs_light
```

**Comment by edwardtfn** [comment]
Please try this (that's right, I wanna try to invert the timezone signal):

```yaml
time:
  - id: !extend time_provider
    timezone: " GMT+05"
```
