### ISSUE TITLE
Heater intern Thermostat

### ISSUE THREAD

**Issue by Daniel167** [Blackymas/NSPanel_HA_Blueprint#1572]
Hello, have anyone a picture from nspanel with Thermostat Mode? I want this Option, but i see a other screen. This is my yaml. Thanks for help. 

```yaml
substitutions:
  ###### CHANGE ME START ######
  device_name: "wcnspanel" 
  wifi_ssid: „xxxx“
  wifi_password: „xxxxx“

  nextion_update_url: "http://192.168.xxx.xx:8123/local/nspanel_eu.tft"

    
  ##### addon-configuration #####
  ## addon_climate ##
  heater_relay: "1" #Use relay 1
  temp_units: "°C" #Temperatures in Fahrenheit
  temp_min: "19" #Min supported temperature is 40°F
  temp_max: "25" #Max supported temperature is 80°F
  temp_step: "0.5" #Temperature granularity is 1°F
    
  ##### CHANGE ME END #####


packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # - nspanel_esphome_addon_climate_cool.yaml # activate for local climate (cooling) control
      - nspanel_esphome_addon_climate_heat.yaml # activate for local climate (heater) control
    refresh: 300s
```
