### ISSUE TITLE
`QUESTION` ESPHome can't be initialized

### ISSUE THREAD

**Issue by jimmyhenne** [Blackymas/NSPanel_HA_Blueprint#1614]
### Question

How can I restore ESPHome?

### Additional Details

**TFT-Version 4.2
ESPHOME no result
Blueprint 4.2**

Hey there,

I'm rather new to NSPanel and this repo. I bought a NSPanel and succesfully flashed and set up v 4.1.4. Then I bought two more panels and also succesfully flashed them, but with new v 4.2. Then I updated the 'old' panel to 4.2 and it was fine at first. But since power off and power on it can't initialize ESPHome. The boot screen is stuck at ESPHome and prompts #retry 1-9.
I validated and installed the device in ESPHome in HA for 5-6 times manually but I can't manage to get it to work again.

This is my panels yaml
```

substitutions:

###### CHANGE ME START ######

  device_name: "nspanelbuero" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: "http://PANEL-IP/local/nspanel_eu.tft" # URL to local tft File
#  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft" # URL to Github

##### CHANGE ME END #####



##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 1s

esp32:
  framework:
    type: esp-idf

##### DO NOT CHANGE ANYTHING! #####
```

**Comment by andythomas** [comment]
Could you post a log from one of the panels from ESPHome? Also, could you take a photograph of the boot screen? Is it stuck at ESPHome showing retries or the Blueprint? 

> TFT-Version 4.2
> ESPHOME no result
> Blueprint 4.2

This seems odd, I assumed the info is filled in sequence.

**Comment by jimmyhenne** [comment]
all devices are displayed offline, although they work. This is a log:
```
INFO ESPHome 2023.12.5
INFO Reading configuration /config/nspanel2.yaml...
INFO Updating https://github.com/Blackymas/NSPanel_HA_Blueprint@main
INFO Updating https://github.com/esphome/esphome.git@pull/6051/head
INFO Detected timezone 'Europe/Berlin'
INFO Starting log output from nspanel2.local using esphome API
WARNING Can't connect to ESPHome API for nspanel2.local: Error resolving IP address: [Errno -2] Name or service not known (APIConnectionError)
INFO Trying to connect to nspanel2.local in the background
```

The not working panel is stuck at ESPHome showing retries:
![IMG_20240112_204720](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/34960757/29186aec-c8a7-4f54-86ad-5f7e03b9ea71)

**Comment by andythomas** [comment]
I see two things that might or might not mean anything.

1) The name of the panel (`nspanelbuero`) and the name of the yaml (`nspanel2.yaml`) are different. It looks for the panel by the name _in_ the yaml file, but not _of_ the yaml file (as far as I recall). Any chance that this got mixed up? 
2) This kind of mixup happened to me, when I switched from the build-in esphome to my desktop computer which compiles much faster. I assume, you are also using a different computer for HA and the esphome compile, since the path of the configuration is `/config/nspanel2.yaml` and not ` /config/esphome/panel2.yaml`

`INFO Reading configuration /config/nspanel2.yaml...`

**Comment by jimmyhenne** [comment]
1. sorry, the log is from one of the running panels. But the log from the broken one is equal except the name. So panelname and matches yaml file name 
`INFO ESPHome 2023.12.5
INFO Reading configuration /config/nspanelbuero.yaml...
INFO Updating https://github.com/Blackymas/NSPanel_HA_Blueprint@main
INFO Updating https://github.com/esphome/esphome.git@pull/6051/head
INFO Detected timezone 'Europe/Berlin'
INFO Starting log output from nspanelbuero.local using esphome API
WARNING Can't connect to ESPHome API for nspanelbuero.local: Error resolving IP address: [Errno -2] Name or service not known (APIConnectionError)
INFO Trying to connect to nspanelbuero.local in the background`

2. You are right. HA runs on a small NUC and I use my desktop. That way worked for 2 of 3 panels

**Comment by flodaho** [comment]
Same issue hier. Since the update to 4.2 my panel stucks at the same screen. Before everything worked allright. I'll check on your obove ideas and see if i can fix it.

**Comment by edwardtfn** [comment]
Try a power cycle or pressing the reset pin behind your device:

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/bc90d69a-ea09-4f04-9cec-387f6e3556cb)

**Comment by flodaho** [comment]
Thanks for the idea, unfortunately both steps did not help, but i found an interresting behavior: 

1. Stuck situation: according to the boot screen of the panel, TFT version 4.2 is installed and the ESP-Home init does count up retries without success. 

3. I open ESP-Home in HA an re-install the firmware (Validate -> Install) with the following code: 
<img width="593" alt="grafik" src="https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/11586838/9c1990e3-cdbf-4842-bf6f-c78b42058955">

4. --> Panel starts up working with TFT: 4.2 / ESP_Home: 4.2.1 / Blueprint: 4.2.1

5. I start the following service:
<img width="434" alt="grafik" src="https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/11586838/0b761994-0b67-4dbe-b84d-7e9b200a7824">

6. What happens is that the panel shows a Window setting baud rate, .... then the TFT Update screen shows up to immediately change to a incompatibility info screen that says "model does not match device model". 
- The TFT file is correct. I checked couple of times, re-downloaded, ..
- I always did it that way before

7. The mentioned interessting part: after the re-boot it stucks again with the boot screen initializing the ESP-Home version without success. 

This can be reproduced sarting over again. Maybe the bout rate is changed, etc?

**Comment by flodaho** [comment]
It also happens this way, without trying to update the TFT file. 

This means:

10 Validate, Install -> works
20 re-boot -> stucks
30 goto 10 ;)

thanks for support, Florian

**Comment by andythomas** [comment]
Is it possible that the panel that get stuck was originally flashed with the esp32 framework `arduino` and was now switched to `esp-idf`? Please see [here](https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/docs/customization.md#framework-esp-idf) for more information. Then, It might need a serial flash.

**Comment by jimmyhenne** [comment]
Unfortunately pushing the reset pin didn't help me.
I don't thinkt that I initially flashed arduino as I using the same code sample with esd-idf from the beginning.
I'm also doing serial flashing with an usb ttl driver.

**Comment by edwardtfn** [comment]
I don’t think the issue is related to TFT. You have v4.2 installed and that should be fully compatible with v4.2.1.

The problem is on ESPHome side which looks to not be connected to your network or dns is not resolving its name.

Can you double check in your router if you see this device connected? If you see an up address you can try connecting using that, but I don’t think you will find it.

Are you sure the WiFi credentials used are correct? If they aren’t, you should be able to see the fallback access point (a Wi-Fi network with your panels name) that you can check with your phone.

**Comment by edwardtfn** [comment]
> Maybe the bout rate is changed, etc?

Tye screen will alternate between 115200 and 921600bps every 30s until ESPHome establishes a connection.

**Comment by blehers** [comment]
Same problem here... Is there a possibility to check whether it's flashed with `arduino` or `esp-idf`?

**Comment by edwardtfn** [comment]
> Same problem here... Is there a possibility to check whether it's flashed with arduino or esp-idf?

On ESPHome logs, once a minute the watchdog will show this info.
But I don't think this is the same problem as @jimmyhenne reported. In your case ESPHome is communicating with the display, but not with the Blueprint.
I woukd suggest you create another bug so we can focus on the issue you have.

**Comment by jimmyhenne** [comment]
> Can you double check in your router if you see this device connected? If you see an up address you can try connecting using that, but I don’t think you will find it.
> 
> Are you sure the WiFi credentials used are correct? If they aren’t, you should be able to see the fallback access point (a Wi-Fi network with your panels name) that you can check with your phone.

I checked the router and the panel and its IP appears as online and active. But I can't get access to it by entering the IP in a browser. I have noticed that the IP isn't shown in the upper left corner of the panel.
The wifi credentials are ok, I checked them. I'm using a secrets.yaml for all panels.

**Comment by edwardtfn** [comment]
> I have noticed that the IP isn't shown in the upper left corner of the panel.

This is controlled by ESPHome, so if isn't working properly, it won't show a up on the screen.

**Comment by edwardtfn** [comment]
Can you compile the firmware again and flash it to the panel? If so, please add this and then try to connect via web when your panel is on, so you will be able to see logs:

```yaml
web_server:
```

**Comment by jimmyhenne** [comment]
Of course, I will flash again. Thanks for your help.
Can you tell me where I have to add web_server: ? Just that tag without any entries?

**Comment by edwardtfn** [comment]
It can be at the end of your tank, like this:

```yaml
substitutions:

###### CHANGE ME START ######

  device_name: "nspanelbuero" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: "http://PANEL-IP/local/nspanel_eu.tft" # URL to local tft File
#  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft" # URL to Github

##### CHANGE ME END #####



##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 1s

esp32:
  framework:
    type: esp-idf

##### DO NOT CHANGE ANYTHING! #####

web_server:
```
