### ISSUE TITLE
NSPanel won't turn on

### ISSUE THREAD

**Issue by Adam5JH** [Blackymas/NSPanel_HA_Blueprint#1618]
Hi there, I am quite new to Home Assistant so apologies if this question is basic.

I have successfully flashed an NSPanel with the blueprint from blackymas…
…or at least the ESPHome web upload process completed successfully.

I then am trying to power up the NSPanel and it isn’t coming on. I have tried the mains and using Dupont pins and connecting up 5V and Ground via an FT232. Pressing and holding the NSPanel buttons for 5+ seconds doesn’t work.

Perhaps foolishly I didn’t attempt to power up the panel before I did the flash so I guess it is possible the screen parts of the board have always been faulty (even though the flash worked).

Is there anything obvious that I have missed? What should I try next?

A few pointers would be much appreciated 🙂

**Comment by plasterer41** [comment]
Check the ribbon cable connection to the board and screen and let us know

**Comment by edwardtfn** [comment]
If the problem is on the screen, you should still be able to connect to ESPHome and it should show itself as “Online” on your ESPHome dashboard.
Could you please check that?

**Comment by Adam5JH** [comment]
Hi, thanks for the help.
I have disconnected the ribbon and reconnected it and that hasn't changed anything.
When I open ESPHome within the add-on area of HA I see the panel as "online" whether it is connected to power or not.???However when I run logs when it is not connected to power I get a failure to connect. When I run it with the panel connected to a 5V bench supply I get this:

INFO ESPHome 2023.12.5
INFO Reading configuration /config/esphome/nspaneloffice.yaml...
INFO Starting log output from 192.168.86.249 using esphome API
INFO Successfully connected to nspaneloffice @ 192.168.86.249 in 0.171s
INFO Successful handshake with nspaneloffice @ 192.168.86.249 in 0.102s
[11:09:08][I][app:102]: ESPHome version 2023.12.5 compiled on Jan  6 2024, 12:15:03
[11:09:08][C][wifi:573]: WiFi:
[11:09:08][C][wifi:405]:   Local MAC: A0:B7:65:54:DB:6C
[11:09:08][C][wifi:410]:   SSID: [redacted]
[11:09:08][C][wifi:411]:   IP Address: 192.168.86.249
[11:09:08][C][wifi:413]:   BSSID: [redacted]
[11:09:08][C][wifi:414]:   Hostname: 'nspaneloffice'
[11:09:08][C][wifi:416]:   Signal strength: -80 dB ▂▄▆█
[11:09:08][C][wifi:420]:   Channel: 1
[11:09:08][C][wifi:421]:   Subnet: 255.255.255.0
[11:09:08][C][wifi:422]:   Gateway: 192.168.86.1
[11:09:08][C][wifi:423]:   DNS1: 192.168.86.1
[11:09:08][C][wifi:424]:   DNS2: 0.0.0.0
[11:09:08][C][logger:443]: Logger:
[11:09:08][C][logger:444]:   Level: DEBUG
[11:09:08][C][logger:445]:   Log Baud Rate: 115200
[11:09:08][C][logger:447]:   Hardware UART: UART0
[11:09:08][C][captive_portal:088]: Captive Portal:
[11:09:08][C][mdns:115]: mDNS:
[11:09:08][C][mdns:116]:   Hostname: nspaneloffice
[11:09:08][C][ota:097]: Over-The-Air Updates:
[11:09:08][C][ota:098]:   Address: nspaneloffice.local:3232
[11:09:08][C][ota:101]:   Using Password.
[11:09:08][C][api:139]: API Server:
[11:09:08][C][api:140]:   Address: nspaneloffice.local:6053
[11:09:08][C][api:142]:   Using noise encryption: YES

**Comment by edwardtfn** [comment]
What if you run it with your panel connected to its back plate and mains power?

And could you please share a bit more of log? You've shared just a fraction of a second, I would ask for at least one minute, starting from the time you reset the panel.

**Comment by Adam5JH** [comment]
Hi, I have now connected the panel to mains power. Getting a very much longer set of logs is proving a bit tricky as the connection appears to get lost somewhere in my network (I am preparing for these units to go into a new build where the network will be a lot more stable).

Here is a set of logs where the connection was maintained for a bit longer (15 mins):
INFO ESPHome 2023.12.5
INFO Reading configuration /config/esphome/nspaneloffice.yaml...
INFO Starting log output from 192.168.86.249 using esphome API
INFO Successfully connected to nspaneloffice @ 192.168.86.249 in 0.191s
INFO Successful handshake with nspaneloffice @ 192.168.86.249 in 0.121s
[05:46:06][I][app:102]: ESPHome version 2023.12.5 compiled on Jan  6 2024, 12:15:03
[05:46:06][C][wifi:573]: WiFi:
[05:46:06][C][wifi:405]:   Local MAC: A0:B7:65:54:DB:6C
[05:46:06][C][wifi:410]:   SSID: [redacted]
[05:46:06][C][wifi:411]:   IP Address: 192.168.86.249
[05:46:06][C][wifi:413]:   BSSID: [redacted]
[05:46:06][C][wifi:414]:   Hostname: 'nspaneloffice'
[05:46:07][C][wifi:416]:   Signal strength: -46 dB ▂▄▆█
[05:46:07][C][wifi:420]:   Channel: 6
[05:46:07][C][wifi:421]:   Subnet: 255.255.255.0
[05:46:07][C][wifi:422]:   Gateway: 192.168.86.1
[05:46:07][C][wifi:423]:   DNS1: 192.168.86.1
[05:46:07][C][wifi:424]:   DNS2: 0.0.0.0
[05:46:07][C][logger:443]: Logger:
[05:46:07][C][logger:444]:   Level: DEBUG
[05:46:07][C][logger:445]:   Log Baud Rate: 115200
[05:46:07][C][logger:447]:   Hardware UART: UART0
[05:46:07][C][captive_portal:088]: Captive Portal:
[05:46:07][C][mdns:115]: mDNS:
[05:46:07][C][mdns:116]:   Hostname: nspaneloffice
[05:46:07][C][ota:097]: Over-The-Air Updates:
[05:46:07][C][ota:098]:   Address: nspaneloffice.local:3232
[05:46:07][C][ota:101]:   Using Password.
[05:46:07][C][api:139]: API Server:
[05:46:07][C][api:140]:   Address: nspaneloffice.local:6053
[05:46:07][C][api:142]:   Using noise encryption: YES
[05:46:37][W][api.connection:104]: ESPHome Logs 2023.12.5 (192.168.86.248): Connection closed
[06:06:55][D][api:102]: Accepted 192.168.86.248
[06:06:55][D][api.connection:1121]: ESPHome Logs 2023.12.5 (192.168.86.248): Connected successfully
[06:06:55][I][app:102]: ESPHome version 2023.12.5 compiled on Jan  6 2024, 12:15:03
[06:06:55][C][wifi:573]: WiFi:
[06:06:55][C][wifi:405]:   Local MAC: A0:B7:65:54:DB:6C
[06:06:55][C][wifi:410]:   SSID: [redacted]
[06:06:55][C][wifi:411]:   IP Address: 192.168.86.249
[06:06:55][C][wifi:413]:   BSSID: [redacted]
[06:06:55][C][wifi:414]:   Hostname: 'nspaneloffice'
[06:06:55][C][wifi:416]:   Signal strength: -51 dB ▂▄▆█
[06:06:55][C][wifi:420]:   Channel: 6
[06:06:55][C][wifi:421]:   Subnet: 255.255.255.0
[06:06:55][C][wifi:422]:   Gateway: 192.168.86.1
[06:06:55][C][wifi:423]:   DNS1: 192.168.86.1
[06:06:55][C][wifi:424]:   DNS2: 0.0.0.0
[06:06:55][C][logger:443]: Logger:
[06:06:55][C][logger:444]:   Level: DEBUG
[06:06:55][C][logger:445]:   Log Baud Rate: 115200
[06:06:55][C][logger:447]:   Hardware UART: UART0
[06:06:55][C][captive_portal:088]: Captive Portal:
[06:06:55][C][mdns:115]: mDNS:
[06:06:55][C][mdns:116]:   Hostname: nspaneloffice
[06:06:55][C][ota:097]: Over-The-Air Updates:
[06:06:55][C][ota:098]:   Address: nspaneloffice.local:3232
[06:06:55][C][ota:101]:   Using Password.
[06:06:55][C][api:139]: API Server:
[06:06:55][C][api:140]:   Address: nspaneloffice.local:6053
[06:06:55][C][api:142]:   Using noise encryption: YES

**Comment by edwardtfn** [comment]
Wi-Fi signal is not bad.
But your log still shows a disconnection from 05:46:37 to 06:06:55. Was that intentional or is the panel still disconnecting like that?

**Comment by edwardtfn** [comment]
By the way, can you see anything on the panel's screen?

**Comment by Adam5JH** [comment]
Many thanks for the help with this. The disconnection I am guessing was just because I opened a new browser tab to open Home Assistant and requested the logs from ESPHome on the new browser - just to check whether the logs were still live or the network had disconnected again.

I have not seen any form of life from the screen since I have been working with it. It has been black throughout, with no backlight visible or anything.

**Comment by edwardtfn** [comment]
Are you sure you don't have a disconnected cable between your panel's board and it's display?

Please add this to your yaml and install it. This will expose a switch to turn on/off the screen power supply. Please let me know if that works.
```yaml
  # Exposes display power switch
  - id: !extend screen_power
    internal: false
```

**Comment by Adam5JH** [comment]
Thanks again. I got this message back when I attempted to install that code:

INFO ESPHome 2023.12.5
INFO Reading configuration /config/esphome/nspaneloffice.yaml...
Failed config

switch.unknown: [source <unicode string>:32]
  
  Source for extension of ID 'screen_power' was not found.
  id: !extend screen_power
  internal: False

*** In case I put it in wrong, here is the yaml:
esphome:
  name: "nspaneloffice"
  friendly_name: nspaneloffice

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "b9VNey1evaG2AQ2WAGE55kR1eccA4sPRoPctzAeBakg="

ota:
  password: "e91d66db29bacbda5b152266c1c9ed52"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Nspaneloffice Fallback Hotspot"
    password: "CPUOmyUt0nD9"

switch:
  # Exposes display power switch
  - id: !extend screen_power
    internal: false

captive_portal:

**Comment by Adam5JH** [comment]
`esphome:
  name: "nspaneloffice"
  friendly_name: nspaneloffice

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "b9VNey1evaG2AQ2WAGE55kR1eccA4sPRoPctzAeBakg="

ota:
  password: "e91d66db29bacbda5b152266c1c9ed52"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Nspaneloffice Fallback Hotspot"
    password: "CPUOmyUt0nD9"

switch:
  # Exposes display power switch
  - id: !extend screen_power
    internal: false

captive_portal:
    `

**Comment by Adam5JH** [comment]
Sorry, I'm not sure how to paste code into Github without it changing the formatting.

**Comment by edwardtfn** [comment]
No need to apologies...

Basically, after pasting the code, select it and then there's a "**Code**" icon in the top of the message editing box, which will format that part of your message.

```
esp32:
  framework:
    type: esp-idf
```

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/94725493/fe084053-9036-4b42-90ef-b1dbe2c77c56)

**Comment by edwardtfn** [comment]
>  I got this message back when I attempted to install that code:

Your yaml is lacking the reference to our project.

Please try this:

```yaml
substitutions:
  # Settings - Editable values
  device_name: "nspaneloffice" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  # Add-on configuration (if needed)
  ## Add-on climate
  # heater_relay: "1"  # Possible values: "1" or "2"

# Customization area
##### My customization - Start #####

# Encrypt the communication between ESPHome and Home Assistant
api:
  encryption:
    key: "b9VNey1evaG2AQ2WAGE55kR1eccA4sPRoPctzAeBakg="

# Add captive portal
captive_portal:

# Use a custom OTA password
ota:
  password: "e91d66db29bacbda5b152266c1c9ed52"

switch:
  # Exposes display power switch
  - id: !extend screen_power
    internal: false
##### My customization - End #####

# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # Optional advanced and add-on configurations
      # - advanced/esphome/nspanel_esphome_advanced.yaml
      # - nspanel_esphome_addon_climate_cool.yaml
      - nspanel_esphome_addon_climate_heat.yaml
      # - nspanel_esphome_addon_climate_dual.yaml
    refresh: 300s

esp32:
  framework:
    type: esp-idf
```

**Comment by edwardtfn** [comment]
>  I got this message back when I attempted to install that code:

Your yaml is lacking the reference to our project.

Please try this:

```yaml
substitutions:
  # Settings - Editable values
  device_name: "nspaneloffice"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  # Add-on configuration (if needed)
  ## Add-on climate
  # heater_relay: "1"  # Possible values: "1" or "2"

# Customization area
##### My customization - Start #####

# Encrypt the communication between ESPHome and Home Assistant
api:
  encryption:
    key: "b9VNey1evaG2AQ2WAGE55kR1eccA4sPRoPctzAeBakg="

# Add captive portal
captive_portal:

# Use a custom OTA password
ota:
  password: "e91d66db29bacbda5b152266c1c9ed52"

switch:
  # Exposes display power switch
  - id: !extend screen_power
    internal: false
##### My customization - End #####

# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # Optional advanced and add-on configurations
      # - advanced/esphome/nspanel_esphome_advanced.yaml
      # - nspanel_esphome_addon_climate_cool.yaml
      - nspanel_esphome_addon_climate_heat.yaml
      # - nspanel_esphome_addon_climate_dual.yaml
    refresh: 300s

esp32:
  framework:
    type: esp-idf
```
