### ISSUE TITLE
The device is very hot since v4.2

### ISSUE THREAD

**Issue by 0hax** [Blackymas/NSPanel_HA_Blueprint#1620]
### TFT Version

4.2

### ESPHome Version

2023.12.5

### Blueprint Version

4.2

### Panel Model

NSPanel EU Model

### What is the bug?

The device is very hot since 4.2 and temperature sensor are thus wrong.

### Steps to Reproduce

Simply flash 4.2 and check temperature sensor. It's 2 degrees more than the normal temperature.
Also you can touch the device and see it's hot.

### Your panel's YAML

```yaml
substitutions:
  wifi_ssid: ""
  wifi_password: ""
  device_name: "salon"
  nextion_update_url: "http://homeassistant.local:8123/local/nspanel_eu.tft"
  heater_relay: "1" # Select 1 for "Relay 1", 2 for "Relay 2" or "0" to a dummy switch/disabled
  temp_min: "8"
  temp_max: "22"
  min_off_time: "300"
  min_run_time: "300"
  min_idle_time: "30"
packages:
  main: !include nspanel_esphome.yaml
  addon_climate: !include nspanel_esphome_addon_climate_heat.yaml
```
