### ISSUE TITLE
`BUG` 

### ISSUE THREAD

**Issue by jimmyhenne** [Blackymas/NSPanel_HA_Blueprint#1630]
### TFT Version

4.1.4, 4.2, 4.2.1

### ESPHome Version

4.1.4, 4.2, 4.2.1

### Blueprint Version

4.1.4, 4.2, 4.2.1

### Panel Model

NSPanel EU Model

### What is the bug?

Use of 'weather.get_forecast' instead 'weather.get_forecasts'

### Steps to Reproduce

I'm running HA docker 2024.1.1 and use openweathermap, which is also set up in the blueprint for the panel. I ran v4.1.4, 4.2 and 4.2.1 and observed same behavior in all these versions. When I tap on the weather icon on the tablet die forecast opens, but at that moment HA prompts the deprecated service 'weather.get_forecast' is used instead of the new 'weather.get_forecasts'.

I found #1377 which was supposed to fix it, but my HA instance obviously still uses 'weather.get_forecast'.

### Your panel's YAML

```yaml
substitutions:

###### CHANGE ME START ######

  device_name: "nspanelbuero" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft" # URL to Github

##### CHANGE ME END #####



##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 1s

esp32:
  framework:
    type: esp-idf

##### DO NOT CHANGE ANYTHING! #####

web_server:
```

### Home Assistant logs

```logs
Logger: homeassistant.components.weather
Source: components/weather/__init__.py:1134
Integration: Wetter (documentation, issues)
First occurred: 13. Januar 2024 um 21:51:45 (18 occurrences)
Last logged: 13. Januar 2024 um 23:54:37

Detected use of service 'weather.get_forecast'. This is deprecated and will stop working in Home Assistant 2024.6. Use 'weather.get_forecasts' instead which supports multiple entities
```
