### ISSUE TITLE
`BUG` Long press hardware button

### ISSUE THREAD

**Issue by misery** [Blackymas/NSPanel_HA_Blueprint#1637]
### TFT Version

4.2.1

### ESPHome Version

4.2.1

### Blueprint Version

4.2.1

### Panel Model

NSPanel EU Model

### What is the bug?

Long press of the hardware button does not work. Short press works.

### Steps to Reproduce

1. Enable long press
![Screenshot_20240115_110514](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/50925/cff91190-35f1-41d7-93f7-e8954dbfb615)
2. Hold hardware button

v4.1.4 worked without problems.

### Your panel's YAML

```yaml
substitutions:
  device_name: "nspanelflur" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: "http://home.worp.duckdns.org/local/nspanel_eu.tft"

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml

esp32:
  framework:
    type: esp-idf

wifi:
  domain: .lan

text_sensor:
  - name: ${device_name} ESPhome Version
    platform: version
    disabled_by_default: true

  - platform: wifi_info
    ip_address:
      name: ${device_name} IP
      disabled_by_default: true
      id: ip_address

captive_portal:

web_server:
  id: web_server_std
  port: 80

time:
  - id: !extend time_provider
    timezone: "Europe/Berlin"
```
