### ISSUE TITLE
`BUG`  Power_save_mode NONE is incompatible with esp32_ble

### ISSUE THREAD

**Issue by Wizzard72** [Blackymas/NSPanel_HA_Blueprint#1652]
### TFT Version

4.1.4

### ESPHome Version

12.6

### Blueprint Version

4.2.2

### Panel Model

NSPanel EU Model

### What is the bug?

 power_save_mode NONE is incompatible with esp32_ble

### Steps to Reproduce

Updated to ESPHome 12.6.
Tried to update ESPHome firmware for NSPanel
Got the error

Tried to Clean build files. Got the same error.

### Your panel's YAML

```yaml
substitutions:
  ###### CHANGE ME START ######
  device_name: "nspanelwerkkamer" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password


  nextion_update_url: "http://192.168.x.x:8086/nspanel_eu.tft"
  #nextion_update_blank_url: "http://192.168.x.x:8086/nspanel_blank.tft"

  ##### addon-configuration #####
  ## addon_climate ##
  # addon_climate_heater_relay: "1" # possible values: 1/2

  ##### CHANGE ME END #####

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # - nspanel_esphome_advanced.yaml # activate advanced (legacy) elements - can be useful for troubleshooting
      # - nspanel_esphome_addon_climate_cool.yaml # activate for local climate (cooling) control
      # - nspanel_esphome_addon_climate_heat.yaml # activate for local climate (heater) control
    refresh: 300s

##### My customization - Start #####
# Enable Home Assistant API
api:
  encryption:
    key: "1234"
# Reboot if HA is not connected for 15 minutes
  reboot_timeout: 15min

captive_portal:

# Change framework to `esp-idf`
esp32:
  framework:
    type: esp-idf

# Enable Bluetooth proxy
bluetooth_proxy:
  active: true

button:
  ##### EXIT REPARSE TFT DISPLAY #####
  - name: ${device_name} Exit reparse
    platform: template
    icon: mdi:file-sync
    id: tft_reparse_off
    entity_category: config
    on_press:
      - logger.log: "Button pressed: Exit reparse"
      - script.execute: exit_reparse
  # Adds a button to put the panel to sleep
  - name: ${device_name} Sleep
    id: force_sleep
    platform: template
    icon: mdi:sleep
    on_press:
      then:
        - logger.log: Button Sleep pressed
        - lambda: |-
            if (id(current_page).state != "screensaver") id(disp1).goto_page("screensaver");
  
  # Adds a button to wake-up the panel (similar to the existing service)
  - name: ${device_name} Wake-up
    id: force_wake_up
    platform: template
    icon: mdi:alarm
    on_press:
      then:
        - logger.log: Button Wake-up pressed
        - lambda: |-
            if (id(current_page).state == "screensaver") id(disp1).goto_page(id(wakeup_page_name).state.c_str());
            // id(timer_page).execute(id(wakeup_page_name).state.c_str()); // enable this if you want page timeout to be reset
            id(timer_sleep).execute(id(wakeup_page_name).state.c_str(), int(id(timeout_sleep).state));
            id(timer_dim).execute(id(wakeup_page_name).state.c_str(), int(id(timeout_dim).state));

sensor:
  ##### Uptime Sensors #####
  - name: ${device_name} Uptime seconds
    id: uptime_sec
    platform: uptime
    internal: true

  - name: ${device_name} API uptime
    id: api_timestamp
    platform: template
    lambda: 'return id(time_provider).now().timestamp;'
    internal: false
    device_class: timestamp
    entity_category: diagnostic
    accuracy_decimals: 0
    update_interval: never

  - name: ${device_name} Device uptime
    id: device_timestamp
    platform: template
    lambda: 'return (id(time_provider).now().timestamp - id(uptime_sec).state);'
    internal: false
    device_class: timestamp
    entity_category: diagnostic
    accuracy_decimals: 0
    update_interval: never

  ##### WIFI Signal stregth
  - name: ${device_name} RSSI
    platform: wifi_signal
    update_interval: 60s
    on_value:
      - script.execute:
          id: refresh_wifi_icon

text_sensor:
  ##### ESPhome version used to compile the app #####
  - name: ${device_name} ESPhome Version
    platform: version
    disabled_by_default: true

  - platform: wifi_info
    ip_address:
      name: ${device_name} IP
      disabled_by_default: true
      id: ip_address
    ssid:
      name: ${device_name} SSID
      disabled_by_default: true
    bssid:
      name: ${device_name} BSSID
      disabled_by_default: true

# Custom web server credentials
web_server:
  auth:
    username: !secret web_server_username
    password: !secret web_server_password
##### My customization - End #####
```

### ESPHome logs

```logs
INFO ESPHome 2023.12.6
INFO Reading configuration /config/esphome/nspanelwerkkamer.yaml...
INFO Detected timezone 'Europe/Amsterdam'
Failed config

wifi: [source <unicode string>:51]
  id: wifi_component
  
  power_save_mode NONE is incompatible with esp32_ble. Please remove the power save mode. See also https://github.com/esphome/issues/issues/2141#issuecomment-865688582.
  power_save_mode: NONE
  networks: 
    - id: wifi_default
      ssid: <wifi>
      password: <password>
      priority: 0.0
  ap: 
    ssid: nspanelwerkkamer
    password: <Wifi>
    ap_timeout: 1min
  on_connect: 
    then: 
      - script.execute: 
          id: watchdog
  on_disconnect: 
    then: 
      - script.execute: 
          id: watchdog
  domain: .local
  reboot_timeout: 15min
  fast_connect: False
  enable_btm: False
  enable_rrm: False
  passive_scan: False
  enable_on_boot: True
  use_address: nspanelwerkkamer.local
```
