### ISSUE TITLE
`BUG` TFT Upload with esphome 4.2.2 not possible but works with 4.2.1

### ISSUE THREAD

**Issue by MichaelHeimann** [Blackymas/NSPanel_HA_Blueprint#1659]
### TFT Version

4.2.2

### ESPHome Version

4.2.2

### Blueprint Version

4.2.2

### Panel Model

NSPanel EU Model

### What is the bug?

trying to update the tft from esphome 4.2.2 

### Steps to Reproduce

1. install esphome 4.2.2
2. push "Update TFT display" in HA
3. read only failed attempts in esphome log
sidenote1: tft was stock before.
sidenote2: installing/downgrading to esphome 4.2.1 fixed the issue and the tft updated fine (tried 5 times with 4.2.2)

[tft-upload-fail_4_2_2_logs_nstoilette_logs.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/13955606/tft-upload-fail_4_2_2_logs_nstoilette_logs.txt)

### Your panel's YAML

```yaml
substitutions:

###### CHANGE ME START ######

  device_name: "nstoilette" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: "http://10.250.23.6:8123/local/nspanel_eu.tft" # URL to local tft File
#  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft" # URL to Github

  ##### addon-configuration #####
  ## addon_climate ##
  heater_relay: "1" # possible values: 1/2
  temp_units: "°C" #Temperatures in Fahrenheit
  temp_min: "16" #Min supported temperature is 40°F
  temp_max: "28" #Max supported temperature is 80°F
  temp_step: "0.5" #Temperature granularity is 1°F


##### CHANGE ME END #####

esphome:
  compile_process_limit: 2

##### DO NOT CHANGE ANYTHING! #####
api:
  encryption:
    key: "removed"

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # - nspanel_esphome_addon_climate_cool.yaml # activate for local climate (cooling) control
      - nspanel_esphome_addon_climate_heat.yaml # activate for local climate (heater) control
    refresh: 1s

esp32:
  framework:
    type: esp-idf

##### DO NOT CHANGE ANYTHING! #####
```

### ESPHome logs

```logs
esphome logs in attached tft-upload-fail_4_2_2_logs_nstoilette_logs.txt
```
