### ISSUE TITLE
`BUG` Incorrect time display when in Singapore timezone

### ISSUE THREAD

**Issue by shing6326** [Blackymas/NSPanel_HA_Blueprint#1665]
### TFT Version

4.2.2

### ESPHome Version

4.2.2

### Blueprint Version

4.2.2

### Panel Model

NSPanel EU Model

### What is the bug?

Incorrect time display when in Singapore timezone

### Steps to Reproduce

The clock is 16 hours behind with my current time in singapore.
I have 2 units, one is in Hong Kong timezone and another one in Singapore timezone.
The HK one doesn't have any issues on the time display but the SG one shows 16 hours behind the current time. I have checked the system clock from system and ESP32, both accurate.

![WhatsApp Image 2024-01-17 at 22 08 01_e6916e50](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/42719827/f88a9e33-ae62-4f48-9326-cb4b3a695395)

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/42719827/c011abaa-1c4c-4dca-ad8f-467eb28e4b6e)

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/42719827/fc5b799f-4e4f-4760-b7c0-8f56488bbfcb)

### Your panel's YAML

```yaml
substitutions:
  ###### CHANGE ME START ######
  device_name: "sg_panel" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  api_key: xxx

  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/dev/advanced/hmi/nspanel_CJK_eu.tft"
  #nextion_update_url: "http://10.186.9.187:8123/local/nspanel_eu.tft"

  ##### CHANGE ME END #####

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: dev
    files:
      - nspanel_esphome.yaml # Core package
      # - nspanel_esphome_advanced.yaml # activate advanced (legacy) elements - can be useful for troubleshooting
      # - nspanel_esphome_addon_climate_cool.yaml # activate for local climate (cooling) control
      # - nspanel_esphome_addon_climate_heat.yaml # activate for local climate (heater) control
    refresh: 0s

##### My customization - Start #####
esp32:
  framework:
    type: esp-idf

logger:
  #level: VERBOSE

api:
  encryption:
    key: ${api_key}

ota:
  password: !secret ota_password
```
