### ISSUE TITLE
`Bug` Nextion is not connected for 7 minutes

### ISSUE THREAD

**Issue by misery** [Blackymas/NSPanel_HA_Blueprint#1674]
### TFT Version

4.2.3

### ESPHome Version

4.2.3

### Blueprint Version

4.2.3

### Panel Model

NSPanel EU Model

### What is the bug?

Nextion cannot be connected

### Steps to Reproduce

1. Reboot the device
2. See boot screen
3. Boot screen shows ```ESPHome: Retry #``` and ALWAYS 921600 bps.
4. Spam log with "Nextion is not connected!"

![photo_2024-01-17_21-51-27](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/50925/a8ae2b32-2944-44b8-adfd-540942883284)

Another panel shows ```115200 bps``` and connects immediately. Why does the other panel always uses ```921600```?

Maybe related to #1667 ?

### Your panel's YAML

```yaml
substitutions:
  device_name: "nspanelflur" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: "http://home.lan/local/nspanel_eu.tft"

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml

esp32:
  framework:
    type: esp-idf

wifi:
  domain: .lan

text_sensor:
  - name: ${device_name} ESPhome Version
    platform: version
    disabled_by_default: true

  - platform: wifi_info
    ip_address:
      name: ${device_name} IP
      disabled_by_default: true
      id: ip_address

captive_portal:

web_server:
  id: web_server_std
  port: 80

time:
  - id: !extend time_provider
    timezone: "Europe/Berlin"
```

### ESPHome logs

```logs
[22:01:49][W][nextion:081]: Nextion is not connected! 
[22:01:50][D][nextion:070]: 0x1A error ignored during setup
[22:01:50][I][nextion:087]: Nextion is connected
```

6 minutes after restart until connected:
[logs_nspanelflur_logs2.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/13968746/logs_nspanelflur_logs2.txt)

7 minutes until it is connected. Also an update from 4.2.1 to 4.2.3 fails completely
[logs_nspanelflur_run.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/13968680/logs_nspanelflur_run.txt)

### Home Assistant logs

```logs
No error log in home assistant
```

**Comment by edwardtfn** [comment]
May I ask you to run a test, please?

I wanna try if power cycling the Nextion display could resolve that issue.
Please add this to your yaml:
```yaml
switch:
  # Exposes display power switch
  - id: !extend screen_power
    internal: false
```
This will expose to Home Assistant the switch to turn on/off the power supply for the Nextion display.

I'd like you to, when you get to that long delay on "Initializing...", try turning it off, wait a second or two and turn on again and please let me know if that resolves the issue or if it just resets the count.
There is just one point here... Your display will be switching between 115200bps and 921600bps. This is visible on the top right on that screen. I wanna this power cycle to be only while 115200bps is shown.

Please let me know your results.
