### ISSUE TITLE
`Bug`  Button page - Empty

### ISSUE THREAD

**Issue by floflogreco** [Blackymas/NSPanel_HA_Blueprint#1685]
### TFT Version

4.2.1

### ESPHome Version

4.2.1

### Blueprint Version

4.2.1

### Panel Model

NSPanel EU Model

### What is the bug?

I added some buttons on the button page 1 but after saving only the title page is being updated. Clicking on the button works but no icon/name is being displayed

### Steps to Reproduce

1. Add the buttons on the blueprint
2. Save

### Your panel's YAML

```yaml
substitutions:
  # Settings - Editable values
  device_name: "nspanel"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  nextion_update_url: "http://homeassistant.local:8123/local/nspanel_eu.tft"  # Optional for `esp-idf` framework
  # Add-on configuration (if needed)
  # heater_relay: "1"  # Possible values: "1" or "2"

# Customization area
##### My customization - Start #####
ota:
  password: !secret nspanel_ota_password
##### My customization - End #####

# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # Optional advanced and add-on configurations
      # - advanced/esphome/nspanel_esphome_advanced.yaml
      # - nspanel_esphome_addon_climate_cool.yaml
      # - nspanel_esphome_addon_climate_heat.yaml
      # - nspanel_esphome_addon_climate_dual.yaml
    refresh: 300s
```
