### ISSUE TITLE
Device Stuck at Initializing after ESP Home Update

### ISSUE THREAD

**Issue by scriven33** [Blackymas/NSPanel_HA_Blueprint#1691]
### Question

After an ESP Home Update, the panel doesn't get past Initializing - any way to recover?

### Additional Details

I posted this on the HA forum, but was advised to post it here.

It would appear I have broken my panel after updating the ESPHOME on it.
The panel starts and says Initializing and the version of TFT (4.1.1) but the other two fields are blank.
It isn’t connected to Wifi, but the nspanel fallback hotspot is available and I can connect to it and get an IP address, but browsing to the panel does not work.

I have done a physical reboot of the device (cutting the power) with no success.

Is it screwed?

I don’t have the capabilities to do a serial reflash, this was bought pre-flashed as I have another one which I spent weeks trying to flash without success and it was easier to just buy one ready to go, which has worked fine for months.

**Comment by illuzn** [comment]
Please post your configuration.yaml

It's probably not wise to update to the latest version without knowing how to serial reflash... see #1686 this could be related

**Comment by scriven33** [comment]
The YAML is below, I have just hashed out Wifi details, otherwise there isn't much to it.
While I would agree with your comment about caution on the latest version, I have updated this panel regularly since I put it in place over the summer and it has not been a problem. 

```
substitutions:

###### CHANGE ME START ######

  device_name: "nspanel" 
  wifi_ssid: "xxxxx"
  wifi_password: "xxxxxx"

  nextion_update_url: "http://192.168.x.x:8123/local/nspanel_eu.tft" # URL to local tft File
#  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_us.tft" # URL to Github

##### CHANGE ME END #####



##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####
```
