### ISSUE TITLE
`Enhancement` Selection of presets on climate page

### ISSUE THREAD

**Issue by NoFace3D** [Blackymas/NSPanel_HA_Blueprint#1702]
### Enhancement Summary

Selection of presets on climate page

### Detailed Description

I am missing possibility to change presets on the climate page, if they are defined like
```
climate:
  - id: !extend thermostat_embedded
    default_preset: "Home"
    preset:
      - name: "Off" # OFF, ECO, AWAY, BOOST, COMFORT, HOME, SLEEP, ACTIVITY
        default_target_temperature_low: ${temp_min} ${temp_units}
        mode: "off" # OFF, AUTO, HEAT
      - name: Home
        default_target_temperature_low: 23.0 ${temp_units}
        mode: "heat"
      - name: Away
        default_target_temperature_low: 18.0 ${temp_units}
        mode: "heat"
      - name: Eco
        default_target_temperature_low: 20.0 ${temp_units}
        mode: "heat"
      - name: Sleep
        default_target_temperature_low: 21.0 ${temp_units}
        mode: "heat"
```

### Additional Context

Currently it's possible to control only modes (in case of heater: heat, off).
Thank you.
