### ISSUE TITLE
Firmware always boots back to old flashed version `Bug` 

### ISSUE THREAD

**Issue by twasilczyk** [Blackymas/NSPanel_HA_Blueprint#1714]
### TFT Version

4.2.4

### ESPHome Version

4.2.4

### Panel Model

NSPanel US Model

### What is the bug?

After each reboot, NSPanel boots back to old lovelace firmware

### Steps to Reproduce

1. Flashed blank TFT firmware through lovelace ESPHome firmware
2. Flashed NSPanel_HA_Blueprint firmware through ESPHome
3. Flashed US-Portrait TFT firmware
4. Not expected: NSPanel booted back to lovelace firmware (I can tell because there are missing entities and there are lovelace-related logs in ESPHome)
5. Flashed NSPanel_HA_Blueprint firmware through ESPHome again
6. As expected: it booted fine
7. Restarted NSPanel
8. Not expected: booted back to lovelace again

### Your panel's YAML

```yaml
substitutions:
  device_name: media-room-panel
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  #nextion_update_url: "http://homeassistant.local:8123/local/nspanel_eu.tft"  # Optional for `esp-idf` framework
  # Add-on configuration (if needed)
  # heater_relay: "1"  # Possible values: "1" or "2"

# Customization area
##### My customization - Start #####
ota:
  password: "<REDACTED>"

api:
  encryption:
    key: "<REDACTED>"
##### My customization - End #####

# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # Optional advanced and add-on configurations
      # - advanced/esphome/nspanel_esphome_advanced.yaml
      # - nspanel_esphome_addon_climate_cool.yaml
      # - nspanel_esphome_addon_climate_heat.yaml
      # - nspanel_esphome_addon_climate_dual.yaml
    refresh: 300s

esp32:
  framework:
    type: esp-idf
```

### ESPHome logs

```logs
[10:16:40][D][nextion.upload.idf:090]: Uploaded 99.91 %, remaining 6376 bytes
[10:16:40][D][nextion.upload.idf:090]: Uploaded 99.97 %, remaining 2280 bytes
[10:16:40][D][nextion.upload.idf:090]: Uploaded 100.00 %, remaining 0 bytes
[10:16:40][D][nextion.upload.idf:249]: Successfully updated Nextion!
[10:16:40][D][nextion.upload.idf:251]: Close HTTP connection
[10:16:40][D][nextion.upload.idf:259]: Restarting Nextion
WARNING media-room-panel @ 192.168.1.142: Connection error occurred: [Errno 104] Connection reset by peer
INFO Processing unexpected disconnect from ESPHome API for media-room-panel @ 192.168.1.142
WARNING Disconnected from API
INFO Successfully connected to media-room-panel @ 192.168.1.142 in 0.006s
INFO Successful handshake with media-room-panel @ 192.168.1.142 in 0.126s
[10:17:03][W][nspanel_lovelace:054]: Unparsed data: 0x66
[10:17:03][W][nspanel_lovelace:054]: Unparsed data: 0x08
[10:17:03][W][nspanel_lovelace:054]: Unparsed data: 0xff
[10:17:03][W][nspanel_lovelace:054]: Unparsed data: 0xff
```

**Comment by twasilczyk** [comment]
After some digging I found that [changing between frameworks](https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/1631) changes partition table, so you can't OTA from lovelace to this firmware. After re-flashing over serial, it boots properly every time.

This bug may be still actionable, but I'm not sure if it's more on the side of this project or ESPHome. Potential AIs:
- detect invalid partition table when trying to do OTA
- if doing it during OTA is not possible, it could be done on boot (e.g. show a warning message)

Currently, everything works fine on the first boot - until restart.

**Comment by X-Ryl669** [comment]
Might be solvable. I'm trying some fix here (see [here](https://github.com/esphome/feature-requests/issues/2488)).
We can specify a `partition.csv` in the YAML file so it's possible to use esp-idf framework with a slightly modified partition scheme that matches Arduino's version so the Arduino bootloader will load the esp-idf application correctly.

I'll keep you informed if my solution works as expected and in that case, maybe it will be worth including it here in the documentation.

**Comment by twasilczyk** [comment]
I'm not really sure if it's worth the effort - there will always be some other partition layout that's not compatible (e.g. Tasmota). It may be better to just fail hard when a wrong layout is detected (that's my warning message suggestion).

**Comment by X-Ryl669** [comment]
You can't detect it. Both the bootloader and the application stores (a compiled version of) the partition layout. The bootloader isn't smart enough to find and compare the layout of the application. If both aren't compiled with the same layout, it's not possible to detect so.

**Comment by X-Ryl669** [comment]
Indeed my workaround works, so if you have built with Arduino framework, you can now switch to esp-idf framework by following this process: 

### 1. In you YAML add this at the end:
```yaml
esp32:
  framework:
    type: esp-idf
  flash_size: 4MB
  partitions: "nspanel1_part.csv"
```

### 2. Add a partitition file that's compatible with Arduino's bootloader
With the file editor, create a file `nspanel1_part.csv` in `esphome` folder (the same folder as your panel's YAML file)
The content is:
```csv
padding, data, undefined,    ,       0x4000,
phy_init, data, phy,     ,        0x1000,
otadata,  data, ota,     ,        0x2000,
app0,     app,  ota_0,   ,        0x1C0000,
app1,     app,  ota_1,   ,        0x1C0000,
nvs,      data, nvs,     ,        0x6D000,
```

### 3. Build and flash once
Then build your YAML file, (optional upload the tft to your server if you don't use github's URL).
It'll build and it'll flash it via OTA. 

Once it's booted, you'll need to re-flash it. This is because on the other OTA partition (the *not running* one), you still have Arduino's version you don't want (if you boot in it, it'll revert the change). By flashing a second time, this partition will be erased with an esp-idf version too and starting from there you're using **esp-idf**'s framework!

@edwardtfn If confirmed that it works for other, can you add this to the documentation? Because else, next month, a lot of your users will complain it doesn't work anymore.
