### ISSUE TITLE
`Bug` I cannot find the alarm section in the configuration

### ISSUE THREAD

**Issue by morpheus8888** [Blackymas/NSPanel_HA_Blueprint#1715]
### TFT Version

4.2.1

### ESPHome Version

4.2.1

### Blueprint Version

4.2.1

### Panel Model

NSPanel EU Model

### What is the bug?

When i open the nspanel configuration blueprint, i cannot find the alarm section and i dont know why

### Steps to Reproduce

Go to nspanel configuration and cannot find it, i followd the instructions in the wiki and i alread activated "Allow the device to make Home Assistant service calls".

### Your panel's YAML

```yaml
substitutions:
  # Settings - Editable values
  device_name: "nspanel" 
  wifi_ssid: "X"
  wifi_password: "X"
  nextion_update_url: "https://192.168.1.173:8123/local/nspanel_eu.tft"  # Optional for `esp-idf` framework
  # Add-on configuration (if needed)
  # heater_relay: "1"  # Possible values: "1" or "2"

# Customization area
##### My customization - Start #####
##### My customization - End #####

# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # Optional advanced and add-on configurations
      # - advanced/esphome/nspanel_esphome_advanced.yaml
      # - nspanel_esphome_addon_climate_cool.yaml
      # - nspanel_esphome_addon_climate_heat.yaml
      # - nspanel_esphome_addon_climate_dual.yaml
    refresh: 300s

esp32:
  framework:
```
