### ISSUE TITLE
Support `esphome.friendly_name` `Enhancement` 

### ISSUE THREAD

**Issue by twasilczyk** [Blackymas/NSPanel_HA_Blueprint#1719]
### Enhancement Summary

If I add `friendly_name` field to `esphome` section, NSPanel UI stops working

### Detailed Description

After adding `friendly_name` (e.g. to have `media-room-panel` as device name, but `Media room panel` as display name), device shows up in HA under this new name (as expected), but its sensors (and as I guess service names) are mixed up (see screenshot). It's probably because `nspanel_esphome.yaml` refer everywhere to `${name}` and not display name.

This in turn causes automation to try calling wrong service names:
> The automation "Media room panel configuration" (automation.media_room_panel_configuration) has an action that calls an unknown service: esphome.media_room_panel_media_room_panel_page_home.

### Additional Context

![friendly-name-problem](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/1107414/4b7687e6-f701-4fe0-a239-974d85dd6272)

My ESPHome yaml:
```
substitutions:
  device_name: media-room-panel
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  ota_password: !secret ota_password

esphome:
  friendly_name: Media room panel

api:
  encryption:
    key: !secret nspanel_api_encryption_key

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml
    refresh: 300s

esp32:
  framework:
    type: esp-idf
```
