### ISSUE TITLE
Slow button page load with automation entities `Bug` 

### ISSUE THREAD

**Issue by brianmaas** [Blackymas/NSPanel_HA_Blueprint#1746]
### TFT Version

4.2.4

### ESPHome Version

4.2.4

### Blueprint Version

4.2.4

### Panel Model

NSPanel US Model

### What is the bug?

Automation entities on button pages load very slowly

### Steps to Reproduce

I have a specific page which only contains automation entities. I have the setting selected to show pages while loading. Each button shows up on the screen with the icon highlighted in the active color. Then it slowly turns to the white or gray color. Then this repeats for each button. My page with 7 buttons takes about 6 seconds to load completely. 

In the advanced settings I also have changed the "button action for automation entities" to "Trigger". I've also tried the "Toggle" setting. The button load time doesn't change.

### Your panel's YAML

```yaml
substitutions:
  ###### CHANGE ME START ######
  device_name: "nsfamilyroom" 
  wifi_ssid: "NETGEAR75"
  wifi_password: ""

  nextion_update_url: "http://10.0.74.138:1180/nspanel_us.tft"
  nextion_blank_url: "http://10.0.74.138:1180/nspanel_blank.tft"

# Limit the amount of resources used for compiling



  ##### addon-configuration #####
  ## addon_climate ##
  # addon_climate_heater_relay: "1" # possible values: 1/2

  ##### CHANGE ME END #####

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # - advanced/esphome/nspanel_esphome_advanced.yaml # activate advanced (legacy) elements - can be useful for troubleshooting
      # - nspanel_esphome_addon_climate_cool.yaml # activate for local climate (cooling) control
      # - nspanel_esphome_addon_climate_heat.yaml # activate for local climate (heater) control
    refresh: 1s

esp32:
  framework:
    type: arduino

#### type: esp-idf
##### My customization - Start #####
##### My customization - End #####
```
