### ISSUE TITLE
Cover add-on

### ISSUE THREAD

**Issue by edwardtfn** [Blackymas/NSPanel_HA_Blueprint#1752]
Thanks Edward!There a two questions about that:1. To use it without the Shelly, you have to add a security option like "if button 1 is in action, button 2 can't be triggered". Shelly makes this in his software. When triggering both buttons at the same time, the shutter will get damaged immediately.2. Can you tell me what I have to type in, when the shutter needs, e.g. 96seconds.I'll try this code without the Shelly in between, since it is a really welcome addition of usecase to the panel!Again, thank you so much!Am 09.08.23, 23:40 schrieb Edward Firmo ***@***.***>:

   
  So, we have discussed about this case with a Shelly 2PM on #968 and #969, so I will focus here on this use case where the panel will be controlling the cover without the Shelly. 
  What you are asking for is already covered by ESPHome Time based cover and I would recommend to work with that as a customization of your ESPHome settings. Something like this: 
  

```yaml
substitutions:
###### CHANGE ME START ######

  device_name: "YOUR NSPANEL_NAME" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: "http://homeassistant.local:8123/local/nspanel_eu.tft"

##### CHANGE ME END #####



##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####


##### MY CUSTOMIZATION - START #####
cover:
  - platform: time_based
    name: "Time-Based Cover"

    open_action:
      - switch.turn_on: relay_1
    open_duration: 2.1min

    close_action:
      - switch.turn_on: relay_2
    close_duration: 2min

    stop_action:
      - switch.turn_off: relay_1
      - switch.turn_off: relay_2
##### MY CUSTOMIZATION - END #####
```
  —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

_Originally posted by @DerBo19 in https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/965#discussioncomment-6688022_
