### ISSUE TITLE
Update notification in HA when new version is available

### ISSUE THREAD

**Issue by edwardtfn** [Blackymas/NSPanel_HA_Blueprint#1759]
I'm not sure if it's technically feasable but HA gives all kinds of update-notifications but not when this bundle (TFT firmware, blueprint and ESP firmware) are updated. That's kind of odd. 
Maybe a simple integration that polls the versions would help?

_Originally posted by @MichaelHeimann in https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/1758_

**Comment by edwardtfn** [comment]
In fact, the notification you currently have is connected to the entity `update.<<Panel name>>_firmware`, which is managed by ESPHome (not our code) and indicate when a new version if ESPHome (compiler) is available, so it is quite disconnected from our project.
A notification about new version of our project available would be possible using Home Assistant notification area, which is not commonly used for this purpose, but this would require the panel pulling our GitHub repository from time to time, which might not be possible in some cases where the panel is isolated from the Internet, but also may cause discomfort in some people (although for those we could have a switch to enable/disable this).
I've been thinking about this as part of [Simplifying User Experience for NSPanel Firmware](https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/1602) as access to Internet would make many things easier for entry level users, but still having to mature this a bit more.

**Comment by Dust-E** [comment]
Hi @edwardtfn 
I'm actually looking for the same solution.
The Github integration in HA gives you the option to create a number of sensors per repository via the Configure button
I think if you give a separate message in this topic that you have uploaded the TFT, you could trigger it
If you would like to do that I can see if I can test this
Let me know

**Comment by edwardtfn** [comment]
Home Assistant v2024.7 (to be released) and ESPHome v2024.6 enables an update entity for the ESPHome part, but that would require a pre-built firmware (which we already have in experimental phase), however that is only for the ESPHome side.
The issue about using the Github integration is that every user would have to install that manually. 😩
As I mentioned before, using persistent notification for this is quite easy, but a bit odd. Maybe we can enable/disable those notifications via Blueprint.
Anyhow, we probably don't want the panel pooling something in the Internet all the time without user's consent.

**Comment by Dust-E** [comment]
I like to see that you go for the best. :-) For the time being, it wouldn't matter to me for this interim solution, which I can understand if you don't want this for a small group of people.

**Comment by Dust-E** [comment]
I made something in my dashboard

<img width="739" height="146" alt="Image" src="https://github.com/user-attachments/assets/48e6505b-c8a4-4fd5-9ff3-bd5ed2a05f16" />


**Chip > NSPanel_versie_github**
```
type: custom:mushroom-chips-card
chips:
  - type: template
    entity: sensor.NSPanel_versie_github
    content: Latest {{ states('sensor.NSPanel_versie_github') }}
    icon_color: orange
    icon: mdi:package-variant-closed
```


**Rest sensor**
```
resource: https://api.github.com/repos/Blackymas/NSPanel_HA_Blueprint/releases/latest
scan_interval: 3600
sensor:
  - name: "NSPanel_versie_github"
    value_template: "​{{ value_json.tag_name }}​"
```


**Chip > Release Changelog**
```
type: custom:mushroom-chips-card
chips:
  - type: template
    icon: mdi:web
    icon_color: blue
    content: Release Changelog
    tap_action:
      action: url
      url_path: https://github.com/Blackymas/NSPanel_HA_Blueprint/releases
```


**Chip > ReleaseNotes**
```
type: custom:mushroom-chips-card
chips:
  - type: template
    icon: mdi:web
    icon_color: blue
    content: ReleaseNotes
    tap_action:
      action: url
      url_path: >-
        https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/ReleaseNotes.md
```


**Chip > nspanel_eu.tft**
```
type: custom:mushroom-chips-card
chips:
  - type: template
    icon: mdi:web
    icon_color: blue
    content: nspanel_eu.tft
    tap_action:
      action: url
      url_path: >-
        https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/hmi/nspanel_eu.tft
```


Chip comparison
With Gemini's help, I created this:
This compares my 4 NSPanels TFT versions with the GitHub TFT. If everything is the same, it shows up-to-date in green. If one or more are not up-to-date, it turns orange. And if everything is not the same as the GitHub version, it turns red.

```
type: custom:mushroom-chips-card
chips:
  - type: template
    entity: sensor.nspanel_versie_github
    icon: mdi:update
    content: >-
      {# Also clean up the GitHub version here robustly, in case the REST sensor
      doesn't work 100% #} {% set github_version =
      states('sensor.nspanel_versie_github') | regex_replace('[^0-9\\.]', '') %}
      {% set panels = [
        states('sensor.nspaneloffice_version_tft') | regex_replace('[^0-9\\.]', ''),
        states('sensor.nspanelmb_version_tft') | regex_replace('[^0-9\\.]', ''),
        states('sensor.nspanel3_version_tft') | regex_replace('[^0-9\\.]', ''),
        states('sensor.nspanel4_version_tft') | regex_replace('[^0-9\\.]', '')
      ] %} {% set matching_panels = panels | select('eq', github_version) | list
      | length %} {% set total_panels = panels | length %}

      {% if matching_panels == total_panels %}
        All panels are up to date
      {% else %}
        {{ matching_panels }} / {{ total_panels }} up-to-date
      {% endif %}
    card_mod:
      style: |
        ha-card {
          {# Clean up the GitHub version here as well, consistently with the content section #}
          {% set github_version = states('sensor.nspanel_versie_github') | regex_replace('[^0-9\\.]', '') %}
          {% set panels = [
            states('sensor.nspaneloffice_version_tft') | regex_replace('[^0-9\\.]', ''),
            states('sensor.nspanelmb_version_tft') | regex_replace('[^0-9\\.]', ''),
            states('sensor.nspanel3_version_tft') | regex_replace('[^0-9\\.]', ''),
            states('sensor.nspanel4_version_tft') | regex_replace('[^0-9\\.]', '')
          ] %}
          {% set matching_panels = panels | select('eq', github_version) | list | length %}
          {% set total_panels = panels | length %}

          {% if matching_panels == total_panels %}
            --chip-background: #4CAF50; /* Green */
          {% elif matching_panels > 0 %}
            --chip-background: #FF9800; /* Orange */
          {% else %}
            --chip-background: #F44336; /* Red */
          {% endif %}
        }
```
