### ISSUE TITLE
`Bug` Entities states "status" not getting the right language

### ISSUE THREAD

**Issue by sanvalerius** [Blackymas/NSPanel_HA_Blueprint#1777]
### ESPHome Version

2023.12.9

### Blueprint Version

4.2.4

### Panel Model

NSPanel EU Model

### What is the bug?

When displaying the entities, the states values are in english even if the "Language for NSPanel" is set to French

### Steps to Reproduce

- Set "Language for NSPanel" to "francais"
- Under "ENTITY PAGE 01", "Entity 01 - ENTITY":  add an entity, ie I added a "Cover"
- On the NSPanel, when I click the Entities Button I get the entity list and status, but it displays:
**Volet Salon     closed**
instead of
**Volet Salon     fermé**

### Your panel's YAML

```yaml
alias: NSPANEL - SALON
description: NSPanel (from blueprint)
use_blueprint:
  path: Blackymas/nspanel_blueprint.yaml
  input:
    language: fr
    date_format: "%A, %d/%m"
......
    entity_page01_label: Etats
    entities_entity01: cover.garage_gauche
    entities_entity02: cover.garage_droite
 
```
