### ISSUE TITLE
Bug: When specifying a `friendly_name` in ESPHome yaml, the blueprint tries to use that for service names

### ISSUE THREAD

**Issue by grigi** [Blackymas/NSPanel_HA_Blueprint#1787]
### Enhancement Summary

Allow to work with specifying friendly_name in ESPHome yaml

### Detailed Description

I have a panel that's named `nspanel-01`, it has a friendly name of `NSPanel Study`.
On 4.2.4 (and a few versions earlier) it worked fine, and it showed the same friendly name in ESPHome and Home Assistant interfaces.

When upgrading for 4.2.5, the panel stopped working as the blueprint couldn't connect to the panel.
In the logs it was failing to call various services that were named `nspanel_study_*`.
The services were all named `nspanel_01_*` instead.

This was with all of ESPHome/TFT/Blueprint being at the stable 4.2.5 release. ESPHome was built with esp-idf.

When I removed the `friendly_name:` value in the ESPHome yaml, rebuilt and uploaded it, and re-selected the NSPanel in the Blueprint, everything started working.

### Additional Context

My full ESPHome yaml:
```yaml
substitutions:
  # Settings - Editable values
  device_name: nspanel-01
  friendly_name: NSPanel Study
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  # nextion_update_url: "http://192.168.0.210:8123/local/nspanel_eu.tft"
  nextion_update_url: "https://github.com/Blackymas/NSPanel_HA_Blueprint/raw/main/nspanel_eu.tft"
  # Add-on configuration (if needed)
  # heater_relay: "1"  # Possible values: "1" or "2"

# Customization area
##### My customization - Start #####
ota:
  password: "<supersecret-as-I-had-to-change-wifi-networks-a-month-ago>"
##### My customization - End #####

# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # Optional advanced and add-on configurations
      # - advanced/esphome/nspanel_esphome_advanced.yaml
      # - nspanel_esphome_addon_climate_cool.yaml
      # - nspanel_esphome_addon_climate_heat.yaml
      # - nspanel_esphome_addon_climate_dual.yaml
    refresh: 300s

esp32:
  framework:
    type: esp-idf
```
