### ISSUE TITLE
Trying to upgrade ESPHome to version 4.2.5 fails with ERROR Error binary size: Unknown error from ESP

### ISSUE THREAD

**Issue by stalakerob** [Blackymas/NSPanel_HA_Blueprint#1791]
### TFT Version

4.2.4

### ESPHome Version

4.2.4

### Blueprint Version

4.2.4

### Panel Model

EU

### What is the bug?

Trying to upgrade ESPHome to version 4.2.5 fails with ERROR Error binary size: Unknown error from ESP.

### Steps to Reproduce

ESPHome is version 2023.12.9

### Your Panel's YAML

```yaml
substitutions:
  # Settings - Editable values
  device_name: "nspanel1" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  nextion_update_url: "http://homeassistant.local:8123/local/nspanel_eu.tft"  # Optional for `esp-idf` framework
  # Add-on configuration (if needed)
  # heater_relay: "1"  # Possible values: "1" or "2"

# Customization area
##### My customization - Start #####
##### My customization - End #####

# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # Optional advanced and add-on configurations
      # - advanced/esphome/nspanel_esphome_advanced.yaml
      # - nspanel_esphome_addon_climate_cool.yaml
      # - nspanel_esphome_addon_climate_heat.yaml
      # - nspanel_esphome_addon_climate_dual.yaml
    refresh: 300s

esp32:
  framework:
    type: esp-idf
```

### ESPHome Logs

INFO ESPHome 2023.12.9
INFO Reading configuration /root/config/nspanel1.yaml...
INFO Detected timezone 'Europe/Berlin'
INFO Generating C++ source...
INFO Compiling app...
Processing nspanel1 (board: esp32dev; framework: espidf; platform: platformio/espressif32@5.4.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - framework-espidf @ 3.40405.230623 (4.4.5) 
 - tool-cmake @ 3.16.4 
 - tool-ninja @ 1.7.1 
 - toolchain-esp32ulp @ 2.35.0-20220830 
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
Reading CMake configuration...
Dependency Graph
|-- ArduinoJson @ 6.18.5
Compiling .pioenvs/nspanel1/src/main.o
Linking .pioenvs/nspanel1/firmware.elf
RAM:   [=         ]  10.2% (used 33336 bytes from 327680 bytes)
Flash: [======    ]  62.0% (used 1137161 bytes from 1835008 bytes)
Building .pioenvs/nspanel1/firmware.bin
Creating esp32 image...
Successfully created esp32 image.
esp32_create_combined_bin([".pioenvs/nspanel1/firmware.bin"], [".pioenvs/nspanel1/firmware.elf"])
Wrote 0x127080 bytes to file /root/config/.esphome/build/nspanel1/.pioenvs/nspanel1/firmware-factory.bin, ready to flash to offset 0x0
========================= [SUCCESS] Took 58.38 seconds =========================
INFO Successfully compiled program.
INFO Connecting to 192.168.1.72
INFO Uploading /root/config/.esphome/build/nspanel1/.pioenvs/nspanel1/firmware.bin (1142912 bytes)
ERROR Error binary size: Unknown error from ESP

**Comment by stalakerob** [comment]
Yes, I tried it but unfortunately it did not help.

**Comment by stalakerob** [comment]
More info which might be useful: I used nspanel-lovelace-ui before and then migrated to this blueprint following the steps outlined in the docs. Everything worked as expected. The installed ESPHome version currently is 2023.12.8. I believe this is the first time I'm trying to use OTA to update the software. So it might have not worked with previous versions either but I don't know.

**Comment by edwardtfn** [comment]
But when migrating from Lovelace UI to ESPHome, have you done OTA or serial flashing?

You can try switching to Arduino framework, as that is closer to what Tasmota uses (or it is exactly the one used by Lovelace UI in it's ESPHome version).

Just change the settings in the end to this:

```yaml
esp32:
  framework:
    type: arduino
```
