### ISSUE TITLE
[nextion:405]: Nextion reported variable name invalid!

### ISSUE THREAD

**Issue by sparkydave1981** [Blackymas/NSPanel_HA_Blueprint#1794]
### TFT Version

4.2.4

### ESPHome Version

2023.12.9

### Blueprint Version

4.2.4

### Panel Model

US

### What is the bug?

Nextion reported variable name invalid!

### Steps to Reproduce

Attempt to upload TFT file via ESPhome device settings page (update TFT button) while using dev version of ESPhome code

### Your Panel's YAML

```yaml
substitutions:

###### CHANGE ME START ######

  device_name: "nspanel1" 
  wifi_ssid: !secret wifi_iot24g_ssid
  wifi_password: !secret wifi_iot24g_password

  nextion_update_url: "http://192.168.0.14:8123/local/nspanel_us.tft" # URL to local tft File
#  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_us.tft" # URL to Github

##### CHANGE ME END #####



##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: dev #main
    files: 
      - nspanel_esphome.yaml
    refresh: 300s

esp32:
  framework:
    type: esp-idf


##### DO NOT CHANGE ANYTHING! #####





##### My customization - Start #####

# Set IP address manually
wifi:
  networks:
    - id: !extend wifi_default
      manual_ip:
        static_ip: 192.168.20.168
        gateway: 192.168.20.1
        subnet: 255.255.255.0
```

### ESPHome Logs

[nextion:405]: Nextion reported variable name invalid!
