### ISSUE TITLE
`Enhancement` Reducing HA recorder database spam.

### ISSUE THREAD

**Issue by illuzn** [Blackymas/NSPanel_HA_Blueprint#1802]
### Enhancement Summary

Lowering the number of "call_service" events

### Detailed Description

I've excluded the blueprint from my state history to reduce the amount of spam to my "states" table in the recorder database. This spam is pretty significant since every time the state changes, it records all of the attributes as well. The automation is fired many times a minute so this saves a lot of database space.

However, aside from excluding all "call_service" events (which I prefer not to do because it affects all services), is there a way to reduce the database spam from "call_service" events? These events are all similar to this:
```yaml
event_type: call_service
data:
  domain: esphome
  service: mbr_nspanel_send_command_text_printf
  service_data:
    component: home.current_temp
    message: 22.8°
origin: LOCAL
time_fired: "2024-02-15T11:56:10.385411+00:00"
context:
  id: 01HPP9ZJY8BM5J8X30A10PGR7F
  parent_id: 01HPP9ZJY407BW8RYM8MJ5SNEW
  user_id: null
```

Needless to say this event data is practically useless.

This fires every time a tracked sensor changes or the display of the NSPanel changes (which given the number of sensors I am tracking occurs multiple times a minute) and is causing me significant database spam (if each request is 0.3KB, and the event fires around 10 times a minute, this will cause 260MB of data per day). Based on my usage, this is taking up around 25% of my database currently.

This may be an upstream issue because there may not be a way to prevent these service calls from being recorded by the recorder.
