### ISSUE TITLE
`Bug` advanced/esphome/nspanel_esphome_core.yaml - config error

### ISSUE THREAD

**Issue by quenthal** [Blackymas/NSPanel_HA_Blueprint#1803]
### TFT Version

4.2.5

### ESPHome Version

4.2.5

### Blueprint Version

4.2.5

### Panel Model

EU

### What is the bug?

Because of underscores, advanced/esphome/nspanel_esphome_core.yam fails as config.

### Steps to Reproduce

Replacing package nspanel_esphome.yaml with advanced/esphome/nspanel_esphome_core.yaml gives few errors for me. mainly because character '_'

### ESPHome Logs

```
Failed config

sensor.nextion: [source <unicode string>:1450]
  id: display_mode
  name: Display mode
  platform: nextion
  
  Must only consist of upper/lowercase characters, numbers and the period '.'. The character '_' cannot be used.
  variable_name: display_mode
  precision: 0
  accuracy_decimals: 0
  internal: False
  icon: mdi:phone-rotate-portrait
  entity_category: diagnostic
text_sensor.nextion: [source <unicode string>:1782]
  id: version_tft
  name: Version TFT
  platform: nextion
  
  Must only consist of upper/lowercase characters, numbers and the period '.'. The character '_' cannot be used.
  component_name: tft_version
  entity_category: diagnostic
  icon: mdi:tag-text-outline
  internal: False
  update_interval: never
  on_value: 
    - lambda: |-
        static const char *const TAG = "text_sensor.version_tft";
        ESP_LOGD(TAG, "TFT version: %s", x.c_str());
        if (current_page->state == "boot") {
          disp1->send_command_printf("tm_esphome.en=0");
          page_boot->execute();
          timer_reset_all->execute("boot");
        }
        check_versions->execute();

```

**Comment by edwardtfn** [comment]
As a working around, please add this to your customizations:
```yaml
external_components:
  - source:
      type: git
      url: https://github.com/edwardtfn/esphome
      ref: nextion-v425
    components:
      - nextion  # Change this when that PR#6192 gets released (2024.2?)
    refresh: 300s
```

This should be removed after the update to v4.2.6, which still in development.
