### ISSUE TITLE
Unable to update

### ISSUE THREAD

**Issue by obrien-james** [Blackymas/NSPanel_HA_Blueprint#1818]
### ESPHome Version

2023.12.9

### Blueprint Version

4.2.6

### Panel Model

EU

### What is the bug?

I've tried to follow the guide to update the blueprint but cant update the panel itself. 

### Steps to Reproduce

I have reloaded the blueprint, which now shows the newest version (4.2.6)

I have gone to ESPHome,
Clicked clean build files 

This fails, the output is as follows:

```
INFO ESPHome 2023.12.9
INFO Reading configuration /config/esphome/study-panel.yaml...
INFO Updating https://github.com/Blackymas/NSPanel_HA_Blueprint@main
Failed config

packages: [source <unicode string>:17]
  
  fetch-pack: invalid index-pack output.
  remote_package: 
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: 
      - nspanel_esphome.yaml
    refresh: 1s
```

Now the panel doesn't show anything on the button pages despite them still being configured in the automation. 

### Your Panel's YAML

```yaml
YAML config:

substitutions:
  ###### CHANGE ME START ######
  device_name: "studypanel" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: "http://homeassistant.local:8123/local/nspanel_eu.tft"
  nextion_blank_url: "http://homeassistant.local:8123/local/nspanel_blank.tft"

  ##### addon-configuration #####
  ## addon_climate ##
  # addon_climate_heater_relay: "1" # possible values: 1/2

  ##### CHANGE ME END #####

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # - advanced/esphome/nspanel_esphome_advanced.yaml # activate advanced (legacy) elements - can be useful for troubleshooting
      # - nspanel_esphome_addon_climate_cool.yaml # activate for local climate (cooling) control
      # - nspanel_esphome_addon_climate_heat.yaml # activate for local climate (heater) control
    refresh: 1s

esp32:
  framework:
    type: esp-idf

##### My customization - Start #####

##### My customization - End #####
```
