### ISSUE TITLE
Seeing an Old Firmware Version After Update? Here's Why & How to Fix It

### ISSUE THREAD

**Issue by edwardtfn** [Blackymas/NSPanel_HA_Blueprint#1821]
## Issue Description
Users updating ESPHome firmware might encounter a situation where the device reports an older version installed than expected.

## Probable Cause
This issue typically arises from switching between the `arduino` and `esp-idf` frameworks without performing a serial flash. These frameworks utilize different partition schemes, potentially causing the bootloader to select an outdated partition during boot.

### Serial Flashing (Recommended)
Reflash your device using a serial connection as described in the [initial installation guide](https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/docs/install.md#flashing-the-device-for-the-first-time).

This ensures the device's filesystem is correctly aligned with ESP-IDF's partitioning, thereby eliminating remnants of Arduino framework data.

### Temporarily Enforcing Arduino Framework
If serial flashing isn't immediately possible, you may temporarily enforce the Arduino framework by adding the following to your device's YAML configuration:
```yaml
esp32:
  framework:
    type: arduino
```
This measure allows more time to plan for a serial flash transition to ESP-IDF.

## Additional Information
- For ongoing discussions and updates, refer to [Aligning with ESP-IDF: Preparing for Our Future](https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/1756).
- Detailed instructions for serial flashing are available in [Getting Started with NSPanel HA Blueprint - Flashing the Device for the First Time](https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/docs/install.md#flashing-the-device-for-the-first-time).

**Comment by electrocamuk** [comment]
I was scratching my head for a while and didn't initially spot this pinned issue, I'll get the RS-232 prodder out later and have a go at re-flashing the NSpanel :)

**Comment by X-Ryl669** [comment]
Or do this, it doesn't require unmounting the panel to serial flash them

## Change to YAML
Add this at the end of the yaml file:
```yaml
esp32:
  framework:
    type: esp-idf
  flash_size: 4MB
  partitions: "nspanel1_part.csv"
```

## Add the partition file 
In the HA File editor, create a new file `nspanel1_part.csv` in `esphome/` folder (the same folder where yaml are)
This files should contains:
```
padding, data, undefined,    ,       0x4000,
phy_init, data, phy,     ,        0x1000,
otadata,  data, ota,     ,        0x2000,
app0,     app,  ota_0,   ,        0x1C0000,
app1,     app,  ota_1,   ,        0x1C0000,
nvs,      data, nvs,     ,        0x6D000,
```

**Comment by primeroz** [comment]
@X-Ryl669 is this a one off change that can be removed after flashing or does it have to stay forever ?

**Comment by X-Ryl669** [comment]
@primeroz No, it's forever. The previous version used the Arduino platform with the Arduino bootloader that has *this* partition layout. The new version uses ESP-IDF platform that has a default partition layout that's not compatible with Arduino's layout. 

Since OTA never flash the bootloader (*), you can't change the partition layout via OTA. So the only option is just to change the partition layout in ESP-IDF platform so it matches Arduino's version. 

(*) It's actually possible to flash the bootloader via OTA, but ESPHome doesn't support it.

**Comment by primeroz** [comment]
thanks , i did try OTA with the extra 

```
esp32:
  framework:
    type: esp-idf
  flash_size: 4MB
  partitions: "nspanel1_part.csv"
```

at the end of my yaml but it did not work, on reboot it still gets stuck and on the logs i can see is booting an old version 

I will go serial :)

**Comment by edwardtfn** [comment]
> (*) It's actually possible to flash the bootloader via OTA, but ESPHome doesn't support it.

Not yet… 😉

- esphome/esphome#5535

**Comment by X-Ryl669** [comment]
@primeroz Bad luck, you were on the other partition. You'll have to flash it twice via OTA with the same firmware, so it updates both partitions. Once you've flashed a first time via OTA, **on next boot** you'll flash a second time with OTA and you'll be done.

**Comment by X-Ryl669** [comment]
@edwardtfn Great, it'll likely solve the underlying issue

**Comment by primeroz** [comment]
> Bad luck, you were on the other partition. You'll have to flash it twice via OTA with the same firmware

Seems like it worked , thanks ! 

so can i remove the `extra yaml` now right

**Comment by edwardtfn** [comment]
> so can Iremove the extra yaml now right

You should have removed that before flashing. 😬

Could you please share the yaml used for flashing via serial? Please remove any sensitive information before sharing.

**Comment by primeroz** [comment]
> Could you please share the yaml used for flashing via serial

sorry i meant i `flashed twice over OTA` not needed to do serial 

anyway here is the yaml

```
substitutions:
###### CHANGE ME START ######

  device_name: "nswhite1" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

#  nextion_update_url: "http://HOME-ASSISTANT-IP:8123/local/nspanel_us.tft" # URL to local tft File
  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/v4.3.1/nspanel_eu.tft"
##### CHANGE ME END #####

##### My Overrides #####
web_server:
  auth:
    username: admin
    password: !secret nswhite1_web_server_password

# NEED To reflash through USB
#ota:
#  password: !secret nswhite1_ota_password

api:
  encryption: 
    key: !secret nswhite1_api_encryption_key
##### My Overrides END #####

##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: v4.3.1
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####

# https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/1821
esp32:
  framework:
    type: esp-idf
  flash_size: 4MB
  partitions: "nspanel_part.csv"
```
