### ISSUE TITLE
Add the possibility to use attributes in the 'Home Page - Sensors' section (a.o) of the blueprint

### ISSUE THREAD

**Issue by edwardtfn** [Blackymas/NSPanel_HA_Blueprint#1831]
After running into some issues, mostly due to very limited knowledge of HA, I managed to get my nspanel up and running and I like it a lot!! One thing that I didn't manage is displaying the attribute value of an entity on my home page (and entity pages). For example the target temperature of my Sonoff TRVZB or the lowest KWh price of electricity for this day (is an attribute of the 'electricity price' entity provided by the API of my provider. When I use an entity with attributes in an automation I can select an attribute from a pull-down menu.
Wouldn't it be nice if this could be added to the blueprint as well?
I have tried several ways to turn an attribute into an entity using the many examples in the HA groups but until now didn't manage to make it work (most likely again due to lack of knowledge). Suggestions for a simple alternative are more than welcome!

_Originally posted by @kees-jans in https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/1827_

**Comment by MikeGuest** [comment]
The easiest way would be to create a template sensor.

In configuration.yaml, add the following:

template: 
  !include sensors.yaml

create the file sensors.yaml in the same folder as configuration.yaml

in sensors.yaml, use a modified version of the following. This example creates a new sensor called TADO_Bedroom_Action where the state of that sensor equals the value of the hvac_action attribute of the climate.bedroom_2 entity

```
    - name: "TADO_Bedroom_Action"
      state: >
        {%set myvalue = state_attr('climate.bedroom_2', 'hvac_action') %}
        {{myvalue}} 
```
After doing this you'll need to reload all yaml to pick up the new sensor.

hopefully with this basic example you should be able to add this new sensor to your panel.

**Comment by kees-jans** [comment]
Hi Mike, thanks for your suggestion and it looks like a good alternative. Unfortunately I get this error message  after restarting the yaml's:

Logger: homeassistant.config
Source: config.py:597
First occurred: 22 februari 2024 om 16:37:53 (7 occurrences)
Last logged: 07:23:46

Invalid config for 'template' at configuration.yaml, line 29: required key 'state' not provided Invalid config for 'template' at configuration.yaml, line 30: 'platform' is an invalid option for 'template', check: sensor->0->platform Invalid config for 'template' at configuration.yaml, line 31: 'entity_id' is an invalid option for 'template', check: sensor->0->entity_id Invalid config for 'template' at configuration.yaml, line 33: 'attribute' is an invalid option for 'template', check: sensor->0->attribute
Invalid config for 'template' at sensors.yaml, line 1: 'name' is an invalid option for 'template', check: name Invalid config for 'template' at sensors.yaml, line 2: 'state' is an invalid option for 'template', check: state
Invalid config for 'template' at sensors.yaml, line 6: 'name' is an invalid option for 'template', check: name Invalid config for 'template' at sensors.yaml, line 7: 'state' is an invalid option for 'template', check: state

Template statement in Config.yaml:

template: 
  !include sensors.yaml_


Sensors.yaml:

    - name: "lowest_kwh_price"
      state: >
        {%set myvalue = state_attr('electricity_price_simone_signoretstraat_51', 'min_price') %}
        {{myvalue}} 
        
    - name: "highest_kwh_price"
      state: >
        {%set myvalue = state_attr('electricity_price_simone_signoretstraat_51', 'max_price') %}
        {{myvalue}}_ 

Any idea what's going wrong here? Probably a stupid mistake due to my lack of yaml knowledge.
Thanks for attempt to solve it.

**Comment by edwardtfn** [comment]
Please try this:

```yaml
- name: "lowest_kwh_price"
  state: >
    {% set myvalue = state_attr('electricity_price_simone_signoretstraat_51', 'min_price') %}
    {{ myvalue }} 
    
- name: "highest_kwh_price"
  state: >
    {% set myvalue = state_attr('electricity_price_simone_signoretstraat_51', 'max_price') %}
    {{ myvalue }}
```

**Comment by kees-jans** [comment]
That helped! No more errors in the log and sensors can be selected on the sensor-homepage of my NSpanel. Thanks!!
But... the value is not showing on the panel. If I look at the status of the sensors (in HA development tools) the value of both min_price and max_price is 'unknown'. Maybe I do need to define things like 'unit_of_measurement' or 'state_class'? These are defined in the main entity (electricity price). Attached is a printscreen of the status.
Sorry for raising many questions.
![highest_kwh_price](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/160887258/f5635c27-941d-47a0-bbdf-66bf304d1936)

**Comment by edwardtfn** [comment]
Try this:

```yaml
- name: "lowest_kwh_price"
  state: >
    {% set myvalue = state_attr('sensor.electricity_price_simone_signoretstraat_51', 'min_price') %}
    {{ myvalue }} 
    
- name: "highest_kwh_price"
  state: >
    {% set myvalue = state_attr('sensor.electricity_price_simone_signoretstraat_51', 'max_price') %}
    {{ myvalue }}
```
