### ISSUE TITLE
nspanel temperautre sensor showing as celsius 

### ISSUE THREAD

**Issue by ascii1b-pixel** [Blackymas/NSPanel_HA_Blueprint#1834]
### TFT Version

4.2.6

### ESPHome Version

4.2.6

### Blueprint Version

4.2.6

### Panel Model

US

### What is the bug?

When I put sensor.nspanel_temperature to read the panel's temperature on the home screen, it displays as Celsius, not Fahrenheit. sensor.nspanel_temperature correctly shows as Fahrenheit inside ESP configuration

**Comment by edwardtfn** [comment]
On your substitutions, please add this:
```yaml
  temp_units: "°F"
```

**Comment by ascii1b-pixel** [comment]
thank you so much for replying so quickly.

where are "substutions"? in the esp32 yamel?

**Comment by edwardtfn** [comment]
In your Home Assistant, go to the ESPHome Dashboard and find your panel, then click **Edit** to see your yaml. It will look like this (please don't copy/paste from here):
```yaml
substitutions:
  # Settings - Editable values
  device_name: "YOUR_NSPANEL_NAME"
  friendly_name: "Your panel's friendly name"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  # Add-on configuration (if needed)
  ## Add-on climate
  heater_relay: "1"  # Possible values: "1" or "2"

# Customization area
##### My customization - Start #####
##### My customization - End #####

# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # Optional advanced and add-on configurations
      # - advanced/esphome/nspanel_esphome_advanced.yaml
      # - nspanel_esphome_addon_climate_cool.yaml
      - nspanel_esphome_addon_climate_heat.yaml
      # - nspanel_esphome_addon_climate_dual.yaml
    refresh: 300s

esp32:
  framework:
    type: esp-idf
```

Then you add that line on the substitutions area, like this (please don't copy/paste, but edit your existing file):
```yaml
substitutions:
  # Settings - Editable values
  device_name: "YOUR_NSPANEL_NAME"
  friendly_name: "Your panel's friendly name"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  temp_units: "°F"

  # Add-on configuration (if needed)
  ## Add-on climate
  heater_relay: "1"  # Possible values: "1" or "2"

# Customization area
##### My customization - Start #####
##### My customization - End #####

# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # Optional advanced and add-on configurations
      # - advanced/esphome/nspanel_esphome_advanced.yaml
      # - nspanel_esphome_addon_climate_cool.yaml
      - nspanel_esphome_addon_climate_heat.yaml
      # - nspanel_esphome_addon_climate_dual.yaml
    refresh: 300s

esp32:
  framework:
    type: esp-idf
```
