### ISSUE TITLE
Panel not loading new firmware on the screen but is connected to HA

### ISSUE THREAD

**Issue by Zouljiin** [Blackymas/NSPanel_HA_Blueprint#1840]
### TFT Version

dont know where to look

### Blueprint Version

Version: v4.2.6

### Panel Model

US

### What is the bug?

Panel not loading new firmware on physical device but is connected to HA

### Steps to Reproduce

I have (successfully) performed the upload 3 times with no errors and one of them was even OTA. I can add the device in HA and even control it but the picture below is what is on the screen and the buttons no longer work. it boots with the sonoff load screens like normal and not the new firmware. the HA controls do control the relays but the physical buttons do not.

![20240222_002437](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/66489173/8d6d3676-40cc-4f26-9677-7f9f76e7d9f6)

### Your Panel's YAML

```yaml
substitutions:
  # Settings - Editable values
  device_name: "livingroomnsp"
  friendly_name: "Living Room NSP"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  # nextion_update_url: "http://192.168.20.230:8123/local/nspanel_us.tft"  # Optional
  # Add-on configuration (if needed)
  # heater_relay: "1"  # Possible values: "1" or "2"

# Customization area
##### My customization - Start #####
##### My customization - End #####

# API. Add api_pwd to your secrets.yaml.
api:
  encryption:
    key: !secret api_encryption_key
    
# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # Optional advanced and add-on configurations
      # - advanced/esphome/nspanel_esphome_advanced.yaml
      # - nspanel_esphome_addon_climate_cool.yaml
      # - nspanel_esphome_addon_climate_heat.yaml
      # - nspanel_esphome_addon_climate_dual.yaml
    refresh: 300s

esp32:
  framework:
    type: esp-idf
```

### ESPHome Logs

I am currently at work and the device is disconnected. I can get it online later if logs are still required for troubleshooting.

### Home Assistant Logs

Im not sure this is going to have the days captured when i was working on this, its been about a week.

[home-assistant_2024-02-27T21-44-00.320Z.log](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/14426074/home-assistant_2024-02-27T21-44-00.320Z.log)
