### ISSUE TITLE
Panel does not connect to the WIFI

### ISSUE THREAD

**Issue by edwardtfn** [Blackymas/NSPanel_HA_Blueprint#1842]
After flash the firmware, the nspanel does not connect to the WIFI at all, Is there any location I can check log or debug? on ESP home wen it says flash complete. the panel now boot into ewelink frontend and does not have any connections at all.

_Originally posted by @vshijiav in https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/1756#discussioncomment-8621043_

**Comment by edwardtfn** [comment]
@vshijiav, could you please share your panel's ESPHome yaml?
Please hide any private info before sharing.

**Comment by vshijiav** [comment]
substitutions:
  # Settings - Editable values
  device_name: "nspanel"
  friendly_name: "test"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  # nextion_update_url: "http://HAip:8123/local/nspanel_eu.tft"  # Optional
  # Add-on configuration (if needed)
  # heater_relay: "1"  # Possible values: "1" or "2"

# Customization area
##### My customization - Start #####
##### My customization - End #####

# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # Optional advanced and add-on configurations
      # - advanced/esphome/nspanel_esphome_advanced.yaml
      # - nspanel_esphome_addon_climate_cool.yaml
      # - nspanel_esphome_addon_climate_heat.yaml
      # - nspanel_esphome_addon_climate_dual.yaml
    refresh: 300s

esp32:
  framework:
    type: esp-idf

I actually didn`t change much...compile without error, flash says complete.

**Comment by vshijiav** [comment]
I kind of figure it out, I created a guest network called test with a simple password and it instantly connect, I tried flash the welcome firmware on web esphome and connect with device hotspot and I see 2 wifi signal with same name(my mesh router network) Is this the reason it does not connect? Any solutions to this?

**Comment by edwardtfn** [comment]
I'm affraid this could be related to some special char used in your password or SSID that are not supported by the substitutions or not in the way we are using those substitutions.
Could you please try these two approaches and let us know if any worked?

## Try 1
```yaml
substitutions:
  # Settings - Editable values
  device_name: "nspanel"
  friendly_name: "test"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  # nextion_update_url: "http://HAip:8123/local/nspanel_eu.tft"  # Optional
  # Add-on configuration (if needed)
  # heater_relay: "1"  # Possible values: "1" or "2"

# Customization area
##### My customization - Start #####
wifi:
  networks: !remove
  ssid: !secret wifi_ssid
  password: !secret wifi_password
##### My customization - End #####

# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # Optional advanced and add-on configurations
      # - advanced/esphome/nspanel_esphome_advanced.yaml
      # - nspanel_esphome_addon_climate_cool.yaml
      # - nspanel_esphome_addon_climate_heat.yaml
      # - nspanel_esphome_addon_climate_dual.yaml
    refresh: 300s

esp32:
  framework:
    type: esp-idf
```

## Try 2
```yaml
substitutions:
  # Settings - Editable values
  device_name: "nspanel"
  friendly_name: "test"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  # nextion_update_url: "http://HAip:8123/local/nspanel_eu.tft"  # Optional
  # Add-on configuration (if needed)
  # heater_relay: "1"  # Possible values: "1" or "2"

# Customization area
##### My customization - Start #####
wifi:
  networks: !remove
  ssid: "!secret wifi_ssid"
  password: "!secret wifi_password"
##### My customization - End #####

# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # Optional advanced and add-on configurations
      # - advanced/esphome/nspanel_esphome_advanced.yaml
      # - nspanel_esphome_addon_climate_cool.yaml
      # - nspanel_esphome_addon_climate_heat.yaml
      # - nspanel_esphome_addon_climate_dual.yaml
    refresh: 300s

esp32:
  framework:
    type: esp-idf
```

**Comment by vshijiav** [comment]
The strange thing is that as long as I connect to the SSID 'test' once, it starts to recognize my old 2.4G SSID. I flashed back old SSID version and now it seems everything works. But it does not show up in ESPhome, but HA instantly picked up the device and everything looks fine. 
BTW is there any way I can flash back to ewelink software? I cant find the original firmware anywhere.

**Comment by edwardtfn** [comment]
> BTW is there any way I can flash back to ewelink software? I cant find the original firmware anywhere.

I've never tried that, but there is: https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/972#issuecomment-1673164989

**Comment by vshijiav** [comment]
![IMG_20240310_111107](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/27871589/6807cd84-2b10-4c37-8b46-0efa3909913e)
After working for some days sadly it stops working, stuck at connect to WIFI...Is there any troubleshooting method to see what is happening with this? I can confirm none of the above works.

**Comment by edwardtfn** [comment]
Can you connect to your panel to get ESPHome logs? If so, please share some here.

**Comment by vshijiav** [comment]
Or is there a way I can set up a hotspot for the panel that I can connect WIFI myself during setup?

**Comment by edwardtfn** [comment]
You can add `captive_portal:` to your panel's yaml, but you will have to connect to your panel to install this anyways. 😞

**Comment by vshijiav** [comment]
> You can add `captive_portal:` to your panel's yaml, but you will have to connect to your panel to install this anyways. 😞

I think I found something, last time when the panel connected to WIFI, the router showing "ESPHOME-WEBXXXX" as device name, but in my yaml file, I named it 'nspanel'. Could this be the problem the ESPHOME never showed it online?

But why the firmware didn`t change the device name? Could this be something related to flashing firmware problem?

**Comment by edwardtfn** [comment]
If ESPHome can't connect to WiFi, it shook ukd expose an wifi fallback AP with your panel's name, but if it is connecting, you shoukd be able to see it's IP on the boot screen in the panel itself, although this picture you shared earlier shows another problem related to ESPHome not connecting to its display also:

![IMG_20240310_111107](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/27871589/6807cd84-2b10-4c37-8b46-0efa3909913e)

So, as I understood, if you go to ESPHome dashboard, it shows the panel offline, right?
What about the integration in Home Assistant? Can you see data from your panel under Settings > Devices and Services > ESPHome? If so, could you please change the baud rate to 115200bps and check if the IP is shown in the boot screen?

**Comment by vshijiav** [comment]
> If ESPHome can't connect to WiFi, it shook ukd expose an wifi fallback AP with your panel's name, but if it is connecting, you shoukd be able to see it's IP on the boot screen in the panel itself, although this picture you shared earlier shows another problem related to ESPHome not connecting to its display also:
> 
> ![IMG_20240310_111107](https://private-user-images.githubusercontent.com/27871589/311786450-6807cd84-2b10-4c37-8b46-0efa3909913e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzNjU5MzcsIm5iZiI6MTcxMDM2NTYzNywicGF0aCI6Ii8yNzg3MTU4OS8zMTE3ODY0NTAtNjgwN2NkODQtMmIxMC00YzM3LThiNDYtMGVmYTM5MDk5MTNlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDIxMzM1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzOGZlZGY2ZjY1ODZkMmZkNzNkMDI1YzE5OTAwYmMwMzc1NmIxODJlMTNlMzg4ODRhYTM4YjY0ODFmM2M5NjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._cXqfD1l56Swzo_qXoUg-BGpaT_2RsYN2HFFod4Gi0A)
> 
> So, as I understood, if you go to ESPHome dashboard, it shows the panel offline, right? What about the integration in Home Assistant? Can you see data from your panel under Settings > Devices and Services > ESPHome? If so, could you please change the baud rate to 115200bps and check if the IP is shown in the boot screen?

When the panel connect to the WIFI, it get instantly picked up by HA integration, but ESPhome shows offline. In router the device name shows "ESPhome-webXXXX" not the name in the yaml file "nspanel"
But right now the panel never connect to the WIFI, and shows the picture above

**Comment by edwardtfn** [comment]
> When the panel connect to the WIFI, it get instantly picked up by HA integration

That means your panel is connected to WiFi.
A long press on the time will bring you to the settings page. From there, a long press on the "Reboot" Text will bring you to the boot page, where you can se the IP.

Do you have HA and your panel in different networks? It could be that you have mDNS issue: https://esphome.io/guides/faq.html#notes-on-disabling-mdns

**Comment by edwardtfn** [comment]
So, the panel is not connecting to Home Assistant then?

Ok.

So, I can only suggest you to flash via serial in this case. 😞

**Comment by vshijiav** [comment]
> So, the panel is not connecting to Home Assistant then?
> 
> Ok.
> 
> So, I can only suggest you to flash via serial in this case. 😞

Okay so I tried on another computer reflash new version, and it connect to home assistant finally.
But still: esphome shows offline
updating TFT to see if everything works fine

**Comment by vshijiav** [comment]
Just flash back and forth again....
Really silly question: Do I have to long press the reset button on the panel before start flash the firmware?
It seems on my computer if I straight plug the panel into USB and start flash, the panel won`t boot and shows the picture above.
I tried long press the reset button before the flash and my FT232 flash got a green light blink once.
Then it seems the firmware got loaded into the nspanel....Not sure if this would help though

**Comment by edwardtfn** [comment]
> Do I have to long press the reset button on the panel before start flash the firmware?

No, that is not needed.


How is your panel's yaml now?

**Comment by vshijiav** [comment]
I tried 3 times using same file to flash. only with long press the button
could get me to a proper boot. If I dont press the button the panel will
just stuck at no ESPHome version like pictures above.

**Comment by edwardtfn** [comment]
Are you connecting IO0 to GND? That should be sufficient to put the board on flashing mode.

What you see in the screen is not very important when you are flashing ESP32. The screen have it's own firmware and will show that image (or anything provided by the TFT previously loaded) when it is powered on.

**Comment by edwardtfn** [comment]
Are you using ESPHome Web for flashing? That should inform you when erasing, flashing and when the transfer is done.

**Comment by vshijiav** [comment]
yes Im using esp web home

And I can see erase loading flash progress during flash, I also have all 5
connector soldered with pin so there wont be any contact issue.
The only difference between button press or not during flash is: If I press
the button, the flash procedure will take about 10 second longer.

**Comment by vshijiav** [comment]
It`s been a week since the fix, so far no problem seen, I have reflash the panel for like 5 times and confirmed only by long press the reset button could flash the panel in my hand. If I do not press the reset button, the flash procedure seems normal on computer screen but it is actually not flashing anything. 
And another strange part is no matter what network configuration in my yaml file (static ip), the panel never appears in ESPhome, but could instantly picked up by homeassistant.
I have no idea whether it is my own panel`s problem or it is being newly manufactured (I bought this from taobao`s sonoff official, I can assume this is a very new version)

**Comment by edwardtfn** [comment]
> no matter what network configuration in my yaml file (static ip)

I don't see the static ip on your yaml. Could you please share that again? It's fine if you hide the IP address, but I wanna know how is my your real settings.
And if you are downloading the TFT file directly from GitHub (not using `nextion_update_url`) and using manual ip, you also must have the dns set in your yaml.

**Comment by edwardtfn** [comment]
Hey @vshijiav, any update to this?

**Comment by vshijiav** [comment]
substitutions:
  # Settings - Editable values
  device_name: "test"
  friendly_name: "test"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  nextion_update_url: "http://homeassistant.local:8123/local/nspanel_eu.tft"  # Optional
  # Add-on configuration (if needed)
  # heater_relay: "1"  # Possible values: "1" or "2"


wifi:
  manual_ip:
        static_ip: ${ip}
        gateway: ${gw}
        subnet: ${subnet}
        dns1: ${dns}

# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Basic package
      # Optional advanced and add-on configurations
      # - esphome/nspanel_esphome_advanced.yaml
      # - nspanel_esphome_addon_climate_cool.yaml
      # - nspanel_esphome_addon_climate_heat.yaml
      # - nspanel_esphome_addon_climate_dual.yaml
    refresh: 300s

esp32:
  framework:
    type: esp-idf


this is my yaml, it still not being recognized by ESPHOME, but could be instantly picked up by homeassistant.

And about the flash, I can confirm if I don`t long press the reset button before flash, it does not flash anything into the panel.(even though the screen shows a progress of flashing). I have tried to flash the sample firmware on ESPWEB, if I don`t press the button, after the flash the panel will straight boot into NSPanel_HA_Blueprint, but if I press the button, the panel will flashed with the sample firmware(boot with a blacked screen with a WIFI hotspot)

**Comment by edwardtfn** [comment]
Please try this:
```yaml
substitutions:
  # Settings - Editable values
  device_name: "test"
  friendly_name: "test"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  nextion_update_url: "http://homeassistant.local:8123/local/nspanel_eu.tft"  # Optional
  # Add-on configuration (if needed)
  # heater_relay: "1"  # Possible values: "1" or "2"

# Customization area
##### My customization - Start #####

# Set IP address manually
wifi:
  networks:
    - id: !extend wifi_default
      manual_ip:
        static_ip: ${ip}
        gateway: ${gw}
        subnet: ${subnet}
        dns1: ${dns}
##### My customization - End #####

# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    refresh: 300s
    files:
      - nspanel_esphome.yaml # Basic package
      # Optional advanced and add-on configurations
      # - esphome/nspanel_esphome_advanced.yaml
      # - nspanel_esphome_addon_climate_cool.yaml
      # - nspanel_esphome_addon_climate_heat.yaml
      # - nspanel_esphome_addon_climate_dual.yaml
```

**Comment by edwardtfn** [comment]
Hey @vshijiav, any update to this?

**Comment by AlainKlarte** [comment]
Hy Guys
For what it's worth, I had the same problem of Panel not connecting to wifi, while I was rather confident in the flashing process.
I had cleaned the "-" and "_" from the ssid name, but it was changing nothing.
When looking at the validation logs, I've seen that my ssid name TPLink1234 was appearing as TPLINK1234 in the logs. I could imagine the ssid was case sensitive, but I'd not imagined that the validation or later compilation would turn the ssid into caps.
When moving my router ssid to caps, the panel immediately and magically appeared on HA.
Seems to me as a little bug. Besides, all my thanks to the incredible community working on HA, with special thanks @edwardtfn and @MarkWattTech.
Hope it may help.
Regards

**Comment by irsl** [comment]
The router of my ISP takes ~10 minutes to boot. After every single electricity outage, NsPanel can't connect to the network, stays offline and I have to restart it manually (after the network is finally stable). Is this a known issue? Any known workarounds?

**Comment by irsl** [comment]
Thank you edwardtfn@ for the hints!

When the device was unable to connect during boot, then it was unavailable until I manually restarted it (via the circuit breaker). Since these settings are supposed to have a sane default, I didn't play with these settings as I didn't see a chance to fix anything.

Instead, since I was on a relatively old version (2023.12 if I recall it correctly), I decided to bump to 2024.6+4.3.9. I will get back to you if I can still repro the issue.

**Comment by anggiaj** [comment]
Getting the same problems, now solved by adding `fast_connect` on wifi section
```
wifi:
  ssid: !secret "wifi_ssid"
  password: !secret "wifi_password"
  fast_connect: yes
```
