### ISSUE TITLE
CUSTOM BUTTONS - light entities that have only the on/off attributes, as simple switches show the extended screen with slider for brightness setting

### ISSUE THREAD

**Issue by Opontios** [Blackymas/NSPanel_HA_Blueprint#1844]
### TFT Version

4.2.6

### ESPHome Version

4.2.6

### Blueprint Version

4.2.6

### Panel Model

EU

### What is the bug?

Although it says that "Entities with supported advanced settings will open it's settings page, all other entities will execute the action or toggle when clicked", the light entities that have only the on/off attributes, as simple switches show the extended screen with slider for brightness setting.

### Your Panel's YAML

```yaml
###### CHANGE ME START ######
  device_name: "nspanel-1"
  friendly_name: "NSPanel 1" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  #nextion_update_url: "http://homeassistant.local:8123/local/nspanel_eu.tft"
  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft"

   ### Local thermostat defaults ###
  # https://esphome.io/components/climate/thermostat.html
  temp_units: "°C"
  heater_relay: "1" # Select 1 for "Relay 1", 2 for "Relay 2" or "0" to a dummy switch/disabled
  min_off_time: "10"
  min_run_time: "10"
  min_idle_time: "10"
  # https://esphome.io/components/climate/index.html#base-climate-configuration
  temp_min: "5"
  temp_max: "30"
  temp_step: "0.5"

  ##### DO NOT CHANGE THIS #####
  # addon_climate_cool: "false"
  # addon_climate_heat: "true"
  ##############################
  # addon_climate_heater_relay: "1" # possible values: 1/2

  # Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # Optional advanced and add-on configurations
      # - advanced/esphome/nspanel_esphome_advanced.yaml
      # - nspanel_esphome_addon_climate_cool.yaml
      - nspanel_esphome_addon_climate_heat.yaml
      # - nspanel_esphome_addon_climate_dual.yaml
    refresh: 300s

esp32:
  framework:
    type: esp-idf

# Custom web server credentials
web_server:
  auth:
    username: !secret web_server_username
    password: !secret web_server_password

api:
  encryption:
    key: !secret api_encryption_key
```

### Home Assistant Logs

Nothing related in the logs
