### ISSUE TITLE
`Bug` Panel only showing red Homeassistant Icon

### ISSUE THREAD

**Issue by martpp** [Blackymas/NSPanel_HA_Blueprint#1847]
### TFT Version

4.2.6

### ESPHome Version

2024.2.1

### Blueprint Version

4.2.6

### Panel Model

EU

### What is the bug?

Panel Display only showing red Homeassitant Icon. The Buttons are working as specified in the Blueprint but the rest of the Config is not applied properly, i guess.

### Steps to Reproduce

Here is a picture how it looks: 
![20240301_112253](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/39768432/2c8b3578-8677-4519-a167-d0c3c221d7b5)
https://imgur.com/a/8eHNUlW

### Your Panel's YAML

```yaml
substitutions:
  # Settings - Editable values
  device_name: "szpanel"
  friendly_name: "SchlafzimmerPanel"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  nextion_update_url: "http://192.168.42.14:8123/local/nspanel_eu.tft"  # Optional
  # Add-on configuration (if needed)
  # heater_relay: "1"  # Possible values: "1" or "2"

# Customization area
##### My customization - Start #####
##### My customization - End #####

# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # Optional advanced and add-on configurations
      # - advanced/esphome/nspanel_esphome_advanced.yaml
      # - nspanel_esphome_addon_climate_cool.yaml
      # - nspanel_esphome_addon_climate_heat.yaml
      # - nspanel_esphome_addon_climate_dual.yaml
    refresh: 300s

esp32:
  framework:
    type: esp-idf
```
