### ISSUE TITLE
NSPanel Configuration is using an unknown service

### ISSUE THREAD

**Issue by MrAshen** [Blackymas/NSPanel_HA_Blueprint#1850]
### TFT Version

4.2.6

### ESPHome Version

4.2.6

### Blueprint Version

4.2.6

### Panel Model

EU

### What is the bug?

esphome page_home and send_command_text_printf services are unknwon

### Steps to Reproduce

Create automation with blueprint NSPanel Configuration, save and restart the NS Panel. 
![Screenshot_20221124_213318](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/104657242/18552efa-112a-4fda-9221-049c120ab2f7)

### Your Panel's YAML

```yaml
substitutions:
  # Settings - Editable values
  device_name: "nspanelog"
  friendly_name: "Sonoff NSPanel OG"
  wifi_ssid: !secret "wifi_ssid"
  wifi_password: !secret "wifi_password"
  nextion_update_url: "http://homeassistant.local:8123/local/nspanel_eu.tft"  # Optional
  # Add-on configuration (if needed)
  heater_relay: "1"  # Possible values: "1" or "2"

# Customization area
##### My customization - Start #####
##### My customization - End #####

# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # Optional advanced and add-on configurations
      # - advanced/esphome/nspanel_esphome_advanced.yaml
      # - nspanel_esphome_addon_climate_cool.yaml
      # - nspanel_esphome_addon_climate_heat.yaml
      # - nspanel_esphome_addon_climate_dual.yaml
    refresh: 300s

esp32:
  framework:
    type: esp-idf
```

### ESPHome Logs

[logs_nspanelog_logs (1).txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/14470336/logs_nspanelog_logs.1.txt)

### Home Assistant Logs

[home-assistant_2024-03-02T18-05-50.532Z.log](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/14470334/home-assistant_2024-03-02T18-05-50.532Z.log)
