### ISSUE TITLE
`Bug` NSPanel does not work properly if the panel is in another network than HA

### ISSUE THREAD

**Issue by Mercy-64** [Blackymas/NSPanel_HA_Blueprint#1856]
### TFT Version

4.2.6

### ESPHome Version

4.2.6 (2024.2.1)

### Blueprint Version

4.2.6

### Panel Model

EU

### What is the bug?

I have two NSPanel, installed with same scripts, only the Name has changed. This white NSPanel is in the same network like HA (10.1.1.xx), the black NSPanel is in IoT network (10.1.50.xx). Both NSPanel has the same configuration and the white Panel is working fine, on the black Panel the Icons on Climate page is missing and I have no access to Log File on black NSPanel, it looks like communication is not working to 100%. On Home Page from black Panel i can see Temp outside, Date and Time and the temperature of a external sensor.

### Steps to Reproduce

1. Go to Homebutton*
2. click to temperature icon
3. see missing icons etc in Climate
4. go to ESPHome and click LOGS on Panel
5. use wireless
6. Logfile window ia opening
7. Get an error -> WARNING: Can't connect to ESPHome API for nspanel-dj-black.local: Error resolving IP address: [Errno -5] No address associated with hostname (APIConnectionError)
8. i can ping the NSPanel from network 10.1.1.xx) via cmd from Windows machine and can ping this black Panel from HA Terminal (10.1.1.xx)
9. Connection from 10.1.1.xx to 10.1.50.xx is working fine with all other IoT Devices (10.1.50.xx) in HA

### Your Panel's YAML

```yaml
# generischer Thermostat für Fußbodenheizung
climate:
# black NSPanel
  - platform: generic_thermostat
    name: DJ Heizung black
    heater: switch.nspanel_dj_black_relay_2
    target_sensor: sensor.dj_oase_temperatur_temperatur    
    min_temp: 15
    max_temp: 29
    ac_mode: false
    target_temp: 24
    cold_tolerance: 0.3
    hot_tolerance: 0
    min_cycle_duration:
      seconds: 5
    keep_alive:
      minutes: 3
    initial_hvac_mode: "heat"
    away_temp: 16
    precision: 0.1
    
# white NSPanel
  - platform: generic_thermostat
    name: DJ Heizung white
    heater: switch.nspanel_dj_white_relay_2
    target_sensor: sensor.dj_oase_temperatur_temperatur    
    min_temp: 15
    max_temp: 29
    ac_mode: false
    target_temp: 24
    cold_tolerance: 0.3
    hot_tolerance: 0
    min_cycle_duration:
      seconds: 5
    keep_alive:
      minutes: 3
    initial_hvac_mode: "heat"
    away_temp: 16
    precision: 0.1
```
