### ISSUE TITLE
How is the „Climate Control“ is working?

### ISSUE THREAD

**Issue by T3mplate-wow** [Blackymas/NSPanel_HA_Blueprint#186]
Hey,
after several hours I was able to flash the NSPanel. Weather is not working at the moment, but I will fix this and I am happy with everything you made here!

What I was wondering is, how is the Climate Control working?
I’ve configured a virtuel thermostat, based on other Issues:
```
climate:
  - platform: generic_thermostat
    unique_id: aa09776c-f063-4a8c-b969-647ee2c42551
    name: Thermostat Mia
    heater: switch.shellyheizungkinderzimmer_switch_0
    target_sensor: sensor.miapanel_temperature
    min_temp: 15
    max_temp: 25
    ac_mode: false
    target_temp: 21
    cold_tolerance: 0.5
    hot_tolerance: 0.5
    min_cycle_duration:
      seconds: 240
```

I use a floor heating and the actuator only knows on or off. This is handled by a shelly. So shelly on -> heating. shelly off -> no heating.

With my configuration the NSPanel uses this virtual thermostat to on/off the shelly. The current temperature comes from the NSPanel itself.
I tested different values and it looks like, that this is working correctly. 

My questions are:
* which one of the values of the virtual thermostat are being used? I’ve read in [137](https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/137) that the min and max values are being ignored. Also the targed temperature isn’t changing. What is about the tolerance and the min cycle duration? I believe it is important that a floor heating isn’t switching on and off all the time.
* In the evening the hole house heating system is off. So after a while there is no more warm water inside the pipes and because of this the rooms are getting colder. This means that the NSPanel will tell the shelly to switch to on. right? Because it is getting colder than defined. My problem is that the floor heating actuators take 4Watts all night for nothing (because there is just cold water inside). Am I right? Is there any chance to mitigate this?
