### ISSUE TITLE
`Bug` Offline mode not working properly

### ISSUE THREAD

**Issue by tarasglek** [Blackymas/NSPanel_HA_Blueprint#1861]
### Enhancement Summary

Would like to have NSPanel retain functionality when offline and/or allow complete configuration without blueprint

### Detailed Description

I would like my nspanel to work as a dumb offline thermostat + bonus online functionality.

Ideally for me I'd just specify all the blueprint stuff in the yaml for the panel, so it's completely independent from HA for functionality and HA is only used to override temperature setting on thermostat when needed.

It's not great that when nspanel reboots and home-assistant is down (or on another network), the UI is mostly blank and appears not functional.

It's really great that we can control the relay via termostat function in esphome 100% without network access. 
Would love to be able to extend these settings to be able to flash-and-forget these as thermostats.

In my case I also made the buttons adjust thermostat temperature and added a sensor to show current thermostat setting. I had to add the sensor to homescreen via blueprint. 

```yaml
binary_sensor:
  - id: !extend left_button
    on_multi_click:
      - timing:
          - ON for at most 0.8s
        then:
        - lambda: |-
            id(thermostat_embedded).target_temperature -= 1;
            id(target_temp_sensor).publish_state(id(thermostat_embedded).target_temperature);
  - id: !extend right_button
    on_multi_click:
      - timing:
          - ON for at most 0.8s
        then:
        - lambda: |-
            id(thermostat_embedded).target_temperature += 1;
            id(target_temp_sensor).publish_state(id(thermostat_embedded).target_temperature);
sensor:
  - platform: template
    id: target_temp_sensor
    name: "target_temp_sensor"
    unit_of_measurement: °C
    lambda: |-
      return id(thermostat_embedded).target_temperature;
```

**Comment by edwardtfn** [comment]
You can fully control the thermostat from the panel when the network is available.

In fact, after the panel first receive it's settings from the blueprint, only the resources from Home Assistant won't be available, but displaying temperature, time and controlling the climate are all there.
What else are you missing and that is not dependent of info from Home Assistant?

**Comment by tarasglek** [comment]
If the panel is rebooted it looses all settings it received via blueprint

**Comment by tarasglek** [comment]
4.2.6

https://youtube.com/shorts/G_GTG5YkJhQ?si=gPLo_6r9PXBLeuxJ when i turn home assistant off

with home assistant online:
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/857083/12c4437b-3d62-4089-8365-95bd50c4133a)

**Comment by tarasglek** [comment]
Would be great to get it to work as you describe. 

```yaml
substitutions:
# Settings - Editable values
device_name: "nspanel1"
# friendly_name: "nspanel1"
wifi_ssid: !secret wifi_ssid
wifi_password: !secret wifi_password
nextion_update_url: http://192.168.33.154/nspanel_eu.tft
# Add-on configuration (if needed)
heater_relay: "1"     # Possible values: "1" or "2"
# temp_units: "°C"      # Temperatures in Fahrenheit
temp_min: "12"        # Min supported temperature is 40°F
temp_max: "25"        # Max supported temperature is 80°F
temp_step: "1"        # Temperature granularity is 1°F
heat_deadband: "1.2"  # Temperature delta before engaging heat
heat_overrun: "1.2"   # Temperature delta before disengaging heat

# Customization area
##### My customization - Start #####
##### My customization - End #####

# Core and optional configurations
packages:
remote_package:
  url: https://github.com/Blackymas/NSPanel_HA_Blueprint
  ref: main
  files:
    - nspanel_esphome.yaml # Core package
    # Optional advanced and add-on configurations
    # - advanced/esphome/nspanel_esphome_advanced.yaml
    # - nspanel_esphome_addon_climate_cool.yaml
    - nspanel_esphome_addon_climate_heat.yaml
    # - nspanel_esphome_addon_climate_dual.yaml
  refresh: 300s

web_server:
port: 80

esp32:
framework:
  # type: esp-idf
  type: arduino

binary_sensor:
- id: !extend left_button
  on_multi_click:
    - timing:
        - ON for at most 0.8s
      then:
      - lambda: |-
          id(thermostat_embedded).target_temperature -= 1;
          id(target_temp_sensor).publish_state(id(thermostat_embedded).target_temperature);
- id: !extend right_button
  on_multi_click:
    - timing:
        - ON for at most 0.8s
      then:
      - lambda: |-
          id(thermostat_embedded).target_temperature += 1;
          id(target_temp_sensor).publish_state(id(thermostat_embedded).target_temperature);
sensor:
- platform: template
  id: target_temp_sensor
  name: "target_temp_sensor"
  unit_of_measurement: °C
  lambda: |-
    return id(thermostat_embedded).target_temperature;
```
