### ISSUE TITLE
`Bug` `Dev` Dual set point heater broken 

### ISSUE THREAD

**Issue by Floppe** [Blackymas/NSPanel_HA_Blueprint#1862]
### TFT Version

4.3dev2

### ESPHome Version

4.3dev2

### Blueprint Version

4.3dev2

### Panel Model

EU

### What is the bug?

Climate page with dual setpoints not showing anything

### Steps to Reproduce

Feature #909 does not work anymore.

### Your Panel's YAML

```yaml
hvac_modes:
  - "off"
  - auto
min_temp: 35
max_temp: 60
target_temp_step: 1
current_temperature: 58.5
target_temp_high: 60
target_temp_low: 45
hvac_action: idle
friendly_name: Tap water
supported_features: 386
```

### Home Assistant Logs

Logger: homeassistant.helpers.template
Source: helpers/template.py:2345
First occurred: March 5, 2024 at 20:12:23 (2 occurrences)
Last logged: 15:13:42

Template variable error: 'dict object' has no attribute 'pages' when rendering '{{ nspanel.service.pages.climate }}'
