### ISSUE TITLE
`Bug` Error time calculation for 'America/Santiago' Timezone

### ISSUE THREAD

**Issue by jsanmart666** [Blackymas/NSPanel_HA_Blueprint#1863]
### TFT Version

4.2.6

### ESPHome Version

4.2.6

### Blueprint Version

4.2.6

### Panel Model

EU

### What is the bug?

Shown time is wrong for 'America/Santiago' timezone and others

### Steps to Reproduce

'America/Santiago' timezone have -3.0 value. Now is 10:52 in Santiago but panel shows 17:52, UTC 13:52

I tried other negative value timezones and shows same issue.

(My guess is an error in calculate the time because "-" sign and add 3 instead substract)

Thank you

### Your Panel's YAML

```yaml
substitutions:

###### CHANGE ME START ######

  device_name: "nssalita"
  friendly_name: "nssalita" 
  wifi_ssid: *********
  wifi_password: ********

  nextion_update_url: "https://192.168.5.165:8123/local/nspanelus.tft" # URL to local tft File

time:
  - id: !extend time_provider
    timezone: "America/Argentina/Buenos_Aires"

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # Optional advanced and add-on configurations
      # - advanced/esphome/nspanel_esphome_advanced.yaml
      # - nspanel_esphome_addon_climate_cool.yaml
      # - nspanel_esphome_addon_climate_heat.yaml
      # - nspanel_esphome_addon_climate_dual.yaml
    refresh: 300s

esp32:
  framework:
    type: esp-idf
```
