### ISSUE TITLE
`Bug` [Dev4.3] QR-Code / climate chip's thermometer symbol disappears

### ISSUE THREAD

**Issue by kroessig** [Blackymas/NSPanel_HA_Blueprint#1869]
### TFT Version

4.3dev3

### ESPHome Version

4.3dev4

### Blueprint Version

4.3dev4

### Panel Model

EU

### What is the bug?

QR-Code / climate chip's thermometer symbol disappears

### Steps to Reproduce

I just installed the dev version according to the instructions here: [Link](https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/docs/different_version.md)

The following problems occurred after successful installation:
- my QR code symbol does appear after saving the configuration As soon as I open the QR code or select a different page, it disappears.
- also the climate chip's thermometer symbol disappears. It appears briefly by open the home page and then disappears again very quickly. Previously the thermometer was gray when it was inactive, now it seems to be completely gone...

[Video](https://photos.app.goo.gl/rRdKndZZYWPt3zyH9)

### Your Panel's YAML

```yaml
substitutions:

###### CHANGE ME START ######

  device_name: "panelwozi"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

#  nextion_update_url: "http://192.168.178.75:8123/local/nspanel_eu_dev4.2.tft" # URL to local tft File
#  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft" # URL to Github

##### CHANGE ME END #####



##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: dev
    files: [nspanel_esphome.yaml]
    refresh: 300s
#esp32:
#  framework:
#    type: esp-idf  

##### DO NOT CHANGE ANYTHING! #####
```

### ESPHome Logs

[15:10:51][D][sensor:094]: 'RSSI': Sending state -55.00000 dBm with 0 decimals of accuracy
[15:11:03][D][nextion:446]: Got touch event:
[15:11:03][D][nextion:447]:   page_id:      0
[15:11:03][D][nextion:448]:   component_id: 30
[15:11:03][D][nextion:449]:   event type:   PRESS
[15:11:03][D][script.timer_dim:2809]: Waking up on page: home
[15:11:03][D][sensor:094]: 'Display Current brightness': Sending state 25.00000 % with 0 decimals of accuracy
[15:11:03][D][nextion:446]: Got touch event:
[15:11:03][D][nextion:447]:   page_id:      0
[15:11:03][D][nextion:448]:   component_id: 30
[15:11:03][D][nextion:449]:   event type:   RELEASE
[15:11:03][D][script:077]: Script 'timer_dim' restarting (mode: restart)
[15:11:03][D][script.timer_dim:2809]: Waking up on page: home
[15:11:03][D][script:077]: Script 'set_brightness' restarting (mode: restart)
[15:11:03][D][nextion:464]: Got new page: 18
[15:11:03][D][text_sensor:064]: 'Current Page': Sending state 'entitypage01'
[15:11:03][D][text_sensor:064]: 'Detailed Entity': Sending state ''
[15:11:03][D][script.page_changed:2109]: New page: entitypage01
[15:11:03][D][script:077]: Script 'timer_dim' restarting (mode: restart)
[15:11:03][D][script.timer_dim:2809]: Waking up on page: entitypage01
[15:11:03][D][script:077]: Script 'set_brightness' restarting (mode: restart)
[15:11:03][D][sensor:094]: 'Display Current brightness': Sending state 30.00000 % with 0 decimals of accuracy
[15:11:03][D][sensor:094]: 'Page Id': Sending state 18.00000  with 0 decimals of accuracy
[15:11:03][D][sensor:094]: 'Display Current brightness': Sending state 30.00000 % with 0 decimals of accuracy
[15:11:05][D][nextion:446]: Got touch event:
[15:11:05][D][nextion:447]:   page_id:      18
[15:11:05][D][nextion:448]:   component_id: 28
[15:11:05][D][nextion:449]:   event type:   PRESS
[15:11:05][D][script:077]: Script 'timer_page' restarting (mode: restart)
[15:11:05][D][script:077]: Script 'timer_dim' restarting (mode: restart)
[15:11:05][D][nextion:464]: Got new page: 0
[15:11:05][D][text_sensor:064]: 'Current Page': Sending state 'home'
[15:11:05][D][text_sensor:064]: 'Detailed Entity': Sending state ''
[15:11:05][D][script.page_changed:2109]: New page: home
[15:11:05][D][script:077]: Script 'timer_page' restarting (mode: restart)
[15:11:05][D][script:077]: Script 'timer_dim' restarting (mode: restart)
[15:11:05][D][sensor:094]: 'Page Id': Sending state 0.00000  with 0 decimals of accuracy
[15:11:06][W][nextion:405]: Nextion reported variable name invalid!
[15:11:06][W][nextion:405]: Nextion reported variable name invalid!
[15:11:06][W][nextion:405]: Nextion reported variable name invalid!
[15:11:06][W][nextion:405]: Nextion reported variable name invalid!
[15:11:06][W][nextion:405]: Nextion reported variable name invalid!
[15:11:06][W][nextion:405]: Nextion reported variable name invalid!
[15:11:06][W][nextion:405]: Nextion reported variable name invalid!
[15:11:06][W][nextion:405]: Nextion reported variable name invalid!
[15:11:06][W][nextion:405]: Nextion reported variable name invalid!
[15:11:06][W][nextion:405]: Nextion reported variable name invalid!
[15:11:06][W][nextion:405]: Nextion reported variable name invalid!
[15:11:06][W][nextion:405]: Nextion reported variable name invalid!
[15:11:06][W][nextion:405]: Nextion reported variable name invalid!
[15:11:06][W][nextion:405]: Nextion reported variable name invalid!
[15:11:06][W][nextion:405]: Nextion reported variable name invalid!
[15:11:08][D][sensor:094]: 'Display Current brightness': Sending state 100.00000 % with 0 decimals of accuracy
[15:11:35][D][sensor:094]: 'Display Current brightness': Sending state 25.00000 % with 0 decimals of accuracy
[15:11:40][D][sensor:094]: 'ntc_source': Sending state 1.60900 V with 2 decimals of accuracy
[15:11:40][D][resistance:039]: 'resistance_sensor' - Resistance 10656.9Ω
[15:11:40][D][sensor:094]: 'resistance_sensor': Sending state 10656.88965 Ω with 1 decimals of accuracy
[15:11:40][D][ntc:026]: 'Temperature' - Temperature: 23.6°C
[15:11:40][D][sensor:094]: 'Temperature': Sending state 23.57506 °C with 1 decimals of accuracy
[15:11:40][D][sensor:094]: 'Display Current brightness': Sending state 25.00000 % with 0 decimals of accuracy
