### ISSUE TITLE
`Bug` fan oscillate button not working

### ISSUE THREAD

**Issue by shing6326** [Blackymas/NSPanel_HA_Blueprint#1873]
### TFT Version

4.3dev4

### ESPHome Version

4.3dev4

### Blueprint Version

4.3dev4

### Panel Model

EU

### What is the bug?

fan oscillate button not working

### Steps to Reproduce

1. go to button page
2. click the fan entity which has the oscillate function
3. press the bt_oscillate
4. the icon turns blue but no effect

### Your Panel's YAML

```yaml
I suspect the error may comes from esphome/nspanel_esphome_core.yaml line 880, the detailed_entity->state.c_str() returns the panel id instead of my fan's entity id. I tried to troubleshoot it but seems I do not have enough skills to fix it :).

            case 22:  // fan
              switch (component_id) {
                case 17:  // bt_oscillate
                  if (!touch_event) {  // Release
                    ha_call_service->execute("fan.oscillate", "", "", detailed_entity->state.c_str());
                  }
                  break;
              }
          }




My Panel's YAML
substitutions:
  # Settings - Editable values
  device_name: "sg_panel"
  friendly_name: "SG Panel"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  api_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/dev/advanced/hmi/nspanel_CJK_eu.tft"
  # Add-on configuration (if needed)
  # heater_relay: "1"  # Possible values: "1" or "2"

# Customization area
##### My customization - Start #####
api:
  encryption:
    key: ${api_key}

logger:

ota:
  password: !secret ota_password

wifi:
  use_address: 10.186.9.115

time:
  - id: !extend time_provider
    platform: sntp
    timezone: SGT-8

##### My customization - End #####

# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: dev
    files:
      - nspanel_esphome.yaml # Core package
      # Optional advanced and add-on configurations
      # - advanced/esphome/nspanel_esphome_advanced.yaml
      # - nspanel_esphome_addon_climate_cool.yaml
      # - nspanel_esphome_addon_climate_heat.yaml
      # - nspanel_esphome_addon_climate_dual.yaml
    refresh: 0s

esp32:
  framework:
    type: esp-idf
```

### ESPHome Logs

no logs during the key press

### Home Assistant Logs

Logger: homeassistant.components.automation.sg_nspanel
Source: components/automation/__init__.py:687
integration: Automation ([documentation](https://www.home-assistant.io/integrations/automation), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+automation%22))
First occurred: 1:54:32 AM (9 occurrences)
Last logged: 1:54:38 AM

Error while executing automation automation.sg_nspanel: required key not provided @ data['oscillating']

**Comment by shing6326** [comment]
this is the attributes of my fan
```
preset_modes: 
oscillating: false
percentage: 25
percentage_step: 25
preset_mode: 
friendly_name: Lemo FW2 1c21ab 
supported_features: 3
```

**Comment by edwardtfn** [comment]
On the device's page under Settings > Devices & Services > ESPHome, there's a sensor named "**Detailed Entity**". What do you see on that sensor when the fan page is open with the entity where you want to control the oscillating?

Also, could you please, with that page open, go to Developer Tools, select the tab "Template" and paste the following, then let me know the results when the page fan is open with that same entity?

```yaml
{% set entity_id = states("sensor.sg_panel_detailed_entity") %}
entity_id: {{ entity_id }}
oscillating: {{ state_attr(entity_id, "oscillating") }} / {{ state_attr(entity_id, "oscillating") | default("true") }}
new oscillating: {{ not (state_attr(entity_id, "oscillating") | default("true")) }}
```
