### ISSUE TITLE
`Bug` Dev 4.3   Confirm Message does not work

### ISSUE THREAD

**Issue by kroessig** [Blackymas/NSPanel_HA_Blueprint#1880]
### TFT Version

4.3dev4

### ESPHome Version

4.3dev4

### Blueprint Version

4.3dev4

### Panel Model

EU

### What is the bug?

Confirm Message does not work

### Steps to Reproduce

Automatisation with esphome.[panelname]_notification_show
confirm notification does not work - see video [Link](https://photos.app.goo.gl/HAf4X62wJ2rLkih48)

there are errors in the esp-home log

### Your Panel's YAML

```yaml
substitutions:

###### CHANGE ME START ######

  device_name: "panelwozi"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

#  nextion_update_url: "http://192.168.178.75:8123/local/nspanel_eu_dev4.2.tft" # URL to local tft File
#  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft" # URL to Github

##### CHANGE ME END #####



##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: dev
    files: [nspanel_esphome.yaml]
    refresh: 300s
#esp32:
#  framework:
#    type: esp-idf  

##### DO NOT CHANGE ANYTHING! #####
```

### ESPHome Logs

[19:55:23][D][sensor:094]: 'Temperature': Sending state 24.25278 °C with 1 decimals of accuracy
[19:55:29][D][sensor:094]: 'RSSI': Sending state -55.00000 dBm with 0 decimals of accuracy
[19:55:56][D][nextion:446]: Got touch event:
[19:55:56][D][nextion:447]:   page_id:      0
[19:55:56][D][nextion:448]:   component_id: 28
[19:55:56][D][nextion:449]:   event type:   PRESS
[19:55:56][D][script.timer_dim:2809]: Waking up on page: home
[19:55:56][E][nextion:550]: ERROR: Received numeric return but next in queue "send_command_printf" is not a valid sensor type 0
[19:55:56][D][nextion:446]: Got touch event:
[19:55:56][D][nextion:447]:   page_id:      0
[19:55:56][D][nextion:448]:   component_id: 28
[19:55:56][D][nextion:449]:   event type:   RELEASE
[19:55:56][D][script:077]: Script 'timer_dim' restarting (mode: restart)
[19:55:56][D][script.timer_dim:2809]: Waking up on page: home
[19:55:56][D][script:077]: Script 'set_brightness' restarting (mode: restart)
[19:55:56][D][nextion:464]: Got new page: 16
[19:55:56][D][text_sensor:064]: 'Current Page': Sending state 'notification'
[19:55:56][D][text_sensor:064]: 'Detailed Entity': Sending state ''
[19:55:56][D][script.page_changed:2109]: New page: notification
[19:55:56][D][script:077]: Script 'timer_dim' restarting (mode: restart)
[19:55:56][D][script.timer_dim:2809]: Waking up on page: notification
[19:55:56][D][script:077]: Script 'set_brightness' restarting (mode: restart)
[19:55:56][E][nextion:550]: ERROR: Received numeric return but next in queue "send_command_printf" is not a valid sensor type 0
[19:55:56][D][sensor:094]: 'Display Current brightness': Sending state 16.00000 % with 0 decimals of accuracy
[19:55:56][E][nextion:550]: ERROR: Received numeric return but next in queue "send_command_printf" is not a valid sensor type 0
[19:55:58][D][nextion:446]: Got touch event:
[19:55:58][D][nextion:447]:   page_id:      16
[19:55:58][D][nextion:448]:   component_id: 7
[19:55:58][D][nextion:449]:   event type:   PRESS
[19:55:58][D][script:077]: Script 'timer_dim' restarting (mode: restart)
[19:55:58][D][script.timer_dim:2809]: Waking up on page: notification
[19:55:58][D][script:077]: Script 'set_brightness' restarting (mode: restart)
[19:55:58][E][nextion:550]: ERROR: Received numeric return but next in queue "send_command_printf" is not a valid sensor type 0
[19:55:58][D][nextion:446]: Got touch event:
[19:55:58][D][nextion:447]:   page_id:      16
[19:55:58][D][nextion:448]:   component_id: 7
[19:55:58][D][nextion:449]:   event type:   RELEASE
[19:55:58][D][script:077]: Script 'timer_dim' restarting (mode: restart)
[19:55:58][D][script.timer_dim:2809]: Waking up on page: notification
[19:55:58][D][script:077]: Script 'set_brightness' restarting (mode: restart)
[19:55:58][D][text_sensor:064]: 'NSPanel event': Sending state '{"page": "notification", "component": "accept", "value": "release"}'
[19:55:58][E][text_sensor.nspanelevent:1648]: Obsolete call
[19:55:58][D][script:077]: Script 'timer_dim' restarting (mode: restart)
[19:55:58][D][script.timer_dim:2809]: Waking up on page: notification
[19:55:58][D][script:077]: Script 'set_brightness' restarting (mode: restart)
[19:55:58][E][text_sensor.nspanelevent:1665]:   Page:      notification
[19:55:58][E][text_sensor.nspanelevent:1666]:   Component: accept
[19:55:58][E][text_sensor.nspanelevent:1667]:   Value:     release
[19:55:58][E][text_sensor.nspanelevent:1668]:   Entity:    
[19:55:58][D][nextion_textsensor:014]: Processed text_sensor "nspanelevent" state "{"page": "notification", "component": "accept", "value": "release"}"
[19:55:58][E][nextion:550]: ERROR: Received numeric return but next in queue "send_command_printf" is not a valid sensor type 0
[19:55:58][E][nextion:550]: ERROR: Received numeric return but next in queue "send_command_printf" is not a valid sensor type 0
[19:55:59][D][switch:016]: 'Notification unread' Turning OFF.
[19:55:59][D][nextion:464]: Got new page: 0
[19:55:59][D][text_sensor:064]: 'Current Page': Sending state 'home'
[19:55:59][D][text_sensor:064]: 'Detailed Entity': Sending state ''
[19:55:59][D][script.page_changed:2109]: New page: home
[19:55:59][D][script:077]: Script 'timer_dim' restarting (mode: restart)
[19:55:59][D][script.timer_dim:2809]: Waking up on page: home
[19:55:59][D][script:077]: Script 'set_brightness' restarting (mode: restart)
[19:55:59][E][nextion:550]: ERROR: Received numeric return but next in queue "send_command_printf" is not a valid sensor type 0
[19:55:59][E][nextion:550]: ERROR: Received numeric return but next in queue "send_command_printf" is not a valid sensor type 0
[19:56:04][E][nextion:550]: ERROR: Received numeric return but next in queue "fill_area" is not a valid sensor type 0
