### ISSUE TITLE
`Bug` Beta 4.3.0b2 notification time out

### ISSUE THREAD

**Issue by bkbartk** [Blackymas/NSPanel_HA_Blueprint#1881]
### TFT Version

4.3.0b2

### ESPHome Version

4.3.0b2

### Blueprint Version

4.3.0b2

### Panel Model

EU

### What is the bug?

(can this become a multiline field?)notification page doesn't close and I can't find anything about it in breaking changes.

### Steps to Reproduce

run this service
```
service: esphome.lamp_kamer_voor_notification_show
data:
  label: test
  message: test

```
and wait for the period in page-timeout,
the notification is still there,  even if you clear it afterwards.

I guess it would also be ok if there is a way to go back to the home page or close the message.
unfortunately I can't find the service for that either.
