### ISSUE TITLE
After the NSPANEL restart, it does not connect to WiFi.`Bug` 

### ISSUE THREAD

**Issue by KoKolaj** [Blackymas/NSPanel_HA_Blueprint#1896]
### TFT Version

4.3

### ESPHome Version

4.3

### Blueprint Version

4.3

### Panel Model

EU

### What is the bug?

After the NSPANEL restart, it does not connect to WiFi.
I noticed that after the restart, when the panel triggers, it reports the ESPHOME 4.2.6 version.
Immediately afterwards, he will not join WiFi.
I have to record Yaml again, and then the panel reports the right version of ESPHOME 4.3. And it will join WiFi.
But if I restart the panel again, it is repeated.
The panel again shows version 4.2.6 at the start
WiFi will not join again ...
This error is the same for all panels I own.
3x EU panel and 1x Us panel ...

### Your Panel's YAML

```yaml
substitutions:

###### CHANGE ME START ######

 device_name: "nspanel_room"
 wifi_ssid: !secret wifi_ssid
 wifi_password: !secret wifi_password

 nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft" # URL to Github

##### CHANGE ME END #####



##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####
```
