### ISSUE TITLE
rttl service broken after upgrade to 4.3.0

### ISSUE THREAD

**Issue by rbr101** [Blackymas/NSPanel_HA_Blueprint#1901]
### TFT Version

4.3.0

### ESPHome Version

4.3.0

### Blueprint Version

4.3.0

### Panel Model

EU

### What is the bug?

The RTTL service was changed, but does not work anymore in version 4.3.0
As per documentation:
```
service: esphome.<your_panel_name>_rtttl_play
data:
  tone: "d=4,o=5,b=140:c,e,g,8p,c6,e6,g6,8p,c7,p"
```

Does not work, the logs show:
```
[09:28:31][D][rtttl:051]: Playing song d=4,o=5,b=140
[09:28:31][E][rtttl:056]: Missing 'd='
```

Before 4.3.0  i was using :
```
{
    "song_str": ">- smb:d=4,o=5,b=100:16e6,16e6,32p,8e6,16c6,8e6,8g6,8p,8g,8p,8c6,16p,8g,16p,8e,16p,8a,8b,16a#,8a,16g.,16e6,16g6,8a6,16f6,8g6,8e6,16c6,16d"
}
```

I use this for specific timers , for example a timer for toothbrush time for my kids.

/R

### Steps to Reproduce

```
Execute the rttl service in homeassistant
```

### ESPHome Logs

```
[09:28:31][D][rtttl:051]: Playing song d=4,o=5,b=140
[09:28:31][E][rtttl:056]: Missing 'd='
```

**Comment by edwardtfn** [comment]
🤔
Which version are you coming from?
I will have to investigate this, as the change was only on naming:
### v4.2
```yaml
    ##### Service to play a rtttl tones #####
    # Example tones : https://codebender.cc/sketch:109888#RTTTL%20Songs.ino
    - service: play_rtttl
      variables:
        song_str: string
      then:
        - rtttl.play:
            rtttl: !lambda 'return song_str;'
```
### v4.3
```yaml
    # Plays melodies encoded in RTTTL format, suitable for audio feedback, notifications, or simple tunes.
    - service: rtttl_play
      variables:
        tone: string  # The RTTTL string for the melody to be played. It should follow the RTTTL format, including the melody's name, default settings, and a sequence of notes.
      then:
        - rtttl.play:
            rtttl: !lambda 'return tone;'
```
