### ISSUE TITLE
`Bug` Old properties still showing up on NSPanel device after many upgrades

### ISSUE THREAD

**Issue by robsonfelix** [Blackymas/NSPanel_HA_Blueprint#1905]
### Panel Model

US

### What is the bug?

Old properties are still showing up after many upgrades.
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/9100568/51a5fce4-89cc-43e8-9d92-1f83d7ea2ee5)
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/9100568/4f7c241e-bb2b-428f-a49f-14b0590c9656)
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/9100568/ba55b228-6ce0-444d-a0f1-6f39d9c2f5ab)
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/9100568/e589ea30-cacf-4706-bcef-ab26d8d5ad8a)

### Your Panel's YAML

```yaml
## corredor cozinha E8

substitutions:

###### CHANGE ME START ######

  device_name: "nspanel001"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

##### CHANGE ME END #####

##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####
```
