### ISSUE TITLE
`Bug` service touchpanel_play_rtttl is no longer supported

### ISSUE THREAD

**Issue by ajvdw** [Blackymas/NSPanel_HA_Blueprint#1912]
### TFT Version

4.3

### ESPHome Version

4.3

### Blueprint Version

4.3

### Panel Model

EU

### What is the bug?

I'm calling touchpanel_play_rtttl from an automation. But it's failing. Looks like an old bug returned ...

### Your Panel's YAML

```yaml
substitutions:
  device_name: touchpanel
  device_description: "SonOff NSPanel"
  wifi_ssid: !secret wifi_ssid 
  wifi_password: !secret wifi_password 

esp32:
  framework:
    type: esp-idf
    
##### CHANGE ME END #####

##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml 
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####

#Wifi settings
wifi:
  use_address: !secret ip_touchpanel
```
