### ISSUE TITLE
`Bug` v4.3.0 Unable to flash ESPHome

### ISSUE THREAD

**Issue by malonip** [Blackymas/NSPanel_HA_Blueprint#1913]
### TFT Version

4.3.0

### ESPHome Version

4.3.0

### Blueprint Version

4.3.0

### Panel Model

EU

### What is the bug?

Unable to flash the new ESPHome v4.3.0 version. When compiling, I get this error message :

`*** [.pioenvs/nspanel/src/esphome/components/status/status_binary_sensor.o] Source `src/esphome/components/status/status_binary_sensor.cpp' not found, needed by target `.pioenvs/nspanel/src/esphome/components/status/status_binary_sensor.o'.`

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/113780852/768fe071-9260-4ca4-882f-3001f9f04084)

### Steps to Reproduce

Try to install ESPHome

### Your Panel's YAML

```yaml
substitutions:

  #### Settings - You can edit these values ####
  device_name: nspanel
  wifi_ssid: < hidden >
  wifi_password: < hidden >
  nextion_update_url: http://192.168.2.100:8123/local/nspanel_eu.tft
      
  # Add-on configuration (if needed)
  # heater_relay: "1"  # Possible values: "1" or "2"

  #### Settings - End ####

# Customization area
##### My customization - Start #####

##### My customization - End #####

##### Do not change area - Start #####
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # Optional advanced and add-on configurations
      # - advanced/esphome/nspanel_esphome_advanced.yaml
      # - nspanel_esphome_addon_climate_cool.yaml
      # - nspanel_esphome_addon_climate_heat.yaml
      # - nspanel_esphome_addon_climate_dual.yaml
    refresh: 300s

esp32:
  framework:
    type: esp-idf

##### Do not change area - End #####
```

### ESPHome Logs

INFO ESPHome 2024.2.2
INFO Reading configuration /config/esphome/nspanel.yaml...
INFO Detected timezone 'Europe/Zurich'
INFO Generating C++ source...
INFO Compiling app...
Processing nspanel (board: esp32dev; framework: espidf; platform: platformio/espressif32@5.4.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - framework-espidf @ 3.40406.240122 (4.4.6) 
 - tool-cmake @ 3.16.9 
 - tool-ninja @ 1.10.2 
 - toolchain-esp32ulp @ 2.35.0-20220830 
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
Reading CMake configuration...
Dependency Graph
|-- ArduinoJson @ 6.18.5
*** [.pioenvs/nspanel/src/esphome/components/status/status_binary_sensor.o] Source `src/esphome/components/status/status_binary_sensor.cpp' not found, needed by target `.pioenvs/nspanel/src/esphome/components/status/status_binary_sensor.o'.
========================== [FAILED] Took 8.16 seconds ==========================
