### ISSUE TITLE
Compile error when customising update_bitwise_setting or update_relay_setting relay_fallback mode

### ISSUE THREAD

**Issue by tikismoke** [Blackymas/NSPanel_HA_Blueprint#1914]
### TFT Version

4.3

### ESPHome Version

4.3

### Blueprint Version

4.3

### Panel Model

EU

### What is the bug?

i can't compile with update_relay_setting to expose relay fallback, i had to change this to update_bitwise_setting.

I don't know if error comes from core:

https://github.com/search?q=repo%3ABlackymas%2FNSPanel_HA_Blueprint%20update_bitwise_setting%20&type=code

or docs :

https://github.com/search?q=repo%3ABlackymas%2FNSPanel_HA_Blueprint%20update_relay_setting%20&type=code

**Comment by edwardtfn** [comment]
Could you please share your panel's yaml?
I will try to duplicate it here.

**Comment by edwardtfn** [comment]
Ok, I could duplicate the issue... Will come with a fix soon.

**Comment by edwardtfn** [comment]
This should work:

```yaml
# Expose relay local control switch to Home Assistant
switch:
  - name: Relay 1 Local
    platform: template
    id: relay1_local
    entity_category: config
    internal: false
    lambda: |-
      return (id(relay_settings) & nspanel_ha_blueprint::RelaySettings::Relay1_Local);
    turn_on_action:
      - lambda: nspanel_ha_blueprint::update_bitwise_setting(id(relay_settings), true, RelaySettings::Relay1_Local);
    on_turn_on:
      - logger.log: "Relay 1 Local turned On!"
    turn_off_action:
      - lambda: nspanel_ha_blueprint::update_bitwise_setting(id(relay_settings), false, RelaySettings::Relay1_Local);
    on_turn_off:
      - logger.log: "Relay 1 Local turned Off!"
  - name: Relay 2 Local
    platform: template
    id: relay2_local
    entity_category: config
    internal: false
    lambda: return (id(relay_settings) & nspanel_ha_blueprint::RelaySettings::Relay2_Local);
    turn_on_action:
      - lambda: nspanel_ha_blueprint::update_bitwise_setting(id(relay_settings), true, RelaySettings::Relay2_Local);
    on_turn_on:
      - logger.log: "Relay 2 Local turned On!"
    turn_off_action:
      - lambda: nspanel_ha_blueprint::update_bitwise_setting(id(relay_settings), false, RelaySettings::Relay2_Local);
    on_turn_off:
      - logger.log: "Relay 2 Local turned Off!"
```
