### ISSUE TITLE
`Bug` Periodic firmware rollback

### ISSUE THREAD

**Issue by I-am-nightingale** [Blackymas/NSPanel_HA_Blueprint#1925]
### TFT Version

4.3

### ESPHome Version

4.3

### Blueprint Version

4.3

### Panel Model

EU

### What is the bug?

Well, it's ridiculous, but from time to time the panel rollback firmware to an older version. This happens completely without my participation, and without any scheduled tasks, moreover, I don’t even have the old firmware!
It all started with an update to 4.2 after 4.1.2, sometimes the panel simply stopped working and did not connect to the API. And in the ESPHome log I have this:
`[I][app:102]: ESPHome version 2023.11.6 compiled on Nov 30 2023, 20:15:13`
And the panel looks like:
![IMG_20240316_145729](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/162443187/f43ea11c-1295-4fa6-be5d-34447e7a2555)
What is "Nov 30 2023, 20:15:13"? It's 4.1.2 compilation time.
Previously, rollbacks were extremely rare, but over the last month this has been happening again and again. 3 days ago I updated the panel firmware, the panel started working, but today the same problem is happening again! I removed everything about the panel from Home Assistant and did everything exactly as stated in the step-by-step guide, but it didn't help! I'll try again right now. The panel started working and this is what is in the log:
`[I][app:102]: ESPHome version 2024.2.2 compiled on Mar 16 2024, 15:09:00`
I thought I was smart enough to figure out the problem, but it looks like I wasn't. I have 14 devices in ESPHome, but only the panel has problems. I don’t know where to look and what to look for, I don’t understand what’s happening at all. I tried to google similar cases, but couldn’t find anything, and now I realized that I was the only one so lucky.
Any ideas?

### Your Panel's YAML

```yaml
ota:
  password: "35ab93020030e12cddc4af0c76515409"

wifi:
  manual_ip:
    static_ip: 192.168.1.205
    gateway: 192.168.1.1
    subnet: 255.255.255.0

substitutions:

###### CHANGE ME START ######

  device_name: "nspanel" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: "http://192.168.1.201:8123/local/nspanel_eu.tft" # URL to local tft File
#  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft" # URL to Github

##### CHANGE ME END #####


# Customization area
##### My customization - Start #####
##### My customization - End #####

# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Basic package
      # Optional advanced and add-on configurations
      # - esphome/nspanel_esphome_advanced.yaml
      # - nspanel_esphome_addon_climate_cool.yaml
      # - nspanel_esphome_addon_climate_heat.yaml
      # - nspanel_esphome_addon_climate_dual.yaml
    refresh: 300s
```
