### ISSUE TITLE
`Bug` utility page line not moving when value is below 0

### ISSUE THREAD

**Issue by bkbartk** [Blackymas/NSPanel_HA_Blueprint#1926]
### TFT Version

4.3

### ESPHome Version

4.3

### Blueprint Version

4.3

### Panel Model

EU

### What is the bug?

in the utilities page

on line1, 3 and 5 I see the slider moving, but not on line 6.
the values of line 6 look like
![313419110-9ae707b5-1082-4bc1-8bca-ac5b1937ec1b](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/17070805/bbc0c6d8-8e85-447b-89da-cf211bd0e38e)
But I was wondering 0.172 might gets rounded to 0. or the value is just to low.

### Steps to Reproduce

congiruge some utilities,
then on line 6 use a linesensor with a value like 0.172

### Your Panel's YAML

```yaml
qrcode_enabled: false
      utilities_enabled: true
      utilities_page01_home_value1: sensor.energy_used_today
      utilities_page01_home_value2: sensor.power_consumed
      utilities_page01_group04_line_inverted: false
      utilities_page01_group01_value1: sensor.grid_fossil_fuel_percentage
      utilities_page01_group01_icon: mdi:leaf
      utilities_page01_group01_color:
      - 15
      - 157
      - 88
      utilities_page01_group02_icon: ''
      utilities_page01_group03_icon: mdi:solar-power
      utilities_page01_group06_icon: mdi:water
      utilities_page01_group05_icon: mdi:fire
      home_value04: sensor.temp_outside_temperature
      home_value04_icon: mdi:sun-thermometer-outline
      utilities_page01_group03_value1: sensor.solaredge_ac_energy_kwh_today
      utilities_page01_group05_value1: sensor.gas_consumed_today
      utilities_page01_group06_value1: sensor.watermeter_today
      utilities_page01_grid_value2: sensor.energy_consumed_today
      utilities_page01_grid_value1: sensor.energy_produced_today
      utilities_page01_group03_value2: sensor.solaredge_ac_power
      utilities_page01_label: Utilitites
      utilities_page01_home_label: ' '
      utilities_page01_grid_label: ' '
      utilities_page01_group06_color:
      - 0
      - 188
      - 212
      utilities_page01_group05_color:
      - 139
      - 3
      - 27
      utilities_page01_group03_color:
      - 255
      - 152
      - 0
      utilities_page01_group06_value2: sensor.watermeter_pulse
      utilities_page01_main_line_reference: sensor.energy_fromgrid_today
      utilities_page01_group03_line_reference: sensor.solaredge_ac_energy_kwh_today
      utilities_page01_group05_line_reference: sensor.gas_consumed_today
      utilities_page01_group06_line_reference: sensor.watermeter_today
      utilities_page01_group05_line_inverted: true
      utilities_page01_group03_line_inverted: true
      utilities_page01_group06_line_inverted: true
      utilities_page01_group01_line_inverted: true
      utilities_page01_group01_line_reference: sensor.grid_fossil_fuel_percentage
      utilities_page01_grid_color:
      - 71
      - 143
      - 194
```
