### ISSUE TITLE
HOME PAGE - CHIPS and ENTITIES STATES are missing.

### ISSUE THREAD

**Issue by dpetrovichev** [Blackymas/NSPanel_HA_Blueprint#1927]
### TFT Version

4.3.0

### ESPHome Version

4.3.0

### Blueprint Version

4.3.0

### Panel Model

EU

### What is the bug?

HOME PAGE - CHIPS are missing.
HOME PAGE - ENTITIES STATES are missing too.
I see only 7 HOME PAGE - CUSTOM BUTTONS.

### Steps to Reproduce

1. To be sure in the state of the HA reboot it. In my case it was reboot after HA Core update.
2. CHIPS and ENTITIES STATES are missing. See screenshot. 
![photo_2024-03-16_23-34-19](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/18519389/ce45bb9e-ccaa-431e-9681-9ca97b71689c)
3. Reboot NSPanel.
4. CHIPS and ENTITIES STATES are missing. See screenshot.
![photo_2024-03-16_23-34-16](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/18519389/213d5285-0edd-489e-a4cf-1fce6dbd7327)
5. Update TFT
6. CHIPS and ENTITIES STATES are missing. See screenshot.
![photo_2024-03-16_23-34-12](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/18519389/a85d39e2-6a27-4581-bbfa-6a58c0953ac9)

Logs of HA and NSPanel attached.
[nspanel.log7.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/14625204/nspanel.log7.txt)

### Your Panel's YAML

```yaml
substitutions:
  # Settings - Editable values
  device_name: "nspanel-01"
  wifi_ssid: "xxxxx"
  wifi_password: "xxxxxx"
  nextion_update_url: "http://192.168.3.28:8123/local/nspanel_eu.tft"  # Optional
  # Add-on configuration (if needed)
  # heater_relay: "1"  # Possible values: "1" or "2"

# Customization area
##### My customization - Start #####
##### My customization - End #####

# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: beta
    files:
      - nspanel_esphome.yaml # Core package
      # Optional advanced and add-on configurations
      # - advanced/esphome/nspanel_esphome_advanced.yaml
      # - nspanel_esphome_addon_climate_cool.yaml
      # - nspanel_esphome_addon_climate_heat.yaml
      # - nspanel_esphome_addon_climate_dual.yaml
    refresh: 300s
```

### Home Assistant Logs

[home-assistant_2024-03-16T20-15-10.869Z.log](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/14625208/home-assistant_2024-03-16T20-15-10.869Z.log)
