### ISSUE TITLE
Unable to work with new version, could i rollback to 4.2.6 `Bug` 

### ISSUE THREAD

**Issue by ady1972** [Blackymas/NSPanel_HA_Blueprint#1929]
### TFT Version

4.3.0

### ESPHome Version

4.3.0

### Blueprint Version

4.3.0

### Panel Model

US (Landscape)

### What is the bug?

After upgrading from 4.2.6 to 4.3.0 i have some problems in resolving issue of home assistant red icon and the panel doesn't work as expected (tried all suggests found in the github repository).
I would like to come back to 4.2. to be able to use panel with all funcionality. Is there any way to do this? I have searched inside repository but i don't find anything.

However reactivity of this new version is incredible. I like it very much...Thanks a lot...I hope as soon as possible to use new version !! 

![Screenshot 2024-03-18 121152](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/7114188/9c9dfea0-c3f4-45fb-960c-b923bad791f7)

### Your Panel's YAML

```yaml
substitutions:

###### CHANGE ME START ######

  device_name: "nspanel-blueprint2" 
  wifi_ssid: "*******"
  wifi_password: "*****"

  nextion_update_url: "http://192.168.1.140:9123/local/nspanel_us_land.tft" # URL to local tft File
#  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft" # URL to Github

##### CHANGE ME END #####

##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! ###### 

# Enable Bluetooth proxy
#bluetooth_proxy:
#  active: true

wifi:
  power_save_mode: LIGHT
```
