### ISSUE TITLE
notification_clear`Bug` 

### ISSUE THREAD

**Issue by Gertc555** [Blackymas/NSPanel_HA_Blueprint#1931]
### TFT Version

4.3.0

### ESPHome Version

4.3.0

### Blueprint Version

4.3.0

### Panel Model

US

### What is the bug?

When calling service to clear notification, nothing happens.
ESPHome: nspanelwhite_notification_clear

![Notification clear](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/53166577/7c0069e8-eda9-4f34-a34e-ff58f98e0217)

### Your Panel's YAML

```yaml
- service: esphome.nspanelwhite_notification_show
        data:
          label: ALARM
          message: ALARM DISARMED
      - delay:
          hours: 0
          minutes: 0
          seconds: 1
          milliseconds: 0
      - service: esphome.nspanelwhite_notification_clear
        data: {}
mode: single
```
