### ISSUE TITLE
`Bug` hw_button_state fails to turn "led" off without short delay

### ISSUE THREAD

**Issue by MichaelHeimann** [Blackymas/NSPanel_HA_Blueprint#1933]
### TFT Version

4.3

### ESPHome Version

4.3

### Blueprint Version

4.3

### Panel Model

EU

### What is the bug?

An automation that disables a hw_button_state fails to turn the state off but the "led" bar just flickers and stays on.

Adding a 100ms delay fixes it (!).

Automation is this:

````
alias: Küche Unterschrank Anzeige im NSPanel
description: >-
  Wenn Küche Unterschrank an ist soll im NSPanel der blaue Balken über der
  linken Taste leuchten
trigger:
  - platform: device
    type: turned_on
    device_id: b111fe8e3bbfcdc4adee4e6d59a1836a
    entity_id: 9df71ee72db9fad674de6d6fb027d88c
    domain: switch
    id: an
  - platform: device
    type: turned_off
    device_id: b111fe8e3bbfcdc4adee4e6d59a1836a
    entity_id: 9df71ee72db9fad674de6d6fb027d88c
    domain: switch
    id: aus
condition: []
action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 100
  - choose:
      - conditions:
          - condition: trigger
            id:
              - an
        sequence:
          - if:
              - condition: state
                entity_id: light.kuche_decke
                state: "on"
            then:
              - service: esphome.nskueche_hw_button_state
                data:
                  left: true
                  right: true
                alias: Beide an
            else:
              - alias: Links an Rechts aus
                service: esphome.nskueche_hw_button_state
                data:
                  left: true
                  right: false
      - conditions:
          - condition: trigger
            id:
              - aus
        sequence:
          - if:
              - condition: state
                entity_id: light.kuche_decke
                state: "on"
            then:
              - alias: Links aus, Rechts an
                service: esphome.nskueche_hw_button_state
                data:
                  left: false
                  right: true
            else:
              - alias: Beide aus
                service: esphome.nskueche_hw_button_state
                data:
                  left: false
                  right: false
mode: single

````

### Steps to Reproduce

config:

1) Have an automation assigned to a hw button 
2) set the blueprint to trigger automations and not toggle them on/off.
3) have another automation to control the "led-bar" via new hw_button_state service

reproduce steps:
1) use the hw-button, which triggers a lightgroup to turn off
2) see the led-bar to flicker instead of turning off
3) add delay of 100ms before hw_button_state service to actually turn it off

### ESPHome Logs

[logs_nskueche_logs.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/14643890/logs_nskueche_logs.txt)
esphome log - I cannot see a difference

### Home Assistant Logs

I don't know how to gather the relevant bit's here. Please help.
