### ISSUE TITLE
error compiling  V4.3.1 from command line

### ISSUE THREAD

**Issue by lecrams** [Blackymas/NSPanel_HA_Blueprint#1941]
### TFT Version

4.3.0

### ESPHome Version

4.3.1

### Blueprint Version

4.3.1

### Panel Model

EU

### What is the bug?

Compiling from command line using arduino framework gives an error for main:
Compiling .pioenvs\nspanel1\src\main.cpp.o
.\esp-panel-1.yaml: In lambda function:
.\esp-panel-1.yaml:66:86: error: no matching function for call to 'esphome::script::RestartScript<>::execute(const char*, int)'
In file included from src/esphome.h:74,
                 from src/main.cpp:3:
src/esphome\components\script\script.h:75:8: note: candidate: 'void esphome::script::RestartScript<Ts>::execute(Ts ...) [with Ts = {}]'
   void execute(Ts... x) override {
        ^~~~~~~
src/esphome\components\script\script.h:75:8: note:   candidate expects 0 arguments, 2 provided
.\esp-panel-1.yaml:67:82: error: no matching function for call to 'esphome::script::RestartScript<>::execute(const char*, int)'
In file included from src/esphome.h:74,
                 from src/main.cpp:3:
src/esphome\components\script\script.h:75:8: note: candidate: 'void esphome::script::RestartScript<Ts>::execute(Ts ...) [with Ts = {}]'
   void execute(Ts... x) override {
        ^~~~~~~
src/esphome\components\script\script.h:75:8: note:   candidate expects 0 arguments, 2 provided
*** [.pioenvs\nspanel1\src\main.cpp.o] Error 1

### Your Panel's YAML

```yaml
substitutions:

###### CHANGE ME ######

  device_name: "nspanel1" 
  wifi_ssid: "StumpelAP"
  wifi_password: "220112021708111290"
##### CHANGE ME #####



##### DO NOT CHANGE ANYTHING! #####

  nextion_update_url: "http://192.168.178.87:8123/local/nspanel.tft"

##### addon-configuration #####
  ## addon_climate ##
  # addon_climate_heater_relay: "1" # possible values: 1/2

  ##### CHANGE ME END #####

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # - nspanel_esphome_advanced.yaml # activate advanced (legacy) elements - can be useful for troubleshooting
      # - nspanel_esphome_addon_climate_cool.yaml # activate for local climate (cooling) control
      # - nspanel_esphome_addon_climate_heat.yaml # activate for local climate (heater) control
    refresh: 300s

##### My customization - Start #####

##### My customization - End #####
esphome:
  compile_process_limit: 1

sensor:
  - platform: uptime
    name: "${device_name} Uptime Sensor"

button:
  # Adds a button to put the panel to sleep
  - name: ${device_name} Sleep
    id: force_sleep
    platform: template
    icon: mdi:sleep
    on_press:
      then:
        - logger.log: Button Sleep pressed
        - lambda: |-
            if (id(current_page).state != "screensaver") id(disp1).goto_page("screensaver");
  
  # Adds a button to wake-up the panel (similar to the existing service)
  - name: ${device_name} Wake-up
    id: force_wake_up
    platform: template
    icon: mdi:alarm
    on_press:
      then:
        - logger.log: Button Wake-up pressed
        - lambda: |-
            if (id(current_page).state == "screensaver") id(disp1).goto_page(id(wakeup_page_name).state.c_str());
            // id(timer_page).execute(id(wakeup_page_name).state.c_str()); // enable this if you want page timeout to be reset
            id(timer_sleep).execute(id(wakeup_page_name).state.c_str(), int(id(timeout_sleep).state));
            id(timer_dim).execute(id(wakeup_page_name).state.c_str(), int(id(timeout_dim).state));
  
wifi: !include .wifi.yaml

esp32:
  framework:
    type: arduino
```

**Comment by edwardtfn** [comment]
Have you tried cleaning build files?
And which version of ESPHome compiler are you using?

**Comment by lecrams** [comment]
Yes I did:
pip install -U esphome
esphome clean nspanel.yaml
esphome run .\nspanel.yaml

**Comment by edwardtfn** [comment]
I could compile it (via command line) with no issues when I've commented out the `wifi: !include .wifi.yaml`.
Are you sure the issue isn't on the `.wifi.yaml`? ESPHome v2024.3.0 have a breaking change on the IP address function, so depending on what you have on that file it could be the issue.

**Comment by edwardtfn** [comment]
I've said too earlier... I got the same issue here.

**Comment by lecrams** [comment]
My .wifi.yaml contains:
networks:
- ssid: "StumpelAP"
  password: "220112021708xxxxx"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
ap:
  ssid: "Esphome Basic Fallback Hotspot"
  password: "YcfplNYTNvx8"

What is the breaking change then? It is not mentioned in the release note of esphome 4.3.0

**Comment by edwardtfn** [comment]
Please try this:

```yaml
substitutions:

###### CHANGE ME ######

  device_name: "nspanel1" 
  wifi_ssid: "StumpelAP"
  wifi_password: "220112021708111290"
##### CHANGE ME #####



##### DO NOT CHANGE ANYTHING! #####

  nextion_update_url: "http://192.168.178.87:8123/local/nspanel.tft"

##### addon-configuration #####
  ## addon_climate ##
  # addon_climate_heater_relay: "1" # possible values: 1/2

  ##### CHANGE ME END #####

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # - nspanel_esphome_advanced.yaml # activate advanced (legacy) elements - can be useful for troubleshooting
      # - nspanel_esphome_addon_climate_cool.yaml # activate for local climate (cooling) control
      # - nspanel_esphome_addon_climate_heat.yaml # activate for local climate (heater) control
    refresh: 300s

##### My customization - Start #####

##### My customization - End #####
esphome:
  compile_process_limit: 1

sensor:
  - platform: uptime
    name: "${device_name} Uptime Sensor"

button:
  # Adds a button to put the panel to sleep
  - name: ${device_name} Sleep
    id: force_sleep
    platform: template
    icon: mdi:sleep
    on_press:
      then:
        - logger.log: Button Sleep pressed
        - lambda: |-
            if (id(current_page).state != "screensaver") id(disp1).goto_page("screensaver");
  
  # Adds a button to wake-up the panel (similar to the existing service)
  - name: ${device_name} Wake-up
    id: force_wake_up
    platform: template
    icon: mdi:alarm
    on_press:
      then:
        - logger.log: Button Wake-up pressed
        - lambda: |-
            if (id(current_page).state == "screensaver") id(disp1).goto_page(id(wakeup_page_name).state.c_str());
            // id(timer_page).execute(); // enable this if you want page timeout to be reset
            id(timer_sleep).execute();
            id(timer_dim).execute();
  
wifi: !include .wifi.yaml

esp32:
  framework:
    type: arduino
```
