### ISSUE TITLE
`Bug` TFT Upload unreliable with ble_tracker enabled

### ISSUE THREAD

**Issue by MichaelHeimann** [Blackymas/NSPanel_HA_Blueprint#1946]
### TFT Version

4.3.1

### ESPHome Version

4.3.1

### Blueprint Version

4.3.1

### Panel Model

EU

### What is the bug?

I have ble_tracker configured on 9 panels and updating from 4.3.0 to 4.3.1 with ble config enabled works mostly. The momory leak fix in 4.3 didn't resolve this but made it consistant as the starting conditions are now always about 22k free heap.

When it doesn't work, it's always running out of heap memory while uploading with 115200 baud.

From the log you can see it tried with 115200 and failed at 10:02:11 and 10:04:51 and finally succeeded with 921600 baud at 11:23:15. 

This was reliable on all panels, although about 50% updated correctly on the first try (with 921600).

The free heap is always going down during tft flash, but because the upload is just faster with 921600 it reaches 100% before out of memory.
- The memory is reduced by about 5k / 20s and esp reboots at about 5k left. 
- Due to ble consuming some memory anyways the panel is left with about 22k so it has about a minute to update. If that's not working it'll crash.
- The upload doesn't continue where it left but always restarts from 85,71% (this time, probably depending on the release). If upload with 921600 doesn't start (for reasons unknown), it's always doomed to fail when it tries with slower speeds.

Since we only need the last 15% of the tft in small updates this can finish. If we have bigger changes in the feature or during initial flashing this issue hits harder.

### Steps to Reproduce

1) add ble_tracker to the nspanel yaml
2) hit update tft display button in HA

### Your Panel's YAML

```yaml
esp32_ble_tracker:
  id: ble_tracker
  scan_parameters:
    active: false
binary_sensor:
  - platform: ble_presence
    ibeacon_uuid: '12624013-e6fa-4a02-aca7-e329827e7865'
    name: "Ivanas Handy im Bad"
  - platform: ble_presence
    # aus dem Log: ibeacon_uuid: '91253BE1-9327-C8AA-1747-1038673A6F20'
    ibeacon_uuid: '206f3a67-3810-4717-aac8-2793e13b2591'
    name: "Michis Handy im Bad"

sensor:
  - platform: ble_rssi
    ibeacon_uuid: '206f3a67-3810-4717-aac8-2793e13b2591'
    name: "Michis Handy Bad RSSI"
  - platform: ble_rssi
    ibeacon_uuid: '12624013-e6fa-4a02-aca7-e329827e7865'
    name: "Ivanas Handy Bad RSSI"

script:
  - id: !extend upload_tft
    then:
      - lambda: |-
          static const char *const TAG = "CUSTOM.script.upload_tft";
          ble_tracker->dump_config();
          ESP_LOGI(TAG, "Stopping BLE Tracker scan...");
          ble_tracker->stop_scan();
          ESP_LOGI(TAG, "Disabling BLE Tracker scan...");
          ble_tracker->set_scan_active(false);

```
```


### ESPHome Logs


[logs_nsschlafzimmer_logs.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/14665270/logs_nsschlafzimmer_logs.txt)

### Home Assistant Logs

_No response_
