### ISSUE TITLE
`Bug` ? Bootscreen displayed after wakeup

### ISSUE THREAD

**Issue by sysrun** [Blackymas/NSPanel_HA_Blueprint#1947]
### TFT Version

4.3.1

### ESPHome Version

4.3.1

### Blueprint Version

4.3.1

### Panel Model

EU

### What is the bug?

After wakeup the "boot screen" is displayed for several seconds. 

In 4.3.0 the device went directly to the homepage.

### Your Panel's YAML

```yaml
substitutions:
###### CHANGE ME START ######
  # Settings - Editable values
  device_name: "nspanel1" 
  #friendly_name: "NS Panel 1"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  # Add-on configuration (if needed)
  heater_relay: "1"  # Possible values: "1" or "2"
##### CHANGE ME END #####

# Customization area
##### My customization - Start #####
##### My customization - End #####

# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: v4.3.1 #main
    files:
      - nspanel_esphome.yaml # Core package
      # Optional advanced and add-on configurations
      # - advanced/esphome/nspanel_esphome_advanced.yaml
      # - nspanel_esphome_addon_climate_cool.yaml
      - nspanel_esphome_addon_climate_heat.yaml
      # - nspanel_esphome_addon_climate_dual.yaml
    refresh: 300s

esp32:
  framework:
    type: esp-idf

ota:
  # change OTA password, remove after flashing
  password: ####
```
