### ISSUE TITLE
Your ESPHome version is too old. Please update to at least 2024.3.0.

### ISSUE THREAD

**Issue by rudgej** [Blackymas/NSPanel_HA_Blueprint#1954]
### TFT Version

4.2.3

### ESPHome Version

4.2.6

### Blueprint Version

4.2.3

### Panel Model

EU

### What is the bug?

On update I Get Your ESPHome version is too old. Please update to at least 2024.3.0.

ESP home has always updated itself on update - so I dont really know what to do. Google does not help not the issues log on here.

If I mouse over the update Button in ESP home it shows update available 2024.2.1 to 2024.2.2   which of course is not 2024.3.0

INFO ESPHome 2024.2.2
INFO Reading configuration /config/esphome/study.yaml...
INFO Updating https://github.com/Blackymas/NSPanel_HA_Blueprint@main
INFO Updating https://github.com/Blackymas/NSPanel_HA_Blueprint@main
INFO Updating https://github.com/edwardtfn/esphome@nextion-v431
INFO Updating https://github.com/edwardtfn/esphome@adc-sampling
INFO Detected timezone 'Europe/London'
Failed config

esphome: None
  name: study
  friendly_name: study
  
  Your ESPHome version is too old. Please update to at least 2024.3.0.
  min_version: 2024.3.0
  platformio_options: 
    build_flags: 
      - -Wno-missing-field-initializers
  on_boot: 
    - priority: 600.0
      then: 
        - lambda: |-
            if (isnan(blueprint_status->raw_state)) blueprint_status->publish_state(0);
            device_name->publish_state("study");
            notification_label->publish_state("");
            notification_text->publish_state("");
            notification_unread->turn_off();
        - script.execute: restore_settings
        - wait_until: 
            condition: 
              - lambda: return disp1->is_setup();
            timeout: 60s
        - if: 
            condition: 
              - lambda: return (not disp1->is_detected());
            then: 
              - switch.turn_off: screen_power
              - delay: 2s
              - switch.turn_on: screen_power
  on_shutdown: 
    - priority: 0
      then: 
        - lambda: |-
            // Make it unavailable to blueprint calls
            nextion_init->publish_state(false);
            // Update Wi-Fi icon
            disp1->set_component_text_printf("home.wifi_icon", "\uE708");
            // Update Wi-Fi icon color
            disp1->set_component_font_color("home.wifi_icon", 63488);
    - priority: 600.0
      then: 
        - switch.turn_off: screen_power
  build_path: build/study

### Steps to Reproduce

Click Update on ESP home 

### Your Panel's YAML

```yaml
substitutions:

###### CHANGE ME START ######

  device_name: "study" 
  wifi_ssid: "xx"
  wifi_password: "xx"

  #nextion_update_url: "http://homeassistant.local:8123/local/nspanel_eu.tft"  # Optional for `esp-idf` framework
  # Add-on configuration (if needed)
  # heater_relay: "1"  # Possible values: "1" or "2"

# Customization area
##### My customization - Start #####
##### My customization - End #####

# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # Optional advanced and add-on configurations
      # - advanced/esphome/nspanel_esphome_advanced.yaml
      # - nspanel_esphome_addon_climate_cool.yaml
      # - nspanel_esphome_addon_climate_heat.yaml
      # - nspanel_esphome_addon_climate_dual.yaml
    refresh: 300s

esp32:
  framework:
    type: esp-idf

    # Set Nextion comms baud rate to 921600 bps
uart:
  - id: !extend tf_uart
    baud_rate: 921600
```

### ESPHome Logs

INFO ESPHome 2024.2.2
INFO Reading configuration /config/esphome/study.yaml...
INFO Detected timezone 'Europe/London'
Failed config

esphome: None
  name: study
  friendly_name: study
  
  Your ESPHome version is too old. Please update to at least 2024.3.0.
  min_version: 2024.3.0
  platformio_options: 
    build_flags: 
      - -Wno-missing-field-initializers
  on_boot: 
    - priority: 600.0
      then: 
        - lambda: |-
            if (isnan(blueprint_status->raw_state)) blueprint_status->publish_state(0);
            device_name->publish_state("study");
            notification_label->publish_state("");
            notification_text->publish_state("");
            notification_unread->turn_off();
        - script.execute: restore_settings
        - wait_until: 
            condition: 
              - lambda: return disp1->is_setup();
            timeout: 60s
        - if: 
            condition: 
              - lambda: return (not disp1->is_detected());
            then: 
              - switch.turn_off: screen_power
              - delay: 2s
              - switch.turn_on: screen_power
  on_shutdown: 
    - priority: 0
      then: 
        - lambda: |-
            // Make it unavailable to blueprint calls
            nextion_init->publish_state(false);
            // Update Wi-Fi icon
            disp1->set_component_text_printf("home.wifi_icon", "\uE708");
            // Update Wi-Fi icon color
            disp1->set_component_font_color("home.wifi_icon", 63488);
    - priority: 600.0
      then: 
        - switch.turn_off: screen_power
  build_path: build/study
