### ISSUE TITLE
`Enhancement` Show alarm panel when triggered for quick deactivation

### ISSUE THREAD

**Issue by NiC1305** [Blackymas/NSPanel_HA_Blueprint#1955]
### Enhancement Summary

Show alarm panel when triggered

### Detailed Description

Hello, thank you for the project.
Would it be possible to bring the alarm control screen to the foreground for deactivation, as long as the alarm is activated and a trigger is activated.
In the same way that a trigger wakes up the screen
Thanks

**Comment by M0uC0** [comment]
Quoting @edwardtfn in 
https://community.home-assistant.io/t/sonoff-nspanel-blueprint-configure-your-own-custom-nspanel-easy-via-a-blueprint/500577/800

______________________________

You can use the open_entity_settings_page to call the alarm page with the alarm entity you wanna show: [How to - Call a Page Directly - Entity-Specific Pages 1](https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/d704de853a029197a2ca8fe9c8466edef0c277d8/docs/howto.md#entity-specific-pages).

You can then check for the sensor “Current page” to wait for page “alarm” to be visible. Once that page is visible, you can use the service send_command_printf to run command click bt_disarm,0 which will simulate the release of a click on button disarm:

service: esphome.xxxxx_send_command_printf
data:
  cmd: click bt_disarm,0

**Comment by NiC1305** [comment]
In order to make a small improvement, would it be possible for the numeric keypad to take up the entire screen, in fact the number keys are quite small and I think this would be more comfortable to use

**Comment by edwardtfn** [comment]
Which model are you using? EU, US or US Landscape?

**Comment by NiC1305** [comment]
I use EU

**Comment by PoopingNow** [comment]
I was able to open the alarm page when i unlock my door, by calling the esphome entity page, as i am using alarmo. However, once the alarm page is opened the "click bt_disarm,0" is not working, i am not able to open the pin pad / disarm page. Ii tried to increase the wait time and other options online, but none seems to work.

**Comment by M0uC0** [comment]
Hello..
API has changed since the post.

now u have to use the 

ESPHome: "your_nsp_panel"_entity_details_show
service..

entity: your_alarm_entity
back_page: home

ESPHome: "your_nsp_panel"_command
service..

cmd: click bt_disarm,0

and maybe checking the "current page" on automation if it is at alarm.. before the click.

**Comment by PoopingNow** [comment]
Thank you for the prompt reply. Yes i am using the latest API and exactly per the above.


ESPHome: mainpanel_entity_details_show

entity: alarm_control_panel.alarmo
back_page: home

At this stage, the alarm panel will load with the option to arm / disarm etc... As per the normal behaviour. 


ESPHome: mainpanel_command
cmd: click bt_disarm,0

At this stage, the disarm window does not load. I expect it to load the disarm window, where there pin pad is visible for easy capture of the disarm code.


Can point me in the right direction? I could not locate the get current page function in the API list.

**Comment by edwardtfn** [comment]
What if you call `click bt_disarm,1` instead?

**Comment by PoopingNow** [comment]
Tried that as well.
I even added a delay of 100ms before i call click bt_disarm,1.
then another delay of 50ms to simulate and actual button press.
Then release the button by calling click bt_disarm,0.

I also tried to increase the delay or without the delays as well. Anyway I will leave it as is for now.

**Comment by NiC1305** [comment]
Hello,
Thanks for sharing this.
I’ve finally tried it out, and it does indeed work with this code:

```
actions:
  - action: esphome.nspanel_entity_details_show
    metadata: {}
    data:
      entity: alarm_control_panel.maison
      back_page: home
  - delay:
      milliseconds: 250
  - action: esphome.nspanel_command
    metadata: {}
    data:
      cmd: click bt_disarm,1
  - delay:
      milliseconds: 250
  - action: esphome.nspanel_command
    metadata: {}
    data:
      cmd: click bt_disarm,0
  - action: esphome.nspanel_command
    metadata: {}
    data:
      cmd: page keyb_num
```


There is just one small issue: if you click the "X" to close the numeric keypad, it redirects you to the boot screen, forcing a reboot to get back to the home page. I don't think that's normal behavior.
