### ISSUE TITLE
NSPanel invalid Blueprint version

### ISSUE THREAD

**Issue by guenther2280** [Blackymas/NSPanel_HA_Blueprint#1957]
### TFT Version

4.2.4

### ESPHome Version

4.3.1

### Blueprint Version

4.2.4

### Panel Model

EU

### What is the bug?

display shows only the watch.
in HA i became the message NSPanel invalid Blueprint version.
I sthere any solution?
Thanks!

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/157225910/6187990c-cace-4c85-b9b1-44bf322430ef)

### Your Panel's YAML

```yaml
alias: NSPanelVorhaus
description: ""
use_blueprint:
  path: Blackymas/nspanel_blueprint.yaml
  input:
    nspanel_name: b7af8231232cd2e9c734b1d3649ce1e1
    language: de
    weather_entity: weather.forecast_home
    outdoortemp: sensor.aussentemperatur_temperature
    home_indoor_temp_icon: ""
    right_button_entity: switch.garage_rechts_switch_0
    right_button_name: Garage Rechts
    home_outdoor_temp_label_color:
      - 17
      - 223
      - 51
    home_outdoor_temp_font: "6"
    indoortemp: sensor.buro_temperatur_temperature
    chip_font_size: "8"
    chip01: binary_sensor.garage_links_input_100_input
    chip01_icon: mdi:garage-alert-variant
    chip01_icon_color:
      - 227
      - 13
      - 198
    chip01_inverted: false
    right_button_hold_select: Default
    chip04: binary_sensor.shelly_blu_door_window_42dd_window
    chip04_icon: mdi:window-closed-variant
    chip04_icon_color:
      - 236
      - 9
      - 9
    chip04_inverted: false
    chip02: binary_sensor.garage_rechts_input_100_input
    chip02_icon: mdi:garage-alert-variant
    chip02_icon_color:
      - 245
      - 10
      - 10
    right_button_color:
      - 12
      - 55
      - 228
    left_button_entity: switch.garage_links_switch_0
    left_button_name: Garage Links
    left_button_color:
      - 248
      - 37
      - 220
    button_pages_icon_size: "10"
    chip05: binary_sensor.wc_fenster_og_contact
    chip05_icon: mdi:window-closed-variant
    chip05_icon_color:
      - 228
      - 12
      - 12
    delay: 0
```
