### ISSUE TITLE
`Bug` [text] is an invalid option for [variables].

### ISSUE THREAD

**Issue by aotsukiqx** [Blackymas/NSPanel_HA_Blueprint#1958]
### TFT Version

4.2.5

### ESPHome Version

2024.3.0

### Blueprint Version

4.2.5

### Panel Model

EU

### What is the bug?

yaml compile error

### Steps to Reproduce

upgrade esphome then upgrade nspanel firmware

### Your Panel's YAML

```yaml
substitutions:
  ###### CHANGE ME START ######
  device_name: "nspanel"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: "http://domain/nspanel.tft"

  ##### CHANGE ME END #####

# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Basic package
      # Optional advanced and add-on configurations
      # - esphome/nspanel_esphome_advanced.yaml
      # - nspanel_esphome_addon_climate_cool.yaml
      # - nspanel_esphome_addon_climate_heat.yaml
      # - nspanel_esphome_addon_climate_dual.yaml
    refresh: 300s
```

### ESPHome Logs

when compile yaml, will report an error:
```
    - service: notification_show
      variables: 
        label: string
        
        [text] is an invalid option for [variables].
        text: string
```
