### ISSUE TITLE
Nspanel TFT kein Update auf 4.3.1

### ISSUE THREAD

**Issue by racerman76** [Blackymas/NSPanel_HA_Blueprint#1960]
### TFT Version

4.6.2

### ESPHome Version

4.3.1

### Blueprint Version

4.3.1

### Panel Model

EU

### What is the bug?

Ich habe gestern das Update 4.3.1 bei EspHome und bei NSPanel_HA_Blueprint durchgeführt , danach wollte ich noch beim Nspanel die TFT Datei auf 4.3.1 updaten .
Aber das Panele führt das Update nicht durch .Vieleicht hat ja jemand eine Idee dazu . Der Befehl esphome:nspanel_update_tft_display ist auch nicht mehr vorhanden.

### Your Panel's YAML

```yaml
substitutions:
  # Settings - Editable values
  device_name: "nspanel-stube"
  friendly_name: "nspanel_stube"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  nextion_update_url: "http://homeassistant.local:8123/local/nspanel_eu.tft"  # Optional
  # Add-on configuration (if needed)
  # heater_relay: "1"  # Possible values: "1" or "2"

# Customization area
##### My customization - Start #####
##### My customization - End #####

# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
       - nspanel_esphome.yaml # Basic package
      # Optional advanced and add-on configurations
      # - esphome/nspanel_esphome_advanced.yaml
      # - nspanel_esphome_addon_climate_cool.yaml
      # - nspanel_esphome_addon_climate_heat.yaml
      # - nspanel_esphome_addon_climate_dual.yaml
    refresh: 300s

esp32:
  framework:
    type: esp-idf

wifi:
  # ...
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.40.6
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.40.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0
```
