### ISSUE TITLE
Page Utilities ― Line Direction only works for Groups 1 & 2

### ISSUE THREAD

**Issue by finch6** [Blackymas/NSPanel_HA_Blueprint#1964]
### TFT Version

4.3.1

### ESPHome Version

4.3.1

### Blueprint Version

4.3.1

### Panel Model

US

### What is the bug?

The `Line Direction` indicator only works for Groups 1 & 2.
It doesn't work for any of the other Groups (3,4,5 or 6) and I also can't get it working for the `Main Line Direction` either.

Even if I use and entity from Group 1 or 2, that I know works, to the `Line Direction Reference`, its doesn't make any of the other groups or main line indicator work.

**My Groups:**
Group 1 ― House
Group 2 ― Flat
Group 3 ― Grid
Group 4 ― _No Used_
Group 5 ― Battery
Group 6 ― Home

https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/42886484/614850bf-a69d-44cb-8662-d41fec6868a5

Below is the Blueprint yaml ― you can see that I have set all of the Groups `Line Direction Reference` to `sensor.sunsynk_pv_power_1`, yet only Group 1 & 2 show movement.

### Your Panel's YAML

```yaml
utilities_enabled: true
    utilities_page01_grid_label: Solar
    utilities_page01_grid_icon: mdi:solar-power
    utilities_page01_grid_value1: sensor.sunsynk_pv_power
    utilities_page01_grid_value2: sensor.sunsynk_pv_energy
    utilities_page01_grid_color:
      - 255
      - 170
      - 0
    utilities_page01_home_label: SunSynk
    utilities_page01_home_icon: mdi:meter-electric-outline
    utilities_page01_home_value1: sensor.sunsynk_load_power
    utilities_page01_home_value2: sensor.sunsynk_temperature
    utilities_page01_group01_label: House
    utilities_page01_group01_icon: mdi:solar-power-variant
    utilities_page01_group01_value1: sensor.sunsynk_pv_power_1
    utilities_page01_group01_value2: sensor.sunsynk_pv_current_1
    utilities_page01_group01_color:
      - 255
      - 170
      - 0
    utilities_page01_group01_line_reference: sensor.sunsynk_pv_power_1
    utilities_page01_group02_label: Flat
    utilities_page01_group02_icon: mdi:solar-power-variant
    utilities_page01_group02_value1: sensor.sunsynk_pv_power_2
    utilities_page01_group02_value2: sensor.sunsynk_pv_current_2
    utilities_page01_group02_color:
      - 255
      - 170
      - 0
    utilities_page01_group02_line_inverted: true
    utilities_page01_group02_line_reference: sensor.sunsynk_pv_power_2
    utilities_page01_group03_label: Grid
    utilities_page01_group03_icon: mdi:transmission-tower
    utilities_page01_group03_value1: sensor.sunsynk_grid_power_ct
    utilities_page01_group03_value2: sensor.sunsynk_grid_energy_in
    utilities_page01_group03_color:
      - 58
      - 136
      - 254
    utilities_page01_group03_line_reference: sensor.sunsynk_pv_power_1
    utilities_page01_group05_label: Battery
    utilities_page01_group05_icon: mdi:home-battery-outline
    utilities_page01_group05_value1: sensor.sunsynk_battery_state_of_charge
    utilities_page01_group05_value2: sensor.sunsynk_battery_power
    utilities_page01_group05_color:
      - 255
      - 106
      - 0
    utilities_page01_group05_line_inverted: false
    utilities_page01_group05_line_reference: sensor.sunsynk_pv_power_1
    utilities_page01_group06_label: Home
    utilities_page01_group06_icon: mdi:home-lightning-bolt-outline
    utilities_page01_group06_value1: sensor.sunsynk_load_power_essential
    utilities_page01_group06_value2: sensor.sunsynk_load_energy
    utilities_page01_group06_color:
      - 0
      - 199
      - 252
    utilities_page01_group06_line_reference: sensor.sunsynk_load_power
    utilities_page01_main_line_reference: sensor.sunsynk_pv_power_1
    utilities_page01_main_line_inverted: false
```
