### ISSUE TITLE
`Bug` NSPanel invalid Blueprint version

### ISSUE THREAD

**Issue by AntonMilushev76** [Blackymas/NSPanel_HA_Blueprint#1966]
### TFT Version

4.3.1

### ESPHome Version

4.3.1

### Blueprint Version

4.3.1

### Panel Model

EU

### What is the bug?

After updating to version 4.3.1, by my mistake I updated the firmware before updating the tft and blueprint, and now I'm getting a mishmash blueprint message from esphome. 

    NSPanel invalid Blueprint version
    ESPHome cannot provide a valid Blueprint version.
    Panel:
    TFT: 4.3.1
    ESPHome: 4.3.1
    Blueprint (reported by ESPHome): Unknown
    Blueprint (installed): 4.3.1

### Your Panel's YAML

```yaml
substitutions:
  # Settings - Editable values
  device_name: nspanellr
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  nextion_update_url: "https://github.com/Blackymas/NSPanel_HA_Blueprint/raw/main/nspanel_eu.tft"  # Optional for `esp-idf` framework
  # Add-on configuration (if needed)
  # heater_relay: "1"  # Possible values: "1" or "2"

# Customization area
##### My customization - Start #####
##### My customization - End #####

# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # Optional advanced and add-on configurations
      # - advanced/esphome/nspanel_esphome_advanced.yaml
      # - nspanel_esphome_addon_climate_cool.yaml
      # - nspanel_esphome_addon_climate_heat.yaml
      # - nspanel_esphome_addon_climate_dual.yaml
    refresh: 300s

esp32:
  framework:
    type: esp-idf
```
