### ISSUE TITLE
`Bug` Unable to upload TFT after update to 4.3.1

### ISSUE THREAD

**Issue by smarthomefamilyverrips** [Blackymas/NSPanel_HA_Blueprint#1969]
### TFT Version

4.2.6

### ESPHome Version

4.3.1

### Blueprint Version

4.3.1

### Panel Model

EU

### What is the bug?

When I push the TFT upload button ith shows a moment the small window what says setting baudrate and after 20 seconds or so it reboots the NSpanel

### Steps to Reproduce

1. Go to ESPhome integration
2. go to device
3. press TFT upload button

### Your Panel's YAML

```yaml
substitutions:

###### CHANGE ME START ######

  device_name: "nsbathroom" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: "http://192.168.0.168:8123/local/nspanel_eu.tft" # URL to local tft File
#  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft" # URL to Github

  ##### addon-configuration #####
  ## addon_climate ##
  # addon_climate_heater_relay: "1" # possible values: 1/2

#  baud_rate: "115200" # requires 115200 if tft is installed but can be changed to 9600 if tft upload fails and nextion switches to 9600

##### CHANGE ME END #####

##### DO NOT CHANGE ANYTHING! #####

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # - nspanel_esphome_advanced.yaml # activate advanced (legacy) elements - can be useful for troubleshooting
      # - nspanel_esphome_addon_climate_cool.yaml # activate for local climate (cooling) control
      # - nspanel_esphome_addon_climate_heat.yaml # activate for local climate (heater) control
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####

##### My customization - Start #####

# Set IP address manually
wifi:
  networks:
    - id: !extend wifi_default
      manual_ip:
        static_ip: 192.168.0.102
        gateway: 192.168.0.1
        subnet: 255.255.255.0

# Custom Arduino framework enforcement 
esp32:
  framework:
    type: arduino      

##### My customization - End #####
```

### ESPHome Logs

[logs_nsbathroom_logs (1).txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/14725738/logs_nsbathroom_logs.1.txt)

### Home Assistant Logs

no error in logs just get this notification

NSPanel component version mismatch
There's a version mismatch between NSPanel_HA_Blueprint components. Please update all the components to the same version.

Panel:

TFT: 4.2.6

ESPHome: 4.3.1

Blueprint (reported by ESPHome): 4.3.1

Blueprint (installed): 4.3.1
