### ISSUE TITLE
`Bug` Can't build with ESPHome 2024.3.0

### ISSUE THREAD

**Issue by X-Ryl669** [Blackymas/NSPanel_HA_Blueprint#1975]
### TFT Version

latest

### ESPHome Version

latest

### Blueprint Version

latest

### Panel Model

EU

### What is the bug?

When trying to build with latest ESPHome version, it fails with this log:
```
/data/packages/566b10a3/advanced/esphome/nspanel_esphome_core.yaml: In lambda function:
/data/packages/566b10a3/advanced/esphome/nspanel_esphome_core.yaml:2818:73: error: 'get_ip_address' is not a member of 'esphome::network'
                         disp1->set_component_text_printf("boot.ip_addr", "%s", network::get_ip_address().str().c_str());
                                                                         ^~~~~~~~~~~~~~
/data/packages/566b10a3/advanced/esphome/nspanel_esphome_core.yaml:2818:73: note: suggested alternative: 'get_ip_addresses'
                         disp1->set_component_text_printf("boot.ip_addr", "%s", network::get_ip_address().str().c_str());
                                                                         ^~~~~~~~~~~~~~
                                                                         get_ip_addresses
```

### Your Panel's YAML

```yaml
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      - advanced/esphome/nspanel_esphome_advanced.yaml # activate advanced (legacy) elements - can be useful for troubleshooting
    refresh: 300s

##### My customization - Start #####
wifi:
  networks:
    - id: !extend wifi_default
      ssid: ${wifi_ssid}
      password: ${wifi_password}
      ##### advanced config - uncomment to use static IP-Config #####
      manual_ip:
        static_ip: ${ip}
        gateway: ${gw}
        subnet: ${subnet}
        dns1: ${dns}
  # domain: ${domain}
  ##### Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${device_name}"
    password: ${wifi_password}

ota:
  password: ${ota_password}

api:
  encryption:
    key: ${api_password}

esp32:
  framework:
    type: esp-idf
  flash_size: 4MB
  partitions: "nspanel1_part.csv"
##### My customization - End #####
```
