### ISSUE TITLE
No "Update TFT display" in configuarion 4.3.1 after succesful update

### ISSUE THREAD

**Issue by rucati** [Blackymas/NSPanel_HA_Blueprint#2002]
### TFT Version

4.2.4

### ESPHome Version

4.3.1 on my  Esphome 2024.3.1

### Blueprint Version

4.3.1

### Panel Model

EU

### What is the bug?

I cannot update TFT to version 4.3.1, so I end up with a version mismatch. I should be able to do this via the config, but this option is not available:
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/16360112/98da12af-2767-42e3-8aa5-61ba289ee87e)

### Your Panel's YAML
I do a direct update for the next_update_url, but I also tried a local update and the eu-tft is in my local HA available.

```yaml
substitutions:
  # Settings - Editable values
  device_name: "nspanel1" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  nextion_update_url: "https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/hmi/nspanel_blank.tft"  # Optional for `esp-idf` framework
  #nextion_update_url: "http://prodesk:8123/local/nspanel_eu.tft"  # Optional for `esp-idf` framework
  # Add-on configuration (if needed)
  # heater_relay: "1"  # Possible values: "1" or "2"

# Customization area
##### My customization - Start #####
##### My customization - End #####

# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: v4.3.1
    files:
      - esphome/nspanel_esphome_core.yaml # Core package
      # Optional advanced and add-on configurations
      - esphome/nspanel_esphome_advanced.yaml
      # - nspanel_esphome_addon_climate_cool.yaml
      - esphome/nspanel_esphome_addon_climate_heat.yaml
      # - nspanel_esphome_addon_climate_dual.yaml
      # Optional TFT-fonts
      #- esphome/nspanel_esphome_addon_upload_tft.yaml
    refresh: 300s

esp32:
  framework:
    type: esp-idf
```

### ESPHome Logs

[09:09:40][W][nextion:405]: Nextion reported variable name invalid!
Probably because of the version mismatch
