### ISSUE TITLE
Frage zu Notifications

### ISSUE THREAD

**Issue by MarkuZP** [Blackymas/NSPanel_HA_Blueprint#201]
Ist es auch möglich anstatt von statischem Text das Ergebnis einer Abfrage (wie bei Lovelace) darzustellen?
Ich habe hier z.B erfolglos den Müllkalender versucht, der in Lovelace super läuft.
<img width="531" alt="Bildschirm­foto 2023-01-19 um 20 36 12" src="https://user-images.githubusercontent.com/109298227/213543451-231733f0-b804-4f29-bc6f-ff396ea0218c.png">

**Comment by Blackymas** [comment]
hab ich ehrlich gesagt noch garnicht probiert.

Weil eigentlich löst du das ja in einer Automation um die Notification los zu schicken.

Daher hast du ja in der Automation schon deinen trigger und weißt ja um was es geht oder wieviele tage es noch sind.

Daher kannst du den Text ja selbst rein schreiben.


Wäre ja auch bei der Klingel so.

Trigger Klingel Terrasse löst aus - dann weis ich in der automation das es die Terrasse und nicht die Haustür ist. Und kann man text schreiben wie ich ihn brauche.

Wie gesagt muss ich testen

**Comment by deejaybeam** [comment]
Ja - warum nicht?
```
service: esphome.nspanel01_notification_show
data:
  label: Notification
  text: "{{ ((as_timestamp(now())) | timestamp_custom('%a %d.%m' )) | replace('Mon', 'Δευτέρα,')| replace('Tue', 'Τρίτη,')| replace('Wed', 'Τετάρτη,')| replace('Thu', 'Πέμπτη,')| replace('Fri', 'Παρασκευή,')| replace('Sat', 'Σάββατο,')| replace('Sun', 'Κυριακή,') }}"
```
Das template wird ja von HA gerendert - dann wird der "fertige" text zum Panel gesendet
