### ISSUE TITLE
`Bug` error: 'get_ip_address' is not a member of 'esphome::network'

### ISSUE THREAD

**Issue by willemvdvliet** [Blackymas/NSPanel_HA_Blueprint#2011]
### TFT Version

4.3.2

### ESPHome Version

2024.3.1

### Blueprint Version

4.3.2

### Panel Model

EU

### What is the bug?

Updating to 4.3.2 beta

Resulting in the following error:
*** [.pioenvs/nspanelzolder/src/main.o] Error 1

Archiving .pioenvs/nspanelzolder/esp-idf/bootloader_support/libbootloader_support.a
/data/packages/b62d81b2/advanced/esphome/nspanel_esphome_core.yaml: In lambda function:
/data/packages/b62d81b2/advanced/esphome/nspanel_esphome_core.yaml:2818:73: error: 'get_ip_address' is not a member of 'esphome::network'
                         disp1->set_component_text_printf("boot.ip_addr", "%s", network::get_ip_address().str().c_str());
                                                                         ^~~~~~~~~~~~~~
/data/packages/b62d81b2/advanced/esphome/nspanel_esphome_core.yaml:2818:73: note: suggested alternative: 'get_ip_addresses'
                         disp1->set_component_text_printf("boot.ip_addr", "%s", network::get_ip_address().str().c_str());
                                                                         ^~~~~~~~~~~~~~
                                                                         get_ip_addresses

### Steps to Reproduce

1. Update NS Panel blue print;
2. Opened ESP Home and selected the panel;
3. Performed a Clean build files;
4. Install (wirelessly) the new build 

### Your Panel's YAML

```yaml
substitutions:

###### CHANGE ME START ######

  device_name: "nspanelzolder" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: "http://192.168.100.233:8123/local/nspanel_eu.tft" # URL to local tft File
  #nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/beta/nspanel_eu.tft" # URL to Github

web_server:
  port: 80
  auth:
    username: admin
    password: ${wifi_password}
    ##### advanced config - change to use web_password ##### 
    # password: ${web_password}

wifi:
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.100.31
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.100.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0
    dns1: 192.168.100.1
    dns2: 192.168.100.1

##### CHANGE ME END #####

##### DO NOT CHANGE ANYTHING! #####

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: beta
    files:
      - nspanel_esphome.yaml # Core package
      - advanced/esphome/nspanel_esphome_advanced.yaml # activate advanced (legacy) elements - can be useful for troubleshooting
      - nspanel_esphome_addon_climate_heat.yaml # activate for local climate (heater) control

esp32:
  framework:
    type: esp-idf

##### DO NOT CHANGE ANYTHING! #####
```

**Comment by edwardtfn** [comment]
For some reason your system isn't using the latest code. Clean build files should have fixed the issue. 😩

Do you have any error message when cleaning build files?
Could you please change from `ref: beta` to `ref: main` and let me know if the issue persists? This shoukd force a new download of the files.

**Comment by edwardtfn** [comment]
Please try this:

```yaml
substitutions:

###### CHANGE ME START ######

  device_name: "nspanelzolder" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: "http://192.168.100.233:8123/local/nspanel_eu.tft" # URL to local tft File
  #nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/beta/nspanel_eu.tft" # URL to Github

web_server:
  port: 80
  auth:
    username: admin
    password: ${wifi_password}
    ##### advanced config - change to use web_password ##### 
    # password: ${web_password}

wifi:
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.100.31
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.100.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0
    dns1: 192.168.100.1
    dns2: 192.168.100.1

##### CHANGE ME END #####

##### DO NOT CHANGE ANYTHING! #####

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    refresh: 3s
    files:
      - nspanel_esphome.yaml # Core package
      - advanced/esphome/nspanel_esphome_advanced.yaml # activate advanced (legacy) elements - can be useful for troubleshooting
      - nspanel_esphome_addon_climate_heat.yaml # activate for local climate (heater) control
```
