### ISSUE TITLE
`Bug` The sensor "Current Page" is unavailable.

### ISSUE THREAD

**Issue by MichalAug** [Blackymas/NSPanel_HA_Blueprint#2026]
### TFT Version

4.3.2

### ESPHome Version

3.4.1 (2024.3.1)

### Blueprint Version

4.3.2

### Panel Model

EU

### What is the bug?

Hi Guys. This situation makes me cry. I have been a Blackymas user for a long time, but this time I can't figure out what's going on.
I got issue in HA:

> The automation "NSPanel Configuration - tvroom" (automation.nspanel_configuration_tvroom) has an action that calls an unknown service: esphome.nspaneltvroom_component_text.
> This error prevents the automation from working properly. Maybe this service is no longer available, or maybe it was a typo.
> To fix this error, edit the automation and remove the activity that calls this service.
> Click COMMIT below to confirm that you have fixed this automation.

And:

> NSPanel sensor unavailable
> The sensor "Current Page" (sensor.nspaneltvroom_current_page) is unavailable.
> Panel: Nspaneltvroom (nspaneltvroom)
> Blueprint version: 4.3.2
> Sensor's expected entity_id: sensor.nspaneltvroom_current_page
> How to fix this:
> Go to the [device page](http://192.168.2.100:8123/config/devices/device/a47152d6075d3605b05b58210651fc8a)
> Find the sensor "Current page" under the "Sensors" area (it might be in the "sensors not shown" group)
> Enable the sensor
> Wait a bit until the sensor starts providing a value (it shouldn't take more than half minute)
> Go to [Developer Tools](http://192.168.2.100:8123/developer-tools/yaml) and click the button "Automations" to reload your automations

(but there is no sensor available)

In ESPHome nspanel log I have such entries:
[20:42:59][W][nextion:317]: Nextion reported invalid instruction!
[20:45:01][W][nextion:396]: Nextion reported variable name invalid!
[20:45:01][W][nextion:396]: Nextion reported variable name invalid!
[20:45:01][W][nextion:396]: Nextion reported variable name invalid!
[20:45:01][W][nextion:396]: Nextion reported variable name invalid!
[20:45:01][W][nextion:396]: Nextion reported variable name invalid!
[20:45:01][W][nextion:396]: Nextion reported variable name invalid!
[20:49:36][W][nextion:317]: Nextion reported invalid instruction!
[20:49:36][E][nextion:260]: Nextion queue is empty!

I've  tried to remove every autiomations, esp devices, HA restart, nothing helps. 
Sometimes NSPanel shows the ESPHome version, sometimes it doesn't, sometimes it shows the IP, sometimes it doesn't. 
It worked once, but after the reset it doesn't work again. When I reset with the button, the screen brightness settings appear, but after reboot the initialization screen returns.

![Zrzut ekranu 2024-04-08 223826](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/104733541/2df6762d-2f47-465a-98eb-a3d3ddc51e16)
![Zrzut ekranu 2024-04-08 225014](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/104733541/55284025-1b16-4800-8d32-3780f902ac68)
![Zrzut ekranu 2024-04-08 225028](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/104733541/67bde698-75f7-4664-b611-04f2677aaceb)
![Zrzut ekranu 2024-04-08 225038](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/104733541/30a812d5-4a9e-4956-9f78-46d7bc442a54)
![IMG_20240408_225304](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/104733541/35de2ff1-4b32-4d6e-b06d-8b7fa986a8af)
![IMG_20240408_225316](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/104733541/681cdfd5-4c37-4c7c-84d5-6b5e66651001)

### Your Panel's YAML

```yaml
substitutions:
  # Settings - Editable values
  device_name: "nspaneltvroom"
  friendly_name: "NSPanel TV Room"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  nextion_update_url: "http://192.168.2.100:8123/local/nspanel_eu.tft"  # Optional
  # Add-on configuration (if needed)
  # heater_relay: "1"  # Possible values: "1" or "2"

# Customization area
##### My customization - Start #####
##### My customization - End #####

# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    refresh: 300s
    files:
      - nspanel_esphome.yaml # Basic package
      # Optional advanced and add-on configurations
      # - esphome/nspanel_esphome_advanced.yaml
      # - nspanel_esphome_addon_climate_cool.yaml
      # - nspanel_esphome_addon_climate_heat.yaml
      # - nspanel_esphome_addon_climate_dual.yaml
```
