### ISSUE TITLE
Issue with climate Add-on: Climate - multiple issues identified. 

### ISSUE THREAD

**Issue by zembrzycki** [Blackymas/NSPanel_HA_Blueprint#2063]
### TFT Version

4.3.4

### ESPHome Version

4.3.4

### Blueprint Version

4.3.4

### Panel Model

US

### What is the bug?

-  When used for cooling, Relay 2 will turn on based on temperature change, but will not switch back off although the snowflake reverts back to a thermometer.  I can manually control the relay under devices and control and turn it off.  
Does not appear to be an issue if I set cooler_relay: "1", in the ESP Home yaml. 

- target_low:   appears to be a required override in the ESP yaml, otherwise compiling fails when calling "nspanel_esphome_addon_climate_dual.yamll", however not an issue using "nspanel_esphome_addon_climate_cool.yaml"

- In the climate card when I increase or decrease the temperature using the "+" or "-", the set point appears to step in increments of (0.9) so there may be a round down error opposed to a round up to the nearest integer, so I tend to get some odd temperature set points in roundoff of multiples of 0.9. 

- Internal temperature sensors does not get converted from C to F, automatically when displaying to the panel. 
climate.nspx_thermostat entity reads correctly in HA Developer tools as 73.2 F, but when I use that variable on the nspanel, home display it reads out as 22.8 F.  I have, of course have "temp_units: "°F" , defined in my yaml.  
Thinking I could create a template sensor to convert from degree C to F.

### Steps to Reproduce

Use Case: use nspanel for local control of water heating/cooling system. 

NSPannel running 4.3.4, with default blueprint. 
ESP Home yaml below for reference. 

### Your Panel's YAML

```yaml
substitutions:
  # Settings - Editable values
  device_name: "nsp3" 
  wifi_ssid: 
  wifi_password: 

  # Add-on configuration (if needed)
  ## Add-on climate
  heater_relay: "1"     # Possible values: "1" or "2"
  cooler_relay: "1"     # Possible values: "1" or "2"
  temp_units: "°F"      # Temperatures in Fahrenheit
  min_off_time: "3"     # Minimum duration (in seconds) the cooling/heating action must be disengaged before it may be engaged.
  min_run_time: "3"     # Minimum duration (in seconds) the cooling/heating action must be engaged before it may be disengaged.
  min_idle_time: "3"    # Minimum duration (in seconds) the idle action must be active before calling another climate action.
  temp_min: "65"        # Min supported temperature is 40°F
  temp_max: "80"        # Max supported temperature is 80°F
  temp_step: "1"        # Temperature granularity is 1°F
  cool_deadband: "1.2"  # Temperature delta before engaging cooling
  cool_overrun: "1.2"   # Temperature delta before disengaging cooling
  heat_deadband: "1.2"  # Temperature delta before engaging heat
  heat_overrun: "1.2"   # Temperature delta before disengaging heat
  target_low: "74"      # The initial lower treshold for the target temperature.
  target_high: "74"     # The initial higher threshold for the target temperature.

# Basic and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Basic package
      # Optional advanced and add-on configurations
      # - esphome/nspanel_esphome_advanced.yaml
      - nspanel_esphome_addon_climate_cool.yaml
      # - nspanel_esphome_addon_climate_heat.yaml
      # - nspanel_esphome_addon_climate_dual.yaml
    refresh: 300s
```
