### ISSUE TITLE
Utility and climate panels not accessible

### ISSUE THREAD

**Issue by proasnet** [Blackymas/NSPanel_HA_Blueprint#2073]
### TFT Version

4.3.4

### ESPHome Version

4.3.4

### Blueprint Version

4.3.4

### Panel Model

EU

### What is the bug?

With the new sonnoff reflashed panel, is not accessible Climate and Utility panels.

### Steps to Reproduce

nothing

### Your Panel's YAML

```yaml
alias: NSPanel Obývák 1NP
description: ""
use_blueprint:
  path: Blackymas/nspanel_blueprint.yaml
  input:
    nspanel_name: 512f12124a318e676451a62328293181
    language: cs
    timezone: Europe/Prague (CET-1CEST,M3.5.0,M10.5.0/3)
    weather_entity: weather.domov
    outdoortemp: sensor.bsb_lan_outside_temperature
    indoortemp: sensor.nspanel_obyvak_1np_temperature
    home_custom_button01_icon: ""
    home_custom_button02_icon: ""
    home_custom_button03_icon: ""
    home_custom_button04_icon: ""
    hw_buttons_bars_pages:
      - "2"
      - "61440"
      - "3932160"
      - "65536"
      - "131072"
      - "512"
      - "256"
      - "134217728"
      - "124"
      - "8388608"
      - "128"
      - "2048"
      - "4194304"
      - "1024"
      - "67108864"
      - "16777216"
      - "33554432"
    hw_button_bar_left_always_show: true
    left_button_entity: light.rgbcw_obyvak_1np
    left_button_name: ZAP/VYP
    left_button_hold_select: Default
    home_outdoor_temp_label_color:
      - 0
      - 128
      - 255
    home_indoor_temp_icon_color:
      - 255
      - 255
      - 0
    climate: climate.termostat_obyvak_1np_termostat
    climate_button08: switch.termostat_obyvak_1np_vypinac
    climate_button08_icon: mdi:thermometer-chevron-up
    climate_button08_icon_color:
      - 255
      - 0
      - 0
    left_button_hold_custom_action: []
    right_button_name: 1 MIN
    right_button_hold_select: Default
    right_button_hold_custom_action: []
    right_button_state_entity: light.rgbcw_obyvak_1np
    right_button_color:
      - 0
      - 255
      - 255
    left_button_state_entity: light.rgbcw_obyvak_1np
    left_button_color:
      - 0
      - 255
      - 255
    home_value01: binary_sensor.input_0
    home_value01_label_color:
      - 0
      - 0
      - 255
    home_value01_icon: mdi:minus-circle-multiple-outline
    home_value02: binary_sensor.inverter_1_battery_mode
    home_value02_label_color:
      - 0
      - 255
      - 0
    home_value02_icon: mdi:battery-50
    button_pages_icon_size: "10"
    button_page01_label: Scény
    entity01: scene.obyvak_1np_bila
    entity01_name: Bila
    entity01_icon_color:
      - 255
      - 255
      - 255
    entity02: scene.obyvak_1np_sky
    entity02_name: More
    entity03: scene.obyvak_1np_ruzova
    entity03_name: Ruzova
    entity03_icon_color:
      - 207
      - 139
      - 196
    entity04: scene.obyvak_1np_cervena
    entity04_name: Cervena
    entity04_icon_color:
      - 255
      - 0
      - 0
    entity05: scene.obyvak_1np_zelena
    entity05_name: Zelena
    entity05_icon: ""
    entity05_icon_color:
      - 0
      - 255
      - 0
    entity06: scene.obyvak_1np_modra
    entity06_name: Modra
    entity06_icon_color:
      - 0
      - 0
      - 255
    chip01: binary_sensor.input_0
    utilities_page01_label: Distribuce energie
    utilities_page01_grid_value1: sensor.sum_line_energy
    utilities_page01_group01_value1: sensor.co2_intensity
    utilities_page01_group01_value2: sensor.grid_fossil_fuel_percentage
    utilities_page01_group03_label: PV Energy
    utilities_page01_group03_value1: sensor.sum_pv_energy
    utilities_page01_group01_label: Line Energy
    utilities_page01_group04_label: Battery Energy
    utilities_page01_group04_value1: sensor.bms_charging_energy
    utilities_page01_group04_value2: sensor.bms_discharging_energy
    utilities_page01_group05_label: Spotřeba plynu
    utilities_page01_group05_value1: sensor.gas_used
    utilities_page01_group06_label: Spotřeba vody
    utilities_page01_group06_icon: mdi:water
    utilities_page01_group05_icon: mdi:fire
    utilities_page01_group06_value1: sensor.water_used
    utilities_page01_group06_color:
      - 0
      - 0
      - 255
    utilities_page01_group05_color:
      - 255
      - 0
      - 0
    utilities_page01_group04_color:
      - 255
      - 128
      - 128
    utilities_page01_group03_color:
      - 255
      - 128
      - 0
    utilities_page01_group01_color:
      - 0
      - 255
      - 0
    utilities_page01_grid_color:
      - 0
      - 128
      - 255
    utilities_page01_group04_line_reference: sensor.bms_charging_current
    utilities_page01_group03_line_reference: sensor.sum_pv_current
    climate_chip_always_visible: true
```

**Comment by MichaelHeimann** [comment]
You posted the yaml of the blueprint. (which is missing 
`utilities_enabled: true`
or this switch enabled here via UI:
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/3189562/4b946ca6-780c-487e-89a6-145b64bd3943)

Can you post the esphome yaml where you added the climate addon?

**Comment by proasnet** [comment]
Thank you for reply. Utility I had disabled, now are accessible.
Climate not, I attaching a yaml of ESP here.
```
substitutions:
  # Settings - Editable values
  name: nspanel-obyvak-1np
  friendly_name: NSPanel Obývák 1NP
  wifi_ssid: !secret wifi_ssid_1
  wifi_password: !secret wifi_password
  nextion_update_url: "http://homeassistant.local:8123/local/nspanel_eu.tft"  # Optional
  # Add-on configuration (if needed)
  # heater_relay: "1"  # Possible values: "1" or "2"

# Customization area
##### My customization - Start #####
##### My customization - End #####

# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    refresh: 300s
    files:
      - nspanel_esphome.yaml # Basic package
      # Optional advanced and add-on configurations
      - esphome/nspanel_esphome_advanced.yaml
      # - nspanel_esphome_addon_climate_cool.yaml
      - nspanel_esphome_addon_climate_heat.yaml
      # - nspanel_esphome_addon_climate_dual.yaml
```
