### ISSUE TITLE
web_server component not working

### ISSUE THREAD

**Issue by afarago** [Blackymas/NSPanel_HA_Blueprint#2076]
### TFT Version

4.3.2

### ESPHome Version

2024.4.1

### Blueprint Version

4.3.4

### Panel Model

EU

### What is the bug?

web_server component is not working, even after boot and HA connection the specific IP address refuses to connect.

web_server is working for many of my other nodes and have been working until ~4-6 weeks ago.

### Steps to Reproduce

Compile, install with success and navigate to the IP address of the node.

### Your Panel's YAML

```yaml
packages:
  NSPanel_HA_Blueprint:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Basic package
      - esphome/nspanel_esphome_advanced.yaml
    refresh: 300s

-----------

#Also tried

##### IMPORT PACKAGES #####
packages:
  NSPanel_HA_Blueprint:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Basic package
    refresh: 300s

web_server:
    port: 80
```

### ESPHome Logs

INFO ESPHome 2024.4.1
INFO Reading configuration /config/esphome/dining-nspanel.esp32dev.yaml...
INFO Updating https://github.com/Blackymas/NSPanel_HA_Blueprint@main
INFO Updating https://github.com/Blackymas/NSPanel_HA_Blueprint@v4.3.4
INFO Updating https://github.com/edwardtfn/esphome@nextion-v432
INFO Updating https://github.com/edwardtfn/esphome@adc-sampling
INFO Detected timezone 'Europe/Budapest'
INFO Starting log output from 192.168.0.64 using esphome API
INFO Successfully connected to nspanel-diningroom @ 192.168.0.64 in 0.108s
INFO Successful handshake with nspanel-diningroom @ 192.168.0.64 in 0.028s
[18:50:15][I][app:100]: ESPHome version 2024.4.1 compiled on Apr 24 2024, 18:40:31
[18:50:30][I][script.watchdog:3197]: Wi-Fi:         Good (-54 dBm)
[18:50:30][I][script.watchdog:3210]: API:           Connected
[18:50:30][I][script.watchdog:3228]: Blueprint:
[18:50:30][I][script.watchdog:3230]:   Version:     4.3.4
[18:50:30][I][script.watchdog:3231]:   Init steps:  62 (100.0%)
[18:50:30][I][script.watchdog:3240]: ESPHome:
[18:50:30][I][script.watchdog:3241]:   Version:     4.3.4
[18:50:30][I][script.watchdog:3242]:   Compiler:    2024.4.1
[18:50:30][I][script.watchdog:3247]:   Framework:   ESP-IDF
[18:50:30][I][script.watchdog:3254]:   Free heap:
[18:50:30][I][script.watchdog:3258]:     Internal:   200116 bytes (56.9%)
[18:50:30][I][script.watchdog:3265]:     PSRAM:     2019151 bytes (96.8%)
[18:50:30][I][script.watchdog:3270]: UART:
[18:50:30][I][script.watchdog:3271]:   Baud rate:   115200 bps
[18:50:30][I][script.watchdog:3272]:   Queue size:  0
[18:50:30][I][script.watchdog:3276]: Nextion:
[18:50:30][I][script.watchdog:3277]:   Queue size:  0
[18:50:30][I][script.watchdog:3279]:   Is setup:    True
[18:50:30][I][script.watchdog:3286]:   Init:        True
[18:50:30][I][script.watchdog:3292]:   TFT:         4.3.2
[18:50:30][I][script.watchdog:3293]: Packages:
[18:50:30][I][script.watchdog:3295]:   - Core
[18:50:30][I][script.watchdog:3298]:   - Advanced
[18:50:30][I][script.watchdog:3301]:   - Upload TFT
[18:50:30][I][script.watchdog:3322]: Non-standard components:
[18:50:30][I][script.watchdog:3324]:   - Captive portal
[18:50:30][I][script.watchdog:3330]:   - Web server
[18:50:30][I][addon_upload_tft.script.watchdog:370]: Add-on Upload TFT:
[18:50:30][I][addon_upload_tft.script.watchdog:371]:   File model: NSPanel EU
[18:50:30][I][addon_upload_tft.script.watchdog:372]:   Valid TFT:  YES

### Home Assistant Logs

no relevant log entry available
