### ISSUE TITLE
Climate Page not showing`Bug` 

### ISSUE THREAD

**Issue by malgates** [Blackymas/NSPanel_HA_Blueprint#2092]
### TFT Version

4.3.4

### ESPHome Version

4.3.4

### Blueprint Version

4.3.7

### Panel Model

EU

### What is the bug?

Climate Page not showing. Maybe bad configuration. Everytime I press the Climate Button the following logs appear:

[23:40:47][D][nextion:446]: Got touch event:
[23:40:47][D][nextion:447]:   page_id:      1
[23:40:47][D][nextion:448]:   component_id: 0
[23:40:47][D][nextion:449]:   event type:   PRESS
[23:40:47][D][script:077]: Script 'timer_dim' restarting (mode: restart)
[23:40:47][D][script:077]: Script 'timer_sleep' restarting (mode: restart)
[23:40:48][D][nextion:446]: Got touch event:
[23:40:48][D][nextion:447]:   page_id:      1
[23:40:48][D][nextion:448]:   component_id: 0
[23:40:48][D][nextion:449]:   event type:   RELEASE
[23:40:48][D][script:077]: Script 'timer_dim' restarting (mode: restart)
[23:40:48][D][script:077]: Script 'timer_sleep' restarting (mode: restart)

### Steps to Reproduce

Climate Entity not shwoing
Updated the NSPanel to 4.3.7
Still not showing

### Your Panel's YAML

```yaml
substitutions:
  # Settings - Editable values
  device_name: "nspanelwozi"
  friendly_name: "NS Panel Wohnzimmer"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  nextion_update_url: "http://homeassistant.local:8123/local/nspanel_eu.tft"  # Optional
  # Add-on configuration (if needed)
  heater_relay: "1"  # Possible values: "1" or "2"
  temp_min: "15" 
  temp_max: "23" 
  temp_step: "0.1"
  cold_tolerance: "0.1"
  hot_tolerance: "0.1"

climate:
  - id: !extend thermostat_embedded
    visual:
      temperature_step: ${temp_step}
    preset:
      - name: Home
        default_target_temperature_low: 19.0
        mode: "heat"
# Customization area
##### My customization - Start #####
##### My customization - End #####

# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    refresh: 300s
    files:
      - nspanel_esphome.yaml # Basic package
      # Optional advanced and add-on configurations
      # - esphome/nspanel_esphome_advanced.yaml
      # - nspanel_esphome_addon_climate_cool.yaml
      - nspanel_esphome_addon_climate_heat.yaml
      # - nspanel_esphome_addon_climate_dual.yaml
```

### ESPHome Logs

[23:39:55][D][sensor:094]: 'ntc_source': Sending state 1.71317 V with 2 decimals of accuracy
[23:39:55][D][resistance:039]: 'resistance_sensor' - Resistance 12091.7Ω
[23:39:55][D][sensor:094]: 'resistance_sensor': Sending state 12091.67188 Ω with 1 decimals of accuracy
[23:39:55][D][ntc:026]: 'Temperature' - Temperature: 20.8°C
[23:39:55][D][sensor:094]: 'Temperature': Sending state 20.78605 °C with 1 decimals of accuracy
[23:39:55][D][climate:396]: 'Thermostat' - Sending state:
[23:39:55][D][climate:399]:   Mode: HEAT
[23:39:55][D][climate:401]:   Action: IDLE
[23:39:55][D][climate:419]:   Current Temperature: 20.79°C
[23:39:55][D][climate:425]:   Target Temperature: 21.10°C
[23:39:58][D][nextion:446]: Got touch event:
[23:39:58][D][nextion:447]:   page_id:      9
[23:39:58][D][nextion:448]:   component_id: 0
[23:39:58][D][nextion:449]:   event type:   PRESS
[23:39:58][D][nextion:446]: Got touch event:
[23:39:58][D][nextion:447]:   page_id:      9
[23:39:58][D][nextion:448]:   component_id: 0
[23:39:58][D][nextion:449]:   event type:   RELEASE
[23:39:58][D][script:077]: Script 'timer_dim' restarting (mode: restart)
[23:39:58][D][text_sensor:064]: 'Current Page': Sending state 'home'
[23:39:58][D][script.page_changed:2377]: New page: home
[23:39:58][D][text_sensor:064]: 'Detailed Entity': Sending state ''
[23:39:58][D][script:077]: Script 'timer_dim' restarting (mode: restart)
[23:39:58][D][script.timer_dim:3007]: Waking up on page: home
[23:39:58][D][nextion_textsensor:014]: Processed text_sensor "current_page" state "home"
[23:39:58][D][sensor:094]: 'Display Current brightness': Sending state 0.00000 % with 0 decimals of accuracy
[23:39:59][D][nextion:446]: Got touch event:
[23:39:59][D][nextion:447]:   page_id:      1
[23:39:59][D][nextion:448]:   component_id: 27
[23:39:59][D][nextion:449]:   event type:   PRESS
[23:39:59][D][script:077]: Script 'timer_dim' restarting (mode: restart)
[23:39:59][D][script.timer_dim:3007]: Waking up on page: home
[23:39:59][D][script:077]: Script 'set_brightness' restarting (mode: restart)
[23:39:59][D][script:077]: Script 'timer_sleep' restarting (mode: restart)
[23:39:59][D][sensor:094]: 'Display Current brightness': Sending state 44.00000 % with 0 decimals of accuracy
[23:40:00][D][nextion:446]: Got touch event:
[23:40:00][D][nextion:447]:   page_id:      1
[23:40:00][D][nextion:448]:   component_id: 27
[23:40:00][D][nextion:449]:   event type:   RELEASE
[23:40:00][D][script:077]: Script 'timer_dim' restarting (mode: restart)
[23:40:00][D][script:077]: Script 'timer_sleep' restarting (mode: restart)
[23:40:04][D][sensor:094]: 'Display Current brightness': Sending state 100.00000 % with 0 decimals of accuracy
[23:40:05][D][sensor:094]: 'ntc_source': Sending state 1.71383 V with 2 decimals of accuracy
[23:40:05][D][resistance:039]: 'resistance_sensor' - Resistance 12101.5Ω
[23:40:05][D][sensor:094]: 'resistance_sensor': Sending state 12101.46094 Ω with 1 decimals of accuracy
[23:40:05][D][ntc:026]: 'Temperature' - Temperature: 20.8°C
[23:40:05][D][sensor:094]: 'Temperature': Sending state 20.76836 °C with 1 decimals of accuracy
[23:40:05][D][climate:396]: 'Thermostat' - Sending state:
[23:40:05][D][climate:399]:   Mode: HEAT
[23:40:05][D][climate:401]:   Action: IDLE
[23:40:05][D][climate:419]:   Current Temperature: 20.77°C
[23:40:05][D][climate:425]:   Target Temperature: 21.10°C
