### ISSUE TITLE
unable to retrieve the blueprint due to authentication expired

### ISSUE THREAD

**Issue by bentouspam** [Blackymas/NSPanel_HA_Blueprint#2099]
### TFT Version

4.3.7

### ESPHome Version

4.3.7

### Blueprint Version

Version: v4.3.7

### Panel Model

EU

### What is the bug?

Blueprint version mismatch (the file and the version are correct, but the nspannel cannot read it.)
there is a message in HA : 
_The ESPHome device nspanelbenoit enabled transport encryption or changed the encryption key. Please enter the updated key._

but the key is unknown to me...

I have 3 nspanel (with quite the same configuration), only this one could not be upgraded to the latest versions 

## System Information

version | core-2024.5.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.1.73-haos-raspi
arch | aarch64
timezone | Europe/Paris
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4761
Installed Version | 1.34.0
Stage | running
Available Repositories | 1402
Downloaded Repositories | 44

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | December 19, 2024 at 01:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | eu-central-1-2.ui.nabu.casa
certificate_status | ready
instance_id | ac9ac8ddbfe9468f950a04eac5615569
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.2
-- | --
update_channel | stable
supervisor_version | supervisor-2024.04.4
agent_version | 1.6.0
docker_version | 25.0.5
disk_total | 457.7 GB
disk_used | 24.8 GB
healthy | true
supported | true
board | rpi5-64
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.13.0), Mosquitto broker (6.4.0), Samba share (12.3.1), ESPHome (2024.4.2), SQLite Web (4.1.2), chrony (3.0.1), Zigbee2MQTT (1.37.0-1), Home Assistant Google Drive Backup (0.112.1), Studio Code Server (5.15.0), OpenThread Border Router (2.6.0), Matter Server (5.6.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 11
-- | --
resources | 30
views | 48
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | April 12, 2024 at 06:57
-- | --
current_recorder_run | May 2, 2024 at 16:31
estimated_db_size | 1671.94 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Your Panel's YAML

```yaml
### esphome file /  nspanelbenoit.yaml
substitutions:
  ###### CHANGE ME START ######
  device_name: "nspanelbenoit"
  comment: NsPanel Salon
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: "http://homeassistant.local:8123/local/nspanel_eu.tft"

  ##### addon-configuration #####
  ## addon_climate ##
  # addon_climate_heater_relay: "1" # possible values: 1/2

  ##### CHANGE ME END #####

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # - nspanel_esphome_advanced.yaml # activate advanced (legacy) elements - can be useful for troubleshooting
      # - nspanel_esphome_addon_climate_cool.yaml # activate for local climate (cooling) control
      # - nspanel_esphome_addon_climate_heat.yaml # activate for local climate (heater) control
    refresh: 300s

esp32:
  framework:
    type: esp-idf

##### My customization - Start #####
web_server:
  port: 80
##### My customization - End #####


### automation file /  extract nspanelbenoit
- id: '1702833986807'
  alias: NSPanel Benoit Configuration
  description: config benoit
  use_blueprint:
    path: Blackymas/nspanel_blueprint.yaml
    input:
      nspanel_name: 326559f434cb8b78cc476d09cfb2ae99
      language: fr
      date_format: '%A, %d.%m'
      weather_entity: weather.boulogne_billancourt
      outdoortemp: sensor.atc_romain_9d23_temperature
      indoortemp: sensor.atc_parents_temperature
      left_button_entity: light.liseuse_benoit
      chip05_icon: mdi:lightbulb-group
      right_button_name: 'Extinction '
      home_custom_button02: light.bureau
      home_custom_button01: light.ac_02182e3_2
      home_custom_button03: cover.volets_benoit
      left_button_name: 'Liseuse '
      home_value02_icon: mdi:molecule-co2
      home_custom_button01_icon: mdi:light-recessed
      home_custom_button02_icon: mdi:led-strip
      home_custom_button03_icon: mdi:blinds
      chip_font_size: '7'
      right_button_hold_select: Custom Action
      media_player_update_delay: 500
      button_page01_label: ButtonPage01
      entity01: light.liseuse_sandrine
      entity02_name: Ventilateur
      entity02_icon_color:
      - 54
      - 250
      - 0
      entity02_icon: mdi:fan
      entity04_icon: mdi:led-strip
      entity03_icon: mdi:light-recessed
      entity05: light.rgb_ecrans
      entity06: light.rgb_retro_tv
      entity07_icon: mdi:printer-3d
      entity08: switch.bouilloire
      chip01: binary_sensor.capteur_wc_occupancy
      chip02_icon: mdi:cupboard
      chip02: binary_sensor.presence_placard_occupancy
      chip03: light.rgb_tv_salon
      chip04_icon: mdi:fire-alert
      chip05: light.groupe_ampoules_couloir
      chip06: light.groupe_ampoules_salon
      chip07: light.groupe_leds_salon
      chip07_icon: mdi:led-strip
      chip01_icon: mdi:toilet
      chip03_icon: mdi:television-classic
      chip04: binary_sensor.detecteur_incendie_smoke
      chip06_icon: mdi:lightbulb-group
      entity08_icon: mdi:kettle
      date_label_color:
      - 78
      - 243
      - 0
      chip01_icon_color:
      - 64
      - 189
      - 10
      chip02_icon_color:
      - 225
      - 178
      - 76
      chip04_icon_color:
      - 221
      - 14
      - 14
      chip05_icon_color:
      - 255
      - 255
      - 255
      chip06_icon_color:
      - 255
      - 255
      - 255
      chip07_icon_color:
      - 255
      - 255
      - 255
      entity08_icon_color:
      - 250
      - 0
      - 0
      time_label_color:
      - 78
      - 243
      - 0
      home_value01: sensor.lights_on_count
      home_value02: sensor.aq_01_studio_aq_01_co
      home_value03: sensor.aq_01_studio_aq_01_2_5_g
      entitypages_enabled: false
      home_value01_icon: mdi:lightbulb
      home_value03_icon: mdi:air-filter
      home_outdoor_temp_label_color:
      - 132
      - 223
      - 230
      home_indoor_temp_icon_color:
      - 255
      - 125
      - 62
      entities_entity01_icon: ''
      entities_entity06_icon: ''
      home_indoor_temp_label_color:
      - 255
      - 125
      - 62
      home_value01_icon_color:
      - 237
      - 219
      - 29
      home_value01_label_color:
      - 237
      - 219
      - 29
      right_button_entity: script.script_extinction_chambre
      home_button04_icon_color01:
      - 110
      - 240
      - 125
      domain_automation_button_action: toggle
      home_button06_icon: ''
      chip03_icon_color:
      - 255
      - 255
      - 255
      hw_buttons_bars_pages:
      - '2'
      - '61440'
      - '3932160'
      - '256'
      - '134217728'
      - '2048'
      - '4194304'
      - '1024'
      decimal_separator: ','
      right_button_hold_custom_action:
      - type: turn_on
        device_id: 60637327576f89f776c126208706246f
        entity_id: cba134d7dbb52f34687a11f252c6f436
        domain: light
      left_button_hold_custom_action:
      - device_id: 65bc115e2bbd15d3ee33f8dce252f6f9
        domain: light
        entity_id: 4cacb522e6ae8f1ffbba279438c60f5f
        type: brightness_decrease
      entity03: light.ac_02182e3_2
      entity04: light.bureau
```

### ESPHome Logs

Logger: homeassistant.components.automation.nspanel_benoit_configuration
Source: helpers/script.py:501
integration: Automation (documentation, issues)
First occurred: 16:32:41 (10 occurrences)
Last logged: 16:45:08

NSPanel Benoit Configuration: Main choices: NSPanel event: Choose at step 2: Boot init: Error executing script. Unexpected error for if at pos 2: Not connected to nspanelbenoit @ 192.168.92.106!
NSPanel Benoit Configuration: Main choices: NSPanel event: Error executing script. Unexpected error for choose at pos 2: Not connected to nspanelbenoit @ 192.168.92.106!
NSPanel Benoit Configuration: Main choices: Automation reloaded: If at step 4: Error executing script. Unexpected error for call_service at pos 1: Not connected to nspanelbenoit @ 192.168.92.113!
NSPanel Benoit Configuration: Main choices: Automation reloaded: Error executing script. Unexpected error for if at pos 4: Not connected to nspanelbenoit @ 192.168.92.113!
NSPanel Benoit Configuration: Error executing script. Unexpected error for choose at pos 3: Not connected to nspanelbenoit @ 192.168.92.113!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 501, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 736, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 699, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2738, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2783, in _execute_service
    return target(service_call)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/esphome/manager.py", line 742, in execute_service
    entry_data.client.execute_service(service, call.data)
  File "/usr/local/lib/python3.12/site-packages/aioesphomeapi/client.py", line 1214, in execute_service
    connection = self._get_connection()
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aioesphomeapi/client.py", line 377, in _get_connection
    raise APIConnectionError(f"Not connected to {self.log_name}!")
aioesphomeapi.core.APIConnectionError: Not connected to nspanelbenoit @ 192.168.92.106!
![Sans titre](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/101732505/a97f225f-b013-4fa2-9ce4-8947ddfede9f)

### Home Assistant Logs

How can I enter the encryption key ?

![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/101732505/1cfc0520-4967-460d-86b2-1bce55818651)

Regards,

Benoit.
