### ISSUE TITLE
Issue with Add-on: Climate - In dual mode, there are two separate set-points, unable to control heat using "-" & "+" buttons.

### ISSUE THREAD

**Issue by zembrzycki** [Blackymas/NSPanel_HA_Blueprint#2100]
### TFT Version

4.3.7

### ESPHome Version

4.3.7

### Blueprint Version

4.3.7

### Panel Model

US

### What is the bug?

While running addon_climate_dual, and heat is selected, the "+" & "-"  buttons on the climate card adjust the cooling temperature opposed to the heating temperature.   (buttons only control cooling set-point regardless of mode)

When in heat mode, it is not necessary to display a cool set-point temperature, likewise, when in cool mode, it is not necessary to display a heat set-point temperature.   Displaying a single set point is all that is actually required in these modes. 

### Steps to Reproduce

https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/13970426/d9e9d0b8-de32-4dde-866d-b2a627319033

### Your Panel's YAML

```yaml
::: ESP :::::.....
substitutions:
  # Settings - Editable values
  device_name: "nsp3" 

  # Add-on configuration (if needed)
  ## Add-on climate
  heater_relay: "1"     # Possible values: "1" or "2"
  cooler_relay: "1"     # Possible values: "1" or "2"
  temp_units: "°F"      # Temperatures in Fahrenheit
  min_off_time: "3"     # Minimum duration (in seconds) the cooling/heating action must be disengaged before it may be engaged.
  min_run_time: "3"     # Minimum duration (in seconds) the cooling/heating action must be engaged before it may be disengaged.
  min_idle_time: "3"    # Minimum duration (in seconds) the idle action must be active before calling another climate action.
  temp_min: "65"        # Min supported temperature is 40°F
  temp_max: "80"        # Max supported temperature is 80°F
  temp_step: "1"        # Temperature granularity is 1°F
  cool_deadband: "1"    # Temperature delta before engaging cooling
  cool_overrun: "0.5"   # Temperature delta before disengaging cooling
  heat_deadband: "1"    # Temperature delta before engaging heat
  heat_overrun: "0.5"   # Temperature delta before disengaging heat
  target_low: "74"      # The initial lower treshold for the target temperature.
  target_high: "74"     # The initial higher treshold for the target temperature.

wifi:
  fast_connect: "on"
  power_save_mode: "none"

# Basic and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Basic package
      # Optional advanced and add-on configurations
      # - esphome/nspanel_esphome_advanced.yaml
      #- nspanel_esphome_addon_climate_cool.yaml
      # - nspanel_esphome_addon_climate_heat.yaml
      - nspanel_esphome_addon_climate_dual.yaml
    refresh: 300s
    



::: Blueprint :::::.....
alias: NSP3
description: ""
use_blueprint:
  path: Blackymas/nspanel_blueprint.yaml
  input:
    nspanel_name: cee07557644ad4dee9455d1d8115fdcf
    date_format: "%A, %-m/%-d"
    timezone: America/New_York (EST5EDT,M3.2.0,M11.1.0)
    weather_entity: weather.beacon
    climate: climate.nsp3_thermostat
    home_indoor_temp_icon: mdi:home-thermometer-outline
    climate_chip_always_visible: true
    home_indoor_temp_visible: true
    outdoortemp: sensor.lumi_weather_outdoor_temperature
    time_format: "%-I:%M %p"
    home_value01: sensor.nsp_setpoint
    home_outdoor_temp_label_color:
      - 255
      - 38
      - 0
    left_button_entity: script.temperature_down
    left_button_name: Down
    right_button_entity: script.temperature_up
    right_button_name: Up
    hw_button_bar_left_always_show: false
    hw_button_bar_right_always_show: false
    hw_buttons_bars_pages:
      - "2"
      - "512"
      - "134217728"
      - "124"
      - "128"
    home_custom_button01: switch.nsp3_relay_2
    home_custom_button01_name: Stage-2
    home_custom_button01_icon: mdi:fan-speed-2
    screensaver_display_time: true
```

### ESPHome Logs

INFO ESPHome 2024.4.2
INFO Reading configuration /config/esphome/nsp3.yaml...
INFO Detected timezone 'America/New_York'
INFO Starting log output from 10.10.10.27 using esphome API
INFO Successfully connected to nsp3 @ 10.10.10.27 in 0.010s
INFO Successful handshake with nsp3 @ 10.10.10.27 in 0.037s
[14:43:35][I][app:100]: ESPHome version 2024.4.2 compiled on May  2 2024, 14:30:27
[14:43:35][C][wifi:580]: WiFi:
[14:43:35][C][wifi:408]:   Local MAC: 08:D1:F9:A3:8A:7C
[14:43:35][C][wifi:413]:   SSID: 'Orange'[redacted]
[14:43:35][C][wifi:416]:   IP Address: 10.10.10.27
[14:43:35][C][wifi:420]:   BSSID: 08:45:D1:0C:0D:61[redacted]
[14:43:35][C][wifi:421]:   Hostname: 'nsp3'
[14:43:35][C][wifi:423]:   Signal strength: -46 dB ▂▄▆█
[14:43:35][C][wifi:427]:   Channel: 6
[14:43:35][C][wifi:428]:   Subnet: 255.255.255.192
[14:43:35][C][wifi:429]:   Gateway: 10.10.10.1
[14:43:35][C][wifi:430]:   DNS1: 10.10.10.10
[14:43:35][C][wifi:431]:   DNS2: 0.0.0.0
[14:43:35][C][logger:166]: Logger:
[14:43:35][C][logger:167]:   Level: DEBUG
[14:43:35][C][logger:169]:   Log Baud Rate: 0
[14:43:35][C][logger:170]:   Hardware UART: UART0
[14:43:35][C][uart.idf:139]: UART Bus 0:
[14:43:35][C][uart.idf:140]:   TX Pin: GPIO16
[14:43:35][C][uart.idf:141]:   RX Pin: GPIO17
[14:43:35][C][uart.idf:143]:   RX Buffer Size: 256
[14:43:35][C][uart.idf:145]:   Baud Rate: 115200 baud
[14:43:35][C][uart.idf:146]:   Data Bits: 8
[14:43:35][C][uart.idf:147]:   Parity: NONE
[14:43:35][C][uart.idf:148]:   Stop bits: 1
[14:43:35][C][ledc.output:173]: LEDC Output:
[14:43:35][C][ledc.output:174]:   Pin GPIO21
[14:43:35][C][ledc.output:175]:   LEDC Channel: 0
[14:43:35][C][ledc.output:176]:   PWM Frequency: 1319.0 Hz
[14:43:35][C][ledc.output:177]:   Phase angle: 0.0°
[14:43:35][C][ledc.output:178]:   Bit depth: 15
[14:43:35][C][template.binary_sensor:028]: Template Binary Sensor 'Nextion display'
[14:43:35][C][template.binary_sensor:028]:   Device Class: 'connectivity'
[14:43:35][C][template.number:050]: Template Number 'Display Brightness'
[14:43:35][C][template.number:050]:   Unit of Measurement: '%'
[14:43:35][C][template.number:051]:   Optimistic: YES
[14:43:35][C][template.number:052]:   Update Interval: 60.0s
[14:43:35][C][template.number:050]: Template Number 'Display Brightness Dimdown'
[14:43:35][C][template.number:050]:   Unit of Measurement: '%'
[14:43:35][C][template.number:051]:   Optimistic: YES
[14:43:35][C][template.number:052]:   Update Interval: 60.0s
[14:43:35][C][template.number:050]: Template Number 'Display Brightness Sleep'
[14:43:35][C][template.number:050]:   Unit of Measurement: '%'
[14:43:35][C][template.number:051]:   Optimistic: YES
[14:43:35][C][template.number:052]:   Update Interval: 60.0s
[14:43:35][C][template.number:050]: Template Number 'Temperature Correction'
[14:43:35][C][template.number:050]:   Unit of Measurement: '°C'
[14:43:35][C][template.number:051]:   Optimistic: YES
[14:43:35][C][template.number:052]:   Update Interval: 60.0s
[14:43:35][C][template.number:050]: Template Number 'Timeout Page'
[14:43:35][C][template.number:050]:   Icon: 'mdi:timer'
[14:43:35][C][template.number:050]:   Unit of Measurement: 's'
[14:43:35][C][template.number:051]:   Optimistic: YES
[14:43:35][C][template.number:052]:   Update Interval: 60.0s
[14:43:35][C][template.number:050]: Template Number 'Timeout Dimming'
[14:43:35][C][template.number:050]:   Icon: 'mdi:timer'
[14:43:35][C][template.number:050]:   Unit of Measurement: 's'
[14:43:35][C][template.number:051]:   Optimistic: YES
[14:43:35][C][template.number:052]:   Update Interval: 60.0s
[14:43:35][C][template.number:050]: Template Number 'Timeout Sleep'
[14:43:35][C][template.number:050]:   Icon: 'mdi:timer'
[14:43:35][C][template.number:050]:   Unit of Measurement: 's'
[14:43:35][C][template.number:051]:   Optimistic: YES
[14:43:35][C][template.number:052]:   Update Interval: 60.0s
[14:43:35][C][template.select:065]: Template Select 'Baud rate'
[14:43:35][C][template.select:065]:   Icon: 'mdi:swap-horizontal'
[14:43:35][C][template.select:066]:   Update Interval: 60.0s
[14:43:35][C][template.select:069]:   Optimistic: YES
[14:43:35][C][template.select:070]:   Initial Option: 115200
[14:43:35][C][template.select:071]:   Restore Value: YES
[14:43:35][C][template.select:065]: Template Select 'Wake-up page'
[14:43:35][C][template.select:065]:   Icon: 'mdi:page-next-outline'
[14:43:35][C][template.select:066]:   Update Interval: 60.0s
[14:43:35][C][template.select:069]:   Optimistic: YES
[14:43:35][C][template.select:070]:   Initial Option: home
[14:43:35][C][template.select:071]:   Restore Value: YES
[14:43:35][C][template.select:065]: Template Select 'Update TFT display - Model'
[14:43:35][C][template.select:065]:   Icon: 'mdi:file-sync'
[14:43:35][C][template.select:066]:   Update Interval: 60.0s
[14:43:35][C][template.select:069]:   Optimistic: YES
[14:43:35][C][template.select:070]:   Initial Option: NSPanel EU
[14:43:35][C][template.select:071]:   Restore Value: YES
[14:43:35][C][template.select:065]: Template Select 'Update TFT display - Baud rate'
[14:43:35][C][template.select:065]:   Icon: 'mdi:swap-horizontal'
[14:43:35][C][template.select:066]:   Update Interval: 60.0s
[14:43:35][C][template.select:069]:   Optimistic: YES
[14:43:35][C][template.select:070]:   Initial Option: 921600
[14:43:35][C][template.select:071]:   Restore Value: YES
[14:43:35][C][switch.gpio:068]: GPIO Switch 'Nextion display - Power'
[14:43:35][C][switch.gpio:091]:   Restore Mode: always ON
[14:43:35][C][switch.gpio:031]:   Pin: GPIO4
[14:43:35][C][template.text_sensor:020]: Template Sensor 'Device Name'
[14:43:35][C][template.text_sensor:020]:   Icon: 'mdi:identifier'
[14:43:35][C][template.text_sensor:020]: Template Sensor 'Detailed Entity'
[14:43:35][C][template.text_sensor:020]:   Icon: 'mdi:tablet-dashboard'
[14:43:35][C][template.text_sensor:020]: Template Sensor 'Notification Label'
[14:43:35][C][template.text_sensor:020]: Template Sensor 'Notification Text'
[14:43:35][C][template.text_sensor:020]: Template Sensor 'Version Blueprint'
[14:43:35][C][template.text_sensor:020]:   Icon: 'mdi:tag-text-outline'
[14:43:35][C][template.text_sensor:020]: Template Sensor 'Version ESPHome'
[14:43:35][C][template.text_sensor:020]:   Icon: 'mdi:tag-text-outline'
[14:43:35][C][template.sensor:022]: Template Sensor 'Blueprint'
[14:43:35][C][template.sensor:022]:   State Class: ''
[14:43:35][C][template.sensor:022]:   Unit of Measurement: '%'
[14:43:35][C][template.sensor:022]:   Accuracy Decimals: 1
[14:43:35][C][template.sensor:022]:   Icon: 'mdi:link-variant'
[14:43:35][C][template.sensor:023]:   Update Interval: 60.0s
[14:43:35][C][gpio.binary_sensor:015]: GPIO Binary Sensor 'Left Button'
[14:43:35][C][gpio.binary_sensor:016]:   Pin: GPIO14
[14:43:35][C][gpio.binary_sensor:015]: GPIO Binary Sensor 'Right Button'
[14:43:35][C][gpio.binary_sensor:016]:   Pin: GPIO27
[14:43:35][C][switch.gpio:068]: GPIO Switch 'Relay 1'
[14:43:35][C][switch.gpio:091]:   Restore Mode: restore defaults to OFF
[14:43:35][C][switch.gpio:031]:   Pin: GPIO22
[14:43:35][C][switch.gpio:068]: GPIO Switch 'Relay 2'
[14:43:35][C][switch.gpio:091]:   Restore Mode: restore defaults to OFF
[14:43:35][C][switch.gpio:031]:   Pin: GPIO19
[14:43:35][C][template.switch:068]: Template Switch 'Notification unread'
[14:43:35][C][template.switch:091]:   Restore Mode: always OFF
[14:43:35][C][template.switch:057]:   Optimistic: YES
[14:43:35][C][template.switch:068]: Template Switch 'Notification sound'
[14:43:35][C][template.switch:091]:   Restore Mode: restore defaults to OFF
[14:43:35][C][template.switch:057]:   Optimistic: YES
[14:43:35][C][template.switch:068]: Template Switch 'Relay 0 (dummy)'
[14:43:35][C][template.switch:091]:   Restore Mode: always OFF
[14:43:35][C][template.switch:057]:   Optimistic: YES
[14:43:35][C][psram:020]: PSRAM:
[14:43:35][C][psram:021]:   Available: YES
[14:43:35][C][psram:024]:   Size: 2036 KB
[14:43:35][C][rtttl:029]: Rtttl
[14:43:35][C][nextion:128]: Nextion:
[14:43:35][C][nextion:129]:   Device Model:     NX4832F035_011C
[14:43:35][C][nextion:130]:   Firmware Version: 72
[14:43:35][C][nextion:131]:   Serial Number:    6BB3340171CFCB79
[14:43:35][C][nextion:132]:   Flash Size:       16777216
[14:43:35][C][nextion:133]:   Wake On Touch:    YES
[14:43:35][C][nextion:134]:   Exit reparse:     YES
[14:43:35][C][factory_reset.button:011]: Factory Reset Button 'Factory reset'
[14:43:35][C][factory_reset.button:011]:   Icon: 'mdi:restart-alert'
[14:43:35][C][restart.button:017]: Restart Button 'Restart'
[14:43:35][C][adc:097]: ADC Sensor 'ntc_source'
[14:43:35][C][adc:097]:   Device Class: 'voltage'
[14:43:35][C][adc:097]:   State Class: 'measurement'
[14:43:35][C][adc:097]:   Unit of Measurement: 'V'
[14:43:35][C][adc:097]:   Accuracy Decimals: 2
[14:43:35][C][adc:107]:   Pin: GPIO38
[14:43:35][C][adc:122]:   Attenuation: 11db
[14:43:35][C][adc:141]:   Samples: 4
[14:43:36][C][adc:142]:   Update Interval: 10.0s
[14:43:36][C][resistance:010]: Resistance Sensor 'resistance_sensor'
[14:43:36][C][resistance:010]:   State Class: 'measurement'
[14:43:36][C][resistance:010]:   Unit of Measurement: 'Ω'
[14:43:36][C][resistance:010]:   Accuracy Decimals: 1
[14:43:36][C][resistance:010]:   Icon: 'mdi:flash'
[14:43:36][C][resistance:011]:   Configuration: DOWNSTREAM
[14:43:36][C][resistance:012]:   Resistor: 11200.00Ω
[14:43:36][C][resistance:013]:   Reference Voltage: 3.3V
[14:43:36][C][ntc:014]: NTC Sensor 'Temperature'
[14:43:36][C][ntc:014]:   Device Class: 'temperature'
[14:43:36][C][ntc:014]:   State Class: 'measurement'
[14:43:36][C][ntc:014]:   Unit of Measurement: '°C'
[14:43:36][C][ntc:014]:   Accuracy Decimals: 1
[14:43:36][C][thermostat.climate:1290]: Thermostat 'Thermostat'
[14:43:36][C][thermostat.climate:1293]:   Minimum Set Point Differential: 0.5°C
[14:43:36][C][thermostat.climate:1295]:   Start-up Delay Enabled: NO
[14:43:36][C][thermostat.climate:1297]:   Cooling Parameters:
[14:43:36][C][thermostat.climate:1298]:     Deadband: 0.6°C
[14:43:36][C][thermostat.climate:1299]:     Overrun: 0.3°C
[14:43:36][C][thermostat.climate:1306]:     Minimum Off Time: 3s
[14:43:36][C][thermostat.climate:1308]:     Minimum Run Time: 3s
[14:43:36][C][thermostat.climate:1311]:   Heating Parameters:
[14:43:36][C][thermostat.climate:1312]:     Deadband: 0.6°C
[14:43:36][C][thermostat.climate:1313]:     Overrun: 0.3°C
[14:43:36][C][thermostat.climate:1320]:     Minimum Off Time: 3s
[14:43:36][C][thermostat.climate:1322]:     Minimum Run Time: 3s
[14:43:36][C][thermostat.climate:1337]:   Minimum Idle Time: 3s
[14:43:36][C][thermostat.climate:1338]:   Supports AUTO: NO
[14:43:36][C][thermostat.climate:1339]:   Supports HEAT/COOL: YES
[14:43:36][C][thermostat.climate:1340]:   Supports COOL: YES
[14:43:36][C][thermostat.climate:1341]:   Supports DRY: NO
[14:43:36][C][thermostat.climate:1342]:   Supports FAN_ONLY: NO
[14:43:36][C][thermostat.climate:1344]:   Supports FAN_ONLY_ACTION_USES_FAN_MODE_TIMER: NO
[14:43:36][C][thermostat.climate:1345]:   Supports FAN_ONLY_COOLING: NO
[14:43:36][C][thermostat.climate:1347]:   Supports FAN_WITH_COOLING: NO
[14:43:36][C][thermostat.climate:1350]:   Supports FAN_WITH_HEATING: NO
[14:43:36][C][thermostat.climate:1352]:   Supports HEAT: YES
[14:43:36][C][thermostat.climate:1353]:   Supports FAN MODE ON: NO
[14:43:36][C][thermostat.climate:1354]:   Supports FAN MODE OFF: NO
[14:43:36][C][thermostat.climate:1355]:   Supports FAN MODE AUTO: NO
[14:43:36][C][thermostat.climate:1356]:   Supports FAN MODE LOW: NO
[14:43:36][C][thermostat.climate:1357]:   Supports FAN MODE MEDIUM: NO
[14:43:36][C][thermostat.climate:1358]:   Supports FAN MODE HIGH: NO
[14:43:36][C][thermostat.climate:1359]:   Supports FAN MODE MIDDLE: NO
[14:43:36][C][thermostat.climate:1360]:   Supports FAN MODE FOCUS: NO
[14:43:36][C][thermostat.climate:1361]:   Supports FAN MODE DIFFUSE: NO
[14:43:36][C][thermostat.climate:972]:       HOME Default Target Temperature High: 23.3°C
[14:43:36][C][thermostat.climate:980]:       HOME Default Mode: HEAT_COOL
[14:43:36][C][homeassistant.time:010]: Home Assistant Time:
[14:43:36][C][homeassistant.time:011]:   Timezone: 'EST5EDT,M3.2.0,M11.1.0'
[14:43:36][C][mdns:115]: mDNS:
[14:43:36][C][mdns:116]:   Hostname: nsp3
[14:43:36][C][ota:096]: Over-The-Air Updates:
[14:43:36][C][ota:097]:   Address: nsp3.7p.net:3232
[14:43:36][C][ota:100]:   Using Password.
[14:43:36][C][ota:103]:   OTA version: 2.
[14:43:36][C][api:139]: API Server:
[14:43:36][C][api:140]:   Address: nsp3.7p.net:6053
[14:43:36][C][api:144]:   Using noise encryption: NO
[14:43:36][C][wifi_signal.sensor:009]: WiFi Signal 'RSSI'
[14:43:36][C][wifi_signal.sensor:009]:   Device Class: 'signal_strength'
[14:43:36][C][wifi_signal.sensor:009]:   State Class: 'measurement'
[14:43:36][C][wifi_signal.sensor:009]:   Unit of Measurement: 'dBm'
[14:43:36][C][wifi_signal.sensor:009]:   Accuracy Decimals: 0
[14:43:36][C][wifi_signal.sensor:009]:   Icon: 'mdi:wifi'
[14:43:44][D][sensor:094]: 'ntc_source': Sending state 1.57900 V with 2 decimals of accuracy
[14:43:44][D][resistance:039]: 'resistance_sensor' - Resistance 10275.9Ω
[14:43:44][D][sensor:094]: 'resistance_sensor': Sending state 10275.88574 Ω with 1 decimals of accuracy
[14:43:44][D][ntc:026]: 'Temperature' - Temperature: 24.4°C
[14:43:44][D][sensor:094]: 'Temperature': Sending state 24.38879 °C with 1 decimals of accuracy
[14:43:44][D][climate:396]: 'Thermostat' - Sending state:
[14:43:44][D][climate:399]:   Mode: HEAT
[14:43:44][D][climate:401]:   Action: IDLE
[14:43:44][D][climate:410]:   Preset: HOME
[14:43:44][D][climate:419]:   Current Temperature: 24.39°C
[14:43:44][D][climate:423]:   Target Temperature: Low: 21.17°C High: 23.89°C
[14:43:44][W][component:237]: Component adc.sensor took a long time for an operation (108 ms).
[14:43:44][W][component:238]: Components should block for at most 30 ms.
[14:43:45][C][nspanel_ha_blueprint:2187]: Wi-Fi:         Excellent (-48 dBm)
[14:43:45][C][nspanel_ha_blueprint:2198]: API:           Connected
[14:43:45][C][nspanel_ha_blueprint:2206]: Blueprint:
[14:43:45][C][nspanel_ha_blueprint:2208]:   Version:     4.3.7
[14:43:45][C][nspanel_ha_blueprint:2209]:   Init steps:  62 (100.0%)
[14:43:45][C][nspanel_ha_blueprint:2218]: ESPHome:
[14:43:45][C][nspanel_ha_blueprint:2219]:   Version:     4.3.7
[14:43:45][C][nspanel_ha_blueprint:2220]:   Compiler:    2024.4.2
[14:43:45][C][nspanel_ha_blueprint:2225]:   Framework:   ESP-IDF
[14:43:45][C][nspanel_ha_blueprint:2230]:   Free heap:
[14:43:45][C][nspanel_ha_blueprint:2234]:     Internal:   199996 bytes (56.9%)
[14:43:45][C][nspanel_ha_blueprint:2244]:     PSRAM:     2008403 bytes (96.3%)
[14:43:45][C][nspanel_ha_blueprint:2251]: UART:
[14:43:45][C][nspanel_ha_blueprint:2252]:   Baud rate:   115200 bps
[14:43:45][C][nspanel_ha_blueprint:2253]:   Queue size:  0
[14:43:45][C][nspanel_ha_blueprint:2257]: Nextion:
[14:43:45][C][nspanel_ha_blueprint:2258]:   Queue size:  0
[14:43:45][C][nspanel_ha_blueprint:2260]:   Is setup:    True
[14:43:45][C][nspanel_ha_blueprint:2267]:   Init:        True
[14:43:45][C][nspanel_ha_blueprint:2273]:   TFT:         4.3.6
[14:43:45][C][nspanel_ha_blueprint:2274]: Packages:
[14:43:45][C][nspanel_ha_blueprint:2276]:   - Core
[14:43:45][C][nspanel_ha_blueprint:2285]:   - Upload TFT
[14:43:45][C][nspanel_ha_blueprint:2288]:   - Climate - Base
[14:43:45][C][nspanel_ha_blueprint:2294]:   - Climate - Dual
[14:43:45][C][nspanel_ha_blueprint:097]: Add-on Upload TFT:
[14:43:45][C][nspanel_ha_blueprint:098]:   File model: NSPanel US
[14:43:45][C][nspanel_ha_blueprint:099]:   Valid TFT:  YES
[14:43:45][C][nspanel_ha_blueprint:133]: Add-on climate:
[14:43:45][C][nspanel_ha_blueprint:149]:   Dual:  Enabled
[14:43:45][C][nspanel_ha_blueprint:151]:   Relay (cooler): 1
[14:43:45][C][nspanel_ha_blueprint:155]:   Relay (heater): 1
[14:43:47][D][nextion:457]: Got touch event:
[14:43:47][D][nextion:458]:   page_id:      7
[14:43:47][D][nextion:459]:   component_id: 5
[14:43:47][D][nextion:460]:   event type:   PRESS
[14:43:47][D][script:077]: Script 'timer_page' restarting (mode: restart)
[14:43:47][D][script:077]: Script 'timer_dim' restarting (mode: restart)
[14:43:47][D][script:077]: Script 'timer_sleep' restarting (mode: restart)
[14:43:48][D][nextion:457]: Got touch event:
[14:43:48][D][nextion:458]:   page_id:      7
[14:43:48][D][nextion:459]:   component_id: 5
[14:43:48][D][nextion:460]:   event type:   RELEASE
[14:43:48][D][script:077]: Script 'timer_page' restarting (mode: restart)
[14:43:48][D][script:077]: Script 'timer_dim' restarting (mode: restart)
[14:43:48][D][script:077]: Script 'timer_sleep' restarting (mode: restart)
[14:43:49][D][text_sensor:064]: 'NSPanel local event': Sending state '{"page": "climate", "key": "target_temp_high", "value": 760, "embedded": 1}'
[14:43:49][D][climate:011]: 'Thermostat' - Setting
[14:43:49][D][climate:046]:   Target Temperature High: 24.44
[14:43:49][D][climate:396]: 'Thermostat' - Sending state:
[14:43:49][D][climate:399]:   Mode: HEAT
[14:43:49][D][climate:401]:   Action: IDLE
[14:43:49][D][climate:410]:   Preset: HOME
[14:43:49][D][climate:419]:   Current Temperature: 24.39°C
[14:43:49][D][climate:423]:   Target Temperature: Low: 21.17°C High: 24.44°C
[14:43:49][D][nextion_textsensor:014]: Processed text_sensor "localevent" state "{"page": "climate", "key": "target_temp_high", "value": 760, "embedded": 1}"
[14:43:49][W][component:237]: Component display took a long time for an operation (117 ms).
[14:43:49][W][component:238]: Components should block for at most 30 ms.
[14:43:52][D][nextion:457]: Got touch event:
[14:43:52][D][nextion:458]:   page_id:      7
[14:43:52][D][nextion:459]:   component_id: 5
[14:43:52][D][nextion:460]:   event type:   PRESS
[14:43:52][D][script:077]: Script 'timer_page' restarting (mode: restart)
[14:43:52][D][script:077]: Script 'timer_dim' restarting (mode: restart)
[14:43:52][D][script:077]: Script 'timer_sleep' restarting (mode: restart)
[14:43:52][D][nextion:457]: Got touch event:
[14:43:52][D][nextion:458]:   page_id:      7
[14:43:52][D][nextion:459]:   component_id: 5
[14:43:52][D][nextion:460]:   event type:   RELEASE
[14:43:52][D][script:077]: Script 'timer_page' restarting (mode: restart)
[14:43:52][D][script:077]: Script 'timer_dim' restarting (mode: restart)
[14:43:52][D][script:077]: Script 'timer_sleep' restarting (mode: restart)
[14:43:53][D][text_sensor:064]: 'NSPanel local event': Sending state '{"page": "climate", "key": "target_temp_high", "value": 770, "embedded": 1}'
[14:43:53][D][climate:011]: 'Thermostat' - Setting
[14:43:53][D][climate:046]:   Target Temperature High: 25.00
[14:43:53][D][climate:396]: 'Thermostat' - Sending state:
[14:43:53][D][climate:399]:   Mode: HEAT
[14:43:53][D][climate:401]:   Action: IDLE
[14:43:53][D][climate:410]:   Preset: HOME
[14:43:53][D][climate:419]:   Current Temperature: 24.39°C
[14:43:53][D][climate:423]:   Target Temperature: Low: 21.17°C High: 25.00°C
[14:43:54][D][nextion_textsensor:014]: Processed text_sensor "localevent" state "{"page": "climate", "key": "target_temp_high", "value": 770, "embedded": 1}"
[14:43:54][W][component:237]: Component display took a long time for an operation (114 ms).
[14:43:54][W][component:238]: Components should block for at most 30 ms.
[14:43:54][D][sensor:094]: 'ntc_source': Sending state 1.57867 V with 2 decimals of accuracy
[14:43:54][D][resistance:039]: 'resistance_sensor' - Resistance 10271.7Ω
[14:43:54][D][sensor:094]: 'resistance_sensor': Sending state 10271.72754 Ω with 1 decimals of accuracy
[14:43:54][D][ntc:026]: 'Temperature' - Temperature: 24.4°C
[14:43:54][D][sensor:094]: 'Temperature': Sending state 24.39786 °C with 1 decimals of accuracy
[14:43:54][D][climate:396]: 'Thermostat' - Sending state:
[14:43:54][D][climate:399]:   Mode: HEAT
[14:43:54][D][climate:401]:   Action: IDLE
[14:43:54][D][climate:410]:   Preset: HOME
[14:43:54][D][climate:419]:   Current Temperature: 24.40°C
[14:43:54][D][climate:423]:   Target Temperature: Low: 21.17°C High: 25.00°C
[14:43:54][W][component:237]: Component adc.sensor took a long time for an operation (109 ms).
[14:43:54][W][component:238]: Components should block for at most 30 ms.
[14:43:57][D][nextion:457]: Got touch event:
[14:43:57][D][nextion:458]:   page_id:      7
[14:43:57][D][nextion:459]:   component_id: 5
[14:43:57][D][nextion:460]:   event type:   PRESS
[14:43:57][D][script:077]: Script 'timer_page' restarting (mode: restart)
[14:43:57][D][script:077]: Script 'timer_dim' restarting (mode: restart)
[14:43:57][D][script:077]: Script 'timer_sleep' restarting (mode: restart)
[14:43:57][D][nextion:457]: Got touch event:
[14:43:57][D][nextion:458]:   page_id:      7
[14:43:57][D][nextion:459]:   component_id: 5
[14:43:57][D][nextion:460]:   event type:   RELEASE
[14:43:57][D][script:077]: Script 'timer_page' restarting (mode: restart)
[14:43:57][D][script:077]: Script 'timer_dim' restarting (mode: restart)
[14:43:57][D][script:077]: Script 'timer_sleep' restarting (mode: restart)
[14:43:58][D][text_sensor:064]: 'NSPanel local event': Sending state '{"page": "climate", "key": "target_temp_high", "value": 780, "embedded": 1}'
[14:43:58][D][climate:011]: 'Thermostat' - Setting
[14:43:58][D][climate:046]:   Target Temperature High: 25.56
[14:43:58][D][climate:396]: 'Thermostat' - Sending state:
[14:43:58][D][climate:399]:   Mode: HEAT
[14:43:58][D][climate:401]:   Action: IDLE
[14:43:58][D][climate:410]:   Preset: HOME
[14:43:58][D][climate:419]:   Current Temperature: 24.40°C
[14:43:58][D][climate:423]:   Target Temperature: Low: 21.17°C High: 25.56°C
[14:43:58][D][nextion_textsensor:014]: Processed text_sensor "localevent" state "{"page": "climate", "key": "target_temp_high", "value": 780, "embedded": 1}"
[14:43:58][W][component:237]: Component display took a long time for an operation (125 ms).
[14:43:58][W][component:238]: Components should block for at most 30 ms.
[14:43:59][D][text_sensor:064]: 'Device Name': Sending state 'nsp3'
[14:44:01][D][esp32.preferences:114]: Saving 1 preferences to flash...
[14:44:01][D][esp32.preferences:143]: Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
