### ISSUE TITLE
`Bug` Climate page does not show Entity State icons.

### ISSUE THREAD

**Issue by denes44** [Blackymas/NSPanel_HA_Blueprint#2111]
### TFT Version

4.3.7

### ESPHome Version

4.3.7

### Blueprint Version

4.3.7

### Panel Model

EU

### What is the bug?

A custom icon is set in the blueprint configuration, but they are not shown on the panel:
![image](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/60078357/250554d8-f773-483a-95a9-553725624cf3)

Even if I change the default color, the icons are missing.

### Your Panel's YAML

```yaml
# Blueprint configuartion
    climate: climate.living_room_ac
    climate_value01: sensor.sensor_living_room_temperature
    climate_value01_icon: mdi:sofa
    climate_value02: sensor.sensor_bedroom_temperature
    climate_value02_icon: mdi:bed
    climate_value03: sensor.sensor_outside_temperature
    climate_value03_icon: mdi:home-thermometer-outline
```
