### ISSUE TITLE
`Bug` 

### ISSUE THREAD

**Issue by Mauricewillemstein** [Blackymas/NSPanel_HA_Blueprint#2113]
### TFT Version

v4.3.8.dev1

### ESPHome Version

 2024.5.0

### Blueprint Version

v4.3.8.dev1

### Panel Model

EU

### What is the bug?

When i try to install this dev version it gives me some erros.
Het main branch installs fine.

Nothing i tryed works, not even clean build files.

### Your Panel's YAML

```yaml
substitutions:
  ###### CHANGE ME START ######
  device_name: "zolder" 
  friendly_name: "NS-Zolder"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password


  #nextion_update_url: "http://homeassistant.local:8123/local/nspanel_eu.tft"  # Optional
  # Add-on configuration (if needed)
  # heater_relay: "1"  # Possible values: "1" or "2"

# Customization area
##### My customization - Start #####
##### My customization - End #####

# Core and optional configurations
# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: dev
    refresh: 300s
    files:
      - nspanel_esphome.yaml # Basic package
      # Optional advanced and add-on configurations
      - esphome/nspanel_esphome_advanced.yaml
      # - esphome/nspanel_esphome_addon_ble_tracker.yaml
      - esphome/nspanel_esphome_addon_bluetooth_proxy.yaml
      # - esphome/nspanel_esphome_addon_climate_cool.yaml
      # - esphome/nspanel_esphome_addon_climate_heat.yaml
      # - esphome/nspanel_esphome_addon_climate_dual.yaml
esp32:
  framework:
    type: esp-idf

##### My customization - Start #####

#uart:
#  - id: !extend tf_uart
#    baud_rate: 921600
    ##### Customization - Start #####
    ## If you wanna set non-standard parameters to your Bluetooth proxy just add like this:
#esp32_ble_tracker:
#      scan_parameters:
#        interval: 1100ms
#        window: 1100ms
#        active: true
    #
#bluetooth_proxy:
#     active: true
##### My customization - End #####
```

### ESPHome Logs

INFO ESPHome 2024.5.0
INFO Reading configuration /config/esphome/scherm.yaml...
Failed config

external_components: [source /data/packages/891b50f5/esphome/nspanel_esphome_core.yaml:25]
  - 
    Source is not a file system path, in expected github://username/name[@branch-or-tag] or github://pr#1234 format!.
    source: components
    components: 
      - nspanel_ha_blueprint
    refresh: 30s
  - source: 
      type: git
      url: https://github.com/edwardtfn/esphome
      ref: nextion-39
    components: 
      - nextion
      - psram
    refresh: 30s
  - source: 
      type: git
      url: https://github.com/edwardtfn/esphome
      ref: esp32ble-01
    components: 
      - esp32_ble_tracker
    refresh: 300s
  - source: 
      type: git
      url: https://github.com/edwardtfn/esphome
      ref: adc-sampling
    components: 
      - adc
    refresh: 300s
