### ISSUE TITLE
`Bug` Esphome 2024.5.0 firmware update doesn't work.

### ISSUE THREAD

**Issue by Lice2** [Blackymas/NSPanel_HA_Blueprint#2115]
### TFT Version

4.3.4

### ESPHome Version

2024.5.0

### Blueprint Version

4.3.7

### Panel Model

EU

### What is the bug?

I get the following error message:

```log
INFO ESPHome 2024.5.0
INFO Reading configuration /config/esphome/nspanel.yaml...
Failed config

external_components: [source /data/packages/566b10a3/esphome/nspanel_esphome_core.yaml:25]
  - 
    Could not find components folder for source. Please check the source contains a 'components' or 'esphome/components' folder.
    source: 
      type: git
      url: https://github.com/Blackymas/NSPanel_HA_Blueprint
      ref: v4.3.7
    components: 
      - nspanel_ha_blueprint
    refresh: 300s
  - source: 
      type: git
      url: https://github.com/edwardtfn/esphome
      ref: nextion-v435
    components: 
      - nextion
      - psram
    refresh: 300s
  - source: 
      type: git
      url: https://github.com/edwardtfn/esphome
      ref: esp32ble-01
    components: 
      - esp32_ble_tracker
    refresh: 300s
  - source: 
      type: git
      url: https://github.com/edwardtfn/esphome
      ref: adc-sampling
    components: 
      - adc
    refresh: 300s
```

I suspect it has something to do with my DNS settings.

```yaml
substitutions:

###### CHANGE ME START ######

  device_name: "nspanel" 
  friendly_name: "NSPanel-Flur-Unten"
  wifi_ssid: "xxxxxx"
  wifi_password: !secret wifi_password

  nextion_update_url: "http://192.168.0.161:8123/local/nspanel_eu.tft" # URL to local tft File
#  nextion_update_url: "http://192.168.0.161:8123/local/nspanel_blank.tft" # URL to Blank Screen
#  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft" # URL to Github

##### CHANGE ME END #####


# Customization area
##### My customization - Start #####

# Set IP address manually
wifi:
  networks:
    - id: !extend wifi_default
      manual_ip:
        static_ip: 192.168.0.199
        gateway: 192.168.0.240
        subnet: 255.255.255.0
        dns1: 192.168.0.240
##### My customization - End #####



##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Basic package
      #- esphome/nspanel_esphome_addon_bluetooth_proxy.yaml # Bluetooth Proxy add-on package
    refresh: 300s
##### DO NOT CHANGE ANYTHING! #####

##### Temporary code #####
#external_components:
#  - source: github://pr#5829
#    components:
#      - nextion
#    refresh: 1s
```

### Steps to Reproduce

I just wanted to install the latest esphome update.
Before, it always worked without any problems.

### Your Panel's YAML

```yaml
substitutions:

###### CHANGE ME START ######

  device_name: "nspanel" 
  friendly_name: "NSPanel-Flur-Unten"
  wifi_ssid: "xxxxxx"
  wifi_password: !secret wifi_password

  nextion_update_url: "http://192.168.0.161:8123/local/nspanel_eu.tft" # URL to local tft File
#  nextion_update_url: "http://192.168.0.161:8123/local/nspanel_blank.tft" # URL to Blank Screen
#  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft" # URL to Github

##### CHANGE ME END #####


# Customization area
##### My customization - Start #####

# Set IP address manually
wifi:
  networks:
    - id: !extend wifi_default
      manual_ip:
        static_ip: 192.168.0.199
        gateway: 192.168.0.240
        subnet: 255.255.255.0
        dns1: 192.168.0.240
##### My customization - End #####



##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Basic package
      #- esphome/nspanel_esphome_addon_bluetooth_proxy.yaml # Bluetooth Proxy add-on package
    refresh: 300s
##### DO NOT CHANGE ANYTHING! #####

##### Temporary code #####
#external_components:
#  - source: github://pr#5829
#    components:
#      - nextion
#    refresh: 1s
```

### ESPHome Logs

```log
INFO ESPHome 2024.5.0
INFO Reading configuration /config/esphome/nspanel.yaml...
Failed config

external_components: [source /data/packages/566b10a3/esphome/nspanel_esphome_core.yaml:25]
  - 
    Could not find components folder for source. Please check the source contains a 'components' or 'esphome/components' folder.
    source: 
      type: git
      url: https://github.com/Blackymas/NSPanel_HA_Blueprint
      ref: v4.3.7
    components: 
      - nspanel_ha_blueprint
    refresh: 300s
  - source: 
      type: git
      url: https://github.com/edwardtfn/esphome
      ref: nextion-v435
    components: 
      - nextion
      - psram
    refresh: 300s
  - source: 
      type: git
      url: https://github.com/edwardtfn/esphome
      ref: esp32ble-01
    components: 
      - esp32_ble_tracker
    refresh: 300s
  - source: 
      type: git
      url: https://github.com/edwardtfn/esphome
      ref: adc-sampling
    components: 
      - adc
    refresh: 300s
```
