### ISSUE TITLE
Unable to remove addon

### ISSUE THREAD

**Issue by rhvs** [Blackymas/NSPanel_HA_Blueprint#2116]
### TFT Version

4.3.7

### ESPHome Version

4.3.7

### Blueprint Version

4.3.7

### Panel Model

EU

### What is the bug?

When I uncomment "- esphome/nspanel_esphome_addon_climate_heat.yaml" after it has been installed once, it's impossible to permanently delete. 

### Steps to Reproduce

1.  Install as detailed in the manual and remove the # for - esphome/nspanel_esphome_addon_climate_heat.yaml
2.  Once installed, re insert the # before the - esphome/nspanel_esphome_addon_climate_heat.yaml
3.  Disable the ESP integration
4.  Remove the thermostat
5.  Enable ESP integration

### Your Panel's YAML

```yaml
substitutions:
  # Settings - Editable values
  device_name: "nspanel"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  nextion_update_url: !secret tft_upload_url  # Optional
  # Add-on configuration (if needed)
  # heater_relay: "1"  # Possible values: "1" or "2"

# Customization area
##### My customization - Start #####
##### My customization - End #####

# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    refresh: 300s
    files:
      - nspanel_esphome.yaml # Basic package
      # Optional advanced and add-on configurations
      # - esphome/nspanel_esphome_advanced.yaml
      - esphome/nspanel_esphome_addon_ble_tracker.yaml
      - esphome/nspanel_esphome_addon_bluetooth_proxy.yaml
      # - esphome/nspanel_esphome_addon_climate_cool.yaml
      - esphome/nspanel_esphome_addon_climate_heat.yaml
      # - esphome/nspanel_esphome_addon_climate_dual.yaml

esp32:
  framework:
    type: esp-idf
```
