### ISSUE TITLE
`Bug` Bluetooth Proxy Addon Crash

### ISSUE THREAD

**Issue by illuzn** [Blackymas/NSPanel_HA_Blueprint#2119]
### TFT Version

4.3.1

### ESPHome Version

4.3.7

### Blueprint Version

4.3.7

### Panel Model

US

### What is the bug?

Switched to the add-on method of having bluetooth proxy (no ble tracker).

Attempting to update TFT causes full device reboot (ESPHome disconnects from logs, device shows the initial boot screen with home assistant logo).

### Steps to Reproduce

1. Use my yaml customizations (none of these should use significant memory other than bluetooth proxy) below.

2. Attempt to update TFT (which crashes).

### Your Panel's YAML

```yaml
# Customization area
##### My customization - Start #####
# Enable Home Assistant API
api:
  encryption:
    key: ###REDACTED###

switch:
  - id: !extend relay_1
    restore_mode: ALWAYS_ON

  - id: !extend relay_2
    restore_mode: ALWAYS_OFF

bluetooth_proxy:
  active: true

wifi:
  power_save_mode: LIGHT
##### My customization - End #####

# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # Optional advanced and add-on configurations
      # - esphome/nspanel_esphome_addon_ble_tracker.yaml
      - esphome/nspanel_esphome_addon_bluetooth_proxy.yaml
      # - esphome/nspanel_esphome_addon_climate_cool.yaml
      # - esphome/nspanel_esphome_addon_climate_heat.yaml
      # - esphome/nspanel_esphome_addon_climate_dual.yaml
    refresh: 300s
```
