### ISSUE TITLE
`Bug` Utility Dashboard  not loading all information - Nextion reported serial buffer overflow!

### ISSUE THREAD

**Issue by theeye1000** [Blackymas/NSPanel_HA_Blueprint#2122]
### TFT Version

4.3.7

### ESPHome Version

2024.5.2

### Blueprint Version

4.3.7

### Panel Model

EU

### What is the bug?

After updating to 4.3.7, the first time I start the Utility Dashboard it loads all the information, but when I open the Utility Dashboard again, it loads less and less information. If I wait for 1 hour, all the information is displayed again. And when I open the dashboard again, less information is displayed. 

Error in the ESP log: 
[W][nextion:446]: Nextion reported serial buffer overflow!

![Screenshot_20240523-061058_Home Assistant](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/84576636/72efcb23-2ad7-4fa8-83d1-610500ef1b6e)

### Steps to Reproduce

1. open the Utility Dashboard
2. close Utility Dashboard
3. open the Utility Dashboard
4. check logs

### Your Panel's YAML

```yaml
substitutions:
###### CHANGE ME START ######

  device_name: "nspanel_eingang" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password


  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft" # URL to Github

##### CHANGE ME END #####



##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

esp32:
  framework:
    type: esp-idf
##### DO NOT CHANGE ANYTHING! #####
```

### ESPHome Logs

![Screenshot_20240523-061058_Home Assistant](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/84576636/d2ed05ab-1e82-4f7e-bc14-691282c208ec)
