### ISSUE TITLE
`Enhancement` Feedback cover

### ISSUE THREAD

**Issue by prigorus** [Blackymas/NSPanel_HA_Blueprint#2132]
### Enhancement Summary

Add support for feedback cover

### Detailed Description

First of all, thank you for adding the time based cover functionality into dev. Would it be possible to expand this to to also include feedback cover in the future? I have tested many different ESPHome cover options and the one I like the most is feedback cover since it also has acceleration_wait_time. I have also motors on my roof windows which have a soft start so the first 3 seconds of opening are not actual 3 seconds of movement position. Without this, you are very quickly off, when opening or closing the window several times.

**Comment by edwardtfn** [comment]
I see no problem in having feedback cover, however that will require sensors to define when it is open or closed. As the NSPanel doesn't offer an easy physical sensor connection, that would require you relying on the Wi-Fi and HA to work, and won't be fully local. This is not really a problem, but it is something to take in account.

Anyhow, you can use the existing add-on to "transform" it in a feedback cover by adding something like this to your yaml:

```yaml
cover:
  - id: !extend cover_embedded
    open_endstop: open_endstop_binary_sensor
    open_sensor: open_movement_binary_sensor
    close_endstop: close_endstop_binary_sensor
    close_sensor: close_movement_binary_sensor
```

This will alow you to change the platform but still take advantage of any other improvement we come to this add-on.
