### ISSUE TITLE
Temperature too high when using bluetooth

### ISSUE THREAD

**Issue by nikdom** [Blackymas/NSPanel_HA_Blueprint#2145]
### TFT Version

4.3.8

### ESPHome Version

4.3.8

### Blueprint Version

4.3.8

### Panel Model

EU

### What is the bug?

The temperature sensor measures too high values once the bluetooth addon was enabled. 
On the screenshot you see a time frame from roughly 15:00 - 23:00 when bluetooth was enabled but the room temperature stayed mostly the same. On other nspanels in the house it behaves similar.

<img width="626" alt="Bildschirmfoto 2024-06-13 um 06 35 39" src="https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/5239330/8c7cff8a-76cb-49f5-ab38-9c4a9f56881b">

I know bluetooth is not really advertised as feature, maybe this is one of the reasons. But anyways, just want to mention it to you.

Thanks a lot for all your commitment and work!!

### Steps to Reproduce

1. Adding addon `esphome/nspanel_esphome_addon_bluetooth_proxy.yaml`
2. Deploy, wait
3. Observe climate entity
4. Remove addon `esphome/nspanel_esphome_addon_bluetooth_proxy.yaml`
5. Deploy, wait
6. Observe climate entity

You might recognize the temperature difference between step 3 and 6. 

### Your Panel's YAML

```yaml
substitutions:
  ###### CHANGE ME START ######
  device_name: "og_az_nspanel" 
  wifi_ssid: !secret wifi_ssid 
  wifi_password: !secret wifi_password 
  nextion_update_url: !secret nspanel_update_url 

  ##### addon-configuration #####
  ## addon_climate ##
  heater_relay: "1" 
  temp_units: "°C"
  temp_min: "18"
  temp_max: "25"
  temp_step: "0.1"
  heat_overrun: "0.2"
  heat_deadband: "0.2"
  target_low: "21.5"

  ##### CHANGE ME END #####



##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      - nspanel_esphome_addon_climate_heat.yaml
      - esphome/nspanel_esphome_addon_bluetooth_proxy.yaml
    refresh: 300s

esp32:
  framework:
    type: esp-idf

##### DO NOT CHANGE ANYTHING! #####
```
