### ISSUE TITLE
`Bug` BLE support with xiaomi_hhccjcy01

### ISSUE THREAD

**Issue by mcrodriguezb** [Blackymas/NSPanel_HA_Blueprint#2146]
### TFT Version

4.3.8

### ESPHome Version

2024.5.5

### Blueprint Version

4.3.8

### Panel Model

EU

### What is the bug?

I have an ESPHome device configure with ble tracker for the xiaomi hhccjcy01 (https://esphome.io/components/sensor/xiaomi_ble.html). 

As I have migrated my nspanel from tasmota to NSPanel HA blueprint, I would like to move the ble tracker from the initial ESP32 to the nspanel. I moved my working configuration to the nspanel and I got an error generating the firmware.

Working configuration: yaml file provided below with no sensor configured.
Non working configuration: yaml file provided below

### Steps to Reproduce

1. Change the yaml file
2. Select install -> Wirelessly

### Your Panel's YAML

```yaml
substitutions:
  # Settings - Editable values
  device_name: "nspanel1"
  friendly_name: "nspanel1"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  nextion_update_url: "http://XX.XX.XX.XX:8123/local/nspanel_eu.tft"  # Optional
  # Add-on configuration (if needed)
  # heater_relay: "1"  # Possible values: "1" or "2"

# Customization area
##### My customization - Start #####
api:
  encryption:
    key: !secret apikey_encryption_nspanel1

esp32_ble_tracker:
#  scan_parameters:
#    active: "false"
#    continuous: false
  on_scan_end:
    - then:
        - lambda: |-
             ESP_LOGD("ble_auto", "The scan has ended!");

sensor:
  - platform: xiaomi_hhccjcy01
    mac_address: 'XX:XX:XX:XX:XX:XX'
    temperature:
      name: "Temperature"
    moisture:
      name: "Moisture"
    illuminance:
      name: "Illuminance"
    conductivity:
      name: "Soil Conductivity"
    battery_level:
      name: "Battery Level"

##### My customization - End #####

# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    refresh: 300s
    files:
      - nspanel_esphome.yaml # Basic package
      # Optional advanced and add-on configurations
      # - esphome/nspanel_esphome_advanced.yaml
      - esphome/nspanel_esphome_addon_ble_tracker.yaml
      # - esphome/nspanel_esphome_addon_bluetooth_proxy.yaml
      # - esphome/nspanel_esphome_addon_climate_cool.yaml
      # - esphome/nspanel_esphome_addon_climate_heat.yaml
      # - esphome/nspanel_esphome_addon_climate_dual.yaml
```

### ESPHome Logs

INFO ESPHome 2024.5.5
INFO Reading configuration /config/nspanel1.yaml...
INFO Updating https://github.com/Blackymas/NSPanel_HA_Blueprint@v4.3.8
INFO Detected timezone 'Etc/UTC'
INFO Generating C++ source...
INFO Compiling app...
Processing nspanel1 (board: esp32dev; framework: espidf; platform: platformio/espressif32@5.4.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - framework-espidf @ 3.40407.240606 (4.4.7) 
 - tool-cmake @ 3.16.9 
 - tool-ninja @ 1.10.2 
 - toolchain-esp32ulp @ 2.35.0-20220830 
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
Reading CMake configuration...
Dependency Graph
|-- ArduinoJson @ 6.18.5
|-- noise-c @ 0.1.4
Compiling .pioenvs/nspanel1/src/main.o
Linking .pioenvs/nspanel1/firmware.elf
/config/.esphome/platformio/packages/toolchain-xtensa-esp32@8.4.0+2021r2-patch5/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/nspanel1/src/main.o:(.literal._Z5setupv+0x638): undefined reference to `vtable for esphome::xiaomi_hhccjcy01::XiaomiHHCCJCY01'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32@8.4.0+2021r2-patch5/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/nspanel1/src/main.o:(.literal._Z5setupv+0x63c): undefined reference to `vtable for esphome::xiaomi_hhccjcy01::XiaomiHHCCJCY01'
/config/.esphome/platformio/packages/toolchain-xtensa-esp32@8.4.0+2021r2-patch5/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/nspanel1/src/main.o:(.literal._Z5setupv+0xad4): undefined reference to `vtable for esphome::xiaomi_ble::XiaomiListener'
collect2: error: ld returned 1 exit status
*** [.pioenvs/nspanel1/firmware.elf] Error 1
========================= [FAILED] Took 264.66 seconds =========================
