### ISSUE TITLE
`Bug` How can I stop the Blackymass blueprint from updating to latest version when I do a update for ESPhome (QUESTION)

### ISSUE THREAD

**Issue by smarthomefamilyverrips** [Blackymas/NSPanel_HA_Blueprint#2152]
### TFT Version

4.3.7

### ESPHome Version

4.3.7

### Blueprint Version

4.3.7

### Panel Model

None

### What is the bug?

As the subject says, now every time when I update ESPhome it also updates my NSpanel to the latest version of the Blackymass Blueprint, how do I prevent this from happening? Do I need to comment out something in the code?

Thanks Upfront!

### Steps to Reproduce

N/A

### Your Panel's YAML

```yaml
substitutions:

###### CHANGE ME START ######

  device_name: "nsbathroom" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: "http://192.168.0.168:8123/local/nspanel_eu.tft" # URL to local tft File
#  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft" # URL to Github

  ##### addon-configuration #####
  ## addon_climate ##
  # addon_climate_heater_relay: "1" # possible values: 1/2

#  baud_rate: "115200" # requires 115200 if tft is installed but can be changed to 9600 if tft upload fails and nextion switches to 9600

##### CHANGE ME END #####

##### DO NOT CHANGE ANYTHING! #####

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # - nspanel_esphome_advanced.yaml # activate advanced (legacy) elements - can be useful for troubleshooting
      # - nspanel_esphome_addon_climate_cool.yaml # activate for local climate (cooling) control
      # - nspanel_esphome_addon_climate_heat.yaml # activate for local climate (heater) control
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####

##### My customization - Start #####

# Set IP address manually
wifi:
  networks:
    - id: !extend wifi_default
      manual_ip:
        static_ip: 192.168.0.102
        gateway: 192.168.0.1
        dns1: 8.8.8.8
        dns2: 8.8.4.4
        subnet: 255.255.255.0

# Custom Arduino framework enforcement 
esp32:
  framework:
    type: arduino      

##### My customization - End #####
```

### ESPHome Logs

N/A

### Home Assistant Logs

N/A
