### ISSUE TITLE
Can't Build with BLE Tracker Addon

### ISSUE THREAD

**Issue by Airey001** [Blackymas/NSPanel_HA_Blueprint#2155]
### TFT Version

4.3.8

### ESPHome Version

204.5.5

### Blueprint Version

4.3.8

### Panel Model

US

### What is the bug?

Whn trying to build or clean with the BLE Tracker add on i get this with all 3 panels i have

Failed config

binary_sensor.template: [source /data/packages/566b10a3/esphome/nspanel_esphome_addon_ble_tracker.yaml:28]
  platform: template
  
  ID ble_component_status redefined! Check binary_sensor->3->id.
  id: ble_component_status
  name: BLE component status
  icon: mdi:bluetooth
  entity_category: diagnostic
  lambda: !lambda |-
    return ble_component->is_active();
  disabled_by_default: False

### Steps to Reproduce

unComment the BLE Tracker line in the YAML and build

**Comment by danir-de** [comment]
I'm having the same issue when upgrading from 4.3.7.

**Comment by edwardtfn** [comment]
This is odd. I had no issues compiling with ESPHome 2024.5.5.

Have you tried [cleaning-up the build files](https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/docs/error_compiling.md#clean-up-build-files)?
Could you please share your yaml? Please remove any sensitive info before sharing.

**Comment by Airey001** [comment]
So yes the error happens when trying to to clean too.

Here is my YAML

`substitutions:
  ###### CHANGE ME START ######
  device_name: "livingroom-nspanel" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: "http://172.16.1.20:8123/local/nspanel_us.tft"
  nextion_blank_url: "http://172.16.1.20:8123/local/nspanel_blank.tft"
  temp_units: "F"

  ##### addon-configuration #####
  ## addon_climate ##
  # addon_climate_heater_relay: "1" # possible values: 1/2

  ##### CHANGE ME END #####
ota:

api:

logger:

web_server:
  port: 80
  # https://esphome.io/components/web_server.html

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    refresh: 300s
    files:
      - nspanel_esphome.yaml # Basic package
      # Optional advanced and add-on configurations
      # - esphome/nspanel_esphome_advanced.yaml
      - esphome/nspanel_esphome_addon_ble_tracker.yaml
      - esphome/nspanel_esphome_addon_bluetooth_proxy.yaml
      # - esphome/nspanel_esphome_addon_climate_cool.yaml
      # - esphome/nspanel_esphome_addon_climate_heat.yaml
      # - esphome/nspanel_esphome_addon_climate_dual.yaml



esp32:
  framework:
    type: esp-idf`

**Comment by edwardtfn** [comment]
Ok, please comment out ble_tracking, as ble_proxy already contains that.

You can also remove your reference to `ota`, `api`, `logger` and `esp-idf`, as all of those are part of the Basic package.

This should work:
```yaml
substitutions:
  ###### CHANGE ME START ######
  device_name: "livingroom-nspanel" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: "http://172.16.1.20:8123/local/nspanel_us.tft"
  nextion_blank_url: "http://172.16.1.20:8123/local/nspanel_blank.tft"
  temp_units: "F"

  ##### addon-configuration #####
  ## addon_climate ##
  # addon_climate_heater_relay: "1" # possible values: 1/2

  ##### CHANGE ME END #####

web_server:
  port: 80
  # https://esphome.io/components/web_server.html

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    refresh: 300s
    files:
      - nspanel_esphome.yaml # Basic package
      # Optional advanced and add-on configurations
      # - esphome/nspanel_esphome_advanced.yaml
      # - esphome/nspanel_esphome_addon_ble_tracker.yaml
      - esphome/nspanel_esphome_addon_bluetooth_proxy.yaml
      # - esphome/nspanel_esphome_addon_climate_cool.yaml
      # - esphome/nspanel_esphome_addon_climate_heat.yaml
      # - esphome/nspanel_esphome_addon_climate_dual.yaml
```
