### ISSUE TITLE
Can't flash when using ota new proposed nomeclature from ESPHome 

### ISSUE THREAD

**Issue by w1zz4** [Blackymas/NSPanel_HA_Blueprint#2169]
### TFT Version

4.3.9

### ESPHome Version

4.3.9

### Blueprint Version

4.3.9

### Panel Model

US

### What is the bug?

When flashing with proposed new ESPHome nomenclature for OTA :
# Example configuration entry
```yaml
ota:
  - platform: esphome
    password: !secret ota_password
``` 

It fails to connect to ota to upload new firmware with error msg :
ERROR Error auth result: Error: Authentication invalid. Is the password correct?

If I use alternate nomenclature without dash :
```yaml
ota:
  platform: esphome
  password: !secret ota_password
``` 

No error and flash is successfull

### Steps to Reproduce

1. Update to latest ESPHome version in HomeAssistant (2024.6.1)
2. Modify ota configuration section in yaml to propose ESPHome new configuration
3. Try to flash device with this new configuration

### Your Panel's YAML

```yaml
substitutions:
  # Settings - Editable values
  device_name: nspanel-salon
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  domain: home.famillerg.com
  fast_connect: 'True'
  ip: 172.30.30.20
  gw: 172.30.30.1
  mask: 255.255.255.0
  dns: 172.30.30.1
  # Add-on configuration (if needed)
  # heater_relay: "1"  # Possible values: "1" or "2"

# Customization area
##### My customization - Start #####
wifi:
  manual_ip:
    static_ip: ${ip}
    gateway: ${gw}
    subnet: ${mask}
    dns1: ${dns}

ota:
  - platform: esphome
    password: !secret ota_password

api:
  encryption:
    key: !secret api_key
    
web_server:
  port: 80
  auth:
    username: !secret webserver_user
    password: !secret webserver_pass

#esp32_ble_tracker:

#text_sensor:
#  - platform: ble_scanner
#    name: "BLE Devices Scanner"

# Sync RTC with HA
time:
  - platform: homeassistant
    timezone: America/Toronto
##### My customization - End #####

# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    refresh: 300s
    files:
      - nspanel_esphome.yaml # Basic NSPanel package
      # Optional packages for advanced features and other add-ons
      # - esphome/nspanel_esphome_addon_ble_tracker.yaml
      # - esphome/nspanel_esphome_addon_bluetooth_proxy.yaml # Bluetooth Proxy add-on package
      # - esphome/nspanel_esphome_addon_climate_cool.yaml
      # - esphome/nspanel_esphome_addon_climate_heat.yaml
      # - esphome/nspanel_esphome_addon_climate_dual.yaml
```

### ESPHome Logs

INFO Successfully compiled program.
INFO Connecting to 172.30.30.20
INFO Uploading /data/build/nspanel-salon/.pioenvs/nspanel-salon/firmware.bin (1229968 bytes)
ERROR Error auth result: Error: Authentication invalid. Is the password correct?

**Comment by edwardtfn** [comment]
You don't have to add the change to OTA. Version 4.3.9 already included all the changes needed for ESPHome v2024.6.0.

**Comment by edwardtfn** [comment]
If you wanna have your custom password, please try this:

```yaml
ota:
  - id: !extend ota_std
    password: !secret ota_password
```
