### ISSUE TITLE
Update over WiFi not working 

### ISSUE THREAD

**Issue by pvtex** [Blackymas/NSPanel_HA_Blueprint#2170]
### TFT Version

4.3.9

### ESPHome Version

4.3.9

### Blueprint Version

4.3.9

### Panel Model

None

### What is the bug?

when trying to update the nspanel over wifi,
it starts uploading but stops with this error

Flashing over serial is no problem

```
INFO Uploading /data/build/nspanel/.pioenvs/nspanel/firmware.bin (1225312 bytes)
ERROR Error receiving acknowledge chunk OK: [Errno 104] Connection reset by peer
```

### Steps to Reproduce

change yaml
upldate over wifi

### Your Panel's YAML

```yaml
esp32:
  framework:
    type: esp-idf

substitutions:
  ###### CHANGE ME START ######
  device_name: nspanel
  name: nspanel
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  #ota_password: "REMOVED"

  nextion_update_url: "http://homeassistant.local:8123/local/nspanel_eu.tft"
  nextion_blank_url: "http://homeassistant.local:8123/local/nspanel_blank.tft"

  # Add-on configuration (if needed)
  ## Add-on climate
  heater_relay: "2"     # Possible values: "1" or "2"
  temp_units: "°C"      # Temperatures in Fahrenheit
  temp_min: "10"        # Min supported temperature is 40°F
  temp_max: "30"        # Max supported temperature is 80°F
  temp_step: "1"        # Temperature granularity is 1°F
  heat_deadband: "1"  # Temperature delta before engaging heat
  heat_overrun: "1"   # Temperature delta before disengaging heat

# Customization area
##### My customization - Start #####
api:
  encryption:
    key: "REMOVED"

ota:
  - platform: esphome
    password: "REMOVED"
##### My customization - End #####

climate:
  - id: !extend thermostat_embedded
    visual:
      temperature_step: ${temp_step}
    preset:
      - name: Home
        default_target_temperature_low: 18
        mode: "heat"
      - name: Away
        default_target_temperature_low: 16
        mode: "heat"

# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    refresh: 300s
    files:
      - nspanel_esphome.yaml # Basic package
      # Optional advanced and add-on configurations
      # - esphome/nspanel_esphome_advanced.yaml
      # - esphome/nspanel_esphome_addon_ble_tracker.yaml
      # - esphome/nspanel_esphome_addon_bluetooth_proxy.yaml
      # - esphome/nspanel_esphome_addon_climate_cool.yaml
      - esphome/nspanel_esphome_addon_climate_heat.yaml
      # - esphome/nspanel_esphome_addon_climate_dual.yaml
      # - esphome/nspanel_esphome_addon_cover.yaml
```

### ESPHome Logs
```
INFO ESPHome 2024.6.1
INFO Reading configuration /config/esphome/nspanel.yaml...
INFO Detected timezone 'Europe/Berlin'
INFO Generating C++ source...
INFO Compiling app...
Processing nspanel (board: esp32dev; framework: espidf; platform: platformio/espressif32@5.4.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - framework-espidf @ 3.40407.0 (4.4.7) 
 - tool-cmake @ 3.16.4 
 - tool-ninja @ 1.7.1 
 - toolchain-esp32ulp @ 2.35.0-20220830 
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
Reading CMake configuration...
Dependency Graph
|-- ArduinoJson @ 6.18.5
|-- noise-c @ 0.1.4
Compiling .pioenvs/nspanel/src/main.o
Linking .pioenvs/nspanel/firmware.elf
RAM:   [=         ]   6.9% (used 22620 bytes from 327680 bytes)
Flash: [=======   ]  66.4% (used 1218733 bytes from 1835008 bytes)
Building .pioenvs/nspanel/firmware.bin
Creating esp32 image...
Successfully created esp32 image.
esp32_create_combined_bin([".pioenvs/nspanel/firmware.bin"], [".pioenvs/nspanel/firmware.elf"])
Wrote 0x13b260 bytes to file /data/build/nspanel/.pioenvs/nspanel/firmware.factory.bin, ready to flash to offset 0x0
esp32_copy_ota_bin([".pioenvs/nspanel/firmware.bin"], [".pioenvs/nspanel/firmware.elf"])
======================== [SUCCESS] Took 128.50 seconds ========================
INFO Successfully compiled program.
INFO Connecting to 192.168.88.136
INFO Uploading /data/build/nspanel/.pioenvs/nspanel/firmware.bin (1225312 bytes)
ERROR Error receiving acknowledge chunk OK: [Errno 104] Connection reset by peer
```

**Comment by plasterer41** [comment]
Add this to your yaml….ota:    - platform: esphomeSent from my iPadOn 21 Jun 2024, at 19:22, PVTex ***@***.***> wrote:﻿
TFT Version
4.3.9
ESPHome Version
4.3.9
Blueprint Version
4.3.9
Panel Model
None
What is the bug?
when trying to update the nspanel over wifi,
it starts uploading but stops with this error
Flashing over serial is no problem
INFO Uploading /data/build/nspanel/.pioenvs/nspanel/firmware.bin (1225312 bytes)
ERROR Error receiving acknowledge chunk OK: [Errno 104] Connection reset by peer

Steps to Reproduce
change yaml
upldate over wifi
Your Panel's YAML
esp32:
  framework:
    type: esp-idf

substitutions:
  ###### CHANGE ME START ######
  device_name: nspanel
  name: nspanel
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  #ota_password: "REMOVED"

  nextion_update_url: "http://homeassistant.local:8123/local/nspanel_eu.tft"
  nextion_blank_url: "http://homeassistant.local:8123/local/nspanel_blank.tft"

  # Add-on configuration (if needed)
  ## Add-on climate
  heater_relay: "2"     # Possible values: "1" or "2"
  temp_units: "°C"      # Temperatures in Fahrenheit
  temp_min: "10"        # Min supported temperature is 40°F
  temp_max: "30"        # Max supported temperature is 80°F
  temp_step: "1"        # Temperature granularity is 1°F
  heat_deadband: "1"  # Temperature delta before engaging heat
  heat_overrun: "1"   # Temperature delta before disengaging heat

# Customization area
##### My customization - Start #####
api:
  encryption:
    key: "REMOVED"

ota:
  - platform: esphome
    password: "REMOVED"
##### My customization - End #####

climate:
  - id: !extend thermostat_embedded
    visual:
      temperature_step: ${temp_step}
    preset:
      - name: Home
        default_target_temperature_low: 18
        mode: "heat"
      - name: Away
        default_target_temperature_low: 16
        mode: "heat"

# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    refresh: 300s
    files:
      - nspanel_esphome.yaml # Basic package
      # Optional advanced and add-on configurations
      # - esphome/nspanel_esphome_advanced.yaml
      # - esphome/nspanel_esphome_addon_ble_tracker.yaml
      # - esphome/nspanel_esphome_addon_bluetooth_proxy.yaml
      # - esphome/nspanel_esphome_addon_climate_cool.yaml
      - esphome/nspanel_esphome_addon_climate_heat.yaml
      # - esphome/nspanel_esphome_addon_climate_dual.yaml
      # - esphome/nspanel_esphome_addon_cover.yaml
ESPHome Logs
INFO ESPHome 2024.6.1
INFO Reading configuration /config/esphome/nspanel.yaml...
INFO Detected timezone 'Europe/Berlin'
INFO Generating C++ source...
INFO Compiling app...
Processing nspanel (board: esp32dev; framework: espidf; platform: ***@***.***)
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash

framework-espidf @ 3.40407.0 (4.4.7)
tool-cmake @ 3.16.4
tool-ninja @ 1.7.1
toolchain-esp32ulp @ 2.35.0-20220830
toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
Reading CMake configuration...
Dependency Graph
|-- ArduinoJson @ 6.18.5
|-- noise-c @ 0.1.4
Compiling .pioenvs/nspanel/src/main.o
Linking .pioenvs/nspanel/firmware.elf
RAM:   [=         ]   6.9% (used 22620 bytes from 327680 bytes)
Flash: [=======   ]  66.4% (used 1218733 bytes from 1835008 bytes)
Building .pioenvs/nspanel/firmware.bin
Creating esp32 image...
Successfully created esp32 image.
esp32_create_combined_bin([".pioenvs/nspanel/firmware.bin"], [".pioenvs/nspanel/firmware.elf"])
Wrote 0x13b260 bytes to file /data/build/nspanel/.pioenvs/nspanel/firmware.factory.bin, ready to flash to offset 0x0
esp32_copy_ota_bin([".pioenvs/nspanel/firmware.bin"], [".pioenvs/nspanel/firmware.elf"])
======================== [SUCCESS] Took 128.50 seconds ========================
INFO Successfully compiled program.
INFO Connecting to 192.168.88.136
INFO Uploading /data/build/nspanel/.pioenvs/nspanel/firmware.bin (1225312 bytes)
ERROR Error receiving acknowledge chunk OK: [Errno 104] Connection reset by peer

Home Assistant Logs
No response

**Comment by plasterer41** [comment]
Worked fine with ota for me with 4 out of 5 panels. Had to flash with cable for the 5th one for some reason Sent from my iPadOn 21 Jun 2024, at 19:22, PVTex ***@***.***> wrote:﻿
TFT Version
4.3.9
ESPHome Version
4.3.9
Blueprint Version
4.3.9
Panel Model
None
What is the bug?
when trying to update the nspanel over wifi,
it starts uploading but stops with this error
Flashing over serial is no problem
INFO Uploading /data/build/nspanel/.pioenvs/nspanel/firmware.bin (1225312 bytes)
ERROR Error receiving acknowledge chunk OK: [Errno 104] Connection reset by peer

Steps to Reproduce
change yaml
upldate over wifi
Your Panel's YAML
esp32:
  framework:
    type: esp-idf

substitutions:
  ###### CHANGE ME START ######
  device_name: nspanel
  name: nspanel
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  #ota_password: "REMOVED"

  nextion_update_url: "http://homeassistant.local:8123/local/nspanel_eu.tft"
  nextion_blank_url: "http://homeassistant.local:8123/local/nspanel_blank.tft"

  # Add-on configuration (if needed)
  ## Add-on climate
  heater_relay: "2"     # Possible values: "1" or "2"
  temp_units: "°C"      # Temperatures in Fahrenheit
  temp_min: "10"        # Min supported temperature is 40°F
  temp_max: "30"        # Max supported temperature is 80°F
  temp_step: "1"        # Temperature granularity is 1°F
  heat_deadband: "1"  # Temperature delta before engaging heat
  heat_overrun: "1"   # Temperature delta before disengaging heat

# Customization area
##### My customization - Start #####
api:
  encryption:
    key: "REMOVED"

ota:
  - platform: esphome
    password: "REMOVED"
##### My customization - End #####

climate:
  - id: !extend thermostat_embedded
    visual:
      temperature_step: ${temp_step}
    preset:
      - name: Home
        default_target_temperature_low: 18
        mode: "heat"
      - name: Away
        default_target_temperature_low: 16
        mode: "heat"

# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    refresh: 300s
    files:
      - nspanel_esphome.yaml # Basic package
      # Optional advanced and add-on configurations
      # - esphome/nspanel_esphome_advanced.yaml
      # - esphome/nspanel_esphome_addon_ble_tracker.yaml
      # - esphome/nspanel_esphome_addon_bluetooth_proxy.yaml
      # - esphome/nspanel_esphome_addon_climate_cool.yaml
      - esphome/nspanel_esphome_addon_climate_heat.yaml
      # - esphome/nspanel_esphome_addon_climate_dual.yaml
      # - esphome/nspanel_esphome_addon_cover.yaml
ESPHome Logs
INFO ESPHome 2024.6.1
INFO Reading configuration /config/esphome/nspanel.yaml...
INFO Detected timezone 'Europe/Berlin'
INFO Generating C++ source...
INFO Compiling app...
Processing nspanel (board: esp32dev; framework: espidf; platform: ***@***.***)
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash

framework-espidf @ 3.40407.0 (4.4.7)
tool-cmake @ 3.16.4
tool-ninja @ 1.7.1
toolchain-esp32ulp @ 2.35.0-20220830
toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
Reading CMake configuration...
Dependency Graph
|-- ArduinoJson @ 6.18.5
|-- noise-c @ 0.1.4
Compiling .pioenvs/nspanel/src/main.o
Linking .pioenvs/nspanel/firmware.elf
RAM:   [=         ]   6.9% (used 22620 bytes from 327680 bytes)
Flash: [=======   ]  66.4% (used 1218733 bytes from 1835008 bytes)
Building .pioenvs/nspanel/firmware.bin
Creating esp32 image...
Successfully created esp32 image.
esp32_create_combined_bin([".pioenvs/nspanel/firmware.bin"], [".pioenvs/nspanel/firmware.elf"])
Wrote 0x13b260 bytes to file /data/build/nspanel/.pioenvs/nspanel/firmware.factory.bin, ready to flash to offset 0x0
esp32_copy_ota_bin([".pioenvs/nspanel/firmware.bin"], [".pioenvs/nspanel/firmware.elf"])
======================== [SUCCESS] Took 128.50 seconds ========================
INFO Successfully compiled program.
INFO Connecting to 192.168.88.136
INFO Uploading /data/build/nspanel/.pioenvs/nspanel/firmware.bin (1225312 bytes)
ERROR Error receiving acknowledge chunk OK: [Errno 104] Connection reset by peer

Home Assistant Logs
No response

**Comment by pvtex** [comment]
this option is there please take a look in the first post

**Comment by edwardtfn** [comment]
Hi @pvtex, are you still having issues with OTA?
My apologies for the late reply here, but I'm moving to a new house and have boxes all around me, which makes quite difficult to be productive those days.

Looking at your YAML, I would suggest you change the OTA part by something like this:
```yaml
ota:
  - id: !extend ota_std
    password: "REMOVED"
```
