### ISSUE TITLE
`Bug` After update to 4.3.9 it hangs after reboot

### ISSUE THREAD

**Issue by erikklavora** [Blackymas/NSPanel_HA_Blueprint#2176]
### TFT Version

4.3.9

### ESPHome Version

4.3.9

### Blueprint Version

4.3.9

### Panel Model

EU

### What is the bug?

So I updated the panel to the latest fw yesterday over ota (from 4.3.7, espHome 2024.6.3) which went fine but when the panel restarted it was stuck at Please wait Initialising screen. OK so I removed the panel, flashed via cable, reinstalled and it worked. so I tryed to reboot the panel and is stuck again at initialising... The reboot button is displayed on the lower end and I can reboot the device too but it's just stuck. If I re-flash it via cable it works fine... once it's up, I can see the logs and all (well it works), bit hungs after reboot

### Your Panel's YAML

```yaml
substitutions:
  name: nspanel2
  device_name: NSPanel2
  # wifi_ssid: #!secret wifi_ssid
  wifi_ssid: Jota
  wifi_password: !secret wifi_password

  nextion_update_url: "http://192.168.178.98:8123/local/nspanel_eu.tft"
  nextion_blank_url: "http://192.168.178.98:8123/local/nspanel_blank.tft"

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      - esphome/nspanel_esphome_advanced.yaml # activate advanced (legacy) elements - can be useful for troubleshooting
      # - advanced/esphome/nspanel_esphome_advanced.yaml # activate advanced (legacy) elements - can be useful for troubleshooting
      # - nspanel_esphome_addon_climate_cool.yaml # activate for local climate (cooling) control
      # - nspanel_esphome_addon_climate_heat.yaml # activate for local climate (heater) control
    refresh: 1s

esphome:
  name: ${name}

esp32:
  framework:
    type: esp-idf

api:
  encryption:
    key: !secret nspanel_encryption

ota:
  platform: esphome
  password: !secret ota_password

safe_mode:

time:
  - id: !extend time_provider
    platform: sntp
    timezone: Europe/Ljubljana
    servers:
     - 0.pool.ntp.org
     - 1.pool.ntp.org
     - 2.pool.ntp.org

# Text sensors with general information.
text_sensor:
  # Expose ESPHome version as sensor.
  - platform: version
    name: Version
  # Expose WiFi information as sensors.
  - platform: wifi_info
    ip_address:
      name: IP
    ssid:
      name: SSID
    bssid:
      name: BSSID
```
