### ISSUE TITLE
Feature request: qr code service

### ISSUE THREAD

**Issue by danwright87** [Blackymas/NSPanel_HA_Blueprint#218]
As per other NS panel builds, would be good to have a QR page similar to notifications, Plows things such as sharing WiFi passwords.

Other builds use a service call to send the QR data and switch to the page. 

Believe Marcfager project has this as an example

**Comment by Blackymas** [comment]
Hi,
is already on the roadmap 😍

**Comment by danwright87** [comment]
If its any help, this is what I use currently. Page named QR with an object qr0.

```yaml
    # Service to show a QR code on the display (ex. for WiFi password)
    - service: display_qr
      variables:
        qrdata: string
      then:
        - lambda: |-
            id(disp1).set_component_text_printf("QR.qr0", "%s", qrdata.c_str());
            id(disp1).send_command_printf("page QR");
```

Once you move off the page then clear the QR code
id(disp1).send_command_printf("QR.qr0.txt=");
