### ISSUE TITLE
Found multiple configurations but password is inconsistent.

### ISSUE THREAD

**Issue by user34756361233** [Blackymas/NSPanel_HA_Blueprint#2186]
### TFT Version

4.3.9

### ESPHome Version

4.3.7

### Blueprint Version

4.3.9

### Panel Model

EU

### What is the bug?

When I try to compile I get the following error:

```
INFO ESPHome 2024.6.6
INFO Reading configuration /config/esphome/nspanel-badkamer.yaml...
INFO Detected timezone 'Europe/Amsterdam'
Failed config

ota.esphome: [source /data/packages/566b10a3/esphome/nspanel_esphome_core.yaml:129]
  
  Found multiple configurations but password is inconsistent.
  platform: esphome
  id: ota_std
  password: Y=V3ZXrV9JUVaGf
  version: 2
  port: 3232
```

The same happens if I try to clean the build files

### Steps to Reproduce

1. click on install
2. error appears

### Your Panel's YAML

```yaml
substitutions:
  ###### CHANGE ME START ######
  device_name: "nspanelbadkamer" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: "http://ipaddress:8123/local/nspanel_eu.tft"

  ##### addon-configuration #####
  ## addon_climate ##
  # addon_climate_heater_relay: "1" # possible values: 1/2

  ##### CHANGE ME END #####

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # - nspanel_esphome_advanced.yaml # activate advanced (legacy) elements - can be useful for troubleshooting
      # - nspanel_esphome_addon_climate_cool.yaml # activate for local climate (cooling) control
      # - nspanel_esphome_addon_climate_heat.yaml # activate for local climate (heater) control
    refresh: 300s

esp32:
  framework:
    type: arduino

##### My customization - Start #####

# Connect to a hidden Wi-Fi network.
wifi:
  networks:
    - id: !extend wifi_default
      hidden: true
      manual_ip:
        static_ip: ipaddress
        gateway: ipaddress
        subnet: 255.255.255.0
  fast_connect: true

# Custom web server credentials
web_server:
  auth:
    username: !secret web_server_username
    password: !secret web_server_password

# Use my global OTA password
ota:
  - platform: esphome
    password: !secret ota_password

##### My customization - End #####
```

### ESPHome Logs

2024-07-09 20:38:58,852 INFO Running command 'esphome --dashboard run /config/esphome/nspanel-badkamer.yaml --device 172.30.3.89'
2024-07-09 20:39:00,452 INFO Process exited with return code 2
2024-07-09 20:39:01,011 INFO 304 GET /devices (0.0.0.0) 1.15ms
2024-07-09 20:39:06,012 INFO 304 GET /devices (0.0.0.0) 1.28ms
2024-07-09 20:39:06,928 INFO 101 GET /clean (0.0.0.0) 0.44ms
2024-07-09 20:39:06,935 INFO Running command 'esphome --dashboard clean /config/esphome/nspanel-badkamer.yaml'
2024-07-09 20:39:07,781 INFO Process exited with return code 2
2024-07-09 20:39:11,018 INFO 304 GET /devices (0.0.0.0) 1.51ms
2024-07-09 20:39:16,018 INFO 304 GET /devices (0.0.0.0) 1.61ms

**Comment by edwardtfn** [comment]
Please try replacing this:
```yaml
# Use my global OTA password
ota:
  - platform: esphome
    password: !secret ota_password
```
By this:
```yaml
# Use my global OTA password
ota:
  - id: !extend ota_std
    password: !secret ota_password
```
