### ISSUE TITLE
NSPanel doesnt start after flashing - black screen

### ISSUE THREAD

**Issue by KKaiKn** [Blackymas/NSPanel_HA_Blueprint#2187]
### ESPHome Version

2024.6.6

### Blueprint Version

4.3.9

### Panel Model

EU

### What is the bug?

Hi,
after I have successfully flashed the NSPanel, the panel does not start. The panel remains black. 
After flashing, the message “configuration installed” appears. 

I have tried to connect the panel to 220V and also to 5V.
The panel also appears as offline in ESPHome. 
 Do you have any idea what the problem could be?

### Your Panel's YAML

```yaml
substitutions:

###### CHANGE ME START ######

  device_name: "nspanel" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: "http://http://192.168.178.96:8123/local/nspanel_eu.tft" # URL to local tft File
#  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft" # URL to Github

##### CHANGE ME END #####



##### DO NOT CHANGE ANYTHING! #####

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    refresh: 300s
    files:
      - nspanel_esphome.yaml # Basic package

esp32:
  framework:
    type: esp-idf

##### DO NOT CHANGE ANYTHING! #####
```
