### ISSUE TITLE
`Enhancement` NSpanel notification via HA notify platform

### ISSUE THREAD

**Issue by Kaibob2** [Blackymas/NSPanel_HA_Blueprint#2188]
### Enhancement Summary

If NSpanel would provide a notify.nspanel_xxx service, sending notifications would be easier.

### Detailed Description

I'm still struggling getting [alarmo](https://github.com/nielsfaber/alarmo) to work properly on the NSpanel. The problem is the "weird" behaviour of the alarm page when there are sensors open which require to be closed to arm the alarm. In the HA dashboard an according message pops up indicating which sensor(s) "blocks" arming the alarm (when using the alarmo card). This is also discussed here https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/1088
I see, that a complete redesign of the alarm page would be a struggle, so I thought of another approach.
Alarmo supports sending notifications for each and every event natively.
https://github.com/nielsfaber/alarmo?tab=readme-ov-file#wildcards
I currently use this with the pushover integration, with great success. 
Wouldn't it be possible to have a command available like notify.nspanel_livingroom which expects the default data for notifications?
I suppose in this project https://github.com/lubeda/EHMTX_custom_component/tree/main something very similar was done.

If you could simply call a notify service via alarmo to the nspanel as target when there is an open sensor a notifiaction would show up on the panel displaying which senor(s) are open.

**Comment by overdrivesFR** [comment]
Currently facing the same issue.
I'm trying to pass on the open sensor name with a wildcard to the esphome notification service, but it only works with plain text.
Having some usual notify service would be perfect.

Also Kaibob2 I've never heard of Pushover before, I would be interested in seeing the way you use it (since we both want the exact same thing I'd basically only need to change the panel name)

**Comment by Kaibob2** [comment]
I'm currently in the process of completely rebuilding my complete home automation due to moving from an appartment to a house which is, sadly, currently a construction site :)
I'm widely using NodeRed for the more complex automations as there is a dedicated Pushover node available.
Pushover is a great notification service as it is 100% reliable, has an android app which never sleeps and supports actionable notifications. https://pushover.net/

I solved the "open sensors when arming issue" quick and dirty with the following in node red:

```
[
    {
        "id": "a3c0c4b3ae68dd70",
        "type": "api-call-service",
        "z": "79fbee1193f7f074",
        "name": "",
        "server": "d03fc0aa.7f6a18",
        "version": 5,
        "debugenabled": false,
        "domain": "esphome",
        "service": "ns_panel_wohnzimmer_notification_show",
        "areaId": [],
        "deviceId": [],
        "entityId": [],
        "data": "{\t      \"label\": \"Arming impossible\",\t  \"message\": \"There are open sensors.\"\t}",
        "dataType": "jsonata",
        "mergeContext": "",
        "mustacheAltTags": false,
        "outputProperties": [],
        "queue": "none",
        "x": 890,
        "y": 560,
        "wires": [
            []
        ]
    },
    {
        "id": "0c5895c2288f0909",
        "type": "trigger-state",
        "z": "79fbee1193f7f074",
        "name": "",
        "server": "d03fc0aa.7f6a18",
        "version": 4,
        "inputs": 0,
        "outputs": 2,
        "exposeAsEntityConfig": "",
        "entityId": "alarm_control_panel.alarmzentrale",
        "entityIdType": "exact",
        "debugEnabled": false,
        "constraints": [
            {
                "targetType": "this_entity",
                "targetValue": "",
                "propertyType": "property",
                "propertyValue": "data.new_state.attributes.open_sensors",
                "comparatorType": "is_not",
                "comparatorValueDatatype": "str",
                "comparatorValue": "null"
            }
        ],
        "customOutputs": [],
        "outputInitially": false,
        "stateType": "str",
        "enableInput": false,
        "x": 220,
        "y": 580,
        "wires": [
            [
                "40f4f691086c4eb6"
            ],
            []
        ]
    },
    {
        "id": "40f4f691086c4eb6",
        "type": "switch",
        "z": "79fbee1193f7f074",
        "name": "",
        "property": "data.event.new_state.attributes.open_sensors",
        "propertyType": "msg",
        "rules": [
            {
                "t": "nnull"
            },
            {
                "t": "null"
            },
            {
                "t": "eq",
                "v": "",
                "vt": "str"
            }
        ],
        "checkall": "true",
        "repair": false,
        "outputs": 3,
        "x": 570,
        "y": 600,
        "wires": [
            [
                "a3c0c4b3ae68dd70"
            ],
            [
                "da0fca1153dfc59b"
            ],
            []
        ]
    },
    {
        "id": "da0fca1153dfc59b",
        "type": "api-call-service",
        "z": "79fbee1193f7f074",
        "name": "",
        "server": "d03fc0aa.7f6a18",
        "version": 5,
        "debugenabled": false,
        "domain": "esphome",
        "service": "ns_panel_wohnzimmer_notification_clear",
        "areaId": [],
        "deviceId": [],
        "entityId": [],
        "data": "",
        "dataType": "jsonata",
        "mergeContext": "",
        "mustacheAltTags": false,
        "outputProperties": [],
        "queue": "none",
        "x": 890,
        "y": 640,
        "wires": [
            []
        ]
    },
    {
        "id": "d03fc0aa.7f6a18",
        "type": "server",
        "name": "Home Assistant",
        "version": 5,
        "addon": true,
        "rejectUnauthorizedCerts": true,
        "ha_boolean": "y|yes|true|on|home|open",
        "connectionDelay": true,
        "cacheJson": true,
        "heartbeat": false,
        "heartbeatInterval": "30",
        "areaSelector": "friendlyName",
        "deviceSelector": "friendlyName",
        "entitySelector": "friendlyName",
        "statusSeparator": "at: ",
        "statusYear": "hidden",
        "statusMonth": "short",
        "statusDay": "numeric",
        "statusHourCycle": "h23",
        "statusTimeFormat": "h:m",
        "enableGlobalContextStore": true
    }
]
```

Maybe when I will ever have some spare time again I'll try to have the sensors listed on the panel by their names. For the moment I'm fine with the information that there IS any open window or door.

**Comment by overdrivesFR** [comment]
My problem truly is the open sensor name. Simply showing a warning on the nspanel was easy.
Either creating a script and calling it upon activation fail in Alarmo action tab :
```
alias: test2 notifs
sequence:
  - data:
      label: Warning
      message: A sensor is open
    action: esphome.nspanel1_notification_show
mode: single
description: ""
```
Or you can simply call the service by editing the action yaml in Alarmo action tab :
```
- service: esphome.nspanel1_notification_show
  data:
    label: Warning
    message: A sensor is open
```
The second one being really easy, but fails to pass on the wildcards.

**Comment by edwardtfn** [comment]
> Wouldn't it be possible to have a command available like notify.nspanel_livingroom which expects the default data for notifications?

Unfortunately ESPHome does not supports notify service, so the only way is using esphome services. 😩



> The second one being really easy, but fails to pass on the wildcards.

Could you please detail it better?

**Comment by overdrivesFR** [comment]
> Could you please detail it better?
```
- service: esphome.nspanel1_notification_show
  data:
    label: Warning
    message: {{open_sensors|lang=fr}}
```
returns the error
`value should be a string for dictionary value @ data['message']`

**Comment by edwardtfn** [comment]
What about this?

```yaml
- service: esphome.nspanel1_notification_show
  data:
    label: Warning
    message: '{{open_sensors|lang=fr}}' 
```

**Comment by overdrivesFR** [comment]
First thing I tried, plain text as well.

**Comment by edwardtfn** [comment]
And what about this?

```yaml
- service: esphome.nspanel1_notification_show
  data:
    label: Warning
    message: '{{ open_sensors }}' 
```

What is the content of `open_sensors`?

**Comment by edwardtfn** [comment]
I've just tried this and it worked just fine:

```yaml
action: esphome.office_workstation_panel_notification_show
data:
  label: Test 01
  message: >
    Battery status unavailable: {{
      states.sensor
      | selectattr('attributes.device_class', 'defined')
      | selectattr('attributes.device_class', 'eq', 'battery')
      | rejectattr('state', 'is_number')
      | map(attribute="attributes.friendly_name")
      | list
      | join("/r")
    }}
```

**Comment by overdrivesFR** [comment]
> What is the content of `open_sensors`?

`{{ open_sensors }}`, literally ^^

**Comment by edwardtfn** [comment]
But is it a list of entity_id's, or a string, or what?

**Comment by Kaibob2** [comment]
```
code_format: null
changed_by: null
code_arm_required: false
arm_mode: null
next_state: disarmed
open_sensors:
  binary_sensor.ble_opening_fenster_wz_rechts: open
  binary_sensor.ble_opening_fenster_wz_links: open
bypassed_sensors: null
delay: null
friendly_name: Alarmzentrale
supported_features: 47
```

**Comment by overdrivesFR** [comment]
> But is it a list of entity_id's, or a string, or what?

Oh my bad.
It's a string that shows the entity alias which prevents Alarmo from arming, and its state ("Garage door is open").

I can also use the wildcards using dev tools, the problem I'm facing is strictly from Alarmo.
Using them with the notify service to my smartphone works fine.

**Comment by Kaibob2** [comment]
Aren't we talking about the attribute "open_sensors" from alarmo which gets populated when the alarm is armed. Meaning it switches from "null" to, for Example, what I posted above.

**Comment by Kaibob2** [comment]
![Screenshot_20241002-230056](https://github.com/user-attachments/assets/e538bc7b-61a4-41fb-8401-98c161f73e4b)

**Comment by edwardtfn** [comment]
> Looks like a list to me.
> 
> ```
> code_format: null
> changed_by: null
> code_arm_required: false
> arm_mode: null
> next_state: disarmed
> open_sensors:
>   binary_sensor.ble_opening_fenster_wz_rechts: open
>   binary_sensor.ble_opening_fenster_wz_links: open
> bypassed_sensors: null
> delay: null
> friendly_name: Alarmzentrale
> supported_features: 47
> ```

It is a dictionary. Your panel's action requires a string, so you have to transform it.

Please try this:
```yaml
- service: esphome.nspanel1_notification_show
  data:
    label: Warning
    message: '{{ open_sensors.keys() | list | join(",") }}' 
```

Or this:
```yaml
- service: esphome.nspanel1_notification_show
  data:
    label: Warning
    message: '{{ state_attr("alarm_control_panel.alarmzentrale", "open_sensors").keys() | list | join("/r") }}' 
```

**Comment by overdrivesFR** [comment]
That's really close, thanks.
The last problem I face is showing the friendly name instead of the sensor name.
If I use :
`{{ state_attr(state_attr("alarm_control_panel.alarmo", "open_sensors").keys() | list | join("\r"), 'friendly_name') }}`
It works in a template, it returns something like "Garage door", but not as the content of a message, home assistant reject the synthax and refuse to save it. (maybe there's something obvious here, but I'm barely starting using yaml)

**Comment by Kaibob2** [comment]
For me 
`{{ state_attr(state_attr("alarm_control_panel.alarmzentrale", "open_sensors").keys() | list | join("\r"), 'friendly_name') }}` 
gives
![grafik](https://github.com/user-attachments/assets/6070e340-c312-49fa-967a-2a4376138732)
when more than one sensor is open.

**Comment by edwardtfn** [comment]
`state_attr` requires a single string with an `entity_id`, you are passing a list of strings.

Please try this:
```yaml
- service: esphome.nspanel1_notification_show
  data:
    label: Warning
    message: 'The following sensors are open:\r{{ states.binary_sensor | selectattr("entity_id", "in", state_attr("alarm_control_panel.alarmzentrale", "open_sensors").keys() | list) | map(attribute="attributes.friendly_name") | list | join("\r") }}' 
```
