### ISSUE TITLE
[RFF] Add a screen wakeup on any HW button press

### ISSUE THREAD

**Issue by ESP4Ever** [Blackymas/NSPanel_HA_Blueprint#2194]
### Enhancement Summary

Wakeup the screen on a HW buttin press

### Detailed Description

Hello.
Thank you for such a beautiful project! It looks very promising and makes life easier.
I would propose to add a config switch to en-/disable the screen wake-up on a HW button press. Currently the screen remains blanked on this event and to check the state a tap on screen needed what is not convenient.

**Comment by illuzn** [comment]
You can do this with your own home assistant automation.

```yaml
trigger:
  - platform: state
    entity_id:
      - binary_sensor.mbr_nspanel_left_button
    from: "off"
    to: "on"
action:
  - service: esphome.mbr_nspanel_wake_up
    data:
      reset_timer: true
```
