### ISSUE TITLE
`Bug` Nextion does not update with blueprint 

### ISSUE THREAD

**Issue by bulior** [Blackymas/NSPanel_HA_Blueprint#2198]
### TFT Version

v2024.3.0

### ESPHome Version

2024.7.1

### Blueprint Version

4.3.9

### Panel Model

EU

### What is the bug?

I updated from lovelace UI to the nspanel_blan.tft and everything works fine. After uploading the tft i see a QR code.

From ESP Home im able to controll the switches or the brigthness. After using the blueprint configuration and pressing the Update button i still see the QR-Code and nothing has changed

**The display will restarts and the logs will say:**
NSPanel Version ESPHome changed to 4.3.9
1:25:26 PM - 13 minutes ago

I tried all mentioned solution but im not able to solve my problem.

![IMG_7584](https://github.com/user-attachments/assets/85f870b8-9b7d-4794-8357-69e5c3daf007)
![IMG_7583](https://github.com/user-attachments/assets/e5c3e795-d174-4c07-b6fe-db3dc77166a5)

NsPanel1.yaml
  ```
substitutions:
    # Settings - Editable values
    device_name: "nspanel1"
    friendly_name: "NSPanel"
    wifi_ssid: !secret wifi_ssid
    wifi_password: !secret wifi_password
    nextion_update_url: "http://192.168.1.111:8123/local/nspanel_blank.tft"  # Optional
    # Add-on configuration (if needed)
    # heater_relay: "1"  # Possible values: "1" or "2"
  
  esp32:
    framework:
      type: esp-idf
  
  # Customization area
  ##### My customization - Start #####
  ##### My customization - End #####
  
  # Core and optional configurations
  packages:
    remote_package:
      url: https://github.com/Blackymas/NSPanel_HA_Blueprint
      ref: main
      refresh: 300s
      files:
        - nspanel_esphome.yaml # Basic package
        # Optional advanced and add-on configurations
        # - esphome/nspanel_esphome_advanced.yaml
        # - esphome/nspanel_esphome_addon_ble_tracker.yaml
        # - esphome/nspanel_esphome_addon_bluetooth_proxy.yaml
        # - esphome/nspanel_esphome_addon_climate_cool.yaml
        - esphome/nspanel_esphome_addon_climate_heat.yaml
        # - esphome/nspanel_esphome_addon_climate_dual.yaml
        # - esphome/nspanel_esphome_addon_cover.yaml
```

NSPanel Configuration:

```
alias: NSPanel Configuration
description: ""
use_blueprint:
  path: Blackymas/nspanel_blueprint.yaml
  input:
    nspanel_name: 99b3919569c8bb59f7aea0b125af160e
    language: de
    weather_entity: weather.forecast_home
    outdoortemp: sensor.umgebung_temperature
    button_page01_label: Staubsauger
    entity01: button.l10s_pro_ultra_heat_shortcut_1
    entity01_name: Alles S/W
```
<img width="325" alt="Screenshot 2024-07-23 at 13 44 40" src="https://github.com/user-attachments/assets/8c9e23f2-4246-42e3-9136-d528360dd3c8">
<img width="331" alt="image" src="https://github.com/user-attachments/assets/6ce27f99-5c1b-48de-acfb-71f5db6d81ce">

<img width="1013" alt="image" src="https://github.com/user-attachments/assets/82b656ff-4606-4f4a-9269-2148a5cf49d7">
