### ISSUE TITLE
OTA asking for password 

### ISSUE THREAD

**Issue by lecrams** [Blackymas/NSPanel_HA_Blueprint#2202]
### TFT Version

4.3.9

### ESPHome Version

2024.7.2

### Blueprint Version

4.3.9

### Panel Model

EU

### What is the bug?

I am trying to update my panel with the latest ESPhome version. I always build from the commandline. To build it I had to add OTA: platform: esphome in my yaml configuration. Once build the OTA is starting but it comes with "ESP requests password, but no password given!". I do not have any password set in my yaml!

How do I get my new binary uploaded via OTA?

### Your Panel's YAML

```yaml
substitutions:

###### CHANGE ME ######

  device_name: "nspanel1" 
  wifi_ssid: "xxxxxx"
  wifi_password: "xxxxx"

##### CHANGE ME #####


##### DO NOT CHANGE ANYTHING! #####

  nextion_update_url: "http://192.168.178.87:8123/local/nspanel.tft"

##### addon-configuration #####
  ## addon_climate ##
  # addon_climate_heater_relay: "1" # possible values: 1/2

  ##### CHANGE ME END #####

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # - nspanel_esphome_advanced.yaml # activate advanced (legacy) elements - can be useful for troubleshooting
      # - nspanel_esphome_addon_climate_cool.yaml # activate for local climate (cooling) control
      # - nspanel_esphome_addon_climate_heat.yaml # activate for local climate (heater) control
    refresh: 300s

##### My customization - Start #####

##### My customization - End #####
esphome:
  compile_process_limit: 1

sensor:
  - platform: uptime
    name: "${device_name} Uptime Sensor"

button:
  # Adds a button to put the panel to sleep
  - name: ${device_name} Sleep
    id: force_sleep
    platform: template
    icon: mdi:sleep
    on_press:
      then:
        - logger.log: Button Sleep pressed
        - lambda: |-
            if (id(current_page).state != "screensaver") id(disp1).goto_page("screensaver");
  
  # Adds a button to wake-up the panel (similar to the existing service)
  - name: ${device_name} Wake-up
    id: force_wake_up
    platform: template
    icon: mdi:alarm
    on_press:
      then:
        - logger.log: Button Wake-up pressed
        - lambda: |-
            if (id(current_page).state == "screensaver") id(disp1).goto_page(id(wakeup_page_name).state.c_str());
            // id(timer_page).execute(); // enable this if you want page timeout to be reset
            id(timer_sleep).execute();
            id(timer_dim).execute();
  
ota:
  platform: esphome
  
esp32:
  framework:
    type: arduino
```

### ESPHome Logs

ESP requests password, but no password given
