### ISSUE TITLE
Setting units to fahrenheit fails to display temperature

### ISSUE THREAD

**Issue by Maxcodesthings** [Blackymas/NSPanel_HA_Blueprint#2207]
### TFT Version

4.3.9

### ESPHome Version

4.3.9

### Blueprint Version

4.3.9

### Panel Model

US

### What is the bug?

When atttempting to change units to fahrenheit for the unit's internal temperature sensor the panel shows the thermometer icon but no temperature value

### Steps to Reproduce

1. Add `temp_units: "F"` or `temp_units: "°F"` to config section under `substitutions`
2. Reinstall firmware

### Your Panel's YAML

```yaml
substitutions:
  # Settings - Editable values
  device_name: "master-smart-panel"
  friendly_name: "Master Smart Panel"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  nextion_update_url: "http://homeassistant.local:8123/local/nspanel_eu.tft"  # Optional
  temp_units: "F"
  # Add-on configuration (if needed)
  # heater_relay: "1"  # Possible values: "1" or "2"

# Customization area
##### My customization - Start #####
api:
  encryption:
    key: !secret master_smart_panel_api
##### My customization - End #####

# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    refresh: 300s
    files:
      - nspanel_esphome.yaml # Basic package
```

### ESPHome Logs

There are no log entries pertaining to the issue directly. There is one section that shows the temperture being recorded in Celsius
```
[22:38:36][D][ntc:026]: 'Temperature' - Temperature: 21.2°C
[22:38:36][D][sensor:094]: 'Temperature': Sending state 21.21135 °C with 1 decimals of accuracy
```

However the temperature recorded in Home Assistant is in fahrenheit
