### ISSUE TITLE
`Bug` display settings page not showing (US TFT)

### ISSUE THREAD

**Issue by JoeyGE0** [Blackymas/NSPanel_HA_Blueprint#2211]
### TFT Version

4.3.9

### ESPHome Version

4.3.9

### Blueprint Version

4.3.7

### Panel Model

US

### What is the bug?

display settings page not showing. Page to control display brightness and other settings. Never worked for me. With multiple different tft versions tested

### Steps to Reproduce

Swipe down, I assume and setting/display settings should open if working properly?

### Your Panel's YAML

```yaml
substitutions:
  ###### CHANGE ME START ######
  device_name: "sonoffscreen" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: "http://joeyshass.local:8123/local/nspanel_us.tft"
  nextion_blank_url: "http://joeyshass.local:8123/local/nspanel_blank.tft"

  ##### addon-configuration #####
  ## addon_climate ##
  # addon_climate_heater_relay: "1" # possible values: 1/2

# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    refresh: 300s
    files:
      - nspanel_esphome.yaml # Basic package
      # - esphome/nspanel_esphome_addon_bluetooth_proxy.yaml
      # Optional advanced and add-on configurations
      # - esphome/nspanel_esphome_advanced.yaml
      # - nspanel_esphome_addon_climate_cool.yaml
      # - nspanel_esphome_addon_climate_heat.yaml
      # - nspanel_esphome_addon_climate_dual.yaml

##### My customization - Start #####

wifi:
  # ...
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.1.164
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.1.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0
##### My customization - End #####
```
