### ISSUE TITLE
`Bug` 

### ISSUE THREAD

**Issue by cfpandrade** [Blackymas/NSPanel_HA_Blueprint#2212]
### TFT Version

4.3.7

### ESPHome Version

4.3.9

### Blueprint Version

4.3.9

### Panel Model

EU

### What is the bug?

not installing

### Steps to Reproduce

INFO ESPHome 2024.7.2
INFO Reading configuration /config/esphome/esphome-web-e7f274.yaml...
INFO Detected timezone 'Europe/Dublin'
WARNING Found and merged multiple configurations for ota platform esphome port(s) [3232]
INFO Generating C++ source...
INFO Compiling app...
Processing ns-office (board: esp32dev; framework: espidf; platform: platformio/espressif32@5.4.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - framework-espidf @ 3.40407.0 (4.4.7) 
 - tool-cmake @ 3.16.4 
 - tool-ninja @ 1.7.1 
 - toolchain-esp32ulp @ 2.35.0-20220830 
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
Reading CMake configuration...
Dependency Graph
|-- ArduinoJson @ 6.18.5
|-- noise-c @ 0.1.4
Compiling .pioenvs/ns-office/src/main.o
Generating project linker script .pioenvs/ns-office/sections.ld
Compiling .pioenvs/ns-office/bootloader/bootloader_support/src/bootloader_console_loader.o
Compiling .pioenvs/ns-office/bootloader/bootloader_support/src/bootloader_panic.o
Compiling .pioenvs/ns-office/bootloader/bootloader_support/src/esp32/bootloader_sha.o
Compiling .pioenvs/ns-office/bootloader/bootloader_support/src/esp32/bootloader_soc.o
Compiling .pioenvs/ns-office/bootloader/bootloader_support/src/esp32/bootloader_esp32.o
/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/xtensa-esp32-elf-objdump: '/data/build/ns-office/.pioenvs/ns-office/esp-idf/bt/libbt.a': No such file
Traceback (most recent call last):
  File "/data/cache/platformio/packages/framework-espidf/tools/ldgen/ldgen.py", line 178, in <module>
    main()
  File "/data/cache/platformio/packages/framework-espidf/tools/ldgen/ldgen.py", line 134, in main
    dump = StringIO(subprocess.check_output([objdump, '-h', library]).decode())
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/data/cache/platformio/packages/toolchain-xtensa-esp32/bin/xtensa-esp32-elf-objdump', '-h', '/data/build/ns-office/.pioenvs/ns-office/esp-idf/bt/libbt.a']' returned non-zero exit status 1.
*** [.pioenvs/ns-office/sections.ld] Error 1
========================= [FAILED] Took 60.89 seconds =========================

### Your Panel's YAML

```yaml
wifi:
  use_address: 192.168.35.141

# OTA (Over the air updates) password. Add to your secrets.yaml
api:
  encryption:
    key: !secret api_key
ota:
  - platform: esphome
#    password: !secret ota_pass

substitutions:
###### CHANGE ME START ######
  ota_password: !secret ota_pass
  friendly_name: "NS Office"
  device_name: "ns-office" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

#  nextion_update_url: "http://192.168.50.168:8123/local/nspanel/nspanel_blank.tft" # URL to local tft File
  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_blank.tft" # URL to local tft File

##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint/
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####
```
