### ISSUE TITLE
Dual climate UI slow and unresponsive 

### ISSUE THREAD

**Issue by nickp7** [Blackymas/NSPanel_HA_Blueprint#2213]
### TFT Version

4.3.9

### ESPHome Version

4.3.9

### Blueprint Version

4.3.9

### Panel Model

US (Landscape)

### What is the bug?

Whenever i change the temperature on the climate UI most of the times the lines doesn't move, the touch is unresponsive or it glitch out and the setpoint flicks between the previous state and the one i'm trying to set. 

https://github.com/user-attachments/assets/b443deca-6ff6-458f-abb0-f1d4d3c7a783

### Steps to Reproduce

1. Press the temperature icon on the UI
2. try to change the temperature

### Your Panel's YAML

```yaml
substitutions:
  # Settings - Editable values
  device_name: "sonoffnspanelus" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  nextion_update_url: "http://hasynology.local:8123/local/nspanel_us_land.tft"

  ##### addon-configuration #####
  ##addon_climate ##
  heater_relay: "2"     # Possible values: "1" or "2"
  cooler_relay: "1"     # Possible values: "1" or "2"
  temp_units: "°C"      # Temperatures in Fahrenheit
  temp_min: "15"        # Min supported temperature is 40°F
  temp_max: "35"        # Max supported temperature is 80°F
  temp_step: "1"        # Temperature granularity is 1°F
  cool_deadband: "1.2"  # Temperature delta before engaging cooling
  cool_overrun: "1.2"   # Temperature delta before disengaging cooling
  heat_deadband: "1.2"  # Temperature delta before engaging heat
  heat_overrun: "1.2"   # Temperature delta before disengaging heat
  ##### CHANGE ME END #####

  ##### CHANGE ME END #####



packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    refresh: 300s
    files:
      - nspanel_esphome.yaml # Basic package
      # Optional advanced and add-on configurations
      # - esphome/nspanel_esphome_advanced.yaml
      # - esphome/nspanel_esphome_addon_ble_tracker.yaml
      # - esphome/nspanel_esphome_addon_bluetooth_proxy.yaml
      # - esphome/nspanel_esphome_addon_climate_cool.yaml
      # - esphome/nspanel_esphome_addon_climate_heat.yaml
      - esphome/nspanel_esphome_addon_climate_dual.yaml
      # - esphome/nspanel_esphome_addon_cover.yaml
```

### ESPHome Logs

INFO ESPHome 2024.7.3
INFO Reading configuration /config/esphome/sonoff-nspanel-us.yaml...
INFO Detected timezone 'Europe/Rome'
INFO Starting log output from 192.168.6.100 using esphome API
INFO Successfully connected to sonoffnspanelus @ 192.168.6.100 in 0.034s
INFO Successful handshake with sonoffnspanelus @ 192.168.6.100 in 0.025s
[10:25:23][I][app:100]: ESPHome version 2024.7.3 compiled on Aug  2 2024, 09:55:33
[10:25:23][I][app:102]: Project esphome.NSPanel_HA_Blueprint version 4.3.9
[10:25:23][C][wifi:599]: WiFi:
[10:25:23][C][wifi:427]:   Local MAC: C8:F0:9E:EE:B5:78
[10:25:23][C][wifi:432]:   SSID: [redacted]
[10:25:23][C][wifi:435]:   IP Address: 192.168.6.100
[10:25:23][C][wifi:439]:   BSSID: [redacted]
[10:25:23][C][wifi:440]:   Hostname: 'sonoffnspanelus'
[10:25:23][C][wifi:442]:   Signal strength: -50 dB ▂▄▆█
[10:25:23][C][wifi:446]:   Channel: 1
[10:25:23][C][wifi:447]:   Subnet: 255.255.255.0
[10:25:23][C][wifi:448]:   Gateway: 192.168.6.1
[10:25:23][C][wifi:449]:   DNS1: 80.93.143.42
[10:25:23][C][wifi:450]:   DNS2: 80.93.143.44
[10:25:23][C][logger:185]: Logger:
[10:25:23][C][logger:186]:   Level: DEBUG
[10:25:23][C][uart.idf:159]: UART Bus 0:
[10:25:23][C][uart.idf:160]:   TX Pin: GPIO16
[10:25:23][C][uart.idf:161]:   RX Pin: GPIO17
[10:25:23][C][uart.idf:163]:   RX Buffer Size: 256
[10:25:23][C][uart.idf:165]:   Baud Rate: 115200 baud
[10:25:23][C][uart.idf:166]:   Data Bits: 8
[10:25:23][C][uart.idf:167]:   Parity: NONE
[10:25:23][C][uart.idf:168]:   Stop bits: 1
[10:25:23][C][ledc.output:176]: LEDC Output:
[10:25:23][C][ledc.output:177]:   Pin GPIO21
[10:25:23][C][ledc.output:178]:   LEDC Channel: 0
[10:25:23][C][ledc.output:179]:   PWM Frequency: 1000.0 Hz
[10:25:23][C][ledc.output:180]:   Phase angle: 0.0°
[10:25:23][C][ledc.output:181]:   Bit depth: 16
[10:25:23][C][template.binary_sensor:028]: Template Binary Sensor 'Nextion display'
[10:25:23][C][template.binary_sensor:028]:   Device Class: 'connectivity'
[10:25:23][C][template.number:050]: Template Number 'Display Brightness'
[10:25:23][C][template.number:050]:   Unit of Measurement: '%'
[10:25:23][C][template.number:051]:   Optimistic: YES
[10:25:23][C][template.number:052]:   Update Interval: 60.0s
[10:25:23][C][template.number:050]: Template Number 'Display Brightness Dimdown'
[10:25:23][C][template.number:050]:   Unit of Measurement: '%'
[10:25:23][C][template.number:051]:   Optimistic: YES
[10:25:23][C][template.number:052]:   Update Interval: 60.0s
[10:25:23][C][template.number:050]: Template Number 'Display Brightness Sleep'
[10:25:23][C][template.number:050]:   Unit of Measurement: '%'
[10:25:23][C][template.number:051]:   Optimistic: YES
[10:25:23][C][template.number:052]:   Update Interval: 60.0s
[10:25:23][C][template.number:050]: Template Number 'Temperature Correction'
[10:25:23][C][template.number:050]:   Unit of Measurement: '°C'
[10:25:23][C][template.number:051]:   Optimistic: YES
[10:25:23][C][template.number:052]:   Update Interval: 60.0s
[10:25:23][C][template.number:050]: Template Number 'Timeout Page'
[10:25:23][C][template.number:050]:   Icon: 'mdi:timer'
[10:25:23][C][template.number:050]:   Unit of Measurement: 's'
[10:25:23][C][template.number:051]:   Optimistic: YES
[10:25:23][C][template.number:052]:   Update Interval: 60.0s
[10:25:23][C][template.number:050]: Template Number 'Timeout Dimming'
[10:25:23][C][template.number:050]:   Icon: 'mdi:timer'
[10:25:23][C][template.number:050]:   Unit of Measurement: 's'
[10:25:23][C][template.number:051]:   Optimistic: YES
[10:25:23][C][template.number:052]:   Update Interval: 60.0s
[10:25:23][C][template.number:050]: Template Number 'Timeout Sleep'
[10:25:23][C][template.number:050]:   Icon: 'mdi:timer'
[10:25:23][C][template.number:050]:   Unit of Measurement: 's'
[10:25:23][C][template.number:051]:   Optimistic: YES
[10:25:23][C][template.number:052]:   Update Interval: 60.0s
[10:25:23][C][template.select:065]: Template Select 'Baud rate'
[10:25:23][C][template.select:065]:   Icon: 'mdi:swap-horizontal'
[10:25:23][C][template.select:066]:   Update Interval: 60.0s
[10:25:23][C][template.select:069]:   Optimistic: YES
[10:25:23][C][template.select:070]:   Initial Option: 115200
[10:25:23][C][template.select:071]:   Restore Value: YES
[10:25:23][C][template.select:065]: Template Select 'Wake-up page'
[10:25:23][C][template.select:065]:   Icon: 'mdi:page-next-outline'
[10:25:23][C][template.select:066]:   Update Interval: 60.0s
[10:25:23][C][template.select:069]:   Optimistic: YES
[10:25:23][C][template.select:070]:   Initial Option: home
[10:25:23][C][template.select:071]:   Restore Value: YES
[10:25:23][C][template.select:065]: Template Select 'Update TFT display - Model'
[10:25:23][C][template.select:065]:   Icon: 'mdi:file-sync'
[10:25:23][C][template.select:066]:   Update Interval: 60.0s
[10:25:23][C][template.select:069]:   Optimistic: YES
[10:25:23][C][template.select:070]:   Initial Option: NSPanel EU
[10:25:23][C][template.select:071]:   Restore Value: YES
[10:25:23][C][template.select:065]: Template Select 'Update TFT display - Baud rate'
[10:25:23][C][template.select:065]:   Icon: 'mdi:swap-horizontal'
[10:25:23][C][template.select:066]:   Update Interval: 60.0s
[10:25:23][C][template.select:069]:   Optimistic: YES
[10:25:23][C][template.select:070]:   Initial Option: 921600
[10:25:23][C][template.select:071]:   Restore Value: YES
[10:25:23][C][switch.gpio:068]: GPIO Switch 'Nextion display - Power'
[10:25:23][C][switch.gpio:091]:   Restore Mode: always ON
[10:25:23][C][switch.gpio:031]:   Pin: GPIO4
[10:25:23][C][template.text_sensor:020]: Template Sensor 'Device Name'
[10:25:23][C][template.text_sensor:020]:   Icon: 'mdi:identifier'
[10:25:23][C][template.text_sensor:020]: Template Sensor 'Detailed Entity'
[10:25:23][C][template.text_sensor:020]:   Icon: 'mdi:tablet-dashboard'
[10:25:23][C][template.text_sensor:020]: Template Sensor 'Notification Label'
[10:25:23][C][template.text_sensor:020]: Template Sensor 'Notification Text'
[10:25:23][C][template.text_sensor:020]: Template Sensor 'Version Blueprint'
[10:25:23][C][template.text_sensor:020]:   Icon: 'mdi:tag-text-outline'
[10:25:23][C][template.text_sensor:020]: Template Sensor 'Version ESPHome'
[10:25:23][C][template.text_sensor:020]:   Icon: 'mdi:tag-text-outline'
[10:25:23][C][template.sensor:022]: Template Sensor 'Blueprint'
[10:25:23][C][template.sensor:022]:   State Class: ''
[10:25:23][C][template.sensor:022]:   Unit of Measurement: '%'
[10:25:23][C][template.sensor:022]:   Accuracy Decimals: 1
[10:25:23][C][template.sensor:022]:   Icon: 'mdi:link-variant'
[10:25:23][C][template.sensor:023]:   Update Interval: 60.0s
[10:25:24][C][gpio.binary_sensor:015]: GPIO Binary Sensor 'Left Button'
[10:25:24][C][gpio.binary_sensor:016]:   Pin: GPIO14
[10:25:24][C][gpio.binary_sensor:015]: GPIO Binary Sensor 'Right Button'
[10:25:24][C][gpio.binary_sensor:016]:   Pin: GPIO27
[10:25:24][C][switch.gpio:068]: GPIO Switch 'Relay 1'
[10:25:24][C][switch.gpio:091]:   Restore Mode: restore defaults to OFF
[10:25:24][C][switch.gpio:031]:   Pin: GPIO22
[10:25:24][C][switch.gpio:068]: GPIO Switch 'Relay 2'
[10:25:24][C][switch.gpio:091]:   Restore Mode: restore defaults to OFF
[10:25:24][C][switch.gpio:031]:   Pin: GPIO19
[10:25:24][C][template.switch:068]: Template Switch 'Notification unread'
[10:25:24][C][template.switch:091]:   Restore Mode: always OFF
[10:25:24][C][template.switch:057]:   Optimistic: YES
[10:25:24][C][template.switch:068]: Template Switch 'Notification sound'
[10:25:24][C][template.switch:091]:   Restore Mode: restore defaults to OFF
[10:25:24][C][template.switch:057]:   Optimistic: YES
[10:25:24][C][template.switch:068]: Template Switch 'Relay 0 (dummy)'
[10:25:24][C][template.switch:091]:   Restore Mode: always OFF
[10:25:24][C][template.switch:057]:   Optimistic: YES
[10:25:24][C][psram:020]: PSRAM:
[10:25:24][C][psram:021]:   Available: YES
[10:25:24][C][psram:024]:   Size: 2036 KB
[10:25:24][C][rtttl:029]: Rtttl
[10:25:24][C][nextion:128]: Nextion:
[10:25:24][C][nextion:129]:   Device Model:     NX4832F035_011C
[10:25:24][C][nextion:130]:   Firmware Version: 72
[10:25:24][C][nextion:131]:   Serial Number:    4FB034017EF1327D
[10:25:24][C][nextion:132]:   Flash Size:       16777216
[10:25:24][C][nextion:133]:   Wake On Touch:    YES
[10:25:24][C][nextion:134]:   Exit reparse:     YES
[10:25:24][C][factory_reset.button:011]: Factory Reset Button 'Factory reset'
[10:25:24][C][factory_reset.button:011]:   Icon: 'mdi:restart-alert'
[10:25:24][C][restart.button:017]: Restart Button 'Restart'
[10:25:24][C][restart.button:017]:   Icon: 'mdi:restart'
[10:25:24][C][adc:097]: ADC Sensor 'ntc_source'
[10:25:24][C][adc:097]:   Device Class: 'voltage'
[10:25:24][C][adc:097]:   State Class: 'measurement'
[10:25:24][C][adc:097]:   Unit of Measurement: 'V'
[10:25:24][C][adc:097]:   Accuracy Decimals: 2
[10:25:24][C][adc:107]:   Pin: GPIO38
[10:25:24][C][adc:122]:   Attenuation: 12db
[10:25:24][C][adc:141]:   Samples: 4
[10:25:24][C][adc:142]:   Update Interval: 10.0s
[10:25:24][C][resistance:010]: Resistance Sensor 'resistance_sensor'
[10:25:24][C][resistance:010]:   State Class: 'measurement'
[10:25:24][C][resistance:010]:   Unit of Measurement: 'Ω'
[10:25:24][C][resistance:010]:   Accuracy Decimals: 1
[10:25:24][C][resistance:010]:   Icon: 'mdi:flash'
[10:25:24][C][resistance:011]:   Configuration: DOWNSTREAM
[10:25:24][C][resistance:012]:   Resistor: 11200.00Ω
[10:25:24][C][resistance:013]:   Reference Voltage: 3.3V
[10:25:24][C][ntc:014]: NTC Sensor 'Temperature'
[10:25:24][C][ntc:014]:   Device Class: 'temperature'
[10:25:24][C][ntc:014]:   State Class: 'measurement'
[10:25:24][C][ntc:014]:   Unit of Measurement: '°C'
[10:25:24][C][ntc:014]:   Accuracy Decimals: 1
[10:25:24][C][thermostat.climate:1290]: Thermostat 'Thermostat'
[10:25:24][C][thermostat.climate:1293]:   Minimum Set Point Differential: 0.5°C
[10:25:24][C][thermostat.climate:1295]:   Start-up Delay Enabled: NO
[10:25:24][C][thermostat.climate:1297]:   Cooling Parameters:
[10:25:24][C][thermostat.climate:1298]:     Deadband: 1.2°C
[10:25:24][C][thermostat.climate:1299]:     Overrun: 1.2°C
[10:25:24][C][thermostat.climate:1306]:     Minimum Off Time: 300s
[10:25:24][C][thermostat.climate:1308]:     Minimum Run Time: 300s
[10:25:24][C][thermostat.climate:1311]:   Heating Parameters:
[10:25:24][C][thermostat.climate:1312]:     Deadband: 1.2°C
[10:25:24][C][thermostat.climate:1313]:     Overrun: 1.2°C
[10:25:24][C][thermostat.climate:1320]:     Minimum Off Time: 300s
[10:25:24][C][thermostat.climate:1322]:     Minimum Run Time: 300s
[10:25:24][C][thermostat.climate:1337]:   Minimum Idle Time: 30s
[10:25:24][C][thermostat.climate:1338]:   Supports AUTO: NO
[10:25:24][C][thermostat.climate:1339]:   Supports HEAT/COOL: YES
[10:25:24][C][thermostat.climate:1340]:   Supports COOL: YES
[10:25:24][C][thermostat.climate:1341]:   Supports DRY: NO
[10:25:24][C][thermostat.climate:1342]:   Supports FAN_ONLY: NO
[10:25:24][C][thermostat.climate:1344]:   Supports FAN_ONLY_ACTION_USES_FAN_MODE_TIMER: NO
[10:25:24][C][thermostat.climate:1345]:   Supports FAN_ONLY_COOLING: NO
[10:25:24][C][thermostat.climate:1347]:   Supports FAN_WITH_COOLING: NO
[10:25:24][C][thermostat.climate:1350]:   Supports FAN_WITH_HEATING: NO
[10:25:24][C][thermostat.climate:1352]:   Supports HEAT: YES
[10:25:24][C][thermostat.climate:1353]:   Supports FAN MODE ON: NO
[10:25:24][C][thermostat.climate:1354]:   Supports FAN MODE OFF: NO
[10:25:24][C][homeassistant.time:010]: Home Assistant Time:
[10:25:24][C][homeassistant.time:011]:   Timezone: 'CET-1CEST,M3.5.0,M10.5.0/3'
[10:25:25][C][mdns:116]: mDNS:
[10:25:25][C][mdns:117]:   Hostname: sonoffnspanelus
[10:25:25][C][esphome.ota:073]: Over-The-Air updates:
[10:25:25][C][esphome.ota:074]:   Address: sonoffnspanelus.local:3232
[10:25:25][C][esphome.ota:075]:   Version: 2
[10:25:25][C][esphome.ota:078]:   Password configured
[10:25:25][C][safe_mode:018]: Safe Mode:
[10:25:25][C][safe_mode:020]:   Boot considered successful after 60 seconds
[10:25:25][C][safe_mode:021]:   Invoke after 10 boot attempts
[10:25:25][C][safe_mode:023]:   Remain in safe mode for 300 seconds
[10:25:25][C][api:139]: API Server:
[10:25:25][C][api:140]:   Address: sonoffnspanelus.local:6053
[10:25:25][C][api:144]:   Using noise encryption: NO
[10:25:25][C][wifi_signal.sensor:009]: WiFi Signal 'RSSI'
[10:25:25][C][wifi_signal.sensor:009]:   Device Class: 'signal_strength'
[10:25:25][C][wifi_signal.sensor:009]:   State Class: 'measurement'
[10:25:25][C][wifi_signal.sensor:009]:   Unit of Measurement: 'dBm'
[10:25:25][C][wifi_signal.sensor:009]:   Accuracy Decimals: 0
[10:25:25][C][wifi_signal.sensor:009]:   Icon: 'mdi:wifi'
[10:25:27][D][sensor:094]: 'ntc_source': Sending state 1.52233 V with 2 decimals of accuracy
[10:25:27][D][resistance:039]: 'resistance_sensor' - Resistance 9591.3Ω
[10:25:27][D][sensor:094]: 'resistance_sensor': Sending state 9591.29883 Ω with 1 decimals of accuracy
[10:25:27][D][ntc:026]: 'Temperature' - Temperature: 25.9°C
[10:25:27][D][sensor:094]: 'Temperature': Sending state 25.94205 °C with 1 decimals of accuracy
[10:25:27][D][climate:396]: 'Thermostat' - Sending state:
[10:25:27][D][climate:399]:   Mode: HEAT
[10:25:27][D][climate:401]:   Action: IDLE
[10:25:27][D][climate:410]:   Preset: HOME
[10:25:27][D][climate:419]:   Current Temperature: 25.94°C
[10:25:27][D][climate:423]:   Target Temperature: Low: 17.50°C High: 29.50°C
