### ISSUE TITLE
`Bug` Updating TFT from 4.3.9 to 4.3.10 Fails

### ISSUE THREAD

**Issue by illuzn** [Blackymas/NSPanel_HA_Blueprint#2223]
### TFT Version

4.3.9

### Firmware Version

4.3.10

### Blueprint Version

4.3.10

### Panel Model

US

### What is the bug?

Updating firmware and blueprint to 4.3.9 completely successfully.

TFT refuses to update to 4.3.10 though. I did notice that it does a partial update (starting at around 89%).

After the attempted update the TFT version is marked as `unknown` in HA for my nspanel and the logs are filled with the following:
```text
[nextion:416]: Nextion reported variable name invalid!
```

It appears the TFT version is still 4.3.9.

Forcing a full update of TFT by using the blank model then US also fails (but ungracefully). Doing this halts the TFT at the initial loading screen and when failing, the TFT screen reports TFT version 4.3.9, blueprint unknown and esphome unknown. With the bottom progress bar not moving at all.

In order to eliminate all other potential issues, I have manually downloaded https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/v4.3.10/hmi/nspanel_us.tft and set use_nextion_update_url (also to no avail).

Have downgraded to 4.3.9 in the meantime and it works with those errors (and a notification that I need to upgrade the TFT).

### Steps to Reproduce

1. NSPanel running 4.3.9 US TFT and 4.3.10 Blueprint and Firmware.
2. Attempt to update to 4.3.10 US TFT.
3. TFT will fully update but fail after reboot.

### Your Panel's YAML

```yaml
Not Applicable
```

### ESPHome Logs

Not Applicable

### Home Assistant Logs

Not Applicable

Edit: It appears that this applies to more than just the US TFT.

**Comment by KoKolaj** [comment]
EU version, the same problem
![nspanel TFT](https://github.com/user-attachments/assets/fd1242d4-b97f-4c36-a6b4-95286b41b67f)

**Comment by illuzn** [comment]
@edwardtfn Sorry to tag you, looks like this is a critical issue causing complete failure and recommend pulling the update in the meantime.

**Comment by illuzn** [comment]
If you need to downgrade to 4.3.9, here's what I did:

In your yaml change these sections:
```yaml
substitutions:
  nextion_update_url: "http://homeassistant.local:8123/local/nspanel_us.tft" # You may not already have this. 
# Obviously, set it to a local address where you will be serving your TFT file from (must be http and not https).

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: v4.3.9 # This previously should have said 'main'
    files:
      - nspanel_esphome.yaml
    refresh: 1 # This previously should have said 300 and avoids any caching issues you should have.
```

Then download your relevant TFT file from https://github.com/Blackymas/NSPanel_HA_Blueprint/tree/v4.3.9/hmi and manually upload it using `use nextion_update_url`
