### ISSUE TITLE
`Bug` Blank Button Pages with Bluetooth Proxy Enabled

### ISSUE THREAD

**Issue by BlairC1** [Blackymas/NSPanel_HA_Blueprint#2228]
### TFT Version

4.3.11

### Firmware Version

4.3.11

### Blueprint Version

4.3.11

### Panel Model

US (Landscape)

### What is the bug?

When I swipe to access the button pages they either show up blank or take a 2-3 seconds to load. I've tried to roll back to 4.3.9 but the issue remains. The only fix I've found is to disable bluetooth proxy. I've got this issue with both of my nspanels. Anyone else seeing this?

### Your Panel's YAML

```yaml
substitutions:

###### CHANGE ME START ######

  device_name: kitchennspanel 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: "http://192.168.1.24:8123/local/nspanel_us_land.tft" # URL to local tft File
#  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_us.tft" # URL to Github

#esp32_ble_tracker:
#  scan_parameters:
#    interval: 1100ms
#    window: 1100ms
#    active: true

##### CHANGE ME END #####



##### DO NOT CHANGE ANYTHING! #####

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    refresh: 300s
    files:
      - nspanel_esphome.yaml # Basic NSPanel package
      # Optional packages for advanced features and other add-ons
      # - esphome/nspanel_esphome_addon_ble_tracker.yaml
      - esphome/nspanel_esphome_addon_bluetooth_proxy.yaml # Bluetooth Proxy add-on package
      # - esphome/nspanel_esphome_addon_climate_cool.yaml
      # - esphome/nspanel_esphome_addon_climate_heat.yaml
      # - esphome/nspanel_esphome_addon_climate_dual.yaml
      # - esphome/nspanel_esphome_addon_cover.yaml
##### DO NOT CHANGE ANYTHING! #####

    
#uart:
#  - id: !extend tf_uart
#    baud_rate: 115200

esp32:
  framework:
    type: esp-idf
```

### ESPHome Logs

[logs_kitchennspanel_logs.txt](https://github.com/user-attachments/files/16631085/logs_kitchennspanel_logs.txt)
