### ISSUE TITLE
`Bug` Syntax Error, YAML

### ISSUE THREAD

**Issue by ucakca** [Blackymas/NSPanel_HA_Blueprint#2231]
### Panel Model

None

### What is the bug?

I hope someone can help with my issue.

INFO ESPHome 2024.7.3
INFO Reading configuration /config/esphome/nspanelhome.yaml...
ERROR Error while reading config: Invalid YAML syntax:

mapping values are not allowed here
  in "/config/esphome/nspanelhome.yaml", line 3, column 14
![Screenshot_20240817_232112](https://github.com/user-attachments/assets/1b450630-9a57-45c4-aaaa-373fa488bdd5)

Thank U a lot!

**Comment by edwardtfn** [comment]
1. Try to comment out the line 1
2. Try to align the indentation of line 3 with line 4

Something like this:
```yaml
#NSpanel-blacky.yaml

substitutions:
  # Settings - Editable values
  device_name: "nspanelhome"
...
```
