### ISSUE TITLE
`Bug` Can't update to 4.3.11 (on LinuxMint 22)

### ISSUE THREAD

**Issue by mills1975** [Blackymas/NSPanel_HA_Blueprint#2238]
### TFT Version

4.3.9

### Firmware Version

4.3.9

### Blueprint Version

4.3.9

### Panel Model

EU

### What is the bug?

Hello,
when I try to update from 4.3.9 to 4.3.11, I run in to the following error:
I didn't change anything on my PC except I upgraded from Mint 21.3 to 22.

Log:
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - framework-espidf @ 3.40407.0 (4.4.7) 
 - tool-cmake @ 3.16.4 
 - tool-ninja @ 1.7.1 
 - toolchain-esp32ulp @ 2.35.0-20220830 
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
/home/andreas/.platformio/penv/.espidf-4.4.7/bin/python: No module named pip
CalledProcessError: Command '['/home/andreas/.platformio/penv/.espidf-4.4.7/bin/python', '-m', 'pip', 'list', '--format=json', '--disable-pip-version-check']' returned non-zero exit status 1.:
  File "/home/andreas/venv/lib/python3.12/site-packages/platformio/builder/main.py", line 173:
    env.SConscript("$BUILD_SCRIPT")
  File "/home/andreas/.platformio/packages/tool-scons/scons-local-4.7.0/SCons/Script/SConscript.py", line 612:
    return _SConscript(self.fs, *files, **subst_kw)
  File "/home/andreas/.platformio/packages/tool-scons/scons-local-4.7.0/SCons/Script/SConscript.py", line 279:
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
  File "/home/andreas/.platformio/platforms/espressif32/builder/main.py", line 312:
    target_elf = env.BuildProgram()
  File "/home/andreas/.platformio/packages/tool-scons/scons-local-4.7.0/SCons/Util/envs.py", line 251:
    return self.method(*nargs, **kwargs)
  File "/home/andreas/venv/lib/python3.12/site-packages/platformio/builder/tools/piobuild.py", line 61:
    env.ProcessProgramDeps()
  File "/home/andreas/.platformio/packages/tool-scons/scons-local-4.7.0/SCons/Util/envs.py", line 251:
    return self.method(*nargs, **kwargs)
  File "/home/andreas/venv/lib/python3.12/site-packages/platformio/builder/tools/piobuild.py", line 121:
    env.BuildFrameworks(env.get("PIOFRAMEWORK"))
  File "/home/andreas/.platformio/packages/tool-scons/scons-local-4.7.0/SCons/Util/envs.py", line 251:
    return self.method(*nargs, **kwargs)
  File "/home/andreas/venv/lib/python3.12/site-packages/platformio/builder/tools/piobuild.py", line 347:
    SConscript(env.GetFrameworkScript(name), exports="env")
  File "/home/andreas/.platformio/packages/tool-scons/scons-local-4.7.0/SCons/Script/SConscript.py", line 676:
    return method(*args, **kw)
  File "/home/andreas/.platformio/packages/tool-scons/scons-local-4.7.0/SCons/Script/SConscript.py", line 612:
    return _SConscript(self.fs, *files, **subst_kw)
  File "/home/andreas/.platformio/packages/tool-scons/scons-local-4.7.0/SCons/Script/SConscript.py", line 279:
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
  File "/home/andreas/.platformio/platforms/espressif32/builder/frameworks/espidf.py", line 1233:
    install_python_deps()
  File "/home/andreas/.platformio/platforms/espressif32/builder/frameworks/espidf.py", line 1110:
    installed_packages = _get_installed_pip_packages(python_exe_path)
  File "/home/andreas/.platformio/platforms/espressif32/builder/frameworks/espidf.py", line 1078:
    pip_output = subprocess.check_output(
  File "/usr/lib/python3.12/subprocess.py", line 466:
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.12/subprocess.py", line 571:
    raise CalledProcessError(retcode, process.args,
========================== [FAILED] Took 1.67 seconds ==========================
========== [ERROR] ./venv/nspanel-wohnzimmer.yaml ==========

======================== [SUMMARY] ========================
  - ./venv/nspanel-wohnzimmer.yaml: FAILED

### Your Panel's YAML

```yaml
api:
  encryption:
    key: "xxxxxx"

substitutions:
  # Settings - Editable values
  device_name: nspanelwohnzimmer
  friendly_name: "NSPanel Wohnzimmer"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  nextion_update_url: "http://x.x.x.x:9000/local/nspanel_eu.tft"  # Optional
  # Add-on configuration (if needed)
  # heater_relay: "1"  # Possible values: "1" or "2"

# Customization area
##### My customization - Start #####
##### My customization - End #####

# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    refresh: 300s
    files:
      - nspanel_esphome.yaml # Basic package
      # Optional advanced and add-on configurations
      # - esphome/nspanel_esphome_advanced.yaml
      # - esphome/nspanel_esphome_addon_ble_tracker.yaml
      # - esphome/nspanel_esphome_addon_bluetooth_proxy.yaml
      # - esphome/nspanel_esphome_addon_climate_cool.yaml
      - esphome/nspanel_esphome_addon_climate_heat.yaml
      # - esphome/nspanel_esphome_addon_climate_dual.yaml
```
