### ISSUE TITLE
`Bug` Unable to Update NSPanel Due to Incorrect OTA Password

### ISSUE THREAD

**Issue by NdR91** [Blackymas/NSPanel_HA_Blueprint#2252]
### TFT Version

4.3.9

### Firmware Version

4.3.9

### Blueprint Version

4.3.9

### Panel Model

US (Landscape)

### What is the bug?

I am encountering an issue when trying to update my NSPanel using ESPHome. The update fails because it is trying to use an incorrect OTA password.

Probably my initial error was specifying the OTA Password in the yaml configuration.
I have 3 NSPanel up and running and i hope there is a fix to do via OTA instead flashing them again via serial...

### Your Panel's YAML

```yaml
Here is the relevant part of my nspanel-mansarda.yaml configuration:

substitutions:
  device_name: "nspanel-mansarda"
  friendly_name: "NSPanel Mansarda"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  nextion_update_url: "http://192.168.178.150:8123/local/nspanel_eu.tft"

# Customization area
api:
  encryption:
    key: "+51z/3ByrTOVpEEmRmM31V+bZHv00X99+ikAIxGN0zE="
ota:
  - platform: esphome
    password: "e7c79d6979f42992d1e1750c082e3913"
wifi:
  use_address: 192.168.178.94
web_server:
  port: 80
```

### ESPHome Logs

```
INFO ESPHome 2024.8.1
INFO Reading configuration /config/nspanel-mansarda.yaml...
INFO Updating https://github.com/Blackymas/NSPanel_HA_Blueprint@v4.3.9
INFO Detected timezone 'Etc/UTC'
Failed config

ota.esphome: [source /config/.esphome/packages/566b10a3/esphome/nspanel_esphome_core.yaml:129]
  
  Found multiple configurations but password is inconsistent.
  platform: esphome
  id: ota_std
  password: Ndr180891
  version: 2
  port: 3232
```

**Comment by NdR91** [comment]
SOLVED

I totally missed the doc section related to OTA Password:

```
# Use my global OTA password
ota:
  - id: !extend ota_std
    password: !secret ota_password
```

Thanks to this i solved my issue

**Comment by NdR91** [comment]
SOLVED

I totally missed the doc section related to OTA Password:

```
# Use my global OTA password
ota:
  - id: !extend ota_std
    password: !secret ota_password
```

Thanks to this i solved my issue
