### ISSUE TITLE
[Bug] Too many candidates found for `id` type `uart::UARTComponent` Some are `tf_uart`, `lin_uart_bus`.

### ISSUE THREAD

**Issue by edwardtfn** [Blackymas/NSPanel_HA_Blueprint#2265]
Hi Edward,

many thx that you have supported me 😊

I have only one question where i stuck.

When i put the following into the Customization area i get the error:
Too many candidates found for `id` type `uart::UARTComponent` Some are `tf_uart`, `lin_uart_bus`.

```yaml
# Customization area
##### My customization - Start #####
external_components:
  - source: github://Fabian-Schmidt/esphome-truma_inetbox
    components: ["truma_inetbox"]

uart:
  - id: lin_uart_bus
    tx_pin: 22
    rx_pin: 23
    baud_rate: 9600
    data_bits: 8
    parity: NONE
    stop_bits: 2

truma_inetbox:
  uart_id: lin_uart_bus

binary_sensor:
  - platform: truma_inetbox
    name: "CP Plus alive"
    type: CP_PLUS_CONNECTED

climate:
  - platform: truma_inetbox
    name: "Room"
    type: ROOM
#######################################################################################################################################
switch:
  - id: !extend relay_1
    platform: template
    pin: !remove
    optimistic: true
    #internal: true
##### My customization - End #####
```

Can you please assist what i have to do.

Best regards
Stefan

_Originally posted by @NetCom-Hymer in https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/2139#issuecomment-2325753303_
