### ISSUE TITLE
TFT Update nextion is not connected.

### ISSUE THREAD

**Issue by cremer42** [Blackymas/NSPanel_HA_Blueprint#2275]
### TFT Version

"unknown"

### Firmware Version

4.3.11

### Blueprint Version

4.3.11

### Panel Model

US

### What is the bug?

I recently updated my NSpanel, and all seems okay for the most part. I started with a "red HA" icon, but was able to correct that some how. I am still getting a couple of errors and cannot figure out what the issue is.

I am seeing:
nextion:081 Nextion is not connected!

then after a while, i see 
nextion:087 Nextion is connected

then the below starts.
nextion:416 Nextion reported variable name invalid

I have updated my update path from my local machine to the github address, I have changed framework, I have tried different baud rates. At this point I am not sure what else to do.

My display currently sort of works, my relay buttons still do what I had them programmed to do. But I had a fan button that doesnt 100% seem right. I even tried removing all entities from my blueprint, and still no luck.

Thank you,

### Your Panel's YAML

```yaml
substitutions:
  ###### CHANGE ME START ######
  device_name: "nspanelwhite" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

#  nextion_update_url: "http://192.168.50.33:8123/local/nspanelus.tft"
  nextion_blank_url: "http://192.168.50.33:8123/local/nspanelblank.tft"
  nextion_update_url: "https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/hmi/nspanel_us.tft"

##### My customization - Start #####

# Encrypt the communication between ESPHome and Home Assistant
api:

# More detailed log (for troubleshooting only)
logger:
  level: VERBOSE

##### My customization - End #####

  ##### addon-configuration #####
  ## addon_climate ##
  # addon_climate_heater_relay: "1" # possible values: 1/2

  ##### CHANGE ME END #####

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # - advanced/esphome/nspanel_esphome_advanced.yaml # activate advanced (legacy) elements - can be useful for troubleshooting
      # - nspanel_esphome_addon_climate_cool.yaml # activate for local climate (cooling) control
      # - nspanel_esphome_addon_climate_heat.yaml # activate for local climate (heater) control
    refresh: 300s

esp32:
  framework:
    type: arduino
    

##### My customization - Start #####
##### My customization - End #####
```

### ESPHome Logs

[logs_nspanelwhite_logs (2).txt](https://github.com/user-attachments/files/16980345/logs_nspanelwhite_logs.2.txt)
