### ISSUE TITLE
`Bug` Addging Bluetooth Code to ESP Home is giving errors 

### ISSUE THREAD

**Issue by rudgej** [Blackymas/NSPanel_HA_Blueprint#2285]
### Panel Model

None

### What is the bug?

I have added the bluetooth code but it gives compiler errors 

### Steps to Reproduce

Add the bluetooth code to the end of the esp home config 

INFO ESPHome 2024.9.0
INFO Reading configuration /config/esphome/musicroom.yaml...
ERROR Error while reading config: Invalid YAML syntax:

expected a single document in the stream
  in "/config/esphome/musicroom.yaml", line 1, column 1
but found another document
  in "/config/esphome/musicroom.yaml", line 48, column 1

### Your Panel's YAML

```yaml
substitutions:

###### CHANGE ME START ######

  device_name: "musicroom" 
  wifi_ssid: "Automation"
  wifi_password: "zzzzzz"

  #nextion_update_url: "http://homeassistant.local:8123/local/nspanel_eu.tft"  # Optional for `esp-idf` framework
  # Add-on configuration (if needed)
  # heater_relay: "1"  # Possible values: "1" or "2"

# Customization area
##### My customization - Start #####
##### My customization - End #####

# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # Optional advanced and add-on configurations
      # - advanced/esphome/nspanel_esphome_advanced.yaml
      # - nspanel_esphome_addon_climate_cool.yaml
      # - nspanel_esphome_addon_climate_heat.yaml
      # - nspanel_esphome_addon_climate_dual.yaml
    refresh: 300s

esp32:
  framework:
    type: esp-idf

    # Set Nextion comms baud rate to 921600 bps
uart:
  - id: !extend tf_uart
    baud_rate: 921600

#####################################################################################################
##### NSPANEL ESPHOME created by Blackymas - https://github.com/Blackymas/NSPanel_HA_Blueprint  #####
##### ESPHome Add-on for Bluetooth proxy                                                        #####
##### PLEASE only make changes if it is necessary and also the required knowledge is available. #####
##### For normal use with the Blueprint, no changes are necessary.                              #####
#####################################################################################################
##### ATTENTION: This will add climate elements to the core system and requires the core part.  #####
#####################################################################################################
---

esphome:
  platformio_options:
    build_flags:
      - -D NSPANEL_HA_BLUEPRINT_ADDON_BLUETOOTH_PROXY

bluetooth_proxy:
  id: ble_proxy

packages:
  ble_base_package: !include nspanel_esphome_addon_ble_tracker.yaml

script:
  - id: !extend dump_config
    then:
      - lambda: |-
          // Check if this is installed with Arduino
          #ifdef USE_ARDUINO
            #error "Invalid settings for add-on Bluetooth Proxy. Arduino framework is not supported when using Bluetooth in this project."
          #endif
          if (!id(is_uploading_tft)) {
            static const char *const TAG = "nspanel_ha_blueprint";
            ESP_LOGCONFIG(TAG, "Add-on Bluetooth Proxy:");
            ESP_LOGCONFIG(TAG, "  Mode:        %s", ble_proxy->has_active() ? "Active" : "Passive");
            ESP_LOGCONFIG(TAG, "  Connections: %i", int(ble_proxy->get_bluetooth_connections_limit() -
                                                        ble_proxy->get_bluetooth_connections_free()));
            ESP_LOGCONFIG(TAG, "  Limit:       %i", int(ble_proxy->get_bluetooth_connections_limit()));
          }

# Set Wi-Fi power save mode to "LIGHT" as required for Bluetooth on ESP32
wifi:
  power_save_mode: LIGHT
...
```

**Comment by edwardtfn** [comment]
I think you are overcomplicating your yaml, as most of those customizations are already part of the core package.

This should work and includes all of your customizations:
```yaml
substitutions:
  # Settings - Editable values
  device_name: "musicroom"
  friendly_name: "Music room panel"
  wifi_ssid: "Automation"
  wifi_password: "zzzzzz"
  # nextion_update_url: "http://homeassistant.local:8123/local/nspanel_eu.tft"  # Optional
  # Add-on configuration (if needed)
  # heater_relay: "1"  # Possible values: "1" or "2"

# Customization area
##### My customization - Start #####
##### My customization - End #####

# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    refresh: 300s
    files:
      - nspanel_esphome.yaml # Basic package
      # Optional advanced and add-on configurations
      # - esphome/nspanel_esphome_advanced.yaml
      # - esphome/nspanel_esphome_addon_ble_tracker.yaml
      - esphome/nspanel_esphome_addon_bluetooth_proxy.yaml
      # - esphome/nspanel_esphome_addon_climate_cool.yaml
      # - esphome/nspanel_esphome_addon_climate_heat.yaml
      # - esphome/nspanel_esphome_addon_climate_dual.yaml
      # - esphome/nspanel_esphome_addon_cover.yaml
```

Please give it a try and let me know the results.

For the UART baud rate, you can set under your panel's page (Settings > Devices & services > ESPHome), but if you have issues, then try returning your customization on that only.
By the way, is 921600bps working fine for you? I would expect some buffer overflow on more busy pages (which I'm working on with v4.4 in `dev`).

**Comment by edwardtfn** [comment]
Hey @rudgej, any success with my suggestions?

**Comment by rudgej** [comment]
Hi

Thank you. Yes to a degree! It now complies ok 

The next mystery is howdo i pair things to it and see those things in HA?

This is out of scope of your project but if you could give any pointers i would appreciate it.

If i add the bluetooth integration then t errors saying 1 uncifgured adepter found.

But I ant find how one configures said adapter!

**Comment by rudgej** [comment]
To add some context!

I am trying to add my robot lawnmower to HA ( which is course has nothing to do wuth this project other than trying to use the bluetooth on the device to make it work!

THis is their suggested code - which i have not added but used yours 

esphome:
  name: mower-ble

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

esp32_ble_tracker:
  scan_parameters:
    active: false
    continuous: false
    duration: 50sec

bluetooth_proxy:
  active: true
  cache_services: true

time:
  - platform: homeassistant
    on_time:
      - seconds: 0
        minutes: '*'
        then:
          esp32_ble_tracker.start_scan:
# create a button to reboot the esp32
button:
  - platform: restart
    name: "Mower ESP Restart"





This is the project 

https://github.com/andyb2000/HACS-husqvarna_automower_ble/issues

**Comment by edwardtfn** [comment]
I will breakdown your yaml, then we try to create the final yaml for your panel:

```yaml
esphome:
  name: mower-ble

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
```
This all is already part of the core package used by your panel, so you don't have to add this again.

```yaml
esp32_ble_tracker:
  scan_parameters:
    active: false
    continuous: false
    duration: 50sec

bluetooth_proxy:
  active: true
  cache_services: true
```
This is already part of the bluetooth proxy add-on, except by the non-standard `scan_parameters` settings, which I really don't think you need. But if you want to keep this customization, I believe it will work just like it is.

```yaml
time:
  - platform: homeassistant
    on_time:
      - seconds: 0
        minutes: '*'
        then:
          esp32_ble_tracker.start_scan:
```
This is forcing the scan every minute, probably to compensate the `continuous: false` from the `scan_parameters` custom settings above. Again, I don't think you need this, but if you want implement it anyways, it will be like this:
```yaml
time:
  - id: !extend time_provider
    on_time:
      - seconds: 0
        minutes: '*'
        then:
          esp32_ble_tracker.start_scan:
```

```yaml
# create a button to reboot the esp32
button:
  - platform: restart
    name: "Mower ESP Restart"
```
This will create a button to restart your panel, which is already part of the core package, so you don't need this.

In the end, I believe the settings I've sent earlier will work fine for your proxy.

**Comment by andreas-bulling** [comment]
@edwardtfn 

When uncommenting the BLE tracker or Bluetooth Proxy lines I see the following error message:

```
Compiling .pioenvs/panel-gf/src/main.cpp.o
/data/packages/566b10a3/esphome/nspanel_esphome_addon_ble_tracker.yaml:29:10: error: #error "Invalid settings for add-on BLE Tracker. Arduino framework is not supported when using Bluetooth in this project."
             #error "Invalid settings for add-on BLE Tracker. Arduino framework is not supported when using Bluetooth in this project."
          ^  ~~
/data/packages/566b10a3/esphome/nspanel_esphome_addon_bluetooth_proxy.yaml:28:10: error: #error "Invalid settings for add-on Bluetooth Proxy. Arduino framework is not supported when using Bluetooth in this project."
             #error "Invalid settings for add-on Bluetooth Proxy. Arduino framework is not supported when using Bluetooth in this project."
          ^  ~~
Building .pioenvs/panel-gf/bootloader.bin
Creating esp32 image...
Successfully created esp32 image.
```

**Comment by edwardtfn** [comment]
Please try adding this to your device's yaml:

```yaml
esp32:
  framework:
    type: esp-idf
```
