### ISSUE TITLE
`Bug` Media player volume buttons disapear

### ISSUE THREAD

**Issue by vukisz** [Blackymas/NSPanel_HA_Blueprint#2286]
### TFT Version

4.3.11

### Firmware Version

4.3.11

### Blueprint Version

4.3.11

### Panel Model

EU

### What is the bug?

When entering media page volume up/down buttons is displayed shortly and then hidden. Video: https://photos.app.goo.gl/DJP5r9dFjxWcXYK8A
Media control via HA SS:
![image](https://github.com/user-attachments/assets/a1e61577-ddb4-46b9-826e-415f5de4d2ac)

### Steps to Reproduce

1. Media which I want to control: CCWGTV (chromecast with google tv).
2. It is playing custom application for live TV (maybe that is the issue) But I can control volume via HA ?

### Your Panel's YAML

```yaml
substitutions:
  # Settings - Editable values
  name: nspanel-stand
  friendly_name: Nspanel Stand
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  nextion_update_url: "http://192.168.86.201:8123/local/nspanel_eu.tft"  # Optional


  # Add-on configuration (if needed)
  ## Add-on climate (https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/docs/addon_climate.md)
  heater_relay: "1"     # Possible values: "1" or "2"
  temp_units: "°C"      # Temperatures in Fahrenheit
  temp_min: "15"        # Min supported temperature is 15°C
  temp_max: "28"        # Max supported temperature is 28°C
  temp_step: "0.1"        # Temperature granularity is 0.1°C
  heat_deadband: "0.4"  # Temperature delta before engaging heat
  heat_overrun: "0.4"   # Temperature delta before disengaging heat


# Customization area
##### My customization - Start #####
# Enable Home Assistant API
api:
  encryption:
    key: !secret encryption_key_nspanel_stand

wifi:
  manual_ip:
    static_ip: 192.168.86.240
    gateway: 192.168.86.1
    subnet: 255.255.255.0

sensor:
  - id: ha_temperature
    platform: homeassistant
    entity_id: sensor.sonoff_snzb_02d_north_room_temperature   # Please change this by the entity_id of your temperature sensor in Home Assistant
  - id: combined_temperature
    platform: template
    lambda: |-
      if (wifi_component->is_connected() and api_server->is_connected())  // Testing both as WiFi is faster to detect issues
        return ha_temperature->state;
      else
        return temp_nspanel->state;


climate:
  - id: !extend thermostat_embedded
    sensor: combined_temperature
    visual:
      temperature_step: ${temp_step}
##### My customization - End #####

# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    refresh: 300s
    files:
      - nspanel_esphome.yaml # Basic package
      # Optional advanced and add-on configurations
      # - esphome/nspanel_esphome_advanced.yaml
      # - esphome/nspanel_esphome_addon_ble_tracker.yaml
      # - esphome/nspanel_esphome_addon_bluetooth_proxy.yaml
      # - esphome/nspanel_esphome_addon_climate_cool.yaml
      - esphome/nspanel_esphome_addon_climate_heat.yaml
      # - esphome/nspanel_esphome_addon_climate_dual.yaml
      # - esphome/nspanel_esphome_addon_cover.yaml
```

### ESPHome Logs

[16:28:40][W][component:238]: Components should block for at most 30 ms.
[16:28:41][D][text_sensor:064]: 'NSPanel local event': Sending state '{"page": "buttonpage03", "event": "long_click", "component": "button01"}'
[16:28:41][D][script:077]: Script 'timer_page' restarting (mode: restart)
[16:28:41][D][script:077]: Script 'timer_dim' restarting (mode: restart)
[16:28:41][D][script:077]: Script 'timer_sleep' restarting (mode: restart)
[16:28:41][D][nextion_textsensor:014]: Processed text_sensor "localevent" state "{"page": "buttonpage03", "event": "long_click", "component": "button01"}"
[16:28:41][D][text_sensor:064]: 'Detailed Entity': Sending state 'media_player.android_tv_remote_livingroom_chromecast'
[16:28:41][D][text_sensor:064]: 'Current Page': Sending state 'media_player'
[16:28:41][D][script.page_changed:2644]: New page: media_player
[16:28:41][D][script.page_changed:2669]: Entity shown: media_player.android_tv_remote_livingroom_chromecast
[16:28:41][D][script:077]: Script 'timer_page' restarting (mode: restart)
[16:28:41][D][script:077]: Script 'timer_dim' restarting (mode: restart)
[16:28:41][D][script:077]: Script 'timer_sleep' restarting (mode: restart)
[16:28:41][D][nextion_textsensor:014]: Processed text_sensor "current_page" state "media_player"
[16:28:41][D][text_sensor:064]: 'Detailed Entity': Sending state 'media_player.android_tv_remote_livingroom_chromecast'
[16:28:43][D][sensor:094]: 'ntc_source': Sending state 1.51567 V with 2 decimals of accuracy
[16:28:43][D][resistance:039]: 'resistance_sensor' - Resistance 9513.6Ω
[16:28:43][D][sensor:094]: 'resistance_sensor': Sending state 9513.61816 Ω with 1 decimals of accuracy
[16:28:43][D][ntc:026]: 'Temperature' - Temperature: 26.1°C
[16:28:43][D][sensor:094]: 'Temperature': Sending state 26.12634 °C with 1 decimals of accuracy
