### ISSUE TITLE
RTTTL not playing to multiple NSPANELS

### ISSUE THREAD

**Issue by Gertc555** [Blackymas/NSPanel_HA_Blueprint#2288]
### TFT Version

4.3.11

### Firmware Version

4.3.11

### Blueprint Version

4.3.11

### Panel Model

US

### What is the bug?

When sending rtttl tone to multiple panels only the last 2 plays the tones. It worked fine about 5 months ago. 

### Your Panel's YAML

```yaml
alias: Washing Done
description: ""
trigger:
  - type: power
    platform: device
    device_id: 350078ecaab34dd75c70299ae05f27c0
    entity_id: 093afe6973a76d3bfaf6ef7f435a8f8a
    domain: sensor
    below: 1.5
condition: []
action:
  - action: esphome.nspanel_toilet_guest_notification_show
    data:
      label: Washing machine
      message: Washing Done
  - action: esphome.nspanel_toilet_guest_rtttl_play
    data:
      tone: >-
        PinkPanther:d=4,o=5,b=160:8d#,8e,2p,8f#,8g,2p,8d#,8e,16p,8f#,8g,16p,8c6,8b,16p,8d#,8e,16p,8b,2a#,2p,16a,16g,16e,16d,2e
  - action: esphome.nspanel_toilet_master_bedroom_notification_show
    data:
      label: Washing machine
      message: Washing Done
  - action: esphome.nspanel_toilet_master_bedroom_rtttl_play
    data:
      tone: >-
        PinkPanther:d=4,o=5,b=160:8d#,8e,2p,8f#,8g,2p,8d#,8e,16p,8f#,8g,16p,8c6,8b,16p,8d#,8e,16p,8b,2a#,2p,16a,16g,16e,16d,2e
  - action: esphome.nspanel_melissa_room_notification_show
    data:
      label: Washing machine
      message: Washing Done
  - action: esphome.nspanel_melissa_room_rtttl_play
    data:
      tone: >-
        PinkPanther:d=4,o=5,b=160:8d#,8e,2p,8f#,8g,2p,8d#,8e,16p,8f#,8g,16p,8c6,8b,16p,8d#,8e,16p,8b,2a#,2p,16a,16g,16e,16d,2e
  - action: esphome.nspanel_bedroom_4_notification_show
    data:
      label: Washing machine
      message: Washing Done
  - action: esphome.nspanel_bedroom_4_rtttl_play
    data:
      tone: >-
        PinkPanther:d=4,o=5,b=160:8d#,8e,2p,8f#,8g,2p,8d#,8e,16p,8f#,8g,16p,8c6,8b,16p,8d#,8e,16p,8b,2a#,2p,16a,16g,16e,16d,2e
  - action: esphome.nspanel_moses_room_notification_show
    data:
      label: Washing machine
      message: Washing Done
  - action: esphome.nspanel_moses_room_rtttl_play
    data:
      tone: >-
        PinkPanther:d=4,o=5,b=160:8d#,8e,2p,8f#,8g,2p,8d#,8e,16p,8f#,8g,16p,8c6,8b,16p,8d#,8e,16p,8b,2a#,2p,16a,16g,16e,16d,2e
  - action: esphome.nspanel_master_bedroom_notification_show
    data:
      label: Washing machine
      message: Washing Done
  - action: esphome.nspanel_master_bedroom_rtttl_play
    data:
      tone: >-
        PinkPanther:d=4,o=5,b=160:8d#,8e,2p,8f#,8g,2p,8d#,8e,16p,8f#,8g,16p,8c6,8b,16p,8d#,8e,16p,8b,2a#,2p,16a,16g,16e,16d,2e
  - action: esphome.nspanel_living_room_notification_show
    data:
      label: Washing machine
      message: Washing Done
  - action: esphome.nspanel_living_room_rtttl_play
    data:
      tone: >-
        PinkPanther:d=4,o=5,b=160:8d#,8e,2p,8f#,8g,2p,8d#,8e,16p,8f#,8g,16p,8c6,8b,16p,8d#,8e,16p,8b,2a#,2p,16a,16g,16e,16d,2e
mode: single
```
