### ISSUE TITLE
`Bug`  Another translation issue for Alarmo panel

### ISSUE THREAD

**Issue by Opontios** [Blackymas/NSPanel_HA_Blueprint#2296]
### TFT Version

4.3.11

### Firmware Version

4.3.11

### Blueprint Version

4.3.11

### Panel Model

EU

### What is the bug?

Hi. I already so reports for the Disarm button for other languages. The "Разоржени" for the Russian language is irrelevant and very wrong. Could it be fixed? Also the other states are not well translated. Could I propose the optimal translations so it could be fixed?

**Comment by edwardtfn** [comment]
Please help with the right strings.

This is what is in use right now:
```yaml
        ru:     # Russian
          bytes_per_char: 2
          weekdays:
            mon: Понедельник
            tue: Вторник
            wed: Среда
            thu: Четверг
            fri: Пятница
            sat: Суббота
            sun: Воскресенье
          weekdays_short:
            mon: Пн
            tue: Вт
            wed: Ср
            thu: Чт
            fri: Пт
            sat: Сб
            sun: Вс
          months:
            jan: Январь
            feb: Февраль
            mar: Март
            apr: Апрель
            may: Май
            jun: Июнь
            jul: Июль
            aug: Август
            sep: Сентябрь
            oct: Октябрь
            nov: Ноябрь
            dec: Декабрь
          months_short:
            jan: Янв
            feb: Фев
            mar: Мар
            apr: Апр
            may: Май
            jun: Июн
            jul: Июл
            aug: Авг
            sep: Сен
            oct: Окт
            nov: Ноя
            dec: Дек
          relative_day:
            today: Сегодня
            tomorrow: Завтра
            in_2_days: Через 2 дня
            in_3_days: Через 3 дня
            in_4_days: Через 4 дня
          climate:
            states:
              "on": Включено
              "off": Выключено
            heat: Отопление
          please_confirm: Пожалуйста, подтвердите
          unavailable: Недоступно
          unknown: Неизвестно
          no_name: Без названия
          alarm:
            home: Дома
            away: Вне дома
            night: Ночь
            vacation: Отпуск
            bypass: Обход
            disarm: Разоружение
          settings:
            reboot: Перезагрузка
            sleep: Сон
            brightness: Яркость
            bright: Яркий
            dimming: Затемнение
            dim: Тусклый
          meridiem:
            am: ДП
            pm: ПП
```

**Comment by Opontios** [comment]
Sorry, didn't have time to answer. I suggest to follow the HA native translation.

```
        ru:     # Russian
          bytes_per_char: 2
          weekdays:
            mon: Понедельник
            tue: Вторник
            wed: Среда
            thu: Четверг
            fri: Пятница
            sat: Суббота
            sun: Воскресенье
          weekdays_short:
            mon: Пн
            tue: Вт
            wed: Ср
            thu: Чт
            fri: Пт
            sat: Сб
            sun: Вс
          months:
            jan: Январь
            feb: Февраль
            mar: Март
            apr: Апрель
            may: Май
            jun: Июнь
            jul: Июль
            aug: Август
            sep: Сентябрь
            oct: Октябрь
            nov: Ноябрь
            dec: Декабрь
          months_short:
            jan: Янв
            feb: Фев
            mar: Мар
            apr: Апр
            may: Май
            jun: Июн
            jul: Июл
            aug: Авг
            sep: Сен
            oct: Окт
            nov: Ноя
            dec: Дек
          relative_day:
            today: Сегодня
            tomorrow: Завтра
            in_2_days: Через 2 дня
            in_3_days: Через 3 дня
            in_4_days: Через 4 дня
          climate:
            states:
              "on": Включено
              "off": Выключено
            heat: Отопление
          please_confirm: Пожалуйста подтвердите
          unavailable: Недоступно
          unknown: Неизвестно
          no_name: Без названия
          alarm:
            home: Охрана (Дома)
            away: Охрана (Не дома)
            night: Охрана (Ночь)
            vacation: Охрана (Отпуск)
            bypass: Охрана (С исключениями)
            disarm: Без охраны
          settings:
            reboot: Перезагрузка
            sleep: Сон
            brightness: Яркость
            bright: Яркий
            dimming: Затемнение
            dim: Тусклый
          meridiem:
            am: ДП
            pm: ПП
```
Although I don't know if it will fit everywhere.
