### ISSUE TITLE
`Bug` Panel became very slow and warm

### ISSUE THREAD

**Issue by hapklaar** [Blackymas/NSPanel_HA_Blueprint#2299]
### TFT Version

4.3.11 (from boot screen)

### Firmware Version

2024.9.1

### Blueprint Version

4.3.11 (from blueprint screen)

### Panel Model

EU

### What is the bug?

I'm not sure if this is a bug, problem with my panel or configuration. 

Just started using the panel actively again after months now we need to control the heater and notice the panel is incredibly slow and hot to the touch. Also button and climate screens stay empty or are only populated with data after a while or after many tries. Sometimes it just completely freezes and needs a power cycle to respond again. It seems like its CPU is constantly pegged or something.

I have rebooted, reinstalled ESPHome, TFT firmware and blueprint a couple of times to no avail. Nothing in the logs seems out of the ordinary, the device just performs very badly. I'm not sure when this started as I haven't touched it during the summer and some updates have been performed without me testing afterwards.

Please let me know what else I can do to debug this and provide you with more relevant info.

### Your Panel's YAML

```yaml
ESPHome:

substitutions:
  device_name: nspanel
  wifi_ssid: -snip-
  wifi_password: -snip-
  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft"
  #nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/beta/nspanel_eu.tft"
  #nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/dev/nspanel_eu.tft"
  #nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/dev/custom_configuration/nspanel_blank.tft"

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

BLUEPRINT:
alias: NSPanel
description: ""
use_blueprint:
  path: Blackymas/nspanel_blueprint.yaml
  input:
    nspanel_name: 5c2034aa559ebf47db7079fb003d26f0
    language: nl
    delay: 10
    weather_entity: weather.home
    qrcode_enabled: false
    climate: climate.huiskamer_2
    home_value01: sensor.dds238_2_solar_power
    home_value01_icon: mdi:solar-power-variant
    home_value01_label_color:
      - 7
      - 237
      - 7
    home_value02_icon_color:
      - 255
      - 0
      - 0
    home_value02_icon: mdi:lightning-bolt-circle
    home_value01_icon_color:
      - 251
      - 255
      - 0
    chip01_icon: mdi:lock-alert
    indoortemp: sensor.huiskamer_temperature_2
    time_format: "%-H:%M"
    chip01: >-
      binary_sensor.z_wave_controlled_door_lock_with_bluetooth_smart_the_current_status_of_the_door
    climate_button08_icon: ""
    climate_button09_icon: ""
    home_outdoor_temp_label_color:
      - 0
      - 219
      - 235
    chip01_icon_color:
      - 255
      - 247
      - 0
    home_value02: sensor.dsmr_total_sl
    left_button_entity: switch.mac_2
    left_button_hold_select: Default
    entity01_name: Lr lights
    entity02_name: Sony AMP
    entity02_icon: ""
    entity01_icon: mdi:lightbulb-group
    entity03_icon: ""
    entity01_icon_color:
      - 250
      - 0
      - 0
    entity02_icon_color:
      - 250
      - 0
      - 0
    entity03_icon_color:
      - 250
      - 121
      - 0
    right_button_entity: light.yee_group
    left_button_name: Printer Isle
    right_button_name: Lr lights
    date_format: "%A %-d-%-m"
    home_custom_button01: climate.keuken
    home_custom_button02: climate.hal
    home_custom_button01_icon: mdi:countertop
    home_custom_button02_icon: mdi:door-closed
    home_custom_button03: climate.slaapkamer
    home_custom_button03_icon: mdi:bed
    home_value02_label_color:
      - 255
      - 255
      - 255
    home_value03: sensor.atmospheric_pressure
    climate_value01: sensor.huiskamer_heating_2
    chip02: binary_sensor.slave_flame_on_boiler_otgw
    chip02_icon: mdi:fire
    chip02_icon_color:
      - 226
      - 111
      - 3
    chip03: binary_sensor.slave_flame_on_thermostat_otgw
    chip03_icon: mdi:fire-circle
    entitypages_enabled: true
    entities_entity01: sensor.huiskamer_heating_2
    entities_entity02: sensor.energy_market_price_current_hour_incl
    entities_entity02_icon: mdi:meter-electric
    entities_entity03: sensor.gas_market_price_current_hour_incl
    entity01: light.yee_group
    button_page01_label: Button Page 1
    entity02: switch.audioset
    climate_value01_icon: mdi:sofa-outline
    climate_value01_icon_color:
      - 255
      - 123
      - 0
    climate_value01_label_color:
      - 200
      - 204
      - 200
    climate_button08_icon_color:
      - 250
      - 121
      - 0
    entity03: light.desk_heater_dimmer_light
    entity03_name: Desk heater
    home_indoor_temp_icon: mdi:home-thermometer
    home_indoor_temp_icon_color:
      - 254
      - 214
      - 144
    chip_font_size: "7"
    outdoortemp: sensor.atc_9c3e_temperature
    entity04: light.desk_heater_dimmer_light
    entity04_name: Desk heater 2
    home_outdoor_temp_font: "5"
    climate_value02: sensor.keuken_heating
    climate_value02_icon: mdi:countertop-outline
    climate_value03: sensor.hal_heating
    climate_value03_icon: mdi:coat-rack
    climate_value04: sensor.slaapkamer_heating
    climate_value04_icon: mdi:bed-king-outline
    climate_value02_icon_color:
      - 255
      - 123
      - 0
    climate_value03_icon_color:
      - 255
      - 123
      - 0
    right_button_hold_select: Default
    timezone: Europe/Amsterdam (CET-1CEST,M3.5.0,M10.5.0/3)
    decimal_separator: ","
```

### ESPHome Logs

Don't think this is relevant. No issues can be seen in these logs.
