### ISSUE TITLE
`Bug` changine wifi details OTA

### ISSUE THREAD

**Issue by geekyclarkey** [Blackymas/NSPanel_HA_Blueprint#2302]
### Panel Model

EU

### What is the bug?

Hi, you have set the ota password the same as the wifi passsword. So now i have changed my wifi, i cant input the new details and do an update OTA. As the new wifi password is different. it says mentions authentication issue when trying to upload it.
can you either not use an ota password or add it into the substitutions so we can decide what its going to be?

The only way around this at the minute is to tft flash all my panels again. but OTA would be far easier.

### Your Panel's YAML

```yaml
substitutions:
  ###### CHANGE ME START ######
  device_name: "theospanel" 
  wifi_ssid: "hallwifi"
  wifi_password: "1234554321"
  ota_password: "whjbw78238edsjnx98whdaa"

  nextion_update_url: "http://192.168.100.229:8123/local/nspanel_eu.tft"

  ##### addon-configuration #####
  ## addon_climate ##
  # addon_climate_heater_relay: "1" # possible values: 1/2

  ##### CHANGE ME END #####

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # - nspanel_esphome_advanced.yaml # activate advanced (legacy) elements - can be useful for troubleshooting
      # - nspanel_esphome_addon_climate_cool.yaml # activate for local climate (cooling) control
      # - nspanel_esphome_addon_climate_heat.yaml # activate for local climate (heater) control
    refresh: 300s

##### My customization - Start #####
##### My customization - End #####
```
