### ISSUE TITLE
`Bug`  can t compile firmware bin file

### ISSUE THREAD

**Issue by mdmstudio571** [Blackymas/NSPanel_HA_Blueprint#2320]
### Panel Model

EU

### What is the bug?

during compile I have error:
Microsoft Windows [Version 6.1.7601]
F:\>esphome compile nsp.yaml
←[32mINFO Reading configuration nsp.yaml...←[0m
←[32mINFO Updating https://github.com/Blackymas/NSPanel_HA_Blueprint@main←[0m
Failed config

packages: [source nsp.yaml:20]

  nspanel_esphome.yaml is not a valid YAML file. Please check the file contents.

  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml
    refresh: 300s

### Your Panel's YAML

```yaml
substitutions:
  # Settings - Editable values
  device_name: "nspanel"
  friendly_name: "nspanel"
  wifi_ssid: ""
  wifi_password: ""
  nextion_update_url: "http://homeassistant.local:8123/local/nspanel_eu.tft"  # Optional
  # Add-on configuration (if needed)
  # heater_relay: "1"  # Possible values: "1" or "2"

# Customization area
##### My customization - Start #####
##### My customization - End #####

# Core and optional configurations
##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####
```
