### ISSUE TITLE
`Enhancement` Add gain property to RTTTL player.

### ISSUE THREAD

**Issue by distante** [Blackymas/NSPanel_HA_Blueprint#2334]
### Enhancement Summary

Allow to set custom gains to RTTTL play action calls.

### Detailed Description

The [RTTTL ESPHome component](https://esphome.io/components/rtttl.html) has a gain parameter that is not used by the RTTTL play action. I would like to have a possibility to set it.

### Additional Context

I want to play some notifications at lower volume at nights since they can sound really loud when everything is quiet.

**Comment by edwardtfn** [comment]
Do you wanna to set the gain based on time or to specify gain per action call?

**Comment by distante** [comment]
I think per action call would be more helpful in my use case. 

That said, I do not know if community wise a global gain would be more useful?

**Comment by Mauricewillemstein** [comment]
Maybe better to make it time based. So at night you can turn the volume down.

**Comment by edwardtfn** [comment]
Could you please try adding this to your panel's yaml and then use the newly created action to try if gain change works per call?

```yaml
api:
  services:
    - service: rtttl_play_with_gain
      variables:
        tone: string  # The RTTTL string for the melody to be played. It should follow the RTTTL format, including the melody's name, default settings, and a sequence of notes.
        gain: float
      then:
        - rtttl.stop
        - lambda: |-
            buzzer->set_gain(gain);
        - rtttl.play: !lambda return tone;
```

**Comment by Mauricewillemstein** [comment]
Compiling........

**Comment by distante** [comment]
I am at work right now but did you reloaded the ESPHome entity on Home Assistant @Mauricewillemstein ?

**Comment by edwardtfn** [comment]
You should have an additional action, this one allowing you to select the gain an the tone to play:
![image](https://github.com/user-attachments/assets/6b64180c-e277-4d00-9535-0697d3241fda)
![image](https://github.com/user-attachments/assets/a37b9001-239e-4098-88a9-24e6dbc39124)

**Comment by Mauricewillemstein** [comment]
found it, but nothing i type in here results in a tone or change volume
![Clipboard01](https://github.com/user-attachments/assets/3536b8db-bd7a-41fb-b67c-eaba7d1afd2d)

**Comment by edwardtfn** [comment]
I'm pretty sure the rtttl standard requires a name for the tone....something like this

`scale_up:d=32,o=5,b=100:c,c#,d#,e,f#,g#,a#,b`

**Comment by Mauricewillemstein** [comment]
You where right. there is sound now. anything below 1 works, but there is no difference in the volume. from 1 and above there is only some clicking sound.

![Clipboard01](https://github.com/user-attachments/assets/e22c0024-a428-44a8-8f17-490dde8f16de)

**Comment by distante** [comment]
@Mauricewillemstein i think it is a normalized percent value, so 1=100% 0.5=50% and so on.

**Comment by Mauricewillemstein** [comment]
@distante tried everything from 0 to 1 with increments of 0.1.
the volume is the same

**Comment by edwardtfn** [comment]
So, please try something different...

Add this to your panel's yaml, flash it again and please let me know if it makes any difference.

```yaml
rtttl:
  - id: !extend buzzer
    gain: 0.25
```

**Comment by Mauricewillemstein** [comment]
got this error, also if i do clean build files:

Failed config

rtttl: [source /config/esphome/zolder.yaml:45]
  - 
    Source for extension of ID 'buzzer' was not found.
    id: !extend buzzer
    gain: 0.25

**Comment by edwardtfn** [comment]
For reference (as I will use it for some tests later):

- esphome/esphome#5968

**Comment by edwardtfn** [comment]
Gain will always be between 0.1 and 1.0. If you set it outside this range it will be adjusted to fit:
https://esphome.io/api/rtttl_8h_source#l00042

**Comment by edwardtfn** [comment]
Please remove the previous code and try this in your panel's yaml:

```yaml
esphome:
  on_boot:
    - priority: -100.44
      then:
        - wait_until:
            condition:
              # - lambda: return not isnan(buzzer->get_gain());
              - lambda: return not isnan(buzzer_gain->state);
        - lambda: |-
            buzzer->set_gain((100-(buzzer_gain->state/10.0f))/100.0f);

number:
  - id: buzzer_gain
    name: Buzzer gain
    platform: template
    max_value: 100
    min_value: 0
    step: 1
    unit_of_measurement: "%"
    entity_category: config
    device_class: sound_pressure
    # icon: mdi:tune-vertical-variant
    restore_value: true
    optimistic: true
    set_action: 
      then:
        - lambda: |-
            buzzer->set_gain((100-(x/10.0f))/100.0f);
            if (x > 0)
              buzzer->play("scale_up:d=32,o=5,b=100:c,c#,d#,e,f#,g#,a#,b");
            buzzer->dump_config();
```

This will create a gain slider in your panel's page under Settings > Devices & services > ESPHome.

**Comment by Mauricewillemstein** [comment]
This works great. also super to include a sound so you can hear it when changing

![Clipboard01](https://github.com/user-attachments/assets/4731b4c8-fc3b-4e4e-998b-e4f66f9a24ff)

**Comment by edwardtfn** [comment]
Nice!
Just to register my discoveries here:
- The effective range at least for the buzzer used in the NSPanel is from 0.9 to 1.0 (or 90% to 100%). Bellow this range, the differences are not audible (at least for me).
- The range is inverted, which means 1.0 is almost impossible to hear, while 0.9 is at maximum.
- I've created a slider to compensate these things, so 0% will be muted and 100% will be max volume. This is changing between 0.9 (100%) to 1.0 (0%).

**Comment by distante** [comment]
Hi, I also had the time to test it and setting the volume there works. 

I have the feeling the "attenuation" values are not really linear but logarithmic. Probably normalized decibels? something like `dB = 20 * log10(val);` ?

**Comment by edwardtfn** [comment]
Yeah, I believe so.

**Comment by Andrecall** [comment]
> Yeah, I believe so.

Hi! Just came here to said a huge thank you! I've messed around it and couldn't get it work on my own. Will add your code to my config now and would appreciate this functionality added to the new release

**Comment by edwardtfn** [comment]
I will play with it a bit more, but it should be part of the next release.

**Comment by distante** [comment]
@edwardtfn will the release contain a global gain or an per RTTTL call gain? (or both 😬 )

**Comment by distante** [comment]
I can test it when I get the chance.

About the breaking change, will an optional extra gain parameter that is checked in the lambda would  take too much memory?

**Comment by edwardtfn** [comment]
Unfortunately ESPHome services can't handle optional parameters. All the parameters are always mandatory, as far as I know.
An additional service don't take that much memory, but as I'm currently fighting for each bit, I'd like to avoid it and instead use as a customization.

Anyhow, please try this:
```yaml

api:
  services:
    - service: rtttl_play_with_gain
      variables:
        tone: string  # The RTTTL string for the melody to be played. It should follow the RTTTL format, including the melody's name, default settings, and a sequence of notes.
        gain: int
      then:
        - rtttl.stop
        - lambda: |-
            buzzer->set_gain((100-(gain/10.0f))/100.0f);
        - rtttl.play: !lambda return tone;
        - wait_until:
            condition:
              - not:
                  - rtttl.is_playing
        - lambda: |-
            buzzer->set_gain((100-(buzzer_gain->state/10.0f))/100.0f);

esphome:
  on_boot:
    - priority: -100.44
      then:
        - wait_until:
            condition:
              # - lambda: return not isnan(buzzer->get_gain());
              - lambda: return not isnan(buzzer_gain->state);
        - lambda: |-
            buzzer->set_gain((100-(buzzer_gain->state/10.0f))/100.0f);

number:
  - id: buzzer_gain
    name: Buzzer gain
    platform: template
    max_value: 100
    min_value: 0
    step: 1
    unit_of_measurement: "%"
    entity_category: config
    device_class: sound_pressure
    # icon: mdi:tune-vertical-variant
    restore_value: true
    optimistic: true
    set_action: 
      then:
        - lambda: |-
            buzzer->set_gain((100-(x/10.0f))/100.0f);
            if (x > 0)
              buzzer->play("scale_up:d=32,o=5,b=100:c,c#,d#,e,f#,g#,a#,b");
            buzzer->dump_config();
```
