### ISSUE TITLE
`Bug` keine Anzeige Starbildschirm accuweather

### ISSUE THREAD

**Issue by minimag450** [Blackymas/NSPanel_HA_Blueprint#2348]
### TFT Version

4.3.11

### Firmware Version

4.3.11

### Blueprint Version

4.3.11

### Panel Model

EU

### What is the bug?

In my case, no temperature is displayed under the weather symbol, for example sun. If I tap on the sun symbol, I get to the pages with the forecast, which works. If I end the preview to get to the start page, the temperature of the panel sensor is briefly displayed under the sun.
Thank you for your help.

### Your Panel's YAML

```yaml
alias: NSPanel Configuration
description: ""
use_blueprint:
  path: Blackymas/nspanel_blueprint.yaml
  input:
    language: de
    nspanel_name: 27e1cbe6bd9c5f2dba1fa5bc32a85b8e
    date_format: "%A %-d.%-m"
    outdoortemp: sensor.gw1100a_outdoor_temperature
    wake_up_sensors:
      - binary_sensor.hue_motion_sensor_1_bewegung
    home_indoor_temp_visible: false
    chip01_icon: ""
    home_value01_icon: mdi:water-percent
    home_value02_icon: ""
    home_indoor_temp_icon: ""
    home_outdoor_temp_label_color:
      - 186
      - 135
      - 135
    home_outdoor_temp_font: "4"
    entity01: cover.wz1
    entity02: cover.wz2
    entity03: cover.wz3
    entity04: cover.wz_oliver
    sun_entity: sun.sun
    timezone: Europe/Berlin (CET-1CEST,M3.5.0,M10.5.0/3)
    decimal_separator: ","
    home_value01: sensor.gw1100a_humidity
```
