### ISSUE TITLE
Error: "Authentification invalid. Is the password correct?"

### ISSUE THREAD

**Issue by CristianN87** [Blackymas/NSPanel_HA_Blueprint#2354]
### Panel Model

None

### What is the bug?

When I try to install this yaml configuration on my NSpanel, which was used in the past with an cust configuration like an thermostat, I strugle with this issue regarding the "Authentification invalid". What can I do more or what I am not doing correct?

### Your Panel's YAML

```yaml
substitutions:
  # Settings - Editable values
  device_name: "termostat-living"
  friendly_name: "Termostat Living"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  # Optional
  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/v4.2.5/nspanel_eu.tft"
  # Add-on configuration (if needed)
  # heater_relay: "1"  # Possible values: "1" or "2"

# Customization area
##### My customization - Start #####


    ##### My customization - End #####

# Core and optional configurations
# we try dev instead of main due to commits for the tft uplaod problem
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    refresh: 300s
    files:
      - nspanel_esphome.yaml # Basic package
      # Optional advanced and add-on configurations
      # - esphome/nspanel_esphome_advanced.yaml
      # - esphome/nspanel_esphome_addon_ble_tracker.yaml
      # - esphome/nspanel_esphome_addon_bluetooth_proxy.yaml
      # - esphome/nspanel_esphome_addon_climate_cool.yaml
      # - esphome/nspanel_esphome_addon_climate_heat.yaml
      # - esphome/nspanel_esphome_addon_climate_dual.yaml
      # - esphome/nspanel_esphome_addon_cover.yaml
```

**Comment by edwardtfn** [comment]
Do you still know the previous ota password used on this device, if any?

Please try adding this as a customization to your panel's Yaml:
```yaml
ota:
  - id: !extend ota_std
    password: !remove
```

**Comment by edwardtfn** [comment]
> Hello @edwardtfn , thank you for your very fast answer.

🙂

> Yes, I have one file saved on my PC with the old YAML configuration.

Good!
So please try this:
```yaml
ota:
  - id: !extend ota_std
    password: <<your-old-ota-password>>
```


> ota:
> 
> * id: !extend ota_std
>   password: !remove
>   This will remove the old password, or what will do?

This will try to install without using any password.
