### ISSUE TITLE
`Bug` "Home page - Entity State 04 - Entity (Optional)" entity appears on a very odd position

### ISSUE THREAD

**Issue by darth-hp** [Blackymas/NSPanel_HA_Blueprint#2406]
### TFT Version

4.3.12

### Firmware Version

2024.11.1

### Blueprint Version

4.3.12

### Panel Model

EU

### What is the bug?

The "Home page - Entity State 04 - Entity (Optional)" entity appears on a very odd position
![esppanel](https://github.com/user-attachments/assets/61730079-13ab-40b0-a3bc-dcbd8d3cb3a4)

### Steps to Reproduce

And a "Home page - Entity State 04 - Entity (Optional)" and check where it appears

### Your Panel's YAML

```yaml
alias: Config esp02nspanel
description: ""
use_blueprint:
  path: Blackymas/nspanel_blueprint.yaml
  input:
    nspanel_name: e649dad95307dcee6e5a69c7576d3217
    language: de
    left_button_entity: light.esszimmerlicht
    left_button_name: Esslicht
    right_button_entity: light.wohnzimmerlicht
    right_button_name: Wohnzimmer
    entity01: light.alle_lichter
    entity01_name: Lichter
    entity02: light.esszimmerlicht
    entity02_name: Esszimmer
    entity03: light.wohnzimmerlicht
    entity03_name: Wohnzimmer
    delay: 10
    outdoortemp: sensor.ws_aussentemperatur
    weather_entity: weather.haus
    button_page01_label: Licht
    button_page02_label: Rollos
    entity10_name: Rollo Links
    entity09_name: Alle Rollos
    entity09: cover.alle_rollos
    entity11: cover.voice_terrasse_rollo_links
    entity11_name: Rollo Rechts
    entity10: cover.voice_terrasse_rollo_rechts
    sync_value_ha: select_yes
    sync_slider_ha: select_yes
    relay_1_local_fallback: false
    qrcode_state: false
    entity04: light.wohnleuchte_licht
    entity04_name: Wohnleuchte
    entity05: light.schlafleuchten
    entity05_name: DGLeuchten
    entity06: light.schlafzimmerlicht
    entity06_name: DGLicht
    time_format: "%H:%M"
    show_while_loading: true
    chip01_icon: ""
    chip02_icon: ""
    indoortemp: sensor.voice_thermometer_wohnzimmer_temperature
    entity01_icon: mdi:lightbulb-group
    entity07: light.wohnzimmer_beleuchtung_licht
    entity07_name: Whz-Spots
    entity07_icon: mdi:led-strip-variant
    entity08: light.duschlicht
    entity08_name: Duschlicht
    entity12: cover.nelerollo_abdeckung
    entity12_name: Rollo Nele
    entity12_icon: ""
    entity13: cover.felixrollo_abdeckung
    entity13_name: Rollo Felix
    entity14: cover.nelerollo_abdeckung
    entity14_name: Rollo Nele
    entity15: cover.kuchenrollo_abdeckung
    entity15_name: Rollo Küche
    home_value01: sensor.huawei_luna2000_state_of_capacity
    home_value01_icon: mdi:battery
    home_value02: sensor.huawei_sun2000_8ktl_m1_input_power
    home_value02_icon: mdi:solar-power
    timezone: Europe/Berlin (CET-1CEST,M3.5.0,M10.5.0/3)
    decimal_separator: ","
    home_custom_button01_icon: ""
    home_custom_button02_icon: ""
    relay01_icon: ""
    relay02_icon: ""
    hw_buttons_bars_pages:
      - "2"
      - "61440"
      - "3932160"
      - "512"
      - "256"
      - "134217728"
      - "124"
      - "2048"
      - "1024"
      - "33554432"
      - "67108864"
      - "16777216"
    home_button06_icon: ""
    home_button04_icon: ""
    wake_up_sensors: []
    screensaver_display_time: true
    home_value03: sensor.datum_vfb_spiel
    home_value03_icon: mdi:soccer
    home_value03_label_color:
      - 200
      - 204
      - 200
    home_value04_icon: mdi:account-group
    qrcode_label: Gast WLAN
    qrcode_value: WIFI:S:foo;T:WPA;P:bar;H:false;
    qrcode_enabled: true
    home_outdoor_temp_font: "4"
    home_value04: sensor.vfb_gegner
```
