### ISSUE TITLE
`Bug` No NSPanel device's to select

### ISSUE THREAD

**Issue by micky2171** [Blackymas/NSPanel_HA_Blueprint#2416]
### TFT Version

4.3.12

### Firmware Version

4.3.12

### Blueprint Version

4.3.12

### Panel Model

EU

### What is the bug?

The blueprint takes a good minute to load, but once loaded there is no NSPanel Device dropdown.
![image](https://github.com/user-attachments/assets/cc56f7d0-e299-4f33-b2b7-5ab48d95802e)

Device is online in ESPHome and connected to Home Assistant
![image](https://github.com/user-attachments/assets/ad6eeae3-8c35-45f2-9fe1-a5172ee7d55c)

### Steps to Reproduce

Settings > Automations > Blueprints > NSPanel Configuration

### Your Panel's YAML

```yaml
substitutions:
  # Settings - Editable values
  device_name: "kitchennspanel"
  friendly_name: "Kitchen Light Switch NSPanel"
  nextion_update_url: "http://homeassistant.local:8123/local/nspanel_eu.tft"  # Optional
  # Add-on configuration (if needed)
  # heater_relay: "1"  # Possible values: "1" or "2"

# Customization area
##### My customization - Start #####
##### My customization - End #####

# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    refresh: 300s
    files:
      - nspanel_esphome.yaml # Basic package
      # Optional advanced and add-on configurations
      # - esphome/nspanel_esphome_advanced.yaml
      # - esphome/nspanel_esphome_addon_ble_tracker.yaml
      # - esphome/nspanel_esphome_addon_bluetooth_proxy.yaml
      # - esphome/nspanel_esphome_addon_climate_cool.yaml
      - esphome/nspanel_esphome_addon_climate_heat.yaml
      # - esphome/nspanel_esphome_addon_climate_dual.yaml
      # - esphome/nspanel_esphome_addon_cover.yaml
```

### Home Assistant Logs

ESPHome Logs
[5c53de3b_esphome_2024-11-29T19-18-14.069Z.log](https://github.com/user-attachments/files/17962542/5c53de3b_esphome_2024-11-29T19-18-14.069Z.log)
