### ISSUE TITLE
`Bug` oscillating internal temperature signal

### ISSUE THREAD

**Issue by ianfab2000** [Blackymas/NSPanel_HA_Blueprint#2422]
### TFT Version

 4.3.12

### Firmware Version

 4.3.12

### Blueprint Version

 4.3.12

### Panel Model

EU

### What is the bug?

Hey everyone.

The panel worked fine for me for quite some time now but since a couple of weeks it's having the following issue.

Multiple times a day the internal temperature signal starts oscillating between +- 0.5K and +-1K.
While the external temperature signal is constant, the temperature correction trys to compensate that but isn't fast enough.
Consequently the relay is repeatingly switching on and off. 

Restarting the panel solves the issue. Sometimes it requires one, sometimes up to 4 restarts in a row. 

Is this a known issue?
(I have not tried a full factory reset yet but I keep it up to date as described in the FAQs.)

Thanks in advance.

![Screenshot 2024-12-04 190902](https://github.com/user-attachments/assets/b0b60153-a286-4dc9-85f9-bd9be818a0bb)

### Your Panel's YAML

```yaml
substitutions:

###### CHANGE ME START ######

  device_name: "nspanel_blacky" 
  wifi_ssid: "FRITZ!Box 5590 OE"
  wifi_password: ""

  # Add-on configuration (if needed)
  ## Add-on climate
  heater_relay: "1"     # Possible values: "1" or "2"
  temp_units: "°C"      # Temperatures in Fahrenheit
  temp_min: "15"        # Min supported temperature is 40°F
  temp_max: "25"        # Max supported temperature is 80°F
  temp_step: "0.1"        # Temperature granularity is 1°F
  heat_deadband: "0.5"  # Temperature delta before engaging heat
  heat_overrun: "0.5"   # Temperature delta before disengaging heat
  min_off_time: "1"
  min_run_time: "1"
  min_idle_time: "1"

#  nextion_update_url: "http://HOME-ASSISTANT-IP:8123/local/nspanel_eu.tft" # URL to local tft File
  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft" # URL to Github

##### CHANGE ME END #####



##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      - nspanel_esphome_addon_climate_heat.yaml
    refresh: 300s
```
