### ISSUE TITLE
`Bug` Unable to compile - fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.

### ISSUE THREAD

**Issue by dieselee** [Blackymas/NSPanel_HA_Blueprint#2426]
### Panel Model

None

### What is the bug?

Hi im unable to compile is this an external issue or local?

INFO ESPHome 2024.11.3
INFO Reading configuration /config/esphome/ns-panel.yaml...
Failed config

external_components: [source /data/packages/566b10a3/esphome/nspanel_esphome_core.yaml:40]
  - 
    fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
    Use '--' to separate paths from revisions, like this:
    'git <command> [<revision>...] -- [<file>...]'.
    source: 
      type: git
      url: https://github.com/Blackymas/NSPanel_HA_Blueprint
      ref: v4.3.12
    components: 
      - nspanel_ha_blueprint
    refresh: 30s

**Comment by edwardtfn** [comment]
Have you tried cleaning the build files?

**Comment by dieselee** [comment]
> Have you tried [cleaning the build files](https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/docs/error_compiling.md#clean-up-build-files)?

Yes  it appears to give the same error

Clean ns-panel.yaml
INFO ESPHome 2024.11.3
INFO Reading configuration /config/esphome/ns-panel.yaml...
INFO Updating https://github.com/Blackymas/NSPanel_HA_Blueprint@main
Failed config

external_components: [source /data/packages/566b10a3/esphome/nspanel_esphome_core.yaml:40]
  - 
    fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
    Use '--' to separate paths from revisions, like this:
    'git <command> [<revision>...] -- [<file>...]'.
    source: 
      type: git
      url: https://github.com/Blackymas/NSPanel_HA_Blueprint
      ref: v4.3.12
    components: 
      - nspanel_ha_blueprint
    refresh: 30s

**Comment by tomatenkopp** [comment]
same here with ESPHome 2024.12.x had to downgrade ESPHome to 2024.11.3
ESP throws the "ambiguous HEAD" error even in the config editor of the device.

Looks like the config syntax has to be changed, please check and update the config example here, thanks!

**Comment by edwardtfn** [comment]
The tag `v4.3.12` is there and all looks good, so I don't understand this issue.
I've just created a branch with this same name, pointing to the same place. Could you please try again?

**Comment by edwardtfn** [comment]
Could you please try forcing an earlier version of this project?
I'm your panel's yaml, change from `ref: main` to `ref: v4.3.11`.

**Comment by dieselee** [comment]
Same error when trying clean build for me with ref: v4.3.11

**Comment by edwardtfn** [comment]
May I ask for another test?
What if you create a new ESP32 device in your ESPHome Dashboard, then copy your panel's yaml entirely to this new device, replacing its yaml, just keeping a different name to avoid conflicts...
Do you have the same error when compiling that new one?

**Comment by edwardtfn** [comment]
Ok, good to know you can use the system with v4.3.11. But I still have no idea why v4.3.12 is failing. 😬
Anyways, the difference is just an unlikely bug fix related to timezone and we probably can come with a work around for that if you face it. ;)
Let's see if v4.4.0 works better when released.

**Comment by dieselee** [comment]
Thank you for your support, I will install to the ns-panel 👍

**Comment by oolivero45** [comment]
Hi,

I'm having exactly the same issue - trying to use 4.3.11 isn't helping in my case either. Any guidance would be greatly appreciated!

The error I'm getting is exactly the same.

Let me know if there are any logs which would be helpful to attach.

**Comment by edwardtfn** [comment]
Could you please share your yaml and the logs for when you are trying `v4.3.11`?
Please remove any sensitive info before sharing. 😉

**Comment by oolivero45** [comment]
YAML:
```
substitutions:
  # Settings - Editable values
  device_name: "desk-nspanel"
  friendly_name: "Desk NSPanel"
  wifi_ssid: DevNet
  wifi_password: [Redacted]
  nextion_update_url: "http://192.168.1.222/local/nspanel_eu.tft"  # Optional
  # Add-on configuration (if needed)
  # heater_relay: "1"  # Possible values: "1" or "2"

# Customization area
##### My customization - Start #####
api:
  encryption:
    key: "[Redacted]"
##### My customization - End #####

# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: v4.3.11
    refresh: 300s
    files:
      - nspanel_esphome.yaml # Basic package
      # Optional advanced and add-on configurations
      # - esphome/nspanel_esphome_advanced.yaml
      # - esphome/nspanel_esphome_addon_ble_tracker.yaml
      # - esphome/nspanel_esphome_addon_bluetooth_proxy.yaml
      # - esphome/nspanel_esphome_addon_climate_cool.yaml
      - esphome/nspanel_esphome_addon_climate_heat.yaml
      # - esphome/nspanel_esphome_addon_climate_dual.yaml
      # - esphome/nspanel_esphome_addon_cover.yaml
      ```
Logs:
```
INFO ESPHome 2024.12.2
INFO Reading configuration /config/esphome/desk-nspanel.yaml...
INFO Detected timezone 'Europe/London'
INFO Generating C++ source...
Traceback (most recent call last):
  File "/usr/local/bin/esphome", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/esphome/esphome/__main__.py", line 1036, in main
    return run_esphome(sys.argv)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/__main__.py", line 1023, in run_esphome
    rc = POST_CONFIG_ACTIONS[args.command](args, config)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/__main__.py", line 503, in command_run
    exit_code = write_cpp(config)
                ^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/__main__.py", line 213, in write_cpp
    return write_cpp_file()
           ^^^^^^^^^^^^^^^^
  File "/esphome/esphome/__main__.py", line 231, in write_cpp_file
    writer.write_cpp(code_s)
  File "/esphome/esphome/writer.py", line 341, in write_cpp
    copy_src_tree()
  File "/esphome/esphome/writer.py", line 307, in copy_src_tree
    copy_files()
  File "/esphome/esphome/components/esp32/__init__.py", line 801, in copy_files
    repo_dir, _ = git.clone_or_update(
                  ^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/git.py", line 92, in clone_or_update
    old_sha = run_git_command(["git", "rev-parse", "HEAD"], str(repo_dir))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/git.py", line 32, in run_git_command
    raise cv.Invalid(err_str)
voluptuous.error.Invalid: fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

If I swap the ref out for any other version it throws the same error. I'm starting to suspect it's somethign weird going on with ESPHome, rather than with the NSPanel project specifically, at this point, as it seems like it just really does not want to do the git operation properly.

I've tried clearing the build files, with no luck, and I've tried swapping the device running HA out for an 8GB pi rather than the original 4GB one just in case it was running out of memory during compilation.
