### ISSUE TITLE
`Bug` v4.4.0.dev9 unable to update tft

### ISSUE THREAD

**Issue by Mauricewillemstein** [Blackymas/NSPanel_HA_Blueprint#2427]
### TFT Version

v4.4.0.dev8

### Firmware Version

v4.4.0.dev9

### Blueprint Version

v4.4.0.dev9

### Panel Model

EU

### What is the bug?

Updated to v4.4.0.dev9 but tft stays on v4.4.0.dev8.
There nomore is a button to update tft and does not update automaticly

### ESPHome Logs

[logs_zolder_run (6).txt](https://github.com/user-attachments/files/18051030/logs_zolder_run.6.txt)
![Clipboard01](https://github.com/user-attachments/assets/2368dcaf-47f6-4850-9679-f9098abc07f5)

**Comment by edwardtfn** [comment]
Mmmmm

Could you please share your panel's yaml?

With this version I've breakdown packages and mos likely the upload TFT package isn't included to your panel.

**Comment by Mauricewillemstein** [comment]
Here it is

substitutions:
  # Settings - Editable values
  device_name: "zolder"
  friendly_name: "Zolder"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  nextion_update_url: "https://192.168.2.96:8123/local/nspanel_eu.tft"  # Optional
  # Add-on configuration (if needed)
  # heater_relay: "1"  # Possible values: "1" or "2"

# Customization area
##### My customization - Start #####
##### My customization - End #####


packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: v4.4.0.dev9
    refresh: 300s
    files:
      - esphome/nspanel_esphome_core.yaml  # Core configuration required for basic functionality
      - esphome/nspanel_esphome_advanced.yaml
      # - esphome/nspanel_esphome_addon_ble_tracker.yaml
      # - esphome/nspanel_esphome_addon_bluetooth_proxy.yaml
      # - esphome/nspanel_esphome_addon_climate_cool.yaml
      # - esphome/nspanel_esphome_addon_climate_heat.yaml
      # - esphome/nspanel_esphome_addon_climate_dual.yaml
      # - esphome/nspanel_esphome_addon_cover.yaml

**Comment by edwardtfn** [comment]
Mmmm...

Please try this:
```yaml
substitutions:
  # Settings - Editable values
  device_name: "zolder"
  friendly_name: "Zolder"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  nextion_update_url: "https://192.168.2.96:8123/local/nspanel_eu.tft"  # Optional
  # Add-on configuration (if needed)
  # heater_relay: "1"  # Possible values: "1" or "2"

# Customization area
##### My customization - Start #####
##### My customization - End #####


packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: v4.4.0.dev9
    refresh: 300s
    files:
      - esphome/nspanel_esphome_core.yaml  # Core configuration required for basic functionality
      - esphome/nspanel_esphome_standard.yaml
      - esphome/nspanel_esphome_advanced.yaml
      # - esphome/nspanel_esphome_addon_ble_tracker.yaml
      # - esphome/nspanel_esphome_addon_bluetooth_proxy.yaml
      # - esphome/nspanel_esphome_addon_climate_cool.yaml
      # - esphome/nspanel_esphome_addon_climate_heat.yaml
      # - esphome/nspanel_esphome_addon_climate_dual.yaml
      # - esphome/nspanel_esphome_addon_cover.yaml
```
