### ISSUE TITLE
`Bug` NS panel uses an unknow action

### ISSUE THREAD

**Issue by CarstenHoell** [Blackymas/NSPanel_HA_Blueprint#2431]
### TFT Version

4.3.12

### Firmware Version

2024.11.3

### Panel Model

EU

### What is the bug?

after updating NS panel the TFT screen is no longer updating with different screens.
Mechanical buttons work incl connection to Z2M devices

### Your Panel's YAML

```yaml
alias: NSpanelStue
description: ""
use_blueprint:
  path: Blackymas/nspanel_blueprint.yaml
  input:
    nspanel_name: nspanelstue
    language: DNK
    weather_entity: weather.hjem
    indoortemp: AirQ_Livingroom Temperature_2
    climate: climate.heat_livingroom_heat_livingroom
    left_button_entity: light.living_room_lights
    left_button_name: Stue
    right_button_entity: switch.entertainment_power_2
    right_button_name: TV
    button_page01_label: Stue
    button_page02_label: Køkken
    button_page03_label: Outdoor
    button_page04_label: Other
    entity01: light.spot_picture_living_room
    entity01_name: Spot Tutankhamon
    entity02: light.spot_drawer_cabinet
    entity02_name: Skuffeskab
    entity03: light.spot_china_cabinet
    entity03_name: Bogskab
    entity04: light.reading_lamp
    entity04_name: Læselampe
    entity05: light.new_moon1_2
    entity05_name: Spot 1
    entity06: light.new_moon2_2
    entity06_name: Spot 2
    entity07: light.new_moon3_2
    entity07_name: Spot 3
    entity09: light.dining_room_1
    entity09_name: Spisebord
    entity10: light.spot_picture_dining_room
    entity10_name: WTC
    entity11: light.kitchen_lamps_2
    entity11_name: Køkkenbord
    entity12: light.bedroom_lights
    entity12_name: Soveværelse
    entity13: light.dish_washer_power
    entity12_confirm: false
    entity13_name: Opvaskemaskine
    entity08: switch.plug_bar_light
    entity08_name: Barskab
    entity13_confirm: true
```

### ESPHome Logs

```log
Logger: homeassistant.components.automation.nspanelstue
Source: helpers/script.py:2032
integration: Automation ([documentation](https://www.home-assistant.io/integrations/automation), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+automation%22))
First occurred: 20:24:50 (194 occurrences)
Last logged: 20:50:00

NSpanelStue: Choose at step 2: choice 19: Error executing script. Service not found for call_service at pos 1: Action esphome.nspanelstue_send_command_text_printf not found
NSpanelStue: Error executing script. Service not found for choose at pos 2: Action esphome.nspanelstue_send_command_text_printf not found
NSpanelStue: Choose at step 2: choice 24: If at step 1: Error executing script. Service not found for call_service at pos 1: Action esphome.nspanelstue_send_command_text_printf not found
NSpanelStue: Choose at step 2: choice 24: Error executing script. Service not found for if at pos 1: Action esphome.nspanelstue_send_command_text_printf not found
NSpanelStue: Error executing script. Service not found for choose at pos 2: Action esphome.nspanelstue_send_command_printf not found
```
![NS panel 3](https://github.com/user-attachments/assets/1b2465c8-331c-4f26-9811-2ba29f8c23b0)
![NS panel 2](https://github.com/user-attachments/assets/802c1b58-57b7-4574-bb2f-56063a4306c2)
![NS panel 1](https://github.com/user-attachments/assets/2c250263-3ab6-4ab6-bf53-9d0e54eefae5)
[logs_nspanelstue_run.txt](https://github.com/user-attachments/files/18085117/logs_nspanelstue_run.txt)
