### ISSUE TITLE
`Bug` Compiling Error -- The C compiler identification is unknown -- The CXX compiler identification is unknown

### ISSUE THREAD

**Issue by morpheus-pl** [Blackymas/NSPanel_HA_Blueprint#2432]
### TFT Version

4.3.11

### Firmware Version

2024.11.3

### Blueprint Version

4.3.11

### Panel Model

US (Landscape)

### What is the bug?

I cannot compile any of the ESP versions bigger than 2024.11.3.
All new firmwares during the compiling process - even after clean build - shows the faults:
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
What shall I do to overcome the compile error.

### Steps to Reproduce

During compilation for firmware update installation.

### Your Panel's YAML

```yaml
substitutions:
  # Settings - Editable values
  device_name: "nspanel-sypialniaesp" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_pass
  nextion_update_url: "http://homeassistant.local:8123/local/nspanelusland.tft"  # Optional
  # Add-on configuration (if needed)
  # heater_relay: "1"  # Possible values: "1" or "2"

# Customization area
##### My customization - Start #####
wifi:
  # ...
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.xxx.107
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.xxx.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0
    dns1: 192.168.xxx.1
    dns2: 8.8.8.8
##### My customization - End #####

# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    refresh: 300s
    files:
      - nspanel_esphome.yaml # Basic package
      # Optional advanced and add-on configurations
      #- nspanel_esphome_advanced.yaml
      # - nspanel_esphome_addon_climate_cool.yaml
      # - nspanel_esphome_addon_climate_heat.yaml
      # - nspanel_esphome_addon_climate_dual.yaml
esphome:
  compile_process_limit: 1
esp32:
  framework:
    type: esp-idf
# Enable wireless updates
ota:
  platform: esphome
  password: "xxx"
##### My customization - Start #####
##### My customization - End #####
```
