### ISSUE TITLE
`Bug`  Blueprint does not save as automation, nspanel does not take it

### ISSUE THREAD

**Issue by lopikamper** [Blackymas/NSPanel_HA_Blueprint#2434]
### TFT Version

v4.3.12

### Firmware Version

v4.3.12

### Blueprint Version

v4.3.12

### Panel Model

EU

### What is the bug?

When I try to create an automation from blueprint, it simply does not save itself. I have completely new NSPanel flashed with latest ESPhome firmware. TFT file loaded fine as well. But I am stuck on this last step. 

### Steps to Reproduce

1. Go to "Automations"
2. Create an automation from blueprint NS Panel
3. Select nspanel device
4. Save new automation
5. Name of automation changes
6. Go back to automations
7. Nothing there

### Your Panel's YAML

```yaml
substitutions:
  # Settings - Editable values
  device_name: "nspanelhall"
  friendly_name: "nspanelhallwhite"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  nextion_update_url: "http://192.168.0.10:8123/local/nspanel_eu.tft"  # Optional
  # Add-on configuration (if needed)
  # heater_relay: "1"  # Possible values: "1" or "2"

# Customization area
##### My customization - Start #####
# Enable Home Assistant API
api:
  encryption:
    key: "t+Qf+ZYiGdhdxfnD3CE0HT+I99Il71Mwr+hXiVMJ9Us="
##### My customization - End #####

# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    refresh: 300s
    files:
      - nspanel_esphome.yaml # Basic package
      # Optional advanced and add-on configurations
      # - esphome/nspanel_esphome_advanced.yaml
      # - esphome/nspanel_esphome_addon_ble_tracker.yaml
      # - esphome/nspanel_esphome_addon_bluetooth_proxy.yaml
      # - esphome/nspanel_esphome_addon_climate_cool.yaml
      # - esphome/nspanel_esphome_addon_climate_heat.yaml
      # - esphome/nspanel_esphome_addon_climate_dual.yaml
      # - esphome/nspanel_esphome_addon_cover.yaml
```

### ESPHome Logs

[17:10:38][C][nspanel_ha_blueprint:2243]: Blueprint:
[17:10:38][W][nspanel_ha_blueprint:2248]:   Init steps:  0 (0.0%)
[17:10:38][W][nspanel_ha_blueprint:2249]:   State:       Pending
[17:10:38][C][nspanel_ha_blueprint:2250]: Requesting blueprint settings
[17:10:38][D][script:077]: Script 'boot_event' restarting (mode: restart)
[17:10:38][C][nspanel_ha_blueprint:2255]: ESPHome:
[17:10:38][C][nspanel_ha_blueprint:2256]:   Version:     4.3.12
[17:10:38][C][nspanel_ha_blueprint:2257]:   Compiler:    2024.10.3
[17:10:38][C][nspanel_ha_blueprint:2262]:   Framework:   ESP-IDF
[17:10:38][C][nspanel_ha_blueprint:2267]:   Free heap:
[17:10:38][C][nspanel_ha_blueprint:2271]:     Internal:   203868 bytes (58.0%)
[17:10:38][C][nspanel_ha_blueprint:2281]:     PSRAM:     2018251 bytes (96.8%)
[17:10:38][C][nspanel_ha_blueprint:2288]: UART:
[17:10:38][C][nspanel_ha_blueprint:2289]:   Baud rate:   115200 bps
[17:10:38][C][nspanel_ha_blueprint:2290]:   Queue size:  0
[17:10:38][C][nspanel_ha_blueprint:2294]: Nextion:
[17:10:38][C][nspanel_ha_blueprint:2295]:   Queue size:  0
[17:10:38][C][nspanel_ha_blueprint:2297]:   Is setup:    True
[17:10:38][C][nspanel_ha_blueprint:2304]:   Init:        True
[17:10:38][C][nspanel_ha_blueprint:2310]:   TFT:         4.3.12
[17:10:38][C][nspanel_ha_blueprint:2311]: Packages:
[17:10:38][C][nspanel_ha_blueprint:2313]:   - Core

### Home Assistant Logs

Nothing relevant
