### ISSUE TITLE
`Bug` Chips are not working

### ISSUE THREAD

**Issue by andreas-bulling** [Blackymas/NSPanel_HA_Blueprint#2451]
### TFT Version

4.3.12

### Firmware Version

4.3.12

### Blueprint Version

4.3.12

### Panel Model

EU

### What is the bug?

Chips are simply not working. Whatever I set in the respective configuration group in the blueprint, nothing is shown at the top. The only thing that is shown are the little boxed 1 and 2 when pressing the physical buttons.

**Comment by edwardtfn** [comment]
Do you have any error message in your Home Assistant logs (Settings > System > Logs)?

**Comment by andreas-bulling** [comment]
Not related to Chips as far as I can see. But two others ones that I posted under [the other issue](https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/2450)

**Comment by umrath** [comment]
I have the same issue.
I have set up 3 new NSPanels yesterday and today and no Chips are visible on either device.

**Comment by andreas-bulling** [comment]
@edwardtfn are chips working for you? Can you send us a minimally working example that we could try?

**Comment by edwardtfn** [comment]
Sorry, I've been sick those days and haven't had time to work at this, but I can confirm chips are working properly with my panel running v4.3.12.

**Comment by edwardtfn** [comment]
Chips will be visible only when the state of the entity assigned to it is 'true' (or equivalent).
Could you please double check the state of the entity on Developer Tools > States?

**Comment by andreas-bulling** [comment]
Does it have to be "on" or is a state that is a number, e.g. AC input or current solar power, also fine?

**Comment by edwardtfn** [comment]
I'm pretty sure any value different than 0 will be considered `true`, but I have to double check this info later.

**Comment by andreas-bulling** [comment]
I've tried to use different entities, incl. some that definitely return a value (such as ac_input). But the chips don't work. I'll try a binary_sensor next.

BTW - what is the intended use case for these chips?

**Comment by kroessig** [comment]
> I've tried to use different entities, incl. some that definitely return a value (such as ac_input). But the chips don't work. I'll try a binary_sensor next.
> 
> BTW - what is the intended use case for these chips?

i use the chips to 
- indicate whether and which garbage can is next.
- whether the heating is on
- the symbol changes depending on whether the battery is being charged or discharged.
- I made a timer that plays a melody on the panel when it expires. To see if the timer is on, I also use a chip.

Most chips also change their color depending on their condition. it's simple like:

```
alias: Farbe Batteriesymbol steigt
sequence:
  - condition: state
    entity_id: sensor.symbol_batterie
    attribute: icon
    state: mdi:battery-arrow-up
  - data:
      component: icon_top_06
      foreground:
        - 0
        - 255
        - 0
      background: []
    action: esphome.panelwozi_set_component_color
mode: single
icon: mdi:battery-arrow-up
```
