### ISSUE TITLE
`Enhancement` Activate screen when button pressed

### ISSUE THREAD

**Issue by PedroKTFC** [Blackymas/NSPanel_HA_Blueprint#2460]
### Enhancement Summary

Activate screen when button pressed, perhaps as an option

### Detailed Description

I use the buttons to turn lights on and off, one of which isn't easily visible. I find pressing the buttons doesn't always work (I probably mispress). It would be useful, perhaps as an option, to activate the screen when a button is pressed to provide a clear confirmation.

[An alternative might be to have a bleep when pressed. In my own implementation on another NSPanel I use, I require that one of the buttons has to be pressed for 2 seconds before it actioned as it opens an electric gate and I don't want that happening with an accidental press.]

**Comment by dimis7** [comment]
Hi! I also wanted this and it's possible to do it with below automation:

```
alias: NSPanel2-Livingroom wake-up the display when buttons are pressed
description: ""
triggers:
  - trigger: state
    entity_id:
      - binary_sensor.nspanel2_livingroom_right_button
      - binary_sensor.nspanel2_livingroom_left_button
conditions: []
actions:
  - action: esphome.nspanel2_livingroom_wake_up
    metadata: {}
    data:
      reset_timer: false
mode: single
```
