### ISSUE TITLE
Configuring 2nd NSPanel over WIFI corrupts previously working 1st NSPanel.

### ISSUE THREAD

**Issue by st2000** [Blackymas/NSPanel_HA_Blueprint#2490]
### TFT Version

4.3.12

### Firmware Version

4.3.12

### Blueprint Version

4.3.11

### Panel Model

US

### What is the bug?

Can not configure 2 differently named NSPanels identically except for physical buttons. Specifically, can not independently configure the physical button settings. 

### Steps to Reproduce

For example, the 1st NSPanel name is chosen in the Settings->Automation->NSPanel Configuration. All desired configurations are set and the panel works as expected. Then, the 2nd NSPanel name is chosen and the physical buttons are assigned a different purpose. The 2nd panel works as expected. However, if the 1st NSPanel name is chosen the physical buttons are set as if this were the 2nd NSPanel. At this point, if the 1st NSPanel is programmed, the physical buttons are unexpectedly changed to that of the 2nd NSPanel.

### Your Panel's YAML

```yaml
substitutions:
  # Settings - Editable values
  device_name: "nspanel100"
  friendly_name: "nspanel100"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  nextion_update_url: "http://homeassistant.local:8123/local/nspanel_eu.tft"  # Optional
  # Add-on configuration (if needed)
  # heater_relay: "1"  # Possible values: "1" or "2"

# Customization area
##### My customization - Start #####
##### My customization - End #####

# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    refresh: 300s
    files:
      - nspanel_esphome.yaml # Basic package
      # Optional advanced and add-on configurations
      # - esphome/nspanel_esphome_advanced.yaml
      # - esphome/nspanel_esphome_addon_ble_tracker.yaml
      # - esphome/nspanel_esphome_addon_bluetooth_proxy.yaml
      # - esphome/nspanel_esphome_addon_climate_cool.yaml
      - esphome/nspanel_esphome_addon_climate_heat.yaml
      # - esphome/nspanel_esphome_addon_climate_dual.yaml
      # - esphome/nspanel_esphome_addon_cover.yaml
```
