### ISSUE TITLE
`Bug` Blueprint automation has an unknown action: esphome.[name]_component_text.

### ISSUE THREAD

**Issue by duko1234** [Blackymas/NSPanel_HA_Blueprint#2511]
### TFT Version

4.3.12

### Firmware Version

4.3.12

### Blueprint Version

4.3.12

### Panel Model

EU

### What is the bug?

Before the error started to occur regularly, I renamed the device including entity-ids.

Now after every home assistant startup, I get the following error message:

```
NS Panel Kind2 uses an unknown action
Error ⸱ Reported by Automation
The automation "NS Panel Kind2" (automation.ns_panel_kind2) has an unknown action: esphome.thermostat_kind_2_component_text.

This error prevents the automation from running correctly. Maybe this action is no longer available, or perhaps a typo caused it.

To fix this error, [edit the automation](http://192.168.1.XX:8123/config/automation/edit/17423123123122) and remove this action.

Select Submit below to confirm you have fixed this automation.
```

### Your Panel's YAML

```yaml
substitutions:
  # Settings - Editable values
  device_name: "ns-panel"
  friendly_name: "NS Panel"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  nextion_update_url: "http://homeassistant.local:8123/local/nspanel_eu.tft"  # Optional
  # Add-on configuration (if needed)
  heater_relay: "1"  # Possible values: "1" or "2"

# Customization area
##### My customization - Start #####
# Example configuration entry
esp32_ble_tracker:

# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    refresh: 300s
    files:
      - nspanel_esphome.yaml # Basic package
      # Optional advanced and add-on configurations
      # - esphome/nspanel_esphome_advanced.yaml
      - esphome/nspanel_esphome_addon_ble_tracker.yaml
      # - esphome/nspanel_esphome_addon_bluetooth_proxy.yaml
      # - esphome/nspanel_esphome_addon_climate_cool.yaml
      - esphome/nspanel_esphome_addon_climate_heat.yaml
      # - esphome/nspanel_esphome_addon_climate_dual.yaml
      # - esphome/nspanel_esphome_addon_cover.yaml
```
