### ISSUE TITLE
`Bug` Incorrect chip display

### ISSUE THREAD

**Issue by Markus1971a** [Blackymas/NSPanel_HA_Blueprint#2521]
### TFT Version

4.3.12

### Firmware Version

4.3.12

### Blueprint Version

4.3.12

### Panel Model

EU

### What is the bug?

Hello, for a while now, a copy of the last custom button I entered has been appearing between the Relay 2 chip and the first chip in the top left corner! Is this a bug or a change in the ESPHome Builder? I've tried everything, but unfortunately, I can't get rid of it! This is happening on all four of my NS panels.

Thanks and keep up the good work...

### Your Panel's YAML

```yaml

```

**Comment by Markus1971a** [comment]
![Image](https://github.com/user-attachments/assets/d7ec90bd-29de-4065-a925-27bab93f2444)

**Comment by karolkoz83** [comment]
Looks like a bug after latests updates. When you remove the entity from custom button home page, the icon is going to be removed from the chip bar. In my case I had a bulb entity as a custom button on a home page and the icon of the bulb was shown on chip bar instead of icon of floor heating entity. The same situation on all of my nspanels.

I hope further updates fix it.

**Comment by Markus1971a** [comment]
If I remove the custom buttons, for example, 4, 5, and 6, it displays custom button 3. If only 6 is deleted or empty, 5 is displayed. The order is always the last custom button, which is displayed at the top between Relay 2 and the first chip. However, it also sporadically changes with a temperature symbol and can sometimes be colored. I'm sure this is a phenomenon after one of the last ESPHome updates, because it hasn't been there yet.

**Comment by karolkoz83** [comment]
Yes. Even the chips before where grayed when state of entity was false/off. Now they are completely invisible with that state. Hopefully they fix it in the next update.

**Comment by AbeltjeNL** [comment]
I'm experiencing a similar issue. My climate entity in the chips section is not showing a climate icon but instead it's showing the Spotify icon.

**Comment by edwardtfn** [comment]
Are you still having these issues with the latest version?

**Comment by PaulBiod** [comment]
> Are you still having these issues with the latest version?

@edwardtfn Yes, still there, no change with v4.3.46

![Image](https://github.com/user-attachments/assets/5685b4f4-e697-4f38-9d56-cd006ad0f55f)

**Comment by Markus1971a** [comment]
Hello, is there any news on this? I thought it would disappear with version 2025.1001, but unfortunately the error is still present! Many thanks, great work.

**Comment by edwardtfn** [comment]
Do you mind sharing the yaml both from your panel and from your automation?
Please remember to hide any private info before sharing. 😉

**Comment by edwardtfn** [comment]
Another question... do you have add-on climate enabled?

**Comment by Markus1971a** [comment]
Hello, attached are the YAML files for the panel and the automation. No, I'm not using the Climate add-on.

```yaml
*****************************************************************************************************************************

substitutions:
  # Settings - Editable values
  device_name: "nspanelkueche"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  nextion_update_url: "http://homeassistant.local:8123/local/nspanel_eu.tft"  # Optional
  # Add-on configuration (if needed)
  # heater_relay: "1"  # Possible values: "1" or "2"

# Customization area
##### My customization - Start #####
##### My customization - End #####

wifi:
  networks:
    - id: !extend wifi_default
      manual_ip:
        static_ip: "192.168.170.18"
        gateway: "192.168.170.1"
        subnet: "255.255.255.0"
        dns1: "192.168.170.1"

api:

##### DO NOT CHANGE - Start! #####
# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Basic package
      # Optional advanced and add-on configurations
      # - esphome/nspanel_esphome_advanced.yaml
      # - nspanel_esphome_addon_climate_cool.yaml
      # - nspanel_esphome_addon_climate_heat.yaml
      # - nspanel_esphome_addon_climate_dual.yaml
    refresh: 300s

    # Change framework to `esp-idf`
esp32:
  framework:
    type: esp-idf
##### DO NOT CHANGE - END! #####    

*******************************************************************************************************************************
```

```yaml
alias: _NSPanel Configuration Küche
description: ""
use_blueprint:
  path: Blackymas/nspanel_blueprint.yaml
  input:
    nspanel_name: 5be26b6cf3725e831acdcb0f9d47ce41
    language: de
    weather_entity: weather.geldern
    outdoortemp: sensor.t_h_sensor_aussen_temperatur
    home_outdoor_temp_label_color:
      - 255
      - 255
      - 255
    indoortemp: sensor.kuche_fuhler_temperature
    home_indoor_temp_icon_color:
      - 10
      - 225
      - 24
    home_indoor_temp_label_color:
      - 10
      - 225
      - 24
    home_value01: sensor.kesselvorlaufisttemperatur
    climate_button08_icon: ""
    climate_value03_icon: mdi:thermometer-lines
    climate_button09_hold_custom_action: []
    climate_button08_hold_custom_action: []
    chip01: input_boolean.hilfsschalter_sommer_winter_modus
    chip01_icon: mdi:white-balance-sunny
    chip01_icon_color:
      - 238
      - 242
      - 7
    home_value01_icon: mdi:gas-burner
    home_value01_icon_color:
      - 248
      - 0
      - 1
    left_button_entity: switch.kuche_licht_total
    left_button_name: Licht
    left_button_color:
      - 255
      - 248
      - 229
    left_button_hold_select: Default
    button_page01_label: Küche Heizung
    entitypages_enabled: true
    entity24_confirm: false
    entity01: climate.better_thermostat_kuche
    entity01_name: Heizung
    entity01_icon: mdi:heating-coil
    entity01_icon_color:
      - 250
      - 0
      - 108
    entity01_confirm: false
    entity02_icon: ""
    entity02_icon_color:
      - 199
      - 199
      - 199
    entity03_icon: ""
    entity03_icon_color:
      - 209
      - 209
      - 209
    entity04_icon: mdi:air-conditioner
    entity04_icon_color:
      - 246
      - 0
      - 250
    entity05: input_boolean.heizung_kuche_party
    entity05_name: KOMFORT
    entity05_icon: mdi:weather-sunny
    entity05_icon_color:
      - 250
      - 0
      - 0
    entity06_icon: mdi:weather-night
    entity07_icon: ""
    entity08_icon: ""
    entity08_confirm: false
    home_value02: sensor.warmwasseristtemperatur
    home_value01_label_color:
      - 248
      - 0
      - 0
    home_value02_icon: mdi:thermometer-water
    home_value02_icon_color:
      - 5
      - 138
      - 255
    home_value02_label_color:
      - 0
      - 129
      - 245
    home_value03_icon: mdi:transmission-tower
    home_value03_icon_color:
      - 245
      - 143
      - 0
    home_value03_label_color:
      - 245
      - 143
      - 1
    chip02: binary_sensor.brenneransteuerung
    chip02_icon: mdi:gas-burner
    chip02_icon_color:
      - 242
      - 7
      - 7
    home_custom_button01_icon: mdi:home-map-marker
    climate_value01: sensor.aussentemperatur
    climate_value01_icon: mdi:thermometer-lines
    climate_value01_icon_color:
      - 0
      - 108
      - 250
    climate_value01_label_color:
      - 0
      - 108
      - 250
    climate_value02: sensor.schimmel_indikator_kuche
    climate_value02_icon: mdi:molecule
    climate_value02_icon_color:
      - 221
      - 0
      - 250
    climate_value02_label_color:
      - 221
      - 0
      - 250
    climate_value04_icon: mdi:pump
    climate_value04_icon_color:
      - 255
      - 10
      - 10
    climate_value04_label_color:
      - 255
      - 10
      - 10
    qrcode_enabled: true
    qrcode_value: WIFI:S:***************;T:WPA;P:********************;;
    qrcode_label: Gäste WLAN
    right_button_entity: input_boolean.kuche_klima_hilfsschalter
    right_button_name: Klimaanlage
    right_button_color:
      - 255
      - 248
      - 229
    entity07_confirm: false
    chip03_icon: mdi:heating-coil
    chip03_icon_color:
      - 242
      - 7
      - 145
    chip04_icon: mdi:pump
    chip04_icon_color:
      - 247
      - 121
      - 2
    chip05: binary_sensor.zirkulationspumpenbetrieb
    chip05_icon: mdi:water-thermometer
    chip05_icon_color:
      - 253
      - 48
      - 246
    chip07: binary_sensor.fehler_brennerstoerung
    chip07_icon: mdi:alert
    chip07_icon_color:
      - 245
      - 25
      - 25
    chip06_icon: mdi:microsoft-office
    chip06_icon_color:
      - 228
      - 1
      - 1
    home_custom_button02_icon: ""
    climate_button09_icon: ""
    climate_button09_icon_color:
      - 200
      - 200
      - 200
    button_page02_label: Küche Rollladen
    entity09: cover.kuche_rolllade_gros
    entity09_name: Rollladen groß
    entity09_icon: ""
    entity09_icon_color:
      - 0
      - 50
      - 250
    entity10_icon: ""
    entity10_icon_color:
      - 0
      - 50
      - 250
    entity11_icon: ""
    entity11_icon_color:
      - 194
      - 194
      - 194
    entity13_icon: ""
    entity14_icon: ""
    entity16_icon: ""
    entity16_icon_color:
      - 194
      - 194
      - 194
    button_page03_label: Beleuchtung
    entity_page01_label: Müllabfur
    entities_entity01: sensor.nachste_abholung
    entities_entity01_name: Nächste Abholung
    entities_entity01_icon: mdi:calendar-today
    entities_entity02: sensor.restmull2
    entities_entity02_name: Restmüll
    entities_entity02_icon: mdi:trash-can-outline
    relay01_icon_color:
      - 223
      - 219
      - 255
    relay02_icon_color:
      - 223
      - 219
      - 255
    show_while_loading: true
    entity17: switch.kuche_licht_herd
    entity17_name: Herd
    entity17_icon: mdi:wall-sconce-round
    entity17_icon_color:
      - 250
      - 217
      - 0
    entity18_icon: mdi:wall-sconce-round
    entity18_icon_color:
      - 250
      - 217
      - 0
    chip03: binary_sensor.heizungspumpe
    home_button04_icon: mdi:email
    entity19_icon: ""
    entity19_icon_color:
      - 204
      - 204
      - 204
    entity20_icon: mdi:floor-lamp
    entity20_icon_color:
      - 250
      - 217
      - 0
    entity_page02_label: zu Hause
    entities_entity09: person.*******
    entities_entity09_icon: mdi:account
    entities_entity09_name: *******
    entities_entity10: person.*******
    entities_entity10_name: ******
    entities_entity10_icon: mdi:account
    entities_entity11: person.******
    entities_entity11_name: ********
    entities_entity11_icon: mdi:account
    entities_entity12: person.*******
    entities_entity12_name: ********
    entities_entity12_icon: mdi:account
    entities_entity13: person.******
    entities_entity13_name: *********
    entities_entity13_icon: mdi:account
    entities_entity03_name: Gelbe Tonne
    entities_entity03: sensor.gelbe_tonne2
    entities_entity03_icon: mdi:trash-can-outline
    entities_entity04: sensor.biomull2
    entities_entity04_name: Biomüll
    entities_entity04_icon: mdi:trash-can-outline
    entities_entity05: sensor.papier2
    entities_entity05_name: Papier Tonne
    entities_entity05_icon: mdi:trash-can-outline
    entities_entity06: sensor.altglas2
    entities_entity06_name: Altglas
    entities_entity06_icon: mdi:bottle-soda
    entities_entity07_icon: ""
    entities_entity08_icon: ""
    entity02_confirm: false
    entity03_confirm: false
    entity04_confirm: false
    entity05_confirm: false
    entity06_confirm: false
    entity25_icon: ""
    entity25_icon_color:
      - 186
      - 3
      - 252
    entity29_icon: mdi:radio
    entity06_icon_color:
      - 54
      - 0
      - 250
    entity07_icon_color:
      - 219
      - 219
      - 219
    entity08_icon_color:
      - 207
      - 207
      - 207
    entity11_confirm: false
    entity12: cover.kuche_rollladen_gruppe
    entity13_icon_color:
      - 189
      - 189
      - 189
    entity14_icon_color:
      - 199
      - 199
      - 199
    entity14_confirm: false
    entity15_icon: ""
    entity15_icon_color:
      - 204
      - 204
      - 204
    entity12_name: Rollladen Gruppe
    entity12_icon: ""
    entity12_icon_color:
      - 0
      - 50
      - 250
    entity21_icon: ""
    entity21_icon_color:
      - 199
      - 199
      - 199
    entity22_icon: ""
    entity22_icon_color:
      - 201
      - 201
      - 201
    entity23_icon: ""
    entity23_icon_color:
      - 201
      - 201
      - 201
    entity24_icon_color:
      - 201
      - 201
      - 201
    entity24_icon: ""
    home_custom_button03_icon: mdi:lamp
    home_custom_button03: switch.kuche_licht_fenster
    entity_page03_label: Betrieb
    entities_entity17: sensor.waschmaschine_power
    entities_entity17_name: Waschmaschine
    entities_entity17_icon: mdi:washing-machine
    entities_entity18: sensor.trockner_power
    entities_entity18_name: Trockner
    entities_entity18_icon: mdi:tumble-dryer
    entities_entity19: sensor.spulmaschine_leistung_w
    entities_entity19_name: Spülmaschine
    entities_entity19_icon: mdi:dishwasher
    entities_entity20: sensor.herd_power
    entities_entity20_name: Herd
    entities_entity20_icon: mdi:stove
    entities_entity21: sensor.backofen_leistung_w
    entities_entity21_name: Backofen
    entities_entity21_icon: mdi:stove
    entities_entity22: sensor.microwelle_leistung_w
    entities_entity22_name: Microwelle
    entities_entity22_icon: mdi:microwave
    entities_entity23: sensor.buro_leistung_w
    entities_entity23_name: Büro
    entities_entity23_icon: mdi:microsoft-office
    chip04: binary_sensor.ladepumpenbetrieb
    entities_entity25_icon: mdi:sun-snowflake
    entities_entity24: sensor.gartenpumpe_leistung_w
    entities_entity24_name: Gartenpumpe
    entities_entity24_icon: mdi:water-pump
    entities_entity32: binary_sensor.ww_tag_modus
    entities_entity32_name: Warmwasser an
    entities_entity32_icon: mdi:heat-wave
    entities_entity26_icon: mdi:exclamation-thick
    entities_entity27_name: Kesselvorlaufisttemperatur
    entities_entity27_icon: mdi:coolant-temperature
    entities_entity28_icon: mdi:pump
    entities_entity29_icon: mdi:thermometer-water
    entities_entity30_icon: mdi:pump
    entitypages_value_alignment: "0"
    entity_page04_label: Heizung Buderus
    entities_entity25: input_boolean.hilfsschalter_sommer_winter_modus
    entities_entity25_name: Winterbetrieb
    entities_entity26: select.heizkreis_1_betriebsmodus
    entities_entity26_name: Betriebsmodus Heizung
    entities_entity27: sensor.kesselvorlaufisttemperatur
    entities_entity28: sensor.hk1_pumpenleistung
    entities_entity28_name: Pumpenbetrieb HK
    entities_entity29: sensor.warmwasseristtemperatur
    entities_entity29_name: Wassertemperatur
    entities_entity30: binary_sensor.ladepumpenbetrieb
    entities_entity30_name: Ladepumpenbetrieb WW
    button_page04_label: Media
    entity26_icon: mdi:spotify
    entity26_icon_color:
      - 32
      - 194
      - 0
    entity27_icon: mdi:radio
    entity27_icon_color:
      - 240
      - 25
      - 25
    entity28_icon: mdi:radio
    entity28_icon_color:
      - 151
      - 10
      - 245
    entity29_icon_color:
      - 151
      - 10
      - 245
    chip_font_size: "8"
    home_button06_icon_color:
      - 2
      - 247
      - 2
    entity32_icon: mdi:radio
    entity32_icon_color:
      - 250
      - 0
      - 75
    entity31: script.alexa_kuche_wdr_2_rhein_und_ruhr
    entity31_name: WDR 2 Rhein und Ruhr
    entity31_icon: mdi:radio
    entity31_icon_color:
      - 0
      - 208
      - 250
    entity30_icon: mdi:radio
    entity30_icon_color:
      - 151
      - 10
      - 245
    entity12_confirm: true
    home_custom_button04: switch.fritz_box_7590_ax_wi_fi_dessert_gast
    home_custom_button04_icon: mdi:wifi-plus
    button_pages_icon_size: "10"
    screensaver_display_time: true
    screensaver_display_time_font_color:
      - 255
      - 245
      - 240
    home_button04_icon_color01:
      - 224
      - 225
      - 224
    home_outdoor_temp_font: "5"
    home_custom_button01: input_boolean.bypass_alle_da_arbeitstag
    screensaver_display_time_font_size: "12"
    home_value04: sensor.solar_total
    home_value04_label_color:
      - 246
      - 250
      - 1
    home_value04_icon: mdi:solar-power-variant
    home_value04_icon_color:
      - 251
      - 255
      - 0
    utilities_enabled: true
    utilities_page01_home_value1: sensor.zu_hause_total_energy_kwh_taglich
    utilities_page01_grid_value1: sensor.entnahme_aus_netz_in_kwh_taglich
    utilities_page01_home_color:
      - 17
      - 255
      - 0
    utilities_page01_grid_color:
      - 65
      - 71
      - 251
    climate: climate.versatile_thermostat_klima_kuche
    climate_chip_always_visible: true
    entity32: script.alexa_kuche_energy
    entity32_name: Radio Energy
    utilities_page01_label: Stromverbrauch Total
    utilities_page01_group01_icon: mdi:molecule-co2
    utilities_page01_group01_color:
      - 217
      - 23
      - 23
    utilities_page01_main_line_reference: sensor.zu_hause_total_energy_kwh_taglich
    utilities_page01_group01_label: CO²
    utilities_page01_group01_value1: sensor.co2_signal_grid_fossil_fuel_percentage
    utilities_page01_group01_line_reference: sensor.entnahme_aus_netz_in_kwh_taglich
    utilities_page01_group02_value1: sensor.zuruck_zum_netz_in_kwh_taglich
    utilities_page01_group02_label: Zurück
    utilities_page01_group02_icon: mdi:transmission-tower-import
    utilities_page01_grid_icon: mdi:transmission-tower-export
    utilities_page01_group02_color:
      - 205
      - 16
      - 218
    utilities_page01_group02_line_reference: sensor.zuruck_zum_netz_in_kwh_taglich
    utilities_page01_group01_line_inverted: true
    home_value03: sensor.total_power
    icon_color_fallback_on:
      - 251
      - 255
      - 26
    icon_color_fallback_off:
      - 106
      - 95
      - 95
    utilities_page01_group03_value1: sensor.solar_total_energy_taglich
    utilities_page01_group03_line_reference: sensor.solar_total_energy_taglich
    utilities_page01_group03_color:
      - 232
      - 248
      - 13
    utilities_page01_group03_icon: mdi:solar-power-variant
    utilities_page01_group03_label: Solar
    utilities_page01_group03_line_inverted: true
    utilities_page01_group02_line_inverted: true
    utilities_page01_group04_color:
      - 255
      - 255
      - 255
    utilities_page01_group05_value1: sensor.gasverbrauch_taglich_kwh
    utilities_page01_group05_color:
      - 255
      - 136
      - 0
    utilities_page01_group04_icon: ""
    utilities_page01_group05_label: Gas
    utilities_page01_group05_icon: mdi:gas-burner
    utilities_page01_group05_line_reference: sensor.gasverbrauch_taglich_kwh
    utilities_page01_group05_line_inverted: true
    utilities_page01_group06_label: Wasser
    utilities_page01_group06_icon: mdi:water
    utilities_page01_group06_value1: sensor.wasserverbrauch_taglich
    utilities_page01_group06_color:
      - 2
      - 107
      - 187
    utilities_page01_group06_line_reference: sensor.wasserverbrauch_taglich
    utilities_page01_group06_line_inverted: false
    home_button08_icon_color:
      - 251
      - 148
      - 4
    utilities_page_cursor_width: 255
    hw_buttons_bar_color_on:
      - 240
      - 27
      - 117
    hw_buttons_bar_color_off:
      - 41
      - 105
      - 255
    chip01_inverted: true
    climate_button08_icon_color:
      - 199
      - 199
      - 199
    timezone: Europe/Berlin (CET-1CEST,M3.5.0,M10.5.0/3)
    home_custom_button07_icon: ""
    entity28: script.alexa_kuche_absolut_relax
    entity28_name: Absolut Relax
    entity28_confirm: false
    entities_entity31: binary_sensor.zirkulationspumpenbetrieb
    entities_entity31_name: Zirkulationspumpenbetrieb WW
    entities_entity31_icon: mdi:pump
    home_custom_button05_icon: mdi:shield-home-outline
    home_custom_button05_name: Alarmanlage
    relay_1_local_fallback: true
    entity27_confirm: false
    left_button_state_entity: switch.kuche_licht_total
    right_button_state_entity: input_boolean.kuche_klima_hilfsschalter
    entity27: script.alexa_kuche_energy_top_40
    entity27_name: Energy Top 40
    hw_button_bar_right_always_show: false
    hw_button_bar_left_always_show: false
    relay_2_local_fallback: true
    entity09_confirm: true
    entity10: cover.kuche_rolllade_klein
    entity10_name: Rollladen klein
    entity10_confirm: true
    entity18: switch.kuche_licht_essen
    entity18_name: Tisch
    entity25: media_player.alexa_kuche
    entity25_name: Alexa
    entity26: media_player.spotify_mr
    entity26_name: Spotify
    entity29: script.alexa_kuche_energy_nrw
    entity29_name: Energy NRW
    entity30: script.alexa_kuche_antenne_niederrhein
    entity30_name: ANTENNE Niederrhein
    climate_value03: number.heizkreis_1_raumsolltemperatur_tag
    climate_value03_icon_color:
      - 10
      - 240
      - 10
    climate_value03_label_color:
      - 10
      - 240
      - 10
    climate_value04: sensor.hk1_vorlaufisttemperatur
    entity04: climate.versatile_thermostat_klima_kuche
    entity04_name: Klima
    entity06: input_boolean.eco_kuche_mode_18
    entity06_name: ECO
    entity20: switch.kuche_licht_fenster
    entity20_name: Fenster
    chip06: input_boolean.buro_abwesenheit
    chip05_inverted: false
    chip02_inverted: false
    chip04_inverted: false
    chip06_inverted: false
    chip07_inverted: false
    chip03_inverted: false
    left_button_hold_custom_action: []
    custom_buttons_font_size: "8"
    home_custom_button05: alarm_control_panel.home_alarm
    home_custom_button06: input_boolean.buro_abwesenheit
    home_custom_button06_icon: mdi:microsoft-office
    home_custom_button06_name: Büro Abwesenheit
    entitypages_show_entities_icons: true
```

**Comment by JeroenvanA** [comment]
Hello all, i thought it was me... I'm experiencing the same issue. My climate entity in the chips section is not showing a climate icon but instead it's showing the Home page - Custom button 3 - Icon.  The climate entity icon in the chip section changes when i change the Home page - Custom button 3 - Icon. 


Version Blueprint: 2025102
Version ESPHome: 2025102
Version TFT: 2025102
No Add-ons 
Couldnt find anthing in the blueprints.

```yaml
alias: 🎛⏰️ NSPanel configuratie
description: >-
  Configuratie voor het NSPanel via de Blackymas blueprint, inclusief weer,
  temperaturen, sensoren, knoppen en personen tracking.
use_blueprint:
  path: Blackymas/nspanel_blueprint.yaml
  input:
    nspanel_name: 015ca637cf8c002f62e12b75cd534fcf
    language: nl
    date_format: "%A %-d-%-m"
    timezone: Europe/Amsterdam (CET-1CEST,M3.5.0,M10.5.0/3)
    decimal_separator: ","
    weather_entity: weather.knmi_thuis
    outdoortemp: sensor.knmi_temperatuur
    indoortemp: sensor.thermostaat_temperature
    home_indoor_temp_icon: mdi:home-thermometer
    climate: climate.thermostaat
    climate_chip_always_visible: true
    hw_button_bar_left_always_show: true
    hw_button_bar_right_always_show: true
    screensaver_display_time: true
    screensaver_display_time_font_size: "12"
    home_value01: sensor.temperatuur_sensor_slaapkamer_temperature
    home_value01_icon: mdi:bed-king-outline
    home_value02: sensor.temperatuur_sensor_slaapkamer_fay_temperature
    home_value02_icon: mdi:bed-double-outline
    home_value03: sensor.temperatuur_sensor_slaapkamer_ian_temperature
    home_value03_icon: mdi:bed-single-outline
    chip01: light.badkamer_spots
    chip01_icon: mdi:shower
    chip02: binary_sensor.beweging_op_trap
    chip02_icon: mdi:stairs
    chip03: event.sonoff_nspanelpro_proximity
    chip03_icon: mdi:alarm-panel-outline
    chip04: binary_sensor.aanwezigheidssensor_occupancy
    chip04_icon: mdi:countertop
    chip05: binary_sensor.camera_tuin_beweging
    chip05_icon: mdi:cctv
    chip06: binary_sensor.video_deurbel_beweging
    chip06_icon: mdi:doorbell-video
    chip_font_size: "8"
    home_custom_button01: light.lampen_woonkamer
    home_custom_button01_icon: mdi:lamps
    home_custom_button01_name: Lampen woonkamer
    home_custom_button02: light.buitenlampen
    home_custom_button02_icon: mdi:outdoor-lamp
    home_custom_button02_name: Buitenlampen
    home_custom_button03: light.sfeer_lampjes_onder_overkapping
    home_custom_button03_icon: mdi:string-lights
    home_custom_button03_name: Sfeer lampjes onder de overkapping
    entity_page01_label: Jeroen
    entities_entity01: person.jeroen
    entity_page02_label: Veronique
    entities_entity09: person.veronique
    entities_entity02: sensor.telefoon_jeroen_next_alarm
    entities_entity02_name: Volgend alarm
    entities_entity02_icon: mdi:alarm
    entities_entity10: sensor.telefoon_veronique_next_alarm
    entities_entity10_name: Volgend alarm
    entities_entity10_icon: mdi:alarm
    chip01_icon_color:
      - 255
      - 0
      - 0
    chip02_icon_color:
      - 255
      - 0
      - 0
    chip03_icon_color:
      - 255
      - 0
      - 0
    chip04_icon_color:
      - 255
      - 0
      - 0
    chip05_icon_color:
      - 255
      - 0
      - 0
    chip06_icon_color:
      - 255
      - 0
      - 0
    chip07_icon_color:
      - 255
      - 0
      - 0
    home_outdoor_temp_label_color:
      - 255
      - 247
      - 0
    screensaver_display_time_font_color:
      - 255
      - 0
      - 0
    time_label_color:
      - 255
      - 255
      - 255
    date_label_color:
      - 255
      - 255
      - 255
    hw_buttons_bar_color_off:
      - 0
      - 0
      - 255
    hw_buttons_bar_color_on:
      - 255
      - 255
      - 0
    icon_color_fallback_on:
      - 255
      - 255
      - 0
    button_pages_icon_size: "10"
    home_value04: person.veronique
    home_value04_label_color:
      - 0
      - 255
      - 0
    home_value04_icon_color:
      - 0
      - 255
      - 0
    home_outdoor_temp_font: "5"
    chip07: binary_sensor.camera_overkapping_persoon
    chip07_icon: mdi:barn
    sun_entity: sun.sun
    home_indoor_temp_icon_color:
      - 0
      - 0
      - 255
    right_button_entity: light.badkamer_spots
    right_button_name: Badkamer/alles
    climate_button08_icon: mdi:thermostat
    screensaver_background_color:
      - 255
      - 255
      - 255
    media_player_update_interval: 5000
    media_player_update_delay: 500
    delay: 10
    delay_boot: 250
    domain_automation_button_action: toggle
    home_button04_icon: mdi:email
    home_button04_icon_color01:
      - 255
      - 255
      - 255
    home_button04_icon_color02:
      - 255
      - 0
      - 0
    utilities_enabled: false
    right_button_hold_custom_action:
      - action: light.turn_off
        metadata: {}
        data: {}
        target:
          label_id:
            - buitenlamp
            - binnenlampen
    climate_button09_icon: mdi:thermostat
    climate_value01_icon: mdi:thermostat
    climate_value03_icon: mdi:thermostat
    climate_value04_icon: mdi:thermostat
    climate_value02_icon: mdi:thermostat
    chip01_inverted: false
    chip02_inverted: false
    chip03_inverted: false
    chip04_inverted: false
    chip07_inverted: false
    home_indoor_temp_visible: true
```

[trace automation.nspanel 2025-11-12T15_23_04.575565+00_00.json](https://github.com/user-attachments/files/23503766/trace.automation.nspanel.2025-11-12T15_23_04.575565%2B00_00.json)
