### ISSUE TITLE
`Bug` Blank display and not connecting to HA after restart

### ISSUE THREAD

**Issue by sorenjacobi** [Blackymas/NSPanel_HA_Blueprint#2531]
### TFT Version

4.3.12

### Firmware Version

2025.4.1

### Blueprint Version

4.3.12

### Panel Model

EU

### What is the bug?

After reboot, the panel has a blank screen, and no connection to Home Assistant. It is online in ESPHome Device Builder, I can check the log and I can install it again, but that seems to be all I can do. 

If I install it again, the install runs fine (with some warnings) and after install, the UI loads and everything seems to work: connection to HA is established, and I can adjust brightness, update TFT and stuff. But after a reboot, the device becomes unavailable in Home Assistant, and the screen is blank. 

Install log: [logs_nspanel_run-5.txt](https://github.com/user-attachments/files/20037319/logs_nspanel_run-5.txt)

Reboot log: [logs_nspanel_logs.txt](https://github.com/user-attachments/files/20037475/logs_nspanel_logs.txt) (Reboot happens at the bottom)

 

### Your Panel's YAML

```yaml
substitutions:
  # Settings - Editable values
  device_name: "nspanel"
  friendly_name: "nspanel"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  ota_password: !secret ota_password


  nextion_update_url: "http://homeassistant.local:8123/local/nspanel_eu.tft"  # Optional
  # Add-on configuration (if needed)
  # heater_relay: "1"  # Possible values: "1" or "2"

# Customization area
##### My customization - Start #####

api:
  encryption:
    key: !secret api_key

captive_portal:

switch:
  # Exposes display power switch
  - id: !extend screen_power
    internal: false

##### My customization - End #####

# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    refresh: 300s
    files:
      - nspanel_esphome.yaml # Basic package
      # Optional advanced and add-on configurations
      # - esphome/nspanel_esphome_advanced.yaml
      # - esphome/nspanel_esphome_addon_ble_tracker.yaml
      # - esphome/nspanel_esphome_addon_bluetooth_proxy.yaml
      # - esphome/nspanel_esphome_addon_climate_cool.yaml
      # - esphome/nspanel_esphome_addon_climate_heat.yaml
      # - esphome/nspanel_esphome_addon_climate_dual.yaml
      # - esphome/nspanel_esphome_addon_cover.yaml
esp32:
  framework:
    type: esp-idf
```
