### ISSUE TITLE
Relay Turns On But Not Off

### ISSUE THREAD

**Issue by JS1Dev** [Blackymas/NSPanel_HA_Blueprint#2537]
### TFT Version

4.3.12

### Firmware Version

4.3.12 (ESPHome 2025.4.2)

### Blueprint Version

4.3.12

### Panel Model

US (Landscape)

### What is the bug?

Using the panel or thermostat Web UI won't trigger relay to STOP cooling/AC - though it initially trigger the relay to START.  i.e. the relay turns on but not off

### Steps to Reproduce

 Initialize ("manually" switch the relay off)
- settings->devices & services->esphome->select the panel, make sure the Relay 1 toggle is off
  - NOTE: Toggling on/off from here always reliably successfully triggers the relay

Reproduce - also see [this video](https://photos.app.goo.gl/fFsmC2AQerVhwHov5) demoing the following
1. Using either the panel directly or via the Web UI thermostat, set to a low/cool enough temperature to trigger cooling/AC -> notice a click (which is the relay) and the cooling/AC successfully turns on (good)
2. Using either the panel directly or via the Web UI thermostat, set to a high/warm enough to turn the AC off, visually the Web and panel UI looks like it's turning the AC off (also good), but the relay never clicks and triggers to actually turn the AC off (bad)

At this point
- Setting the temperature low or high enough never triggers the relay to turn the AC on or off (no relay click sound) although visually the Web and panel UI looks like it's turning the AC on/off

Additional notes
- As mentioned, "manually" toggling the relay on/off consistently successfully triggers the relay on/off - see above initialize steps for details
- I have 3 NSPanels (all with **4.3.12** for TFT, Firmware, Blueprint) and they all exhibit this same exact behavior
- The below panel .yaml refer to the following which were downloaded and uploaded to the www folder today "nspanel_us_land.tft" & "nspanel_blank.tft.tft"
- I also successfully reinstalled (using what's specified below for my panel's YAML): ESPHome->click the 3 dots for my NSPanel->Install 
  - I do this because I need to switch from heating to cooling, as my furnace supports both and it doesn't seem that there's a way to switch back and forth without reinstalling, which is what I think this issue is: https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/2237
- Below is what the panel shows when rebooting (notice 4.3.12 for TFT, Firmware, Blueprint), but also see below how device info shows Hardware 4.3.11 (settings->devices & services->esphome->select the panel)
  - ![Image](https://github.com/user-attachments/assets/2f1b0d9b-dbd7-4243-93e0-5e0d40e3d057)
  - ![Image](https://github.com/user-attachments/assets/28183112-c3c0-408e-8312-52a1c306b091)
- Using Home Assistant Core (docker container): 2025.5.2; Frontend: 20250516.0 (though I also have access to it via HA OS if I boot up an older server)
  - ![Image](https://github.com/user-attachments/assets/5fe2b49d-abb2-42a9-94a5-7b0e06aab147)

### Your Panel's YAML

```yaml
substitutions:
  ###### CHANGE ME START ######
  device_name: "nspkitchen"
  friendly_name: Kitchen Thermostat
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: "http://homeassistant.local:8123/local/nspanel_us_land.tft"
  nextion_blank_url: "http://homeassistant.local:8123/local/nspanel_blank.tft.tft"

  ##### addon-configuration #####
  ## addon_climate ##

  cooler_relay: "1" #Use relay 1
  #->heater_relay: "1" #Use relay 1

#  temp_units: "°C" #Temperatures in Fahrenheit
#  temp_min: "4.44" #Min supported temperature is 40°F
#  temp_max: "26.66" #Max supported temperature is 80°F
#  temp_step: ".5" #Temperature granularity is 1°F
#  min_off_time: "1"
#  min_run_time: "1"
#  min_idle_time: "0"

  temp_units: "°F" #Temperatures in Fahrenheit "°C"
  temp_min: "40" #Min supported temperature
  temp_max: "85" #Max supported temperature
  temp_step: "1" #Temperature granularity is 1°F
  min_off_time: "1"
  min_run_time: "1"
  min_idle_time: "0"
  target_low: "40"
  target_high: "75"
  #addon_climate_heater_relay: "1" 
  # possible values: 1/2

  ##### CHANGE ME END #####

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      #->nspanel_esphome_addon_climate_heat.yaml # activate for local climate (heater) control
      - nspanel_esphome_addon_climate_cool.yaml # activate for local climate (cooling) control
      #- advanced/esphome/nspanel_esphome_advanced.yaml # activate advanced (legacy) elements - can be useful for troubleshooting
    refresh: 300s #300s #1s

esp32:
  framework:
    type: esp-idf

# - This will expose a "Factory Reset" button to Home Assistant, which will basically restore your NSPanel to use on y what is set in the yaml, cleaning its whole settings saved in flash.
# - See: https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/1678#issuecomment-1903375436
#button:
#  - platform: factory_reset
#    name: Restart with Factory Default Settings
#    internal: false

##### My customization - Start #####
# Encrypt the communication between ESPHome and Home Assistant
#api:
#  encryption:
#    key: !secret api_encryption_key_nsp2ndfloor
# More detailed log (for troubleshooting only)
#logger:
#  level: VERBOSE
climate:
  - id: !extend thermostat_embedded
    default_preset: eco
    on_boot_restore_from: memory #default_preset

    #->heat_deadband: 1 # turn on differential (.5 °C; 1 °F)
    #->heat_overrun: 1 # turn off differential / idle (.5 °C; 1 °F)
    cool_deadband: 1 # turn on differential (.5 °C; 1 °F)
    cool_overrun: 1 # turn off differential / idle (.5 °C; 1 °F)

    preset:
      - name: sleep
        #->default_target_temperature_low: 55 °F #55 °F; 12.7 °C
        #->mode: "heat"
        default_target_temperature_high: 72 °F #55 °F; 12.7 °C
        mode: "cool"
      - name: eco
        #->default_target_temperature_low: 60 °F #60 °F; 15.5 °C
        #->mode: "heat"
        default_target_temperature_high: 76 °F #55 °F; 12.7 °C
        mode: "cool" #heat_cool
      - name: comfort
        #->default_target_temperature_low: 64 °F #64 °F; 17.7 °C
        #->mode: "heat"
        default_target_temperature_high: 74 °F #55 °F; 12.7 °C
        mode: "cool"
      - name: away
        #->default_target_temperature_low: 55 °F #55 °F; 12.7 °C
        #->mode: "heat"
        default_target_temperature_high: 79 °F #55 °F; 12.7 °C
        mode: "cool"

#      - name: "off"
#        default_target_temperature_low: 40 °F #40 °F; 4.44 °C
#        mode: "off"
# https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/1418
#    visual:
#      min_temperature: 40 °F
#      max_temperature: 80 °F
#      temperature_step:
#        target_temperature: 1
#        current_temperature: 0.1
#
#sensor:
#  - id: !extend temp_nspanel
#    unit_of_measurement: "°F"
#    filters:
#      - lambda: |-
#          return (x * (9.0/5.0)) + 32.0 + temperature_correction->state;
#
#number:
#  - id: !extend temperature_correction
#    unit_of_measurement: "°F"
##### My customization - End #####
```

### ESPHome Logs

NOTE: This log represents the same steps from [this video](https://photos.app.goo.gl/fFsmC2AQerVhwHov5) demoing the issue except
- They were done via the HA UI (on my phone), vs the physical NSPanel
- Additionally (at the end), I "manually" switch the relay off
  - settings->devices & services->esphome->select the panel, toggled Relay 1 to off
[logs_nspkitchen_logs.txt](https://github.com/user-attachments/files/20274860/logs_nspkitchen_logs.txt)

### Home Assistant Logs

[home-assistant_2025-05-18T20-31-33.301Z.log](https://github.com/user-attachments/files/20274890/home-assistant_2025-05-18T20-31-33.301Z.log)
