### ISSUE TITLE
wake-up page issue

### ISSUE THREAD

**Issue by bhuebschen** [Blackymas/NSPanel_HA_Blueprint#2538]
### TFT Version

4.3.12

### Firmware Version

4.3.12

### Blueprint Version

4.3.12

### Panel Model

EU

### What is the bug?

i'm using it as thermostate for the floor water heater in the room i've installed it.

Due to my wife wants to control the climate-settings, i changed the wake-up page in the esphome-settings page of the nspanel to "climate".

unfortunately, it looks like the climate-page as wake-up page does not have the climate entity assigned and any changes on the page will have no effect

### Steps to Reproduce

<img width="346" alt="Image" src="https://github.com/user-attachments/assets/db1c8219-f962-46a4-8d82-7bfa0645c6d4" />

### Your Panel's YAML

```yaml
substitutions:
  device_name: "ezthermostate"
  friendly_name: "Esszimmer Thermostat"
  wifi_ssid: !secret home_ssid
  wifi_password: !secret home_password
  nextion_update_url: "http://10.10.0.9:8123/local/nspanel_eu.tft" # URL to local tft File
  heater_relay: "1"
  temp_min: "15" 
  temp_max: "25" 
  temp_step: "0.5"

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    refresh: 300s
    files:
      - nspanel_esphome.yaml # Basic package
      - esphome/nspanel_esphome_addon_climate_heat.yaml
```
