### ISSUE TITLE
`Bug` ERROR Unable to import component logger:

### ISSUE THREAD

**Issue by LeendertvdHoek** [Blackymas/NSPanel_HA_Blueprint#2557]
### TFT Version

4.3.12

### Firmware Version

4.3.12

### Blueprint Version

4.3.14

### Panel Model

EU

### What is the bug?

I Have 8 nspanels that all have the same failure when I try to Update to 4.3.13:

INFO ESPHome 2025.5.2
INFO Reading configuration /config/esphome/nswoonkamer.yaml...
INFO Updating https://github.com/Blackymas/NSPanel_HA_Blueprint@v4.3.14
ERROR Unable to import component logger:
Traceback (most recent call last):
  File "/esphome/esphome/loader.py", line 185, in _lookup_module
    module = importlib.import_module(f"esphome.components.{domain}")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/data/external_components/ab7a46ec/esphome/components/logger/__init__.py", line 7, in <module>
    from esphome.components.esp32.const import (
ImportError: cannot import name 'VARIANT_ESP32C5' from 'esphome.components.esp32.const' (/esphome/esphome/components/esp32/const.py)
Failed config

logger: [source /data/packages/566b10a3/esphome/nspanel_esphome_core.yaml:153]
  
  Component not found: logger.
  id: logger_std
  baud_rate: 0

### Steps to Reproduce

Go to ESPHome, select a panel and click update -> Wirelessly

### Your Panel's YAML

```yaml
substitutions:
  # Settings - Editable values
  device_name: nswoonkamer
  #friendly_name: "ns woonkamer"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  # nextion_update_url: "http://homeassistant.local:8123/local/nspanel_eu.tft"  # Optional
  
  # Add-on configuration (if needed)
  # heater_relay: "1"  # Possible values: "1" or "2"


# Begin Customization Section
##### Customization - Start #####
## If you wanna set non-standard parameters to your Bluetooth proxy just add like this:
# esp32_ble_tracker:
#   scan_parameters:
#     interval: 1100ms
#     window: 1100ms
#     active: true
#
# bluetooth_proxy:
#   active: true
##### Customization - End #####

# Package Configuration
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    refresh: 300s
    files:
      - nspanel_esphome.yaml # Basic NSPanel package
      # Optional packages for advanced features and other add-ons
      # - esphome/nspanel_esphome_addon_ble_tracker.yaml
      - esphome/nspanel_esphome_addon_bluetooth_proxy.yaml # Bluetooth Proxy add-on package
      # - esphome/nspanel_esphome_addon_climate_cool.yaml
      # - esphome/nspanel_esphome_addon_climate_heat.yaml
      # - esphome/nspanel_esphome_addon_climate_dual.yaml
      # - esphome/nspanel_esphome_addon_cover.yaml
      
esp32:
  framework:
    type: esp-idf
```
