### ISSUE TITLE
`Enhancement` Tempest WeatherFlow Forecast is not working

### ISSUE THREAD

**Issue by lightingman117** [Blackymas/NSPanel_HA_Blueprint#2579]
### Enhancement Summary

Add support for Tempest Weather Forecast

### Detailed Description

Related to #2450 I think

The Tempest weather forecasting is better and I would prefer it.

```
Version Blueprint - 4.3.15
Version ESPHome - 4.3.15
Version TFT - 4.3.15
```

```
alias: NSPanel Config - Attempt 1
description: ""
use_blueprint:
  path: Blackymas/nspanel_blueprint.yaml
  input:
    nspanel_name: 7c60c3adeb88d1786046c7183b5afbbf
    date_format: "%A, %-m/%-d"
    time_format: "%-I:%M %p"
    timezone: America/Chicago (CST6CDT,M3.2.0,M11.1.0)
    decimal_separator: .
    weather_entity: weather.home
    outdoortemp: sensor.home_temperature
    indoortemp: sensor.temp_sensors_tmp117_temperature
    climate: climate.thermostat
    entity01: light.shellyrgbw2_48e72965c000
    climate_chip_always_visible: true
    entity02: input_button.mbath_fan_automation
    entity04: switch.office_flood_s31_s31_relay
    entity03: switch.office_flood_2_s31_s31_relay
    entity07_confirm: true
    entity08_confirm: true
    utilities_enabled: true
    utilities_page01_home_value1: sensor.shellyem3_c8c9a316d210_channel_a_power
    utilities_page01_home_value2: sensor.shellyem3_c8c9a316d210_channel_b_power
    left_button_entity: script.new_script
    right_button_entity: light.shellyrgbw2_48e72965c000
    delay: 15
    domain_automation_button_action: trigger
```

[not-working_trace automation.nspanel_config_attempt_1 2025-06-07T02_24_24.159063+00_00.json](https://github.com/user-attachments/files/20636588/not-working_trace.automation.nspanel_config_attempt_1.2025-06-07T02_24_24.159063%2B00_00.json)

### Additional Context

Working (Met.no):
![Image](https://github.com/user-attachments/assets/787cdaaf-e124-4166-9c54-1393afc208d6)

Not working(WeatherflowCloud):
![Image](https://github.com/user-attachments/assets/7354b007-147e-4e8f-b388-e8f24f4b7aee)

https://www.home-assistant.io/integrations/weatherflow/
