### ISSUE TITLE
`Enhancement` [4.4.0] Decrease generated file size

### ISSUE THREAD

**Issue by sztupy** [Blackymas/NSPanel_HA_Blueprint#2585]
### Enhancement Summary

Decrease generated file size

### Detailed Description

4.4.0.dev10 generated binaries are much larger than the 4.3.x variants to the point where they don't fit in the.

E.g.
```yaml
logger:
  level: DEBUG
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    refresh: 300s
    files:
      - nspanel_esphome.yaml
      - esphome/nspanel_esphome_addon_ble_tracker.yaml
      - esphome/nspanel_esphome_addon_bluetooth_proxy.yaml
      - esphome/nspanel_esphome_addon_climate_heat.yaml
```

this fits easily into the OTA limits, being `1776561` bytes large

However the corresponding 4.4.0 version:

```yaml
logger:
  level: DEBUG
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: v4.4.0.dev10
    refresh: 300s
    files:
      - esphome/nspanel_esphome_core.yaml
      - esphome/nspanel_esphome_standard.yaml
      - esphome/nspanel_esphome_addon_ble_tracker.yaml
      - esphome/nspanel_esphome_addon_bluetooth_proxy.yaml
      - esphome/nspanel_esphome_addon_climate_heat.yaml
```

takes up `1834405` which is slightly larger than what OTA allows. I have to split out the `standard` packages removing almost everything to get back to the same size as before, negating the benefit of being able to only build what I need

**Comment by edwardtfn** [comment]
For reference, I've just tried this (with ESPHome 2025.6.0b1) with both v4.3.15 and the latest v4.4.0.dev10:
```yaml
substitutions:
  # Settings - Editable values
  device_name: "nspanel-2585"
  friendly_name: "NSPanel issue 2585"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  nextion_update_url: "http://homeassistant.local:8123/local/nspanel_eu.tft"  # Optional
  # Add-on configuration (if needed)
  heater_relay: "2"  # Possible values: "1" or "2"

# Customization area
##### My customization - Start #####
##### My customization - End #####

# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    refresh: 30s
    files:
      - nspanel_esphome.yaml # Basic package
      # Optional advanced and add-on configurations
      # - esphome/nspanel_esphome_advanced.yaml
      - esphome/nspanel_esphome_addon_ble_tracker.yaml
      - esphome/nspanel_esphome_addon_bluetooth_proxy.yaml
      # - esphome/nspanel_esphome_addon_climate_cool.yaml
      - esphome/nspanel_esphome_addon_climate_heat.yaml
      # - esphome/nspanel_esphome_addon_climate_dual.yaml
      # - esphome/nspanel_esphome_addon_cover.yaml
```

## Results

### v4.3.15
```log
RAM:   [=         ]  11.1% (used 36252 bytes from 327680 bytes)
Flash: [========= ]  92.2% (used 1691040 bytes from 1835008 bytes)
```
Please note that my test is taking less flash than your panel, probably thanks to the memory optimization introduced to ESPHome 2025.6.0b1... or do you have any customization?

### v4.4.0.dev10 (from 2025-06-11 23:29 UTC)
```log
RAM:   [==        ]  16.5% (used 54028 bytes from 327680 bytes)
Flash: [==========]  95.2% (used 1747460 bytes from 1835008 bytes)
```

I will see what else I can do to optimize v4.4.0.dev.
