### ISSUE TITLE
System Data ERROR! Persistant

### ISSUE THREAD

**Issue by Let000** [Blackymas/NSPanel_HA_Blueprint#2587]
### TFT Version

lui-release.tft

### Firmware Version

2025.7.0-dev

### Panel Model

EU

### What is the bug?

Bonjour, j'ai déjà deux panneaux qui fonctionnent parfaitement. Mais avec exactement la même configuration pour le nouveau,  le Nextion pose problème. Tout semble ok niveau code, mais ça semble tourner en boucle, sans déroulement de la mise à jour TFT, l'écran s'éteint et s'allume en boucle.
J'ai flasher 3 fois déjà, suivi le wiki et rien n'y fait toujours la même erreur :/ 
Merci d'avance de votre aide 

![Image](https://github.com/user-attachments/assets/a1275a48-1e07-41bd-9992-bf2e2c0db9bc)
![Image](https://github.com/user-attachments/assets/dbd66ddd-e47f-43c0-9637-e3c7846a2d97)

### Steps to Reproduce

[logs_panel_run.txt](https://github.com/user-attachments/files/20705235/logs_panel_run.txt)

### Your Panel's YAML

```yaml
Substitutions : # Paramètres - Valeurs modifiables nom_du dispositif : "panel" friendly_name : "panel" wifi_ssid : secret mot de passe wifi : secret nextion_update_url : "http://homelsg.local:8123/homeassistant/local/nspanel_eu.tft" # Facultatif # Configuration du module complémentaire (si nécessaire) # relais_de chauffage : "1" # Valeurs possibles : "1" ou "2" # Zone de personnalisation ##### Ma personnalisation - Démarrer ##### ##### Ma personnalisation - Fin ##### # Configurations de base et optionnelles Paquets : Paquet_à distance : URL : https://github.com/Blackymas/NSPanel_HA_Blueprint Réf : principal Rafraîchissement : 300s Fichiers : - nspanel_esphome.yaml # Forfait de base # Configurations avancées et complémentaires facultatives # - esphome/nspanel_esphome_advanced.yaml # - esphome/nspanel_esphome_addon_climate_cool.yaml # - esphome/nspanel_esphome_addon_climate_heat.yaml # - esphome/nspanel_esphome_addon_climate_dual.yaml # - esphome/nspanel_esphome_addon_cover.yamlesphome :
```

**Comment by edwardtfn** [comment]
Please try adding this to your panel's yaml and let me know if that helps:

```yaml
esphome:
  on_shutdown: !remove
```

**Comment by edwardtfn** [comment]
There is a discussion around this on ESPHome Discord (beta channel) and looks like I will have to release a patch for users upgrading to ESPHome 2025.6.0 or later.

- https://discord.com/channels/429907082951524364/1382496793442648176

**Comment by edwardtfn** [comment]
I just put a PR to ESPHome to handle this issue in a different way, so that remove of `on_shutdown` wouldn't be needed anymore:

- esphome/esphome#9064

It was already approved and assigned to beta 2. Hopefully will be available on `dev` in the next build (in the coming hours) and in the following beta release so, when you update your ESPHome builder, please remove any of the customization I've suggested above.

**Comment by Let000** [comment]
```yaml
substitutions:
  # Settings - Editable values
  device_name: "control"
  friendly_name: "control"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  nextion_update_url: "http://homeassistant.local:8123/local/lui-release.tft"  # Optional
  # Add-on configuration (if needed)
  # heater_relay: "1"  # Possible values: "1" or "2"
esphome:
  on_shutdown: !remove
  
# Customization area
##### My customization - Start #####
##### My customization - End #####

# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    refresh: 300s
    files:
      - nspanel_esphome.yaml # Basic package
      # Optional advanced and add-on configurations
      # - esphome/nspanel_esphome_advanced.yaml
      # - esphome/nspanel_esphome_addon_ble_tracker.yaml
      # - esphome/nspanel_esphome_addon_bluetooth_proxy.yaml
      # - esphome/nspanel_esphome_addon_climate_cool.yaml
      - esphome/nspanel_esphome_addon_climate_heat.yaml
      # - esphome/nspanel_esphome_addon_climate_dual.yaml
      # - esphome/nspanel_esphome_addon_cover.yaml
```
Bonjour, merci mais on_shutdown n'apparait pas dans mon appareil (peut être l'ai je mal inclus ou recherché), Maj esphome 2025.7.0-dev et je n'accède pas au Discord 

![Image](https://github.com/user-attachments/assets/358b584f-4ec2-41f6-b869-c70ff25d3365)
