### ISSUE TITLE
`Bug` AC Climate control shows as Unavailable

### ISSUE THREAD

**Issue by wojciechczyz** [Blackymas/NSPanel_HA_Blueprint#2595]
### TFT Version

4.3.15

### Firmware Version

4.3.15

### Blueprint Version

4.3.15

### Panel Model

None

### What is the bug?

Even when working, it is always shown as Unavailable

### Your Panel's YAML

```yaml

```

**Comment by edwardtfn** [comment]
Could you please share your panel's yaml? Please remove any sensitive info before sharing. 😉

**Comment by wojciechczyz** [comment]
I looked at another installation and understand what is going on. The AC Climate entity is remote smartIR AC controllet that does not know the current temperature. This "Unknown" is temperature sensor which indeed has no value.
How can I show the current temperature of the nspanel instead? Thank you!

**Comment by Xferno2** [comment]
Hello, as someone who uses smarir as well you have to define the temp sensor in the smart ir template. You can use the sensor from the ns panel.
```
climate:
  - platform: smartir
    name: Bedroom AC
    unique_id: bedroom_ac
    device_code: 11819
    controller_data:
      controller_type: Broadlink
      remote_entity: remote.rm4c_mini
      delay_secs: 0.5
      num_repeats: 1
    temperature_sensor: sensor.average_temp_bedroom
    humidity_sensor: sensor.sonoff_temperature_humidity
    power_sensor: binary_sensor.ac_running`
```
