### ISSUE TITLE
`Bug` Issue updating TFT to 4.3.16

### ISSUE THREAD

**Issue by petikeje** [Blackymas/NSPanel_HA_Blueprint#2611]
### TFT Version

currently not available (last 4.3.15)

### Firmware Version

2025.6.0 Jun 19 2025, 04:37:42

### Blueprint Version

4.3.16

### Panel Model

EU

### What is the bug?

After updating the blueprint and the firmware to 4.3.16 from 4.3.15 the update of TFT is not possible.
Based on the logs the Nextion dispaly is not connected.
The display show the following screen:

![Image](https://github.com/user-attachments/assets/1be5b937-b63b-4bb1-83ee-2bd6432bb08d)

Tried to update tft after clean build and with baud rate 115200 with no success.
Other wierd thing: nextion_update_url is defined in yaml as local url but tft update tries to dowload https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/v4.3.16/hmi/nspanel_eu.tft

The nspanel thermostat seems OK in Home Assistant instance.

### Steps to Reproduce

Nextion not connected, the display shows a boot screen

### Your Panel's YAML

```yaml
substitutions:

###### CHANGE ME START ######

  device_name: "nspanel"
  friendly_name: NSPanel
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

#  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft" # URL to Github
  nextion_update_url: "http://192.168.1.182:8123/local/tft/nspanel_eu.tft"

##### CHANGE ME END #####

  heater_relay: "1"

##### DO NOT CHANGE ANYTHING! #####

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      - esphome/nspanel_esphome_advanced.yaml
      - esphome/nspanel_esphome_addon_climate_heat.yaml # activate for local climate (heater) control
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####

# Set Nextion comms baud rate to 921600 bps
uart:
  - id: !extend tf_uart
    baud_rate: 921600

api:
  on_client_disconnected:
    - climate.control:
        id: thermostat_embedded
        #mode: auto
        target_temperature: 22°

  on_client_connected:
    - climate.control:
        id: thermostat_embedded
        mode: AUTO
```

### ESPHome Logs

[logs_nspanel_logs.txt](https://github.com/user-attachments/files/20847448/logs_nspanel_logs.txt)

### Home Assistant Logs

Can't find any relevant logs.

**Comment by edwardtfn** [comment]
The problem is your ESPHome not detecting the display, which is expecting communication at 115200 bps.

Please try removing this from your yaml:
```yaml
uart:
  - id: !extend tf_uart
    baud_rate: 921600
```
Also, please make sure in your device's page (Settings > Devices & Services > ESPHome) you have "**Baud rate**" set to 115200 bps.
