### ISSUE TITLE
`Bug` fail to switch to button page

### ISSUE THREAD

**Issue by deepjia** [Blackymas/NSPanel_HA_Blueprint#2612]
### TFT Version

4.3.16

### Firmware Version

4.3.16

### Blueprint Version

4.3.16

### Panel Model

EU

### What is the bug?

Occasionally, the panel fails to switch to the button page when sliding. While restarting the panel temporarily resolves the issue, it may recur after several hours.

### Steps to Reproduce

Irregular but easily reproducible, most likely to occur right after a system update, and temporarily restored after each reboot.

### Your Panel's YAML

```yaml
substitutions:
  ###### CHANGE ME START ######
  device_name: "nssr" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: "http://10.0.0.100:8123/local/nspanel_CJK_eu.tft"

  ##### addon-configuration #####
  ## addon_climate ##
  # addon_climate_heater_relay: "1" # possible values: 1/2

  ##### CHANGE ME END #####

packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files:
      - nspanel_esphome.yaml # Core package
      # - nspanel_esphome_advanced.yaml # activate advanced (legacy) elements - can be useful for troubleshooting
      # - nspanel_esphome_addon_climate_cool.yaml # activate for local climate (cooling) control
      # - nspanel_esphome_addon_climate_heat.yaml # activate for local climate (heater) control
    refresh: 300s

esp32:
  framework:
    type: esp-idf
##### My customization - Start #####
##### My customization - End #####
```

### ESPHome Logs

[01:55:33][D][nextion:520]: Touch PRESS: page 1 comp 0
[01:55:33][D][script.timer_dim:3263]: Waking up on page: home
[01:55:33][D][script:077]: Script 'timer_sleep' restarting (mode: restart)
[01:55:33][D][sensor:098]: 'Display Current brightness': Sending state 100.00000 % with 0 decimals of accuracy
[01:55:33][D][nextion:520]: Touch RELEASE: page 1 comp 0
[01:55:33][D][script:077]: Script 'timer_dim' restarting (mode: restart)
[01:55:33][D][script:077]: Script 'timer_sleep' restarting (mode: restart)
[01:55:35][D][nextion:520]: Touch PRESS: page 1 comp 0
[01:55:35][D][script:077]: Script 'timer_dim' restarting (mode: restart)
[01:55:35][D][script:077]: Script 'timer_sleep' restarting (mode: restart)
[01:55:36][D][nextion:520]: Touch RELEASE: page 1 comp 0
[01:55:36][D][script:077]: Script 'timer_dim' restarting (mode: restart)
[01:55:36][D][script:077]: Script 'timer_sleep' restarting (mode: restart)
[01:55:37][C][nspanel_ha_blueprint:2216]: Wi-Fi:         Fair (-61 dBm)
[01:55:37][C][nspanel_ha_blueprint:2227]: API:           Connected
[01:55:37][C][nspanel_ha_blueprint:2235]: Blueprint:
[01:55:37][C][nspanel_ha_blueprint:2237]:   Version:     4.3.16
[01:55:37][C][nspanel_ha_blueprint:2238]:   Init steps:  62 (100.0%)
[01:55:37][C][nspanel_ha_blueprint:2247]: ESPHome:
[01:55:37][C][nspanel_ha_blueprint:2248]:   Version:     4.3.16
[01:55:37][C][nspanel_ha_blueprint:2249]:   Compiler:    2025.6.0
[01:55:37][C][nspanel_ha_blueprint:2254]:   Framework:   ESP-IDF
[01:55:37][C][nspanel_ha_blueprint:2259]:   Free heap:
[01:55:37][C][nspanel_ha_blueprint:2262]:     Internal:   196364 bytes (57.8%)
[01:55:37][C][nspanel_ha_blueprint:2272]:     PSRAM:     1998756 bytes (95.9%)
[01:55:37][C][nspanel_ha_blueprint:2280]: UART:
[01:55:37][C][nspanel_ha_blueprint:2281]:   Baud rate:   115200 bps
[01:55:37][C][nspanel_ha_blueprint:2282]:   Queue size:  0
[01:55:37][C][nspanel_ha_blueprint:2286]: Nextion:
[01:55:37][C][nspanel_ha_blueprint:2287]:   Queue size:  0
[01:55:37][C][nspanel_ha_blueprint:2289]:   Is setup:    True
[01:55:37][C][nspanel_ha_blueprint:2296]:   Init:        True
[01:55:37][C][nspanel_ha_blueprint:2302]:   TFT:         4.3.16
[01:55:37][C][nspanel_ha_blueprint:2303]: Packages:
[01:55:37][C][nspanel_ha_blueprint:2305]:   - Core
[01:55:37][C][nspanel_ha_blueprint:2314]:   - Upload TFT
[01:55:37][C][nspanel_ha_blueprint:097]: Add-on Upload TFT:
[01:55:37][C][nspanel_ha_blueprint:098]:   File model: NSPanel EU (CJK languages)
[01:55:37][C][nspanel_ha_blueprint:099]:   Valid TFT:  YES
[01:55:37][W][component:278]: Component script took a long time for an operation (58 ms).
[01:55:37][W][component:279]: Components should block for at most 30 ms.
[01:55:42][D][sensor:098]: 'ntc_source': Sending state 1.60583 V with 2 decimals of accuracy
[01:55:42][D][resistance:042]: 'resistance_sensor' - Resistance 10616.0Ω
[01:55:42][D][sensor:098]: 'resistance_sensor': Sending state 10616.03711 Ω with 1 decimals of accuracy
[01:55:42][D][ntc:026]: 'Temperature' - Temperature: 23.7°C
[01:55:42][D][sensor:098]: 'Temperature': Sending state 23.66069 °C with 1 decimals of accuracy
[01:55:47][D][nextion:520]: Touch PRESS: page 1 comp 0
[01:55:47][D][script:077]: Script 'timer_dim' restarting (mode: restart)
[01:55:47][D][script:077]: Script 'timer_sleep' restarting (mode: restart)
[01:55:47][D][nextion:520]: Touch RELEASE: page 1 comp 0
[01:55:47][D][script:077]: Script 'timer_dim' restarting (mode: restart)
[01:55:47][D][script:077]: Script 'timer_sleep' restarting (mode: restart)
[01:55:52][D][sensor:098]: 'ntc_source': Sending state 1.60517 V with 2 decimals of accuracy
[01:55:52][D][resistance:042]: 'resistance_sensor' - Resistance 10607.5Ω
