### ISSUE TITLE
`Bug` ESPHome 2025.6.2 several reboot

### ISSUE THREAD

**Issue by synack666** [Blackymas/NSPanel_HA_Blueprint#2616]
### TFT Version

4.3.16

### Firmware Version

4.3.16

### Blueprint Version

4.3.16

### Panel Model

EU

### What is the bug?

rolling reboot after update ESPHome to 2025.6.2, back to 2025.6.1

### Your Panel's YAML

```yaml
substitutions:

###### CHANGE ME ######

  device_name: "nspanel" 
  wifi_ssid: xxxx
  wifi_password: xxxx
##### CHANGE ME #####


##### DO NOT CHANGE ANYTHING! #####

##  nextion_update_url: "http://192.168.0.171:8123/local/nspanel_eu.tft" # URL to local tft File
  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft"

packages:
  ##### download esphome code from Github
 remote_package:
  url: https://github.com/Blackymas/NSPanel_HA_Blueprint
  ref: main
  files: [nspanel_esphome.yaml]
  refresh: 300s
```

### ESPHome Logs

[logs_nspanel_run.txt](https://github.com/user-attachments/files/20972751/logs_nspanel_run.txt)
