### ISSUE TITLE
Help with updating TFT

### ISSUE THREAD

**Issue by StevenB1701** [Blackymas/NSPanel_HA_Blueprint#265]
Hi I've been able to flash esphome on my nspanel and started the tft update. However this took over 12 hours and when finished it just came up with an update failed message (System Data ERROR). Sensors from the NSP are showing in HA but all attempts to update the tft either via HA (service call) and esphome have so far failed. I have deleted blueprint and esphome (nspane) from HA and reflashed/reinstalled blueprint etc but all to no avail. Can you help? Thanks

**Comment by trunneml** [comment]
Hi, 

I had a similar problem.  I could fix the problem by downloading the `esphome_nspanel.yaml` and disable/comment  `captive_portal` and  `web_server` (lines 66-74):

```
##### TYPE OF ESP BOARD #####
esp32:
  board: esp32dev

# captive_portal:

# web_server:
#   port: 80
#   auth:
#     username: admin
#     password: ${wifi_password}
#     ##### advanced config - change to use web_password ##### 
#     # password: ${web_password}

##### OTA PASSWORD #####
ota:
  password: ${wifi_password}
```

After that I could upload the display firmware. It seems that the esp runs out of memory. I have the feeling the latest esphome Version needs more ram than the initial version where the upload was tested. Maybe some maintainer could test it or help us debugging it.

Maybe the problem is also related to  #204. Do you use HTTPS to provide the `tft` file? If so you could also try using HTTP (not HTTPS).
