### ISSUE TITLE
Why not use regexps for redundancies?

### ISSUE THREAD

**Issue by tomredhot** [Blackymas/NSPanel_HA_Blueprint#271]
Hi!
First of all THANKS A LOT @Blackymas !
Your work on this blueprint and nextion is incredible.

Like this is not perfect for my setup and my needs, I start to rework it a little (a lot)
eg : 
![IMG_20230130_122928](https://user-images.githubusercontent.com/5106847/215465528-506db04c-266c-4a7d-8c05-c1ac30e0519b.jpg)
![IMG_20230130_122916](https://user-images.githubusercontent.com/5106847/215465548-db9d3345-e6a9-4e25-a5e5-40db8a629baf.jpg)
![IMG_20230130_122949](https://user-images.githubusercontent.com/5106847/215465592-80b2ac8a-3184-4b7e-8636-1e55f9067de3.jpg)

But i'm not here for this : 
I work on a new blueprint for my needs and I see that yours has a lot of repetition. I know why, but i think some can be avoid with a little of regexp

Really small example :
Push titles on buttonpage01, buttonpage02, buttonpage03 and buttonpage04.
In your blueprint :  
```
  sequence:
      - conditions: '{{ trigger.event.data.new_state.state == page_buttonpage01 }}'
        sequence:
        - if:
          - condition: template
            value_template: '{{ button_page01_label |length > 0 }}'
          then:
          - service: '{{ command_text_printf }}'
            data:
              component: bpage01_label
              message: '{{ button_page01_label }}'
      - conditions: '{{ trigger.event.data.new_state.state == page_buttonpage02 }}'
        sequence:
        - if:
          - condition: template
            value_template: '{{ button_page02_label |length > 0 }}'
          then:
          - service: '{{ command_text_printf }}'
            data:
              component: bpage02_label
              message: '{{ button_page02_label }}'
      - conditions: '{{ trigger.event.data.new_state.state == page_buttonpage03 }}'
        sequence:
        - if:
          - condition: template
            value_template: '{{ button_page03_label |length > 0 }}'
          then:
          - service: '{{ command_text_printf }}'
            data:
              component: bpage03_label
              message: '{{ button_page03_label }}'
      - conditions: '{{ trigger.event.data.new_state.state == page_buttonpage04 }}'
        sequence:
        - if:
          - condition: template
            value_template: '{{ button_page04_label |length > 0 }}'
          then:
          - service: '{{ command_text_printf }}'
            data:
              component: bpage04_label
              message: '{{ button_page04_label }}'
```

My proposal :
```
- conditions: '{{ trigger.event.data.new_state.state is match "buttonpage" }}'  ## IF PAGE START WITH buttonpage
        sequence:
        - variables:
            actual_btn_page: '{{ trigger.event.data.new_state.state }}' ## PUT NAME IN VARIABLE
            actual_btn_page_number: '{{ actual_btn_page | regex_replace(''buttonpage0'','''') }}' ## KEEP THE NUMBER
            actual_btn_page_nextion_name_input: 'bpage0{{ actual_btn_page_number }}_label' ## NAME OF LABEL IN NEXTION
            actual_btn_page_ha_name_value: '{%- if actual_btn_page_number==1 -%} {{ button_page01_label }} {%- elif  actual_btn_page_number==2 -%} {{ button_page02_label }} {%- elif  actual_btn_page_number==3 -%} {{ button_page03_label  }} {%- endif -%}'  ## GET THE LABEL DEFINED BY THE USER
        - if:
          - condition: template
            value_template: '{{ actual_btn_page_ha_name_value |length > 0 }}'
          then:
          - service: '{{ command_text_printf }}'
            data:
              component: '{{ actual_btn_page_nextion_name_input }}'
              message: '{{ actual_btn_page_ha_name_value }}'
```

This is a really small example, & i think it can be optimized again.
And you can too use the same name in nextion for titles on every button pages ("bpage01", "bpage02" etc... became for example "bpage_title") and this will be :

```
- conditions: '{{ trigger.event.data.new_state.state is match "buttonpage" }}'  ## IF PAGE START WITH buttonpage
        sequence:
        - variables:
            actual_btn_page: '{{ trigger.event.data.new_state.state }}' ## PUT NAME IN VARIABLE
            actual_btn_page_number: '{{ actual_btn_page | regex_replace(''buttonpage0'','''') }}' ## KEEP THE NUMBER
            actual_btn_page_ha_name_value: '{%- if actual_btn_page_number==1 -%} {{ button_page01_label }} {%- elif  actual_btn_page_number==2 -%} {{ button_page02_label }} {%- elif  actual_btn_page_number==3 -%} {{ button_page03_label  }} {%- endif -%}'  ## GET THE LABEL DEFINED BY THE USER
        - if:
          - condition: template
            value_template: '{{ actual_btn_page_ha_name_value |length > 0 }}'
          then:
          - service: '{{ command_text_printf }}'
            data:
              component: 'bpage_title'
              message: '{{ actual_btn_page_ha_name_value }}'
```
So my question is : Is there a specific reason not to do this? In your plan, I mean.

I'm working on it ATM, but i think the use of regexp can be easily remove +500 lines of code (in particular with weather forecast section ).

Thanks again @Blackymas !
Have a nice day!
