### ISSUE TITLE
restart screen button

### ISSUE THREAD

**Issue by bkbartk** [Blackymas/NSPanel_HA_Blueprint#309]
would you please consider adding the following code?
```
  ##### DISPLAY ALWAYS ON #####
  - platform: gpio
    name: ${device_name} Screen Power
    id: screen_power
    entity_category: config
    pin:
      number: 4
      inverted: true
    restore_mode: ALWAYS_ON
    on_turn_off:
      - script.execute: restartScreen
    on_turn_on:
      - script.stop: restartScreen
  #   internal: true
```
```
script:
  - id: page_timer
........
  - id: restartScreen
    then:
      - delay: 3s
      - switch.turn_on: screen_power

```

It will make the scheen power button available so you can restart the screen in case it crashes, for instance during an update.

I still struggle a bit with the update part, so a reset button would be nice, I already use it but others might can benefit from it as well.

**Comment by Blackymas** [comment]
Don't really understand the question.

In the update of Esphome or TFT can not be installed button.

We have added a reboot button on the boot page and settings page

**Comment by bkbartk** [comment]
Sorry, I see ESPhome restarts the screen on reboot, tasmota doesn't do this So I was under the impression esphome wouldn't either.

**Comment by bkbartk** [comment]
Sorry, 
I would like to reopen this one.
the reboot button does not prevent from this loop
![image](https://user-images.githubusercontent.com/17070805/226937166-dfbdcf0e-3364-4676-bf2a-7172d1ca97a5.png)
for that one you need to power off the screen.

**Comment by Blackymas** [comment]
try v3.2.1

**Comment by bkbartk** [comment]
can you explain what is changed?
I noticed the tft upload works way better now, but not sure that will help with the issue.

**Comment by bkbartk** [comment]
@edwardtfn would you please consider this option again?
this will prevent people from having to power cycle which can be hard to do if the panel is in the wall.
https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-Common-Issues-TFT-Upload#6-power-cycle-your-panel
personally I add this script, and if the upload fails I can only restart the screen and give it another try,
sometimes I have to use _blank, but still I don't have to powercycle.

**Comment by edwardtfn** [comment]
We are facing a memory limit on both the ESPHome and TFT sides, so we are trying to have all of those things as customizations or Add-ons.
Do you think it could be the case for this?
If this happens just on specific situations (like when you are going to an update) maybe it should be outside and we have more memory for future features, but if this is some thing that you cannot prevent when it will be needed, then it make sense to be in the core.

**Comment by bkbartk** [comment]
That might makes things easier, 
this is only needed while the TFT update stops and you get an UART message in a loop.
there is no need for this at all when the device is up and running.

an easier solution then would be te remove 
`internal: true`
from the switch
and then in the manual describe to poweroff the screen for 10 seconds or something.
it does the same thing but manually.
and I assume an external component uses the same amount of memory as an internal one in esp home.

**Comment by edwardtfn** [comment]
> an external component uses the same amount of memory as an internal one in esp home.

It takes the same amount, but playing with add-ins enables using more memory so you can temporarily disable other add-on when enabling this one. We cannot have everything at the same time, but we can select when to have each one.

**Comment by bkbartk** [comment]
I don’t know how add ons work for this. But that could also be a solution indeed. 
I assumed. It was just enabling other stuff while compiling. But maybe it works different. 
anyway exposing the switch to ha or webinterface would work. To make it nice. The script above can be added in an addon.

**Comment by edwardtfn** [comment]
Shouldn't this be a button instead? As this is more an action than a state?
And should ESPHome also be restarted or restarting the screen power would be enough? I'm afraid if someone press this button when the screen is connected, it will cause a disconnection and the system wouldn't try to reconnect again.

So I would propose something like this:
```yaml
button:
  ##### Turn the display off for 5sec before restarting ESPHome #####
  - name: ${device_name} Restart screen power
    id: debug_restart_screen
    platform: template
    entity_category: config
    internal: false
    on_press:
      - switch.turn_off: screen_power
      - delay: 5s
      - switch.turn_on: screen_power
      - button.press: restart_nspanel
```
