### ISSUE TITLE
ESP home not able to make the bin

### ISSUE THREAD

**Issue by Peterhansel88** [Blackymas/NSPanel_HA_Blueprint#322]
The nspanel_esphome.yaml has some issue on the 53. line.
And  the ESP home not able to make de binary for the hardware.

"
INFO Reading configuration /config/esphome/nspanel.yaml...
Failed config

external_components: [source /config/esphome/.esphome/packages/566b10a3/nspanel_esphome.yaml:53]
  - [source /config/esphome/.esphome/packages/566b10a3/nspanel_esphome.yaml:53]
    
    Source is not a file system path or in expected github://username/name[@branch-or-tag] format!.
    source: github://pr#2956 [source /config/esphome/.esphome/packages/566b10a3/nspanel_esphome.yaml:53]
    components: 
      - nextion
    refresh: 1h
"
![2023-02-10 212138](https://user-images.githubusercontent.com/61584947/218190077-304323bb-1876-42e1-94b1-97ae03fbe33f.jpg)

**Comment by deejaybeam** [comment]
Would be helpfull if you share your config.
There must be an issue, because works on all others.

**Comment by Peterhansel88** [comment]
![2023-02-10 215514](https://user-images.githubusercontent.com/61584947/218195805-ead10dd5-aab9-4794-ae1b-8284520e21f3.jpg)

**Comment by Peterhansel88** [comment]
Anyway it is on a raspberry Pi 4
and:
Home Assistant 2023.2.3
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230202.0 - latest

**Comment by deejaybeam** [comment]
Please try again to copy the code with the symbol on the upper right corner in the wiki.
Replace all lines in your config, just set nsplanel-name SSID and PASS inside the quotes.
Yaml code has strict rules for the intends, but I can´t see them 100% in a pic.

Done this right now, works with out a problem:
```
substitutions:

###### CHANGE ME START ######

  device_name: "nspanel" 
  wifi_ssid: "XXXXX"
  wifi_password: "XXXXXXXXXXX"

#  nextion_update_url: "http://HOME-ASSISTANT-IP:8123/local/nspanel_us.tft" # URL to local tft File
  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_us.tft" # URL to Github

##### CHANGE ME END #####



##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####
```

Additionally I see you have set the tft-update-url to the git-link:
please be aware that there where many issuse when doing that!
![image](https://user-images.githubusercontent.com/10434729/218201597-17e8d624-6d64-411f-b4a5-21c85b57b14f.png)

Look at the three pinned issues in the repo:
https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/166
https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/177
https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/197

and:
https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/224

I think there happend a mistake when changing the tft update-url...
