### ISSUE TITLE
new feature: allow setting the startup state of the relays

### ISSUE THREAD

**Issue by LorenzKahl** [Blackymas/NSPanel_HA_Blueprint#352]
I have relay 1 connected to a light with a Philips hue bulb. I have set the left hardware switch to toggle the corresponding entity of the bulb instead the relay so it is easy to control its brightness from HA.

The new fallback feature that allows controlling the relay with the hardware in case of connection loss is a real WAF-booster - props for that 💯 

But my wife really doesn't appreciate the light going off completely when the NSPanel is rebooted and the default relay state is off.

Like the title already spoilered, it would be awesome having a setting in the Blueprint that allows setting the startup/reboot state of the relays.

Keep up the great work guys - this project is the best 🥇

**Comment by nitruxa** [comment]
I believe for those internal relays it makes more sense to default them to have `restore_mode` as `RESTORE_DEFAULT_OFF` 🤔

**Comment by LorenzKahl** [comment]
@nitruxa in my special case it would be `RESTORE_DEFAULT_ON` - maybe even `ALWAYS_ON` - but why not let the user choose? That's the main reason I opened this feature request.

**Comment by nitruxa** [comment]
Restore mode is being set when device is being installed. You won't be able to control it via blueprint. So technically you can decide which mode to use during the flashing procedure

**Comment by deejaybeam** [comment]
For normal circumstastances, the last state (should) be stored in flash - and be restored after a reboot:
https://esphome.io/components/switch/index.html#config-switch
"RESTORE_DEFAULT_OFF - Attempt to restore state and default to OFF if not possible to restore."

and:
https://github.com/esphome/ESPHome-Core/issues/460
```
- platform: gpio
  name: nspanel00 Relay 1
  id: relay_1
  pin:
    number: 22
    mode:
      output: true
      input: false
      open_drain: false
      pullup: false
      pulldown: false
    drive_strength: 20.0
    inverted: false
  disabled_by_default: false
  restore_mode: RESTORE_DEFAULT_OFF
  interlock_wait_time: 0ms
```
NSPanel has an ESP32 - so restore from flash is activated, and the statement:"Attempt to restore state and default to OFF if not possible to restore." describes everything perfect - just if something went wrong (eg corrupted flash!) then the state will be restored from flash.

Also in my personal case I can confirm that that works 100% I have always-on smart-bulbs connected via the realays and they never turn off on reboot, reflash, ....

Per default ther is just a "small" delay, writing the state to flash:
https://esphome.io/components/esphome.html#adjusting-flash-writes

but for "always on" this should not be a problem if you don´t reboot every minute...

So this is working as requested in general - maybe you have a faulty flash-storage on your device:
https://esphome.io/guides/faq.html#component-states-not-restored-after-reboot
