### ISSUE TITLE
Stuck with HA icon screen, never moves on

### ISSUE THREAD

**Issue by livlif2dfullest** [Blackymas/NSPanel_HA_Blueprint#382]
I followed the instructions and everything worked fine until I ran the HA service to use the new UI and now it's stuck just showing the HA icon startup screen.  How can I fix this, to either reset it and start over or find out what the problem is.  Any effort to get the logs produces zero results so I have no idea where to go from here.  I'm wondering if perhaps it's having an issue with my wifi information?  My SSID is hidden and my password has $ and & in it which I think are problems with yaml, but not sure if hidden SSIDs are supported or if those characters are ok with the way this works.  Any help would be appreciated.

No matter what I flash to the NSPanel, it always shows that HA icon at the startup and I can't get it to ever show online via ESPHome when just connecting it via the TTL serial adapter (USB connection/jumper wires) and flashing the basic configuration from ESPHome.

**Comment by Blackymas** [comment]
Have you installed the Blueprint and entered the correct name? without - or special characters?

Did you add the NSpanel in HA under ESPhome Devices?

Which versions are displayed on the boot screen?


If everything is not set up correctly, the display will stop in the boot - it is an indication that something is not configured correctly.

Under HA -> ESPhome -> you can find your NSpanel and see if it is connected to wifi or not.

**Comment by livlif2dfullest** [comment]
> Have you installed the Blueprint and entered the correct name? without - or special characters?
Yes
> 
> Did you add the NSpanel in HA under ESPhome Devices?
Yes
> 
> Which versions are displayed on the boot screen?
Are you referring to the NSPanel boot screen?  I don't see any version information when booting, it's just the HA graphic.
> 
> If everything is not set up correctly, the display will stop in the boot - it is an indication that something is not configured correctly.
> 
> Under HA -> ESPhome -> you can find your NSpanel and see if it is connected to Wi-Fi or not.
I can no longer get it to be connected via Wi-Fi, I can only do things via the USB connection and it no longer shows up in HA, i.e. it can't connect.

Is there anything I can do to "reset" the NSPanel, via the USB connection, so I can start over?  As I said previously, no matter what I flash I'm stuck at the bootup screen so it seems nothing ever loads to get me the ability to fix the Wi-Fi connection.

**Comment by livlif2dfullest** [comment]
Thinking about this more, I think I did have a '-' in the name when I set it up in ESPHome, does that cause problems?  I don't recall reading anything about only using alpha characters or alphanumeric characters and it seems underscores are allowed?

**Comment by livlif2dfullest** [comment]
Either way I think the NSPanel is hosed, I can't find anything on the Internet to show me how to "reset" it.  I'll order another one and make sure the naming is correct.  Is there someway to backup the stock configuration so if I encounter this again I can reverse everything back to stock?

**Comment by bkbartk** [comment]
> I think I did have a '-' in the name when I set it up in ESPHome

in that case, you the blueprint replace those with _
![image](https://user-images.githubusercontent.com/17070805/222434298-c4508e4f-b9a2-4bed-a67b-d66319780728.png)

and also, you should just be able to reflash you nspanel using serial flash, you don't have to throw yours away.

**Comment by livlif2dfullest** [comment]
So I tried re-flashing but it's still stuck on the HA icon, no version information displayed.  I flashed the kitchen-right-nspanel.txt file (has yaml ext in ESPHome), substituted MySSID, MyPwd, MyLocalIP4HA and MyLocalPort4HA with the proper values, double quotes remain around these values as shown in the attached file:
[kitchen-right-nspanel.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/10872780/kitchen-right-nspanel.txt)


Then I disconnected the serial connection, connected 5v and ground, which started up the NSPanel, but all it ever displays is the HA icon, the display will turn off after a while and I can turn it back on by clicking the display but that's all it ever does:![NSPanelDisplay](https://user-images.githubusercontent.com/94875936/222476607-59381465-d156-4e91-9e3f-b299dc4ace7d.jpg)  Is there something else I'm missing to get this to work properly?

**Comment by livlif2dfullest** [comment]
I've gotten a bit further, the issue was with my WiFi, it had a $ and # sign in it which was causing part of the password to be commented out.  So I can now see it in HA with the entities.  I tried calling the service "ESPHome: kitchenrightnspanel_upload_tft", however, the screen didn't switch to the loading screen as it did the first time I did this, it continues to show the HA icon from the image above.  I went back into ESPHome and clicked on the "Visit" button from the NSPanel device and it took me to the NSPanel's web site, where it prompted me for my username/password and then I see it's generating the following errors:
<img width="417" alt="NSPanelWebSiteLog" src="https://user-images.githubusercontent.com/94875936/222492639-b056fd08-b8a0-468e-bff5-a7ecca93ba3a.png">
So what's wrong here?

**Comment by Blackymas** [comment]
> So I tried re-flashing but it's still stuck on the HA icon, no version information displayed. I flashed the kitchen-right-nspanel.txt file (has yaml ext in ESPHome), substituted MySSID, MyPwd, MyLocalIP4HA and MyLocalPort4HA with the proper values, double quotes remain around these values as shown in the attached file: [kitchen-right-nspanel.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/10872780/kitchen-right-nspanel.txt)
> 
> Then I disconnected the serial connection, connected 5v and ground, which started up the NSPanel, but all it ever displays is the HA icon, the display will turn off after a while and I can turn it back on by clicking the display but that's all it ever does:![NSPanelDisplay](https://user-images.githubusercontent.com/94875936/222476607-59381465-d156-4e91-9e3f-b299dc4ace7d.jpg) Is there something else I'm missing to get this to work properly?

The image has been important. It shows you that you are not using my TFT version.

My boot page looks completely different.

So that means that currently my TFT version is not running on your display.

**Comment by abidullah** [comment]
i too had same issues and finally ford a solution
my workaround is 

on the Home assistant 
go to Developer Tools
![image](https://user-images.githubusercontent.com/2981996/222845565-e5862981-85e9-49c0-8882-83f2d4a2cf3b.png)
then Choose Services 
![image](https://user-images.githubusercontent.com/2981996/222845447-358caa95-9773-42a0-bad8-ae5f4c717883.png)

then find service called  ESPHome: nspanel_send_command_printf
and enter page 0 and send

**Comment by abidullah** [comment]
My setup

![04285A33-88CD-42C8-9411-E4D4B0F8905A](https://user-images.githubusercontent.com/2981996/222847660-45660375-fa26-49d2-895b-df370c5ede32.jpeg)
![D61105F0-7CAE-455A-9FC0-A394E861246B](https://user-images.githubusercontent.com/2981996/222847730-722aa823-8013-410f-ba36-030be5585cce.jpeg)
![D4D4DADC-72EF-44E5-9215-6D66E0B4910D](https://user-images.githubusercontent.com/2981996/222847741-6134eba5-97c8-4deb-a626-3112fd9357a0.jpeg)

**Comment by livlif2dfullest** [comment]
I'm able to upload a tft now, the only issue is I have to change the UART baud rate to  9600. Are you saying the print 0 fix you suggested above fixed the stuck at boot screen or fixed the baud rate issue or both?

**Comment by abidullah** [comment]
yes but it has to be uploaded with new version of tft file created by @Blackymas and i have managed to edit it and made it horizontal screen mode as u can see it in my post.

**Comment by jpettitt** [comment]
I've also got a panel that is stuck at 9600, any idea how to get it back to 115,200?

**Comment by livlif2dfullest** [comment]
I haven't got my NSPanel fully working with the blueprint as of yet, but I've gotten over the following hurdles:
- not being able to flash the tft with anything other than 9600 UART baud rate.
- Screen only shows 'System data ERROR!'

I fixed both of those this morning by doing the following:
Flashed the configuration file https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/nspanel_esphome.yaml with the following modifications:
- commented out the logger configuration entries from this:
`logger:`
to this:
`#logger:`
- uncommented the following substitution lines from this:
```
# substitutions: 
  # ## usage of secrets-file ## -> comment in ###### Change ME ######
  # device_name: "nspanel-name" # Wird im Blueprint benötigt!
  # wifi_ssid: !secret nspanel_wifi_ssid # add in your esphome secrets file.
  # wifi_password: !secret nspanel_wifi_password # add in your esphome secrets file. -> per default this is also used for ota_password and web_password
  # ota_password: !secret nspanel_ota_password # add in your esphome secrets file. - manual change in code required to activate
  # web_password: !secret nspanel_web_password # add in your esphome secrets file. - manual change in code required to activate
  # api_password: !secret nspanel_api_password # add in your esphome secrets file. - manual change in code required to activate
  # nextion_update_url: !secret nspanel_update_url # add in your esphome secrets file. Example: "http://"HOME ASSISTANT IP":8123/local/nspanel/nspanel.tft"
```
to this:
```
substitutions: 
  # ## usage of secrets-file ## -> comment in ###### Change ME ######
  device_name: "nspanel-name" # Wird im Blueprint benötigt!
  wifi_ssid: !secret nspanel_wifi_ssid # add in your esphome secrets file.
  wifi_password: !secret nspanel_wifi_password # add in your esphome secrets file. -> per default this is also used for ota_password and web_password
  # ota_password: !secret nspanel_ota_password # add in your esphome secrets file. - manual change in code required to activate
  # web_password: !secret nspanel_web_password # add in your esphome secrets file. - manual change in code required to activate
  # api_password: !secret nspanel_api_password # add in your esphome secrets file. - manual change in code required to activate
  nextion_update_url: !secret nspanel_update_url # add in your esphome secrets file. Example: "http://"HOME ASSISTANT IP":8123/local/nspanel/nspanel.tft"
```
- Changed the UART baud rate from 115200 to 9600, this:
```
uart:
  tx_pin: 16
  rx_pin: 17
  baud_rate: 115200
  id: tf_uart
```
to this:
```
uart:
  tx_pin: 16
  rx_pin: 17
  baud_rate: 9600 #115200
  id: tf_uart
```
- Added the following to my secrets.yaml file:
```
nspanel_wifi_ssid: MyWiFiSSID
nspanel_wifi_password: MyWiFiPassword #I had to change my WiFI password as it had a $ and # sign in it which was causing problems.
nspanel_update_url: http://HA_IPAddress:HA_Port/local/nspanel_blank.tft
```
- Flashed the configuration from above on the NSPanel.
- Switch to 5v and Ground
- Went into HA and called service ESPHome: kitchen_right_nspanel_upload_tft, obviously change your service to what ever you named your panel, this slowly flashed the nspanel_blank.tft and once it was done I saw a white screen.
- Switched back to 3.3v and the tx and rx pin stuff, removing the 5v and Ground.
- Changed the configuration back to 115200 baud rate:
```
uart:
  tx_pin: 16
  rx_pin: 17
  baud_rate: 115200
  id: tf_uart
```
- Changed secrets.yaml from this:
```
nspanel_update_url: http://HA_IPAddress:HA_Port/local/nspanel_blank.tft
```
to this:
```
nspanel_update_url: http://HA_IPAddress:HA_Port/local/nspanel_us.tft
```
- Flashed that configuration to the NSPanel.
- After flashing changed back to 5v and Ground.
- Went into HA and called service ESPHome: kitchen_right_nspanel_upload_tft, obviously change your service to what ever you named your panel, this quickly flashed the nspanel_us.tft as 115200 baud and now I'm at the Please wait... screen from the blueprint and it's been like that for a few minutes now so something is wrong but at least I can now get to this part, I probably still need to change something with my configuration.  Once I get it figured out I'll post the remaining things I did to get it all fixed, I hope this helps you out.

**Comment by jpettitt** [comment]
Hmm, even after flashing the `nspanel_blank`  mine will still only talk to the ESP at 9600.  I've tried with and without commenting `logger:` - what was the reason to comment that?

Also is there a meaningful difference between uploading over wifi and uploading via a serial adaptor?

**Comment by livlif2dfullest** [comment]
Now stuck at blueprint load page:
- Continuing from the above steps, I switched my yaml configuration to:
```
substitutions:

###### CHANGE ME START ######

  device_name: kitchen_right_nspanel
  wifi_ssid: !secret nspanel_wifi_ssid
  wifi_password: !secret nspanel_wifi_password
  nextion_update_url: !secret nspanel_update_url # URL to local tft File

##### CHANGE ME END #####



##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####
```
- Flashed the above configuration.
- Switched to 5v and Ground
- Now stuck at the following screen: 
![NSPanelDisplay_blueprint](https://user-images.githubusercontent.com/94875936/222980016-7a5dfeb7-29f7-4fa6-98a4-496b3349c40b.jpg)

I was able to get it to switch to my display by calling the ESPHome: kitchen_right_nspanel_send_command_printf service with:
`page 0`
However, it continues to get stuck at the blueprint load screen every time I reboot the NSPanel, any suggestions?
