### ISSUE TITLE
Command Line Cover are not presented as cover button

### ISSUE THREAD

**Issue by bakito** [Blackymas/NSPanel_HA_Blueprint#389]
I have some covers that I only can address via command line scripts by use of Command Line Cover https://www.home-assistant.io/integrations/cover.command_line/ 

I can configure this entities in the Blueprint, they also take a position in the display but no button is presented.
![missing_covers](https://user-images.githubusercontent.com/2733215/222894543-030b960e-f8fa-4b4d-836e-548cfdb6bfbb.png)
Clicking the empty space triggers the action on the cover.

Is something missing in the command_line cover entities to be compatible?

This is the entity state of one of the covers

```yaml
current_position: 0
friendly_name: All Covers
supported_features: 15
```
