### ISSUE TITLE
Nspanel nightly dim to 0% not possible?

### ISSUE THREAD

**Issue by kroon040** [Blackymas/NSPanel_HA_Blueprint#418]
Hi,

I have several nspanels and also in the bedroom. During the night I'd like to dim the home page  to 0%. I think only 1% is possible?

I now have this, is this the best way or is there a better solution?

```
alias: nspanelslaap uit
description: test
trigger:
  - platform: time
    at: "23:15:00"
condition:
  - condition: time
    weekday:
      - fri
      - thu
      - wed
      - tue
      - mon
action:
  - service: number.set_value
    data:
      value: "1"
    target:
      entity_id: number.nspanel_display_brightness
mode: single
```

```
