### ISSUE TITLE
Panel not interactive

### ISSUE THREAD

**Issue by albinmedoc** [Blackymas/NSPanel_HA_Blueprint#459]
I have got an problem with my panel that I can't use the physical buttons, neither the entity buttons even though they show up. 

The state of the entities are shown correctly (changes if I turn on/off through home assistant). 

I have this error on both of my panels.

What I have tried:
- Reflashed the panel, both OTA and through wire
- Update nextion, TFT display 
- Created a new blueprint and remove the old 

The intresting part is that even if I created a new blueprint and only specified left/right button and weather, all other entities showed up from the old blueprint (it was deleted and HA, panel restarted)

I wonder if there is something stored in memory causing the problem. 

https://user-images.githubusercontent.com/7331299/226097227-6938c08e-bae5-4ea7-a701-352f93c38ca2.MOV

**Comment by albinmedoc** [comment]
This is my automation
```yaml
alias: NS-Panel Living room
description: ""
use_blueprint:
  path: Blackymas/nspanel_blueprint.yaml
  input:
    nspanel_name: ns_panel_living_room
    language: SWE
    weather_entity: weather.smhi
```
