### ISSUE TITLE
Confirmation dialog entity name

### ISSUE THREAD

**Issue by albinmedoc** [Blackymas/NSPanel_HA_Blueprint#501]
The confirmation dialog doesn't show the specified name for the entity.

For example if I have this code:

```yaml
entity27: scene.night
entity27_name: Nattläge
entity27_confirm: true
```

I would like the confirmation dialog to show "Nattläge" instead of the entity's friendly name.
