### ISSUE TITLE
NS Panel stays dark after powercut

### ISSUE THREAD

**Issue by Ierlandfan** [Blackymas/NSPanel_HA_Blueprint#590]
I know this is a difficult one but since I am redecorating I sometimes have to shut down the power completely. Everytime when power is restored (Flipping the breakers) NS Panel stays dark. Only and always working solution is to get it off the wall and reseat it. No idea what is happening. I will update my findings here like checking the WIFI state when it happens.  Maybe someone experienced the same or want to try out what happens on their devices while flipping the breakers.

**Comment by edwardtfn** [comment]
What about the entities on Home Assistant? Are those available?
Can you restart the panel from HA when it is in this "dark" state?

**Comment by Ierlandfan** [comment]
Entity unavailable in HA. cannot ping the device, not registered on WIFI. Like it is just not rebooting on it's own.

**Comment by Ierlandfan** [comment]
It works without a flaw otherwise. Just don't touch the breakers :-) I was just hoping that someone could replicate this behaviour. It's no big deal. More an edge case thing. You can close it if you want. If anyone ever run into it at least they know that reaseating helps then.

**Comment by Ierlandfan** [comment]
Firmware: 2023.3.2 (Apr 5 2023, 14:03:38)

Yaml:

substitutions:

###### CHANGE ME START ######

  device_name: "nspanel_livingroom" 
  wifi_ssid: "redacted"
  wifi_password: "redacted"

  nextion_update_url: "http://192.168.3.101:8123/local/tft/nspanel_eu.tft" # URL to local tft File
#  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_us.tft" # URL to Github

##### CHANGE ME END #####



##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: dev
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####

**Comment by edwardtfn** [comment]
These settings are pointing to ESPHome in DEV, which by the way is the same I'm using right now.

You should either change back to MAIN (see bellow) or make sure you have also Blueprint and TFT from DEV.

```
substitutions:

###### CHANGE ME START ######

  device_name: "nspanel_livingroom" 
  wifi_ssid: "redacted"
  wifi_password: "redacted"

  nextion_update_url: "http://192.168.3.101:8123/local/tft/nspanel_eu.tft" # URL to local tft File
#  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_us.tft" # URL to Github

##### CHANGE ME END #####



##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####
```
