### ISSUE TITLE
Bug: Can’t update a new device using 3.2.2

### ISSUE THREAD

**Issue by T3mplate-wow** [Blackymas/NSPanel_HA_Blueprint#605]
Hey there,
yesterday a completely new device arrived. So there was sonoff preinstalled on it.
I was using 3.2.2 to flash the device and this worked for the device itself. I saw the entity in HA and was able to switch the relays and see the temperature, state of the buttons ect.
But the screen shows the sonoff page. As I tried to upgrade the screen nothing happens on the screen. The device lost the connection to HA shortly but there was no refreshing/installing on the tft. 
As I switched to 3.0 (this one I used for initial installing before, so I knew this version was working) I was able to upgrade the screen. 

On my existing devices using 3.1 I was able to upgrade to 3.2.2. So I beliefe it is a problem just happening on a newly purchased device.

**Comment by EvilDemos** [comment]
Im having the same issue.  Newly purchased device. Followed the instructions carefully. Flash was sucessfull and integration was successful. Entities are there but can not upgrade the screen. ESPhome log for the nspanel shows

`[02:44:27][E][uart:015]: Reading from UART timed out at byte 0!`
`[02:44:27][W][nextion:072]: Nextion is not connected!`

Would really appreciate the help

**Comment by NC1609** [comment]
Hello friends,

I have the same problem. My display is relatively new. 
I have bought it 2 weeks ago. 
I have already tried to flash the blank.tft and then go to 3.2.2. All unfortunately without success.

**Comment by edwardtfn** [comment]
What if you try copying the URL for the TFT file and past into your browser, can you successfully download the TFT file to your computer? And could you please double check the file size after the download with your browser?

**Comment by T3mplate-wow** [comment]
I am not able to reproduce this anymore, because I installed 3.0 and this one was working. 
I am extremely sure that I did everything right. The tft was downloadable/reachable even through the browser.
Update from 3.0 to 3.2.2 or from 3.1 to 3.2.2 works fine. It is just happening when the display is clean with Sonoff from factory

**Comment by Azimuth0r** [comment]
I just bought a new NSPanel and have the same issue. How do you deploy version 3.0?

**Comment by T3mplate-wow** [comment]
I believe 3.1 will also work. Here you can find 3.0 https://github.com/Blackymas/NSPanel_HA_Blueprint/tree/v.3.0.0
and here 3.1 https://github.com/Blackymas/NSPanel_HA_Blueprint/tree/v.3.1.0

you need to download the nspanel.tft or nspanel_eu.tft. I marked it as nspanel_3_0.tft, so that I can distinguish between.

Then I downloaded the blueprint in this version.

In the ESP Config I used just the first part:
```
substitutions:

###### CHANGE ME START ######

  device_name: "YOUR NSPANEL_NAME" 
  wifi_ssid: "YOUR WIFI SSID"
  wifi_password: "YOUR WIFI PASSWORD"

  nextion_update_url: "http://HOME-ASSISTANT-IP:8123/local/nspanel_eu.tft" # URL to local tft File
#  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft" # URL to Github

##### CHANGE ME END #####
```
Don’t forget to insert the right tft file. In my case it was nspanel_3_0.tft.

After this part I added the whole esphome.yaml.
In case of 3.0 this file:
https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/v.3.0.0/nspanel_esphome.yaml
copy the whole text into the esp config under the part mentioned before. 

After this you can flash it by wire und update the tft successfully.
