### ISSUE TITLE
[Feature Request] - Close relay once on initial button press, then call service on consecutive presses

### ISSUE THREAD

**Issue by bbbenji** [Blackymas/NSPanel_HA_Blueprint#659]
I have smart lights connected to my relays and I want them to be on 99% of the time, but if there is a power outage, I don't want them to automatically turn on when the power comes back on. As suggested in [another FR here](https://github.com/Blackymas/NSPanel_HA_Blueprint/issues/352). Instead, I would like the relay to only turn on once on the initial button press after power loss, and then on consecutive button presses, call a service to toggle the light.

Here's an example of my current ESPHome configuration for another smart switch, I think it might explain a little better:

```
    on_press:
      if:
        condition:
          api.connected:
        then:
          - switch.turn_on: relay
          - homeassistant.service:
              service: light.toggle
              data:
                entity_id: light.bulb
        else:
          - switch.toggle: relay
```

**Comment by bbbenji** [comment]
That sounds like a good idea. I have never touched the scripts section of HA before, but this does appear to be a solution for me. Thanks!

For reference, here is the script I created.
```
alias: NSPanel Relay/Switch 2
sequence:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.nspanel_relay_2
  - type: toggle
    device_id: b21fde50ffe2b38f0c1a49d2c4628eb8
    entity_id: light.kitchen_table_ceiling_light
    domain: light
mode: single
```

I guess we can close this FR.
