### ISSUE TITLE
After flashing unit is in a reboot loop

### ISSUE THREAD

**Issue by farcouet** [Blackymas/NSPanel_HA_Blueprint#670]
Hello,

I flashed using Esphome, ESP32 and the configuration. However after flashing the unit is in a reboot loop (nothing is showing on the LCD). I tried with a first unit and I was thinking it might be faulty but I have the same issue with a brand new NSpanel US.

I used that exact configuration:
substitutions:

###### CHANGE ME START ######

  device_name: "nspanel1" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: "http://192.168.12.233:8123/local/nspanel_us.tft" # URL to local tft File
#  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_us.tft" # URL to Github

##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####

****Error log:****

[I][logger:258]: Log initialized
[C][ota:469]: There have been 0 suspected unsuccessful boot attempts.
[D][esp32.preferences:113]: Saving 1 preferences to flash...
[D][esp32.preferences:142]: Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
[I][app:029]: Running through setup()...
[C][esp32_ble:026]: Setting up BLE...
ets Jul 29 2019 12:21:46

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13132
load:0x40080400,len:3036
entry 0x400805e4
[I][logger:258]: Log initialized
[C][ota:469]: There have been 1 suspected unsuccessful boot attempts.
[D][esp32.preferences:113]: Saving 1 preferences to flash...
[D][esp32.preferences:142]: Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
[I][app:029]: Running through setup()...
[C][esp32_ble:026]: Setting up BLE...
ets Jul 29 2019 12:21:46

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)

**Comment by edwardtfn** [comment]
Could you please format your configuration as a code?

Just press this button `<>` in the top of the box where you write you message (please select the text to format first).

![image](https://user-images.githubusercontent.com/94725493/231805850-45469191-4580-4943-8eba-a79204f54666.png)

So it will look like this:

```
packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s
```

And not like this (much harder to troubleshoot, specially in yaml where blank spaces counts a lot):
packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

**Comment by farcouet** [comment]
> Could you please format your configuration as a code?
> 
> Just press this button `<>` in the top of the box where you write you message (please select the text to format first).
> 
> ![image](https://user-images.githubusercontent.com/94725493/231805850-45469191-4580-4943-8eba-a79204f54666.png)
> 
> So it will look like this:
> 
> ```
> packages:
>   ##### download esphome code from Github
>   remote_package:
>     url: https://github.com/Blackymas/NSPanel_HA_Blueprint
>     ref: main
>     files: [nspanel_esphome.yaml]
>     refresh: 300s
> ```
> 
> And not like this (much harder to troubleshoot, specially in yaml where blank spaces counts a lot): packages:
> 
> ##### download esphome code from Github
> remote_package: url: https://github.com/Blackymas/NSPanel_HA_Blueprint ref: main files: [nspanel_esphome.yaml] refresh: 300s

Sure here is the configuration and sorry about that:
`substitutions:

###### CHANGE ME START ######

  device_name: "nspanel1" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: "http://192.168.12.233:8123/local/nspanel_us.tft" # URL to local tft File
#  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_us.tft" # URL to Github

##### CHANGE ME END #####



##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####`

**Comment by farcouet** [comment]
> > [C][esp32_ble:026]: Setting up BLE...
> 
> Are you sure you have flashed ESPHome into your panel? Is you panel showing as "Online" on the ESPHome dashboard?

Yes I flashed with ESPHome and it completed and this is after that that it's stock on rebooting loop. So nothing shows on the screen but when connecting with the terminal and the serial adapter that's how I got the error log. So it never showed up in ESPHome dashboard and I don't see it connecting to the Wifi (as it's also rebooting non stop).

**Comment by farcouet** [comment]
Does anyone has an idea where to look?

**Comment by edwardtfn** [comment]
Try to flash ESPHOME again using this and the try uploading the nspanel_blank.tft again, please.

```yaml 
substitutions:

###### CHANGE ME START ######

  device_name: "nspanel1" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: "http://192.168.12.233:8123/local/nspanel_us.tft" # URL to local tft File
#  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_us.tft" # URL to Github

##### CHANGE ME END #####

###### USE THIS ONLY FOR YOUR FIRST TFT UPLOAD, ONCE IT WORKED, REMOVE THESE LINES ######
external_components:
  - source: github://pr#2956
    components: [nextion]
    refresh: 1h
###############################################################################


##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: beta
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####
```
