### ISSUE TITLE
Bang Bang climate not working

### ISSUE THREAD

**Issue by denes44** [Blackymas/NSPanel_HA_Blueprint#749]
Hi,

I wanted to test someting, so I created a [Bang Bang Climate Controller](https://esphome.io/components/climate/bang_bang.html) in esphome.
However this is not working with nspanel, I got the following error:
`Hallway NSPanel Configuration: Main choices: Climate - Sync: If at step 5: Error executing script. Error for call_service at pos 1: Error rendering data template: UndefinedError: 'homeassistant.util.read_only_dict.ReadOnlyDict object' has no attribute 'temperature'`

And this climate entity indeed does not have a temperature attribute, only a current_temperature:
```
hvac_modes: off, heat
min_temp: 10
max_temp: 30
target_temp_step: 0.1
current_temperature: 27.5
target_temp_high: 30
target_temp_low: 20
hvac_action: off
friendly_name: Bang Bang Climate Controller
supported_features: 2
```

**Comment by edwardtfn** [comment]
Can you share your yaml where you setup the bang bang on ESPHome.
I've shared some code for a thermostat in other discussion here and that I could test with no issues.

**Comment by edwardtfn** [comment]
There is: https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions/646#discussioncomment-5635185

**Comment by denes44** [comment]
> Can you share your yaml where you setup the bang bang on ESPHome. I've shared some code for a thermostat in other discussion here and that I could test with no issues.

This is the code:
```
climate:
  - platform: bang_bang
    name: "Bang Bang Climate Controller"
    sensor: temp_nspanel
    default_target_temperature_low: 20 °C
    default_target_temperature_high: 22 °C

    heat_action:
      - switch.turn_on: relay_1
    idle_action:
      - switch.turn_off: relay_1
```
The problem was with it, is that this climate entity does not provide a temperature attribute, which the blueprint expects.

I'm using the [Thermostat](https://esphome.io/components/climate/thermostat.html) platform now, which works good, because it has a temperature attribute.

The difference between the two, is that the bang bang controller has a low and a high target temperature, not just one.
I'm not sure if anybody uses it, I just wanted to test something with a heating only climate entity.
