### ISSUE TITLE
not working tft upload to display

### ISSUE THREAD

**Issue by jrspowers** [Blackymas/NSPanel_HA_Blueprint#777]
hello  have new nspanel in today wow this flash with this version but i get everything done until i want to upload the tft it doesn’t want to do it if not via local or the online tft file this is my config in esphome i am very sorry that this is not hope you can help me?

```yaml
substitutions:

###### CHANGE ME START ######

  device_name: "nspanelblueprint" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

#  nextion_update_url: "http://192.168.0.184:8123/local/nspanel_eu.tft" # URL to local tft File
  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft" # URL to Github
  

##### CHANGE ME END #####



##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####
```
