### ISSUE TITLE
issue with thermostat and cover

### ISSUE THREAD

**Issue by pbranly** [Blackymas/NSPanel_HA_Blueprint#783]
Hi
After several hours I could upload both tft and esp thanks to Tasmota. 
It seems and work fine and I can add switches, lights, temperature, weather but:
- I tried to add a climate but nothing appears (while as stated) it should at least generate a specific page
- I tried to add covers but it is displayed only as on/off toogle
- I don't have any content in the daily weather forecasts
- That's all for the moment.
My configuration is : HA in docker 2023.05
TFT: 3.3
ESPHOME: 3.3
Blueprint: 3.3
Thanks
Phil

**Comment by ervee** [comment]
Hi, for the climate page you need to tap this icon:

![16832234775463172230831270080112](https://user-images.githubusercontent.com/4435930/236290895-e96bbb72-fe6d-4d3e-9151-78b810106090.jpg)

I can't help with the covers.

Not all forecast services work the same IMO. Which service do you use? Set the climate to Default and select your service entity. Openweathermap and buienradar (Netherlands) seem to work best for me.

![Screenshot_2023-05-04-20-09-16-97_c3a231c25ed346e59462e84656a70e50](https://user-images.githubusercontent.com/4435930/236291662-4fc84d8b-2cc9-4f39-a820-b04b08d2be56.jpg)

**Comment by pbranly** [comment]
Hi 
I don't have this choice for weather
![image](https://user-images.githubusercontent.com/22018509/236296323-89402da4-0a4b-487e-a93d-10361850326e.png)

**Comment by ervee** [comment]
I'm still on blueprint 3.2.2 so perhaps that first setting is removed. Have you tried another weather intehration/entity?

**Comment by edwardtfn** [comment]
It should work with most of the weather providers.

Could you please share the yaml of your blueprint configuration?

**Comment by edwardtfn** [comment]
> I tried to add a climate but nothing appears (while as stated) it should at least generate a specific page

As @ervee mentioned, adding a climate will show the indoor temperature in your screen. You have to click at that number to be able to see the climate page.

> I tried to add covers but it is displayed only as on/off toogle

On the buttons pages, all the buttons will respond with a toggle to the short press, however, lights and covers will respond for a long click (hold for 1sec, I think) and will show the detailed screen.

> I don't have any content in the daily weather forecasts

I've asked for info about which integration you are using, so I can replicate. It would be nice if you can also go to the Developer Tools, select the tab States and then filter for your weather entity, so please send a screenshot showing its attributes, like this:
![IMG_6209](https://user-images.githubusercontent.com/94725493/236324603-961b2cbb-ef25-48b3-848e-79f475d4bede.png)
This will help a lot.

**Comment by pbranly** [comment]
Please find the copy of the automation generated by the blueprint 
```
alias: "NSPanel "
description: ""
use_blueprint:
  path: Blackymas/nspanel_blueprint.yaml
  input:
    nspanel_name: 76520303a8cbc905d522e79f6a527b5e
    language: FRA
    weather_entity: weather.villeneuve_d_ascq
    outdoortemp: sensor.netatmo_netatmo_module_exterieur_temperature
    indoortemp: sensor.netatmo_netatmo_module_interieur_temperature
    show_while_loading: true
    climate_optimistic: true
    qrcode_enabled: false
    entity01: switch.lampe_cuisine
    button_page01_label: Lampes
    entity01_icon: mdi:ceiling-light-outline
    relay_1_local_fallback: true
    date_format: "%d/%m"
    entity01_name: Cuisine
    climate: climate.vanne_chambre_nicolas
    left_button_entity: button.nspanel_restart
    left_button_name: Restart
    entity02: switch.prise_salle_tv
    entity01_icon_color:
      - 255
      - 255
      - 0
    entity02_name: Prise salle TV
    entity02_icon: mdi:power-socket-eu
    entity02_icon_color:
      - 255
      - 255
      - 0
    entity03: switch.prise_bureau
    entity03_name: Prise bureau
    entity03_icon: mdi:power-socket-eu
    entity03_icon_color:
      - 255
      - 255
      - 0
    entity09: cover.volet_bureau_nicolas_time_based
    entitypages_enabled: true
    button_page02_label: Volets
    entity09_name: Bureau Nicolas
```
Phil
