### ISSUE TITLE
Waste collection Notofication - new feature 

### ISSUE THREAD

**Issue by lygilygi** [Blackymas/NSPanel_HA_Blueprint#800]
Many of us are using Waste collection integrations - and many of those have attribute DAYS_TO

Like here:

<img width="1044" alt="Screenshot 2023-05-09 at 17 09 01" src="https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/45388740/0cadb542-4342-439c-bb00-d55966779e2a">

It would be great to add an option to see Which Bin is gonna be collected in...(1 day or so) and here set how many days from the attribute.
Let's say the day before collection you can set the lid color or icon or description of the due bin

This could be implemented as a notification as well - with the manual/automatic after-due day  option 'remove'

**Comment by deejaybeam** [comment]
this can be easy done with an own automation:
```yaml
- id: 'waste_collection'
  alias: Müll Rausstellen
  trigger:
    - platform: time
      at: '17:00:00'
  condition:
    - condition: numeric_state
      entity_id: sensor.abfallnaechster
      below: 2
  action:
    - service: esphome.nspanel02_play_rtttl
      data:
        song_str: "MahnaMahna:d=16,o=6,b=125:c#,c.,b5,8a#.5,8f.,4g#,a#,g.,4d#,8p,c#,c.,b5,8a#.5,8f.,g#.,8a#.,4g,8p,c#,c.,b5,8a#.5,8f.,4g#,f,g.,8d#.,f,g.,8d#.,f,8g,8d#.,f,8g,d#,8c,a#5,8d#.,8d#.,4d#,8d#."
    - service: esphome.nspanel02_notification_show
      data:
        label: 'Abfuhrkalender'
        text: "Müll rausstellen: {{ states.sensor.abfallnaechster.attributes.values() | first | replace('GelberSack', 'Gelber Sack') | replace('Restmuell', 'Restmüll') }}"
```
In this example every day at 17:00 waste-collection is checked. If something is picked up tomorrow it plays a sound and shows the notification.
The example is from the description of the waste-collection project, but uses the services "notification_show" and "play_rtttl" that were made for this usecase.

To implement this into the blueprint would maybe be possible, but is out of scope of this project.
In addition to too many possible parameters this would require translation to all supported languages.

**Comment by maffi123** [comment]
Hi,

I'm interested in this feature, too.
Actually, I have running some automation that switches helpers on / off if there is a bin collected next 15 hours.

I use a chip (in the color of the bin) for each bin. < Waste of 3 Chips, I have 4 different bins.

I would be glad if there is a possibility to show a -depending on which bin is going to be collected-  colored icon on the lower right corner of the main page.

Or maybe there will be a possibility to have a colored frame around the main page... Depending on the bin.

**Comment by edwardtfn** [comment]
> I would be glad if there is a possibility to show a -depending on which bin is going to be collected- colored icon on the lower right corner of the main page.

There is the service `esphome.xxxxx_set_component_color` (coming on v4.0, but there is another one for v3.4, which is not that easy, but still can be used). You can call that in an automation like suggested by @deejaybeam.

```yaml
service: esphome.xxxxx_set_component_color
data:
  component: home.icon_top_04
  foreground: [255, 0, 0]
  background: []
```

The colors are passed in a array like [red, green, blue], from 0 to 255, so the example above will change the color to red without changing the background.

The chips 1 to 7 are using components `icon_top_04` to `icon_top_10`, respectively.

How you see that solution?
