### ISSUE TITLE
White screen after eu.tft upload

### ISSUE THREAD

**Issue by xInsan3** [Blackymas/NSPanel_HA_Blueprint#803]
Hi, 
I'm struggling with flashing nspanel. Everything is going okay until the moment of tft file flash. After flashing (without any error) im getting white blank screen, cant use it at all. I tried like 50 times flashing, blank, eu etc. Anyone have any idea what can help to this issue?
NSPANEL conf:
substitutions:

###### CHANGE ME START ######

  device_name: "nspanel" 
  wifi_ssid: "xxx"
  wifi_password: "xxx"
  nextion_update_url: "https://xxx/local/nspanel_eu.tft" # URL to local tft File  ---link works, can download the file
 # nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft" # URL to Github

##### CHANGE ME END #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

HA version: 2023.5.2
Supervisor version: 2023.04.1
ESPhome version: 2023.4.4

Any help would be very appreciate :D

**Comment by edwardtfn** [comment]
Are you getting a totally blank screen or is there anything written in the blank screen?

**Comment by edwardtfn** [comment]
> Ye, link works, I can get that file

Is the file with the right size?

**Comment by xInsan3** [comment]
> > Ye, link works, I can get that file
> 
> Is the file with the right size?

Yes, 6.1 mb

**Comment by Blackymas** [comment]
can you try to add this in essphome
# external_components:
#   - source: github://pr#2956
#     components: [nextion]
#     refresh: 1h

**Comment by edwardtfn** [comment]
You can try first the "Exit reparse" button as per instructions bellow (from release notes):

&nbsp;
### 3. "Exit reparse" button
One of the biggest challenges to a new user is to upload the TFT file for the first time. This is due to Sonoff using the [Protocol Reparse Mode](https://nextion.tech/instruction-set/#:~:text=20-,Advanced.,the%20serial%20buffer%20for%20processing) to control the communication with the Nextion display. This prevents ESPHome to communicate with the display using its default libraries and therefore prevents installing the new TFT.
With this version you will have a new button named "Exit reparse", which will send a command to the Nextion to exit that mode for a few seconds, giving to the use a chance to then upload the TFT file without the need to change your ESPHome settings or using older Nextion libraries.
![image](https://user-images.githubusercontent.com/94725493/235167581-50070e44-fff8-46b9-a036-c6b60b278d77.png)
Once you have successfully uploaded any of the TFT files from this project (`nspanel_blank.tft`, `nspanel_eu.tft` or `nspanel_us.tft`), the reparse mode will be permanently disabled and this button is not needed anymore.

If you have your panel displaying the Sonoff original screen, please follow the following steps to install your TFT file:
1. Go to the front of your panel with a portable device with access to Home Assistant
2. Open the device related to your panel under Settings > Device & Services > ESPHome
3. Press the new button "Exit reparse" and wait for your panel to change it's screen to another page (which will take around 10s)
4. While the new page is shown (it will be there for just a couple of seconds), press the button "Upload TFT"
5. You should then see the progress bar in your display and after no more than 20 minutes the new TFT will be displayed.



If that didn't help, you should try what @Blackymas is proposing. Something like this:

```yaml 
substitutions:

###### CHANGE ME START ######

  device_name: "nspanel" 
  wifi_ssid: "xxx"
  wifi_password: "xxx"

  nextion_update_url: "https://xxx/local/nspanel_eu.tft"
  #nextion_update_url: "https://xxx/local/nspanel_blank.tft"

##### CHANGE ME END #####

###### USE THIS ONLY FOR YOUR FIRST TFT UPLOAD, ONCE IT WORKED, REMOVE THESE LINES ######
external_components:
  - source: github://pr#2956
    components: [nextion]
    refresh: 1h
###############################################################################


##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####
```

Although if you got to install `nspanal_blank.tft` this shouldn't make any difference. But again, older `nspanel_blank.tft` was a totally white screen just like you have described, but the latest available in github is a QR code.
