### ISSUE TITLE
Nothing happens with "Update TFT Display".

### ISSUE THREAD

**Issue by theoldphilip** [Blackymas/NSPanel_HA_Blueprint#805]
Hello everyone,

I have a new NS panel in front of me.
The current .tft is in the www directory and the software is flashed onto the ESP. Yes, when I click on the link, the browser also starts downloading the file.

I can also switch the relays via HomeAssistant.
The problem is I currently have the Sonoff firmware on the display. If I now click on "Update TFT Display" absolutely nothing happens.

Only the Nextion Display briefly switches from "Unknown" to "Disconnected". Blueprint is also new.

What am I doing wrong ?

Greeting Philip

`substitutions:

###### CHANGE ME START ######

  device_name: "panelarbeit" 
  wifi_ssid: "ESP"
  wifi_password: "philipjuliaforever"

 
  nextion_update_url: "http://172.30.40.2:8123/local/nspanel_eu.tft" # URL to local tft File
  ## nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft" # URL to Github

##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####`

**Comment by theoldphilip** [comment]
[21:07:09][E][uart:015]: Reading from UART timed out at byte 0!
[21:07:09][E][uart:015]: Reading from UART timed out at byte 0!
[21:07:09][E][uart:015]: Reading from UART timed out at byte 0!
[21:07:09][E][uart:015]: Reading from UART timed out at byte 0!
[21:07:09][E][uart:015]: Reading from UART timed out at byte 0!
[21:07:09][E][uart:015]: Reading from UART timed out at byte 0!
[21:07:09][E][uart:015]: Reading from UART timed out at byte 0!
[21:07:09][E][uart:015]: Reading from UART timed out at byte 0!
[21:07:10][E][uart:015]: Reading from UART timed out at byte 0!
[21:07:10][E][uart:015]: Reading from UART timed out at byte 0!
[21:07:10][E][uart:015]: Reading from UART timed out at byte 0!
[21:07:10][E][uart:015]: Reading from UART timed out at byte 0!
[21:07:10][E][uart:015]: Reading from UART timed out at byte 0!
[21:07:10][E][uart:015]: Reading from UART timed out at byte 0!
[21:07:10][E][uart:015]: Reading from UART timed out at byte 0!
[21:07:10][E][uart:015]: Reading from UART timed out at byte 0!
[21:07:10][E][uart:015]: Reading from UART timed out at byte 0!
[21:07:10][E][uart:015]: Reading from UART timed out at byte 0!
[21:07:11][E][uart:015]: Reading from UART timed out at byte 0!
[21:07:11][E][uart:015]: Reading from UART timed out at byte 0!
[21:07:11][D][nextion_upload:239]: Upgrade response is  20
[21:07:11][D][nextion_upload:242]: Available 0 : 0x00
[21:07:11][D][nextion_upload:242]: Available 1 : 0x00
[21:07:11][D][nextion_upload:242]: Available 2 : 0x00
[21:07:11][D][nextion_upload:242]: Available 3 : 0x00
[21:07:11][D][nextion_upload:242]: Available 4 : 0x00
[21:07:11][D][nextion_upload:242]: Available 5 : 0x00
[21:07:11][D][nextion_upload:242]: Available 6 : 0x00
[21:07:11][D][nextion_upload:242]: Available 7 : 0x00
[21:07:11][D][nextion_upload:242]: Available 8 : 0x00
[21:07:11][D][nextion_upload:242]: Available 9 : 0x00
[21:07:11][D][nextion_upload:242]: Available 10 : 0x00
[21:07:11][D][nextion_upload:242]: Available 11 : 0x00
[21:07:11][D][nextion_upload:242]: Available 12 : 0x00
[21:07:11][D][nextion_upload:242]: Available 13 : 0x00
[21:07:11][D][nextion_upload:242]: Available 14 : 0x00
[21:07:11][D][nextion_upload:242]: Available 15 : 0x00
[21:07:11][D][nextion_upload:242]: Available 16 : 0x00
[21:07:11][D][nextion_upload:242]: Available 17 : 0x00
[21:07:11][D][nextion_upload:242]: Available 18 : 0x00
[21:07:11][D][nextion_upload:242]: Available 19 : 0x00
[21:07:11][D][nextion_upload:248]: preparation for tft update failed 0 ""
[21:07:11][D][nextion_upload:310]: Restarting Nextion
[21:07:12][D][nextion_upload:313]: Restarting esphome

**Comment by Blackymas** [comment]
please use the issue search function this topic has been discussed several times and what to look for.

**Comment by edwardtfn** [comment]
### 3. "Exit reparse" button
One of the biggest challenges to a new user is to upload the TFT file for the first time. This is due to Sonoff using the [Protocol Reparse Mode](https://nextion.tech/instruction-set/#:~:text=20-,Advanced.,the%20serial%20buffer%20for%20processing) to control the communication with the Nextion display. This prevents ESPHome to communicate with the display using its default libraries and therefore prevents installing the new TFT.
With this version you will have a new button named "Exit reparse", which will send a command to the Nextion to exit that mode for a few seconds, giving to the use a chance to then upload the TFT file without the need to change your ESPHome settings or using older Nextion libraries.
![image](https://user-images.githubusercontent.com/94725493/235167581-50070e44-fff8-46b9-a036-c6b60b278d77.png)
Once you have successfully uploaded any of the TFT files from this project (`nspanel_blank.tft`, `nspanel_eu.tft` or `nspanel_us.tft`), the reparse mode will be permanently disabled and this button is not needed anymore.

If you have your panel displaying the Sonoff original screen, please follow the following steps to install your TFT file:
1. Go to the front of your panel with a portable device with access to Home Assistant
2. Open the device related to your panel under Settings > Device & Services > ESPHome
3. Press the new button "Exit reparse" and wait for your panel to change it's screen to another page (which will take around 10s)
4. While the new page is shown (it will be there for just a couple of seconds), press the button "Upload TFT"
5. You should then see the progress bar in your display and after no more than 20 minutes the new TFT will be displayed.

**Comment by theoldphilip** [comment]
Thanks edwardtfn for your help.

But if i click the Exit reparse Button nothing happens,
no matter how long i wait

**Comment by edwardtfn** [comment]
So, please try this and let me know what happens when you press "Upload TFT" (no need to press "Exit reparse" with this):

```yaml 
substitutions:

###### CHANGE ME START ######

  device_name: "panelarbeit" 
  wifi_ssid: "ESP"
  wifi_password: "philipjuliaforever"

  #nextion_update_url: "http://172.30.40.2:8123/local/nspanel_eu.tft"
  nextion_update_url: "http://172.30.40.2:8123/local/nspanel_blank.tft"

##### CHANGE ME END #####

###### USE THIS ONLY FOR YOUR FIRST TFT UPLOAD, ONCE IT WORKED, REMOVE THESE LINES ######
external_components:
  - source: github://pr#2956
    components: [nextion]
    refresh: 1h
###############################################################################


##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####
```
