### ISSUE TITLE
Problem after flashing

### ISSUE THREAD

**Issue by ulf1987** [Blackymas/NSPanel_HA_Blueprint#806]
Hello,

I have already successfully set up an NSPANEL with your great project. However, I have the problem with all other devices. The standard sonoff animation comes after flashing and the sonoff menu is shown on the display. In the HomeAssistant the device is recognized as new ESPHOME device, it is even possible to trigger relay 1 or 2 but the TFT cannot be uploaded. Am I missing something? I'm at a loss right now. Greetings Timo 
![IMG_9900](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/95085564/cd42f476-7884-4bbb-a43e-fa48aee0ab6b)

**Comment by edwardtfn** [comment]
Have you tried this?

### 3. "Exit reparse" button
One of the biggest challenges to a new user is to upload the TFT file for the first time. This is due to Sonoff using the [Protocol Reparse Mode](https://nextion.tech/instruction-set/#:~:text=20-,Advanced.,the%20serial%20buffer%20for%20processing) to control the communication with the Nextion display. This prevents ESPHome to communicate with the display using its default libraries and therefore prevents installing the new TFT.
With this version you will have a new button named "Exit reparse", which will send a command to the Nextion to exit that mode for a few seconds, giving to the use a chance to then upload the TFT file without the need to change your ESPHome settings or using older Nextion libraries.
![image](https://user-images.githubusercontent.com/94725493/235167581-50070e44-fff8-46b9-a036-c6b60b278d77.png)
Once you have successfully uploaded any of the TFT files from this project (`nspanel_blank.tft`, `nspanel_eu.tft` or `nspanel_us.tft`), the reparse mode will be permanently disabled and this button is not needed anymore.

If you have your panel displaying the Sonoff original screen, please follow the following steps to install your TFT file:
1. Go to the front of your panel with a portable device with access to Home Assistant
2. Open the device related to your panel under Settings > Device & Services > ESPHome
3. Press the new button "Exit reparse" and wait for your panel to change it's screen to another page (which will take around 10s)
4. While the new page is shown (it will be there for just a couple of seconds), press the button "Upload TFT"
5. You should then see the progress bar in your display and after no more than 20 minutes the new TFT will be displayed.

**Comment by ulf1987** [comment]
Hello edwardtfn,

Thank you very much for your quick reply. Yes, I know the "Exit reparse" button. If I use this function nothing happens. In point 3 you explain that a new page should appear but it doesn't. The display just gets a little darker. I waited between 10-60 seconds for several attempts and pressed the "Upload button" again and again. If I press the "Exit reparse" button and then shortly thereafter the "Upload button" the device restarts and the sonoff boot animation appears. Also during the boot I tried to use the "Upload" button but also without success. I keep getting back to the home screen as shown in my screenshot.

Greetings

Timo

**Comment by edwardtfn** [comment]
Please add this to your ESPHome file, flash your panel again and then try to press "Upload TFT".

```yaml 
###### USE THIS ONLY FOR YOUR FIRST TFT UPLOAD, ONCE IT WORKED, REMOVE THESE LINES ######
external_components:
  - source: github://pr#2956
    components: [nextion]
    refresh: 1h
###############################################################################
```

**Comment by ulf1987** [comment]
Hello Edward,

short problem still exists.
My approach:
1.ESPHome file customized with your code.
2. Device flashed
3.The device briefly displayed progress and issued an OK.
4. "Upload TFT" button pressed
5. The device restarts and the Sonoff animation is displayed
6. Sonoff home screen will appear
7. Deleted your code. Device reflashed
8. Several upload attempts with and without "Exit reparse"
I hope you understood everything. :-) Do you need any logs?

Greetings
Timo

**Comment by edwardtfn** [comment]
Are you sure you are using the right url to the TFT file? If you use that url in your browser (in your computer), do you get the file downloaded with the right size?

**Comment by ulf1987** [comment]
Hello Edward,

here is the code from one of the panels:

"substitutions:

###### CHANGE ME START ######

  device_name: "ns_wohnzimmer" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: "http://192.168.1.113:8123/local/nspanel_eu.tft" # URL to local tft File
#nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_eu.tft" # URL to Github

##### CHANGE ME END #####



##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####"

I just tested the link again with Chrome. The file will be downloaded directly.

Greetings
Timo

**Comment by edwardtfn** [comment]
I hardly suggest you to try `nspanel_blank.tft` first, as it is much smaller and will take out the reparse mode.

Please try this and let me know:

```yaml 
substitutions:

###### CHANGE ME START ######

  device_name: "ns_wohnzimmer" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  #nextion_update_url: "http://192.168.1.113:8123/local/nspanel_eu.tft"
  nextion_update_url: "http://192.168.1.113:8123/local/nspanel_blank.tft"

##### CHANGE ME END #####

###### USE THIS ONLY FOR YOUR FIRST TFT UPLOAD, ONCE IT WORKED, REMOVE THESE LINES ######
external_components:
  - source: github://pr#2956
    components: [nextion]
    refresh: 1h
###############################################################################


##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####
```

**Comment by ulf1987** [comment]
Hello Edward,

I don't know how to thank you :-) Thank you so much
The panel now displays a QR code. Do I now have to flash the code from your instructions again and then upload the TFT?
I can then also use your code for the other panels, of course with an adapted device name?
Thank you again for your work and time.

Greetings
![IMG_9903](https://github.com/Blackymas/NSPanel_HA_Blueprint/assets/95085564/25312b0d-dbdb-4682-a3f6-c2fec6211b9a)

Tim

**Comment by edwardtfn** [comment]
I'm happy to see that QR code. 🙂

You don't need those extra lines in this panel anymore, so you can remove those, point to the `nspanel_eu.tft` and click "Upload TFT".

So your new ESPHome settings will look like this:

```yaml 

substitutions:

###### CHANGE ME START ######

  device_name: "ns_wohnzimmer" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: "http://192.168.1.113:8123/local/nspanel_eu.tft"
  #nextion_update_url: "http://192.168.1.113:8123/local/nspanel_blank.tft"

##### CHANGE ME END #####

##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####
```


And yes, you can repeat this process for your other panels.
