### ISSUE TITLE
Update TFT Display

### ISSUE THREAD

**Issue by jamieFL** [Blackymas/NSPanel_HA_Blueprint#816]
Hello,

I cannot get my TFT Display to update.  When I try, the panel goes unavailable for a few seconds, then comes back up.  I have 31 entities and the 'Nextion display' entity stays 'unknown'.

I have the NS Panel flashed and connected to wifi.  I have the blueprint installed and have selected the NS Panel (nspanel_kitchen). 

Here is the Nextion Update URL:
nextion_update_url: "http://www.xxx.yyy.zzz:8123/local/nspanel_us.tft"
I downloaded the file 2 days ago.

The nspanel_us.tft file is in config/www and when I paste the above URL into my browser, it tries to download the file.  A file compare shows the files to be identical.

I am attaching my ESP Home Logs during the update process, during idle, and the Home Assistant Logs after a reset and TFT Update.

I am also aware that someone else on Discord is having the exact same problem with the same logs during the update process.

[HA Error Logs After Reset and Update TFT Display.log](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/11492190/HA.Error.Logs.After.Reset.and.Update.TFT.Display.log)
[Logs_During_Update_TFT Display.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/11492191/Logs_During_Update_TFT.Display.txt)
[logs_nspanelkitchen_logs.txt](https://github.com/Blackymas/NSPanel_HA_Blueprint/files/11492192/logs_nspanelkitchen_logs.txt)

**Comment by edwardtfn** [comment]
What you see in your panel's display?

**Comment by edwardtfn** [comment]
If that isn't working also, please try this and then go directly to "Upload TFT" ("Exit reparse" is not needed with this):

```yaml
substitutions:

###### CHANGE ME START ######

  device_name: "nspanel_kitchen" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  #nextion_update_url: "http://homeassistant.local:8123/local/nspanel_us.tft"
  nextion_update_url: "http://homeassistant.local:8123/local/nspanel_blank.tft"

##### CHANGE ME END #####

###### USE THIS ONLY FOR YOUR FIRST TFT UPLOAD, ONCE IT WORKED, REMOVE THESE LINES ######
external_components:
  - source: github://pr#2956
    components: [nextion]
    refresh: 1h
###############################################################################


##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####
```
