### ISSUE TITLE
ERROR Error sending data: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by techunleadit** [Blackymas/NSPanel_HA_Blueprint#820]
Hi everyone, I hope to find someone who can help me with this problem because I didn't find anything useful on ESPHome and neither on the developer's GitHub.
Premise, I have a SonOff NSPanel purchased on Amazon (https://www.amazon.it/NSPanel-US-switch-Temperature-touchscreen-bidirectional/dp/B09MRZQCN2).
It works great and was integrated using Blackymas project (https://github.com/Blackymas/NSPanel_HA_Blueprint) flashing as per guide (https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(EN)-First -Steps---Installation-and-Setup).
Now I have to upgrade the 12 NSPanels I have around the house from version 2023.3.2 to 2023.4.4.
I wanted to update via WiFi so as to avoid having to disconnect them and update them via USB, unfortunately I can't update and this is what the log shows me.

```
INFO Reading configuration /config/esphome/nsguestbathroom.yaml...
WARNING GPIO4 is a Strapping PIN and should be avoided.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
INFO Generating C++ source...
INFO Compiling app...
Processing nsguestbathroom (board: esp32dev; framework: arduino; platform: platformio/espressif32 @ 5.3.0)
-------------------------------------------------- ------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
  - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
Dependency Graph
|-- AsyncTCP-esphome @ 1.2.2
|-- Wi-Fi @ 2.0.0
|--FS @ 2.0.0
|-- Update @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 2.1.0
| |-- AsyncTCP-esphome @ 1.2.2
|-- DNSServer @ 2.0.0
|-- ESPmDNS @ 2.0.0
|-- ArduinoJson @ 6.18.5
|--WiFiClientSecure @ 2.0.0
|-- HTTPClient @ 2.0.0
Compiling /data/nsguestbathroom/.pioenvs/nsguestbathroom/src/main.cpp.o
Linking /data/nsguestbathroom/.pioenvs/nsguestbathroom/firmware.elf
RAM: [= ] 13.4% (used 44048 bytes from 327680 bytes)
Flash: [====== ] 63.4% (used 1163549 bytes from 1835008 bytes)
Building /data/nsguestbathroom/.pioenvs/nsguestbathroom/firmware.bin
Creating esp32 image...
Successfully created esp32 image.
esp32_create_combined_bin(["/data/nsguestbathroom/.pioenvs/nsguestbathroom/firmware.bin"], ["/data/nsguestbathroom/.pioenvs/nsguestbathroom/firmware.elf"])
Wrote 0x12d7b0 bytes to file /data/nsguestbathroom/.pioenvs/nsguestbathroom/firmware-factory.bin, ready to flash to offset 0x0
========================= [SUCCESS] Took 17.42 seconds ==================== ======
INFO Successfully compiled program.
INFO Resolving IP address of nsguestbathroom.local
INFO -> 192.168.4.67
INFO Uploading /data/nsguestbathroom/.pioenvs/nsguestbathroom/firmware.bin (1169328 bytes)
Uploading: [= ] 1%
ERROR Error sending data: [Errno 104] Connection reset by peer
```

The configuration is:
```
substitutions:

###### CHANGE ME START ######
  baud_rate: "9600"
  device_name: "nsguestbathroom" 
  wifi_ssid: "XXXX"
  wifi_password: "XXXX"

  nextion_update_url: "http://192.168.4.3:8123/local/nspanel_eu.tft" # URL to local tft File
#  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_us.tft" # URL to Github

##### CHANGE ME END #####



##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####
```

Anyone can help me? The network is Ubiquiti and is very stable
