### ISSUE TITLE
Unable to find referenced entities switch.nspanel_kitchen_relay_1_local_fallback

### ISSUE THREAD

**Issue by jamieFL** [Blackymas/NSPanel_HA_Blueprint#869]
```
Logger: homeassistant.helpers.service
Source: helpers/service.py:770
First occurred: 18:39:10 (2 occurrences)
Last logged: 18:39:10

Unable to find referenced entities switch.nspanel_kitchen_relay_1_local_fallback or it is/they are currently not available
Unable to find referenced entities switch.nspanel_kitchen_relay_2_local_fallback or it is/they are currently not available
```

I keep getting the above error in my logs.  Below is the yaml for the blueprint.  Everything seems to work, but not sure what the above is or how to fix it.

```
alias: NSPanel Kitchen Wall Switch
description: ""
use_blueprint:
  path: Blackymas/nspanel_blueprint.yaml
  input:
    date_format: "%-m/%-d"
    outdoortemp: sensor.temperature_outdoor_temperature
    climate: climate.living_room_ac
    relay_1_local_fallback: true
    left_button_name: Ceiling Fan
    right_button_name: Island Lights
    hotwatercharge: switch.furnace
    qrcode_label: xxxxx
    qrcode_value: xxxxx
    qrcode_enabled: true
    nspanel_name: bb4918ddbe0418d7ee7c427ccad6a930
    button_page01_label: Kitchen
    entity01: switch.kitchen_lights
    entity01_name: Ceiling Lights
    entity01_icon: mdi:light-recessed
    entity02_name: Island Lights
    entity02_icon: mdi:ceiling-light-multiple-outline
    entity03: switch.dinette_slide_light
    entity03_name: Dinette Lights
    entity03_icon: mdi:led-strip-variant
    entity04: switch.appliance_slide_lights
    entity04_name: Appliance Lights
    entity04_icon: mdi:led-strip-variant
    button_page02_label: Living Room
    entity09: switch.livingroom_lights
    entity09_name: Ceiling Lights
    entity09_icon: mdi:light-recessed
    entity10: switch.living_room_port_slide_light
    entity10_name: Port Lights
    entity10_icon: mdi:led-strip-variant
    entity11: switch.living_room_starboard_slide_lite
    entity11_name: Starboard Lights
    entity11_icon: mdi:led-strip-variant
    entity05: switch.cabinet_lights
    entity05_name: Cabinet Lights
    entity05_icon: mdi:light-recessed
    delay: 5
    entitypages_enabled: false
    hotwatertemp: sensor.broadlink_remote_temperature
    weather_entity: weather.kocf_daynight
    indoortemp: sensor.ac_living_room_thermometer_temperature
    entity02: switch.island_lights
    left_button_entity: switch.nspanel_ceiling_fan
    right_button_entity: switch.island_lights
```
