### ISSUE TITLE
Automatition uses an unknown service

### ISSUE THREAD

**Issue by juapem** [Blackymas/NSPanel_HA_Blueprint#888]
Hi there,

After installing esphome in the panel sucesfully when I create the automatition I start receiving error messages like:

_as an action that calls an unknown service: esphome. #####_send_command_font_color_

same with:

_send_command_text_printf_

And the panel keeps initializing in  "Please wait" mode

TFT version 3.4
ESPhome version 2023.6.0
HA: 2023.6.2
Blueprint: v.3.4

**Comment by edwardtfn** [comment]
1. Which version of ESPHome is shown on your panel's screen?
2. Have you renamed your panel recently?
3. From which version of this project have you updated?
4. Have you tried removing your device related to this panel from Home Assistant and then adding it again? This under Settings > Devices and Services > ESPHome.
5. Have you checked your automation related to this biueprint if the panel selection is correct?
6. Could you please share your ESPHome yaml used to set this panel? Please remove any sensitive info.

**Comment by juapem** [comment]
Hi in the panel I have:

1. ESPHome 3.4
2. The panel was just setup.
3. Blueprint: v.3.4
4. Yes I have tried
5. Ys I have checked it
6. I can share it
7. Yes I have tried restarting

**Comment by juapem** [comment]
esphome:
  name: panelabajo
  friendly_name: panelabajo

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "##############"

ota:
  password: "###############"



substitutions:

###### CHANGE ME START ######

  device_name: "panelabajo" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  nextion_update_url: "http://192.168.0.##:8123/local/nspanel_us.tft" # URL to local tft File
  #  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_us.tft" # URL to Github
##### CHANGE ME END #####



##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####

**Comment by edwardtfn** [comment]
You shouldn't use a `friendly_name` in your settings as this will cause the name to be duplicated and will result exactly on the problem you described.

I would suggest to remove the device from your HA, then use something like this to flash again:

```yaml
# your customizations - advanced mode
api:
  encryption:
    key: "##############"

ota:
  password: "###############"

# end of your customizations


substitutions:

###### CHANGE ME START ######

  device_name: "panelabajo" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  nextion_update_url: "http://192.168.0.##:8123/local/nspanel_us.tft" # URL to local tft File
  #  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel_us.tft" # URL to Github
##### CHANGE ME END #####



##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####

```

The other sections are not needed.
