### ISSUE TITLE
Use send_command_printf to load an entity page.

### ISSUE THREAD

**Issue by snoopsbne** [Blackymas/NSPanel_HA_Blueprint#899]
Hopefully i did not miss this in the docs anywhere but I would like to be able to load an entity page directly (not a button page). 

For example:
  - service: esphome.nspanel_send_command_printf
    data:
      cmd: page page.light
      entity_id: light.somerandomlightentity

Cheers

**Comment by edwardtfn** [comment]
We are changing this in the next release to make it a bit easier, but for now (v3.4), I would suggest the following:
1. Go to your panel and open the detailed light page for your light
2. Go to your panel's device page (Settings > Devices and Services > ESPHome) and copy the content of the sensor named "Settings entity". It should be a json-like string with info for constructing that page.
3. Call the service `esphome.xxxxx_set_settings_entity` with that json-like string on the parameter `entity`

**Comment by edwardtfn** [comment]
This service call is being replaced.
On v4.0 (currently in `beta`), you will have to use `esphome.xxxxx_open_entity_settings_page` instead.

Something like this:

```yaml
service: esphome.xxxxx_open_entity_settings_page
data:
  page: climate
  page_label: My thermostat
  page_icon: ""
  page_icon_color: [229, 42, 34] 
  entity: climate.my_thermostat
  back_page: home
```
