### ISSUE TITLE
`Feature request` Climate with dual setpoints

### ISSUE THREAD

**Issue by roblamoreaux** [Blackymas/NSPanel_HA_Blueprint#909]
My heatpump thermostat does not use temperature, instead is uses target_temp_low and target_temp_high for the setpoints. 
On the climate page it would be nice to have the setpoints, since currently it has nothing.

In particular the attributes of my climate device are:
```yaml
hvac_modes:
  - 'off'
  - auto
  - heat_cool
  - heat
  - cool
min_temp: 55
max_temp: 99
target_temp_step: 1
min_humidity: 35
max_humidity: 65
fan_modes:
  - Auto
  - 'On'
  - Circulate
preset_modes:
  - None
  - Home
  - Away
  - Sleep
current_temperature: 72
temperature: null
target_temp_high: 72
target_temp_low: 69
current_humidity: 50
humidity: 50
fan_mode: 'On'
hvac_action: cooling
preset_mode: None
aux_heat: 'off'
dehumidify_setpoint: 50
humidify_setpoint: 45
attribution: Data provided by Trane Technologies
friendly_name: Thermostat NativeZone
supported_features: 95
```
