### ISSUE TITLE
ERROR Error auth result on uploading firmware.bin

### ISSUE THREAD

**Issue by stingone** [Blackymas/NSPanel_HA_Blueprint#92]
On uploading the bin file it throws me the error:

```
INFO Uploading /data/nspanel/.pioenvs/nspanel/firmware.bin (1265840 bytes)
ERROR Error auth result: Error: Authentication invalid. Is the password correct?
```

**Comment by stingone** [comment]
got it working. the device is listed in home assistant with its entities however the tft file is somehow not loading. the old UI is still showing and even when change the blueprint option everything on the screen shows 0.

**Comment by Blackymas** [comment]
Did you already have my version running or is this the first time you are installing it?

If you have already installed the version please use the new esphome version and reflash the nspanel again.

We had made a change in the OTA that can now cause problems for you if you had installed the major version 2.0.0

**Comment by stingone** [comment]
> Did you already have my version running or is this the first time you are installing it?
> 
> If you have already installed the version please use the new esphome version and reflash the nspanel again.
> 
> We had made a change in the OTA that can now cause problems for you if you had installed the major version 2.0.0
> 
> Please also delete the device itself and add it new in HA

Done all that and i was able to upload it succesfully. The devices as said is listed in ESPHOME, online and added to the devices under integration together with the blueprint. The settings e.g. brightness is working and the internal temp. but thats it.

no matter what i try the screen with the new UI is not showing date,time or anything reflecting the bluerprint after running the tft update based on the blueprint. even the relays are now showing change of state.

**Comment by Blackymas** [comment]
Nextion Queue is empty is not wrong - I have this message too

Can you please share the automation yaml file and please see if you have 2 last clicks would then look like this

"sensor. NAME_last_click_2"

When you start the NSPanel, pls wait appears in red letters?

You can also go directly to the automation and then to Trace.

Search there for the timestamp. The automation should go to the first branch - please make a screenshot of it.

what we need you can also read here
https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(DE)-HowTo-%7C-Alle-wichtigen-Dinge-die-man-wissen-sollte

**Comment by stingone** [comment]
> Nextion Queue is empty is not wrong - I have this message too
> 
> 1. Can you please share the automation yaml file and es-home file.
> 2. Please check if you have 2 last clicks would then look like this "sensor. NAME_last_click_2"
> 3. When you start the NSPanel, pls wait appears in red letters?
> 4. You can also go directly to the automation and then to Trace. Search there for the timestamp. The automation should go to the first branch - please make a screenshot of it.
> 
> what we need you can also read here https://github.com/Blackymas/NSPanel_HA_Blueprint/wiki/(DE)-HowTo-%7C-Alle-wichtigen-Dinge-die-man-wissen-sollte
> 
> Currently it is not clear the cause of your problem is

1.  The automation in YAML:
  ```
   alias: NSPanel Configuration
description: ""
use_blueprint:
  path: Blackymas/nspanel_blueprint.yaml
  input:
    weather: AccuWeather
    nspanel_name: sonoff-nspanel
    language: EN
    sync_value_ha: select_yes
    sync_slider_ha: select_yes
    outdoortemp: sensor.buienradar_temperature
    heatingsystemflame: []
    climate: climate.airco_overloop
    humidity: sensor.buienradar_humidity
    accuweather: krulzoom_32
    left_button_entity: light.dimmer_hal
    left_button_name: Verlichting Hal

```
ESPhome YAML - Device is online
```
substitutions:

###### CHANGE ME ######

  device_name: "sonoff-nspanel" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

##### CHANGE ME #####



##### DO NOT CHANGE ANYTHING! #####

  nextion_update_url: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/nspanel.tft"
packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####
```

2. I have the following sensor : sensor.sonoff_nspanel_last_click. not with the 2 on the end.

3.  3. When i start the NSPanel, pls wait does NOT appair in red letters? only the blue initialize screen for 2 sec.

4. see the snip of the trace. [https://snipboard.io/tVUGa3.jpg](url)
