### ISSUE TITLE
notification icon won't disapear

### ISSUE THREAD

**Issue by bkbartk** [Blackymas/NSPanel_HA_Blueprint#937]
Hello,

I'm struggling with an issue
After I send a notification like this
```
service: esphome.myswitch_notification_show
data:
  label: xx
  text: xx
```

and then wait for the homepage to be shown again, I see a notification icon.
when I click it, I see the message again.
and when I hit the green button the home screen shows including the notification icon.
but now I cannot click it anymore.

also at this point the clear service won't work anymore
```
service: esphome.myswitch_notification_clear
data: {}
```
the clear service only works if I haven't tried to click the green button yet
