### ISSUE TITLE
Feature request: Deep sleep / Wifi off

### ISSUE THREAD

**Issue by OlwinFroon** [Blackymas/NSPanel_HA_Blueprint#955]
I tend to kill the Wifi over night, all Wifi devices shut down at 23:00.

I'd like to see that here, too: 
- deep sleep / wifi off on demand, at a specific time or inactivity
- wake up on touch, click or specific time

**Comment by edwardtfn** [comment]
What do you mean by deep sleep? Should the hardware buttons and relay still working (so just the screen will be sleeping) or do you mean the entire system sleeping?

Will a wake-up by hardware button press be enough or you want touch screen wake up?

**Comment by OlwinFroon** [comment]
TBH I didn't look into the depths of the code. But then, I'm not exactly inclined to go McGyver anyway :)
I'm happy enough that I managed to get this thing flashed and running. Awesome stuff, by the way!

Deep sleep is probably not the correct term, my focus here is that the device should turn off WiFi during the night.
Anything else would be a plus.

**Comment by edwardtfn** [comment]
Adding this to your yaml will probabdo the trick, however, as wifi is needed for HA API and the communication to the Blueprint, I have no idea how useful will be your panel dorung the time it will be off (maybe a deep sleep could make sense in this case):

```yaml
time:
  - platform: homeassistant
    on_time:
      # Turn off wifi at midnight
      - hours: 0
        minutes: 0
        seconds: 0
        then:
          - wifi.disable:

      # Turn on wifi at 6AM
      - hours: 6
        minutes: 0
        seconds: 0
        then:
          - wifi.enable:
```

https://esphome.io/components/wifi.html#wifi-disable-action

**Comment by OlwinFroon** [comment]
Thanks, I´ll give that a try!

Possibly not the perfect solution, but I'll be good enough if it works and the panel can digest pulling the Wifi plug.

In any case, I´m not too concerned about the functionality while I´m asleep :)

**Comment by edwardtfn** [comment]
> In any case, I´m not too concerned about the functionality while I´m asleep :)

Yeah. Depending on how you use your panel, I understand you.
Some people uses the panel to turn lights on/off and in that case they probably want the panel working all the time, even when wifi is unavailable. In the coming version we are trying to implement a local controlled climate entity, so in that case also it should work without Wi-Fi.
But if you are using only as a display, you probably don't need that while you are sleeping.

**Comment by OlwinFroon** [comment]
Exactly. 

Unless I'm not sleeping, hence the original question:

How to send the unit into deep sleep (= no wifi, as little power as possible) within a fixed time frame while still being able to wake it up by interacting with it (button, swipe).

BTW: I just tested the timer controlled wifi on/off thingy.
I set it to disable Wifi 20 minutes ago and re-enable it 10 minutes ago.
Worked like a charm, 

While offline, the panel did not update the clock on the main screen. 
That gave me a bit of a start until it dawned to me that it gets the time to display from HA.
So ... kinda obvious-ish. At least understandable.

Not so obvious: The Wifi icon didn't turn off either. 

I'll give it another go and switch it off for an hour, to see if there are watchdogs trying to reconnect or even reboot the panel.

**Comment by OlwinFroon** [comment]
It rebooted and went online after 15 minutes :(

**Comment by OlwinFroon** [comment]
Eureka :)

That worked perfectly, it went off for the planned 30 minutes and then rebooted again.

Thanks for the inspiration!

Now to find out how to wake it up manually ...

**Comment by edwardtfn** [comment]
> While offline, the panel did not update the clock on the main screen.
> That gave me a bit of a start until it dawned to me that it gets the time to display from HA.
> So ... kinda obvious-ish. At least understandable.

Currently the clock is set by the Blueprint (in Home Assistant), so it requires the Wi-Fi connection to work. This will change in the coming version where the clock will be in ESPHome and therefore will keep being update when the Wi-Fi is off.

> Not so obvious: The Wifi icon didn't turn off either.

That mechanism was also rebuilt with the coming version and I believe it will update much faster when the Wi-Fi is disconnected. We have to test.

> Now to find out how to wake it up manually ...

If you are not using any of the panel's buttons, you can use those to wake up the panel from deep sleep. This should work.

**Comment by edwardtfn** [comment]
Are you fine if I add this to the docs of "customizations"?
Also, are you ok if I close this issue?

**Comment by OlwinFroon** [comment]
Right.
Sure, go ahead.

**Comment by edwardtfn** [comment]
Hey @OlwinFroon,

Just for information, this customization failed the tests for ESPHome 2023.12 beta 1. I will wait for beta 2 to see if this persists and if that is the case I would suggest looking for an alternative.
The problem is using pin 14 or 27 both to wake-up from deep sleep and also for controlling the panel when awake. This is generating an error at building phase saying the pin is being double assigned.

**Comment by OlwinFroon** [comment]
D: how unfortunate

New versions are supposed to improve things, not break working ones.

**Comment by edwardtfn** [comment]
But still beta... Beta tests are there to find those things.
😉

**Comment by edwardtfn** [comment]
So, looks like there is a working around, but this won't work for 2023.11.6, I think.

```yaml
# Define the wake-up button. Use pin 14 for left button or pin 27 for right button
deep_sleep:
  wakeup_pin:
    number: 14
    allow_other_uses: true
  wakeup_pin_mode: INVERT_WAKEUP
binary_sensor:
  - id: !extend left_button
    pin:
      allow_other_uses: true
```
