### ISSUE TITLE
Feature Request: Possibility to change NSPanel hardware switch to NSPanel hardware button

### ISSUE THREAD

**Issue by DerBo19** [Blackymas/NSPanel_HA_Blueprint#969]
Hi,

like in my Q&A with Edward told, i would request to implement the possibility to change the behaviour of the Hardware switches on the panel to real buttons. Edward allready designed a workaround for this, but maybe it is possible to implement this as a permanent feature. I think nobody would be bothered about this possibility but a bunch of people would benefit from this, since you then can operate with the buttons analog and control shutters etc. You could use a simple True/False as you did on "climate control optimistic mode" in the blueprint. 

Maybe its even possible to change the enities from the NSPanel in HA then either you want Switch or Button-Mode.

thanks a lot for all your work and effort you put in this fantastic project. I´m about  to install 10-12 Panels in my new house we´re building at the moment!

**Comment by edwardtfn** [comment]
I've commented also on #968, but I was thinking more about this and I believe I have a simpler solution using customization on your ESPHome yaml like this:

```yaml
substitutions:

###### CHANGE ME START ######

  device_name: "YOUR NSPANEL_NAME" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: "http://homeassistant.local:8123/local/nspanel_eu.tft"

##### CHANGE ME END #####



##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####


##### MY CUSTOMIZATIONS - START #####
binary_sensor:
  - id: !extend left_button
    on_click:
      then:
    on_press:
      then:
        switch.turn_on: relay_1
    on_release:
        switch.turn_off: relay_1

  - id: !extend right_button
    on_click:
      then:
    on_press:
      then:
        switch.turn_on: relay_2
    on_release:
        switch.turn_off: relay_2
##### MY CUSTOMIZATIONS - END #####
```

This will work even when Wi-Fi is out and will survive to upgrades to this project (unless we change the internal ID of this component, which is very unlikely).
